/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0021M_TBL.sql
-- 物理名：ED0021M_TBL
-- 論理名：満期契約抽出条件マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0021M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0021M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,JIGYO_SEGMENT_CD  CHAR(3) NOT NULL --「事業セグメントコード」
	,SHOHIN_SERVICE_SHUBETSU_CD  CHAR(3) NOT NULL --「商品サービス種別コード」
	,MNK_KIYK_CHSHTS_KJMB_KBN  CHAR(1) NOT NULL --「満期契約抽出基準日区分」
	,MNK_KIYK_CHSHTS_TSUKISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「満期契約抽出月数」
	,TSUKIZENGO_KBN  CHAR(1) NOT NULL --「月前後区分」
	,MANKI_KEIYAKU_CHUSHUTSU_BIKO  VARCHAR2(30) --「満期契約抽出備考」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0021M_PK PRIMARY KEY(
	 SHOHIN_SERVICE_CD
	,  KAISHA_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0021M_TBL IS '満期契約抽出条件マスタ'
/

COMMENT ON COLUMN ED0021M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0021M_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED0021M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED0021M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED0021M_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED0021M_TBL.SHOHIN_SERVICE_SHUBETSU_CD IS '商品サービス種別コード'
/
COMMENT ON COLUMN ED0021M_TBL.MNK_KIYK_CHSHTS_KJMB_KBN IS '満期契約抽出基準日区分'
/
COMMENT ON COLUMN ED0021M_TBL.MNK_KIYK_CHSHTS_TSUKISU IS '満期契約抽出月数'
/
COMMENT ON COLUMN ED0021M_TBL.TSUKIZENGO_KBN IS '月前後区分'
/
COMMENT ON COLUMN ED0021M_TBL.MANKI_KEIYAKU_CHUSHUTSU_BIKO IS '満期契約抽出備考'
/
COMMENT ON COLUMN ED0021M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0021M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0021M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0021M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0021M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0021M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0021M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0021M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0021M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0021M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0021M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0021M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
