/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0027W_TBL.sql
-- 物理名：ED0027W_TBL
-- 論理名：案件一括ＣＳＶ取込ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0027W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0027W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) NOT NULL --「一括取込用社員番号」
	,ANKEN_IKKATSU_CSV_TORIKOMI_SN  CHAR(14) NOT NULL --「案件一括ＣＳＶ取込連番」
	,ANKN_IKKTS_CSV_FILE_SHBTS_KBN  CHAR(1) NOT NULL --「案件一括ＣＳＶファイル種別区分」
	,ANKEN_NO  CHAR(13) --「案件番号」
	,ANKEN_SHOHIN_SN  CHAR(3) --「案件商品連番」
	,ANKEN_TAISHOSAKI_SN  CHAR(7) --「案件対象先連番」
	,ANKEN_NM  VARCHAR2(100) --「案件名称」
	,ANKEN_SHUBETSU_KBN  CHAR(1) NOT NULL --「案件種別区分」
	,SHODAN_KEIKI_KBN  CHAR(2) NOT NULL --「商談契機区分」
	,JUYO_ANKEN_TAISHO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「重要案件対象フラグ」
	,SESSHO_KAISHI_YMD  DATE --「折衝開始年月日」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,ANKEN_MAIN_TANTOSHA_SHAIN_NO  VARCHAR2(8) --「案件メイン担当者社員番号」
	,ANKEN_TORIHIKISAKI_CD  CHAR(9) --「案件取引先コード」
	,TDB_KIGYO_CD  CHAR(9) --「ＴＤＢ企業コード」
	,ANKN_TRHKSK_SISHK_NM  VARCHAR2(50) --「案件取引先正式名称」
	,KOJIN_HOJIN_KBN  CHAR(1) --「個人法人区分」
	,ANKEN_TORIHIKISAKI_DENWA_NO  VARCHAR2(20) --「案件取引先電話番号」
	,ANKEN_TORIHIKISAKI_JUSHO_CD  CHAR(11) --「案件取引先住所コード」
	,ANKEN_TORIHIKISAKI_YUBIN_NO  CHAR(7) --「案件取引先郵便番号」
	,ANKEN_TORIHIKISAKI_BANCHI  VARCHAR2(50) --「案件取引先番地」
	,ANKEN_TORIHIKISAKI_TATEMONO_NM  VARCHAR2(50) --「案件取引先建物名称」
	,ANKEN_TORIHIKISAKI_BUSHO_CD  CHAR(4) --「案件取引先部署コード」
	,ANKEN_TORIHIKISAKI_BUSHO_NM  VARCHAR2(40) --「案件取引先部署名称」
	,TARGET_LIST_CD  CHAR(11) --「ターゲットリストコード」
	,HONSHA_SHIEN_CD  CHAR(11) --「本社支援コード」
	,SHOHIN_SERVICE_SHUBETSU_CD  CHAR(3) --「商品サービス種別コード」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,KARITAISHOSAKI_NM  VARCHAR2(40) --「仮対象先名称」
	,KARITAISHOSAKI_JUSHO_CD  CHAR(11) --「仮対象先住所コード」
	,KARITAISHOSAKI_BANCHI  VARCHAR2(50) --「仮対象先番地」
	,KARITAISHOSAKI_TATEMONO_NM  VARCHAR2(50) --「仮対象先建物名称」
	,KARITAISHOSAKI_YUBIN_NO  CHAR(7) --「仮対象先郵便番号」
	,JISSHI_JIGYOSHO_CD  CHAR(6) --「実施事業所コード」
	,JISSHI_JIGYOSHO_KETSUGO_NM  VARCHAR2(400) --「実施事業所結合名称」
	,SHOHIN_SERVICE_CD  CHAR(3) --「商品サービスコード」
	,KADO_NOHIN_KAIYAKU_KAITEI_YM  CHAR(6) --「稼働納品解約改定年月」
	,KEIYAKU_KIKAN_TSUKISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「契約期間月数」
	,ANKEN_GETSUGAKU_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「案件月額数量」
	,ANKEN_GETSUGAKU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「案件月額金額」
	,ANKEN_KAITEIGO_GETSUGAKU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「案件改定後月額金額」
	,ANKEN_BAIKYAKU_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「案件売却数量」
	,ANKEN_BAIKYAKU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「案件売却金額」
	,ANKEN_KOJI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「案件工事金額」
	,ANKEN_RINJI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「案件臨時金額」
	,ANKEN_HOKEN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「案件保険数量」
	,ANKEN_HOKEN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「案件保険金額」
	,SALES_STAGE_A_CD  CHAR(2) --「セールスステージＡコード」
	,SALES_STAGE_B_CD  CHAR(2) --「セールスステージＢコード」
	,JUCHU_KAKURITSU_KBN  CHAR(2) NOT NULL --「受注確率区分」
	,JUCHU_RIYU_KBN  CHAR(1) --「受注理由区分」
	,SHITCHU_RIYU_KBN  CHAR(1) --「失注理由区分」
	,HAKI_RIYU_KBN  CHAR(1) --「破棄理由区分」
	,JUCHU_RIYU_NAIYO  VARCHAR2(100) --「受注理由内容」
	,SHITCHU_RIYU_NAIYO  VARCHAR2(100) --「失注理由内容」
	,HAKI_RIYU_NAIYO  VARCHAR2(100) --「破棄理由内容」
	,TSH_JCH_KYG_TRHKSK_CD  CHAR(9) --「他社受注競合取引先コード」
	,TASHA_JUCHU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「他社受注金額」
	,SAIANKENKA_TSUCHI_YOTEI_YM  CHAR(6) --「再案件化通知予定年月」
	,SAIANKENKA_BUNRUI_KBN  CHAR(1) --「再案件化分類区分」
	,SAIANKENKA_BUNRUI_NAIYO  VARCHAR2(100) --「再案件化分類内容」
	,SHHN_SHBTS_CD_JFK_TRKAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「商品種別コード重複登録有フラグ」
	,ANKN_SHHN_SHBTS_CD_SKJAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「案件商品種別コード削除有フラグ」
	,ANKN_TISHSK_CD_SKJAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「案件対象先コード削除有フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0027W_PK PRIMARY KEY(
	 IKKATSU_TORIKOMIYO_SHAIN_NO
	,  ANKEN_IKKATSU_CSV_TORIKOMI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0027W_TBL IS '案件一括ＣＳＶ取込ワーク'
/

COMMENT ON COLUMN ED0027W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0027W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_IKKATSU_CSV_TORIKOMI_SN IS '案件一括ＣＳＶ取込連番'
/
COMMENT ON COLUMN ED0027W_TBL.ANKN_IKKTS_CSV_FILE_SHBTS_KBN IS '案件一括ＣＳＶファイル種別区分'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_NO IS '案件番号'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_SHOHIN_SN IS '案件商品連番'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_TAISHOSAKI_SN IS '案件対象先連番'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_NM IS '案件名称'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_SHUBETSU_KBN IS '案件種別区分'
/
COMMENT ON COLUMN ED0027W_TBL.SHODAN_KEIKI_KBN IS '商談契機区分'
/
COMMENT ON COLUMN ED0027W_TBL.JUYO_ANKEN_TAISHO_FLG IS '重要案件対象フラグ'
/
COMMENT ON COLUMN ED0027W_TBL.SESSHO_KAISHI_YMD IS '折衝開始年月日'
/
COMMENT ON COLUMN ED0027W_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_MAIN_TANTOSHA_SHAIN_NO IS '案件メイン担当者社員番号'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_TORIHIKISAKI_CD IS '案件取引先コード'
/
COMMENT ON COLUMN ED0027W_TBL.TDB_KIGYO_CD IS 'ＴＤＢ企業コード'
/
COMMENT ON COLUMN ED0027W_TBL.ANKN_TRHKSK_SISHK_NM IS '案件取引先正式名称'
/
COMMENT ON COLUMN ED0027W_TBL.KOJIN_HOJIN_KBN IS '個人法人区分'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_TORIHIKISAKI_DENWA_NO IS '案件取引先電話番号'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_TORIHIKISAKI_JUSHO_CD IS '案件取引先住所コード'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_TORIHIKISAKI_YUBIN_NO IS '案件取引先郵便番号'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_TORIHIKISAKI_BANCHI IS '案件取引先番地'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_TORIHIKISAKI_TATEMONO_NM IS '案件取引先建物名称'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_TORIHIKISAKI_BUSHO_CD IS '案件取引先部署コード'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_TORIHIKISAKI_BUSHO_NM IS '案件取引先部署名称'
/
COMMENT ON COLUMN ED0027W_TBL.TARGET_LIST_CD IS 'ターゲットリストコード'
/
COMMENT ON COLUMN ED0027W_TBL.HONSHA_SHIEN_CD IS '本社支援コード'
/
COMMENT ON COLUMN ED0027W_TBL.SHOHIN_SERVICE_SHUBETSU_CD IS '商品サービス種別コード'
/
COMMENT ON COLUMN ED0027W_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED0027W_TBL.KARITAISHOSAKI_NM IS '仮対象先名称'
/
COMMENT ON COLUMN ED0027W_TBL.KARITAISHOSAKI_JUSHO_CD IS '仮対象先住所コード'
/
COMMENT ON COLUMN ED0027W_TBL.KARITAISHOSAKI_BANCHI IS '仮対象先番地'
/
COMMENT ON COLUMN ED0027W_TBL.KARITAISHOSAKI_TATEMONO_NM IS '仮対象先建物名称'
/
COMMENT ON COLUMN ED0027W_TBL.KARITAISHOSAKI_YUBIN_NO IS '仮対象先郵便番号'
/
COMMENT ON COLUMN ED0027W_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED0027W_TBL.JISSHI_JIGYOSHO_KETSUGO_NM IS '実施事業所結合名称'
/
COMMENT ON COLUMN ED0027W_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED0027W_TBL.KADO_NOHIN_KAIYAKU_KAITEI_YM IS '稼働納品解約改定年月'
/
COMMENT ON COLUMN ED0027W_TBL.KEIYAKU_KIKAN_TSUKISU IS '契約期間月数'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_GETSUGAKU_SURYO IS '案件月額数量'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_GETSUGAKU_AMT IS '案件月額金額'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_KAITEIGO_GETSUGAKU_AMT IS '案件改定後月額金額'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_BAIKYAKU_SURYO IS '案件売却数量'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_BAIKYAKU_AMT IS '案件売却金額'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_KOJI_AMT IS '案件工事金額'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_RINJI_AMT IS '案件臨時金額'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_HOKEN_SURYO IS '案件保険数量'
/
COMMENT ON COLUMN ED0027W_TBL.ANKEN_HOKEN_AMT IS '案件保険金額'
/
COMMENT ON COLUMN ED0027W_TBL.SALES_STAGE_A_CD IS 'セールスステージＡコード'
/
COMMENT ON COLUMN ED0027W_TBL.SALES_STAGE_B_CD IS 'セールスステージＢコード'
/
COMMENT ON COLUMN ED0027W_TBL.JUCHU_KAKURITSU_KBN IS '受注確率区分'
/
COMMENT ON COLUMN ED0027W_TBL.JUCHU_RIYU_KBN IS '受注理由区分'
/
COMMENT ON COLUMN ED0027W_TBL.SHITCHU_RIYU_KBN IS '失注理由区分'
/
COMMENT ON COLUMN ED0027W_TBL.HAKI_RIYU_KBN IS '破棄理由区分'
/
COMMENT ON COLUMN ED0027W_TBL.JUCHU_RIYU_NAIYO IS '受注理由内容'
/
COMMENT ON COLUMN ED0027W_TBL.SHITCHU_RIYU_NAIYO IS '失注理由内容'
/
COMMENT ON COLUMN ED0027W_TBL.HAKI_RIYU_NAIYO IS '破棄理由内容'
/
COMMENT ON COLUMN ED0027W_TBL.TSH_JCH_KYG_TRHKSK_CD IS '他社受注競合取引先コード'
/
COMMENT ON COLUMN ED0027W_TBL.TASHA_JUCHU_AMT IS '他社受注金額'
/
COMMENT ON COLUMN ED0027W_TBL.SAIANKENKA_TSUCHI_YOTEI_YM IS '再案件化通知予定年月'
/
COMMENT ON COLUMN ED0027W_TBL.SAIANKENKA_BUNRUI_KBN IS '再案件化分類区分'
/
COMMENT ON COLUMN ED0027W_TBL.SAIANKENKA_BUNRUI_NAIYO IS '再案件化分類内容'
/
COMMENT ON COLUMN ED0027W_TBL.SHHN_SHBTS_CD_JFK_TRKAR_FLG IS '商品種別コード重複登録有フラグ'
/
COMMENT ON COLUMN ED0027W_TBL.ANKN_SHHN_SHBTS_CD_SKJAR_FLG IS '案件商品種別コード削除有フラグ'
/
COMMENT ON COLUMN ED0027W_TBL.ANKN_TISHSK_CD_SKJAR_FLG IS '案件対象先コード削除有フラグ'
/
COMMENT ON COLUMN ED0027W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0027W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0027W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0027W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0027W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0027W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0027W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0027W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0027W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0027W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0027W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0027W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
