/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0006T_TBL.sql
-- 物理名：ED0006T_TBL
-- 論理名：案件訪問先テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0006T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0006T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,ANKEN_NO  CHAR(13) NOT NULL --「案件番号」
	,ANKEN_HOMONSAKI_SN  CHAR(3) NOT NULL --「案件訪問先連番」
	,HOMONSAKI_BUSHO_NM  VARCHAR2(40) --「訪問先部署名称」
	,HOMONSAKI_YAKUSHOKU_NM  VARCHAR2(200) --「訪問先役職名称」
	,HOMONSAKI_TANTOSHA_NM  VARCHAR2(60) --「訪問先担当者氏名」
	,HOMONSAKI_YAKUWARI_KBN  CHAR(1) NOT NULL --「訪問先役割区分」
	,HOMONSAKI_BIKO  VARCHAR2(100) --「訪問先備考」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0006T_PK PRIMARY KEY(
	 ANKEN_NO
	,  ANKEN_HOMONSAKI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0006T_TBL IS '案件訪問先テーブル'
/

COMMENT ON COLUMN ED0006T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0006T_TBL.ANKEN_NO IS '案件番号'
/
COMMENT ON COLUMN ED0006T_TBL.ANKEN_HOMONSAKI_SN IS '案件訪問先連番'
/
COMMENT ON COLUMN ED0006T_TBL.HOMONSAKI_BUSHO_NM IS '訪問先部署名称'
/
COMMENT ON COLUMN ED0006T_TBL.HOMONSAKI_YAKUSHOKU_NM IS '訪問先役職名称'
/
COMMENT ON COLUMN ED0006T_TBL.HOMONSAKI_TANTOSHA_NM IS '訪問先担当者氏名'
/
COMMENT ON COLUMN ED0006T_TBL.HOMONSAKI_YAKUWARI_KBN IS '訪問先役割区分'
/
COMMENT ON COLUMN ED0006T_TBL.HOMONSAKI_BIKO IS '訪問先備考'
/
COMMENT ON COLUMN ED0006T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0006T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0006T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0006T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0006T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0006T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0006T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0006T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0006T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0006T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0006T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0006T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
