/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0024T_TBL.sql
-- 物理名：ED0024T_TBL
-- 論理名：ターゲットリスト地域本部別集計テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0024T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0024T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TARGET_LIST_CD  CHAR(11) NOT NULL --「ターゲットリストコード」
	,DAI_1_KAISO_EIGYO_SOSHIKI_CD  CHAR(6) NOT NULL --「第１階層営業組織コード」
	,TARGET_LIST_SHUKEI_KEKKA_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「ターゲットリスト集計結果件数」
	,JIZEN_JUMBI_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「事前準備件数」
	,APPROACH_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「アプローチ件数」
	,HEARING_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「ヒアリング件数」
	,PRESENTATION_CHOKI_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「プレゼンテーション長期件数」
	,PRESENTATION_CHOKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「プレゼンテーション長期金額」
	,PRESENTATION_TANKI_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「プレゼンテーション短期件数」
	,PRESENTATION_TANKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「プレゼンテーション短期金額」
	,CLOSING_CHOKI_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「クロージング長期件数」
	,CLOSING_CHOKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「クロージング長期金額」
	,CLOSING_TANKI_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「クロージング短期件数」
	,CLOSING_TANKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「クロージング短期金額」
	,JUCHU_CHOKI_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「受注長期件数」
	,JUCHU_CHOKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「受注長期金額」
	,JUCHU_TANKI_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「受注短期件数」
	,JUCHU_TANKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「受注短期金額」
	,SHITCHU_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「失注件数」
	,MIKOMI_NASHI_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「見込みなし件数」
	,HAKI_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「破棄件数」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0024T_PK PRIMARY KEY(
	 TARGET_LIST_CD
	,  DAI_1_KAISO_EIGYO_SOSHIKI_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0024T_TBL IS 'ターゲットリスト地域本部別集計テーブル'
/

COMMENT ON COLUMN ED0024T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0024T_TBL.TARGET_LIST_CD IS 'ターゲットリストコード'
/
COMMENT ON COLUMN ED0024T_TBL.DAI_1_KAISO_EIGYO_SOSHIKI_CD IS '第１階層営業組織コード'
/
COMMENT ON COLUMN ED0024T_TBL.TARGET_LIST_SHUKEI_KEKKA_KENSU IS 'ターゲットリスト集計結果件数'
/
COMMENT ON COLUMN ED0024T_TBL.JIZEN_JUMBI_KENSU IS '事前準備件数'
/
COMMENT ON COLUMN ED0024T_TBL.APPROACH_KENSU IS 'アプローチ件数'
/
COMMENT ON COLUMN ED0024T_TBL.HEARING_KENSU IS 'ヒアリング件数'
/
COMMENT ON COLUMN ED0024T_TBL.PRESENTATION_CHOKI_KENSU IS 'プレゼンテーション長期件数'
/
COMMENT ON COLUMN ED0024T_TBL.PRESENTATION_CHOKI_AMT IS 'プレゼンテーション長期金額'
/
COMMENT ON COLUMN ED0024T_TBL.PRESENTATION_TANKI_KENSU IS 'プレゼンテーション短期件数'
/
COMMENT ON COLUMN ED0024T_TBL.PRESENTATION_TANKI_AMT IS 'プレゼンテーション短期金額'
/
COMMENT ON COLUMN ED0024T_TBL.CLOSING_CHOKI_KENSU IS 'クロージング長期件数'
/
COMMENT ON COLUMN ED0024T_TBL.CLOSING_CHOKI_AMT IS 'クロージング長期金額'
/
COMMENT ON COLUMN ED0024T_TBL.CLOSING_TANKI_KENSU IS 'クロージング短期件数'
/
COMMENT ON COLUMN ED0024T_TBL.CLOSING_TANKI_AMT IS 'クロージング短期金額'
/
COMMENT ON COLUMN ED0024T_TBL.JUCHU_CHOKI_KENSU IS '受注長期件数'
/
COMMENT ON COLUMN ED0024T_TBL.JUCHU_CHOKI_AMT IS '受注長期金額'
/
COMMENT ON COLUMN ED0024T_TBL.JUCHU_TANKI_KENSU IS '受注短期件数'
/
COMMENT ON COLUMN ED0024T_TBL.JUCHU_TANKI_AMT IS '受注短期金額'
/
COMMENT ON COLUMN ED0024T_TBL.SHITCHU_KENSU IS '失注件数'
/
COMMENT ON COLUMN ED0024T_TBL.MIKOMI_NASHI_KENSU IS '見込みなし件数'
/
COMMENT ON COLUMN ED0024T_TBL.HAKI_KENSU IS '破棄件数'
/
COMMENT ON COLUMN ED0024T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0024T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0024T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0024T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0024T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0024T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0024T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0024T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0024T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0024T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0024T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0024T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
