/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0103T_TBL.sql
-- 物理名：ED0103T_TBL
-- 論理名：受注計画仮目標完了状況テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0103T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0103T_TBL (
	 KEIJO_TAISHO_NENDO  CHAR(4) NOT NULL --「計上対象年度」
	,KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,EIGYO_SOSHIKI_CD  CHAR(6) NOT NULL --「営業組織コード」
	,HONSHA_NYURYOKU_KANRYO_DT  TIMESTAMP --「本社入力完了日時」
	,CHIIKI_HOMBU_SHUSEI_KANRYO_DT  TIMESTAMP --「地域本部修正完了日時」
	,SHSH_EIGY_GROUP_NYRYK_KNRY_DT  TIMESTAMP --「支社営業グループ入力完了日時」
	,SHSH_EIGYIN_NYRYK_KNRY_DT  TIMESTAMP --「支社営業員入力完了日時」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0103T_PK PRIMARY KEY(
	 KEIJO_TAISHO_NENDO
	,  EIGYO_SOSHIKI_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0103T_TBL IS '受注計画仮目標完了状況テーブル'
/

COMMENT ON COLUMN ED0103T_TBL.KEIJO_TAISHO_NENDO IS '計上対象年度'
/
COMMENT ON COLUMN ED0103T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0103T_TBL.EIGYO_SOSHIKI_CD IS '営業組織コード'
/
COMMENT ON COLUMN ED0103T_TBL.HONSHA_NYURYOKU_KANRYO_DT IS '本社入力完了日時'
/
COMMENT ON COLUMN ED0103T_TBL.CHIIKI_HOMBU_SHUSEI_KANRYO_DT IS '地域本部修正完了日時'
/
COMMENT ON COLUMN ED0103T_TBL.SHSH_EIGY_GROUP_NYRYK_KNRY_DT IS '支社営業グループ入力完了日時'
/
COMMENT ON COLUMN ED0103T_TBL.SHSH_EIGYIN_NYRYK_KNRY_DT IS '支社営業員入力完了日時'
/
COMMENT ON COLUMN ED0103T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0103T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0103T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0103T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0103T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0103T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0103T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0103T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0103T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0103T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0103T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0103T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
