/* ---------------------------------------------------------------------- */
-- インデックス作成DDL(ORACLE用)
-- ファイル名：ED0148M_IDX.sql
-- 対象テーブル（物理名）：ED0148M_TBL
-- 対象テーブル（論理名）：営業組織マスタ
/* ---------------------------------------------------------------------- */

CREATE INDEX ED0148M_IDX01 ON ED0148M_TBL(
	EIGYO_SOSHIKI_CD,
	KAISHA_CD,
	EIGYO_SOSHIKI_KAISO_KBN,
	TEKIYO_KAISHI_YMD 
)
/

CREATE INDEX ED0148M_IDX02 ON ED0148M_TBL(
	DAI_1_KAISO_EIGYO_SOSHIKI_CD,
	DAI_2_KAISO_EIGYO_SOSHIKI_CD,
	DAI_3_KAISO_EIGYO_SOSHIKI_CD,
	DAI_4_KAISO_EIGYO_SOSHIKI_CD,
	DAI_5_KAISO_EIGYO_SOSHIKI_CD,
	DAI_6_KAISO_EIGYO_SOSHIKI_CD,
	DAI_7_KAISO_EIGYO_SOSHIKI_CD 
)
/

CREATE INDEX ED0148M_IDX03 ON ED0148M_TBL(
	TEKIYO_KAISHI_YMD,
	KAISHA_CD,
	DAI_1_KAISO_EIGYO_SOSHIKI_CD,
	DAI_2_KAISO_EIGYO_SOSHIKI_CD 
)
/
