/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0107T_TBL.sql
-- 物理名：ED0107T_TBL
-- 論理名：目標ＣＳＶ取込状況詳細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0107T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0107T_TBL (
	 KEIJO_TAISHO_NENDO  CHAR(4) NOT NULL --「計上対象年度」
	,KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,EIGY_MKHY_TISH_KIKK_KBN  CHAR(1) NOT NULL --「営業目標対象計画区分」
	,EIGYO_MOKUHYO_KBN  CHAR(1) NOT NULL --「営業目標区分」
	,EIGYO_SOSHIKI_CD  CHAR(6) NOT NULL --「営業組織コード」
	,MKHY_CSV_TRKM_JKY_SHSI_SN  CHAR(14) NOT NULL --「目標ＣＳＶ取込状況詳細連番」
	,CSV_TORIKOMI_SHOSAI_NAIYO  VARCHAR2(100) NOT NULL --「ＣＳＶ取込詳細内容」
	,CSV_TORIKOMI_ERROR_LEVEL_KBN  CHAR(1) NOT NULL --「ＣＳＶ取込エラーレベル区分」
	,CSV_TORIKOMI_ERROR_KASHOSU  NUMBER(9,0) --「ＣＳＶ取込エラー箇所数」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0107T_PK PRIMARY KEY(
	 KEIJO_TAISHO_NENDO
	,  EIGY_MKHY_TISH_KIKK_KBN
	,  EIGYO_MOKUHYO_KBN
	,  MKHY_CSV_TRKM_JKY_SHSI_SN
	,  EIGYO_SOSHIKI_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0107T_TBL IS '目標ＣＳＶ取込状況詳細テーブル'
/

COMMENT ON COLUMN ED0107T_TBL.KEIJO_TAISHO_NENDO IS '計上対象年度'
/
COMMENT ON COLUMN ED0107T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0107T_TBL.EIGY_MKHY_TISH_KIKK_KBN IS '営業目標対象計画区分'
/
COMMENT ON COLUMN ED0107T_TBL.EIGYO_MOKUHYO_KBN IS '営業目標区分'
/
COMMENT ON COLUMN ED0107T_TBL.EIGYO_SOSHIKI_CD IS '営業組織コード'
/
COMMENT ON COLUMN ED0107T_TBL.MKHY_CSV_TRKM_JKY_SHSI_SN IS '目標ＣＳＶ取込状況詳細連番'
/
COMMENT ON COLUMN ED0107T_TBL.CSV_TORIKOMI_SHOSAI_NAIYO IS 'ＣＳＶ取込詳細内容'
/
COMMENT ON COLUMN ED0107T_TBL.CSV_TORIKOMI_ERROR_LEVEL_KBN IS 'ＣＳＶ取込エラーレベル区分'
/
COMMENT ON COLUMN ED0107T_TBL.CSV_TORIKOMI_ERROR_KASHOSU IS 'ＣＳＶ取込エラー箇所数'
/
COMMENT ON COLUMN ED0107T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0107T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0107T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0107T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0107T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0107T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0107T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0107T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0107T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0107T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0107T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0107T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
