/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0302T_TBL.sql
-- 物理名：ED0302T_TBL
-- 論理名：営業行動予定テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0302T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0302T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,EIGYO_KODO_YOTEI_SHAIN_NO  VARCHAR2(8) NOT NULL --「営業行動予定社員番号」
	,EIGYO_KODO_YOTEI_NO  CHAR(13) NOT NULL --「営業行動予定番号」
	,YOTEI_BUNRUI_CD  CHAR(2) --「予定分類コード」
	,EIGYO_KODO_YOTEI_KAISHI_DT  TIMESTAMP --「営業行動予定開始日時」
	,EIGYO_KODO_YOTEI_SHURYO_DT  TIMESTAMP --「営業行動予定終了日時」
	,EIGYO_KODO_YOTEI_JIGYOSHO_CD  CHAR(6) --「営業行動予定事業所コード」
	,EIGYO_KODO_YOTEI_HOMON_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「営業行動予定訪問件数」
	,ANKEN_NO  CHAR(13) --「案件番号」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,EIGY_KD_YTI_TRHKSK_CD  CHAR(9) --「営業行動予定取引先コード」
	,EIGY_KD_YTI_TRHKSK_BSH_CD  CHAR(4) --「営業行動予定取引先部署コード」
	,SHOHIN_SERVICE_SHUBETSU_CD  CHAR(3) --「商品サービス種別コード」
	,JKI_EIGY_KD_YTI_KISH_DT  TIMESTAMP --「次回営業行動予定開始日時」
	,JKI_EIGY_KD_YTI_SHRY_DT  TIMESTAMP --「次回営業行動予定終了日時」
	,EIGYO_KODO_YOTEI_RENDOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「営業行動予定連動有フラグ」
	,JKI_EIGYO_KODO_YOTEI_NO  CHAR(13) --「次回営業行動予定番号」
	,EIGYO_KODO_YOTEI_MEMO_NAIYO  VARCHAR2(300) --「営業行動予定メモ内容」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0302T_PK PRIMARY KEY(
	 EIGYO_KODO_YOTEI_SHAIN_NO
	,  EIGYO_KODO_YOTEI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0302T_TBL IS '営業行動予定テーブル'
/

COMMENT ON COLUMN ED0302T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0302T_TBL.EIGYO_KODO_YOTEI_SHAIN_NO IS '営業行動予定社員番号'
/
COMMENT ON COLUMN ED0302T_TBL.EIGYO_KODO_YOTEI_NO IS '営業行動予定番号'
/
COMMENT ON COLUMN ED0302T_TBL.YOTEI_BUNRUI_CD IS '予定分類コード'
/
COMMENT ON COLUMN ED0302T_TBL.EIGYO_KODO_YOTEI_KAISHI_DT IS '営業行動予定開始日時'
/
COMMENT ON COLUMN ED0302T_TBL.EIGYO_KODO_YOTEI_SHURYO_DT IS '営業行動予定終了日時'
/
COMMENT ON COLUMN ED0302T_TBL.EIGYO_KODO_YOTEI_JIGYOSHO_CD IS '営業行動予定事業所コード'
/
COMMENT ON COLUMN ED0302T_TBL.EIGYO_KODO_YOTEI_HOMON_KENSU IS '営業行動予定訪問件数'
/
COMMENT ON COLUMN ED0302T_TBL.ANKEN_NO IS '案件番号'
/
COMMENT ON COLUMN ED0302T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0302T_TBL.EIGY_KD_YTI_TRHKSK_CD IS '営業行動予定取引先コード'
/
COMMENT ON COLUMN ED0302T_TBL.EIGY_KD_YTI_TRHKSK_BSH_CD IS '営業行動予定取引先部署コード'
/
COMMENT ON COLUMN ED0302T_TBL.SHOHIN_SERVICE_SHUBETSU_CD IS '商品サービス種別コード'
/
COMMENT ON COLUMN ED0302T_TBL.JKI_EIGY_KD_YTI_KISH_DT IS '次回営業行動予定開始日時'
/
COMMENT ON COLUMN ED0302T_TBL.JKI_EIGY_KD_YTI_SHRY_DT IS '次回営業行動予定終了日時'
/
COMMENT ON COLUMN ED0302T_TBL.EIGYO_KODO_YOTEI_RENDOARI_FLG IS '営業行動予定連動有フラグ'
/
COMMENT ON COLUMN ED0302T_TBL.JKI_EIGYO_KODO_YOTEI_NO IS '次回営業行動予定番号'
/
COMMENT ON COLUMN ED0302T_TBL.EIGYO_KODO_YOTEI_MEMO_NAIYO IS '営業行動予定メモ内容'
/
COMMENT ON COLUMN ED0302T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0302T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0302T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0302T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0302T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0302T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0302T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0302T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0302T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0302T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0302T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0302T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
