/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0452T_TBL.sql
-- 物理名：ED0452T_TBL
-- 論理名：要望苦情対応状況テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0452T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0452T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,YOBO_KUJO_UKETSUKE_NO  CHAR(12) NOT NULL --「要望苦情受付番号」
	,YOBO_KUJO_TAIO_SN  CHAR(3) NOT NULL --「要望苦情対応連番」
	,YOBO_KUJO_TAIO_JIGYOSHO_CD  CHAR(6) NOT NULL --「要望苦情対応事業所コード」
	,YOBO_KUJO_TAIO_SHAIN_NO  VARCHAR2(8) --「要望苦情対応社員番号」
	,YOBO_KUJO_TAIO_JOKYO_KBN  CHAR(1) NOT NULL --「要望苦情対応状況区分」
	,YOBO_KUJO_TAIO_NAIYO  VARCHAR2(300) --「要望苦情対応内容」
	,YOBO_KUJO_TAIO_DT  TIMESTAMP --「要望苦情対応日時」
	,YOBO_KUJO_JIKAI_TAIO_YOTEI_YMD  DATE --「要望苦情次回対応予定年月日」
	,YOBO_KUJO_TAIO_YOTEI_NAIYO_KBN  CHAR(1) NOT NULL --「要望苦情対応予定内容区分」
	,TOROKU_DT  TIMESTAMP --「登録日時」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0452T_PK PRIMARY KEY(
	 YOBO_KUJO_UKETSUKE_NO
	,  YOBO_KUJO_TAIO_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0452T_TBL IS '要望苦情対応状況テーブル'
/

COMMENT ON COLUMN ED0452T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0452T_TBL.YOBO_KUJO_UKETSUKE_NO IS '要望苦情受付番号'
/
COMMENT ON COLUMN ED0452T_TBL.YOBO_KUJO_TAIO_SN IS '要望苦情対応連番'
/
COMMENT ON COLUMN ED0452T_TBL.YOBO_KUJO_TAIO_JIGYOSHO_CD IS '要望苦情対応事業所コード'
/
COMMENT ON COLUMN ED0452T_TBL.YOBO_KUJO_TAIO_SHAIN_NO IS '要望苦情対応社員番号'
/
COMMENT ON COLUMN ED0452T_TBL.YOBO_KUJO_TAIO_JOKYO_KBN IS '要望苦情対応状況区分'
/
COMMENT ON COLUMN ED0452T_TBL.YOBO_KUJO_TAIO_NAIYO IS '要望苦情対応内容'
/
COMMENT ON COLUMN ED0452T_TBL.YOBO_KUJO_TAIO_DT IS '要望苦情対応日時'
/
COMMENT ON COLUMN ED0452T_TBL.YOBO_KUJO_JIKAI_TAIO_YOTEI_YMD IS '要望苦情次回対応予定年月日'
/
COMMENT ON COLUMN ED0452T_TBL.YOBO_KUJO_TAIO_YOTEI_NAIYO_KBN IS '要望苦情対応予定内容区分'
/
COMMENT ON COLUMN ED0452T_TBL.TOROKU_DT IS '登録日時'
/
COMMENT ON COLUMN ED0452T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0452T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0452T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0452T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0452T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0452T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0452T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0452T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0452T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0452T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0452T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0452T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
