/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0464W_TBL.sql
-- 物理名：ED0464W_TBL
-- 論理名：契約書未回収ポータル通知ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0464W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0464W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,EIGYO_SOSHIKI_KAISO_KBN  CHAR(1) NOT NULL --「営業組織階層区分」
	,PORTAL_TSCH_TISHSH_JGYSH_CD  CHAR(6) NOT NULL --「ポータル通知対象者事業所コード」
	,PORTAL_TSCH_TISHSH_SHIN_NO  VARCHAR2(8) NOT NULL --「ポータル通知対象者社員番号」
	,KEIYAKUSHO_MIKAISHU_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「契約書未回収件数」
	,GROUP_LEADER_FLG  CHAR(1) DEFAULT '0' NOT NULL --「グループリーダフラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0464W_PK PRIMARY KEY(
	 PORTAL_TSCH_TISHSH_JGYSH_CD
	,  PORTAL_TSCH_TISHSH_SHIN_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0464W_TBL IS '契約書未回収ポータル通知ワーク'
/

COMMENT ON COLUMN ED0464W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0464W_TBL.EIGYO_SOSHIKI_KAISO_KBN IS '営業組織階層区分'
/
COMMENT ON COLUMN ED0464W_TBL.PORTAL_TSCH_TISHSH_JGYSH_CD IS 'ポータル通知対象者事業所コード'
/
COMMENT ON COLUMN ED0464W_TBL.PORTAL_TSCH_TISHSH_SHIN_NO IS 'ポータル通知対象者社員番号'
/
COMMENT ON COLUMN ED0464W_TBL.KEIYAKUSHO_MIKAISHU_KENSU IS '契約書未回収件数'
/
COMMENT ON COLUMN ED0464W_TBL.GROUP_LEADER_FLG IS 'グループリーダフラグ'
/
COMMENT ON COLUMN ED0464W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0464W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0464W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0464W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0464W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0464W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0464W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0464W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0464W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0464W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0464W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0464W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
