/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0531T_TBL.sql
-- 物理名：ED0531T_TBL
-- 論理名：契約第三者支払テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0531T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0531T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIYAKU_ID  CHAR(18) NOT NULL --「契約ＩＤ」
	,DAISANSHA_SHIHARAI_SN  CHAR(14) NOT NULL --「第三者支払連番」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) --「請求先取引先コード」
	,SEIKYUSAKIBETSU_TEMPLATE_SN  CHAR(5) --「請求先別テンプレート連番」
	,SHIHARAI_JOKEN_KBN  CHAR(1) NOT NULL --「支払条件区分」
	,KOKYAKU_SHIHARAI_HOHO_KBN  CHAR(2) NOT NULL --「顧客支払方法区分」
	,SEIKYU_KEITAI_KBN  CHAR(2) NOT NULL --「請求形態区分」
	,SEIKYU_KUGIRI_M_KBN  CHAR(2) NOT NULL --「請求区切月区分」
	,DAISANSHA_FUTAN_KIGEN_YM  DATE --「第三者負担期限年月」
	,DAISANSHA_FUTAN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「第三者負担金額」
	,TEIJI_KAKAKU_SN  CHAR(14) --「提示価格連番」
	,TEIJI_KAKAKU_HIYO_KBN  CHAR(2) NOT NULL --「提示価格費用区分」
	,TEIJI_KAKAKU_KBN  CHAR(2) NOT NULL --「提示価格区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0531T_PK PRIMARY KEY(
	 KEIYAKU_ID
	,  DAISANSHA_SHIHARAI_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0531T_TBL IS '契約第三者支払テーブル'
/

COMMENT ON COLUMN ED0531T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0531T_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED0531T_TBL.DAISANSHA_SHIHARAI_SN IS '第三者支払連番'
/
COMMENT ON COLUMN ED0531T_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED0531T_TBL.SEIKYUSAKIBETSU_TEMPLATE_SN IS '請求先別テンプレート連番'
/
COMMENT ON COLUMN ED0531T_TBL.SHIHARAI_JOKEN_KBN IS '支払条件区分'
/
COMMENT ON COLUMN ED0531T_TBL.KOKYAKU_SHIHARAI_HOHO_KBN IS '顧客支払方法区分'
/
COMMENT ON COLUMN ED0531T_TBL.SEIKYU_KEITAI_KBN IS '請求形態区分'
/
COMMENT ON COLUMN ED0531T_TBL.SEIKYU_KUGIRI_M_KBN IS '請求区切月区分'
/
COMMENT ON COLUMN ED0531T_TBL.DAISANSHA_FUTAN_KIGEN_YM IS '第三者負担期限年月'
/
COMMENT ON COLUMN ED0531T_TBL.DAISANSHA_FUTAN_AMT IS '第三者負担金額'
/
COMMENT ON COLUMN ED0531T_TBL.TEIJI_KAKAKU_SN IS '提示価格連番'
/
COMMENT ON COLUMN ED0531T_TBL.TEIJI_KAKAKU_HIYO_KBN IS '提示価格費用区分'
/
COMMENT ON COLUMN ED0531T_TBL.TEIJI_KAKAKU_KBN IS '提示価格区分'
/
COMMENT ON COLUMN ED0531T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0531T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0531T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0531T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0531T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0531T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0531T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0531T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0531T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0531T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0531T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0531T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
