/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0525T_TBL.sql
-- 物理名：ED0525T_TBL
-- 論理名：受注ＧＳ保険テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0525T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0525T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,GS_HOKEN_KANYU_TYPE_CD  CHAR(4) --「ＧＳ保険加入タイプコード」
	,GS_SG_HKN_KIYKSHT_KISH_D  DATE --「ＧＳ総合保険契約書等回収日」
	,GS_SOGO_HOKEN_HOKENRYO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＧＳ総合保険保険料金額」
	,SOFU_SHIRYO_SOFUSAKI_KBN  CHAR(1) NOT NULL --「送付資料送付先区分」
	,YUBIN_NO  CHAR(7) --「郵便番号」
	,SOFU_SHIRYO_SOFUSAKI_JUSHO  VARCHAR2(60) --「送付資料送付先住所」
	,SOFU_SHIRYO_ATENA_NM  VARCHAR2(60) --「送付資料宛名氏名」
	,SOFU_SHIRYO_BIKO  VARCHAR2(100) --「送付資料備考」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0525T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0525T_TBL IS '受注ＧＳ保険テーブル'
/

COMMENT ON COLUMN ED0525T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0525T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0525T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0525T_TBL.GS_HOKEN_KANYU_TYPE_CD IS 'ＧＳ保険加入タイプコード'
/
COMMENT ON COLUMN ED0525T_TBL.GS_SG_HKN_KIYKSHT_KISH_D IS 'ＧＳ総合保険契約書等回収日'
/
COMMENT ON COLUMN ED0525T_TBL.GS_SOGO_HOKEN_HOKENRYO_AMT IS 'ＧＳ総合保険保険料金額'
/
COMMENT ON COLUMN ED0525T_TBL.SOFU_SHIRYO_SOFUSAKI_KBN IS '送付資料送付先区分'
/
COMMENT ON COLUMN ED0525T_TBL.YUBIN_NO IS '郵便番号'
/
COMMENT ON COLUMN ED0525T_TBL.SOFU_SHIRYO_SOFUSAKI_JUSHO IS '送付資料送付先住所'
/
COMMENT ON COLUMN ED0525T_TBL.SOFU_SHIRYO_ATENA_NM IS '送付資料宛名氏名'
/
COMMENT ON COLUMN ED0525T_TBL.SOFU_SHIRYO_BIKO IS '送付資料備考'
/
COMMENT ON COLUMN ED0525T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0525T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0525T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0525T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0525T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0525T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0525T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0525T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0525T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0525T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0525T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0525T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
