/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0541T_TBL.sql
-- 物理名：ED0541T_TBL
-- 論理名：契約警備先テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0541T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0541T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIYAKU_ID  CHAR(18) NOT NULL --「契約ＩＤ」
	,KEIBISAKI_TANTOSHA_BUSHO_NM  VARCHAR2(40) --「警備先担当者部署名称」
	,KEIBISAKI_TANTOSHA_NM  VARCHAR2(60) --「警備先担当者氏名」
	,KEIBISAKI_TANTOSHA_DENWA_NO  VARCHAR2(20) --「警備先担当者電話番号」
	,TATEMONO_KOZO_KBN  CHAR(1) NOT NULL --「建物構造区分」
	,TATEMONO_KOJI_SHUBETSU_KBN  CHAR(1) NOT NULL --「建物工事種別区分」
	,KEIBI_KUKAKUSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「警備区画数」
	,TTMN_SMP_MENSEKI_NYRYK_HH_KBN  CHAR(1) NOT NULL --「建物寸法面積入力方法区分」
	,TATEMONO_SUMPOTATE_M  NUMBER(12,3) DEFAULT '0' NOT NULL --「建物寸法縦メートル」
	,TATEMONO_SUMPOYOKO_M  NUMBER(12,3) DEFAULT '0' NOT NULL --「建物寸法横メートル」
	,TATEMONO_SUMPO_MENSEKI  NUMBER(12,3) DEFAULT '0' NOT NULL --「建物寸法面積」
	,TATEMONO_SUMPO_KUKAKUSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「建物寸法区画数」
	,TATEMONO_SUMPO_TAKASA_M  NUMBER(9,0) DEFAULT '0' NOT NULL --「建物寸法高さメートル」
	,KEIBI_TAISHO_MENSEKI  NUMBER(9,0) DEFAULT '0' NOT NULL --「警備対象面積」
	,KOJI_TAISHO_MENSEKI  NUMBER(9,0) DEFAULT '0' NOT NULL --「工事対象面積」
	,KEIBI_TAISHO_SHITSUSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「警備対象室数」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0541T_PK PRIMARY KEY(
	 KEIYAKU_ID
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0541T_TBL IS '契約警備先テーブル'
/

COMMENT ON COLUMN ED0541T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0541T_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED0541T_TBL.KEIBISAKI_TANTOSHA_BUSHO_NM IS '警備先担当者部署名称'
/
COMMENT ON COLUMN ED0541T_TBL.KEIBISAKI_TANTOSHA_NM IS '警備先担当者氏名'
/
COMMENT ON COLUMN ED0541T_TBL.KEIBISAKI_TANTOSHA_DENWA_NO IS '警備先担当者電話番号'
/
COMMENT ON COLUMN ED0541T_TBL.TATEMONO_KOZO_KBN IS '建物構造区分'
/
COMMENT ON COLUMN ED0541T_TBL.TATEMONO_KOJI_SHUBETSU_KBN IS '建物工事種別区分'
/
COMMENT ON COLUMN ED0541T_TBL.KEIBI_KUKAKUSU IS '警備区画数'
/
COMMENT ON COLUMN ED0541T_TBL.TTMN_SMP_MENSEKI_NYRYK_HH_KBN IS '建物寸法面積入力方法区分'
/
COMMENT ON COLUMN ED0541T_TBL.TATEMONO_SUMPOTATE_M IS '建物寸法縦メートル'
/
COMMENT ON COLUMN ED0541T_TBL.TATEMONO_SUMPOYOKO_M IS '建物寸法横メートル'
/
COMMENT ON COLUMN ED0541T_TBL.TATEMONO_SUMPO_MENSEKI IS '建物寸法面積'
/
COMMENT ON COLUMN ED0541T_TBL.TATEMONO_SUMPO_KUKAKUSU IS '建物寸法区画数'
/
COMMENT ON COLUMN ED0541T_TBL.TATEMONO_SUMPO_TAKASA_M IS '建物寸法高さメートル'
/
COMMENT ON COLUMN ED0541T_TBL.KEIBI_TAISHO_MENSEKI IS '警備対象面積'
/
COMMENT ON COLUMN ED0541T_TBL.KOJI_TAISHO_MENSEKI IS '工事対象面積'
/
COMMENT ON COLUMN ED0541T_TBL.KEIBI_TAISHO_SHITSUSU IS '警備対象室数'
/
COMMENT ON COLUMN ED0541T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0541T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0541T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0541T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0541T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0541T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0541T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0541T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0541T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0541T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0541T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0541T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
