/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0534M_TBL.sql
-- 物理名：ED0534M_TBL
-- 論理名：契約資料マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0534M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0534M_TBL (
	 SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,KEIYAKU_SHIRYO_NO  NUMBER(9,0) DEFAULT '0' NOT NULL --「契約資料番号」
	,KEIYAKU_SHIRYO_FILE_NM  VARCHAR2(255) --「契約資料ファイル名称」
	,KIYK_SHRY_FILE_SHKBTS_KEY  VARCHAR2(255) --「契約資料ファイル識別キー」
	,SHOMEIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「署名有フラグ」
	,DENSHI_SIGN_KAKUNIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「電子サイン確認フラグ」
	,KEIYAKU_KAKUNI_JIKI_KBN  CHAR(1) NOT NULL --「契約確認時期区分」
	,KEIYAKUSHO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「契約書フラグ」
	,KEIYAKUSHO_KAISHUYO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「契約書回収要フラグ」
	,KEIYAKUSHO_SOFUYO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「契約書送付要フラグ」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0534M_PK PRIMARY KEY(
	 SHOHIN_SERVICE_CD
	,  KEIYAKU_SHIRYO_NO
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0534M_TBL IS '契約資料マスタ'
/

COMMENT ON COLUMN ED0534M_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED0534M_TBL.KEIYAKU_SHIRYO_NO IS '契約資料番号'
/
COMMENT ON COLUMN ED0534M_TBL.KEIYAKU_SHIRYO_FILE_NM IS '契約資料ファイル名称'
/
COMMENT ON COLUMN ED0534M_TBL.KIYK_SHRY_FILE_SHKBTS_KEY IS '契約資料ファイル識別キー'
/
COMMENT ON COLUMN ED0534M_TBL.SHOMEIARI_FLG IS '署名有フラグ'
/
COMMENT ON COLUMN ED0534M_TBL.DENSHI_SIGN_KAKUNIN_FLG IS '電子サイン確認フラグ'
/
COMMENT ON COLUMN ED0534M_TBL.KEIYAKU_KAKUNI_JIKI_KBN IS '契約確認時期区分'
/
COMMENT ON COLUMN ED0534M_TBL.KEIYAKUSHO_FLG IS '契約書フラグ'
/
COMMENT ON COLUMN ED0534M_TBL.KEIYAKUSHO_KAISHUYO_FLG IS '契約書回収要フラグ'
/
COMMENT ON COLUMN ED0534M_TBL.KEIYAKUSHO_SOFUYO_FLG IS '契約書送付要フラグ'
/
COMMENT ON COLUMN ED0534M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED0534M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED0534M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0534M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0534M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0534M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0534M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0534M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0534M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0534M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0534M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0534M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0534M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0534M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
