/* ---------------------------------------------------------------------- */
-- インデックス作成DDL(ORACLE用)
-- ファイル名：ED0504T_IDX11.sql
-- 対象テーブル（物理名）：ED0504T_TBL
-- 対象テーブル（論理名）：契約テーブル
/* ---------------------------------------------------------------------- */

CREATE INDEX ED0504T_IDX11 ON ED0504T_TBL(
	KEIYAKU_JUCHU_TANTO_SHAIN_NO
)
/

CREATE INDEX ED0504T_IDX12 ON ED0504T_TBL(
	JUCHU_SHINSEI_NO
)
/

CREATE INDEX ED0504T_IDX13 ON ED0504T_TBL(
	KEIBI_SHINDAN_NO
)
/

CREATE INDEX ED0504T_IDX14 ON ED0504T_TBL(
	KIHON_KYOTSU_KEIYAKU_NO
)
/

CREATE INDEX ED0504T_IDX15 ON ED0504T_TBL(
	DENKEI_NO
)
/

CREATE INDEX ED0504T_IDX16 ON ED0504T_TBL(
	KEIYAKUSHO_NO
)
/

CREATE INDEX ED0504T_IDX17 ON ED0504T_TBL(
	GYOMU_KAISHI_YOTEI_YMD
)
/

CREATE INDEX ED0504T_IDX18 ON ED0504T_TBL(
	SEKISAN_KANRYO_DT,
	SEKISAN_KIYK_KANRI_KBN,
	JUCHU_JIGYOSHO_CD
)
/

CREATE INDEX ED0504T_IDX19 ON ED0504T_TBL(
	JUCHU_SHINSEI_DT,
	SEKISAN_KIYK_KANRI_KBN,
	JUCHU_JIGYOSHO_CD
)
/

CREATE INDEX ED0504T_IDX20 ON ED0504T_TBL(
	KAISHA_CD,
	KEIYAKU_ID,
	JUCHU_KEIYAKU_NO,
	JUCHU_KEIYAKU_HENKO_NO,
	SEKISAN_KIYK_KANRI_KBN,
	KEIYAKU_CHOKI_RINJI_KBN,
	KEIYAKU_KENSAKU_TAISHO_FLG
)
/
