/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0519T_TBL.sql
-- 物理名：ED0519T_TBL
-- 論理名：支払方法テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0519T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0519T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,SHIHARAI_HOHO_SN  CHAR(14) NOT NULL --「支払方法連番」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) --「請求先取引先コード」
	,SEIKYUSAKIBETSU_TEMPLATE_SN  CHAR(5) --「請求先別テンプレート連番」
	,TEKIYO_JOTAI_KBN  CHAR(1) NOT NULL --「適用状態区分」
	,SEIKYU_KEITAI_KBN  CHAR(2) NOT NULL --「請求形態区分」
	,SHIHARAI_JOKEN_KBN  CHAR(1) NOT NULL --「支払条件区分」
	,KOKYAKU_SHIHARAI_HOHO_KBN  CHAR(2) NOT NULL --「顧客支払方法区分」
	,SHIHARAI_D  CHAR(2) --「支払日」
	,SEIKYU_KIKAN_SHIME_D  CHAR(2) --「請求期間締日」
	,SEIKYU_KEITAI_KITEN_M  CHAR(2) --「請求形態起点月」
	,SEIKYU_HOHO_KBN  CHAR(1) NOT NULL --「請求方法区分」
	,BUNKATSU_KAISU_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「分割回数数量」
	,BUNKATSU_TESURYO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「分割手数料金額」
	,BUNKATSU_SHOKAI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「分割初回金額」
	,BUNKATSU_2_KAIME_IKO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「分割２回目以降金額」
	,SEIKYU_DAIKO_KANRI_NO  CHAR(13) --「請求代行管理番号」
	,DAISANSHA_SHIHARAI_SN  CHAR(14) --「第三者支払連番」
	,RONRI_SAKUJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「論理削除フラグ」
	,TKYME_JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「適用前受注契約変更番号」
	,TKYGO_JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「適用後受注契約変更番号」
	,KIYK_SIKY_DIK_IRISH_NO  CHAR(10) --「契約請求代行依頼書番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0519T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  SHIHARAI_HOHO_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0519T_TBL IS '支払方法テーブル'
/

COMMENT ON COLUMN ED0519T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0519T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0519T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0519T_TBL.SHIHARAI_HOHO_SN IS '支払方法連番'
/
COMMENT ON COLUMN ED0519T_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED0519T_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED0519T_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED0519T_TBL.SEIKYUSAKIBETSU_TEMPLATE_SN IS '請求先別テンプレート連番'
/
COMMENT ON COLUMN ED0519T_TBL.TEKIYO_JOTAI_KBN IS '適用状態区分'
/
COMMENT ON COLUMN ED0519T_TBL.SEIKYU_KEITAI_KBN IS '請求形態区分'
/
COMMENT ON COLUMN ED0519T_TBL.SHIHARAI_JOKEN_KBN IS '支払条件区分'
/
COMMENT ON COLUMN ED0519T_TBL.KOKYAKU_SHIHARAI_HOHO_KBN IS '顧客支払方法区分'
/
COMMENT ON COLUMN ED0519T_TBL.SHIHARAI_D IS '支払日'
/
COMMENT ON COLUMN ED0519T_TBL.SEIKYU_KIKAN_SHIME_D IS '請求期間締日'
/
COMMENT ON COLUMN ED0519T_TBL.SEIKYU_KEITAI_KITEN_M IS '請求形態起点月'
/
COMMENT ON COLUMN ED0519T_TBL.SEIKYU_HOHO_KBN IS '請求方法区分'
/
COMMENT ON COLUMN ED0519T_TBL.BUNKATSU_KAISU_SURYO IS '分割回数数量'
/
COMMENT ON COLUMN ED0519T_TBL.BUNKATSU_TESURYO_AMT IS '分割手数料金額'
/
COMMENT ON COLUMN ED0519T_TBL.BUNKATSU_SHOKAI_AMT IS '分割初回金額'
/
COMMENT ON COLUMN ED0519T_TBL.BUNKATSU_2_KAIME_IKO_AMT IS '分割２回目以降金額'
/
COMMENT ON COLUMN ED0519T_TBL.SEIKYU_DAIKO_KANRI_NO IS '請求代行管理番号'
/
COMMENT ON COLUMN ED0519T_TBL.DAISANSHA_SHIHARAI_SN IS '第三者支払連番'
/
COMMENT ON COLUMN ED0519T_TBL.RONRI_SAKUJO_FLG IS '論理削除フラグ'
/
COMMENT ON COLUMN ED0519T_TBL.TKYME_JUCHU_KEIYAKU_HENKO_NO IS '適用前受注契約変更番号'
/
COMMENT ON COLUMN ED0519T_TBL.TKYGO_JUCHU_KEIYAKU_HENKO_NO IS '適用後受注契約変更番号'
/
COMMENT ON COLUMN ED0519T_TBL.KIYK_SIKY_DIK_IRISH_NO IS '契約請求代行依頼書番号'
/
COMMENT ON COLUMN ED0519T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0519T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0519T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0519T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0519T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0519T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0519T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0519T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0519T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0519T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0519T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0519T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
