/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0592M_TBL.sql
-- 物理名：ED0592M_TBL
-- 論理名：基本共通契約マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0592M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0592M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KIHON_KYOTSU_KEIYAKU_NO  CHAR(9) NOT NULL --「基本共通契約番号」
	,SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,TORIHIKISAKI_CD  CHAR(9) NOT NULL --「取引先コード」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) NOT NULL --「契約先取引先コード」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,TANTO_SHAIN_NO  VARCHAR2(8) --「担当社員番号」
	,JIGYOSHO_CD  CHAR(6) --「事業所コード」
	,KHN_KYTS_KIYK_SKJ_FLG  CHAR(1) DEFAULT '0' NOT NULL --「基本共通契約削除フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0592M_PK PRIMARY KEY(
	 KIHON_KYOTSU_KEIYAKU_NO
	,  KAISHA_CD
	,  SHOHIN_SERVICE_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0592M_TBL IS '基本共通契約マスタ'
/

COMMENT ON COLUMN ED0592M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0592M_TBL.KIHON_KYOTSU_KEIYAKU_NO IS '基本共通契約番号'
/
COMMENT ON COLUMN ED0592M_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED0592M_TBL.TORIHIKISAKI_CD IS '取引先コード'
/
COMMENT ON COLUMN ED0592M_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED0592M_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED0592M_TBL.TANTO_SHAIN_NO IS '担当社員番号'
/
COMMENT ON COLUMN ED0592M_TBL.JIGYOSHO_CD IS '事業所コード'
/
COMMENT ON COLUMN ED0592M_TBL.KHN_KYTS_KIYK_SKJ_FLG IS '基本共通契約削除フラグ'
/
COMMENT ON COLUMN ED0592M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0592M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0592M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0592M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0592M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0592M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0592M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0592M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0592M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0592M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0592M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0592M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
