/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0546T_TBL.sql
-- 物理名：ED0546T_TBL
-- 論理名：契約料金テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0546T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0546T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,RYOKIN_KBN  CHAR(5) NOT NULL --「料金区分」
	,KEIYAKU_RYOKIN_SEIKYUSAKI_KBN  CHAR(1) NOT NULL --「契約料金請求先区分」
	,KEIYAKU_RYOKIN_SN  CHAR(14) NOT NULL --「契約料金連番」
	,KANREN_JUCHU_KEIYAKU_NO  CHAR(15) --「関連受注契約番号」
	,KEIYAKU_CHOKI_RINJI_KBN  CHAR(1) NOT NULL --「契約長期臨時区分」
	,URIAGE_KEIJO_SHUBETSU_KBN  CHAR(2) NOT NULL --「売上計上種別区分」
	,TEKIYO_KAISHI_YOTEI_YMD  DATE NOT NULL --「適用開始予定年月日」
	,TEKIYO_SHURYO_YOTEI_YMD  DATE NOT NULL --「適用終了予定年月日」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,KEIYAKU_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「契約料金金額」
	,KEIYAKU_SHONIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「契約承認金額」
	,KEIYAKU_HYOJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「契約標準金額」
	,KEIYAKU_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「契約原価金額」
	,OTSUFUTAN_KOJI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「乙負担工事金額」
	,NYUSHUKKINKI_OPTION_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「入出金機オプション有フラグ」
	,NYUSHUKKINKI_OPTION_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「入出金機オプション数量」
	,HIYO_UCHIWAKE_NAIYO  VARCHAR2(100) --「費用内訳内容」
	,KEIYAKU_RYOKIN_BIKO  VARCHAR2(100) --「契約料金備考」
	,SHOHIZEI_KBN  CHAR(1) NOT NULL --「消費税区分」
	,SHOHI_ZEIRITSU_CD  CHAR(2) --「消費税率コード」
	,SHUKEISAKI_RYOKIN_KBN  CHAR(5) NOT NULL --「集計先料金区分」
	,DAISANSHA_SHIHARAI_SN  CHAR(14) --「第三者支払連番」
	,RONRI_SAKUJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「論理削除フラグ」
	,TKYME_JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「適用前受注契約変更番号」
	,TKYGO_JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「適用後受注契約変更番号」
	,CHK_KIYK_RYKN_KIZK_SIKY_KBN  CHAR(1) NOT NULL --「長期契約料金継続請求区分」
	,KIYK_RYKN_SHOHIZEI_AMT  NUMBER(13,0) --「契約料金消費税金額」
	,UNYO_JOCHU_SHOSAI_SN  CHAR(14) --「運用常駐詳細連番」
	,SHHRI_JKN_NBKAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「支払条件値引有フラグ」
	,SHIHARAI_HOHO_SN  CHAR(14) --「支払方法連番」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0546T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  RYOKIN_KBN
	,  KEIYAKU_RYOKIN_SEIKYUSAKI_KBN
	,  KEIYAKU_RYOKIN_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0546T_TBL IS '契約料金テーブル'
/

COMMENT ON COLUMN ED0546T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0546T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0546T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0546T_TBL.RYOKIN_KBN IS '料金区分'
/
COMMENT ON COLUMN ED0546T_TBL.KEIYAKU_RYOKIN_SEIKYUSAKI_KBN IS '契約料金請求先区分'
/
COMMENT ON COLUMN ED0546T_TBL.KEIYAKU_RYOKIN_SN IS '契約料金連番'
/
COMMENT ON COLUMN ED0546T_TBL.KANREN_JUCHU_KEIYAKU_NO IS '関連受注契約番号'
/
COMMENT ON COLUMN ED0546T_TBL.KEIYAKU_CHOKI_RINJI_KBN IS '契約長期臨時区分'
/
COMMENT ON COLUMN ED0546T_TBL.URIAGE_KEIJO_SHUBETSU_KBN IS '売上計上種別区分'
/
COMMENT ON COLUMN ED0546T_TBL.TEKIYO_KAISHI_YOTEI_YMD IS '適用開始予定年月日'
/
COMMENT ON COLUMN ED0546T_TBL.TEKIYO_SHURYO_YOTEI_YMD IS '適用終了予定年月日'
/
COMMENT ON COLUMN ED0546T_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED0546T_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED0546T_TBL.KEIYAKU_RYOKIN_AMT IS '契約料金金額'
/
COMMENT ON COLUMN ED0546T_TBL.KEIYAKU_SHONIN_AMT IS '契約承認金額'
/
COMMENT ON COLUMN ED0546T_TBL.KEIYAKU_HYOJUN_AMT IS '契約標準金額'
/
COMMENT ON COLUMN ED0546T_TBL.KEIYAKU_GENKA_AMT IS '契約原価金額'
/
COMMENT ON COLUMN ED0546T_TBL.OTSUFUTAN_KOJI_AMT IS '乙負担工事金額'
/
COMMENT ON COLUMN ED0546T_TBL.NYUSHUKKINKI_OPTION_ARI_FLG IS '入出金機オプション有フラグ'
/
COMMENT ON COLUMN ED0546T_TBL.NYUSHUKKINKI_OPTION_SURYO IS '入出金機オプション数量'
/
COMMENT ON COLUMN ED0546T_TBL.HIYO_UCHIWAKE_NAIYO IS '費用内訳内容'
/
COMMENT ON COLUMN ED0546T_TBL.KEIYAKU_RYOKIN_BIKO IS '契約料金備考'
/
COMMENT ON COLUMN ED0546T_TBL.SHOHIZEI_KBN IS '消費税区分'
/
COMMENT ON COLUMN ED0546T_TBL.SHOHI_ZEIRITSU_CD IS '消費税率コード'
/
COMMENT ON COLUMN ED0546T_TBL.SHUKEISAKI_RYOKIN_KBN IS '集計先料金区分'
/
COMMENT ON COLUMN ED0546T_TBL.DAISANSHA_SHIHARAI_SN IS '第三者支払連番'
/
COMMENT ON COLUMN ED0546T_TBL.RONRI_SAKUJO_FLG IS '論理削除フラグ'
/
COMMENT ON COLUMN ED0546T_TBL.TKYME_JUCHU_KEIYAKU_HENKO_NO IS '適用前受注契約変更番号'
/
COMMENT ON COLUMN ED0546T_TBL.TKYGO_JUCHU_KEIYAKU_HENKO_NO IS '適用後受注契約変更番号'
/
COMMENT ON COLUMN ED0546T_TBL.CHK_KIYK_RYKN_KIZK_SIKY_KBN IS '長期契約料金継続請求区分'
/
COMMENT ON COLUMN ED0546T_TBL.KIYK_RYKN_SHOHIZEI_AMT IS '契約料金消費税金額'
/
COMMENT ON COLUMN ED0546T_TBL.UNYO_JOCHU_SHOSAI_SN IS '運用常駐詳細連番'
/
COMMENT ON COLUMN ED0546T_TBL.SHHRI_JKN_NBKAR_FLG IS '支払条件値引有フラグ'
/
COMMENT ON COLUMN ED0546T_TBL.SHIHARAI_HOHO_SN IS '支払方法連番'
/
COMMENT ON COLUMN ED0546T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0546T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0546T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0546T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0546T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0546T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0546T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0546T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0546T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0546T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0546T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0546T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
