/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0570T_TBL.sql
-- 物理名：ED0570T_TBL
-- 論理名：受注常駐テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0570T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0570T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,KEIBITAI_NM_TENYURYOKU_NAIYO  VARCHAR2(30) --「警備隊名称手入力内容」
	,KEIBI_GYOHO_1_GO_GYOMUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備業法１号業務有フラグ」
	,KEIBI_GYOHO_2_GO_GYOMUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備業法２号業務有フラグ」
	,KEIBI_GYOHO_3_GO_GYOMUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備業法３号業務有フラグ」
	,KEIBI_GYOHO_4_GO_GYOMUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備業法４号業務有フラグ」
	,UNYO_KBN  CHAR(1) NOT NULL --「運用区分」
	,JITAI_UNYO_EIGYO_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「自隊運用営業係数」
	,JITAI_UNYO_JININ_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「自隊運用人員単価金額」
	,BAIKYAKUHINARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「売却品有フラグ」
	,NITCHU_KYUKEIJI_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「日中休憩時時間」
	,NITCHU_KYUKEIFUN_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「日中休憩分時間」
	,RENZOKU_KYUKEI_KBN  CHAR(1) NOT NULL --「連続休憩区分」
	,YAKAN_KYUKEIJI_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「夜間休憩時時間」
	,YAKAN_KYUKEIFUN_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「夜間休憩分時間」
	,KIMMU_KIJUNHYO_UNYO_KBN  CHAR(1) NOT NULL --「勤務基準表運用区分」
	,KEIYAKU_KAISHI_YOTEI_YMD  DATE --「契約開始予定年月日」
	,SHINYA_TSUIKARYOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「深夜追加料金有フラグ」
	,SHINYA_TSUIKARYO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「深夜追加料金額」
	,JOCHU_KEIBI_JOKEN_1_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「常駐警備条件１金額」
	,JOCHU_KEIBI_JOKEN_1_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「常駐警備条件１時間」
	,JOCHU_KEIBI_JOKEN_2_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「常駐警備条件２金額」
	,JOCHU_KEIBI_JOKEN_2_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「常駐警備条件２時間」
	,KIB_JSSH_CHK_JKN_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「警備実施超過条件時間」
	,KIB_JSSH_CHK_AMT_TANI_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「警備実施超過金額単位時間」
	,KIB_JSSH_CHK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「警備実施超過金額」
	,SHNY_TSUIKARYOKIN_KANSAN_KS_H  CHAR(2) --「深夜追加料金換算開始時」
	,SHNY_TSUIKARYOKIN_KANSAN_SR_H  CHAR(2) --「深夜追加料金換算終了時」
	,CHIJO_KAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「地上階数」
	,CHIKA_KAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「地下階数」
	,NOBEYUKA_MENSEKI  NUMBER(12,3) DEFAULT '0' NOT NULL --「延べ床面積」
	,KOKYO_KOTSU_KIKANARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「公共交通機関有フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0570T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0570T_TBL IS '受注常駐テーブル'
/

COMMENT ON COLUMN ED0570T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0570T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0570T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0570T_TBL.KEIBITAI_NM_TENYURYOKU_NAIYO IS '警備隊名称手入力内容'
/
COMMENT ON COLUMN ED0570T_TBL.KEIBI_GYOHO_1_GO_GYOMUARI_FLG IS '警備業法１号業務有フラグ'
/
COMMENT ON COLUMN ED0570T_TBL.KEIBI_GYOHO_2_GO_GYOMUARI_FLG IS '警備業法２号業務有フラグ'
/
COMMENT ON COLUMN ED0570T_TBL.KEIBI_GYOHO_3_GO_GYOMUARI_FLG IS '警備業法３号業務有フラグ'
/
COMMENT ON COLUMN ED0570T_TBL.KEIBI_GYOHO_4_GO_GYOMUARI_FLG IS '警備業法４号業務有フラグ'
/
COMMENT ON COLUMN ED0570T_TBL.UNYO_KBN IS '運用区分'
/
COMMENT ON COLUMN ED0570T_TBL.JITAI_UNYO_EIGYO_KEISU IS '自隊運用営業係数'
/
COMMENT ON COLUMN ED0570T_TBL.JITAI_UNYO_JININ_TANKA_AMT IS '自隊運用人員単価金額'
/
COMMENT ON COLUMN ED0570T_TBL.BAIKYAKUHINARI_FLG IS '売却品有フラグ'
/
COMMENT ON COLUMN ED0570T_TBL.NITCHU_KYUKEIJI_JIKAN IS '日中休憩時時間'
/
COMMENT ON COLUMN ED0570T_TBL.NITCHU_KYUKEIFUN_JIKAN IS '日中休憩分時間'
/
COMMENT ON COLUMN ED0570T_TBL.RENZOKU_KYUKEI_KBN IS '連続休憩区分'
/
COMMENT ON COLUMN ED0570T_TBL.YAKAN_KYUKEIJI_JIKAN IS '夜間休憩時時間'
/
COMMENT ON COLUMN ED0570T_TBL.YAKAN_KYUKEIFUN_JIKAN IS '夜間休憩分時間'
/
COMMENT ON COLUMN ED0570T_TBL.KIMMU_KIJUNHYO_UNYO_KBN IS '勤務基準表運用区分'
/
COMMENT ON COLUMN ED0570T_TBL.KEIYAKU_KAISHI_YOTEI_YMD IS '契約開始予定年月日'
/
COMMENT ON COLUMN ED0570T_TBL.SHINYA_TSUIKARYOARI_FLG IS '深夜追加料金有フラグ'
/
COMMENT ON COLUMN ED0570T_TBL.SHINYA_TSUIKARYO_AMT IS '深夜追加料金額'
/
COMMENT ON COLUMN ED0570T_TBL.JOCHU_KEIBI_JOKEN_1_AMT IS '常駐警備条件１金額'
/
COMMENT ON COLUMN ED0570T_TBL.JOCHU_KEIBI_JOKEN_1_JIKAN IS '常駐警備条件１時間'
/
COMMENT ON COLUMN ED0570T_TBL.JOCHU_KEIBI_JOKEN_2_AMT IS '常駐警備条件２金額'
/
COMMENT ON COLUMN ED0570T_TBL.JOCHU_KEIBI_JOKEN_2_JIKAN IS '常駐警備条件２時間'
/
COMMENT ON COLUMN ED0570T_TBL.KIB_JSSH_CHK_JKN_JIKAN IS '警備実施超過条件時間'
/
COMMENT ON COLUMN ED0570T_TBL.KIB_JSSH_CHK_AMT_TANI_JIKAN IS '警備実施超過金額単位時間'
/
COMMENT ON COLUMN ED0570T_TBL.KIB_JSSH_CHK_AMT IS '警備実施超過金額'
/
COMMENT ON COLUMN ED0570T_TBL.SHNY_TSUIKARYOKIN_KANSAN_KS_H IS '深夜追加料金換算開始時'
/
COMMENT ON COLUMN ED0570T_TBL.SHNY_TSUIKARYOKIN_KANSAN_SR_H IS '深夜追加料金換算終了時'
/
COMMENT ON COLUMN ED0570T_TBL.CHIJO_KAISU IS '地上階数'
/
COMMENT ON COLUMN ED0570T_TBL.CHIKA_KAISU IS '地下階数'
/
COMMENT ON COLUMN ED0570T_TBL.NOBEYUKA_MENSEKI IS '延べ床面積'
/
COMMENT ON COLUMN ED0570T_TBL.KOKYO_KOTSU_KIKANARI_FLG IS '公共交通機関有フラグ'
/
COMMENT ON COLUMN ED0570T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0570T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0570T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0570T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0570T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0570T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0570T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0570T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0570T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0570T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0570T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0570T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
