/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0559T_TBL.sql
-- 物理名：ED0559T_TBL
-- 論理名：契約コスモテーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0559T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0559T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIYAKU_ID  CHAR(18) NOT NULL --「契約ＩＤ」
	,COSMO_MISEBAN_NO  CHAR(15) --「コスモ店番番号」
	,COSMO_MISEBAN_NO_BN  CHAR(5) --「コスモ店番番号枝番」
	,COSMO_HOSHU_KAISHA_NM  VARCHAR2(40) --「コスモ保守会社名称」
	,YUJIN_TEMPO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「有人店舗フラグ」
	,COSMO_BACKUP_TAIOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「コスモバックアップ対応有フラグ」
	,HEIJITSU_EIGYO_KAISHI_TM  CHAR(4) --「平日営業開始時刻」
	,HEIJITSU_EIGYO_SHURYO_TM  CHAR(4) --「平日営業終了時刻」
	,HEIJITSU_TAIO_KAISHI_TM_1  CHAR(4) --「平日対応開始時刻１」
	,HEIJITSU_TAIO_SHURYO_TM_1  CHAR(4) --「平日対応終了時刻１」
	,HEIJITSU_TAIO_KAISHI_TM_2  CHAR(4) --「平日対応開始時刻２」
	,HEIJITSU_TAIO_SHURYO_TM_2  CHAR(4) --「平日対応終了時刻２」
	,DOYO_EIGYO_KAISHI_TM  CHAR(4) --「土曜営業開始時刻」
	,DOYO_EIGYO_SHURYO_TM  CHAR(4) --「土曜営業終了時刻」
	,DOYO_TAIO_KAISHI_TM_1  CHAR(4) --「土曜対応開始時刻１」
	,DOYO_TAIO_SHURYO_TM_1  CHAR(4) --「土曜対応終了時刻１」
	,DOYO_TAIO_KAISHI_TM_2  CHAR(4) --「土曜対応開始時刻２」
	,DOYO_TAIO_SHURYO_TM_2  CHAR(4) --「土曜対応終了時刻２」
	,NICHIYO_EIGYO_KAISHI_TM  CHAR(4) --「日曜営業開始時刻」
	,NICHIYO_EIGYO_SHURYO_TM  CHAR(4) --「日曜営業終了時刻」
	,NICHIYO_TAIO_KAISHI_TM_1  CHAR(4) --「日曜対応開始時刻１」
	,NICHIYO_TAIO_SHURYO_TM_1  CHAR(4) --「日曜対応終了時刻１」
	,NICHIYO_TAIO_KAISHI_TM_2  CHAR(4) --「日曜対応開始時刻２」
	,NICHIYO_TAIO_SHURYO_TM_2  CHAR(4) --「日曜対応終了時刻２」
	,SHUKUJITSU_EIGYO_KAISHI_TM  CHAR(4) --「祝日営業開始時刻」
	,SHUKUJITSU_EIGYO_SHURYO_TM  CHAR(4) --「祝日営業終了時刻」
	,SHUKUJITSU_TAIO_KAISHI_TM_1  CHAR(4) --「祝日対応開始時刻１」
	,SHUKUJITSU_TAIO_SHURYO_TM_1  CHAR(4) --「祝日対応終了時刻１」
	,SHUKUJITSU_TAIO_KAISHI_TM_2  CHAR(4) --「祝日対応開始時刻２」
	,SHUKUJITSU_TAIO_SHURYO_TM_2  CHAR(4) --「祝日対応終了時刻２」
	,COSMO_BIKO  VARCHAR2(60) --「コスモ備考」
	,COSMO_KEIYAKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「コスモ契約有フラグ」
	,COSMO_KHNRYKN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「コスモ基本料金金額」
	,COSMO_KIHON_RYOKIN_CD  CHAR(3) --「コスモ基本料金コード」
	,COSMO_NENGAKU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「コスモ年額金額」
	,KHN_KYTS_KIYK_SHNN_KJN_CD  CHAR(10) --「基本共通契約承認基準コード」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0559T_PK PRIMARY KEY(
	 KEIYAKU_ID
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0559T_TBL IS '契約コスモテーブル'
/

COMMENT ON COLUMN ED0559T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0559T_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED0559T_TBL.COSMO_MISEBAN_NO IS 'コスモ店番番号'
/
COMMENT ON COLUMN ED0559T_TBL.COSMO_MISEBAN_NO_BN IS 'コスモ店番番号枝番'
/
COMMENT ON COLUMN ED0559T_TBL.COSMO_HOSHU_KAISHA_NM IS 'コスモ保守会社名称'
/
COMMENT ON COLUMN ED0559T_TBL.YUJIN_TEMPO_FLG IS '有人店舗フラグ'
/
COMMENT ON COLUMN ED0559T_TBL.COSMO_BACKUP_TAIOARI_FLG IS 'コスモバックアップ対応有フラグ'
/
COMMENT ON COLUMN ED0559T_TBL.HEIJITSU_EIGYO_KAISHI_TM IS '平日営業開始時刻'
/
COMMENT ON COLUMN ED0559T_TBL.HEIJITSU_EIGYO_SHURYO_TM IS '平日営業終了時刻'
/
COMMENT ON COLUMN ED0559T_TBL.HEIJITSU_TAIO_KAISHI_TM_1 IS '平日対応開始時刻１'
/
COMMENT ON COLUMN ED0559T_TBL.HEIJITSU_TAIO_SHURYO_TM_1 IS '平日対応終了時刻１'
/
COMMENT ON COLUMN ED0559T_TBL.HEIJITSU_TAIO_KAISHI_TM_2 IS '平日対応開始時刻２'
/
COMMENT ON COLUMN ED0559T_TBL.HEIJITSU_TAIO_SHURYO_TM_2 IS '平日対応終了時刻２'
/
COMMENT ON COLUMN ED0559T_TBL.DOYO_EIGYO_KAISHI_TM IS '土曜営業開始時刻'
/
COMMENT ON COLUMN ED0559T_TBL.DOYO_EIGYO_SHURYO_TM IS '土曜営業終了時刻'
/
COMMENT ON COLUMN ED0559T_TBL.DOYO_TAIO_KAISHI_TM_1 IS '土曜対応開始時刻１'
/
COMMENT ON COLUMN ED0559T_TBL.DOYO_TAIO_SHURYO_TM_1 IS '土曜対応終了時刻１'
/
COMMENT ON COLUMN ED0559T_TBL.DOYO_TAIO_KAISHI_TM_2 IS '土曜対応開始時刻２'
/
COMMENT ON COLUMN ED0559T_TBL.DOYO_TAIO_SHURYO_TM_2 IS '土曜対応終了時刻２'
/
COMMENT ON COLUMN ED0559T_TBL.NICHIYO_EIGYO_KAISHI_TM IS '日曜営業開始時刻'
/
COMMENT ON COLUMN ED0559T_TBL.NICHIYO_EIGYO_SHURYO_TM IS '日曜営業終了時刻'
/
COMMENT ON COLUMN ED0559T_TBL.NICHIYO_TAIO_KAISHI_TM_1 IS '日曜対応開始時刻１'
/
COMMENT ON COLUMN ED0559T_TBL.NICHIYO_TAIO_SHURYO_TM_1 IS '日曜対応終了時刻１'
/
COMMENT ON COLUMN ED0559T_TBL.NICHIYO_TAIO_KAISHI_TM_2 IS '日曜対応開始時刻２'
/
COMMENT ON COLUMN ED0559T_TBL.NICHIYO_TAIO_SHURYO_TM_2 IS '日曜対応終了時刻２'
/
COMMENT ON COLUMN ED0559T_TBL.SHUKUJITSU_EIGYO_KAISHI_TM IS '祝日営業開始時刻'
/
COMMENT ON COLUMN ED0559T_TBL.SHUKUJITSU_EIGYO_SHURYO_TM IS '祝日営業終了時刻'
/
COMMENT ON COLUMN ED0559T_TBL.SHUKUJITSU_TAIO_KAISHI_TM_1 IS '祝日対応開始時刻１'
/
COMMENT ON COLUMN ED0559T_TBL.SHUKUJITSU_TAIO_SHURYO_TM_1 IS '祝日対応終了時刻１'
/
COMMENT ON COLUMN ED0559T_TBL.SHUKUJITSU_TAIO_KAISHI_TM_2 IS '祝日対応開始時刻２'
/
COMMENT ON COLUMN ED0559T_TBL.SHUKUJITSU_TAIO_SHURYO_TM_2 IS '祝日対応終了時刻２'
/
COMMENT ON COLUMN ED0559T_TBL.COSMO_BIKO IS 'コスモ備考'
/
COMMENT ON COLUMN ED0559T_TBL.COSMO_KEIYAKUARI_FLG IS 'コスモ契約有フラグ'
/
COMMENT ON COLUMN ED0559T_TBL.COSMO_KHNRYKN_AMT IS 'コスモ基本料金金額'
/
COMMENT ON COLUMN ED0559T_TBL.COSMO_KIHON_RYOKIN_CD IS 'コスモ基本料金コード'
/
COMMENT ON COLUMN ED0559T_TBL.COSMO_NENGAKU_AMT IS 'コスモ年額金額'
/
COMMENT ON COLUMN ED0559T_TBL.KHN_KYTS_KIYK_SHNN_KJN_CD IS '基本共通契約承認基準コード'
/
COMMENT ON COLUMN ED0559T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0559T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0559T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0559T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0559T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0559T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0559T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0559T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0559T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0559T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0559T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0559T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
