/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0595T_TBL.sql
-- 物理名：ED0595T_TBL
-- 論理名：契約ＣＤＡＴＭテーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0595T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0595T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIYAKU_ID  CHAR(18) NOT NULL --「契約ＩＤ」
	,SOTENYO_SHIHEI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「装填用紙幣数量」
	,SOTENYO_KOKA_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「装填用硬貨数量」
	,KAISHUYO_SHIHEI_MAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「回収用紙幣枚数」
	,KAISHUYO_KOKA_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「回収用硬貨袋数量」
	,SHIKIN_TATEKAE_TESURYO_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「資金立替手数料率」
	,HEIKIN_ZANDAKA_AMT  NUMBER(15,2) DEFAULT '0' NOT NULL --「平均残高金額」
	,HOKENRYO_SETTEI_CDATM_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「保険料設定ＣＤＡＴＭ数量」
	,JIDOKI_SHUBETSU_CD  CHAR(2) --「自動機種別コード」
	,SONOTA_JIDOKI_SHUBETSU_NM  VARCHAR2(100) --「その他自動機種別名称」
	,JIDOKI_MAKER_CD  CHAR(2) --「自動機メーカコード」
	,SONOTA_JIDOKI_MAKER_NM  VARCHAR2(100) --「その他自動機メーカ名称」
	,JIDOKI_KISHU_NM  VARCHAR2(30) --「自動機機種名称」
	,JIDOKI_DAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「自動機台数」
	,HANSO_YOKI_HIYO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「搬送容器費用金額」
	,SYSTEM_HIYO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「システム費用金額」
	,SHIKIN_CENTER_HIYO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「資金センター費用金額」
	,UKETSUKE_CENTER_HIYO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「受付センター費用金額」
	,SONOTA_SHOKEIHI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「その他諸経費金額」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0595T_PK PRIMARY KEY(
	 KEIYAKU_ID
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0595T_TBL IS '契約ＣＤＡＴＭテーブル'
/

COMMENT ON COLUMN ED0595T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0595T_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED0595T_TBL.SOTENYO_SHIHEI_SURYO IS '装填用紙幣数量'
/
COMMENT ON COLUMN ED0595T_TBL.SOTENYO_KOKA_SURYO IS '装填用硬貨数量'
/
COMMENT ON COLUMN ED0595T_TBL.KAISHUYO_SHIHEI_MAISU IS '回収用紙幣枚数'
/
COMMENT ON COLUMN ED0595T_TBL.KAISHUYO_KOKA_SURYO IS '回収用硬貨袋数量'
/
COMMENT ON COLUMN ED0595T_TBL.SHIKIN_TATEKAE_TESURYO_RITSU IS '資金立替手数料率'
/
COMMENT ON COLUMN ED0595T_TBL.HEIKIN_ZANDAKA_AMT IS '平均残高金額'
/
COMMENT ON COLUMN ED0595T_TBL.HOKENRYO_SETTEI_CDATM_SURYO IS '保険料設定ＣＤＡＴＭ数量'
/
COMMENT ON COLUMN ED0595T_TBL.JIDOKI_SHUBETSU_CD IS '自動機種別コード'
/
COMMENT ON COLUMN ED0595T_TBL.SONOTA_JIDOKI_SHUBETSU_NM IS 'その他自動機種別名称'
/
COMMENT ON COLUMN ED0595T_TBL.JIDOKI_MAKER_CD IS '自動機メーカコード'
/
COMMENT ON COLUMN ED0595T_TBL.SONOTA_JIDOKI_MAKER_NM IS 'その他自動機メーカ名称'
/
COMMENT ON COLUMN ED0595T_TBL.JIDOKI_KISHU_NM IS '自動機機種名称'
/
COMMENT ON COLUMN ED0595T_TBL.JIDOKI_DAISU IS '自動機台数'
/
COMMENT ON COLUMN ED0595T_TBL.HANSO_YOKI_HIYO_AMT IS '搬送容器費用金額'
/
COMMENT ON COLUMN ED0595T_TBL.SYSTEM_HIYO_AMT IS 'システム費用金額'
/
COMMENT ON COLUMN ED0595T_TBL.SHIKIN_CENTER_HIYO_AMT IS '資金センター費用金額'
/
COMMENT ON COLUMN ED0595T_TBL.UKETSUKE_CENTER_HIYO_AMT IS '受付センター費用金額'
/
COMMENT ON COLUMN ED0595T_TBL.SONOTA_SHOKEIHI_AMT IS 'その他諸経費金額'
/
COMMENT ON COLUMN ED0595T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0595T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0595T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0595T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0595T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0595T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0595T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0595T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0595T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0595T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0595T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0595T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
