/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0576T_TBL.sql
-- 物理名：ED0576T_TBL
-- 論理名：定型外契約資料テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0576T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0576T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TEIKEIGAI_KEIYAKU_SHIRYO_NO  CHAR(17) NOT NULL --「定型外契約資料番号」
	,KIHON_KYOTSU_KEIYAKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「基本共通契約有フラグ」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,KEIYAKUSHO_SHORI_KBN  CHAR(1) NOT NULL --「契約書処理区分」
	,KEIYAKUSHO_NO  CHAR(17) --「契約書番号」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,JUCHU_TANTO_SHAIN_NO  VARCHAR2(8) --「受注担当社員番号」
	,HITEIKEI_KEIYAKUSHO_EIGYO_CMNT  VARCHAR2(150) --「非定型契約書営業コメント」
	,SHOKAI_SHINSEI_DT  TIMESTAMP --「初回申請日時」
	,SHUSEI_SHINSEI_DT  TIMESTAMP --「修正申請日時」
	,SHINSEISHA_SHAIN_NO  VARCHAR2(8) --「申請者社員番号」
	,SAISHU_SHONIN_DT  TIMESTAMP --「最終承認日時」
	,SHONINSHA_SHAIN_NO  VARCHAR2(8) --「承認者社員番号」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「受注契約変更番号」
	,KIHON_KYOTSU_KEIYAKU_NO  CHAR(9) --「基本共通契約番号」
	,KEIYAKUSHO_KAISHU_YMD  DATE --「契約書回収年月日」
	,HTIKI_KIYKSH_SHONIN_ROOT_KBN  CHAR(1) NOT NULL --「非定型契約書承認ルート区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0576T_PK PRIMARY KEY(
	 TEIKEIGAI_KEIYAKU_SHIRYO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0576T_TBL IS '定型外契約資料テーブル'
/

COMMENT ON COLUMN ED0576T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0576T_TBL.TEIKEIGAI_KEIYAKU_SHIRYO_NO IS '定型外契約資料番号'
/
COMMENT ON COLUMN ED0576T_TBL.KIHON_KYOTSU_KEIYAKUARI_FLG IS '基本共通契約有フラグ'
/
COMMENT ON COLUMN ED0576T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED0576T_TBL.KEIYAKUSHO_SHORI_KBN IS '契約書処理区分'
/
COMMENT ON COLUMN ED0576T_TBL.KEIYAKUSHO_NO IS '契約書番号'
/
COMMENT ON COLUMN ED0576T_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED0576T_TBL.JUCHU_TANTO_SHAIN_NO IS '受注担当社員番号'
/
COMMENT ON COLUMN ED0576T_TBL.HITEIKEI_KEIYAKUSHO_EIGYO_CMNT IS '非定型契約書営業コメント'
/
COMMENT ON COLUMN ED0576T_TBL.SHOKAI_SHINSEI_DT IS '初回申請日時'
/
COMMENT ON COLUMN ED0576T_TBL.SHUSEI_SHINSEI_DT IS '修正申請日時'
/
COMMENT ON COLUMN ED0576T_TBL.SHINSEISHA_SHAIN_NO IS '申請者社員番号'
/
COMMENT ON COLUMN ED0576T_TBL.SAISHU_SHONIN_DT IS '最終承認日時'
/
COMMENT ON COLUMN ED0576T_TBL.SHONINSHA_SHAIN_NO IS '承認者社員番号'
/
COMMENT ON COLUMN ED0576T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED0576T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0576T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0576T_TBL.KIHON_KYOTSU_KEIYAKU_NO IS '基本共通契約番号'
/
COMMENT ON COLUMN ED0576T_TBL.KEIYAKUSHO_KAISHU_YMD IS '契約書回収年月日'
/
COMMENT ON COLUMN ED0576T_TBL.HTIKI_KIYKSH_SHONIN_ROOT_KBN IS '非定型契約書承認ルート区分'
/
COMMENT ON COLUMN ED0576T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0576T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0576T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0576T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0576T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0576T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0576T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0576T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0576T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0576T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0576T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0576T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
