/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0539T_TBL.sql
-- 物理名：ED0539T_TBL
-- 論理名：中断再開テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0539T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0539T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,CHUDAN_YOTEI_YMD  DATE --「中断予定年月日」
	,KEIYAKU_CHUDAN_YMD  DATE --「契約中断年月日」
	,SAIKAI_YOTEI_YMD  DATE --「再開予定年月日」
	,KEIYAKU_SAIKAI_YMD  DATE --「契約再開年月日」
	,CHUDAN_RIYU_KBN  CHAR(1) NOT NULL --「中断理由区分」
	,SONOTA_CHUDAN_RIYU  VARCHAR2(50) --「その他中断理由」
	,CHUDAN_BIKO  VARCHAR2(150) --「中断備考」
	,CHUDAN_SAIKAI_CANCEL_FLG  CHAR(1) DEFAULT '0' NOT NULL --「中断再開キャンセルフラグ」
	,KEIYAKUSHO_KAISHU_YMD  DATE --「契約書回収年月日」
	,CHUDAN_NYURYOKU_TANTO_SHAIN_NO  VARCHAR2(8) --「中断入力担当社員番号」
	,SAIKAI_NYURYOKU_TANTO_SHAIN_NO  VARCHAR2(8) --「再開入力担当社員番号」
	,CHUDANCHU_RYOKIN_SEIKYUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「中断中料金請求有フラグ」
	,KAISEN_SHIYORYO_SEIKYUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「回線使用料請求有フラグ」
	,LEASE_HOSHURYO_SEIKYUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「リース保守料請求有フラグ」
	,KAGI_HENNO_YMD  DATE --「鍵返納年月日」
	,DENGEN_OFF_YMD  DATE --「電源ＯＦＦ年月日」
	,SAISHU_KAISHU_YMD  DATE --「最終回収年月日」
	,SAISHU_KAISHU_TM  CHAR(4) --「最終回収時刻」
	,CHDN_SIKI_KIYKJ_HSK_NAIYO  VARCHAR2(200) --「中断再開解約時補足内容」
	,CHDN_SIKI_KIYKJ_HSK_NAIYO_1  VARCHAR2(1000) --「中断再開解約時補足内容１」
	,RINJI_TAIO_RYOKINARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「臨時対応料金有フラグ」
	,CHDN_SIKI_KIYKJ_MSH_RIYU  VARCHAR2(200) --「中断再開解約時無償理由」
	,YUSHO_SHUTSUDO_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「有償出動料金金額」
	,SAIKAIGO_SHOKAI_KAISHU_YMD  DATE --「再開後初回回収年月日」
	,SAIKAIGO_SHOKAI_KAISHU_TM  CHAR(4) --「再開後初回回収時刻」
	,SAIKAIGO_SHOKAI_HAIKINARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「再開後初回配金有フラグ」
	,SAIKAIGO_SHOKAI_HAIKIN_YMD  DATE --「再開後初回配金年月日」
	,SAIKAIGO_SHOKAI_HAIKIN_TM  CHAR(4) --「再開後初回配金時刻」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0539T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0539T_TBL IS '中断再開テーブル'
/

COMMENT ON COLUMN ED0539T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0539T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0539T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0539T_TBL.CHUDAN_YOTEI_YMD IS '中断予定年月日'
/
COMMENT ON COLUMN ED0539T_TBL.KEIYAKU_CHUDAN_YMD IS '契約中断年月日'
/
COMMENT ON COLUMN ED0539T_TBL.SAIKAI_YOTEI_YMD IS '再開予定年月日'
/
COMMENT ON COLUMN ED0539T_TBL.KEIYAKU_SAIKAI_YMD IS '契約再開年月日'
/
COMMENT ON COLUMN ED0539T_TBL.CHUDAN_RIYU_KBN IS '中断理由区分'
/
COMMENT ON COLUMN ED0539T_TBL.SONOTA_CHUDAN_RIYU IS 'その他中断理由'
/
COMMENT ON COLUMN ED0539T_TBL.CHUDAN_BIKO IS '中断備考'
/
COMMENT ON COLUMN ED0539T_TBL.CHUDAN_SAIKAI_CANCEL_FLG IS '中断再開キャンセルフラグ'
/
COMMENT ON COLUMN ED0539T_TBL.KEIYAKUSHO_KAISHU_YMD IS '契約書回収年月日'
/
COMMENT ON COLUMN ED0539T_TBL.CHUDAN_NYURYOKU_TANTO_SHAIN_NO IS '中断入力担当社員番号'
/
COMMENT ON COLUMN ED0539T_TBL.SAIKAI_NYURYOKU_TANTO_SHAIN_NO IS '再開入力担当社員番号'
/
COMMENT ON COLUMN ED0539T_TBL.CHUDANCHU_RYOKIN_SEIKYUARI_FLG IS '中断中料金請求有フラグ'
/
COMMENT ON COLUMN ED0539T_TBL.KAISEN_SHIYORYO_SEIKYUARI_FLG IS '回線使用料請求有フラグ'
/
COMMENT ON COLUMN ED0539T_TBL.LEASE_HOSHURYO_SEIKYUARI_FLG IS 'リース保守料請求有フラグ'
/
COMMENT ON COLUMN ED0539T_TBL.KAGI_HENNO_YMD IS '鍵返納年月日'
/
COMMENT ON COLUMN ED0539T_TBL.DENGEN_OFF_YMD IS '電源ＯＦＦ年月日'
/
COMMENT ON COLUMN ED0539T_TBL.SAISHU_KAISHU_YMD IS '最終回収年月日'
/
COMMENT ON COLUMN ED0539T_TBL.SAISHU_KAISHU_TM IS '最終回収時刻'
/
COMMENT ON COLUMN ED0539T_TBL.CHDN_SIKI_KIYKJ_HSK_NAIYO IS '中断再開解約時補足内容'
/
COMMENT ON COLUMN ED0539T_TBL.CHDN_SIKI_KIYKJ_HSK_NAIYO_1 IS '中断再開解約時補足内容１'
/
COMMENT ON COLUMN ED0539T_TBL.RINJI_TAIO_RYOKINARI_FLG IS '臨時対応料金有フラグ'
/
COMMENT ON COLUMN ED0539T_TBL.CHDN_SIKI_KIYKJ_MSH_RIYU IS '中断再開解約時無償理由'
/
COMMENT ON COLUMN ED0539T_TBL.YUSHO_SHUTSUDO_RYOKIN_AMT IS '有償出動料金金額'
/
COMMENT ON COLUMN ED0539T_TBL.SAIKAIGO_SHOKAI_KAISHU_YMD IS '再開後初回回収年月日'
/
COMMENT ON COLUMN ED0539T_TBL.SAIKAIGO_SHOKAI_KAISHU_TM IS '再開後初回回収時刻'
/
COMMENT ON COLUMN ED0539T_TBL.SAIKAIGO_SHOKAI_HAIKINARI_FLG IS '再開後初回配金有フラグ'
/
COMMENT ON COLUMN ED0539T_TBL.SAIKAIGO_SHOKAI_HAIKIN_YMD IS '再開後初回配金年月日'
/
COMMENT ON COLUMN ED0539T_TBL.SAIKAIGO_SHOKAI_HAIKIN_TM IS '再開後初回配金時刻'
/
COMMENT ON COLUMN ED0539T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED0539T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0539T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0539T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0539T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0539T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0539T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0539T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0539T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0539T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0539T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0539T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0539T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
