/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0553T_TBL.sql
-- 物理名：ED0553T_TBL
-- 論理名：入出金機プール登録明細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0553T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0553T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,NYUSHUKKINKI_NO  VARCHAR2(6) NOT NULL --「入出金機番号」
	,NYSHKKNK_POOL_TRK_SHSI_SN  CHAR(14) NOT NULL --「入出金機プール登録詳細連番」
	,NYUSHUKKINKI_BIHIN_KBN  CHAR(1) NOT NULL --「入出金機備品区分」
	,NYUSHUKKINKI_KAGI_CD  CHAR(8) --「入出金機鍵コード」
	,NYUSHUKKINKI_KAGI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「入出金機鍵数量」
	,NYUSHUKKINKI_FUZOKUHIN_CD  CHAR(8) --「入出金機付属品コード」
	,TMP_SHRY_FILE_SHKBTS_KEY  VARCHAR2(255) --「添付資料ファイル識別キー」
	,TEMPU_SHIRYO_FILE_NM  VARCHAR2(255) --「添付資料ファイル名称」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0553T_PK PRIMARY KEY(
	 NYUSHUKKINKI_NO
	,  NYSHKKNK_POOL_TRK_SHSI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0553T_TBL IS '入出金機プール登録明細テーブル'
/

COMMENT ON COLUMN ED0553T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0553T_TBL.NYUSHUKKINKI_NO IS '入出金機番号'
/
COMMENT ON COLUMN ED0553T_TBL.NYSHKKNK_POOL_TRK_SHSI_SN IS '入出金機プール登録詳細連番'
/
COMMENT ON COLUMN ED0553T_TBL.NYUSHUKKINKI_BIHIN_KBN IS '入出金機備品区分'
/
COMMENT ON COLUMN ED0553T_TBL.NYUSHUKKINKI_KAGI_CD IS '入出金機鍵コード'
/
COMMENT ON COLUMN ED0553T_TBL.NYUSHUKKINKI_KAGI_SURYO IS '入出金機鍵数量'
/
COMMENT ON COLUMN ED0553T_TBL.NYUSHUKKINKI_FUZOKUHIN_CD IS '入出金機付属品コード'
/
COMMENT ON COLUMN ED0553T_TBL.TMP_SHRY_FILE_SHKBTS_KEY IS '添付資料ファイル識別キー'
/
COMMENT ON COLUMN ED0553T_TBL.TEMPU_SHIRYO_FILE_NM IS '添付資料ファイル名称'
/
COMMENT ON COLUMN ED0553T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0553T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0553T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0553T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0553T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0553T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0553T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0553T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0553T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0553T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0553T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0553T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
