/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0529T_TBL.sql
-- 物理名：ED0529T_TBL
-- 論理名：貸出返却テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0529T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0529T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIYAKUSHO_NO  CHAR(17) NOT NULL --「契約書番号」
	,KEIYAKUSHO_KASHIDASHI_NO  CHAR(12) NOT NULL --「契約書貸出番号」
	,KASHIDASHI_IRAI_YMD  DATE NOT NULL --「貸出依頼年月日」
	,KASHIDASHI_IRAI_RIYU  VARCHAR2(30) --「貸出依頼理由」
	,KSHDSH_IRI_KIYKSH_TCHK_KB_YMD  DATE --「貸出依頼契約書到着希望年月日」
	,KSDS_IRI_KIYKS_HNKK_YTI_YMD  DATE --「貸出依頼契約書返却予定年月日」
	,KSHDSH_IRI_KIYKSH_SF_HH_KBN  CHAR(1) --「貸出依頼契約書送付方法区分」
	,KSHDSH_IRI_SHIN_NISN_NO  VARCHAR2(20) NOT NULL --「貸出依頼社員内線番号」
	,KASHIDASHI_IRAI_NAIYO_KBN  CHAR(1) NOT NULL --「貸出依頼内容区分」
	,KSHDSH_KIYKSH_HNKYK_KGN_YMD  DATE --「貸出契約書返却期限年月日」
	,KASHIDASHI_IRAI_SHAIN_NO  VARCHAR2(8) NOT NULL --「貸出依頼社員番号」
	,KASHIDASHI_TANTO_SHAIN_NO  VARCHAR2(8) --「貸出担当社員番号」
	,KASHIDASHI_YMD  DATE --「貸出年月日」
	,KEIYAKUSHO_HENKYAKU_HOKAN_YMD  DATE --「契約書返却保管年月日」
	,KASHIDASHI_HENKYAKU_BIKO  VARCHAR2(50) --「貸出返却備考」
	,KASHIDASHI_IRAI_SHONINZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「貸出依頼承認済フラグ」
	,RONRI_SAKUJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「論理削除フラグ」
	,KEIYAKUSHO_KASHIDASHIZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「契約書貸出中フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0529T_PK PRIMARY KEY(
	 KEIYAKUSHO_NO
	,  KEIYAKUSHO_KASHIDASHI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0529T_TBL IS '貸出返却テーブル'
/

COMMENT ON COLUMN ED0529T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0529T_TBL.KEIYAKUSHO_NO IS '契約書番号'
/
COMMENT ON COLUMN ED0529T_TBL.KEIYAKUSHO_KASHIDASHI_NO IS '契約書貸出番号'
/
COMMENT ON COLUMN ED0529T_TBL.KASHIDASHI_IRAI_YMD IS '貸出依頼年月日'
/
COMMENT ON COLUMN ED0529T_TBL.KASHIDASHI_IRAI_RIYU IS '貸出依頼理由'
/
COMMENT ON COLUMN ED0529T_TBL.KSHDSH_IRI_KIYKSH_TCHK_KB_YMD IS '貸出依頼契約書到着希望年月日'
/
COMMENT ON COLUMN ED0529T_TBL.KSDS_IRI_KIYKS_HNKK_YTI_YMD IS '貸出依頼契約書返却予定年月日'
/
COMMENT ON COLUMN ED0529T_TBL.KSHDSH_IRI_KIYKSH_SF_HH_KBN IS '貸出依頼契約書送付方法区分'
/
COMMENT ON COLUMN ED0529T_TBL.KSHDSH_IRI_SHIN_NISN_NO IS '貸出依頼社員内線番号'
/
COMMENT ON COLUMN ED0529T_TBL.KASHIDASHI_IRAI_NAIYO_KBN IS '貸出依頼内容区分'
/
COMMENT ON COLUMN ED0529T_TBL.KSHDSH_KIYKSH_HNKYK_KGN_YMD IS '貸出契約書返却期限年月日'
/
COMMENT ON COLUMN ED0529T_TBL.KASHIDASHI_IRAI_SHAIN_NO IS '貸出依頼社員番号'
/
COMMENT ON COLUMN ED0529T_TBL.KASHIDASHI_TANTO_SHAIN_NO IS '貸出担当社員番号'
/
COMMENT ON COLUMN ED0529T_TBL.KASHIDASHI_YMD IS '貸出年月日'
/
COMMENT ON COLUMN ED0529T_TBL.KEIYAKUSHO_HENKYAKU_HOKAN_YMD IS '契約書返却保管年月日'
/
COMMENT ON COLUMN ED0529T_TBL.KASHIDASHI_HENKYAKU_BIKO IS '貸出返却備考'
/
COMMENT ON COLUMN ED0529T_TBL.KASHIDASHI_IRAI_SHONINZUMI_FLG IS '貸出依頼承認済フラグ'
/
COMMENT ON COLUMN ED0529T_TBL.RONRI_SAKUJO_FLG IS '論理削除フラグ'
/
COMMENT ON COLUMN ED0529T_TBL.KEIYAKUSHO_KASHIDASHIZUMI_FLG IS '契約書貸出中フラグ'
/
COMMENT ON COLUMN ED0529T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0529T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0529T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0529T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0529T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0529T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0529T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0529T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0529T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0529T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0529T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0529T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
