/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0557T_TBL.sql
-- 物理名：ED0557T_TBL
-- 論理名：受注入出金機口座テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0557T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0557T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,DENKEI_NO  CHAR(9) NOT NULL --「電計番号」
	,KINYU_KIKAN_CD  CHAR(4) NOT NULL --「金融機関コード」
	,KINYU_KIKAN_SHITEN_CD  CHAR(3) NOT NULL --「金融機関支店コード」
	,KOZA_SHUBETSU_KBN  CHAR(1) NOT NULL --「口座種別区分」
	,KOZA_NO  CHAR(7) NOT NULL --「口座番号」
	,NYUSHUKKINKI_TONYUYO_CARD_NO_1  NUMBER(9,0) DEFAULT '0' NOT NULL --「入出金機投入用カード番号１」
	,NYUSHUKKINKI_TONYUYO_CARD_NO_2  NUMBER(9,0) DEFAULT '0' NOT NULL --「入出金機投入用カード番号２」
	,KOZA_MEIGININ_HKN_NM  VARCHAR2(60) --「口座名義人半角カナ氏名」
	,KOZA_MEIGININ_KANJI_NM  VARCHAR2(60) --「口座名義人漢字氏名」
	,KOZA_SHOSAI_BIKO  VARCHAR2(100) --「口座詳細備考」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0557T_PK PRIMARY KEY(
	 DENKEI_NO
	,  KINYU_KIKAN_CD
	,  KINYU_KIKAN_SHITEN_CD
	,  KOZA_SHUBETSU_KBN
	,  KOZA_NO
	,  NYUSHUKKINKI_TONYUYO_CARD_NO_1
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0557T_TBL IS '受注入出金機口座テーブル'
/

COMMENT ON COLUMN ED0557T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0557T_TBL.DENKEI_NO IS '電計番号'
/
COMMENT ON COLUMN ED0557T_TBL.KINYU_KIKAN_CD IS '金融機関コード'
/
COMMENT ON COLUMN ED0557T_TBL.KINYU_KIKAN_SHITEN_CD IS '金融機関支店コード'
/
COMMENT ON COLUMN ED0557T_TBL.KOZA_SHUBETSU_KBN IS '口座種別区分'
/
COMMENT ON COLUMN ED0557T_TBL.KOZA_NO IS '口座番号'
/
COMMENT ON COLUMN ED0557T_TBL.NYUSHUKKINKI_TONYUYO_CARD_NO_1 IS '入出金機投入用カード番号１'
/
COMMENT ON COLUMN ED0557T_TBL.NYUSHUKKINKI_TONYUYO_CARD_NO_2 IS '入出金機投入用カード番号２'
/
COMMENT ON COLUMN ED0557T_TBL.KOZA_MEIGININ_HKN_NM IS '口座名義人半角カナ氏名'
/
COMMENT ON COLUMN ED0557T_TBL.KOZA_MEIGININ_KANJI_NM IS '口座名義人漢字氏名'
/
COMMENT ON COLUMN ED0557T_TBL.KOZA_SHOSAI_BIKO IS '口座詳細備考'
/
COMMENT ON COLUMN ED0557T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0557T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0557T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0557T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0557T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0557T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0557T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0557T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0557T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0557T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0557T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0557T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
