/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0530T_TBL.sql
-- 物理名：ED0530T_TBL
-- 論理名：運用機械テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0530T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0530T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,UNYO_HENKO_RIREKI_NO  CHAR(10) NOT NULL --「運用変更履歴番号」
	,KIBTI_KG_TRATSKIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備隊鍵取扱有フラグ」
	,TO_CD  CHAR(8) --「棟コード」
	,HOKOKUSHO_TEISHUTSU_BASHO_NM  VARCHAR2(100) --「報告書提出場所名称」
	,JUTAKU_KOSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「住宅戸数」
	,WEB_SITE_RIYOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「Ｗｅｂサイト利用有フラグ」
	,KANKATSU_KEISATSUSHO_NM  VARCHAR2(20) --「管轄警察署名称」
	,KANKATSU_KEISATSUSHO_DENWA_NO  VARCHAR2(20) --「管轄警察署電話番号」
	,KANKATSU_SHOBOSHO_NM  VARCHAR2(20) --「管轄消防署名称」
	,KANKATSU_SHOBOSHO_DENWA_NO  VARCHAR2(20) --「管轄消防署電話番号」
	,UNYOJO_TORIKIME_NAIYO_1  VARCHAR2(30) --「運用上取決め内容１」
	,UNYOJO_TORIKIME_NAIYO_2  VARCHAR2(30) --「運用上取決め内容２」
	,UNYOJO_TORIKIME_NAIYO_3  VARCHAR2(30) --「運用上取決め内容３」
	,UNYOJO_TORIKIME_NAIYO_4  VARCHAR2(30) --「運用上取決め内容４」
	,UNYOJO_TORIKIME_NAIYO_5  VARCHAR2(30) --「運用上取決め内容５」
	,CLIENT_SHMISH_SHY_KGN_YMD  DATE --「クライアント証明書使用期限年月日」
	,KINKYU_SOKUJI_TSUHOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「緊急即時通報有フラグ」
	,SHOBOCHO_TODOKEDE_SHONIN_NO  VARCHAR2(15) --「消防庁届出承認番号」
	,KUMIKOMI_KAISEN_NO  VARCHAR2(20) --「組込回線番号」
	,SHIYO_FUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「使用不可フラグ」
	,GYOMU_KAISHI_YOTEI_YMD  DATE --「業務開始予定年月日」
	,GYOMU_KAISHI_YMD  DATE --「業務開始年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0530T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  UNYO_HENKO_RIREKI_NO
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0530T_TBL IS '運用機械テーブル'
/

COMMENT ON COLUMN ED0530T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0530T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0530T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0530T_TBL.UNYO_HENKO_RIREKI_NO IS '運用変更履歴番号'
/
COMMENT ON COLUMN ED0530T_TBL.KIBTI_KG_TRATSKIAR_FLG IS '警備隊鍵取扱有フラグ'
/
COMMENT ON COLUMN ED0530T_TBL.TO_CD IS '棟コード'
/
COMMENT ON COLUMN ED0530T_TBL.HOKOKUSHO_TEISHUTSU_BASHO_NM IS '報告書提出場所名称'
/
COMMENT ON COLUMN ED0530T_TBL.JUTAKU_KOSU IS '住宅戸数'
/
COMMENT ON COLUMN ED0530T_TBL.WEB_SITE_RIYOARI_FLG IS 'Ｗｅｂサイト利用有フラグ'
/
COMMENT ON COLUMN ED0530T_TBL.KANKATSU_KEISATSUSHO_NM IS '管轄警察署名称'
/
COMMENT ON COLUMN ED0530T_TBL.KANKATSU_KEISATSUSHO_DENWA_NO IS '管轄警察署電話番号'
/
COMMENT ON COLUMN ED0530T_TBL.KANKATSU_SHOBOSHO_NM IS '管轄消防署名称'
/
COMMENT ON COLUMN ED0530T_TBL.KANKATSU_SHOBOSHO_DENWA_NO IS '管轄消防署電話番号'
/
COMMENT ON COLUMN ED0530T_TBL.UNYOJO_TORIKIME_NAIYO_1 IS '運用上取決め内容１'
/
COMMENT ON COLUMN ED0530T_TBL.UNYOJO_TORIKIME_NAIYO_2 IS '運用上取決め内容２'
/
COMMENT ON COLUMN ED0530T_TBL.UNYOJO_TORIKIME_NAIYO_3 IS '運用上取決め内容３'
/
COMMENT ON COLUMN ED0530T_TBL.UNYOJO_TORIKIME_NAIYO_4 IS '運用上取決め内容４'
/
COMMENT ON COLUMN ED0530T_TBL.UNYOJO_TORIKIME_NAIYO_5 IS '運用上取決め内容５'
/
COMMENT ON COLUMN ED0530T_TBL.CLIENT_SHMISH_SHY_KGN_YMD IS 'クライアント証明書使用期限年月日'
/
COMMENT ON COLUMN ED0530T_TBL.KINKYU_SOKUJI_TSUHOARI_FLG IS '緊急即時通報有フラグ'
/
COMMENT ON COLUMN ED0530T_TBL.SHOBOCHO_TODOKEDE_SHONIN_NO IS '消防庁届出承認番号'
/
COMMENT ON COLUMN ED0530T_TBL.KUMIKOMI_KAISEN_NO IS '組込回線番号'
/
COMMENT ON COLUMN ED0530T_TBL.SHIYO_FUKA_FLG IS '使用不可フラグ'
/
COMMENT ON COLUMN ED0530T_TBL.GYOMU_KAISHI_YOTEI_YMD IS '業務開始予定年月日'
/
COMMENT ON COLUMN ED0530T_TBL.GYOMU_KAISHI_YMD IS '業務開始年月日'
/
COMMENT ON COLUMN ED0530T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0530T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0530T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0530T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0530T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0530T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0530T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0530T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0530T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0530T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0530T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0530T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
