/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0657T_TBL.sql
-- 物理名：ED0657T_TBL
-- 論理名：受注試験問題サービステーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0657T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0657T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,SHIKEN_MONDAI_SECURITY_KBN  CHAR(1) NOT NULL --「試験問題セキュリティ区分」
	,SKMD_SECURITY_SERVICE_AR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「試験問題セキュリティサービス有フラグ」
	,SERVICE_KAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「サービス回数」
	,UNYO_SHUBETSU_KBN  CHAR(2) NOT NULL --「運用種別区分」
	,UNKO_NISSU_KBN  CHAR(1) NOT NULL --「運行日数区分」
	,SONOTA_UNKO_KAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「その他運行回数」
	,UNKO_NINZU  NUMBER(9,0) DEFAULT '0' NOT NULL --「運行人数」
	,IDO_JIKAN  NUMBER(12,3) DEFAULT '0' NOT NULL --「移動時間」
	,SAGYO_JIKAN  NUMBER(12,3) DEFAULT '0' NOT NULL --「作業時間」
	,JITSUDO_JIKAN  NUMBER(12,3) DEFAULT '0' NOT NULL --「実働時間」
	,JISSHI_JIKANTAI_KBN  CHAR(2) NOT NULL --「実施時間帯区分」
	,TACHIYORI_TEMPOSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「立寄り店舗数」
	,SOKO_KYORI_KM  NUMBER(12,3) DEFAULT '0' NOT NULL --「走行距離キロメートル」
	,SHIYO_SHARYO_KBN  CHAR(1) NOT NULL --「使用車両区分」
	,SHIYO_SHARYO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「使用車両金額」
	,SHARYO_MAINTENANCE_KBN  CHAR(1) NOT NULL --「車両メンテナンス区分」
	,CHUSHAJO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「駐車場金額」
	,KOSOKU_RYOKIN_TSUSHINHI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「高速料金通信費金額」
	,KOTSUHI_SHUKUHAKUHI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「交通費宿泊費金額」
	,SONOTA_SHOKI_HIYO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「その他初期費用金額」
	,GYM_ITKSK_TRHKSK_CD  CHAR(9) --「業務委託先取引先コード」
	,SERVICE_GOKEI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「サービス合計金額」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0657T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  SHIKEN_MONDAI_SECURITY_KBN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0657T_TBL IS '受注試験問題サービステーブル'
/

COMMENT ON COLUMN ED0657T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0657T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0657T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0657T_TBL.SHIKEN_MONDAI_SECURITY_KBN IS '試験問題セキュリティ区分'
/
COMMENT ON COLUMN ED0657T_TBL.SKMD_SECURITY_SERVICE_AR_FLG IS '試験問題セキュリティサービス有フラグ'
/
COMMENT ON COLUMN ED0657T_TBL.SERVICE_KAISU IS 'サービス回数'
/
COMMENT ON COLUMN ED0657T_TBL.UNYO_SHUBETSU_KBN IS '運用種別区分'
/
COMMENT ON COLUMN ED0657T_TBL.UNKO_NISSU_KBN IS '運行日数区分'
/
COMMENT ON COLUMN ED0657T_TBL.SONOTA_UNKO_KAISU IS 'その他運行回数'
/
COMMENT ON COLUMN ED0657T_TBL.UNKO_NINZU IS '運行人数'
/
COMMENT ON COLUMN ED0657T_TBL.IDO_JIKAN IS '移動時間'
/
COMMENT ON COLUMN ED0657T_TBL.SAGYO_JIKAN IS '作業時間'
/
COMMENT ON COLUMN ED0657T_TBL.JITSUDO_JIKAN IS '実働時間'
/
COMMENT ON COLUMN ED0657T_TBL.JISSHI_JIKANTAI_KBN IS '実施時間帯区分'
/
COMMENT ON COLUMN ED0657T_TBL.TACHIYORI_TEMPOSU IS '立寄り店舗数'
/
COMMENT ON COLUMN ED0657T_TBL.SOKO_KYORI_KM IS '走行距離キロメートル'
/
COMMENT ON COLUMN ED0657T_TBL.SHIYO_SHARYO_KBN IS '使用車両区分'
/
COMMENT ON COLUMN ED0657T_TBL.SHIYO_SHARYO_AMT IS '使用車両金額'
/
COMMENT ON COLUMN ED0657T_TBL.SHARYO_MAINTENANCE_KBN IS '車両メンテナンス区分'
/
COMMENT ON COLUMN ED0657T_TBL.CHUSHAJO_AMT IS '駐車場金額'
/
COMMENT ON COLUMN ED0657T_TBL.KOSOKU_RYOKIN_TSUSHINHI_AMT IS '高速料金通信費金額'
/
COMMENT ON COLUMN ED0657T_TBL.KOTSUHI_SHUKUHAKUHI_AMT IS '交通費宿泊費金額'
/
COMMENT ON COLUMN ED0657T_TBL.SONOTA_SHOKI_HIYO_AMT IS 'その他初期費用金額'
/
COMMENT ON COLUMN ED0657T_TBL.GYM_ITKSK_TRHKSK_CD IS '業務委託先取引先コード'
/
COMMENT ON COLUMN ED0657T_TBL.SERVICE_GOKEI_AMT IS 'サービス合計金額'
/
COMMENT ON COLUMN ED0657T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0657T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0657T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0657T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0657T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0657T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0657T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0657T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0657T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0657T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0657T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0657T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
