/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0649T_TBL.sql
-- 物理名：ED0649T_TBL
-- 論理名：運用インターネット警備システム機械警備実施連絡票テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0649T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0649T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,UNYO_HENKO_RIREKI_NO  CHAR(10) NOT NULL --「運用変更履歴番号」
	,KEIYAKU_BUNRUI_KBN  CHAR(1) NOT NULL --「契約分類区分」
	,ATM_NO  VARCHAR2(4) --「ＡＴＭ番号」
	,GC_GOKI_NO  VARCHAR2(11) --「ＧＣ号機番号」
	,INTERNET_KIB_JSSH_GC_JGYSH_CD  CHAR(6) --「インターネット警備実施ＧＣ事業所コード」
	,INTERNET_KIB_JSSH_GC_JGYSH_NM  VARCHAR2(200) --「インターネット警備実施ＧＣ事業所名称」
	,GYOMU_KAISHI_YMD  DATE --「業務開始年月日」
	,KENSA_YOTEI_YMD  DATE --「検査予定年月日」
	,SEIGYO_SOCHI_HIMMEI_CD  CHAR(8) --「制御装置品名コード」
	,SIGY_SCH_SIGY_SCH_KSH_NM  VARCHAR2(60) --「制御装置制御装置機種名称」
	,KAISEN_SHUBETSU_CD  CHAR(3) --「回線種別コード」
	,KAISEN_SHUBETSU_NM  VARCHAR2(60) --「回線種別名称」
	,KAISEN_JIKKO_SOKUDO  NUMBER(9,0) DEFAULT '0' NOT NULL --「回線実効速度」
	,BACKUP_KISN_JGYSH_DNW_NO  VARCHAR2(20) --「バックアップ回線事業者電話番号」
	,PROVIDER_KAITSUZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「プロバイダ開通済フラグ」
	,PROVIDER_KAITSU_YOTEI_YMD  DATE --「プロバイダ開通予定年月日」
	,PROVIDER_SGTGS_TASSK_DENWA_NO  VARCHAR2(20) --「プロバイダ障害等業者問合せ先電話番号」
	,INTERNET_KAISEN_KAITSUZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「インターネット回線開通済フラグ」
	,INTERNET_KISN_KITS_YTI_YMD  DATE --「インターネット回線開通予定年月日」
	,INTERNET_KISN_SGTGS_TAS_DNW_NO  VARCHAR2(20) --「インターネット回線障害等業者問合せ電話番号」
	,BACKUP_KAISEN_KAITSUZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「バックアップ回線開通済フラグ」
	,BACKUP_KAISEN_KAITSU_YOTEI_YMD  DATE --「バックアップ回線開通予定年月日」
	,BACKUP_KISN_SGTGS_TAS_DENWA_NO  VARCHAR2(20) --「バックアップ回線障害等業者問合せ電話番号」
	,KAISEN_HIKIKOMI_BASHO_NM  VARCHAR2(100) --「回線引込場所名称」
	,INTERNET_KAISEN_KBN  CHAR(1) NOT NULL --「インターネット回線区分」
	,TATEMONO_KOZO_KBN  CHAR(1) NOT NULL --「建物構造区分」
	,KANKATSU_KEISATSUSHO_NM  VARCHAR2(20) --「管轄警察署名称」
	,KANKATSU_KEISATSUSHO_DENWA_NO  VARCHAR2(20) --「管轄警察署電話番号」
	,KANKATSU_SHOBOSHO_NM  VARCHAR2(20) --「管轄消防署名称」
	,KANKATSU_SHOBOSHO_DENWA_NO  VARCHAR2(20) --「管轄消防署電話番号」
	,JOHO_KEIBIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「情報警備有フラグ」
	,INTERNET_JISSHI_TOKKI_JIKO  VARCHAR2(100) --「インターネット実施特記事項」
	,JSSH_JGYSH_GJTS_TNTSH_SHIN_NO  VARCHAR2(8) --「実施事業所技術担当者社員番号」
	,JSSH_JGYSH_EIGY_TNTSH_SHIN_NO  VARCHAR2(8) --「実施事業所営業担当者社員番号」
	,SUB_CHIKU_NM_1  VARCHAR2(30) --「サブ地区名称１」
	,SUB_CHIKU_NM_2  VARCHAR2(30) --「サブ地区名称２」
	,SUB_CHIKU_NM_3  VARCHAR2(30) --「サブ地区名称３」
	,SUB_CHIKU_NM_4  VARCHAR2(30) --「サブ地区名称４」
	,SUB_CHIKU_NM_5  VARCHAR2(30) --「サブ地区名称５」
	,SUB_CHIKU_NM_6  VARCHAR2(30) --「サブ地区名称６」
	,SUB_CHIKU_NM_7  VARCHAR2(30) --「サブ地区名称７」
	,SUB_CHIKU_NM_8  VARCHAR2(30) --「サブ地区名称８」
	,SUB_CHIKU_SETTEIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「サブ地区設定有フラグ」
	,SHUTTER_SEIGYOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「シャッター制御有フラグ」
	,ENKAKU_IKAKU_SOSAARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「遠隔威嚇操作有フラグ」
	,ALMOND_TEMPO_KEITAI_KBN  CHAR(1) NOT NULL --「アマンド店舗形態区分」
	,JUCHU_JIMUSHO_UKETSUKE_YMD  DATE --「受注事務所受付年月日」
	,JISSHI_JIGYOSHO_UKETSUKE_YMD  DATE --「実施事業所受付年月日」
	,JISSHI_JIGYOSHO_TANTO_AREA_NO  CHAR(4) --「実施事業所担当エリア番号」
	,INTERNET_JISSHI_BIKO  VARCHAR2(100) --「インターネット実施備考」
	,GC_UKETSUKE_YMD  DATE --「ＧＣ受付年月日」
	,GAZO_CENTER_UKETSUKE_YMD  DATE --「画像センター受付年月日」
	,MAIN_KAISEN_IP_ADDRESS  VARCHAR2(40) --「メイン回線ＩＰアドレス」
	,BACKUP_KAISEN_IP_ADDRESS  VARCHAR2(40) --「バックアップ回線ＩＰアドレス」
	,SEIJOKEI_GLOBAL_IP_ADDRESS  VARCHAR2(40) --「正常系グローバルＩＰアドレス」
	,SEIJOKEI_LOCAL_IP_ADDRESS  VARCHAR2(40) --「正常系ローカルＩＰアドレス」
	,BACKUP_KEI_GLOBAL_IP_ADDRESS  VARCHAR2(40) --「バックアップ系グローバルＩＰアドレス」
	,BACKUP_KEI_LOCAL_IP_ADDRESS  VARCHAR2(40) --「バックアップ系ローカルＩＰアドレス」
	,SHUKAISEN_PROVIDER_KBN  CHAR(3) NOT NULL --「主回線プロバイダ区分」
	,SHUKAISEN_JIGYOSHA_KBN  CHAR(3) NOT NULL --「主回線事業者区分」
	,FUKUKAISEN_JIGYOSHA_KBN  CHAR(3) NOT NULL --「副回線事業者区分」
	,UNYO_SHUKAISEN_JIGYOSHA_NM  VARCHAR2(30) --「運用主回線事業者名称」
	,UNYO_FUKUKAISEN_JIGYOSHA_NM  VARCHAR2(30) --「運用副回線事業者名称」
	,UNYO_SHUKAISEN_PROVIDER_NM  VARCHAR2(30) --「運用主回線プロバイダ名称」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0649T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  UNYO_HENKO_RIREKI_NO
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0649T_TBL IS '運用インターネット警備システム機械警備実施連絡票テーブル'
/

COMMENT ON COLUMN ED0649T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0649T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0649T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0649T_TBL.UNYO_HENKO_RIREKI_NO IS '運用変更履歴番号'
/
COMMENT ON COLUMN ED0649T_TBL.KEIYAKU_BUNRUI_KBN IS '契約分類区分'
/
COMMENT ON COLUMN ED0649T_TBL.ATM_NO IS 'ＡＴＭ番号'
/
COMMENT ON COLUMN ED0649T_TBL.GC_GOKI_NO IS 'ＧＣ号機番号'
/
COMMENT ON COLUMN ED0649T_TBL.INTERNET_KIB_JSSH_GC_JGYSH_CD IS 'インターネット警備実施ＧＣ事業所コード'
/
COMMENT ON COLUMN ED0649T_TBL.INTERNET_KIB_JSSH_GC_JGYSH_NM IS 'インターネット警備実施ＧＣ事業所名称'
/
COMMENT ON COLUMN ED0649T_TBL.GYOMU_KAISHI_YMD IS '業務開始年月日'
/
COMMENT ON COLUMN ED0649T_TBL.KENSA_YOTEI_YMD IS '検査予定年月日'
/
COMMENT ON COLUMN ED0649T_TBL.SEIGYO_SOCHI_HIMMEI_CD IS '制御装置品名コード'
/
COMMENT ON COLUMN ED0649T_TBL.SIGY_SCH_SIGY_SCH_KSH_NM IS '制御装置制御装置機種名称'
/
COMMENT ON COLUMN ED0649T_TBL.KAISEN_SHUBETSU_CD IS '回線種別コード'
/
COMMENT ON COLUMN ED0649T_TBL.KAISEN_SHUBETSU_NM IS '回線種別名称'
/
COMMENT ON COLUMN ED0649T_TBL.KAISEN_JIKKO_SOKUDO IS '回線実効速度'
/
COMMENT ON COLUMN ED0649T_TBL.BACKUP_KISN_JGYSH_DNW_NO IS 'バックアップ回線事業者電話番号'
/
COMMENT ON COLUMN ED0649T_TBL.PROVIDER_KAITSUZUMI_FLG IS 'プロバイダ開通済フラグ'
/
COMMENT ON COLUMN ED0649T_TBL.PROVIDER_KAITSU_YOTEI_YMD IS 'プロバイダ開通予定年月日'
/
COMMENT ON COLUMN ED0649T_TBL.PROVIDER_SGTGS_TASSK_DENWA_NO IS 'プロバイダ障害等業者問合せ先電話番号'
/
COMMENT ON COLUMN ED0649T_TBL.INTERNET_KAISEN_KAITSUZUMI_FLG IS 'インターネット回線開通済フラグ'
/
COMMENT ON COLUMN ED0649T_TBL.INTERNET_KISN_KITS_YTI_YMD IS 'インターネット回線開通予定年月日'
/
COMMENT ON COLUMN ED0649T_TBL.INTERNET_KISN_SGTGS_TAS_DNW_NO IS 'インターネット回線障害等業者問合せ電話番号'
/
COMMENT ON COLUMN ED0649T_TBL.BACKUP_KAISEN_KAITSUZUMI_FLG IS 'バックアップ回線開通済フラグ'
/
COMMENT ON COLUMN ED0649T_TBL.BACKUP_KAISEN_KAITSU_YOTEI_YMD IS 'バックアップ回線開通予定年月日'
/
COMMENT ON COLUMN ED0649T_TBL.BACKUP_KISN_SGTGS_TAS_DENWA_NO IS 'バックアップ回線障害等業者問合せ電話番号'
/
COMMENT ON COLUMN ED0649T_TBL.KAISEN_HIKIKOMI_BASHO_NM IS '回線引込場所名称'
/
COMMENT ON COLUMN ED0649T_TBL.INTERNET_KAISEN_KBN IS 'インターネット回線区分'
/
COMMENT ON COLUMN ED0649T_TBL.TATEMONO_KOZO_KBN IS '建物構造区分'
/
COMMENT ON COLUMN ED0649T_TBL.KANKATSU_KEISATSUSHO_NM IS '管轄警察署名称'
/
COMMENT ON COLUMN ED0649T_TBL.KANKATSU_KEISATSUSHO_DENWA_NO IS '管轄警察署電話番号'
/
COMMENT ON COLUMN ED0649T_TBL.KANKATSU_SHOBOSHO_NM IS '管轄消防署名称'
/
COMMENT ON COLUMN ED0649T_TBL.KANKATSU_SHOBOSHO_DENWA_NO IS '管轄消防署電話番号'
/
COMMENT ON COLUMN ED0649T_TBL.JOHO_KEIBIARI_FLG IS '情報警備有フラグ'
/
COMMENT ON COLUMN ED0649T_TBL.INTERNET_JISSHI_TOKKI_JIKO IS 'インターネット実施特記事項'
/
COMMENT ON COLUMN ED0649T_TBL.JSSH_JGYSH_GJTS_TNTSH_SHIN_NO IS '実施事業所技術担当者社員番号'
/
COMMENT ON COLUMN ED0649T_TBL.JSSH_JGYSH_EIGY_TNTSH_SHIN_NO IS '実施事業所営業担当者社員番号'
/
COMMENT ON COLUMN ED0649T_TBL.SUB_CHIKU_NM_1 IS 'サブ地区名称１'
/
COMMENT ON COLUMN ED0649T_TBL.SUB_CHIKU_NM_2 IS 'サブ地区名称２'
/
COMMENT ON COLUMN ED0649T_TBL.SUB_CHIKU_NM_3 IS 'サブ地区名称３'
/
COMMENT ON COLUMN ED0649T_TBL.SUB_CHIKU_NM_4 IS 'サブ地区名称４'
/
COMMENT ON COLUMN ED0649T_TBL.SUB_CHIKU_NM_5 IS 'サブ地区名称５'
/
COMMENT ON COLUMN ED0649T_TBL.SUB_CHIKU_NM_6 IS 'サブ地区名称６'
/
COMMENT ON COLUMN ED0649T_TBL.SUB_CHIKU_NM_7 IS 'サブ地区名称７'
/
COMMENT ON COLUMN ED0649T_TBL.SUB_CHIKU_NM_8 IS 'サブ地区名称８'
/
COMMENT ON COLUMN ED0649T_TBL.SUB_CHIKU_SETTEIARI_FLG IS 'サブ地区設定有フラグ'
/
COMMENT ON COLUMN ED0649T_TBL.SHUTTER_SEIGYOARI_FLG IS 'シャッター制御有フラグ'
/
COMMENT ON COLUMN ED0649T_TBL.ENKAKU_IKAKU_SOSAARI_FLG IS '遠隔威嚇操作有フラグ'
/
COMMENT ON COLUMN ED0649T_TBL.ALMOND_TEMPO_KEITAI_KBN IS 'アマンド店舗形態区分'
/
COMMENT ON COLUMN ED0649T_TBL.JUCHU_JIMUSHO_UKETSUKE_YMD IS '受注事務所受付年月日'
/
COMMENT ON COLUMN ED0649T_TBL.JISSHI_JIGYOSHO_UKETSUKE_YMD IS '実施事業所受付年月日'
/
COMMENT ON COLUMN ED0649T_TBL.JISSHI_JIGYOSHO_TANTO_AREA_NO IS '実施事業所担当エリア番号'
/
COMMENT ON COLUMN ED0649T_TBL.INTERNET_JISSHI_BIKO IS 'インターネット実施備考'
/
COMMENT ON COLUMN ED0649T_TBL.GC_UKETSUKE_YMD IS 'ＧＣ受付年月日'
/
COMMENT ON COLUMN ED0649T_TBL.GAZO_CENTER_UKETSUKE_YMD IS '画像センター受付年月日'
/
COMMENT ON COLUMN ED0649T_TBL.MAIN_KAISEN_IP_ADDRESS IS 'メイン回線ＩＰアドレス'
/
COMMENT ON COLUMN ED0649T_TBL.BACKUP_KAISEN_IP_ADDRESS IS 'バックアップ回線ＩＰアドレス'
/
COMMENT ON COLUMN ED0649T_TBL.SEIJOKEI_GLOBAL_IP_ADDRESS IS '正常系グローバルＩＰアドレス'
/
COMMENT ON COLUMN ED0649T_TBL.SEIJOKEI_LOCAL_IP_ADDRESS IS '正常系ローカルＩＰアドレス'
/
COMMENT ON COLUMN ED0649T_TBL.BACKUP_KEI_GLOBAL_IP_ADDRESS IS 'バックアップ系グローバルＩＰアドレス'
/
COMMENT ON COLUMN ED0649T_TBL.BACKUP_KEI_LOCAL_IP_ADDRESS IS 'バックアップ系ローカルＩＰアドレス'
/
COMMENT ON COLUMN ED0649T_TBL.SHUKAISEN_PROVIDER_KBN IS '主回線プロバイダ区分'
/
COMMENT ON COLUMN ED0649T_TBL.SHUKAISEN_JIGYOSHA_KBN IS '主回線事業者区分'
/
COMMENT ON COLUMN ED0649T_TBL.FUKUKAISEN_JIGYOSHA_KBN IS '副回線事業者区分'
/
COMMENT ON COLUMN ED0649T_TBL.UNYO_SHUKAISEN_JIGYOSHA_NM IS '運用主回線事業者名称'
/
COMMENT ON COLUMN ED0649T_TBL.UNYO_FUKUKAISEN_JIGYOSHA_NM IS '運用副回線事業者名称'
/
COMMENT ON COLUMN ED0649T_TBL.UNYO_SHUKAISEN_PROVIDER_NM IS '運用主回線プロバイダ名称'
/
COMMENT ON COLUMN ED0649T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0649T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0649T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0649T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0649T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0649T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0649T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0649T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0649T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0649T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0649T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0649T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
