/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0650T_TBL.sql
-- 物理名：ED0650T_TBL
-- 論理名：工事指示書テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0650T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0650T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_SHIJISHO_NO  CHAR(18) NOT NULL --「工事指示書番号」
	,KOJI_SHIJISHO_SAKUSEI_YMD  DATE --「工事指示書作成年月日」
	,SHOHIN_SERVICE_CD  CHAR(3) --「商品サービスコード」
	,SHOHIN_SERVICE_SHUBETSU_CD  CHAR(3) --「商品サービス種別コード」
	,SHOHIN_SERVICE_NM  VARCHAR2(60) --「商品サービス名称」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,JISSHI_JIGYOSHO_CD  CHAR(6) --「実施事業所コード」
	,KOJI_JISSHI_JIGYOSHO_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「工事実施事業所件数」
	,KEIYAKU_JUCHU_TANTO_SHAIN_NO  VARCHAR2(8) --「契約受注担当社員番号」
	,ANKEN_NO  CHAR(13) --「案件番号」
	,KOJI_KBN  CHAR(1) NOT NULL --「工事区分」
	,KJ_SHJSH_RYYMT_JCH_KIYK_NO  CHAR(15) --「工事指示書流用元受注契約番号」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,KEIYAKUSAKI_TORIHIKISAKI_NM  VARCHAR2(40) --「契約先取引先名称」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,TAISHOSAKI_NM  VARCHAR2(40) --「対象先名称」
	,TAISHOSAKI_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「対象先件数」
	,TAISHOSAKI_JUSHO  VARCHAR2(60) --「対象先住所」
	,TAISHOSAKI_TATEMONO_NM  VARCHAR2(50) --「対象先建物名称」
	,TAISHOSAKI_EIGYO_NAIYO_CD  CHAR(3) --「対象先営業内容コード」
	,TATEMONO_KOJI_SHUBETSU_KBN  CHAR(1) NOT NULL --「建物工事種別区分」
	,KEIBI_TAISHO_KAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「警備対象階数」
	,TATEMONO_SUMPO_TAKASA_M  NUMBER(9,0) DEFAULT '0' NOT NULL --「建物寸法高さメートル」
	,TATEMONO_SUMPOTATE_M  NUMBER(12,3) DEFAULT '0' NOT NULL --「建物寸法縦メートル」
	,TATEMONO_SUMPOYOKO_M  NUMBER(12,3) DEFAULT '0' NOT NULL --「建物寸法横メートル」
	,TATEMONO_SUMPO_MENSEKI  NUMBER(12,3) DEFAULT '0' NOT NULL --「建物寸法面積」
	,KOSHO_SAGYOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「高所作業有フラグ」
	,KOSHO_SAGYOSHAARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「高所作業車有フラグ」
	,ROLLING_TOWER_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ローリングタワー有フラグ」
	,HOJOSHAARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「補助者有フラグ」
	,TASHA_JUMBIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「他社準備有フラグ」
	,TENJO_KOZO_KBN  CHAR(1) NOT NULL --「天井構造区分」
	,TENKENKO_KBN  CHAR(1) NOT NULL --「点検口区分」
	,SHOMEI_KBN  CHAR(1) NOT NULL --「照明区分」
	,TENJOBARI_KBN  CHAR(1) NOT NULL --「天井梁区分」
	,HAISEN_ROSHUTSUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「配線露出有フラグ」
	,JUCHU_TANTOSHA_NAISEN_NO  VARCHAR2(20) --「受注担当者内線番号」
	,JUCHU_TANTOSHA_DENWA_NO  VARCHAR2(20) --「受注担当者電話番号」
	,JUCHU_TANTOSHA_MAIL_ADDRESS  VARCHAR2(200) --「受注担当者メールアドレス」
	,SEKKEI_TANTOSHA_NM  VARCHAR2(60) --「設計担当者氏名」
	,SKKI_TNTSH_SHZK_SSHK_NM  VARCHAR2(200) --「設計担当者所属組織名称」
	,SEKKEI_TANTOSHA_NAISEN_NO  VARCHAR2(20) --「設計担当者内線番号」
	,KJ_OKYKSM_TIAWSSK_TNTSH_NM  VARCHAR2(60) --「工事お客様問合先担当者氏名」
	,KJ_OKYKSM_TIAWSSK_TNTSH_DNW_NO  VARCHAR2(20) --「工事お客様問合先担当者電話番号」
	,KOJI_SAGYO_KAISHI_SHITEI_TM  CHAR(4) --「工事作業開始指定時刻」
	,KOJI_SAGYO_SHURYO_SHITEI_TM  CHAR(4) --「工事作業終了指定時刻」
	,KJ_KB_TRK_SICHSI_TNT_KBN  CHAR(1) NOT NULL --「工事希望登録再調整担当区分」
	,KJ_KBB_TCHAI_TNTSH_HKTSGAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事希望日立会担当者引継有フラグ」
	,KOJIBI_RENRAKU_TANTO_SHAIN_NM  VARCHAR2(60) --「工事日連絡担当社員氏名」
	,KJB_RNRK_TNT_SHIN_DNW_NO  VARCHAR2(20) --「工事日連絡担当社員電話番号」
	,SOSA_SETSUMEI_JIKI_KBN  CHAR(2) NOT NULL --「操作説明時期区分」
	,SOSA_SETSUMEI_SHITEI_YMD  DATE --「操作説明指定年月日」
	,SOSA_SETSUMEI_SHITEI_TM  CHAR(4) --「操作説明指定時刻」
	,SS_STSMI_TNTSH_HKTSG_FLG  CHAR(1) DEFAULT '0' NOT NULL --「操作説明担当者引継フラグ」
	,SOSA_SETSUMEI_TANTOSHA_NM  VARCHAR2(60) --「操作説明担当者氏名」
	,SS_STSMI_TNTSH_DNW_NO  VARCHAR2(20) --「操作説明担当者電話番号」
	,KAGI_YOTAKU_JIKI_KBN  CHAR(2) NOT NULL --「鍵預託時期区分」
	,KAGI_YOTAKU_SHITEI_YMD  DATE --「鍵預託指定年月日」
	,KAGI_YOTAKU_TM  CHAR(4) --「鍵預託時刻」
	,KG_YTK_TNTSH_HKTSG_FLG  CHAR(1) DEFAULT '0' NOT NULL --「鍵預託担当者引継フラグ」
	,KAGI_YOTAKU_TANTOSHA_NM  VARCHAR2(60) --「鍵預託担当者氏名」
	,KAGI_YOTAKU_TANTOSHA_DENWA_NO  VARCHAR2(20) --「鍵預託担当者電話番号」
	,KIKI_SETCHI_KASHO_KAKUNIN_KBN  CHAR(2) NOT NULL --「機器設置箇所確認区分」
	,SHUKAISEN_SHUBETSU_CD  CHAR(3) --「主回線種別コード」
	,SONOTA_SHUKAISEN_SHUBETSU_NM  VARCHAR2(60) --「その他主回線種別名称」
	,SHUKAISEN_SHOYU_KBN  CHAR(1) NOT NULL --「主回線所有区分」
	,SHUKAISEN_CHOSA_KEKKA_CD  CHAR(2) --「主回線調査結果コード」
	,SHUKAISEN_CHOSA_KEKKA_NM  VARCHAR2(60) --「主回線調査結果名称」
	,SHUKAISEN_DEMPA_LEVEL_NAIYO  VARCHAR2(100) --「主回線電波レベル内容」
	,SHUKAISEN_JIGYOSHA_KBN  CHAR(3) NOT NULL --「主回線事業者区分」
	,SONOTA_SHUKAISEN_JIGYOSHA_NM  VARCHAR2(30) --「その他主回線事業者名称」
	,SHUKAISEN_PROVIDER_KBN  CHAR(3) NOT NULL --「主回線プロバイダ区分」
	,SONOTA_SHUKAISEN_PROVIDER_NM  VARCHAR2(30) --「その他主回線プロバイダ名称」
	,SHUKAISEN_KAITSU_JOKYO_KBN  CHAR(1) NOT NULL --「主回線開通状況区分」
	,SHUKAISEN_KAITSU_YOTEI_YMD  DATE --「主回線開通予定年月日」
	,SHKISN_STSZK_BSH_ZMN_KSIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「主回線接続場所図面記載有フラグ」
	,FUKUKAISEN_SHUBETSU_CD  CHAR(3) --「副回線種別コード」
	,SONOTA_FUKUKAISEN_SHUBETSU_NM  VARCHAR2(60) --「その他副回線種別名称」
	,FUKUKAISEN_SHOYU_KBN  CHAR(1) NOT NULL --「副回線所有区分」
	,FUKUKAISEN_CHOSA_KEKKA_CD  CHAR(2) --「副回線調査結果コード」
	,FUKUKAISEN_CHOSA_KEKKA_NM  VARCHAR2(60) --「副回線調査結果名称」
	,FUKUKAISEN_DEMPA_LEVEL_NAIYO  VARCHAR2(100) --「副回線電波レベル内容」
	,FUKUKAISEN_JIGYOSHA_KBN  CHAR(3) NOT NULL --「副回線事業者区分」
	,SONOTA_FUKUKAISEN_JIGYOSHA_NM  VARCHAR2(30) --「その他副回線事業者名称」
	,FUKUKAISEN_PROVIDER_KBN  CHAR(3) NOT NULL --「副回線プロバイダ区分」
	,SONOTA_FUKUKAISEN_PROVIDER_NM  VARCHAR2(30) --「その他副回線プロバイダ名称」
	,FUKUKAISEN_KAITSU_JOKYO_KBN  CHAR(1) NOT NULL --「副回線開通状況区分」
	,FUKUKAISEN_KAITSU_YOTEI_YMD  DATE --「副回線開通予定年月日」
	,FKKISN_STSZK_BSH_ZMN_KSIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「副回線接続場所図面記載有フラグ」
	,IP_ADDRESS_KBN  CHAR(1) NOT NULL --「ＩＰアドレス区分」
	,IP_ADDRESS  VARCHAR2(40) --「ＩＰアドレス」
	,DEFAULT_GATEWAY_ADDRESS  VARCHAR2(40) --「デフォルトゲートウェイアドレス」
	,SUB_NET_MASK_ADDRESS  VARCHAR2(40) --「サブネットマスクアドレス」
	,YUSEN_DNS_SETTEI_NAIYO  VARCHAR2(30) --「優先ＤＮＳ設定内容」
	,DAITAI_DNS_SETTEI_NAIYO  VARCHAR2(30) --「代替ＤＮＳ設定内容」
	,ROUTER_KATASHIKI_NM  VARCHAR2(15) --「ルータ型式名称」
	,ROUTER_STCH_BSH_ZMN_KSIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ルータ設置場所図面記載有フラグ」
	,AKI_PORT_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「空きポート有フラグ」
	,NETWORK_KANRISHAARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ネットワーク管理者有フラグ」
	,NETWORK_KANRISHA_NM  VARCHAR2(60) --「ネットワーク管理者氏名」
	,KOJI_TOJITSU_TACHIAIYO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事当日立会い要フラグ」
	,ANALOG_STSZK_KISN_DNW_NO  VARCHAR2(20) --「アナログ接続回線電話番号」
	,ANALOG_STSZK_KISN_SHBTS_KBN  CHAR(2) NOT NULL --「アナログ接続回線種別区分」
	,TSSHN_KISN_TIJ_HSSHN_STTI_KBN  CHAR(2) NOT NULL --「通信回線定時発信設定区分」
	,KYOSEI_SETSUDAN_SETTEI_KBN  CHAR(2) NOT NULL --「強制切断設定区分」
	,HKKM_BSH_ZMN_KSIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「引込場所図面記載有フラグ」
	,KAISEN_HIKIKOMI_BASHO_NM  VARCHAR2(100) --「回線引込場所名称」
	,KEIBIYO_DENGEN_JOHO_KBN  CHAR(1) NOT NULL --「警備用電源情報区分」
	,KIBY_DNGN_JH_ZMN_KSIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備用電源情報図面記載有フラグ」
	,BUNDEMBAN_AKINASHI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「分電盤空き無フラグ」
	,DNGN_STSZK_BSH_ZMN_KSIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「電源接続場所図面記載有フラグ」
	,DENGEN_SETSUZOKU_BASHO_NM  VARCHAR2(15) --「電源接続場所名称」
	,KEY_BOX_TIMER_JIKAN_SETTEI_KBN  CHAR(2) NOT NULL --「キーボックスタイマ時間設定区分」
	,KEY_BOX_TIMER_NYUKAMBYO_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「キーボックスタイマ入館秒時間」
	,KEY_BOX_TIMER_TAIKAMBYO_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「キーボックスタイマ退館秒時間」
	,ALSOK_LIGHT_SHINGO_SETTEI_KBN  CHAR(2) NOT NULL --「ＡＬＳＯＫライト信号設定区分」
	,ALSOK_LIGHT_BOHANARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫライト防犯有フラグ」
	,ALSOK_LIGHT_HIJOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫライト非常有フラグ」
	,ALSOK_LIGHT_SETSUBIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫライト設備有フラグ」
	,ALSOK_LIGHT_BOSAIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫライト防災有フラグ」
	,ALSOK_LIGHT_HOGOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫライト保護有フラグ」
	,ALSOK_LIGHT_TEIDENARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫライト停電有フラグ」
	,ALSOK_LIGHT_KASAIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫライト火災有フラグ」
	,ALSOK_LIGHT_GAS_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫライトガス有フラグ」
	,ALSOK_LIGHT_DANSENARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫライト断線有フラグ」
	,ALSOK_LIGHT_TAMPER_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫライトタンパ有フラグ」
	,ALSOK_LIGHT_SADOBYO_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「ＡＬＳＯＫライト作動秒時間」
	,IKAKU_BELL_SETTEI_KBN  CHAR(2) NOT NULL --「威嚇ベル設定区分」
	,IKAKU_BELL_BOHANARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「威嚇ベル防犯有フラグ」
	,IKAKU_BELL_HIJOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「威嚇ベル非常有フラグ」
	,IKAKU_BELL_SETSUBIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「威嚇ベル設備有フラグ」
	,IKAKU_BELL_BOSAIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「威嚇ベル防災有フラグ」
	,IKAKU_BELL_HOGOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「威嚇ベル保護有フラグ」
	,IKAKU_BELL_TEIDENARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「威嚇ベル停電有フラグ」
	,IKAKU_BELL_KASAIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「威嚇ベル火災有フラグ」
	,IKAKU_BELL_GAS_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「威嚇ベルガス有フラグ」
	,IKAKU_BELL_DANSENARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「威嚇ベル断線有フラグ」
	,IKAKU_BELL_TAMPER_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「威嚇ベルタンパ有フラグ」
	,IKAKU_BELL_SADOBYO_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「威嚇ベル作動秒時間」
	,DENGEN_SONOTA_SETTEI_NAIYO  VARCHAR2(100) --「電源その他設定内容」
	,KEIBI_KEITAI_KBN  CHAR(2) NOT NULL --「警備形態区分」
	,KEIBI_KEITAI_SONOTA_NAIYO  VARCHAR2(100) --「警備形態その他内容」
	,SENSOR_SHK_ZMN_KSIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「センサ色図面記載有フラグ」
	,TACHIAI_HEYAARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「立会部屋有フラグ」
	,TCHAI_HY_ZMN_KSIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「立会部屋図面記載有フラグ」
	,TACHIAI_HEYA_NM  VARCHAR2(50) --「立会部屋名称」
	,GEMBA_TACHIAI_SHAIN_NM  VARCHAR2(60) --「現場立会社員氏名」
	,RIYO_KANO_CHUSHAJOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「利用可能駐車場有フラグ」
	,CHUSHAJO_ICHI_NAIYO  VARCHAR2(30) --「駐車場位置内容」
	,CHUSHA_KANO_DAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「駐車可能台数」
	,SATSUEI_FUKA_KASHOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「撮影不可箇所有フラグ」
	,STSEI_FK_KSH_ZMN_KSIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「撮影不可箇所図面記載有フラグ」
	,BOHAN_KANSHI_KOMOKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「防犯監視項目有フラグ」
	,HIJO_KANSHI_KOMOKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「非常監視項目有フラグ」
	,KASAI_KANSHI_KOMOKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「火災監視項目有フラグ」
	,SETSUBI_KANSHI_KOMOKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「設備監視項目有フラグ」
	,NYUSHUKKINKI_KOTEI_HOHO_KBN  CHAR(1) NOT NULL --「入出金機固定方法区分」
	,NYSHKKNK_DNGN_JMB_TNT_KBN  CHAR(2) NOT NULL --「入出金機電源準備担当区分」
	,NYSHKKNK_DNGN_HISN_KJAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「入出金機電源配線工事有フラグ」
	,KIKAI_KEIBIKEI_KAISEN_BIKO  VARCHAR2(100) --「機械警備系回線備考」
	,NYUKINKI_KANJOKEI_KAISEN_BIKO  VARCHAR2(100) --「入金機勘定系回線備考」
	,NYUSHUKKINKI_SHIKO_SHIJI_BIKO  VARCHAR2(300) --「入出金機施工指示備考」
	,STSB_KIH_BN_TMP_FILE_AR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「設備警報盤添付ファイル有フラグ」
	,DOJI_YOSHOHIN_SHOHINARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「同時工事要商品有フラグ」
	,DOJI_YOSHOHIN_SHOHIN_BIKO  VARCHAR2(300) --「同時工事要商品備考」
	,YOBO_JIKO_NAIYO  VARCHAR2(500) --「要望事項内容」
	,SHANAI_MOSHIOKURI_JIKO  VARCHAR2(300) --「社内申送り事項」
	,SHANAI_MOSHIOKURI_JIKO_2  VARCHAR2(300) --「社内申送り事項２」
	,SHANAI_MOSHIOKURI_JIKO_3  VARCHAR2(300) --「社内申送り事項３」
	,SHANAI_MOSHIOKURI_JIKO_4  VARCHAR2(300) --「社内申送り事項４」
	,KOJI_SHIJISHO_KAKUNINSHA_NM  VARCHAR2(60) --「工事指示書確認者氏名」
	,KOJI_SHIJISHO_KAKUNIN_YMD  DATE --「工事指示書確認年月日」
	,EIGYO_TANTO_SHAIN_NM  VARCHAR2(60) --「営業担当社員氏名」
	,HA_YO_CONTROLLER_NM  VARCHAR2(40) --「ＨＡ用コントローラ名称」
	,HA_YO_CONTROLLER_SETSUZOKU_KBN  CHAR(2) NOT NULL --「ＨＡ用コントローラ接続区分」
	,UKEIRE_TANTOSHA_NM  VARCHAR2(60) --「受入担当者氏名」
	,EIGYO_NAIYO_KBN  CHAR(3) NOT NULL --「営業内容区分」
	,KOJI_NAIYO  VARCHAR2(100) --「工事内容」
	,TATEMONO_KOZO_KBN  CHAR(1) NOT NULL --「建物構造区分」
	,KOJI_MENSEKI  NUMBER(9,0) DEFAULT '0' NOT NULL --「工事面積」
	,OKYAKUSAMA_TACHIAISHA_NM  VARCHAR2(60) --「お客様立会者氏名」
	,OKYAKUSAMA_TACHIAISHA_DENWA_NO  VARCHAR2(20) --「お客様立会者電話番号」
	,KENSETSU_KAISHA_NM  VARCHAR2(40) --「建設会社名称」
	,SHUNKO_YOTEI_YMD  DATE --「竣工予定年月日」
	,GEMBA_SEKININSHA_NM  VARCHAR2(60) --「現場責任者氏名」
	,GEMBA_SEKININSHA_DENWA_NO  VARCHAR2(20) --「現場責任者電話番号」
	,KIKI_TORIATSUKAI_SETSUMEI_YMD  DATE --「機器取扱説明年月日」
	,KIKI_TORIATSUKAI_SETSUMEI_TM  CHAR(4) --「機器取扱説明時刻」
	,KADO_KAISHI_YOTEI_YMD  DATE --「稼働開始予定年月日」
	,SNT_TIJ_HSSHN_KNKK_NM  VARCHAR2(15) --「その他定時発信間隔名称」
	,SODAN_TOROKUSAKI_KBN  CHAR(2) NOT NULL --「相談登録先区分」
	,SONOTA_SODAN_TOROKUSAKI_NAIYO  VARCHAR2(30) --「その他相談登録先内容」
	,SNT_SDN_TRKSK_RNRKSK_DNW_NO  VARCHAR2(20) --「その他相談登録先連絡先電話番号」
	,JIDO_CHAKUSHIN_SETTEI_KBN  CHAR(2) NOT NULL --「自動着信設定区分」
	,CONTROLLER_SETCHI_HOHO_KBN  CHAR(2) NOT NULL --「コントローラ設置方法区分」
	,CONTROLLER_SCIC_ZMKSA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「コントローラ設置位置図面記載有フラグ」
	,ALSOK_LIGHT_SCIC_ZMKSA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫライト設置位置図面記載有フラグ」
	,LRH_SCIC_ZMKSA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ライフリズムホルダ設置位置図面記載有フラグ」
	,KAIHEI_SENSOR_BIS_DOMEKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「開閉センサビス止め可フラグ」
	,KIHI_SENSOR_IRSHTRAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「開閉センサ色指定有フラグ」
	,KIHI_SENSOR_SHK_STZM_KSA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「開閉センサ色指定図面記載有フラグ」
	,SJ_KKNN_SENSOR_BIS_DMK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「施錠確認センサビス止め可フラグ」
	,SJ_KKNN_SENSOR_IRSHTRAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「施錠確認センサ色指定有フラグ」
	,SJ_KKNN_SENSOR_SK_STZM_KSA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「施錠確認センサ色指定図面記載有フラグ」
	,WIRE_PROTECTOR_IRSHTRAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ワイヤプロテクタ色指定有フラグ」
	,WIRE_PROTECTOR_SK_ZMKSA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ワイヤプロテクタ色図面記載有フラグ」
	,KIKI_SETCHI_ICHI_HENKO_KBN  CHAR(2) NOT NULL --「機器設置位置変更区分」
	,TAISHOSAKI_CHUSHAJO_RIYO_KBN  CHAR(2) NOT NULL --「対象先駐車場利用区分」
	,KANTSUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「貫通可フラグ」
	,GISHTS_TIMER_NYKMBY_JIKAN_KBN  CHAR(2) NOT NULL --「外出タイマ入館秒時間区分」
	,GISHTS_TIMER_TIKMBY_JIKAN_KBN  CHAR(2) NOT NULL --「外出タイマ退館秒時間区分」
	,ZITK_TIMER_NYKMBY_JIKAN_KBN  CHAR(2) NOT NULL --「在宅タイマ入館秒時間区分」
	,ZITK_TIMER_TIKMBY_JIKAN_KBN  CHAR(2) NOT NULL --「在宅タイマ退館秒時間区分」
	,ZITK_KIB_KISHJ_NNSH_UM_KBN  CHAR(1) NOT NULL --「在宅警備開始時認証有無区分」
	,ZITK_KIB_KIJJ_NNSH_UM_KBN  CHAR(1) NOT NULL --「在宅警備解除時認証有無区分」
	,ZTKB_TS_AREA_HKJ_NSUM_KBN  CHAR(1) NOT NULL --「在宅警備対象エリア変更時認証有無区分」
	,CONTROLLER_ONSEI_GENGO_KBN  CHAR(2) NOT NULL --「コントローラ音声言語区分」
	,CONTROLLER_ONSEI_SONOTA_NAIYO  VARCHAR2(30) --「コントローラ音声その他内容」
	,CONTROLLER_SOSA_HOHO_KBN  CHAR(2) NOT NULL --「コントローラ操作方法区分」
	,SEJO_KAKUNIN_KINO_RIYOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「施錠確認機能利用有フラグ」
	,SJ_KKNN_KN_ZMN_KSIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「施錠確認機能図面記載有フラグ」
	,MISEJO_KANSHIBYO_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「未施錠監視秒時間」
	,MSJ_KIKK_TISHG_SIMIDAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「未施錠警告停止後再鳴動有フラグ」
	,MSJ_KIKK_TISHG_SIMID_JIKAN_KBN  CHAR(2) NOT NULL --「未施錠警告停止後再鳴動時間区分」
	,ZAITAKU_ALSOK_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「在宅ＡＬＳＯＫ有フラグ」
	,KAIJOCHU_KYOSEI_LOOP_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「解除中強制ループ有フラグ」
	,CANCEL_REMOCON_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「キャンセルリモコン有フラグ」
	,JUNRO_TIMER_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「順路タイマ有フラグ」
	,KEIBI_SHINDAN_NO  CHAR(17) --「警備診断番号」
	,ANKEN_SHOHIN_SN  CHAR(3) --「案件商品連番」
	,ANKEN_TAISHOSAKI_SN  CHAR(7) --「案件対象先連番」
	,KOJI_SHIJISHO_TOROKUZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事指示書登録済フラグ」
	,SEKISAN_NO  CHAR(17) --「積算番号」
	,KEIYAKU_ID  CHAR(18) --「契約ＩＤ」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「受注契約変更番号」
	,JUCHU_SHORI_KBN  CHAR(2) NOT NULL --「受注処理区分」
	,ALSOK_LGT_A_STTN_DNSN_AR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫライトＡ接点断線有フラグ」
	,IKKBL_A_STTN_DNSN_AR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「威嚇ベルＡ接点断線有フラグ」
	,ALSOK_LIGHT_TSUSN_IJ_AR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫライト通信異常有フラグ」
	,IKKBL_TSUSN_IJ_AR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「威嚇ベル通信異常有フラグ」
	,SENSOR_SETCHI_TAKASA_M  NUMBER(9,0) DEFAULT '0' NOT NULL --「センサ設置高さメートル」
	,KOSHO_SAGYO_SONOTAARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「高所作業その他有フラグ」
	,KOSHO_SAGYO_SONOTA_NAIYO  VARCHAR2(30) --「高所作業その他内容」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0650T_PK PRIMARY KEY(
	 KOJI_SHIJISHO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0650T_TBL IS '工事指示書テーブル'
/

COMMENT ON COLUMN ED0650T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0650T_TBL.KOJI_SHIJISHO_NO IS '工事指示書番号'
/
COMMENT ON COLUMN ED0650T_TBL.KOJI_SHIJISHO_SAKUSEI_YMD IS '工事指示書作成年月日'
/
COMMENT ON COLUMN ED0650T_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED0650T_TBL.SHOHIN_SERVICE_SHUBETSU_CD IS '商品サービス種別コード'
/
COMMENT ON COLUMN ED0650T_TBL.SHOHIN_SERVICE_NM IS '商品サービス名称'
/
COMMENT ON COLUMN ED0650T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0650T_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED0650T_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED0650T_TBL.KOJI_JISSHI_JIGYOSHO_KENSU IS '工事実施事業所件数'
/
COMMENT ON COLUMN ED0650T_TBL.KEIYAKU_JUCHU_TANTO_SHAIN_NO IS '契約受注担当社員番号'
/
COMMENT ON COLUMN ED0650T_TBL.ANKEN_NO IS '案件番号'
/
COMMENT ON COLUMN ED0650T_TBL.KOJI_KBN IS '工事区分'
/
COMMENT ON COLUMN ED0650T_TBL.KJ_SHJSH_RYYMT_JCH_KIYK_NO IS '工事指示書流用元受注契約番号'
/
COMMENT ON COLUMN ED0650T_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED0650T_TBL.KEIYAKUSAKI_TORIHIKISAKI_NM IS '契約先取引先名称'
/
COMMENT ON COLUMN ED0650T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED0650T_TBL.TAISHOSAKI_NM IS '対象先名称'
/
COMMENT ON COLUMN ED0650T_TBL.TAISHOSAKI_KENSU IS '対象先件数'
/
COMMENT ON COLUMN ED0650T_TBL.TAISHOSAKI_JUSHO IS '対象先住所'
/
COMMENT ON COLUMN ED0650T_TBL.TAISHOSAKI_TATEMONO_NM IS '対象先建物名称'
/
COMMENT ON COLUMN ED0650T_TBL.TAISHOSAKI_EIGYO_NAIYO_CD IS '対象先営業内容コード'
/
COMMENT ON COLUMN ED0650T_TBL.TATEMONO_KOJI_SHUBETSU_KBN IS '建物工事種別区分'
/
COMMENT ON COLUMN ED0650T_TBL.KEIBI_TAISHO_KAISU IS '警備対象階数'
/
COMMENT ON COLUMN ED0650T_TBL.TATEMONO_SUMPO_TAKASA_M IS '建物寸法高さメートル'
/
COMMENT ON COLUMN ED0650T_TBL.TATEMONO_SUMPOTATE_M IS '建物寸法縦メートル'
/
COMMENT ON COLUMN ED0650T_TBL.TATEMONO_SUMPOYOKO_M IS '建物寸法横メートル'
/
COMMENT ON COLUMN ED0650T_TBL.TATEMONO_SUMPO_MENSEKI IS '建物寸法面積'
/
COMMENT ON COLUMN ED0650T_TBL.KOSHO_SAGYOARI_FLG IS '高所作業有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.KOSHO_SAGYOSHAARI_FLG IS '高所作業車有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.ROLLING_TOWER_ARI_FLG IS 'ローリングタワー有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.HOJOSHAARI_FLG IS '補助者有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.TASHA_JUMBIARI_FLG IS '他社準備有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.TENJO_KOZO_KBN IS '天井構造区分'
/
COMMENT ON COLUMN ED0650T_TBL.TENKENKO_KBN IS '点検口区分'
/
COMMENT ON COLUMN ED0650T_TBL.SHOMEI_KBN IS '照明区分'
/
COMMENT ON COLUMN ED0650T_TBL.TENJOBARI_KBN IS '天井梁区分'
/
COMMENT ON COLUMN ED0650T_TBL.HAISEN_ROSHUTSUARI_FLG IS '配線露出有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.JUCHU_TANTOSHA_NAISEN_NO IS '受注担当者内線番号'
/
COMMENT ON COLUMN ED0650T_TBL.JUCHU_TANTOSHA_DENWA_NO IS '受注担当者電話番号'
/
COMMENT ON COLUMN ED0650T_TBL.JUCHU_TANTOSHA_MAIL_ADDRESS IS '受注担当者メールアドレス'
/
COMMENT ON COLUMN ED0650T_TBL.SEKKEI_TANTOSHA_NM IS '設計担当者氏名'
/
COMMENT ON COLUMN ED0650T_TBL.SKKI_TNTSH_SHZK_SSHK_NM IS '設計担当者所属組織名称'
/
COMMENT ON COLUMN ED0650T_TBL.SEKKEI_TANTOSHA_NAISEN_NO IS '設計担当者内線番号'
/
COMMENT ON COLUMN ED0650T_TBL.KJ_OKYKSM_TIAWSSK_TNTSH_NM IS '工事お客様問合先担当者氏名'
/
COMMENT ON COLUMN ED0650T_TBL.KJ_OKYKSM_TIAWSSK_TNTSH_DNW_NO IS '工事お客様問合先担当者電話番号'
/
COMMENT ON COLUMN ED0650T_TBL.KOJI_SAGYO_KAISHI_SHITEI_TM IS '工事作業開始指定時刻'
/
COMMENT ON COLUMN ED0650T_TBL.KOJI_SAGYO_SHURYO_SHITEI_TM IS '工事作業終了指定時刻'
/
COMMENT ON COLUMN ED0650T_TBL.KJ_KB_TRK_SICHSI_TNT_KBN IS '工事希望登録再調整担当区分'
/
COMMENT ON COLUMN ED0650T_TBL.KJ_KBB_TCHAI_TNTSH_HKTSGAR_FLG IS '工事希望日立会担当者引継有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.KOJIBI_RENRAKU_TANTO_SHAIN_NM IS '工事日連絡担当社員氏名'
/
COMMENT ON COLUMN ED0650T_TBL.KJB_RNRK_TNT_SHIN_DNW_NO IS '工事日連絡担当社員電話番号'
/
COMMENT ON COLUMN ED0650T_TBL.SOSA_SETSUMEI_JIKI_KBN IS '操作説明時期区分'
/
COMMENT ON COLUMN ED0650T_TBL.SOSA_SETSUMEI_SHITEI_YMD IS '操作説明指定年月日'
/
COMMENT ON COLUMN ED0650T_TBL.SOSA_SETSUMEI_SHITEI_TM IS '操作説明指定時刻'
/
COMMENT ON COLUMN ED0650T_TBL.SS_STSMI_TNTSH_HKTSG_FLG IS '操作説明担当者引継フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.SOSA_SETSUMEI_TANTOSHA_NM IS '操作説明担当者氏名'
/
COMMENT ON COLUMN ED0650T_TBL.SS_STSMI_TNTSH_DNW_NO IS '操作説明担当者電話番号'
/
COMMENT ON COLUMN ED0650T_TBL.KAGI_YOTAKU_JIKI_KBN IS '鍵預託時期区分'
/
COMMENT ON COLUMN ED0650T_TBL.KAGI_YOTAKU_SHITEI_YMD IS '鍵預託指定年月日'
/
COMMENT ON COLUMN ED0650T_TBL.KAGI_YOTAKU_TM IS '鍵預託時刻'
/
COMMENT ON COLUMN ED0650T_TBL.KG_YTK_TNTSH_HKTSG_FLG IS '鍵預託担当者引継フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.KAGI_YOTAKU_TANTOSHA_NM IS '鍵預託担当者氏名'
/
COMMENT ON COLUMN ED0650T_TBL.KAGI_YOTAKU_TANTOSHA_DENWA_NO IS '鍵預託担当者電話番号'
/
COMMENT ON COLUMN ED0650T_TBL.KIKI_SETCHI_KASHO_KAKUNIN_KBN IS '機器設置箇所確認区分'
/
COMMENT ON COLUMN ED0650T_TBL.SHUKAISEN_SHUBETSU_CD IS '主回線種別コード'
/
COMMENT ON COLUMN ED0650T_TBL.SONOTA_SHUKAISEN_SHUBETSU_NM IS 'その他主回線種別名称'
/
COMMENT ON COLUMN ED0650T_TBL.SHUKAISEN_SHOYU_KBN IS '主回線所有区分'
/
COMMENT ON COLUMN ED0650T_TBL.SHUKAISEN_CHOSA_KEKKA_CD IS '主回線調査結果コード'
/
COMMENT ON COLUMN ED0650T_TBL.SHUKAISEN_CHOSA_KEKKA_NM IS '主回線調査結果名称'
/
COMMENT ON COLUMN ED0650T_TBL.SHUKAISEN_DEMPA_LEVEL_NAIYO IS '主回線電波レベル内容'
/
COMMENT ON COLUMN ED0650T_TBL.SHUKAISEN_JIGYOSHA_KBN IS '主回線事業者区分'
/
COMMENT ON COLUMN ED0650T_TBL.SONOTA_SHUKAISEN_JIGYOSHA_NM IS 'その他主回線事業者名称'
/
COMMENT ON COLUMN ED0650T_TBL.SHUKAISEN_PROVIDER_KBN IS '主回線プロバイダ区分'
/
COMMENT ON COLUMN ED0650T_TBL.SONOTA_SHUKAISEN_PROVIDER_NM IS 'その他主回線プロバイダ名称'
/
COMMENT ON COLUMN ED0650T_TBL.SHUKAISEN_KAITSU_JOKYO_KBN IS '主回線開通状況区分'
/
COMMENT ON COLUMN ED0650T_TBL.SHUKAISEN_KAITSU_YOTEI_YMD IS '主回線開通予定年月日'
/
COMMENT ON COLUMN ED0650T_TBL.SHKISN_STSZK_BSH_ZMN_KSIAR_FLG IS '主回線接続場所図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.FUKUKAISEN_SHUBETSU_CD IS '副回線種別コード'
/
COMMENT ON COLUMN ED0650T_TBL.SONOTA_FUKUKAISEN_SHUBETSU_NM IS 'その他副回線種別名称'
/
COMMENT ON COLUMN ED0650T_TBL.FUKUKAISEN_SHOYU_KBN IS '副回線所有区分'
/
COMMENT ON COLUMN ED0650T_TBL.FUKUKAISEN_CHOSA_KEKKA_CD IS '副回線調査結果コード'
/
COMMENT ON COLUMN ED0650T_TBL.FUKUKAISEN_CHOSA_KEKKA_NM IS '副回線調査結果名称'
/
COMMENT ON COLUMN ED0650T_TBL.FUKUKAISEN_DEMPA_LEVEL_NAIYO IS '副回線電波レベル内容'
/
COMMENT ON COLUMN ED0650T_TBL.FUKUKAISEN_JIGYOSHA_KBN IS '副回線事業者区分'
/
COMMENT ON COLUMN ED0650T_TBL.SONOTA_FUKUKAISEN_JIGYOSHA_NM IS 'その他副回線事業者名称'
/
COMMENT ON COLUMN ED0650T_TBL.FUKUKAISEN_PROVIDER_KBN IS '副回線プロバイダ区分'
/
COMMENT ON COLUMN ED0650T_TBL.SONOTA_FUKUKAISEN_PROVIDER_NM IS 'その他副回線プロバイダ名称'
/
COMMENT ON COLUMN ED0650T_TBL.FUKUKAISEN_KAITSU_JOKYO_KBN IS '副回線開通状況区分'
/
COMMENT ON COLUMN ED0650T_TBL.FUKUKAISEN_KAITSU_YOTEI_YMD IS '副回線開通予定年月日'
/
COMMENT ON COLUMN ED0650T_TBL.FKKISN_STSZK_BSH_ZMN_KSIAR_FLG IS '副回線接続場所図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.IP_ADDRESS_KBN IS 'ＩＰアドレス区分'
/
COMMENT ON COLUMN ED0650T_TBL.IP_ADDRESS IS 'ＩＰアドレス'
/
COMMENT ON COLUMN ED0650T_TBL.DEFAULT_GATEWAY_ADDRESS IS 'デフォルトゲートウェイアドレス'
/
COMMENT ON COLUMN ED0650T_TBL.SUB_NET_MASK_ADDRESS IS 'サブネットマスクアドレス'
/
COMMENT ON COLUMN ED0650T_TBL.YUSEN_DNS_SETTEI_NAIYO IS '優先ＤＮＳ設定内容'
/
COMMENT ON COLUMN ED0650T_TBL.DAITAI_DNS_SETTEI_NAIYO IS '代替ＤＮＳ設定内容'
/
COMMENT ON COLUMN ED0650T_TBL.ROUTER_KATASHIKI_NM IS 'ルータ型式名称'
/
COMMENT ON COLUMN ED0650T_TBL.ROUTER_STCH_BSH_ZMN_KSIAR_FLG IS 'ルータ設置場所図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.AKI_PORT_ARI_FLG IS '空きポート有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.NETWORK_KANRISHAARI_FLG IS 'ネットワーク管理者有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.NETWORK_KANRISHA_NM IS 'ネットワーク管理者氏名'
/
COMMENT ON COLUMN ED0650T_TBL.KOJI_TOJITSU_TACHIAIYO_FLG IS '工事当日立会い要フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.ANALOG_STSZK_KISN_DNW_NO IS 'アナログ接続回線電話番号'
/
COMMENT ON COLUMN ED0650T_TBL.ANALOG_STSZK_KISN_SHBTS_KBN IS 'アナログ接続回線種別区分'
/
COMMENT ON COLUMN ED0650T_TBL.TSSHN_KISN_TIJ_HSSHN_STTI_KBN IS '通信回線定時発信設定区分'
/
COMMENT ON COLUMN ED0650T_TBL.KYOSEI_SETSUDAN_SETTEI_KBN IS '強制切断設定区分'
/
COMMENT ON COLUMN ED0650T_TBL.HKKM_BSH_ZMN_KSIAR_FLG IS '引込場所図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.KAISEN_HIKIKOMI_BASHO_NM IS '回線引込場所名称'
/
COMMENT ON COLUMN ED0650T_TBL.KEIBIYO_DENGEN_JOHO_KBN IS '警備用電源情報区分'
/
COMMENT ON COLUMN ED0650T_TBL.KIBY_DNGN_JH_ZMN_KSIAR_FLG IS '警備用電源情報図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.BUNDEMBAN_AKINASHI_FLG IS '分電盤空き無フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.DNGN_STSZK_BSH_ZMN_KSIAR_FLG IS '電源接続場所図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.DENGEN_SETSUZOKU_BASHO_NM IS '電源接続場所名称'
/
COMMENT ON COLUMN ED0650T_TBL.KEY_BOX_TIMER_JIKAN_SETTEI_KBN IS 'キーボックスタイマ時間設定区分'
/
COMMENT ON COLUMN ED0650T_TBL.KEY_BOX_TIMER_NYUKAMBYO_JIKAN IS 'キーボックスタイマ入館秒時間'
/
COMMENT ON COLUMN ED0650T_TBL.KEY_BOX_TIMER_TAIKAMBYO_JIKAN IS 'キーボックスタイマ退館秒時間'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LIGHT_SHINGO_SETTEI_KBN IS 'ＡＬＳＯＫライト信号設定区分'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LIGHT_BOHANARI_FLG IS 'ＡＬＳＯＫライト防犯有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LIGHT_HIJOARI_FLG IS 'ＡＬＳＯＫライト非常有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LIGHT_SETSUBIARI_FLG IS 'ＡＬＳＯＫライト設備有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LIGHT_BOSAIARI_FLG IS 'ＡＬＳＯＫライト防災有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LIGHT_HOGOARI_FLG IS 'ＡＬＳＯＫライト保護有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LIGHT_TEIDENARI_FLG IS 'ＡＬＳＯＫライト停電有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LIGHT_KASAIARI_FLG IS 'ＡＬＳＯＫライト火災有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LIGHT_GAS_ARI_FLG IS 'ＡＬＳＯＫライトガス有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LIGHT_DANSENARI_FLG IS 'ＡＬＳＯＫライト断線有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LIGHT_TAMPER_ARI_FLG IS 'ＡＬＳＯＫライトタンパ有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LIGHT_SADOBYO_JIKAN IS 'ＡＬＳＯＫライト作動秒時間'
/
COMMENT ON COLUMN ED0650T_TBL.IKAKU_BELL_SETTEI_KBN IS '威嚇ベル設定区分'
/
COMMENT ON COLUMN ED0650T_TBL.IKAKU_BELL_BOHANARI_FLG IS '威嚇ベル防犯有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.IKAKU_BELL_HIJOARI_FLG IS '威嚇ベル非常有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.IKAKU_BELL_SETSUBIARI_FLG IS '威嚇ベル設備有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.IKAKU_BELL_BOSAIARI_FLG IS '威嚇ベル防災有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.IKAKU_BELL_HOGOARI_FLG IS '威嚇ベル保護有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.IKAKU_BELL_TEIDENARI_FLG IS '威嚇ベル停電有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.IKAKU_BELL_KASAIARI_FLG IS '威嚇ベル火災有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.IKAKU_BELL_GAS_ARI_FLG IS '威嚇ベルガス有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.IKAKU_BELL_DANSENARI_FLG IS '威嚇ベル断線有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.IKAKU_BELL_TAMPER_ARI_FLG IS '威嚇ベルタンパ有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.IKAKU_BELL_SADOBYO_JIKAN IS '威嚇ベル作動秒時間'
/
COMMENT ON COLUMN ED0650T_TBL.DENGEN_SONOTA_SETTEI_NAIYO IS '電源その他設定内容'
/
COMMENT ON COLUMN ED0650T_TBL.KEIBI_KEITAI_KBN IS '警備形態区分'
/
COMMENT ON COLUMN ED0650T_TBL.KEIBI_KEITAI_SONOTA_NAIYO IS '警備形態その他内容'
/
COMMENT ON COLUMN ED0650T_TBL.SENSOR_SHK_ZMN_KSIAR_FLG IS 'センサ色図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.TACHIAI_HEYAARI_FLG IS '立会部屋有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.TCHAI_HY_ZMN_KSIAR_FLG IS '立会部屋図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.TACHIAI_HEYA_NM IS '立会部屋名称'
/
COMMENT ON COLUMN ED0650T_TBL.GEMBA_TACHIAI_SHAIN_NM IS '現場立会社員氏名'
/
COMMENT ON COLUMN ED0650T_TBL.RIYO_KANO_CHUSHAJOARI_FLG IS '利用可能駐車場有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.CHUSHAJO_ICHI_NAIYO IS '駐車場位置内容'
/
COMMENT ON COLUMN ED0650T_TBL.CHUSHA_KANO_DAISU IS '駐車可能台数'
/
COMMENT ON COLUMN ED0650T_TBL.SATSUEI_FUKA_KASHOARI_FLG IS '撮影不可箇所有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.STSEI_FK_KSH_ZMN_KSIAR_FLG IS '撮影不可箇所図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.BOHAN_KANSHI_KOMOKUARI_FLG IS '防犯監視項目有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.HIJO_KANSHI_KOMOKUARI_FLG IS '非常監視項目有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.KASAI_KANSHI_KOMOKUARI_FLG IS '火災監視項目有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.SETSUBI_KANSHI_KOMOKUARI_FLG IS '設備監視項目有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.NYUSHUKKINKI_KOTEI_HOHO_KBN IS '入出金機固定方法区分'
/
COMMENT ON COLUMN ED0650T_TBL.NYSHKKNK_DNGN_JMB_TNT_KBN IS '入出金機電源準備担当区分'
/
COMMENT ON COLUMN ED0650T_TBL.NYSHKKNK_DNGN_HISN_KJAR_FLG IS '入出金機電源配線工事有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.KIKAI_KEIBIKEI_KAISEN_BIKO IS '機械警備系回線備考'
/
COMMENT ON COLUMN ED0650T_TBL.NYUKINKI_KANJOKEI_KAISEN_BIKO IS '入金機勘定系回線備考'
/
COMMENT ON COLUMN ED0650T_TBL.NYUSHUKKINKI_SHIKO_SHIJI_BIKO IS '入出金機施工指示備考'
/
COMMENT ON COLUMN ED0650T_TBL.STSB_KIH_BN_TMP_FILE_AR_FLG IS '設備警報盤添付ファイル有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.DOJI_YOSHOHIN_SHOHINARI_FLG IS '同時工事要商品有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.DOJI_YOSHOHIN_SHOHIN_BIKO IS '同時工事要商品備考'
/
COMMENT ON COLUMN ED0650T_TBL.YOBO_JIKO_NAIYO IS '要望事項内容'
/
COMMENT ON COLUMN ED0650T_TBL.SHANAI_MOSHIOKURI_JIKO IS '社内申送り事項'
/
COMMENT ON COLUMN ED0650T_TBL.SHANAI_MOSHIOKURI_JIKO_2 IS '社内申送り事項２'
/
COMMENT ON COLUMN ED0650T_TBL.SHANAI_MOSHIOKURI_JIKO_3 IS '社内申送り事項３'
/
COMMENT ON COLUMN ED0650T_TBL.SHANAI_MOSHIOKURI_JIKO_4 IS '社内申送り事項４'
/
COMMENT ON COLUMN ED0650T_TBL.KOJI_SHIJISHO_KAKUNINSHA_NM IS '工事指示書確認者氏名'
/
COMMENT ON COLUMN ED0650T_TBL.KOJI_SHIJISHO_KAKUNIN_YMD IS '工事指示書確認年月日'
/
COMMENT ON COLUMN ED0650T_TBL.EIGYO_TANTO_SHAIN_NM IS '営業担当社員氏名'
/
COMMENT ON COLUMN ED0650T_TBL.HA_YO_CONTROLLER_NM IS 'ＨＡ用コントローラ名称'
/
COMMENT ON COLUMN ED0650T_TBL.HA_YO_CONTROLLER_SETSUZOKU_KBN IS 'ＨＡ用コントローラ接続区分'
/
COMMENT ON COLUMN ED0650T_TBL.UKEIRE_TANTOSHA_NM IS '受入担当者氏名'
/
COMMENT ON COLUMN ED0650T_TBL.EIGYO_NAIYO_KBN IS '営業内容区分'
/
COMMENT ON COLUMN ED0650T_TBL.KOJI_NAIYO IS '工事内容'
/
COMMENT ON COLUMN ED0650T_TBL.TATEMONO_KOZO_KBN IS '建物構造区分'
/
COMMENT ON COLUMN ED0650T_TBL.KOJI_MENSEKI IS '工事面積'
/
COMMENT ON COLUMN ED0650T_TBL.OKYAKUSAMA_TACHIAISHA_NM IS 'お客様立会者氏名'
/
COMMENT ON COLUMN ED0650T_TBL.OKYAKUSAMA_TACHIAISHA_DENWA_NO IS 'お客様立会者電話番号'
/
COMMENT ON COLUMN ED0650T_TBL.KENSETSU_KAISHA_NM IS '建設会社名称'
/
COMMENT ON COLUMN ED0650T_TBL.SHUNKO_YOTEI_YMD IS '竣工予定年月日'
/
COMMENT ON COLUMN ED0650T_TBL.GEMBA_SEKININSHA_NM IS '現場責任者氏名'
/
COMMENT ON COLUMN ED0650T_TBL.GEMBA_SEKININSHA_DENWA_NO IS '現場責任者電話番号'
/
COMMENT ON COLUMN ED0650T_TBL.KIKI_TORIATSUKAI_SETSUMEI_YMD IS '機器取扱説明年月日'
/
COMMENT ON COLUMN ED0650T_TBL.KIKI_TORIATSUKAI_SETSUMEI_TM IS '機器取扱説明時刻'
/
COMMENT ON COLUMN ED0650T_TBL.KADO_KAISHI_YOTEI_YMD IS '稼働開始予定年月日'
/
COMMENT ON COLUMN ED0650T_TBL.SNT_TIJ_HSSHN_KNKK_NM IS 'その他定時発信間隔名称'
/
COMMENT ON COLUMN ED0650T_TBL.SODAN_TOROKUSAKI_KBN IS '相談登録先区分'
/
COMMENT ON COLUMN ED0650T_TBL.SONOTA_SODAN_TOROKUSAKI_NAIYO IS 'その他相談登録先内容'
/
COMMENT ON COLUMN ED0650T_TBL.SNT_SDN_TRKSK_RNRKSK_DNW_NO IS 'その他相談登録先連絡先電話番号'
/
COMMENT ON COLUMN ED0650T_TBL.JIDO_CHAKUSHIN_SETTEI_KBN IS '自動着信設定区分'
/
COMMENT ON COLUMN ED0650T_TBL.CONTROLLER_SETCHI_HOHO_KBN IS 'コントローラ設置方法区分'
/
COMMENT ON COLUMN ED0650T_TBL.CONTROLLER_SCIC_ZMKSA_FLG IS 'コントローラ設置位置図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LIGHT_SCIC_ZMKSA_FLG IS 'ＡＬＳＯＫライト設置位置図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.LRH_SCIC_ZMKSA_FLG IS 'ライフリズムホルダ設置位置図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.KAIHEI_SENSOR_BIS_DOMEKA_FLG IS '開閉センサビス止め可フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.KIHI_SENSOR_IRSHTRAR_FLG IS '開閉センサ色指定有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.KIHI_SENSOR_SHK_STZM_KSA_FLG IS '開閉センサ色指定図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.SJ_KKNN_SENSOR_BIS_DMK_FLG IS '施錠確認センサビス止め可フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.SJ_KKNN_SENSOR_IRSHTRAR_FLG IS '施錠確認センサ色指定有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.SJ_KKNN_SENSOR_SK_STZM_KSA_FLG IS '施錠確認センサ色指定図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.WIRE_PROTECTOR_IRSHTRAR_FLG IS 'ワイヤプロテクタ色指定有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.WIRE_PROTECTOR_SK_ZMKSA_FLG IS 'ワイヤプロテクタ色図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.KIKI_SETCHI_ICHI_HENKO_KBN IS '機器設置位置変更区分'
/
COMMENT ON COLUMN ED0650T_TBL.TAISHOSAKI_CHUSHAJO_RIYO_KBN IS '対象先駐車場利用区分'
/
COMMENT ON COLUMN ED0650T_TBL.KANTSUKA_FLG IS '貫通可フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.GISHTS_TIMER_NYKMBY_JIKAN_KBN IS '外出タイマ入館秒時間区分'
/
COMMENT ON COLUMN ED0650T_TBL.GISHTS_TIMER_TIKMBY_JIKAN_KBN IS '外出タイマ退館秒時間区分'
/
COMMENT ON COLUMN ED0650T_TBL.ZITK_TIMER_NYKMBY_JIKAN_KBN IS '在宅タイマ入館秒時間区分'
/
COMMENT ON COLUMN ED0650T_TBL.ZITK_TIMER_TIKMBY_JIKAN_KBN IS '在宅タイマ退館秒時間区分'
/
COMMENT ON COLUMN ED0650T_TBL.ZITK_KIB_KISHJ_NNSH_UM_KBN IS '在宅警備開始時認証有無区分'
/
COMMENT ON COLUMN ED0650T_TBL.ZITK_KIB_KIJJ_NNSH_UM_KBN IS '在宅警備解除時認証有無区分'
/
COMMENT ON COLUMN ED0650T_TBL.ZTKB_TS_AREA_HKJ_NSUM_KBN IS '在宅警備対象エリア変更時認証有無区分'
/
COMMENT ON COLUMN ED0650T_TBL.CONTROLLER_ONSEI_GENGO_KBN IS 'コントローラ音声言語区分'
/
COMMENT ON COLUMN ED0650T_TBL.CONTROLLER_ONSEI_SONOTA_NAIYO IS 'コントローラ音声その他内容'
/
COMMENT ON COLUMN ED0650T_TBL.CONTROLLER_SOSA_HOHO_KBN IS 'コントローラ操作方法区分'
/
COMMENT ON COLUMN ED0650T_TBL.SEJO_KAKUNIN_KINO_RIYOARI_FLG IS '施錠確認機能利用有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.SJ_KKNN_KN_ZMN_KSIAR_FLG IS '施錠確認機能図面記載有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.MISEJO_KANSHIBYO_JIKAN IS '未施錠監視秒時間'
/
COMMENT ON COLUMN ED0650T_TBL.MSJ_KIKK_TISHG_SIMIDAR_FLG IS '未施錠警告停止後再鳴動有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.MSJ_KIKK_TISHG_SIMID_JIKAN_KBN IS '未施錠警告停止後再鳴動時間区分'
/
COMMENT ON COLUMN ED0650T_TBL.ZAITAKU_ALSOK_ARI_FLG IS '在宅ＡＬＳＯＫ有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.KAIJOCHU_KYOSEI_LOOP_ARI_FLG IS '解除中強制ループ有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.CANCEL_REMOCON_ARI_FLG IS 'キャンセルリモコン有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.JUNRO_TIMER_ARI_FLG IS '順路タイマ有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.KEIBI_SHINDAN_NO IS '警備診断番号'
/
COMMENT ON COLUMN ED0650T_TBL.ANKEN_SHOHIN_SN IS '案件商品連番'
/
COMMENT ON COLUMN ED0650T_TBL.ANKEN_TAISHOSAKI_SN IS '案件対象先連番'
/
COMMENT ON COLUMN ED0650T_TBL.KOJI_SHIJISHO_TOROKUZUMI_FLG IS '工事指示書登録済フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.SEKISAN_NO IS '積算番号'
/
COMMENT ON COLUMN ED0650T_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED0650T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0650T_TBL.JUCHU_SHORI_KBN IS '受注処理区分'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LGT_A_STTN_DNSN_AR_FLG IS 'ＡＬＳＯＫライトＡ接点断線有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.IKKBL_A_STTN_DNSN_AR_FLG IS '威嚇ベルＡ接点断線有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.ALSOK_LIGHT_TSUSN_IJ_AR_FLG IS 'ＡＬＳＯＫライト通信異常有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.IKKBL_TSUSN_IJ_AR_FLG IS '威嚇ベル通信異常有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.SENSOR_SETCHI_TAKASA_M IS 'センサ設置高さメートル'
/
COMMENT ON COLUMN ED0650T_TBL.KOSHO_SAGYO_SONOTAARI_FLG IS '高所作業その他有フラグ'
/
COMMENT ON COLUMN ED0650T_TBL.KOSHO_SAGYO_SONOTA_NAIYO IS '高所作業その他内容'
/
COMMENT ON COLUMN ED0650T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0650T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0650T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0650T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0650T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0650T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0650T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0650T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0650T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0650T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0650T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0650T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
