/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0668T_TBL.sql
-- 物理名：ED0668T_TBL
-- 論理名：運用台帳連絡票テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0668T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0668T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,UNYO_HENKO_RIREKI_NO  CHAR(10) NOT NULL --「運用変更履歴番号」
	,KEIBI_KEIKAKU_SHURUI_KBN  CHAR(1) NOT NULL --「警備計画種類区分」
	,KEY_BOX_ICHI_KBN  CHAR(1) NOT NULL --「キーボックス位置区分」
	,KEIBI_TAISHOBUTSU_TOKKI_JIKO  VARCHAR2(100) --「警備対象物特記事項」
	,KEIBI_KAIRO_TOKUCHO_NAIYO  VARCHAR2(100) --「警備回路特長内容」
	,TATEMONO_ZEIJAKU_BUBUN_NAIYO  VARCHAR2(60) --「建物脆弱部分内容」
	,TAIKISHO_CD  CHAR(4) --「待機所コード」
	,KEIYUSAKI_NM_1  VARCHAR2(10) --「経由先名称１」
	,KEIYUSAKI_NM_2  VARCHAR2(10) --「経由先名称２」
	,SOKO_KYORI_KM  NUMBER(12,3) DEFAULT '0' NOT NULL --「走行距離キロメートル」
	,TAIKISHO_SHOYO_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「待機所所要時間」
	,KNKI_RNRKSK_DNWKYK_NM  VARCHAR2(20) --「関係連絡先電話局名称」
	,KNKI_RNRKSK_DNWKYK_DNW_NO  VARCHAR2(20) --「関係連絡先電話局電話番号」
	,KNKI_RNRKSK_DNRYK_GISH_NM  VARCHAR2(40) --「関係連絡先電力会社名称」
	,KNKI_RNRKSK_DNRYK_GISH_DNW_NO  VARCHAR2(20) --「関係連絡先電力会社電話番号」
	,KNKI_RNRKSK_GAS_GISH_NM  VARCHAR2(40) --「関係連絡先ガス会社名称」
	,KNKI_RNRKSK_GAS_GISH_DNW_NO  VARCHAR2(20) --「関係連絡先ガス会社電話番号」
	,SONOTA_KANKEI_RENRAKUSAKI_NM_1  VARCHAR2(20) --「その他関係連絡先名称１」
	,SNT_KNKI_RNRKSK_DNW_NO_1  VARCHAR2(20) --「その他関係連絡先電話番号１」
	,SONOTA_KANKEI_RENRAKUSAKI_NM_2  VARCHAR2(20) --「その他関係連絡先名称２」
	,SNT_KNKI_RNRKSK_DNW_NO_2  VARCHAR2(20) --「その他関係連絡先電話番号２」
	,KIBSK_KYJ_KNRNNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備先居住管理人有フラグ」
	,KIBSK_KYJ_KNRNN_DNW_NO  VARCHAR2(20) --「警備先居住管理人電話番号」
	,KIBSK_KNRN_KYJ_KNRNNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備先近隣居住管理人有フラグ」
	,KIBSK_KNRN_KYJ_KNRNN_DNW_NO  VARCHAR2(20) --「警備先近隣居住管理人電話番号」
	,SNT_KNKI_RNRKSKAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「その他関係連絡先有フラグ」
	,SONOTA_KANKEI_RENRAKUSAKI_NM  VARCHAR2(20) --「その他関係連絡先名称」
	,SNT_KNKI_RNRKSK_DNW_NO  VARCHAR2(20) --「その他関係連絡先電話番号」
	,KEIBI_KEIKAKU_MOKUHYO_NAIYO  VARCHAR2(20) --「警備計画目標内容」
	,KEIBI_KEIKAKU_BIKO  VARCHAR2(150) --「警備計画備考」
	,GC_GOKI_NO  VARCHAR2(11) --「ＧＣ号機番号」
	,GC_UKETSUKE_YMD  DATE --「ＧＣ受付年月日」
	,GC_ZUMEN_JURYOZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＧＣ図面受領済フラグ」
	,GC_KINREN_JURYOZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＧＣ緊連受領済フラグ」
	,KKI_KIB_JSSH_RNRKHY_BIKO  VARCHAR2(150) --「機械警備実施連絡票備考」
	,KEIYAKUSAKI_TANTOSHA_KN_NM  VARCHAR2(90) --「契約先担当者カナ氏名」
	,TAISHOSAKI_TANTOSHA_KN_NM  VARCHAR2(90) --「対象先担当者カナ氏名」
	,TAIKISHO_NM  VARCHAR2(40) --「待機所名称」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0668T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  UNYO_HENKO_RIREKI_NO
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0668T_TBL IS '運用台帳連絡票テーブル'
/

COMMENT ON COLUMN ED0668T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0668T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0668T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0668T_TBL.UNYO_HENKO_RIREKI_NO IS '運用変更履歴番号'
/
COMMENT ON COLUMN ED0668T_TBL.KEIBI_KEIKAKU_SHURUI_KBN IS '警備計画種類区分'
/
COMMENT ON COLUMN ED0668T_TBL.KEY_BOX_ICHI_KBN IS 'キーボックス位置区分'
/
COMMENT ON COLUMN ED0668T_TBL.KEIBI_TAISHOBUTSU_TOKKI_JIKO IS '警備対象物特記事項'
/
COMMENT ON COLUMN ED0668T_TBL.KEIBI_KAIRO_TOKUCHO_NAIYO IS '警備回路特長内容'
/
COMMENT ON COLUMN ED0668T_TBL.TATEMONO_ZEIJAKU_BUBUN_NAIYO IS '建物脆弱部分内容'
/
COMMENT ON COLUMN ED0668T_TBL.TAIKISHO_CD IS '待機所コード'
/
COMMENT ON COLUMN ED0668T_TBL.KEIYUSAKI_NM_1 IS '経由先名称１'
/
COMMENT ON COLUMN ED0668T_TBL.KEIYUSAKI_NM_2 IS '経由先名称２'
/
COMMENT ON COLUMN ED0668T_TBL.SOKO_KYORI_KM IS '走行距離キロメートル'
/
COMMENT ON COLUMN ED0668T_TBL.TAIKISHO_SHOYO_JIKAN IS '待機所所要時間'
/
COMMENT ON COLUMN ED0668T_TBL.KNKI_RNRKSK_DNWKYK_NM IS '関係連絡先電話局名称'
/
COMMENT ON COLUMN ED0668T_TBL.KNKI_RNRKSK_DNWKYK_DNW_NO IS '関係連絡先電話局電話番号'
/
COMMENT ON COLUMN ED0668T_TBL.KNKI_RNRKSK_DNRYK_GISH_NM IS '関係連絡先電力会社名称'
/
COMMENT ON COLUMN ED0668T_TBL.KNKI_RNRKSK_DNRYK_GISH_DNW_NO IS '関係連絡先電力会社電話番号'
/
COMMENT ON COLUMN ED0668T_TBL.KNKI_RNRKSK_GAS_GISH_NM IS '関係連絡先ガス会社名称'
/
COMMENT ON COLUMN ED0668T_TBL.KNKI_RNRKSK_GAS_GISH_DNW_NO IS '関係連絡先ガス会社電話番号'
/
COMMENT ON COLUMN ED0668T_TBL.SONOTA_KANKEI_RENRAKUSAKI_NM_1 IS 'その他関係連絡先名称１'
/
COMMENT ON COLUMN ED0668T_TBL.SNT_KNKI_RNRKSK_DNW_NO_1 IS 'その他関係連絡先電話番号１'
/
COMMENT ON COLUMN ED0668T_TBL.SONOTA_KANKEI_RENRAKUSAKI_NM_2 IS 'その他関係連絡先名称２'
/
COMMENT ON COLUMN ED0668T_TBL.SNT_KNKI_RNRKSK_DNW_NO_2 IS 'その他関係連絡先電話番号２'
/
COMMENT ON COLUMN ED0668T_TBL.KIBSK_KYJ_KNRNNAR_FLG IS '警備先居住管理人有フラグ'
/
COMMENT ON COLUMN ED0668T_TBL.KIBSK_KYJ_KNRNN_DNW_NO IS '警備先居住管理人電話番号'
/
COMMENT ON COLUMN ED0668T_TBL.KIBSK_KNRN_KYJ_KNRNNAR_FLG IS '警備先近隣居住管理人有フラグ'
/
COMMENT ON COLUMN ED0668T_TBL.KIBSK_KNRN_KYJ_KNRNN_DNW_NO IS '警備先近隣居住管理人電話番号'
/
COMMENT ON COLUMN ED0668T_TBL.SNT_KNKI_RNRKSKAR_FLG IS 'その他関係連絡先有フラグ'
/
COMMENT ON COLUMN ED0668T_TBL.SONOTA_KANKEI_RENRAKUSAKI_NM IS 'その他関係連絡先名称'
/
COMMENT ON COLUMN ED0668T_TBL.SNT_KNKI_RNRKSK_DNW_NO IS 'その他関係連絡先電話番号'
/
COMMENT ON COLUMN ED0668T_TBL.KEIBI_KEIKAKU_MOKUHYO_NAIYO IS '警備計画目標内容'
/
COMMENT ON COLUMN ED0668T_TBL.KEIBI_KEIKAKU_BIKO IS '警備計画備考'
/
COMMENT ON COLUMN ED0668T_TBL.GC_GOKI_NO IS 'ＧＣ号機番号'
/
COMMENT ON COLUMN ED0668T_TBL.GC_UKETSUKE_YMD IS 'ＧＣ受付年月日'
/
COMMENT ON COLUMN ED0668T_TBL.GC_ZUMEN_JURYOZUMI_FLG IS 'ＧＣ図面受領済フラグ'
/
COMMENT ON COLUMN ED0668T_TBL.GC_KINREN_JURYOZUMI_FLG IS 'ＧＣ緊連受領済フラグ'
/
COMMENT ON COLUMN ED0668T_TBL.KKI_KIB_JSSH_RNRKHY_BIKO IS '機械警備実施連絡票備考'
/
COMMENT ON COLUMN ED0668T_TBL.KEIYAKUSAKI_TANTOSHA_KN_NM IS '契約先担当者カナ氏名'
/
COMMENT ON COLUMN ED0668T_TBL.TAISHOSAKI_TANTOSHA_KN_NM IS '対象先担当者カナ氏名'
/
COMMENT ON COLUMN ED0668T_TBL.TAIKISHO_NM IS '待機所名称'
/
COMMENT ON COLUMN ED0668T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0668T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0668T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0668T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0668T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0668T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0668T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0668T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0668T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0668T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0668T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0668T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
