/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0652T_TBL.sql
-- 物理名：ED0652T_TBL
-- 論理名：工事指示書入出金機テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0652T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0652T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_SHIJISHO_NO  CHAR(18) NOT NULL --「工事指示書番号」
	,KOJI_SHIJISHO_NYUSHUKKINKI_SN  CHAR(1) NOT NULL --「工事指示書入出金機連番」
	,NYUSHUKKINKI_KISHU_CD  CHAR(8) --「入出金機機種コード」
	,NYUSHUKKINKI_DAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「入出金機台数」
	,NYUSHUKKINKI_NO  VARCHAR2(6) --「入出金機番号」
	,CHUKO_NYUSHUKKINKI_NO  VARCHAR2(6) --「中古入出金機番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0652T_PK PRIMARY KEY(
	 KOJI_SHIJISHO_NO
	,  KAISHA_CD
	,  KOJI_SHIJISHO_NYUSHUKKINKI_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0652T_TBL IS '工事指示書入出金機テーブル'
/

COMMENT ON COLUMN ED0652T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0652T_TBL.KOJI_SHIJISHO_NO IS '工事指示書番号'
/
COMMENT ON COLUMN ED0652T_TBL.KOJI_SHIJISHO_NYUSHUKKINKI_SN IS '工事指示書入出金機連番'
/
COMMENT ON COLUMN ED0652T_TBL.NYUSHUKKINKI_KISHU_CD IS '入出金機機種コード'
/
COMMENT ON COLUMN ED0652T_TBL.NYUSHUKKINKI_DAISU IS '入出金機台数'
/
COMMENT ON COLUMN ED0652T_TBL.NYUSHUKKINKI_NO IS '入出金機番号'
/
COMMENT ON COLUMN ED0652T_TBL.CHUKO_NYUSHUKKINKI_NO IS '中古入出金機番号'
/
COMMENT ON COLUMN ED0652T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0652T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0652T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0652T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0652T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0652T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0652T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0652T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0652T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0652T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0652T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0652T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
