/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0659T_TBL.sql
-- 物理名：ED0659T_TBL
-- 論理名：受注搬送車両テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0659T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0659T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,HANSO_SHARYO_SN  CHAR(14) NOT NULL --「搬送車両連番」
	,SHIYO_SHARYO_KBN  CHAR(1) NOT NULL --「使用車両区分」
	,HANSOSHA_CHARTER_TYPE_KBN  CHAR(1) NOT NULL --「搬送車チャータータイプ区分」
	,HANSOSHA_SHORI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬送車処理数量」
	,HANSOSHA_DAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬送車台数」
	,HNSSH_SHR_WRATMEZN_SHR_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬送車処理割当前残処理数量」
	,HNSSH_SHR_WRAT_SHR_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬送車処理割当処理数量」
	,HNSSH_SHR_WRAT_SHRZN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬送車処理割当処理残数量」
	,CHARTER_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「チャーター金額」
	,CHARTER_RYO_GOKEI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「チャーター料合計金額」
	,HANSOSHA_SEKISAI_KBN  CHAR(1) NOT NULL --「搬送車積載区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0659T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  HANSO_SHARYO_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0659T_TBL IS '受注搬送車両テーブル'
/

COMMENT ON COLUMN ED0659T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0659T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0659T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0659T_TBL.HANSO_SHARYO_SN IS '搬送車両連番'
/
COMMENT ON COLUMN ED0659T_TBL.SHIYO_SHARYO_KBN IS '使用車両区分'
/
COMMENT ON COLUMN ED0659T_TBL.HANSOSHA_CHARTER_TYPE_KBN IS '搬送車チャータータイプ区分'
/
COMMENT ON COLUMN ED0659T_TBL.HANSOSHA_SHORI_SURYO IS '搬送車処理数量'
/
COMMENT ON COLUMN ED0659T_TBL.HANSOSHA_DAISU IS '搬送車台数'
/
COMMENT ON COLUMN ED0659T_TBL.HNSSH_SHR_WRATMEZN_SHR_SURYO IS '搬送車処理割当前残処理数量'
/
COMMENT ON COLUMN ED0659T_TBL.HNSSH_SHR_WRAT_SHR_SURYO IS '搬送車処理割当処理数量'
/
COMMENT ON COLUMN ED0659T_TBL.HNSSH_SHR_WRAT_SHRZN_SURYO IS '搬送車処理割当処理残数量'
/
COMMENT ON COLUMN ED0659T_TBL.CHARTER_AMT IS 'チャーター金額'
/
COMMENT ON COLUMN ED0659T_TBL.CHARTER_RYO_GOKEI_AMT IS 'チャーター料合計金額'
/
COMMENT ON COLUMN ED0659T_TBL.HANSOSHA_SEKISAI_KBN IS '搬送車積載区分'
/
COMMENT ON COLUMN ED0659T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0659T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0659T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0659T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0659T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0659T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0659T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0659T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0659T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0659T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0659T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0659T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
