/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0639T_TBL.sql
-- 物理名：ED0639T_TBL
-- 論理名：運用コスモテーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0639T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0639T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,UNYO_HENKO_RIREKI_NO  CHAR(10) NOT NULL --「運用変更履歴番号」
	,COSMO_KKI_KIB_JSSH_KISH_KBN  CHAR(1) NOT NULL --「コスモ機械警備実施会社区分」
	,COSMO_MISEBAN_NO  CHAR(15) --「コスモ店番番号」
	,COSMO_MISEBAN_NO_BN  CHAR(5) --「コスモ店番番号枝番」
	,COSMO_TEMPO_NM  VARCHAR2(30) --「コスモ店舗名称」
	,COSMO_TEMPO_DENWA_NO  VARCHAR2(20) --「コスモ店舗電話番号」
	,GENKIN_KEY_SHIYO_KBN  CHAR(2) NOT NULL --「現金キー使用区分」
	,COSMO_TOKUYAKU_JIKO  VARCHAR2(60) --「コスモ特約事項」
	,COSMO_MENSEKI_JIKO  VARCHAR2(60) --「コスモ免責事項」
	,COSMO_BIKO  VARCHAR2(60) --「コスモ備考」
	,SHIYO_FUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「使用不可フラグ」
	,GYOMU_KAISHI_YOTEI_YMD  DATE --「業務開始予定年月日」
	,GYOMU_KAISHI_YMD  DATE --「業務開始年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0639T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  UNYO_HENKO_RIREKI_NO
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0639T_TBL IS '運用コスモテーブル'
/

COMMENT ON COLUMN ED0639T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0639T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0639T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0639T_TBL.UNYO_HENKO_RIREKI_NO IS '運用変更履歴番号'
/
COMMENT ON COLUMN ED0639T_TBL.COSMO_KKI_KIB_JSSH_KISH_KBN IS 'コスモ機械警備実施会社区分'
/
COMMENT ON COLUMN ED0639T_TBL.COSMO_MISEBAN_NO IS 'コスモ店番番号'
/
COMMENT ON COLUMN ED0639T_TBL.COSMO_MISEBAN_NO_BN IS 'コスモ店番番号枝番'
/
COMMENT ON COLUMN ED0639T_TBL.COSMO_TEMPO_NM IS 'コスモ店舗名称'
/
COMMENT ON COLUMN ED0639T_TBL.COSMO_TEMPO_DENWA_NO IS 'コスモ店舗電話番号'
/
COMMENT ON COLUMN ED0639T_TBL.GENKIN_KEY_SHIYO_KBN IS '現金キー使用区分'
/
COMMENT ON COLUMN ED0639T_TBL.COSMO_TOKUYAKU_JIKO IS 'コスモ特約事項'
/
COMMENT ON COLUMN ED0639T_TBL.COSMO_MENSEKI_JIKO IS 'コスモ免責事項'
/
COMMENT ON COLUMN ED0639T_TBL.COSMO_BIKO IS 'コスモ備考'
/
COMMENT ON COLUMN ED0639T_TBL.SHIYO_FUKA_FLG IS '使用不可フラグ'
/
COMMENT ON COLUMN ED0639T_TBL.GYOMU_KAISHI_YOTEI_YMD IS '業務開始予定年月日'
/
COMMENT ON COLUMN ED0639T_TBL.GYOMU_KAISHI_YMD IS '業務開始年月日'
/
COMMENT ON COLUMN ED0639T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0639T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0639T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0639T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0639T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0639T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0639T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0639T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0639T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0639T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0639T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0639T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
