/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0605T_TBL.sql
-- 物理名：ED0605T_TBL
-- 論理名：特約事項電子メモテーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0605T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0605T_TBL (
	 DENKEI_NO  CHAR(9) NOT NULL --「電計番号」
	,GC_GOKI_NO  VARCHAR2(11) --「ＧＣ号機番号」
	,KUMIKOMI_KAISEN_NO  VARCHAR2(20) --「組込回線番号」
	,KEIBI_RENKEI_TOKUYAKU_JIKO_1  VARCHAR2(150) --「警備系特約事項１」
	,KEIBI_RENKEI_TOKUYAKU_JIKO_2  VARCHAR2(150) --「警備系特約事項２」
	,KEIBI_RENKEI_TOKUYAKU_JIKO_3  VARCHAR2(150) --「警備系特約事項３」
	,KEIBI_RENKEI_TOKUYAKU_JIKO_4  VARCHAR2(150) --「警備系特約事項４」
	,KEIBI_RENKEI_TOKUYAKU_JIKO_5  VARCHAR2(150) --「警備系特約事項５」
	,KEIBI_RENKEI_DNSH_MEMO_NAIYO  VARCHAR2(150) --「警備系電子メモ内容」
	,KEIBI_RENKEI_YOBI_KMK_NAIYO_1  VARCHAR2(255) --「警備系予備項目内容１」
	,KEIBI_RENKEI_YOBI_KMK_NAIYO_2  VARCHAR2(255) --「警備系予備項目内容２」
	,KEIBI_RENKEI_YOBI_KMK_NAIYO_3  VARCHAR2(255) --「警備系予備項目内容３」
	,KEIBI_RENKEI_YOBI_KMK_NAIYO_4  VARCHAR2(255) --「警備系予備項目内容４」
	,KEIBI_RENKEI_YOBI_KMK_NAIYO_5  VARCHAR2(255) --「警備系予備項目内容５」
	,KEIBI_RENKEI_YOBI_KMK_NAIYO_6  VARCHAR2(255) --「警備系予備項目内容６」
	,KEIBI_RENKEI_YOBI_KMK_NAIYO_7  VARCHAR2(255) --「警備系予備項目内容７」
	,KEIBI_RENKEI_YOBI_KMK_NAIYO_8  VARCHAR2(255) --「警備系予備項目内容８」
	,KEIBI_RENKEI_YOBI_KMK_NAIYO_9  VARCHAR2(255) --「警備系予備項目内容９」
	,KEIBI_RENKEI_YOBI_KMK_NAIYO_10  VARCHAR2(255) --「警備系予備項目内容１０」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0605T_PK PRIMARY KEY(
	 DENKEI_NO
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0605T_TBL IS '特約事項電子メモテーブル'
/

COMMENT ON COLUMN ED0605T_TBL.DENKEI_NO IS '電計番号'
/
COMMENT ON COLUMN ED0605T_TBL.GC_GOKI_NO IS 'ＧＣ号機番号'
/
COMMENT ON COLUMN ED0605T_TBL.KUMIKOMI_KAISEN_NO IS '組込回線番号'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_TOKUYAKU_JIKO_1 IS '警備系特約事項１'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_TOKUYAKU_JIKO_2 IS '警備系特約事項２'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_TOKUYAKU_JIKO_3 IS '警備系特約事項３'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_TOKUYAKU_JIKO_4 IS '警備系特約事項４'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_TOKUYAKU_JIKO_5 IS '警備系特約事項５'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_DNSH_MEMO_NAIYO IS '警備系電子メモ内容'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_YOBI_KMK_NAIYO_1 IS '警備系予備項目内容１'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_YOBI_KMK_NAIYO_2 IS '警備系予備項目内容２'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_YOBI_KMK_NAIYO_3 IS '警備系予備項目内容３'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_YOBI_KMK_NAIYO_4 IS '警備系予備項目内容４'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_YOBI_KMK_NAIYO_5 IS '警備系予備項目内容５'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_YOBI_KMK_NAIYO_6 IS '警備系予備項目内容６'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_YOBI_KMK_NAIYO_7 IS '警備系予備項目内容７'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_YOBI_KMK_NAIYO_8 IS '警備系予備項目内容８'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_YOBI_KMK_NAIYO_9 IS '警備系予備項目内容９'
/
COMMENT ON COLUMN ED0605T_TBL.KEIBI_RENKEI_YOBI_KMK_NAIYO_10 IS '警備系予備項目内容１０'
/
COMMENT ON COLUMN ED0605T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0605T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0605T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0605T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0605T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0605T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0605T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0605T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0605T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0605T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0605T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0605T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
