/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0642T_TBL.sql
-- 物理名：ED0642T_TBL
-- 論理名：入出金機受注仕様明細詳細変更テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0642T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0642T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,NYSHKKNK_JCH_SHY_MISI_KBN  CHAR(1) NOT NULL --「入出金機受注仕様明細区分」
	,NYSHKKNK_JCH_SHY_MISI_NO  CHAR(10) NOT NULL --「入出金機受注仕様明細番号」
	,NSKK_JCH_SHY_MEISAI_RIREKI_NO  CHAR(3) NOT NULL --「入出金機受注仕様明細履歴番号」
	,NYUSHUKKINKI_SN  CHAR(14) NOT NULL --「入出金機連番」
	,NSKK_JUCHUSY_MEISAI_SS_HK_SN  CHAR(14) NOT NULL --「入出金機受注仕様明細詳細変更連番」
	,NSKK_HENKO_KOMOKU_NM  VARCHAR2(60) --「入出金機変更項目名称」
	,NSKK_HENKOMAE_KOMOKU_NAIYO  VARCHAR2(100) --「入出金機変更前項目内容」
	,NSKK_HENKOGO_KOMOKU_NAIYO  VARCHAR2(100) --「入出金機変更後項目内容」
	,NSKK_HK_KOMOKU_SYURUI_KBN  CHAR(1) NOT NULL --「入出金機変更項目種類区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0642T_PK PRIMARY KEY(
	 NYSHKKNK_JCH_SHY_MISI_NO
	,  NYUSHUKKINKI_SN
	,  KAISHA_CD
	,  NYSHKKNK_JCH_SHY_MISI_KBN
	,  NSKK_JCH_SHY_MEISAI_RIREKI_NO
	,  NSKK_JUCHUSY_MEISAI_SS_HK_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0642T_TBL IS '入出金機受注仕様明細詳細変更テーブル'
/

COMMENT ON COLUMN ED0642T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0642T_TBL.NYSHKKNK_JCH_SHY_MISI_KBN IS '入出金機受注仕様明細区分'
/
COMMENT ON COLUMN ED0642T_TBL.NYSHKKNK_JCH_SHY_MISI_NO IS '入出金機受注仕様明細番号'
/
COMMENT ON COLUMN ED0642T_TBL.NSKK_JCH_SHY_MEISAI_RIREKI_NO IS '入出金機受注仕様明細履歴番号'
/
COMMENT ON COLUMN ED0642T_TBL.NYUSHUKKINKI_SN IS '入出金機連番'
/
COMMENT ON COLUMN ED0642T_TBL.NSKK_JUCHUSY_MEISAI_SS_HK_SN IS '入出金機受注仕様明細詳細変更連番'
/
COMMENT ON COLUMN ED0642T_TBL.NSKK_HENKO_KOMOKU_NM IS '入出金機変更項目名称'
/
COMMENT ON COLUMN ED0642T_TBL.NSKK_HENKOMAE_KOMOKU_NAIYO IS '入出金機変更前項目内容'
/
COMMENT ON COLUMN ED0642T_TBL.NSKK_HENKOGO_KOMOKU_NAIYO IS '入出金機変更後項目内容'
/
COMMENT ON COLUMN ED0642T_TBL.NSKK_HK_KOMOKU_SYURUI_KBN IS '入出金機変更項目種類区分'
/
COMMENT ON COLUMN ED0642T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0642T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0642T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0642T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0642T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0642T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0642T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0642T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0642T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0642T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0642T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0642T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
