/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0696T_TBL.sql
-- 物理名：ED0696T_TBL
-- 論理名：運用ＣＤＡＴＭテーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0696T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0696T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,UNYO_HENKO_RIREKI_NO  CHAR(10) NOT NULL --「運用変更履歴番号」
	,KOKYAKU_SHITEN_CD  CHAR(12) --「顧客支店コード」
	,TAMMATSU_CD  CHAR(15) --「端末コード」
	,SHIHEI_RYOKIN_TYPE_CD  CHAR(3) --「警送紙幣料金タイプコード」
	,KOKA_RYOKIN_TYPE_CD  CHAR(3) --「警送硬貨料金タイプコード」
	,JIDOKI_KIKAI_KEIBI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「自動機機械警備フラグ」
	,JIDOKI_IKAKU_KEIHOKI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「自動機威嚇警報機フラグ」
	,JIDOKI_LOCAL_KEIBI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「自動機ローカル警備フラグ」
	,JIDOKI_KEIBI_NASHI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「自動機警備なしフラグ」
	,SONOTA_JIDOKI_KEIBI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「その他自動機警備フラグ」
	,SONOTA_JIDOKI_KEIBI_NAIYO  VARCHAR2(40) --「その他自動機警備内容」
	,TTMN_KIB_JSSH_TNT_KBN  CHAR(1) --「建物警備実施担当区分」
	,TATEMONO_KEIBI_HOHO_KBN  CHAR(2) --「建物警備方法区分」
	,JIDOKI_BIKO  VARCHAR2(100) --「自動機備考」
	,CDATM_TANTO_COSMO_TEMPO_NM  VARCHAR2(30) --「ＣＤＡＴＭ担当コスモ店舗名称」
	,CDATM_TNT_COSMO_TMP_DNW_NO  VARCHAR2(20) --「ＣＤＡＴＭ担当コスモ店舗電話番号」
	,COSMO_CENTER_JIGYOSHO_CD  CHAR(6) --「コスモセンター事業所コード」
	,SOTEN_KAISHU_GENKIN_KBN  CHAR(1) NOT NULL --「装填回収現金区分」
	,SOTENYO_SHIHEI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「装填用紙幣数量」
	,SOTENYO_KOKA_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「装填用硬貨数量」
	,KAISHUYO_SHIHEI_MAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「回収用紙幣枚数」
	,KAISHU_KOKA_MAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「回収硬貨枚数」
	,SOTEN_HOSHIKI_KBN  CHAR(1) --「装填方式区分」
	,SONOTA_SOTEN_HOSHIKI_NAIYO  VARCHAR2(60) --「その他装填方式内容」
	,KANRI_HOSHIKI_KBN  CHAR(2) --「管理方式区分」
	,SNT_SHKN_KNR_HSHK_NAIYO  VARCHAR2(100) --「その他資金管理方式内容」
	,SHIKIN_KBN  CHAR(1) --「資金区分」
	,JDK_GNKN_UKWTSH_HH_KBN  CHAR(1) --「自動機現金受渡方法区分」
	,SHIKIN_KEIKAKU_KBN  CHAR(1) --「資金計画区分」
	,KIGYONAI_CD_SHUBETSU_KBN  CHAR(1) NOT NULL --「企業内ＣＤ種別区分」
	,KIGYONAI_CD_SETTEI_COURSE_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「企業内ＣＤ設定コース金額」
	,KIGYONAI_CD_RIYO_HOHO_KBN  CHAR(1) NOT NULL --「企業内ＣＤ利用方法区分」
	,CDATM_GYOMU_SYSTEM_KBN  CHAR(1) --「ＣＤＡＴＭ業務システム区分」
	,SNT_CDATM_GYM_SYSTEM_KBN_NAIYO  VARCHAR2(20) --「その他ＣＤＡＴＭ業務システム区分内容」
	,KEISO_CDATM_BIKO  VARCHAR2(100) --「警送ＣＤＡＴＭ備考」
	,SHIYO_FUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「使用不可フラグ」
	,GYOMU_KAISHI_YOTEI_YMD  DATE --「業務開始予定年月日」
	,GYOMU_KAISHI_YMD  DATE --「業務開始年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0696T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  UNYO_HENKO_RIREKI_NO
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0696T_TBL IS '運用ＣＤＡＴＭテーブル'
/

COMMENT ON COLUMN ED0696T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0696T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0696T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0696T_TBL.UNYO_HENKO_RIREKI_NO IS '運用変更履歴番号'
/
COMMENT ON COLUMN ED0696T_TBL.KOKYAKU_SHITEN_CD IS '顧客支店コード'
/
COMMENT ON COLUMN ED0696T_TBL.TAMMATSU_CD IS '端末コード'
/
COMMENT ON COLUMN ED0696T_TBL.SHIHEI_RYOKIN_TYPE_CD IS '警送紙幣料金タイプコード'
/
COMMENT ON COLUMN ED0696T_TBL.KOKA_RYOKIN_TYPE_CD IS '警送硬貨料金タイプコード'
/
COMMENT ON COLUMN ED0696T_TBL.JIDOKI_KIKAI_KEIBI_FLG IS '自動機機械警備フラグ'
/
COMMENT ON COLUMN ED0696T_TBL.JIDOKI_IKAKU_KEIHOKI_FLG IS '自動機威嚇警報機フラグ'
/
COMMENT ON COLUMN ED0696T_TBL.JIDOKI_LOCAL_KEIBI_FLG IS '自動機ローカル警備フラグ'
/
COMMENT ON COLUMN ED0696T_TBL.JIDOKI_KEIBI_NASHI_FLG IS '自動機警備なしフラグ'
/
COMMENT ON COLUMN ED0696T_TBL.SONOTA_JIDOKI_KEIBI_FLG IS 'その他自動機警備フラグ'
/
COMMENT ON COLUMN ED0696T_TBL.SONOTA_JIDOKI_KEIBI_NAIYO IS 'その他自動機警備内容'
/
COMMENT ON COLUMN ED0696T_TBL.TTMN_KIB_JSSH_TNT_KBN IS '建物警備実施担当区分'
/
COMMENT ON COLUMN ED0696T_TBL.TATEMONO_KEIBI_HOHO_KBN IS '建物警備方法区分'
/
COMMENT ON COLUMN ED0696T_TBL.JIDOKI_BIKO IS '自動機備考'
/
COMMENT ON COLUMN ED0696T_TBL.CDATM_TANTO_COSMO_TEMPO_NM IS 'ＣＤＡＴＭ担当コスモ店舗名称'
/
COMMENT ON COLUMN ED0696T_TBL.CDATM_TNT_COSMO_TMP_DNW_NO IS 'ＣＤＡＴＭ担当コスモ店舗電話番号'
/
COMMENT ON COLUMN ED0696T_TBL.COSMO_CENTER_JIGYOSHO_CD IS 'コスモセンター事業所コード'
/
COMMENT ON COLUMN ED0696T_TBL.SOTEN_KAISHU_GENKIN_KBN IS '装填回収現金区分'
/
COMMENT ON COLUMN ED0696T_TBL.SOTENYO_SHIHEI_SURYO IS '装填用紙幣数量'
/
COMMENT ON COLUMN ED0696T_TBL.SOTENYO_KOKA_SURYO IS '装填用硬貨数量'
/
COMMENT ON COLUMN ED0696T_TBL.KAISHUYO_SHIHEI_MAISU IS '回収用紙幣枚数'
/
COMMENT ON COLUMN ED0696T_TBL.KAISHU_KOKA_MAISU IS '回収硬貨枚数'
/
COMMENT ON COLUMN ED0696T_TBL.SOTEN_HOSHIKI_KBN IS '装填方式区分'
/
COMMENT ON COLUMN ED0696T_TBL.SONOTA_SOTEN_HOSHIKI_NAIYO IS 'その他装填方式内容'
/
COMMENT ON COLUMN ED0696T_TBL.KANRI_HOSHIKI_KBN IS '管理方式区分'
/
COMMENT ON COLUMN ED0696T_TBL.SNT_SHKN_KNR_HSHK_NAIYO IS 'その他資金管理方式内容'
/
COMMENT ON COLUMN ED0696T_TBL.SHIKIN_KBN IS '資金区分'
/
COMMENT ON COLUMN ED0696T_TBL.JDK_GNKN_UKWTSH_HH_KBN IS '自動機現金受渡方法区分'
/
COMMENT ON COLUMN ED0696T_TBL.SHIKIN_KEIKAKU_KBN IS '資金計画区分'
/
COMMENT ON COLUMN ED0696T_TBL.KIGYONAI_CD_SHUBETSU_KBN IS '企業内ＣＤ種別区分'
/
COMMENT ON COLUMN ED0696T_TBL.KIGYONAI_CD_SETTEI_COURSE_AMT IS '企業内ＣＤ設定コース金額'
/
COMMENT ON COLUMN ED0696T_TBL.KIGYONAI_CD_RIYO_HOHO_KBN IS '企業内ＣＤ利用方法区分'
/
COMMENT ON COLUMN ED0696T_TBL.CDATM_GYOMU_SYSTEM_KBN IS 'ＣＤＡＴＭ業務システム区分'
/
COMMENT ON COLUMN ED0696T_TBL.SNT_CDATM_GYM_SYSTEM_KBN_NAIYO IS 'その他ＣＤＡＴＭ業務システム区分内容'
/
COMMENT ON COLUMN ED0696T_TBL.KEISO_CDATM_BIKO IS '警送ＣＤＡＴＭ備考'
/
COMMENT ON COLUMN ED0696T_TBL.SHIYO_FUKA_FLG IS '使用不可フラグ'
/
COMMENT ON COLUMN ED0696T_TBL.GYOMU_KAISHI_YOTEI_YMD IS '業務開始予定年月日'
/
COMMENT ON COLUMN ED0696T_TBL.GYOMU_KAISHI_YMD IS '業務開始年月日'
/
COMMENT ON COLUMN ED0696T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0696T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0696T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0696T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0696T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0696T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0696T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0696T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0696T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0696T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0696T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0696T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
