/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0646T_TBL.sql
-- 物理名：ED0646T_TBL
-- 論理名：受注機器テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0646T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0646T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,CHOTATSU_BUMON_RENRAKU_NAIYO  VARCHAR2(100) --「調達部門連絡内容」
	,SHIZAI_KIKI_JOHO_BIKO  VARCHAR2(100) --「資材機器情報備考」
	,CHOTATSU_RENKEIZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「調達連携済フラグ」
	,KIKI_KOSEI_CMNT  VARCHAR2(100) --「機器構成コメント」
	,TOSHI_KIKI_GOKEI_KK_KSN_B_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「投資機器合計機器加算Ｂ金額」
	,TOSHI_KIKI_GOKEI_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「投資機器合計原価金額」
	,TOSHI_KIKI_GOKEI_HYOJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「投資機器合計標準金額」
	,BAIKYAKU_KIKI_GOKEI_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売却機器合計原価金額」
	,BAIKYAKU_KIKI_GOKEI_HYOJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売却機器合計標準金額」
	,KIKI_KOSEI_HENKO_RIYU  VARCHAR2(100) --「機器構成変更理由」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0646T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0646T_TBL IS '受注機器テーブル'
/

COMMENT ON COLUMN ED0646T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0646T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0646T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0646T_TBL.CHOTATSU_BUMON_RENRAKU_NAIYO IS '調達部門連絡内容'
/
COMMENT ON COLUMN ED0646T_TBL.SHIZAI_KIKI_JOHO_BIKO IS '資材機器情報備考'
/
COMMENT ON COLUMN ED0646T_TBL.CHOTATSU_RENKEIZUMI_FLG IS '調達連携済フラグ'
/
COMMENT ON COLUMN ED0646T_TBL.KIKI_KOSEI_CMNT IS '機器構成コメント'
/
COMMENT ON COLUMN ED0646T_TBL.TOSHI_KIKI_GOKEI_KK_KSN_B_AMT IS '投資機器合計機器加算Ｂ金額'
/
COMMENT ON COLUMN ED0646T_TBL.TOSHI_KIKI_GOKEI_GENKA_AMT IS '投資機器合計原価金額'
/
COMMENT ON COLUMN ED0646T_TBL.TOSHI_KIKI_GOKEI_HYOJUN_AMT IS '投資機器合計標準金額'
/
COMMENT ON COLUMN ED0646T_TBL.BAIKYAKU_KIKI_GOKEI_GENKA_AMT IS '売却機器合計原価金額'
/
COMMENT ON COLUMN ED0646T_TBL.BAIKYAKU_KIKI_GOKEI_HYOJUN_AMT IS '売却機器合計標準金額'
/
COMMENT ON COLUMN ED0646T_TBL.KIKI_KOSEI_HENKO_RIYU IS '機器構成変更理由'
/
COMMENT ON COLUMN ED0646T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0646T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0646T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0646T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0646T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0646T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0646T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0646T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0646T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0646T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0646T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0646T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
