/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0694T_TBL.sql
-- 物理名：ED0694T_TBL
-- 論理名：運用入出金機テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0694T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0694T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,UNYO_HENKO_RIREKI_NO  CHAR(10) NOT NULL --「運用変更履歴番号」
	,KIB_TISHSK_EIGY_KISH_TM  CHAR(4) --「警備対象先営業開始時刻」
	,KIB_TISHSK_EIGY_SHRY_TM  CHAR(4) --「警備対象先営業終了時刻」
	,KIB_TISHSK_TIKYB_STTI_NAIYO  VARCHAR2(20) --「警備対象先定休日設定内容」
	,SETCHI_BASHO_NM  VARCHAR2(60) --「設置場所名称」
	,KIB_TISH_TTMN_KIB_JKY_NAIYO  VARCHAR2(20) --「警備対象建物警備状況内容」
	,YSHN_KISH_SHTI_JIKAN_KBN  CHAR(1) --「輸送品回収指定時間区分」
	,YSHN_KISH_SHTI_KISH_TM  CHAR(4) --「輸送品回収指定開始時刻」
	,YSHN_KISH_SHTI_SHRY_TM  CHAR(4) --「輸送品回収指定終了時刻」
	,YSHN_KISH_SHTIB_STTI_NAIYO  VARCHAR2(20) --「輸送品回収指定日設定内容」
	,HAIKIN_SHITEI_JIKAN_KBN  CHAR(1) --「配金指定時間区分」
	,HAIKIN_SHITEI_KAISHI_TM  CHAR(4) --「配金指定開始時刻」
	,HAIKIN_SHITEI_SHURYO_TM  CHAR(4) --「配金指定終了時刻」
	,HAIKIN_SHITEIBI_NAIYO  VARCHAR2(20) --「配金指定日内容」
	,HAIKIN_TANI_KBN  CHAR(1) --「配金単位区分」
	,SHIKIN_KBN  CHAR(1) --「資金区分」
	,NSKKNK_BHN_PROTECTOR_ST_JK_KBN  CHAR(1) --「入出金機防犯プロテクター設置状況区分」
	,NYUSHUKKINKI_DENSOSAKI_KBN  CHAR(1) --「入出金機伝送先区分」
	,NYUSHUKKINKI_KOTEI_HOHO_KBN  CHAR(1) --「入出金機固定方法区分」
	,CLIENT_SHMISH_SHY_KGN_YMD  DATE --「クライアント証明書使用期限年月日」
	,RYOGAEKI_UNKO_SHITEI_JIKAN_KBN  CHAR(1) --「両替機運行指定時間区分」
	,RYOGAEKI_UNKO_SHITEI_KAISHI_TM  CHAR(4) --「両替機運行指定開始時刻」
	,RYOGAEKI_UNKO_SHITEI_SHURYO_TM  CHAR(4) --「両替機運行指定終了時刻」
	,RYGEK_UNK_SHTIB_STTI_NAIYO  VARCHAR2(20) --「両替機運行指定日設定内容」
	,KIKAI_KEIBI_KAISHI_YOTEI_YMD  DATE --「機械警備開始予定年月日」
	,KIKAI_KEIBI_KAISHI_YMD  DATE --「機械警備開始年月日」
	,COSMO_KEIBI_KAISHI_YOTEI_YMD  DATE --「コスモ警備開始予定年月日」
	,COSMO_KEIBI_KAISHI_YMD  DATE --「コスモ警備開始年月日」
	,COSMO_KKI_KIB_JSSH_KISH_KBN  CHAR(1) --「コスモ機械警備実施会社区分」
	,COSMO_MISEBAN_NO  CHAR(15) --「コスモ店番番号」
	,COSMO_MISEBAN_NO_BN  CHAR(5) --「コスモ店番番号枝番」
	,COSMO_TEMPO_NM  VARCHAR2(30) --「コスモ店舗名称」
	,COSMO_TEMPO_DENWA_NO  VARCHAR2(20) --「コスモ店舗電話番号」
	,GENKIN_KEY_SHIYO_KBN  CHAR(2) --「現金キー使用区分」
	,COSMO_TOKUYAKU_JIKO  VARCHAR2(60) --「コスモ特約事項」
	,COSMO_MENSEKI_JIKO  VARCHAR2(60) --「コスモ免責事項」
	,COSMO_BIKO  VARCHAR2(60) --「コスモ備考」
	,KIBTI_KG_TRATSKIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備隊鍵取扱有フラグ」
	,HOKOKUSHO_TEISHUTSUSAKI_NM  VARCHAR2(60) --「報告書提出先名称」
	,UNYOJO_TORIKIME_NAIYO_1  VARCHAR2(30) --「運用上取決め内容１」
	,UNYOJO_TORIKIME_NAIYO_2  VARCHAR2(30) --「運用上取決め内容２」
	,UNYOJO_TORIKIME_NAIYO_3  VARCHAR2(30) --「運用上取決め内容３」
	,UNYOJO_TORIKIME_NAIYO_4  VARCHAR2(30) --「運用上取決め内容４」
	,UNYOJO_TORIKIME_NAIYO_5  VARCHAR2(30) --「運用上取決め内容５」
	,NYUSHUKKINKI_SETCHI_YMD  DATE --「入出金機設置年月日」
	,NYUSHUKKINKI_SETCHI_TM  CHAR(4) --「入出金機設置時刻」
	,NYUSHUKKINKI_SHOKAI_KAISHU_YMD  DATE --「入出金機初回回収年月日」
	,NYUSHUKKINKI_SHOKAI_KAISHU_TM  CHAR(4) --「入出金機初回回収時刻」
	,NYUSHUKKINKI_SHOKAI_HAIKIN_YMD  DATE --「入出金機初回配金年月日」
	,NYUSHUKKINKI_SHOKAI_HAIKIN_TM  CHAR(4) --「入出金機初回配金時刻」
	,NSKKNK_CASSETTE_LESS_UNYAR_FLG  CHAR(1) --「入出金機カセットレス運用有フラグ」
	,NYUSHUKKINKI_JUCHU_KAISO_NAIYO  VARCHAR2(150) --「入出金機受注階層内容」
	,NYSHKKNK_IRAI_HOSOKU_NAIYO  VARCHAR2(1000) --「入出金機依頼補足内容」
	,NYSHKKNK_IRAI_HOSOKU_NAIYO_1  VARCHAR2(1000) --「入出金機依頼補足内容１」
	,NYUSHUKKINKI_KAITEI_YMD  DATE --「入出金機改定年月日」
	,NYUSHUKKINKI_KAITEI_NAIYO  VARCHAR2(1000) --「入出金機改定内容」
	,NYUSHUKKINKI_KAITEI_NAIYO_1  VARCHAR2(1000) --「入出金機改定内容１」
	,RINJI_TAIO_RYOKINARI_FLG  CHAR(1) --「臨時対応料金有フラグ」
	,YUSHO_SHUTSUDO_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「有償出動料金金額」
	,NYSHKKNK_KITI_TIO_MSH_RIYU  VARCHAR2(100) --「入出金機改定対応無償理由」
	,SHIYO_FUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「使用不可フラグ」
	,GYOMU_KAISHI_YOTEI_YMD  DATE --「業務開始予定年月日」
	,GYOMU_KAISHI_YMD  DATE --「業務開始年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0694T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  UNYO_HENKO_RIREKI_NO
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0694T_TBL IS '運用入出金機テーブル'
/

COMMENT ON COLUMN ED0694T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0694T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0694T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0694T_TBL.UNYO_HENKO_RIREKI_NO IS '運用変更履歴番号'
/
COMMENT ON COLUMN ED0694T_TBL.KIB_TISHSK_EIGY_KISH_TM IS '警備対象先営業開始時刻'
/
COMMENT ON COLUMN ED0694T_TBL.KIB_TISHSK_EIGY_SHRY_TM IS '警備対象先営業終了時刻'
/
COMMENT ON COLUMN ED0694T_TBL.KIB_TISHSK_TIKYB_STTI_NAIYO IS '警備対象先定休日設定内容'
/
COMMENT ON COLUMN ED0694T_TBL.SETCHI_BASHO_NM IS '設置場所名称'
/
COMMENT ON COLUMN ED0694T_TBL.KIB_TISH_TTMN_KIB_JKY_NAIYO IS '警備対象建物警備状況内容'
/
COMMENT ON COLUMN ED0694T_TBL.YSHN_KISH_SHTI_JIKAN_KBN IS '輸送品回収指定時間区分'
/
COMMENT ON COLUMN ED0694T_TBL.YSHN_KISH_SHTI_KISH_TM IS '輸送品回収指定開始時刻'
/
COMMENT ON COLUMN ED0694T_TBL.YSHN_KISH_SHTI_SHRY_TM IS '輸送品回収指定終了時刻'
/
COMMENT ON COLUMN ED0694T_TBL.YSHN_KISH_SHTIB_STTI_NAIYO IS '輸送品回収指定日設定内容'
/
COMMENT ON COLUMN ED0694T_TBL.HAIKIN_SHITEI_JIKAN_KBN IS '配金指定時間区分'
/
COMMENT ON COLUMN ED0694T_TBL.HAIKIN_SHITEI_KAISHI_TM IS '配金指定開始時刻'
/
COMMENT ON COLUMN ED0694T_TBL.HAIKIN_SHITEI_SHURYO_TM IS '配金指定終了時刻'
/
COMMENT ON COLUMN ED0694T_TBL.HAIKIN_SHITEIBI_NAIYO IS '配金指定日内容'
/
COMMENT ON COLUMN ED0694T_TBL.HAIKIN_TANI_KBN IS '配金単位区分'
/
COMMENT ON COLUMN ED0694T_TBL.SHIKIN_KBN IS '資金区分'
/
COMMENT ON COLUMN ED0694T_TBL.NSKKNK_BHN_PROTECTOR_ST_JK_KBN IS '入出金機防犯プロテクター設置状況区分'
/
COMMENT ON COLUMN ED0694T_TBL.NYUSHUKKINKI_DENSOSAKI_KBN IS '入出金機伝送先区分'
/
COMMENT ON COLUMN ED0694T_TBL.NYUSHUKKINKI_KOTEI_HOHO_KBN IS '入出金機固定方法区分'
/
COMMENT ON COLUMN ED0694T_TBL.CLIENT_SHMISH_SHY_KGN_YMD IS 'クライアント証明書使用期限年月日'
/
COMMENT ON COLUMN ED0694T_TBL.RYOGAEKI_UNKO_SHITEI_JIKAN_KBN IS '両替機運行指定時間区分'
/
COMMENT ON COLUMN ED0694T_TBL.RYOGAEKI_UNKO_SHITEI_KAISHI_TM IS '両替機運行指定開始時刻'
/
COMMENT ON COLUMN ED0694T_TBL.RYOGAEKI_UNKO_SHITEI_SHURYO_TM IS '両替機運行指定終了時刻'
/
COMMENT ON COLUMN ED0694T_TBL.RYGEK_UNK_SHTIB_STTI_NAIYO IS '両替機運行指定日設定内容'
/
COMMENT ON COLUMN ED0694T_TBL.KIKAI_KEIBI_KAISHI_YOTEI_YMD IS '機械警備開始予定年月日'
/
COMMENT ON COLUMN ED0694T_TBL.KIKAI_KEIBI_KAISHI_YMD IS '機械警備開始年月日'
/
COMMENT ON COLUMN ED0694T_TBL.COSMO_KEIBI_KAISHI_YOTEI_YMD IS 'コスモ警備開始予定年月日'
/
COMMENT ON COLUMN ED0694T_TBL.COSMO_KEIBI_KAISHI_YMD IS 'コスモ警備開始年月日'
/
COMMENT ON COLUMN ED0694T_TBL.COSMO_KKI_KIB_JSSH_KISH_KBN IS 'コスモ機械警備実施会社区分'
/
COMMENT ON COLUMN ED0694T_TBL.COSMO_MISEBAN_NO IS 'コスモ店番番号'
/
COMMENT ON COLUMN ED0694T_TBL.COSMO_MISEBAN_NO_BN IS 'コスモ店番番号枝番'
/
COMMENT ON COLUMN ED0694T_TBL.COSMO_TEMPO_NM IS 'コスモ店舗名称'
/
COMMENT ON COLUMN ED0694T_TBL.COSMO_TEMPO_DENWA_NO IS 'コスモ店舗電話番号'
/
COMMENT ON COLUMN ED0694T_TBL.GENKIN_KEY_SHIYO_KBN IS '現金キー使用区分'
/
COMMENT ON COLUMN ED0694T_TBL.COSMO_TOKUYAKU_JIKO IS 'コスモ特約事項'
/
COMMENT ON COLUMN ED0694T_TBL.COSMO_MENSEKI_JIKO IS 'コスモ免責事項'
/
COMMENT ON COLUMN ED0694T_TBL.COSMO_BIKO IS 'コスモ備考'
/
COMMENT ON COLUMN ED0694T_TBL.KIBTI_KG_TRATSKIAR_FLG IS '警備隊鍵取扱有フラグ'
/
COMMENT ON COLUMN ED0694T_TBL.HOKOKUSHO_TEISHUTSUSAKI_NM IS '報告書提出先名称'
/
COMMENT ON COLUMN ED0694T_TBL.UNYOJO_TORIKIME_NAIYO_1 IS '運用上取決め内容１'
/
COMMENT ON COLUMN ED0694T_TBL.UNYOJO_TORIKIME_NAIYO_2 IS '運用上取決め内容２'
/
COMMENT ON COLUMN ED0694T_TBL.UNYOJO_TORIKIME_NAIYO_3 IS '運用上取決め内容３'
/
COMMENT ON COLUMN ED0694T_TBL.UNYOJO_TORIKIME_NAIYO_4 IS '運用上取決め内容４'
/
COMMENT ON COLUMN ED0694T_TBL.UNYOJO_TORIKIME_NAIYO_5 IS '運用上取決め内容５'
/
COMMENT ON COLUMN ED0694T_TBL.NYUSHUKKINKI_SETCHI_YMD IS '入出金機設置年月日'
/
COMMENT ON COLUMN ED0694T_TBL.NYUSHUKKINKI_SETCHI_TM IS '入出金機設置時刻'
/
COMMENT ON COLUMN ED0694T_TBL.NYUSHUKKINKI_SHOKAI_KAISHU_YMD IS '入出金機初回回収年月日'
/
COMMENT ON COLUMN ED0694T_TBL.NYUSHUKKINKI_SHOKAI_KAISHU_TM IS '入出金機初回回収時刻'
/
COMMENT ON COLUMN ED0694T_TBL.NYUSHUKKINKI_SHOKAI_HAIKIN_YMD IS '入出金機初回配金年月日'
/
COMMENT ON COLUMN ED0694T_TBL.NYUSHUKKINKI_SHOKAI_HAIKIN_TM IS '入出金機初回配金時刻'
/
COMMENT ON COLUMN ED0694T_TBL.NSKKNK_CASSETTE_LESS_UNYAR_FLG IS '入出金機カセットレス運用有フラグ'
/
COMMENT ON COLUMN ED0694T_TBL.NYUSHUKKINKI_JUCHU_KAISO_NAIYO IS '入出金機受注階層内容'
/
COMMENT ON COLUMN ED0694T_TBL.NYSHKKNK_IRAI_HOSOKU_NAIYO IS '入出金機依頼補足内容'
/
COMMENT ON COLUMN ED0694T_TBL.NYSHKKNK_IRAI_HOSOKU_NAIYO_1 IS '入出金機依頼補足内容１'
/
COMMENT ON COLUMN ED0694T_TBL.NYUSHUKKINKI_KAITEI_YMD IS '入出金機改定年月日'
/
COMMENT ON COLUMN ED0694T_TBL.NYUSHUKKINKI_KAITEI_NAIYO IS '入出金機改定内容'
/
COMMENT ON COLUMN ED0694T_TBL.NYUSHUKKINKI_KAITEI_NAIYO_1 IS '入出金機改定内容１'
/
COMMENT ON COLUMN ED0694T_TBL.RINJI_TAIO_RYOKINARI_FLG IS '臨時対応料金有フラグ'
/
COMMENT ON COLUMN ED0694T_TBL.YUSHO_SHUTSUDO_RYOKIN_AMT IS '有償出動料金金額'
/
COMMENT ON COLUMN ED0694T_TBL.NYSHKKNK_KITI_TIO_MSH_RIYU IS '入出金機改定対応無償理由'
/
COMMENT ON COLUMN ED0694T_TBL.SHIYO_FUKA_FLG IS '使用不可フラグ'
/
COMMENT ON COLUMN ED0694T_TBL.GYOMU_KAISHI_YOTEI_YMD IS '業務開始予定年月日'
/
COMMENT ON COLUMN ED0694T_TBL.GYOMU_KAISHI_YMD IS '業務開始年月日'
/
COMMENT ON COLUMN ED0694T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0694T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0694T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0694T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0694T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0694T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0694T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0694T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0694T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0694T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0694T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0694T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
