/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0677T_TBL.sql
-- 物理名：ED0677T_TBL
-- 論理名：運用常駐詳細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0677T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0677T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,UNYO_HENKO_RIREKI_NO  CHAR(10) NOT NULL --「運用変更履歴番号」
	,UNYO_JOCHU_SHOSAI_SN  CHAR(14) NOT NULL --「運用常駐詳細連番」
	,GYOMU_SAIITAKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「業務再委託有フラグ」
	,KEIBIIN_SEIFUKU_KBN  CHAR(1) NOT NULL --「警備員制服区分」
	,SONOTA_KEIBIIN_SEIFUKU_NAIYO  VARCHAR2(30) --「その他警備員制服内容」
	,JISHA_DENWA_RENRAKUSAKI_NAIYO  VARCHAR2(150) --「自社電話連絡先内容」
	,KEIBI_GYOHO_1_GO_GYOMUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備業法１号業務有フラグ」
	,KEIBI_GYOHO_2_GO_GYOMUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備業法２号業務有フラグ」
	,KEIBI_GYOHO_3_GO_GYOMUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備業法３号業務有フラグ」
	,KEIBI_GYOHO_4_GO_GYOMUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備業法４号業務有フラグ」
	,TOSHO_SHOHI_ZEIRITSU_CD  CHAR(2) --「当初消費税率コード」
	,SHOHIZEI_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「消費税率」
	,HIKAZEI_RIYU  VARCHAR2(60) --「非課税理由」
	,KIBTI_KG_TRATSKIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備隊鍵取扱有フラグ」
	,KIBTI_KG_TRATSKI_TKK_JIKO  VARCHAR2(30) --「警備隊鍵取扱特記事項」
	,HKKSH_GNCH_TISHTSAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「報告書現地提出有フラグ」
	,HKKSH_GNCH_TISHTS_TKK_JIKO  VARCHAR2(30) --「報告書現地提出特記事項」
	,GYM_ITKSK_TRHKSK_CD  CHAR(9) --「業務委託先取引先コード」
	,GYOMU_JISSHI_KAISHI_YMD  DATE --「業務実施開始年月日」
	,SAGYO_KAISHI_TM  CHAR(4) --「作業開始時刻」
	,GYOMU_JISSHI_SHURYO_YMD  DATE --「業務実施終了年月日」
	,SAGYO_SHURYO_TM  CHAR(4) --「作業終了時刻」
	,SAGYO_JIKAN  NUMBER(12,3) DEFAULT '0' NOT NULL --「作業時間」
	,UNKO_NINZU  NUMBER(9,0) DEFAULT '0' NOT NULL --「運行人数」
	,JOCHU_KEIBI_JISSEKIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「常駐警備実績有フラグ」
	,KEIBI_ITAKU_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「警備委託単価金額」
	,RINJI_KEIBI_SHIHARAI_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「臨時警備支払時間」
	,GYOMU_ITAKU_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「業務委託料金金額」
	,KEIBITAKU_TANKA_KAKUTEI_KBN  CHAR(1) NOT NULL --「警備委託単価確定状況区分」
	,ITAKU_TESURYO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「委託手数料金額」
	,UYO_JOCHU_GMITAKU_RYOKIN_BIKO  VARCHAR2(50) --「運用常駐業務委託料金備考」
	,SEIKYU_SAGYO_JISSEKI_JIKAN  NUMBER(12,3) DEFAULT '0' NOT NULL --「請求作業実績時間」
	,KEIBI_RYOKIN_SEIKYUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備料金請求有フラグ」
	,KIHON_KYTS_KIYK_RYOKIN_TYPE_CD  CHAR(3) --「基本共通契約料金タイプコード」
	,JIKAN_TANKA_RYOKIN_TYPE_CD  CHAR(3) --「時間単価料金タイプコード」
	,GYM_ITKMT_SIKY_KKTI_JKY_KBN  CHAR(1) NOT NULL --「業務委託元契約請求確定状況区分」
	,GYMITAKUSK_SEIKYU_KKTEI_KBN  CHAR(1) NOT NULL --「業務委託先請求確定状況区分」
	,GYOMUITAKU_ATM_KAKUTEIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「業務委託料金確定有フラグ」
	,JCH_CHK_GYM_ITK_TOKKI_JIKO  VARCHAR2(200) --「常駐長期業務委託特記事項」
	,GYM_ITKSK_TRHKSK_BSH_CD  CHAR(4) --「業務委託先取引先部署コード」
	,UNYO_GYM_ITK_HATCHUZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「運用業務委託発注済フラグ」
	,HAICHI_POST_KAITEI_KBN  CHAR(1) NOT NULL --「配置ポスト改定区分」
	,ZEINUKI_SEIKYU_AMT  NUMBER(13,0) --「税抜請求金額」
	,RYYMT_UNYO_JOCHU_SHOSAI_SN  CHAR(14) --「流用元運用常駐詳細連番」
	,JCH_KEB_NMMU_RKKYO_NAIYO  VARCHAR2(100) --「常駐警備任務列挙内容」
	,UNYO_KBN  CHAR(1) NOT NULL --「運用区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0677T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  UNYO_HENKO_RIREKI_NO
	,  UNYO_JOCHU_SHOSAI_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0677T_TBL IS '運用常駐詳細テーブル'
/

COMMENT ON COLUMN ED0677T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0677T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0677T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0677T_TBL.UNYO_HENKO_RIREKI_NO IS '運用変更履歴番号'
/
COMMENT ON COLUMN ED0677T_TBL.UNYO_JOCHU_SHOSAI_SN IS '運用常駐詳細連番'
/
COMMENT ON COLUMN ED0677T_TBL.GYOMU_SAIITAKUARI_FLG IS '業務再委託有フラグ'
/
COMMENT ON COLUMN ED0677T_TBL.KEIBIIN_SEIFUKU_KBN IS '警備員制服区分'
/
COMMENT ON COLUMN ED0677T_TBL.SONOTA_KEIBIIN_SEIFUKU_NAIYO IS 'その他警備員制服内容'
/
COMMENT ON COLUMN ED0677T_TBL.JISHA_DENWA_RENRAKUSAKI_NAIYO IS '自社電話連絡先内容'
/
COMMENT ON COLUMN ED0677T_TBL.KEIBI_GYOHO_1_GO_GYOMUARI_FLG IS '警備業法１号業務有フラグ'
/
COMMENT ON COLUMN ED0677T_TBL.KEIBI_GYOHO_2_GO_GYOMUARI_FLG IS '警備業法２号業務有フラグ'
/
COMMENT ON COLUMN ED0677T_TBL.KEIBI_GYOHO_3_GO_GYOMUARI_FLG IS '警備業法３号業務有フラグ'
/
COMMENT ON COLUMN ED0677T_TBL.KEIBI_GYOHO_4_GO_GYOMUARI_FLG IS '警備業法４号業務有フラグ'
/
COMMENT ON COLUMN ED0677T_TBL.TOSHO_SHOHI_ZEIRITSU_CD IS '当初消費税率コード'
/
COMMENT ON COLUMN ED0677T_TBL.SHOHIZEI_RITSU IS '消費税率'
/
COMMENT ON COLUMN ED0677T_TBL.HIKAZEI_RIYU IS '非課税理由'
/
COMMENT ON COLUMN ED0677T_TBL.KIBTI_KG_TRATSKIAR_FLG IS '警備隊鍵取扱有フラグ'
/
COMMENT ON COLUMN ED0677T_TBL.KIBTI_KG_TRATSKI_TKK_JIKO IS '警備隊鍵取扱特記事項'
/
COMMENT ON COLUMN ED0677T_TBL.HKKSH_GNCH_TISHTSAR_FLG IS '報告書現地提出有フラグ'
/
COMMENT ON COLUMN ED0677T_TBL.HKKSH_GNCH_TISHTS_TKK_JIKO IS '報告書現地提出特記事項'
/
COMMENT ON COLUMN ED0677T_TBL.GYM_ITKSK_TRHKSK_CD IS '業務委託先取引先コード'
/
COMMENT ON COLUMN ED0677T_TBL.GYOMU_JISSHI_KAISHI_YMD IS '業務実施開始年月日'
/
COMMENT ON COLUMN ED0677T_TBL.SAGYO_KAISHI_TM IS '作業開始時刻'
/
COMMENT ON COLUMN ED0677T_TBL.GYOMU_JISSHI_SHURYO_YMD IS '業務実施終了年月日'
/
COMMENT ON COLUMN ED0677T_TBL.SAGYO_SHURYO_TM IS '作業終了時刻'
/
COMMENT ON COLUMN ED0677T_TBL.SAGYO_JIKAN IS '作業時間'
/
COMMENT ON COLUMN ED0677T_TBL.UNKO_NINZU IS '運行人数'
/
COMMENT ON COLUMN ED0677T_TBL.JOCHU_KEIBI_JISSEKIARI_FLG IS '常駐警備実績有フラグ'
/
COMMENT ON COLUMN ED0677T_TBL.KEIBI_ITAKU_TANKA_AMT IS '警備委託単価金額'
/
COMMENT ON COLUMN ED0677T_TBL.RINJI_KEIBI_SHIHARAI_JIKAN IS '臨時警備支払時間'
/
COMMENT ON COLUMN ED0677T_TBL.GYOMU_ITAKU_RYOKIN_AMT IS '業務委託料金金額'
/
COMMENT ON COLUMN ED0677T_TBL.KEIBITAKU_TANKA_KAKUTEI_KBN IS '警備委託単価確定状況区分'
/
COMMENT ON COLUMN ED0677T_TBL.ITAKU_TESURYO_AMT IS '委託手数料金額'
/
COMMENT ON COLUMN ED0677T_TBL.UYO_JOCHU_GMITAKU_RYOKIN_BIKO IS '運用常駐業務委託料金備考'
/
COMMENT ON COLUMN ED0677T_TBL.SEIKYU_SAGYO_JISSEKI_JIKAN IS '請求作業実績時間'
/
COMMENT ON COLUMN ED0677T_TBL.KEIBI_RYOKIN_SEIKYUARI_FLG IS '警備料金請求有フラグ'
/
COMMENT ON COLUMN ED0677T_TBL.KIHON_KYTS_KIYK_RYOKIN_TYPE_CD IS '基本共通契約料金タイプコード'
/
COMMENT ON COLUMN ED0677T_TBL.JIKAN_TANKA_RYOKIN_TYPE_CD IS '時間単価料金タイプコード'
/
COMMENT ON COLUMN ED0677T_TBL.GYM_ITKMT_SIKY_KKTI_JKY_KBN IS '業務委託元契約請求確定状況区分'
/
COMMENT ON COLUMN ED0677T_TBL.GYMITAKUSK_SEIKYU_KKTEI_KBN IS '業務委託先請求確定状況区分'
/
COMMENT ON COLUMN ED0677T_TBL.GYOMUITAKU_ATM_KAKUTEIARI_FLG IS '業務委託料金確定有フラグ'
/
COMMENT ON COLUMN ED0677T_TBL.JCH_CHK_GYM_ITK_TOKKI_JIKO IS '常駐長期業務委託特記事項'
/
COMMENT ON COLUMN ED0677T_TBL.GYM_ITKSK_TRHKSK_BSH_CD IS '業務委託先取引先部署コード'
/
COMMENT ON COLUMN ED0677T_TBL.UNYO_GYM_ITK_HATCHUZUMI_FLG IS '運用業務委託発注済フラグ'
/
COMMENT ON COLUMN ED0677T_TBL.HAICHI_POST_KAITEI_KBN IS '配置ポスト改定区分'
/
COMMENT ON COLUMN ED0677T_TBL.ZEINUKI_SEIKYU_AMT IS '税抜請求金額'
/
COMMENT ON COLUMN ED0677T_TBL.RYYMT_UNYO_JOCHU_SHOSAI_SN IS '流用元運用常駐詳細連番'
/
COMMENT ON COLUMN ED0677T_TBL.JCH_KEB_NMMU_RKKYO_NAIYO IS '常駐警備任務列挙内容'
/
COMMENT ON COLUMN ED0677T_TBL.UNYO_KBN IS '運用区分'
/
COMMENT ON COLUMN ED0677T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0677T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0677T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0677T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0677T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0677T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0677T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0677T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0677T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0677T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0677T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0677T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
