/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0613T_TBL.sql
-- 物理名：ED0613T_TBL
-- 論理名：契約両替金テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0613T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0613T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIYAKU_ID  CHAR(18) NOT NULL --「契約ＩＤ」
	,RYOGAEKI_SAKUSEI_AMT  NUMBER(15,2) DEFAULT '0' NOT NULL --「両替機作成金額」
	,RYOGAEKIN_5_SENEN_SHIHEI_MAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「両替金５千円紙幣枚数」
	,RYOGAEKIN_SENEN_SHIHEI_MAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「両替金千円紙幣枚数」
	,RYGEKN_500_EMB_KMB_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「両替金５００円棒金棒数量」
	,RYGEKN_100_EMB_KMB_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「両替金１００円棒金棒数量」
	,RYOGAEKIN_50_EMBO_KANABO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「両替金５０円棒金棒数量」
	,RYOGAEKIN_10_EMBO_KANABO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「両替金１０円棒金棒数量」
	,RYOGAEKIN_5_EMBO_KANABO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「両替金５円棒金棒数量」
	,RYOGAEKIN_1_EMBO_KANABO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「両替金１円棒金棒数量」
	,RYOGAEKIN_500_EN_KOKA_MAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「両替金５００円硬貨枚数」
	,RYOGAEKIN_100_EN_KOKA_MAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「両替金１００円硬貨枚数」
	,URIAGE_UNYO_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上運用原価金額」
	,TSURISEN_HAIKIN_HINDO_CD  CHAR(3) --「釣銭配金頻度コード」
	,RYOGAEKI_KISHU_CD  CHAR(8) --「両替機機種コード」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0613T_PK PRIMARY KEY(
	 KEIYAKU_ID
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0613T_TBL IS '契約両替金テーブル'
/

COMMENT ON COLUMN ED0613T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0613T_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED0613T_TBL.RYOGAEKI_SAKUSEI_AMT IS '両替機作成金額'
/
COMMENT ON COLUMN ED0613T_TBL.RYOGAEKIN_5_SENEN_SHIHEI_MAISU IS '両替金５千円紙幣枚数'
/
COMMENT ON COLUMN ED0613T_TBL.RYOGAEKIN_SENEN_SHIHEI_MAISU IS '両替金千円紙幣枚数'
/
COMMENT ON COLUMN ED0613T_TBL.RYGEKN_500_EMB_KMB_SURYO IS '両替金５００円棒金棒数量'
/
COMMENT ON COLUMN ED0613T_TBL.RYGEKN_100_EMB_KMB_SURYO IS '両替金１００円棒金棒数量'
/
COMMENT ON COLUMN ED0613T_TBL.RYOGAEKIN_50_EMBO_KANABO_SURYO IS '両替金５０円棒金棒数量'
/
COMMENT ON COLUMN ED0613T_TBL.RYOGAEKIN_10_EMBO_KANABO_SURYO IS '両替金１０円棒金棒数量'
/
COMMENT ON COLUMN ED0613T_TBL.RYOGAEKIN_5_EMBO_KANABO_SURYO IS '両替金５円棒金棒数量'
/
COMMENT ON COLUMN ED0613T_TBL.RYOGAEKIN_1_EMBO_KANABO_SURYO IS '両替金１円棒金棒数量'
/
COMMENT ON COLUMN ED0613T_TBL.RYOGAEKIN_500_EN_KOKA_MAISU IS '両替金５００円硬貨枚数'
/
COMMENT ON COLUMN ED0613T_TBL.RYOGAEKIN_100_EN_KOKA_MAISU IS '両替金１００円硬貨枚数'
/
COMMENT ON COLUMN ED0613T_TBL.URIAGE_UNYO_GENKA_AMT IS '売上運用原価金額'
/
COMMENT ON COLUMN ED0613T_TBL.TSURISEN_HAIKIN_HINDO_CD IS '釣銭配金頻度コード'
/
COMMENT ON COLUMN ED0613T_TBL.RYOGAEKI_KISHU_CD IS '両替機機種コード'
/
COMMENT ON COLUMN ED0613T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0613T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0613T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0613T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0613T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0613T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0613T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0613T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0613T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0613T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0613T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0613T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
