/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0651T_TBL.sql
-- 物理名：ED0651T_TBL
-- 論理名：工事指示書警報盤テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0651T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0651T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_SHIJISHO_NO  CHAR(18) NOT NULL --「工事指示書番号」
	,KOJI_SHIJISHO_KEIHO_BAN_SN  CHAR(1) NOT NULL --「工事指示書警報盤連番」
	,KEIHO_BAN_SETSUBI_NAIYO_KBN  CHAR(2) NOT NULL --「警報盤設備内容区分」
	,SONOTA_KEIHO_BAN_SETSUBI_NM  VARCHAR2(60) --「その他警報盤設備名称」
	,KEIHO_BAN_SETSUBI_MAKER_NM  VARCHAR2(100) --「警報盤設備メーカ名称」
	,KEIHO_BAN_SETSUBI_KATASHIKI_NM  VARCHAR2(15) --「警報盤設備型式名称」
	,KEIHO_BAN_SETSUBI_TANSHI_NM_1  VARCHAR2(16) --「警報盤設備端子名称１」
	,KEIHO_BAN_SETSUBI_TANSHI_NM_2  VARCHAR2(16) --「警報盤設備端子名称２」
	,KEIHO_BAN_SETSUBI_TANSHI_KBN  CHAR(2) NOT NULL --「警報盤設備端子区分」
	,SNT_KIH_BN_STSB_TNSH_NM  VARCHAR2(16) --「その他警報盤設備端子名称」
	,KIH_BN_STSB_STSZK_GYSH_NM  VARCHAR2(40) --「警報盤設備接続業者名称」
	,KIH_BN_STSB_STSZK_GYSH_DNW_NO  VARCHAR2(20) --「警報盤設備接続業者電話番号」
	,SIGY_SHNG_SHTSRYK_NAIYO_KBN  CHAR(1) DEFAULT '0' NOT NULL --「制御信号出力内容区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0651T_PK PRIMARY KEY(
	 KOJI_SHIJISHO_NO
	,  KAISHA_CD
	,  KOJI_SHIJISHO_KEIHO_BAN_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0651T_TBL IS '工事指示書警報盤テーブル'
/

COMMENT ON COLUMN ED0651T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0651T_TBL.KOJI_SHIJISHO_NO IS '工事指示書番号'
/
COMMENT ON COLUMN ED0651T_TBL.KOJI_SHIJISHO_KEIHO_BAN_SN IS '工事指示書警報盤連番'
/
COMMENT ON COLUMN ED0651T_TBL.KEIHO_BAN_SETSUBI_NAIYO_KBN IS '警報盤設備内容区分'
/
COMMENT ON COLUMN ED0651T_TBL.SONOTA_KEIHO_BAN_SETSUBI_NM IS 'その他警報盤設備名称'
/
COMMENT ON COLUMN ED0651T_TBL.KEIHO_BAN_SETSUBI_MAKER_NM IS '警報盤設備メーカ名称'
/
COMMENT ON COLUMN ED0651T_TBL.KEIHO_BAN_SETSUBI_KATASHIKI_NM IS '警報盤設備型式名称'
/
COMMENT ON COLUMN ED0651T_TBL.KEIHO_BAN_SETSUBI_TANSHI_NM_1 IS '警報盤設備端子名称１'
/
COMMENT ON COLUMN ED0651T_TBL.KEIHO_BAN_SETSUBI_TANSHI_NM_2 IS '警報盤設備端子名称２'
/
COMMENT ON COLUMN ED0651T_TBL.KEIHO_BAN_SETSUBI_TANSHI_KBN IS '警報盤設備端子区分'
/
COMMENT ON COLUMN ED0651T_TBL.SNT_KIH_BN_STSB_TNSH_NM IS 'その他警報盤設備端子名称'
/
COMMENT ON COLUMN ED0651T_TBL.KIH_BN_STSB_STSZK_GYSH_NM IS '警報盤設備接続業者名称'
/
COMMENT ON COLUMN ED0651T_TBL.KIH_BN_STSB_STSZK_GYSH_DNW_NO IS '警報盤設備接続業者電話番号'
/
COMMENT ON COLUMN ED0651T_TBL.SIGY_SHNG_SHTSRYK_NAIYO_KBN IS '制御信号出力内容区分'
/
COMMENT ON COLUMN ED0651T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0651T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0651T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0651T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0651T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0651T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0651T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0651T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0651T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0651T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0651T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0651T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
