/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0638T_TBL.sql
-- 物理名：ED0638T_TBL
-- 論理名：入出金機変更連絡詳細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0638T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0638T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,NSKK_KEIYAKU_HENKO_SYORI_KBN  CHAR(1) NOT NULL --「入出金機契約変更処理区分」
	,NYSHKKNK_HNK_RNRK_RRK_NO  CHAR(3) NOT NULL --「入出金機変更連絡履歴番号」
	,NYUSHUKKINKI_SN  CHAR(14) NOT NULL --「入出金機連番」
	,NYSHKKNK_ISTS_HNK_PATTERN_KBN  CHAR(1) NOT NULL --「入出金機移設変更パターン区分」
	,NYUSHUKKINKI_ISETSU_TAIYO_KBN  CHAR(1) NOT NULL --「入出金機移設態様区分」
	,NYUSHUKKINKI_ISETSU_SHOSAI_KBN  CHAR(1) NOT NULL --「入出金機移設詳細区分」
	,NYUSHUKKINKI_GOKI_NO  VARCHAR2(18) --「入出金機号機番号」
	,LEASE_KEIYAKUSHO_NO  VARCHAR2(13) --「リース契約書番号」
	,LEASE_KEIYAKUSHO_TEIKETSU_YMD  DATE --「リース契約書締結年月日」
	,NYSHKKNK_CHOHYO_SUBTITLE_NM  VARCHAR2(20) --「入出金機帳票サブタイトル名称」
	,CHOHYO_SYORI_KBN_NM  VARCHAR2(60) --「帳票処理区分名称」
	,NYSHKKNK_HNK_RNRKHY_SKSI_YMD  DATE --「入出金機変更連絡票作成年月日」
	,BKKN_STCH_BSH_HNK_NAIYO  VARCHAR2(20) --「物件設置場所変更内容」
	,HOKAN_BASHO_SENTAKU_KBN  CHAR(1) NOT NULL --「保管場所選択区分」
	,HOKAN_JIGYOSHO_CD  CHAR(6) --「保管事業所コード」
	,POOL_YO_SOKO_CD  CHAR(6) --「プール用倉庫コード」
	,SONOTA_HOKAN_BASHO_YUBIN_NO  CHAR(7) --「その他保管場所郵便番号」
	,SONOTA_HOKANSISETSU_NM  VARCHAR2(40) --「その他保管施設名称」
	,SONOTA_HOKAN_BASHO_JUSHO  VARCHAR2(60) --「その他保管場所住所」
	,SONOTA_HOKAN_BASHO_BANCHI  VARCHAR2(50) --「その他保管場所番地」
	,SAGYOHI_SEIKYU_JIGYOSHO_CD  CHAR(6) --「作業費請求事業所コード」
	,SGYH_SIKYSK_TNT_SHIN_NM  VARCHAR2(60) --「作業費請求先担当社員氏名」
	,NYSHKKNK_ISTSMT_YBN_NO  CHAR(7) --「入出金機移設元郵便番号」
	,NYUSHUKKINKI_ISETSUMOTO_JUSHO  VARCHAR2(60) --「入出金機移設元住所」
	,NYUSHUKKINKI_ISETSUMOTO_BANCHI  VARCHAR2(50) --「入出金機移設元番地」
	,KIYKSK_TISHSK_HNKAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「契約先対象先変更有フラグ」
	,HOSHURYO_JIGYOSHO_HENKOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保守料事業所変更有フラグ」
	,CHUDAN_SAIKAIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「中断再開有フラグ」
	,NYSHKKNK_KIYK_SIKI_RIYU  VARCHAR2(50) --「入出金機契約再開理由」
	,CHUDAN_SAIKAI_JOHO_BIKO_1  VARCHAR2(60) --「中断再開情報備考１」
	,CHUDAN_SAIKAI_JOHO_BIKO_2  VARCHAR2(60) --「中断再開情報備考２」
	,NYSHKKNK_ISTS_THI_NAIYO_KBN  CHAR(1) --「入出金機移設手配内容区分」
	,ISTSG_KIYKSK_TRHKSK_CD  CHAR(9) --「移設後契約先取引先コード」
	,ISETSUGO_TAISHOSAKI_CD  CHAR(9) --「移設後対象先コード」
	,NYUSHUKKINKI_ISETSUGO_YUBIN_NO  CHAR(7) --「入出金機移設後郵便番号」
	,NYUSHUKKINKI_ISETSUGO_JUSHO  VARCHAR2(60) --「入出金機移設後住所」
	,NYSHKKNK_ISTSG_JUSHO_BANCHI  VARCHAR2(50) --「入出金機移設後住所番地」
	,NSKKNK_ISTG_HSR_SIK_JGS_CD  CHAR(6) --「入出金機移設後保守料請求事業所コード」
	,ISETSUGO_TAISHOSAKI_DENWA_NO  VARCHAR2(20) --「移設後対象先電話番号」
	,ISETSUGO_KEISO_JIGYOSHO_CD  CHAR(6) --「移設後警送事業所コード」
	,ISETSUGO_KIKAI_JIGYOSHO_CD  CHAR(6) --「移設後機械事業所コード」
	,NYSHKKNK_TRHZSHSH_KBN  CHAR(1) --「入出金機取外し者区分」
	,NYUSHUKKINKI_TORIHAZUSHI_YMD  DATE --「入出金機取外し年月日」
	,NYUSHUKKINKI_TORIHAZUSHI_TM  CHAR(4) --「入出金機取外し時刻」
	,NYUSHUKKINKI_UMPANSHA_KBN  CHAR(1) --「入出金機運搬者区分」
	,NYUSHUKKINKI_HANSHUTSU_YMD  DATE --「入出金機搬出年月日」
	,NYUSHUKKINKI_HANSHUTSU_TM  CHAR(4) --「入出金機搬出時刻」
	,NYUSHUKKINKI_HANNYU_YMD  DATE --「入出金機搬入年月日」
	,NYUSHUKKINKI_HANNYU_TM  CHAR(4) --「入出金機搬入時刻」
	,NYUSHUKKINKI_SETCHISHA_KBN  CHAR(1) --「入出金機設置者区分」
	,NYUSHUKKINKI_SETCHI_YMD  DATE --「入出金機設置年月日」
	,NYUSHUKKINKI_SETCHI_TM  CHAR(4) --「入出金機設置時刻」
	,NYUSHUKKINKI_ISETSU_RIYU  VARCHAR2(50) --「入出金機移設理由」
	,ISETSU_SECURITY_PLATE_KBN  CHAR(1) --「移設セキュリティプレート区分」
	,ISETSU_FOOT_GUARD_KBN  CHAR(1) --「移設フットガード区分」
	,ISETSU_ANCHOR_PLATE_KBN  CHAR(1) --「移設アンカープレート区分」
	,ISETSU_SETCHI_HOJO_PLATE_KBN  CHAR(1) --「移設設置補助プレート区分」
	,ISETSU_BOOK_PRINTER_KBN  CHAR(1) --「移設ブックプリンタ区分」
	,ISETSU_DUMMY_BOLT_KBN  CHAR(1) --「移設ダミーボルト区分」
	,NYUSHUKKINKI_SHIYO_JOKYO_KBN  CHAR(1) NOT NULL --「入出金機使用状況区分」
	,POOL_KOKAI_HANI_KBN  CHAR(1) NOT NULL --「プール公開範囲区分」
	,NYUSHUKKINKI_TEKKYO_YMD  DATE --「入出金機撤去年月日」
	,NYUSHUKKINKI_TEKKYO_TM  CHAR(4) --「入出金機撤去時刻」
	,TEKKYO_KOJIARI_FLG  CHAR(1) --「撤去工事有フラグ」
	,KOJI_KAISHI_YMD  DATE --「工事開始年月日」
	,KOJI_SHURYO_YMD  DATE --「工事終了年月日」
	,KIYK_NYSHKKNK_HNSHTS_YMD  DATE --「解約入出金機搬出年月日」
	,KIYK_NYSHKKNK_HNSHTS_TM  CHAR(4) --「解約入出金機搬出時刻」
	,KIYK_NYSHKKNK_TRHZSHSH_KBN  CHAR(1) --「解約入出金機取外し者区分」
	,KIYK_NYSHKKNK_HNSHTSSH_KBN  CHAR(1) --「解約入出金機搬出者区分」
	,KIYK_NYSHKKNK_IRKEAR_FLG  CHAR(1) --「解約入出金機入替有フラグ」
	,KIYK_NYSHKKNK_IRKE_GYSH_KBN  CHAR(1) --「解約入出金機入替業者区分」
	,KIYK_HKN_BSH_SNTK_KBN  CHAR(1) NOT NULL --「解約保管場所選択区分」
	,KIYK_HKN_BSH_JGYSH_CD  CHAR(6) --「解約保管場所事業所コード」
	,KAIYAKU_POOL_YO_SOKO_CD  CHAR(6) --「解約プール用倉庫コード」
	,SONOTA_KAIYAKU_HOKAN_YUBIN_NO  CHAR(7) --「その他解約保管郵便番号」
	,SONOTA_KYK_HOKANSISETSU_NM  VARCHAR2(40) --「その他解約保管施設名称」
	,SONOTA_KAIYAKU_HOKAN_JUSHO  VARCHAR2(60) --「その他解約保管住所」
	,SNT_KIYK_HKN_JUSHO_BANCHI  VARCHAR2(50) --「その他解約保管住所番地」
	,KIYK_HSHRY_JGYSH_HNKAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「解約保守料事業所変更有フラグ」
	,KIYK_HKNG_HSH_SIKY_JGYSH_CD  CHAR(6) --「解約保管後保守請求事業所コード」
	,KIYK_KIS_JSSH_JGYSH_HNKAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「解約警送実施事業所変更有フラグ」
	,KIYK_HKNG_KIS_JSSH_JGYSH_CD  CHAR(6) --「解約保管後警送実施事業所コード」
	,NYUSHUKKINKI_HAIKISHA_KBN  CHAR(1) --「入出金機廃棄者区分」
	,KAIYAKU_JOHO_BIKO_1  VARCHAR2(50) --「解約情報備考１」
	,KAIYAKU_JOHO_BIKO_2  VARCHAR2(50) --「解約情報備考２」
	,NYUSHUKKINKI_KOTEI_HOHO_KBN  CHAR(1) --「入出金機固定方法区分」
	,NSKKNK_BHN_PROTECTOR_STAR_FLG  CHAR(1) --「入出金機防犯プロテクター設置有フラグ」
	,NYSHKKNK_KISN_SHBTS_CD  CHAR(3) --「入出金機回線種別コード」
	,NSKKNK_TERMINAL_ADAPTER_KS_KBN  CHAR(1) --「入出金機ターミナルアダプタ機種区分」
	,NYSHKKNK_PARAMETER_HNK_KBN  CHAR(1) --「入出金機パラメータ変更区分」
	,NYSHKKNK_STTI_SHJSH_SFAR_FLG  CHAR(1) --「入出金機設定指示書送付有フラグ」
	,MAKER_GNCH_SHTM_IRIAR_FLG  CHAR(1) --「メーカー現地下見依頼有フラグ」
	,NSKKNK_MAKER_GNC_STM_IRIAR_FLG  CHAR(1) --「入出金機メーカー現地下見依頼有フラグ」
	,NYSHKKNK_STCHSK_SGYTDKAR_FLG  CHAR(1) --「入出金機設置先作業届有フラグ」
	,HNSHTS_GNZI_KTI_HH_KBN  CHAR(1) --「搬出現在固定方法区分」
	,HANSHUTSU_CHUSHAJO_UMU_KBN  CHAR(1) --「搬出駐車場有無区分」
	,HANSHUTSU_SETCHI_BASHO_KYORI_M  NUMBER(12,3) DEFAULT '0' NOT NULL --「搬出設置場所距離メートル」
	,HNSHTS_NRIRK_TRUCK_SHRI_KBN  CHAR(1) --「搬出乗入可トラック種類区分」
	,HNSHTS_TTMNNI_DNSAR_FLG  CHAR(1) --「搬出建物内段差有フラグ」
	,HANSHUTSU_TATEMONONAI_DANSASU  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬出建物内段差数」
	,HANSHUTSU_TATEMONONAI_DANSA_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬出建物内段差センチ」
	,HANSHUTSU_ISETSU_KEIROHABA_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬出移設径路幅センチ」
	,HNSHTS_STCH_BSH_DNSAR_FLG  CHAR(1) --「搬出設置場所段差有フラグ」
	,HNSHTS_STCH_BSH_DNS_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬出設置場所段差数量」
	,HNSHTS_STCH_BSH_DNS_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬出設置場所段差センチ」
	,HANSHUTSU_KAI  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬出階」
	,HANSHUTSU_ELEVATOR_SHIYOKA_FLG  CHAR(1) --「搬出エレベーター使用可フラグ」
	,HNSHTS_ELEVATOR_DNSAR_FLG  CHAR(1) --「搬出エレベーター段差有フラグ」
	,HNSHTS_ELEVATOR_DNS_TKS_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬出エレベーター段差高さセンチ」
	,HANSHUTSU_KAIDAN_KEIJO_KBN  CHAR(1) --「搬出階段形状区分」
	,HNSHTSZ_B_HB_150_CM_IJ_FLG  CHAR(1) --「搬出図Ｂ幅１５０センチ以上フラグ」
	,HANSHUTSUZU_B_HABA_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬出図Ｂ幅センチ」
	,HNSHTSZ_A_HB_120_CM_IJ_FLG  CHAR(1) --「搬出図Ａ幅１２０センチ以上フラグ」
	,HANSHUTSUZU_A_HABA_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬出図Ａ幅センチ」
	,HANSHUTSU_ODORIBAYOKO_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬出踊り場横センチ」
	,HANSHUTSU_ODORIBATATE_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬出踊り場縦センチ」
	,HANSHUTSU_KAIDAN_KAKUDO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬出階段角度数量」
	,HANNYU_CHUSHAJO_UMU_KBN  CHAR(1) --「搬入駐車場有無区分」
	,HANNYU_SETCHI_BASHO_KYORI_M  NUMBER(12,3) DEFAULT '0' NOT NULL --「搬入設置場所距離メートル」
	,HNNY_NRIRK_TRUCK_SHRI_KBN  CHAR(1) --「搬入乗入可トラック種類区分」
	,HNNY_TTMNNI_DNSAR_FLG  CHAR(1) --「搬入建物内段差有フラグ」
	,HANNYU_TATEMONONAI_DANSASU  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬入建物内段差数」
	,HANNYU_TATEMONONAI_DANSA_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬入建物内段差センチ」
	,HANNYU_HANNYUGUCHIHABA_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬入搬入口幅センチ」
	,HNNY_STCH_BSH_DNSAR_FLG  CHAR(1) --「搬入設置場所段差有フラグ」
	,HNNY_STCH_BSH_DNS_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬入設置場所段差数量」
	,HANNYU_SETCHI_BASHO_DANSA_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬入設置場所段差センチ」
	,HANNYU_KAI  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬入階」
	,HANNYU_ELEVATOR_SHIYOKA_FLG  CHAR(1) --「搬入エレベーター使用可フラグ」
	,HANNYU_ELEVATOR_DANSAARI_FLG  CHAR(1) --「搬入エレベーター段差有フラグ」
	,HNNY_ELEVATOR_DNS_TKS_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬入エレベーター段差高さセンチ」
	,HANNYU_KAIDAN_KEIJO_KBN  CHAR(1) --「搬入階段形状区分」
	,HANNYUZU_B_HABA_150_CM_IJO_FLG  CHAR(1) --「搬入図Ｂ幅１５０センチ以上フラグ」
	,HANNYUZU_B_HABA_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬入図Ｂ幅センチ」
	,HANNYUZU_A_HABA_120_CM_IJO_FLG  CHAR(1) --「搬入図Ａ幅１２０センチ以上フラグ」
	,HANNYUZU_A_HABA_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬入図Ａ幅センチ」
	,HANNYU_ODORIBAYOKO_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬入踊り場横センチ」
	,HANNYU_ODORIBATATE_CM  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬入踊り場縦センチ」
	,HANNYU_KAIDAN_KAKUDO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「搬入階段角度数量」
	,SAGYOJI_CHUI_JIKO_1  VARCHAR2(30) --「作業時注意事項１」
	,SAGYOJI_CHUI_JIKO_2  VARCHAR2(30) --「作業時注意事項２」
	,HOSHURYO_SEIKYU_JIGYOSHO_NM  VARCHAR2(200) --「保守料請求事業所名称」
	,HOSHURYO_SEIKYU_JIGYOSHO_CD  CHAR(6) --「保守料請求事業所コード」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0638T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  NSKK_KEIYAKU_HENKO_SYORI_KBN
	,  NYSHKKNK_HNK_RNRK_RRK_NO
	,  NYUSHUKKINKI_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0638T_TBL IS '入出金機変更連絡詳細テーブル'
/

COMMENT ON COLUMN ED0638T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0638T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0638T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0638T_TBL.NSKK_KEIYAKU_HENKO_SYORI_KBN IS '入出金機契約変更処理区分'
/
COMMENT ON COLUMN ED0638T_TBL.NYSHKKNK_HNK_RNRK_RRK_NO IS '入出金機変更連絡履歴番号'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_SN IS '入出金機連番'
/
COMMENT ON COLUMN ED0638T_TBL.NYSHKKNK_ISTS_HNK_PATTERN_KBN IS '入出金機移設変更パターン区分'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_ISETSU_TAIYO_KBN IS '入出金機移設態様区分'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_ISETSU_SHOSAI_KBN IS '入出金機移設詳細区分'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_GOKI_NO IS '入出金機号機番号'
/
COMMENT ON COLUMN ED0638T_TBL.LEASE_KEIYAKUSHO_NO IS 'リース契約書番号'
/
COMMENT ON COLUMN ED0638T_TBL.LEASE_KEIYAKUSHO_TEIKETSU_YMD IS 'リース契約書締結年月日'
/
COMMENT ON COLUMN ED0638T_TBL.NYSHKKNK_CHOHYO_SUBTITLE_NM IS '入出金機帳票サブタイトル名称'
/
COMMENT ON COLUMN ED0638T_TBL.CHOHYO_SYORI_KBN_NM IS '帳票処理区分名称'
/
COMMENT ON COLUMN ED0638T_TBL.NYSHKKNK_HNK_RNRKHY_SKSI_YMD IS '入出金機変更連絡票作成年月日'
/
COMMENT ON COLUMN ED0638T_TBL.BKKN_STCH_BSH_HNK_NAIYO IS '物件設置場所変更内容'
/
COMMENT ON COLUMN ED0638T_TBL.HOKAN_BASHO_SENTAKU_KBN IS '保管場所選択区分'
/
COMMENT ON COLUMN ED0638T_TBL.HOKAN_JIGYOSHO_CD IS '保管事業所コード'
/
COMMENT ON COLUMN ED0638T_TBL.POOL_YO_SOKO_CD IS 'プール用倉庫コード'
/
COMMENT ON COLUMN ED0638T_TBL.SONOTA_HOKAN_BASHO_YUBIN_NO IS 'その他保管場所郵便番号'
/
COMMENT ON COLUMN ED0638T_TBL.SONOTA_HOKANSISETSU_NM IS 'その他保管施設名称'
/
COMMENT ON COLUMN ED0638T_TBL.SONOTA_HOKAN_BASHO_JUSHO IS 'その他保管場所住所'
/
COMMENT ON COLUMN ED0638T_TBL.SONOTA_HOKAN_BASHO_BANCHI IS 'その他保管場所番地'
/
COMMENT ON COLUMN ED0638T_TBL.SAGYOHI_SEIKYU_JIGYOSHO_CD IS '作業費請求事業所コード'
/
COMMENT ON COLUMN ED0638T_TBL.SGYH_SIKYSK_TNT_SHIN_NM IS '作業費請求先担当社員氏名'
/
COMMENT ON COLUMN ED0638T_TBL.NYSHKKNK_ISTSMT_YBN_NO IS '入出金機移設元郵便番号'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_ISETSUMOTO_JUSHO IS '入出金機移設元住所'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_ISETSUMOTO_BANCHI IS '入出金機移設元番地'
/
COMMENT ON COLUMN ED0638T_TBL.KIYKSK_TISHSK_HNKAR_FLG IS '契約先対象先変更有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.HOSHURYO_JIGYOSHO_HENKOARI_FLG IS '保守料事業所変更有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.CHUDAN_SAIKAIARI_FLG IS '中断再開有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.NYSHKKNK_KIYK_SIKI_RIYU IS '入出金機契約再開理由'
/
COMMENT ON COLUMN ED0638T_TBL.CHUDAN_SAIKAI_JOHO_BIKO_1 IS '中断再開情報備考１'
/
COMMENT ON COLUMN ED0638T_TBL.CHUDAN_SAIKAI_JOHO_BIKO_2 IS '中断再開情報備考２'
/
COMMENT ON COLUMN ED0638T_TBL.NYSHKKNK_ISTS_THI_NAIYO_KBN IS '入出金機移設手配内容区分'
/
COMMENT ON COLUMN ED0638T_TBL.ISTSG_KIYKSK_TRHKSK_CD IS '移設後契約先取引先コード'
/
COMMENT ON COLUMN ED0638T_TBL.ISETSUGO_TAISHOSAKI_CD IS '移設後対象先コード'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_ISETSUGO_YUBIN_NO IS '入出金機移設後郵便番号'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_ISETSUGO_JUSHO IS '入出金機移設後住所'
/
COMMENT ON COLUMN ED0638T_TBL.NYSHKKNK_ISTSG_JUSHO_BANCHI IS '入出金機移設後住所番地'
/
COMMENT ON COLUMN ED0638T_TBL.NSKKNK_ISTG_HSR_SIK_JGS_CD IS '入出金機移設後保守料請求事業所コード'
/
COMMENT ON COLUMN ED0638T_TBL.ISETSUGO_TAISHOSAKI_DENWA_NO IS '移設後対象先電話番号'
/
COMMENT ON COLUMN ED0638T_TBL.ISETSUGO_KEISO_JIGYOSHO_CD IS '移設後警送事業所コード'
/
COMMENT ON COLUMN ED0638T_TBL.ISETSUGO_KIKAI_JIGYOSHO_CD IS '移設後機械事業所コード'
/
COMMENT ON COLUMN ED0638T_TBL.NYSHKKNK_TRHZSHSH_KBN IS '入出金機取外し者区分'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_TORIHAZUSHI_YMD IS '入出金機取外し年月日'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_TORIHAZUSHI_TM IS '入出金機取外し時刻'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_UMPANSHA_KBN IS '入出金機運搬者区分'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_HANSHUTSU_YMD IS '入出金機搬出年月日'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_HANSHUTSU_TM IS '入出金機搬出時刻'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_HANNYU_YMD IS '入出金機搬入年月日'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_HANNYU_TM IS '入出金機搬入時刻'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_SETCHISHA_KBN IS '入出金機設置者区分'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_SETCHI_YMD IS '入出金機設置年月日'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_SETCHI_TM IS '入出金機設置時刻'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_ISETSU_RIYU IS '入出金機移設理由'
/
COMMENT ON COLUMN ED0638T_TBL.ISETSU_SECURITY_PLATE_KBN IS '移設セキュリティプレート区分'
/
COMMENT ON COLUMN ED0638T_TBL.ISETSU_FOOT_GUARD_KBN IS '移設フットガード区分'
/
COMMENT ON COLUMN ED0638T_TBL.ISETSU_ANCHOR_PLATE_KBN IS '移設アンカープレート区分'
/
COMMENT ON COLUMN ED0638T_TBL.ISETSU_SETCHI_HOJO_PLATE_KBN IS '移設設置補助プレート区分'
/
COMMENT ON COLUMN ED0638T_TBL.ISETSU_BOOK_PRINTER_KBN IS '移設ブックプリンタ区分'
/
COMMENT ON COLUMN ED0638T_TBL.ISETSU_DUMMY_BOLT_KBN IS '移設ダミーボルト区分'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_SHIYO_JOKYO_KBN IS '入出金機使用状況区分'
/
COMMENT ON COLUMN ED0638T_TBL.POOL_KOKAI_HANI_KBN IS 'プール公開範囲区分'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_TEKKYO_YMD IS '入出金機撤去年月日'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_TEKKYO_TM IS '入出金機撤去時刻'
/
COMMENT ON COLUMN ED0638T_TBL.TEKKYO_KOJIARI_FLG IS '撤去工事有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.KOJI_KAISHI_YMD IS '工事開始年月日'
/
COMMENT ON COLUMN ED0638T_TBL.KOJI_SHURYO_YMD IS '工事終了年月日'
/
COMMENT ON COLUMN ED0638T_TBL.KIYK_NYSHKKNK_HNSHTS_YMD IS '解約入出金機搬出年月日'
/
COMMENT ON COLUMN ED0638T_TBL.KIYK_NYSHKKNK_HNSHTS_TM IS '解約入出金機搬出時刻'
/
COMMENT ON COLUMN ED0638T_TBL.KIYK_NYSHKKNK_TRHZSHSH_KBN IS '解約入出金機取外し者区分'
/
COMMENT ON COLUMN ED0638T_TBL.KIYK_NYSHKKNK_HNSHTSSH_KBN IS '解約入出金機搬出者区分'
/
COMMENT ON COLUMN ED0638T_TBL.KIYK_NYSHKKNK_IRKEAR_FLG IS '解約入出金機入替有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.KIYK_NYSHKKNK_IRKE_GYSH_KBN IS '解約入出金機入替業者区分'
/
COMMENT ON COLUMN ED0638T_TBL.KIYK_HKN_BSH_SNTK_KBN IS '解約保管場所選択区分'
/
COMMENT ON COLUMN ED0638T_TBL.KIYK_HKN_BSH_JGYSH_CD IS '解約保管場所事業所コード'
/
COMMENT ON COLUMN ED0638T_TBL.KAIYAKU_POOL_YO_SOKO_CD IS '解約プール用倉庫コード'
/
COMMENT ON COLUMN ED0638T_TBL.SONOTA_KAIYAKU_HOKAN_YUBIN_NO IS 'その他解約保管郵便番号'
/
COMMENT ON COLUMN ED0638T_TBL.SONOTA_KYK_HOKANSISETSU_NM IS 'その他解約保管施設名称'
/
COMMENT ON COLUMN ED0638T_TBL.SONOTA_KAIYAKU_HOKAN_JUSHO IS 'その他解約保管住所'
/
COMMENT ON COLUMN ED0638T_TBL.SNT_KIYK_HKN_JUSHO_BANCHI IS 'その他解約保管住所番地'
/
COMMENT ON COLUMN ED0638T_TBL.KIYK_HSHRY_JGYSH_HNKAR_FLG IS '解約保守料事業所変更有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.KIYK_HKNG_HSH_SIKY_JGYSH_CD IS '解約保管後保守請求事業所コード'
/
COMMENT ON COLUMN ED0638T_TBL.KIYK_KIS_JSSH_JGYSH_HNKAR_FLG IS '解約警送実施事業所変更有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.KIYK_HKNG_KIS_JSSH_JGYSH_CD IS '解約保管後警送実施事業所コード'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_HAIKISHA_KBN IS '入出金機廃棄者区分'
/
COMMENT ON COLUMN ED0638T_TBL.KAIYAKU_JOHO_BIKO_1 IS '解約情報備考１'
/
COMMENT ON COLUMN ED0638T_TBL.KAIYAKU_JOHO_BIKO_2 IS '解約情報備考２'
/
COMMENT ON COLUMN ED0638T_TBL.NYUSHUKKINKI_KOTEI_HOHO_KBN IS '入出金機固定方法区分'
/
COMMENT ON COLUMN ED0638T_TBL.NSKKNK_BHN_PROTECTOR_STAR_FLG IS '入出金機防犯プロテクター設置有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.NYSHKKNK_KISN_SHBTS_CD IS '入出金機回線種別コード'
/
COMMENT ON COLUMN ED0638T_TBL.NSKKNK_TERMINAL_ADAPTER_KS_KBN IS '入出金機ターミナルアダプタ機種区分'
/
COMMENT ON COLUMN ED0638T_TBL.NYSHKKNK_PARAMETER_HNK_KBN IS '入出金機パラメータ変更区分'
/
COMMENT ON COLUMN ED0638T_TBL.NYSHKKNK_STTI_SHJSH_SFAR_FLG IS '入出金機設定指示書送付有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.MAKER_GNCH_SHTM_IRIAR_FLG IS 'メーカー現地下見依頼有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.NSKKNK_MAKER_GNC_STM_IRIAR_FLG IS '入出金機メーカー現地下見依頼有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.NYSHKKNK_STCHSK_SGYTDKAR_FLG IS '入出金機設置先作業届有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.HNSHTS_GNZI_KTI_HH_KBN IS '搬出現在固定方法区分'
/
COMMENT ON COLUMN ED0638T_TBL.HANSHUTSU_CHUSHAJO_UMU_KBN IS '搬出駐車場有無区分'
/
COMMENT ON COLUMN ED0638T_TBL.HANSHUTSU_SETCHI_BASHO_KYORI_M IS '搬出設置場所距離メートル'
/
COMMENT ON COLUMN ED0638T_TBL.HNSHTS_NRIRK_TRUCK_SHRI_KBN IS '搬出乗入可トラック種類区分'
/
COMMENT ON COLUMN ED0638T_TBL.HNSHTS_TTMNNI_DNSAR_FLG IS '搬出建物内段差有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.HANSHUTSU_TATEMONONAI_DANSASU IS '搬出建物内段差数'
/
COMMENT ON COLUMN ED0638T_TBL.HANSHUTSU_TATEMONONAI_DANSA_CM IS '搬出建物内段差センチ'
/
COMMENT ON COLUMN ED0638T_TBL.HANSHUTSU_ISETSU_KEIROHABA_CM IS '搬出移設径路幅センチ'
/
COMMENT ON COLUMN ED0638T_TBL.HNSHTS_STCH_BSH_DNSAR_FLG IS '搬出設置場所段差有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.HNSHTS_STCH_BSH_DNS_SURYO IS '搬出設置場所段差数量'
/
COMMENT ON COLUMN ED0638T_TBL.HNSHTS_STCH_BSH_DNS_CM IS '搬出設置場所段差センチ'
/
COMMENT ON COLUMN ED0638T_TBL.HANSHUTSU_KAI IS '搬出階'
/
COMMENT ON COLUMN ED0638T_TBL.HANSHUTSU_ELEVATOR_SHIYOKA_FLG IS '搬出エレベーター使用可フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.HNSHTS_ELEVATOR_DNSAR_FLG IS '搬出エレベーター段差有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.HNSHTS_ELEVATOR_DNS_TKS_CM IS '搬出エレベーター段差高さセンチ'
/
COMMENT ON COLUMN ED0638T_TBL.HANSHUTSU_KAIDAN_KEIJO_KBN IS '搬出階段形状区分'
/
COMMENT ON COLUMN ED0638T_TBL.HNSHTSZ_B_HB_150_CM_IJ_FLG IS '搬出図Ｂ幅１５０センチ以上フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.HANSHUTSUZU_B_HABA_CM IS '搬出図Ｂ幅センチ'
/
COMMENT ON COLUMN ED0638T_TBL.HNSHTSZ_A_HB_120_CM_IJ_FLG IS '搬出図Ａ幅１２０センチ以上フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.HANSHUTSUZU_A_HABA_CM IS '搬出図Ａ幅センチ'
/
COMMENT ON COLUMN ED0638T_TBL.HANSHUTSU_ODORIBAYOKO_CM IS '搬出踊り場横センチ'
/
COMMENT ON COLUMN ED0638T_TBL.HANSHUTSU_ODORIBATATE_CM IS '搬出踊り場縦センチ'
/
COMMENT ON COLUMN ED0638T_TBL.HANSHUTSU_KAIDAN_KAKUDO_SURYO IS '搬出階段角度数量'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYU_CHUSHAJO_UMU_KBN IS '搬入駐車場有無区分'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYU_SETCHI_BASHO_KYORI_M IS '搬入設置場所距離メートル'
/
COMMENT ON COLUMN ED0638T_TBL.HNNY_NRIRK_TRUCK_SHRI_KBN IS '搬入乗入可トラック種類区分'
/
COMMENT ON COLUMN ED0638T_TBL.HNNY_TTMNNI_DNSAR_FLG IS '搬入建物内段差有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYU_TATEMONONAI_DANSASU IS '搬入建物内段差数'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYU_TATEMONONAI_DANSA_CM IS '搬入建物内段差センチ'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYU_HANNYUGUCHIHABA_CM IS '搬入搬入口幅センチ'
/
COMMENT ON COLUMN ED0638T_TBL.HNNY_STCH_BSH_DNSAR_FLG IS '搬入設置場所段差有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.HNNY_STCH_BSH_DNS_SURYO IS '搬入設置場所段差数量'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYU_SETCHI_BASHO_DANSA_CM IS '搬入設置場所段差センチ'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYU_KAI IS '搬入階'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYU_ELEVATOR_SHIYOKA_FLG IS '搬入エレベーター使用可フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYU_ELEVATOR_DANSAARI_FLG IS '搬入エレベーター段差有フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.HNNY_ELEVATOR_DNS_TKS_CM IS '搬入エレベーター段差高さセンチ'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYU_KAIDAN_KEIJO_KBN IS '搬入階段形状区分'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYUZU_B_HABA_150_CM_IJO_FLG IS '搬入図Ｂ幅１５０センチ以上フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYUZU_B_HABA_CM IS '搬入図Ｂ幅センチ'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYUZU_A_HABA_120_CM_IJO_FLG IS '搬入図Ａ幅１２０センチ以上フラグ'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYUZU_A_HABA_CM IS '搬入図Ａ幅センチ'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYU_ODORIBAYOKO_CM IS '搬入踊り場横センチ'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYU_ODORIBATATE_CM IS '搬入踊り場縦センチ'
/
COMMENT ON COLUMN ED0638T_TBL.HANNYU_KAIDAN_KAKUDO_SURYO IS '搬入階段角度数量'
/
COMMENT ON COLUMN ED0638T_TBL.SAGYOJI_CHUI_JIKO_1 IS '作業時注意事項１'
/
COMMENT ON COLUMN ED0638T_TBL.SAGYOJI_CHUI_JIKO_2 IS '作業時注意事項２'
/
COMMENT ON COLUMN ED0638T_TBL.HOSHURYO_SEIKYU_JIGYOSHO_NM IS '保守料請求事業所名称'
/
COMMENT ON COLUMN ED0638T_TBL.HOSHURYO_SEIKYU_JIGYOSHO_CD IS '保守料請求事業所コード'
/
COMMENT ON COLUMN ED0638T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0638T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0638T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0638T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0638T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0638T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0638T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0638T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0638T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0638T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0638T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0638T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
