/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0640T_TBL.sql
-- 物理名：ED0640T_TBL
-- 論理名：入出金機変更連絡詳細変更テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0640T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0640T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,NSKK_KEIYAKU_HENKO_SYORI_KBN  CHAR(1) NOT NULL --「入出金機契約変更処理区分」
	,NYSHKKNK_HNK_RNRK_RRK_NO  CHAR(3) NOT NULL --「入出金機変更連絡履歴番号」
	,NYUSHUKKINKI_SN  CHAR(14) NOT NULL --「入出金機連番」
	,NSKK_HK_RENRAKU_SYOSAI_HK_SN  CHAR(14) NOT NULL --「入出金機変更連絡詳細変更連番」
	,NSKK_HENKO_KOMOKU_NM  VARCHAR2(60) --「入出金機変更項目名称」
	,NSKK_HENKOMAE_KOMOKU_NAIYO  VARCHAR2(100) --「入出金機変更前項目内容」
	,NSKK_HENKOGO_KOMOKU_NAIYO  VARCHAR2(100) --「入出金機変更後項目内容」
	,NSKK_HK_KOMOKU_SYURUI_KBN  CHAR(1) NOT NULL --「入出金機変更項目種類区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0640T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  NSKK_KEIYAKU_HENKO_SYORI_KBN
	,  NYSHKKNK_HNK_RNRK_RRK_NO
	,  NYUSHUKKINKI_SN
	,  NSKK_HK_RENRAKU_SYOSAI_HK_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0640T_TBL IS '入出金機変更連絡詳細変更テーブル'
/

COMMENT ON COLUMN ED0640T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0640T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0640T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0640T_TBL.NSKK_KEIYAKU_HENKO_SYORI_KBN IS '入出金機契約変更処理区分'
/
COMMENT ON COLUMN ED0640T_TBL.NYSHKKNK_HNK_RNRK_RRK_NO IS '入出金機変更連絡履歴番号'
/
COMMENT ON COLUMN ED0640T_TBL.NYUSHUKKINKI_SN IS '入出金機連番'
/
COMMENT ON COLUMN ED0640T_TBL.NSKK_HK_RENRAKU_SYOSAI_HK_SN IS '入出金機変更連絡詳細変更連番'
/
COMMENT ON COLUMN ED0640T_TBL.NSKK_HENKO_KOMOKU_NM IS '入出金機変更項目名称'
/
COMMENT ON COLUMN ED0640T_TBL.NSKK_HENKOMAE_KOMOKU_NAIYO IS '入出金機変更前項目内容'
/
COMMENT ON COLUMN ED0640T_TBL.NSKK_HENKOGO_KOMOKU_NAIYO IS '入出金機変更後項目内容'
/
COMMENT ON COLUMN ED0640T_TBL.NSKK_HK_KOMOKU_SYURUI_KBN IS '入出金機変更項目種類区分'
/
COMMENT ON COLUMN ED0640T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0640T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0640T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0640T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0640T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0640T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0640T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0640T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0640T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0640T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0640T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0640T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
