/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0698T_TBL.sql
-- 物理名：ED0698T_TBL
-- 論理名：運用警送通貨テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0698T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0698T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,UNYO_HENKO_RIREKI_NO  CHAR(10) NOT NULL --「運用変更履歴番号」
	,KEISO_KEIYAKU_YUSOHIN_JURYO_KG  NUMBER(9,0) DEFAULT '0' NOT NULL --「警送契約輸送品重量キログラム」
	,KEISO_KEIYAKU_YUSOHIN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「警送契約輸送品数量」
	,UKWTSHY_KNK_SHYSK_KBN  CHAR(1) NOT NULL --「受渡用金庫所有先区分」
	,SNT_UKWTSHY_KNK_SHYSK_NAIYO  VARCHAR2(30) --「その他受渡用金庫所有先内容」
	,KEISO_BAG_JUMBISAKI_KBN  CHAR(1) NOT NULL --「警送バック準備先区分」
	,SNT_KIS_BAG_JMBSK_NAIYO  VARCHAR2(30) --「その他警送バック準備先内容」
	,UKWTSH_DMPY_JMBSK_KBN  CHAR(1) NOT NULL --「受渡伝票準備先区分」
	,SNT_UKWTSH_DMPY_JMBSK_NAIYO  VARCHAR2(30) --「その他受渡伝票準備先内容」
	,SNT_TSRSN_KF_HH_NAIYO  VARCHAR2(30) --「その他釣銭交付方法内容」
	,CHINTAIHIN_KBN  CHAR(1) NOT NULL --「賃貸品区分」
	,SONOTA_CHINTAIHIN_NAIYO  VARCHAR2(30) --「その他賃貸品内容」
	,KOKYAKU_SHITEN_CD  CHAR(12) --「顧客支店コード」
	,TAMMATSU_CD  CHAR(15) --「端末コード」
	,SHIHEI_RYOKIN_TYPE_CD  CHAR(3) --「警送紙幣料金タイプコード」
	,KOKA_RYOKIN_TYPE_CD  CHAR(3) --「警送硬貨料金タイプコード」
	,GENKIN_KAISHU_TANI_KBN  CHAR(1) NOT NULL --「現金回収単位区分」
	,SNT_GNKN_KISH_TNI_NAIYO  VARCHAR2(30) --「その他現金回収単位内容」
	,GNKN_MCHKM_KNY_KKN_CD  CHAR(4) --「現金持込金融機関コード」
	,GENKIN_MOCHIKOMI_D_KBN  CHAR(1) NOT NULL --「現金持込日区分」
	,SNT_GNKN_MCHKM_D_STTI_NAIYO  VARCHAR2(30) --「その他現金持込日設定内容」
	,HAIKIN_TANI_KBN  CHAR(1) NOT NULL --「配金単位区分」
	,SONOTA_HAIKIN_TANI_NAIYO  VARCHAR2(30) --「その他配金単位内容」
	,SHUKKIN_KINYU_KIKAN_CD  CHAR(4) --「出金金融機関コード」
	,JDK_URAGKN_SIS_TNI_KBN  CHAR(1) NOT NULL --「自動機売上金精査単位区分」
	,SNT_JDK_URAGKN_SIS_TNI_NAIYO  VARCHAR2(30) --「その他自動機売上金精査単位内容」
	,JDK_URAGKN_MCHKM_HH_KBN  CHAR(1) NOT NULL --「自動機売上金持込方法区分」
	,SNT_JDK_URAGKN_MCHKM_HH_NAIYO  VARCHAR2(30) --「その他自動機売上金持込方法内容」
	,TSRSN_RYGEKN_HIKN_HSHK_KBN  CHAR(1) NOT NULL --「釣銭両替金配金方式区分」
	,SNT_TRSN_RGEKN_HIKN_HSK_NAIYO  VARCHAR2(30) --「その他釣銭両替金配金方式内容」
	,TSRSN_RYGEKN_KISH_HSHK_KBN  CHAR(1) NOT NULL --「釣銭両替金回収方式区分」
	,SNT_TRSN_RGEKN_SKN_HSK_NAIYO  VARCHAR2(30) --「その他釣銭両替金資金方式内容」
	,KEISO_TSUKA_BIKO  VARCHAR2(100) --「警送通貨備考」
	,KIS_TSK_KISH_JSSH_KNKK_KBN  CHAR(1) NOT NULL --「警送通貨回収実施間隔区分」
	,KIS_TSK_HIKN_JSSH_KNKK_KBN  CHAR(1) NOT NULL --「警送通貨配金実施間隔区分」
	,SHIYO_FUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「使用不可フラグ」
	,GYOMU_KAISHI_YOTEI_YMD  DATE --「業務開始予定年月日」
	,GYOMU_KAISHI_YMD  DATE --「業務開始年月日」
	,KEISO_TSUKA_UKWTSH_HOHO_KBN  CHAR(1) NOT NULL --「警送通貨受渡方法区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0698T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  UNYO_HENKO_RIREKI_NO
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0698T_TBL IS '運用警送通貨テーブル'
/

COMMENT ON COLUMN ED0698T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0698T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0698T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0698T_TBL.UNYO_HENKO_RIREKI_NO IS '運用変更履歴番号'
/
COMMENT ON COLUMN ED0698T_TBL.KEISO_KEIYAKU_YUSOHIN_JURYO_KG IS '警送契約輸送品重量キログラム'
/
COMMENT ON COLUMN ED0698T_TBL.KEISO_KEIYAKU_YUSOHIN_SURYO IS '警送契約輸送品数量'
/
COMMENT ON COLUMN ED0698T_TBL.UKWTSHY_KNK_SHYSK_KBN IS '受渡用金庫所有先区分'
/
COMMENT ON COLUMN ED0698T_TBL.SNT_UKWTSHY_KNK_SHYSK_NAIYO IS 'その他受渡用金庫所有先内容'
/
COMMENT ON COLUMN ED0698T_TBL.KEISO_BAG_JUMBISAKI_KBN IS '警送バック準備先区分'
/
COMMENT ON COLUMN ED0698T_TBL.SNT_KIS_BAG_JMBSK_NAIYO IS 'その他警送バック準備先内容'
/
COMMENT ON COLUMN ED0698T_TBL.UKWTSH_DMPY_JMBSK_KBN IS '受渡伝票準備先区分'
/
COMMENT ON COLUMN ED0698T_TBL.SNT_UKWTSH_DMPY_JMBSK_NAIYO IS 'その他受渡伝票準備先内容'
/
COMMENT ON COLUMN ED0698T_TBL.SNT_TSRSN_KF_HH_NAIYO IS 'その他釣銭交付方法内容'
/
COMMENT ON COLUMN ED0698T_TBL.CHINTAIHIN_KBN IS '賃貸品区分'
/
COMMENT ON COLUMN ED0698T_TBL.SONOTA_CHINTAIHIN_NAIYO IS 'その他賃貸品内容'
/
COMMENT ON COLUMN ED0698T_TBL.KOKYAKU_SHITEN_CD IS '顧客支店コード'
/
COMMENT ON COLUMN ED0698T_TBL.TAMMATSU_CD IS '端末コード'
/
COMMENT ON COLUMN ED0698T_TBL.SHIHEI_RYOKIN_TYPE_CD IS '警送紙幣料金タイプコード'
/
COMMENT ON COLUMN ED0698T_TBL.KOKA_RYOKIN_TYPE_CD IS '警送硬貨料金タイプコード'
/
COMMENT ON COLUMN ED0698T_TBL.GENKIN_KAISHU_TANI_KBN IS '現金回収単位区分'
/
COMMENT ON COLUMN ED0698T_TBL.SNT_GNKN_KISH_TNI_NAIYO IS 'その他現金回収単位内容'
/
COMMENT ON COLUMN ED0698T_TBL.GNKN_MCHKM_KNY_KKN_CD IS '現金持込金融機関コード'
/
COMMENT ON COLUMN ED0698T_TBL.GENKIN_MOCHIKOMI_D_KBN IS '現金持込日区分'
/
COMMENT ON COLUMN ED0698T_TBL.SNT_GNKN_MCHKM_D_STTI_NAIYO IS 'その他現金持込日設定内容'
/
COMMENT ON COLUMN ED0698T_TBL.HAIKIN_TANI_KBN IS '配金単位区分'
/
COMMENT ON COLUMN ED0698T_TBL.SONOTA_HAIKIN_TANI_NAIYO IS 'その他配金単位内容'
/
COMMENT ON COLUMN ED0698T_TBL.SHUKKIN_KINYU_KIKAN_CD IS '出金金融機関コード'
/
COMMENT ON COLUMN ED0698T_TBL.JDK_URAGKN_SIS_TNI_KBN IS '自動機売上金精査単位区分'
/
COMMENT ON COLUMN ED0698T_TBL.SNT_JDK_URAGKN_SIS_TNI_NAIYO IS 'その他自動機売上金精査単位内容'
/
COMMENT ON COLUMN ED0698T_TBL.JDK_URAGKN_MCHKM_HH_KBN IS '自動機売上金持込方法区分'
/
COMMENT ON COLUMN ED0698T_TBL.SNT_JDK_URAGKN_MCHKM_HH_NAIYO IS 'その他自動機売上金持込方法内容'
/
COMMENT ON COLUMN ED0698T_TBL.TSRSN_RYGEKN_HIKN_HSHK_KBN IS '釣銭両替金配金方式区分'
/
COMMENT ON COLUMN ED0698T_TBL.SNT_TRSN_RGEKN_HIKN_HSK_NAIYO IS 'その他釣銭両替金配金方式内容'
/
COMMENT ON COLUMN ED0698T_TBL.TSRSN_RYGEKN_KISH_HSHK_KBN IS '釣銭両替金回収方式区分'
/
COMMENT ON COLUMN ED0698T_TBL.SNT_TRSN_RGEKN_SKN_HSK_NAIYO IS 'その他釣銭両替金資金方式内容'
/
COMMENT ON COLUMN ED0698T_TBL.KEISO_TSUKA_BIKO IS '警送通貨備考'
/
COMMENT ON COLUMN ED0698T_TBL.KIS_TSK_KISH_JSSH_KNKK_KBN IS '警送通貨回収実施間隔区分'
/
COMMENT ON COLUMN ED0698T_TBL.KIS_TSK_HIKN_JSSH_KNKK_KBN IS '警送通貨配金実施間隔区分'
/
COMMENT ON COLUMN ED0698T_TBL.SHIYO_FUKA_FLG IS '使用不可フラグ'
/
COMMENT ON COLUMN ED0698T_TBL.GYOMU_KAISHI_YOTEI_YMD IS '業務開始予定年月日'
/
COMMENT ON COLUMN ED0698T_TBL.GYOMU_KAISHI_YMD IS '業務開始年月日'
/
COMMENT ON COLUMN ED0698T_TBL.KEISO_TSUKA_UKWTSH_HOHO_KBN IS '警送通貨受渡方法区分'
/
COMMENT ON COLUMN ED0698T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0698T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0698T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0698T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0698T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0698T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0698T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0698T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0698T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0698T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0698T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0698T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
