/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0727W_TBL.sql
-- 物理名：ED0727W_TBL
-- 論理名：売上配分事業所変換マスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0727W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0727W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,WK_KAISHA_NM  VARCHAR2(40) --「ワーク用会社名称」
	,KEISO_JISSHIJIGYOSHO_CD  CHAR(6) NOT NULL --「警送実施事業所コード」
	,WK_KEISO_JISSHI_JIGYOSHO_NM  VARCHAR2(200) --「ワーク用警送実施事業所名称」
	,SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,WK_SHOHIN_SERVICE_NM  VARCHAR2(60) --「ワーク用商品サービス名称」
	,JISSHI_JIGYOSHO_CD  CHAR(6) NOT NULL --「実施事業所コード」
	,WK_JISSI_JIGYOSYO_NM  VARCHAR2(200) --「ワーク用実施事業所名称」
	,JSSH_JGYSH_GYM_SHBTS_KBN  CHAR(2) NOT NULL --「実施事業所業務種別区分」
	,WK_JSSH_JGYS_GYM_SHBT_KBN_NM  VARCHAR2(60) --「ワーク用実施事業所業務種別区分名称」
	,URIAGE_HAIBUN_JIGYOSHO_CD  CHAR(6) NOT NULL --「売上配分事業所コード」
	,WK_URAG_HABN_JIGYOSHO_NM  VARCHAR2(200) --「ワーク用売上配分事業所名称」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE NOT NULL --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE NOT NULL --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) --「アップロードテーブルＩＤ」
	,TH_KAISHA_CD  CHAR(5) --「退避用会社コード」
	,TAIHIYO_KIS_JISSHIJIGYOSHO_CD  CHAR(6) --「退避用警送実施事業所コード」
	,TH_SHOHIN_SERVICE_CD  CHAR(3) --「退避用商品サービスコード」
	,TAIHIYO_JISSHI_JIGYOSHO_CD  CHAR(6) --「退避用実施事業所コード」
	,TH_JSSH_JGYSH_GYM_SHBTS_KBN  CHAR(2) NOT NULL --「退避用実施事業所業務種別区分」
	,TAIHIYO_URAG_HIBN_JIGYOSHO_CD  CHAR(6) --「退避用売上配分事業所コード」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0727W_PK PRIMARY KEY(
	 KEISO_JISSHIJIGYOSHO_CD
	,  SHOHIN_SERVICE_CD
	,  JISSHI_JIGYOSHO_CD
	,  JSSH_JGYSH_GYM_SHBTS_KBN
	,  URIAGE_HAIBUN_JIGYOSHO_CD
	,  KAISHA_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0727W_TBL IS '売上配分事業所変換マスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED0727W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED0727W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED0727W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0727W_TBL.WK_KAISHA_NM IS 'ワーク用会社名称'
/
COMMENT ON COLUMN ED0727W_TBL.KEISO_JISSHIJIGYOSHO_CD IS '警送実施事業所コード'
/
COMMENT ON COLUMN ED0727W_TBL.WK_KEISO_JISSHI_JIGYOSHO_NM IS 'ワーク用警送実施事業所名称'
/
COMMENT ON COLUMN ED0727W_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED0727W_TBL.WK_SHOHIN_SERVICE_NM IS 'ワーク用商品サービス名称'
/
COMMENT ON COLUMN ED0727W_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED0727W_TBL.WK_JISSI_JIGYOSYO_NM IS 'ワーク用実施事業所名称'
/
COMMENT ON COLUMN ED0727W_TBL.JSSH_JGYSH_GYM_SHBTS_KBN IS '実施事業所業務種別区分'
/
COMMENT ON COLUMN ED0727W_TBL.WK_JSSH_JGYS_GYM_SHBT_KBN_NM IS 'ワーク用実施事業所業務種別区分名称'
/
COMMENT ON COLUMN ED0727W_TBL.URIAGE_HAIBUN_JIGYOSHO_CD IS '売上配分事業所コード'
/
COMMENT ON COLUMN ED0727W_TBL.WK_URAG_HABN_JIGYOSHO_NM IS 'ワーク用売上配分事業所名称'
/
COMMENT ON COLUMN ED0727W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED0727W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED0727W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED0727W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED0727W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED0727W_TBL.TH_KAISHA_CD IS '退避用会社コード'
/
COMMENT ON COLUMN ED0727W_TBL.TAIHIYO_KIS_JISSHIJIGYOSHO_CD IS '退避用警送実施事業所コード'
/
COMMENT ON COLUMN ED0727W_TBL.TH_SHOHIN_SERVICE_CD IS '退避用商品サービスコード'
/
COMMENT ON COLUMN ED0727W_TBL.TAIHIYO_JISSHI_JIGYOSHO_CD IS '退避用実施事業所コード'
/
COMMENT ON COLUMN ED0727W_TBL.TH_JSSH_JGYSH_GYM_SHBTS_KBN IS '退避用実施事業所業務種別区分'
/
COMMENT ON COLUMN ED0727W_TBL.TAIHIYO_URAG_HIBN_JIGYOSHO_CD IS '退避用売上配分事業所コード'
/
COMMENT ON COLUMN ED0727W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED0727W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED0727W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED0727W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED0727W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED0727W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0727W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0727W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0727W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0727W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0727W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0727W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0727W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0727W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0727W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0727W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0727W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
