/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0701T_TBL.sql
-- 物理名：ED0701T_TBL
-- 論理名：契約提示価格売上テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0701T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0701T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIYAKU_ID  CHAR(18) NOT NULL --「契約ＩＤ」
	,TEIJI_KAKAKU_URIAGE_SN  CHAR(14) NOT NULL --「提示価格売上連番」
	,URIAGE_KEIJO_SHUBETSU_KBN  CHAR(2) NOT NULL --「売上計上種別区分」
	,URIAGE_GETSUGAKU_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上月額料金金額」
	,URIAGE_KIKI_TOSHI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上機器投資金額」
	,SONOTA_URIAGE_SHISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「その他売上指数」
	,URIAGE_KOJIHI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上工事費金額」
	,URIAGE_KOJI_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上工事原価金額」
	,URIAGE_KOJI_RIEKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上工事利益金額」
	,URIAGE_BAIKYAKUHI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上売却費金額」
	,URIAGE_BAIKYAKU_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上売却原価金額」
	,URIAGE_BAIKYAKU_RIEKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上売却利益金額」
	,URIAGE_UNYO_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上運用原価金額」
	,SONOTA_URIAGE_SHOKI_HIYO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「その他売上初期費用金額」
	,SONOTA_URIAGE_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「その他売上原価金額」
	,SONOTA_URIAGE_RIEKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「その他売上利益金額」
	,URIAGE_TOSHI_KAISHU_TSUKISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「売上投資回収月数」
	,URIAGE_KIKAN_URIAGE_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上期間売上金額」
	,URIAGE_KIKAN_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上期間原価金額」
	,URIAGE_KIKAN_RIEKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上期間利益金額」
	,URIAGE_SHOMI_KEIBI_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上正味警備料金金額」
	,URIAGE_HOSHOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上報奨金金額」
	,URIAGE_RIEKI_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売上利益率」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0701T_PK PRIMARY KEY(
	 KEIYAKU_ID
	,  TEIJI_KAKAKU_URIAGE_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0701T_TBL IS '契約提示価格売上テーブル'
/

COMMENT ON COLUMN ED0701T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0701T_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED0701T_TBL.TEIJI_KAKAKU_URIAGE_SN IS '提示価格売上連番'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_KEIJO_SHUBETSU_KBN IS '売上計上種別区分'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_GETSUGAKU_RYOKIN_AMT IS '売上月額料金金額'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_KIKI_TOSHI_AMT IS '売上機器投資金額'
/
COMMENT ON COLUMN ED0701T_TBL.SONOTA_URIAGE_SHISU IS 'その他売上指数'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_KOJIHI_AMT IS '売上工事費金額'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_KOJI_GENKA_AMT IS '売上工事原価金額'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_KOJI_RIEKI_AMT IS '売上工事利益金額'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_BAIKYAKUHI_AMT IS '売上売却費金額'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_BAIKYAKU_GENKA_AMT IS '売上売却原価金額'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_BAIKYAKU_RIEKI_AMT IS '売上売却利益金額'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_UNYO_GENKA_AMT IS '売上運用原価金額'
/
COMMENT ON COLUMN ED0701T_TBL.SONOTA_URIAGE_SHOKI_HIYO_AMT IS 'その他売上初期費用金額'
/
COMMENT ON COLUMN ED0701T_TBL.SONOTA_URIAGE_GENKA_AMT IS 'その他売上原価金額'
/
COMMENT ON COLUMN ED0701T_TBL.SONOTA_URIAGE_RIEKI_AMT IS 'その他売上利益金額'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_TOSHI_KAISHU_TSUKISU IS '売上投資回収月数'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_KIKAN_URIAGE_AMT IS '売上期間売上金額'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_KIKAN_GENKA_AMT IS '売上期間原価金額'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_KIKAN_RIEKI_AMT IS '売上期間利益金額'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_SHOMI_KEIBI_RYOKIN_AMT IS '売上正味警備料金金額'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_HOSHOKIN_AMT IS '売上報奨金金額'
/
COMMENT ON COLUMN ED0701T_TBL.URIAGE_RIEKI_RITSU IS '売上利益率'
/
COMMENT ON COLUMN ED0701T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0701T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0701T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0701T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0701T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0701T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0701T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0701T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0701T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0701T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0701T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0701T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
