/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0703M_TBL.sql
-- 物理名：ED0703M_TBL
-- 論理名：契約汎用区分マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0703M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0703M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIYAKU_HANYO_KBN_CD  CHAR(4) NOT NULL --「契約汎用区分コード」
	,KEIYAKU_HANYO_KBN_CD_BN  CHAR(4) NOT NULL --「契約汎用区分コード枝番」
	,KEIYAKU_HANYO_KBN_NM  VARCHAR2(60) --「契約汎用区分名称」
	,KY_HY_KBN_SHBRKM_JKN_NAIYO_1  VARCHAR2(20) --「契約汎用区分絞込条件内容１」
	,KY_HY_KBN_SHBRKM_JKN_NAIYO_2  VARCHAR2(20) --「契約汎用区分絞込条件内容２」
	,KY_HY_KBN_SHBRKM_JKN_NAIYO_3  VARCHAR2(20) --「契約汎用区分絞込条件内容３」
	,KY_HY_KBN_SHBRKM_JKN_NAIYO_4  VARCHAR2(20) --「契約汎用区分絞込条件内容４」
	,KY_HY_KBN_SHBRKM_JKN_NAIYO_5  VARCHAR2(20) --「契約汎用区分絞込条件内容５」
	,KY_HY_KBN_SHBRKM_JKN_NM_1  VARCHAR2(60) --「契約汎用区分絞込条件名称１」
	,KY_HY_KBN_SHBRKM_JKN_NM_2  VARCHAR2(60) --「契約汎用区分絞込条件名称２」
	,KY_HY_KBN_SHBRKM_JKN_NM_3  VARCHAR2(60) --「契約汎用区分絞込条件名称３」
	,KY_HY_KBN_SHBRKM_JKN_NM_4  VARCHAR2(60) --「契約汎用区分絞込条件名称４」
	,KY_HY_KBN_SHBRKM_JKN_NM_5  VARCHAR2(60) --「契約汎用区分絞込条件名称５」
	,KY_HY_KBN_SETTEI_NAIYO_1  VARCHAR2(100) --「契約汎用区分設定内容１」
	,KY_HY_KBN_SETTEI_NAIYO_2  VARCHAR2(100) --「契約汎用区分設定内容２」
	,KY_HY_KBN_SETTEI_NAIYO_3  VARCHAR2(100) --「契約汎用区分設定内容３」
	,KY_HY_KBN_SETTEI_NAIYO_4  VARCHAR2(100) --「契約汎用区分設定内容４」
	,KY_HY_KBN_SETTEI_NAIYO_5  VARCHAR2(100) --「契約汎用区分設定内容５」
	,KY_HY_KBN_STTI_NAIYO_STMI_JIKO  VARCHAR2(200) --「契約汎用区分設定内容説明事項」
	,KY_HY_KBN_BIKO  VARCHAR2(100) --「契約汎用区分備考」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0703M_PK PRIMARY KEY(
	 KEIYAKU_HANYO_KBN_CD
	,  KEIYAKU_HANYO_KBN_CD_BN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0703M_TBL IS '契約汎用区分マスタ'
/

COMMENT ON COLUMN ED0703M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0703M_TBL.KEIYAKU_HANYO_KBN_CD IS '契約汎用区分コード'
/
COMMENT ON COLUMN ED0703M_TBL.KEIYAKU_HANYO_KBN_CD_BN IS '契約汎用区分コード枝番'
/
COMMENT ON COLUMN ED0703M_TBL.KEIYAKU_HANYO_KBN_NM IS '契約汎用区分名称'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SHBRKM_JKN_NAIYO_1 IS '契約汎用区分絞込条件内容１'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SHBRKM_JKN_NAIYO_2 IS '契約汎用区分絞込条件内容２'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SHBRKM_JKN_NAIYO_3 IS '契約汎用区分絞込条件内容３'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SHBRKM_JKN_NAIYO_4 IS '契約汎用区分絞込条件内容４'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SHBRKM_JKN_NAIYO_5 IS '契約汎用区分絞込条件内容５'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SHBRKM_JKN_NM_1 IS '契約汎用区分絞込条件名称１'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SHBRKM_JKN_NM_2 IS '契約汎用区分絞込条件名称２'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SHBRKM_JKN_NM_3 IS '契約汎用区分絞込条件名称３'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SHBRKM_JKN_NM_4 IS '契約汎用区分絞込条件名称４'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SHBRKM_JKN_NM_5 IS '契約汎用区分絞込条件名称５'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SETTEI_NAIYO_1 IS '契約汎用区分設定内容１'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SETTEI_NAIYO_2 IS '契約汎用区分設定内容２'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SETTEI_NAIYO_3 IS '契約汎用区分設定内容３'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SETTEI_NAIYO_4 IS '契約汎用区分設定内容４'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_SETTEI_NAIYO_5 IS '契約汎用区分設定内容５'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_STTI_NAIYO_STMI_JIKO IS '契約汎用区分設定内容説明事項'
/
COMMENT ON COLUMN ED0703M_TBL.KY_HY_KBN_BIKO IS '契約汎用区分備考'
/
COMMENT ON COLUMN ED0703M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0703M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0703M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0703M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0703M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0703M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0703M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0703M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0703M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0703M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0703M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0703M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
