/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0719W_TBL.sql
-- 物理名：ED0719W_TBL
-- 論理名：警備系＿営業送信＿入出金機情報ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0719W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0719W_TBL (
	 KBK_SOSHIN_SHKBTS_KEY  CHAR(9) NOT NULL --「ＫＢＫ＿送信識別キー」
	,KBK_SOSHIN_SHKBTS_SN  CHAR(10) NOT NULL --「ＫＢＫ＿送信識別連番」
	,KBK_SOSHIN_SHKBTS_MEISAI_SN  CHAR(10) NOT NULL --「ＫＢＫ＿明細連番」
	,KBK_NYUSHUKKINKI_NO  VARCHAR2(6) --「ＫＢＫ＿入出金機端末番号」
	,KBK_NYUSHUKKINKI_SHUBETSU  VARCHAR2(30) --「ＫＢＫ＿入出金機機種種別」
	,KBK_NYUSHUKKINKI_SHURUI  VARCHAR2(30) --「ＫＢＫ＿入出金機機種種類」
	,KBK_CHUKO_NYUSHUKKINKI_NO  VARCHAR2(6) --「ＫＢＫ＿中古入出金機番号」
	,KBK_NYSHKKNK_SHD_SHM_PRINT  CHAR(1) DEFAULT '0' NOT NULL --「ＫＢＫ＿締めプリント」
	,KBK_NYSHKKNK_SHD_SHM_PRI_SAI  CHAR(1) DEFAULT '0' NOT NULL --「ＫＢＫ＿締めプリント再印字」
	,KBK_NYSHKKNK_JD_SHM  CHAR(1) DEFAULT '0' NOT NULL --「ＫＢＫ＿自動締め」
	,KBK_NYUSHUKKINKI_JIDO_SHIME_TM  CHAR(4) --「ＫＢＫ＿自動締め時間」
	,KBK_NYSHKKNK_JD_SHM_PRINT  CHAR(1) DEFAULT '0' NOT NULL --「ＫＢＫ＿自動締めプリント」
	,KBK_NSKKNK_SM_REGI_BT  CHAR(1) DEFAULT '0' NOT NULL --「ＫＢＫ＿締めレジ別印字」
	,KBK_KAISEN_SHUBETSU  VARCHAR2(60) --「ＫＢＫ＿主回線種別」
	,KBK_MAIN_KAISEN_IP_ADDRESS  VARCHAR2(40) --「ＫＢＫ＿メイン回線ＩＰアドレス」
	,KBK_YOBI_KOMOKU_01  VARCHAR2(255) --「ＫＢＫ＿予備項目０１」
	,KBK_YOBI_KOMOKU_02  VARCHAR2(255) --「ＫＢＫ＿予備項目０２」
	,KBK_YOBI_KOMOKU_03  VARCHAR2(255) --「ＫＢＫ＿予備項目０３」
	,KBK_YOBI_KOMOKU_04  VARCHAR2(255) --「ＫＢＫ＿予備項目０４」
	,KBK_YOBI_KOMOKU_05  VARCHAR2(255) --「ＫＢＫ＿予備項目０５」
	,KBK_YOBI_KOMOKU_06  VARCHAR2(255) --「ＫＢＫ＿予備項目０６」
	,KBK_YOBI_KOMOKU_07  VARCHAR2(255) --「ＫＢＫ＿予備項目０７」
	,KBK_YOBI_KOMOKU_08  VARCHAR2(255) --「ＫＢＫ＿予備項目０８」
	,KBK_YOBI_KOMOKU_09  VARCHAR2(255) --「ＫＢＫ＿予備項目０９」
	,KBK_YOBI_KOMOKU_10  VARCHAR2(255) --「ＫＢＫ＿予備項目１０」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0719W_PK PRIMARY KEY(
	 KBK_SOSHIN_SHKBTS_KEY
	,  KBK_SOSHIN_SHKBTS_SN
	,  KBK_SOSHIN_SHKBTS_MEISAI_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0719W_TBL IS '警備系＿営業送信＿入出金機情報ワーク'
/

COMMENT ON COLUMN ED0719W_TBL.KBK_SOSHIN_SHKBTS_KEY IS 'ＫＢＫ＿送信識別キー'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_SOSHIN_SHKBTS_SN IS 'ＫＢＫ＿送信識別連番'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_SOSHIN_SHKBTS_MEISAI_SN IS 'ＫＢＫ＿明細連番'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_NYUSHUKKINKI_NO IS 'ＫＢＫ＿入出金機端末番号'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_NYUSHUKKINKI_SHUBETSU IS 'ＫＢＫ＿入出金機機種種別'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_NYUSHUKKINKI_SHURUI IS 'ＫＢＫ＿入出金機機種種類'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_CHUKO_NYUSHUKKINKI_NO IS 'ＫＢＫ＿中古入出金機番号'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_NYSHKKNK_SHD_SHM_PRINT IS 'ＫＢＫ＿締めプリント'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_NYSHKKNK_SHD_SHM_PRI_SAI IS 'ＫＢＫ＿締めプリント再印字'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_NYSHKKNK_JD_SHM IS 'ＫＢＫ＿自動締め'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_NYUSHUKKINKI_JIDO_SHIME_TM IS 'ＫＢＫ＿自動締め時間'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_NYSHKKNK_JD_SHM_PRINT IS 'ＫＢＫ＿自動締めプリント'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_NSKKNK_SM_REGI_BT IS 'ＫＢＫ＿締めレジ別印字'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_KAISEN_SHUBETSU IS 'ＫＢＫ＿主回線種別'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_MAIN_KAISEN_IP_ADDRESS IS 'ＫＢＫ＿メイン回線ＩＰアドレス'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_YOBI_KOMOKU_01 IS 'ＫＢＫ＿予備項目０１'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_YOBI_KOMOKU_02 IS 'ＫＢＫ＿予備項目０２'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_YOBI_KOMOKU_03 IS 'ＫＢＫ＿予備項目０３'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_YOBI_KOMOKU_04 IS 'ＫＢＫ＿予備項目０４'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_YOBI_KOMOKU_05 IS 'ＫＢＫ＿予備項目０５'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_YOBI_KOMOKU_06 IS 'ＫＢＫ＿予備項目０６'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_YOBI_KOMOKU_07 IS 'ＫＢＫ＿予備項目０７'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_YOBI_KOMOKU_08 IS 'ＫＢＫ＿予備項目０８'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_YOBI_KOMOKU_09 IS 'ＫＢＫ＿予備項目０９'
/
COMMENT ON COLUMN ED0719W_TBL.KBK_YOBI_KOMOKU_10 IS 'ＫＢＫ＿予備項目１０'
/
COMMENT ON COLUMN ED0719W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0719W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0719W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0719W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0719W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0719W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0719W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0719W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0719W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0719W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0719W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0719W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
