/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1035M_TBL.sql
-- 物理名：ED1035M_TBL
-- 論理名：工事従業員マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1035M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1035M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KJ_KYRYK_KISH_TRHKSK_CD  CHAR(9) NOT NULL --「工事協力会社取引先コード」
	,KOJI_TORIHIKISAKI_BUSHO_CD  CHAR(4) NOT NULL --「工事取引先部署コード」
	,KOJI_JUJISHA_NO  CHAR(8) NOT NULL --「工事従事者番号」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,KANRISHA_TAISHO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「管理者対象フラグ」
	,HANCHO_TAISHO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「班長対象フラグ」
	,KJ_KYRYK_KISH_JGYIN_TRK_KBN  CHAR(1) NOT NULL --「工事協力会社従業員登録区分」
	,KOJI_BLOCK_CD  CHAR(3) --「工事ブロックコード」
	,JUJISHASHO_NO  CHAR(10) --「従事者証番号」
	,KJ_KYRYK_KISH_TNTSI_KN_NM  VARCHAR2(45) --「工事協力会社担当姓カナ氏名」
	,KJ_KYRYK_KISH_TNTMI_KN_NM  VARCHAR2(45) --「工事協力会社担当名カナ氏名」
	,KJ_KYRYK_KISH_TNTSI_NM  VARCHAR2(30) --「工事協力会社担当姓氏名」
	,KJ_KYRYK_KISH_TNTMI_NM  VARCHAR2(30) --「工事協力会社担当名氏名」
	,SEI_YMD  DATE --「生年月日」
	,SEIBETSU_KBN  CHAR(1) NOT NULL --「性別区分」
	,KETSUEKIGATA_KBN  CHAR(1) NOT NULL --「血液型区分」
	,KOJI_JUJISHA_ALSOK_TOROKU_YMD  DATE --「工事従事者ＡＬＳＯＫ登録年月日」
	,HAKKO_YMD  DATE --「発行年月日」
	,KOJI_JUJISHA_YUKO_KIGEN_YMD  DATE --「工事従事者有効期限年月日」
	,SHTUK_KISH_TRHKSK_CD  CHAR(9) --「下請会社取引先コード」
	,KJKRKS_JGIJS_CD  CHAR(11) --「工事協力会社従業員住所コード」
	,KJKRKS_JGIJS_HOSOKU_NAIYO  VARCHAR2(100) --「工事協力会社従業員住所補足内容」
	,KJ_KYRYK_KISH_JGYIN_DNW_NO  VARCHAR2(20) --「工事協力会社従業員電話番号」
	,KJ_KYRYK_KISH_JGYIN_KITI_NO  VARCHAR2(20) --「工事協力会社従業員携帯番号」
	,GS_KOJI_SHIKAKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＧＳ工事資格有フラグ」
	,HS_KOJI_SHIKAKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＨＳ工事資格有フラグ」
	,SONOTA_SHIKAKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「その他資格有フラグ」
	,ALMOND_KOJI_SHIKAKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「アマンド工事資格有フラグ」
	,SHK_KNR_GSH_1_KY_SHKK_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「施行管理技師１級資格対象フラグ」
	,SHK_KNR_GSH_2_KY_SHKK_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「施行管理技師２級資格対象フラグ」
	,DNK_KJSH_1_SH_SHKK_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「電気工事士１種資格対象フラグ」
	,DNK_KJSH_2_SH_SHKK_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「電気工事士２種資格対象フラグ」
	,ANALOG_DIGITAL_SGS_SKK_TIS_FLG  CHAR(1) DEFAULT '0' NOT NULL --「アナログデジタル総合種資格対象フラグ」
	,ANALOG_1_SH_SHKK_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「アナログ１種資格対象フラグ」
	,ANALOG_2_SH_SHKK_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「アナログ２種資格対象フラグ」
	,ANALOG_3_SH_SHKK_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「アナログ３種資格対象フラグ」
	,DIGITAL_1_SH_SHKK_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「デジタル１種資格対象フラグ」
	,DIGITAL_2_SH_SHKK_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「デジタル２種資格対象フラグ」
	,DIGITAL_3_SH_SHKK_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「デジタル３種資格対象フラグ」
	,DNK_SHNN_GJTSSH_SHKK_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「電気主任技術者資格対象フラグ」
	,KAT_DNK_KJ_GJTS_SKK_TIS_FLG  CHAR(1) DEFAULT '0' NOT NULL --「高圧電気工事技術者資格対象フラグ」
	,SHB_STSBSH_SHKK_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「消防設備士資格対象フラグ」
	,DNK_KJSH_1_SH_YK_KGN_YMD  DATE --「電気工事士１種有効期限年月日」
	,DNK_KJSH_2_SH_YK_KGN_YMD  DATE --「電気工事士２種有効期限年月日」
	,KANRYO_KENSA_NINTEI_NAIYO  VARCHAR2(100) --「完了検査認定内容」
	,KANRYO_KENSA_NINTEI_YMD  DATE --「完了検査認定年月日」
	,SHOKUCHO_KYOIKU_JUKO_YMD  DATE --「職長教育受講年月日」
	,ALMOND_KOJI_KEIKENARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「アマンド工事経験有フラグ」
	,ATM_NIB_TMMTS_KJ_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＴＭ内部端末工事経験有フラグ」
	,S_859_TENANT_KJ_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「Ｓ８５９テナント工事経験有フラグ」
	,GTACS_KOJI_KEIKENARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＧＴＡＣＳ工事経験有フラグ」
	,MANSION_TACKLES_KJ_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「マンションタクルス工事経験有フラグ」
	,NYUKINKI_KOJI_KEIKENARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「入金機工事経験有フラグ」
	,LEOPALACE_HS_KJ_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「レオパレスＨＳ工事経験有フラグ」
	,DROOM_HS_KOJI_KEIKENARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ｄｒｏｏｍＨＳ工事経験有フラグ」
	,KS_HOUSE_MAKER_TRJK_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「各種ハウスメーカー登録状況経験有フラグ」
	,SEVEN_BKSEJI_KJ_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「セブンＢＫＳＥＪＩ工事経験有フラグ」
	,SHNCHK_HS_YSN_KJ_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「新築ＨＳ有線工事経験有フラグ」
	,OLM_YUSEN_KOJI_KEIKENARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＯＬＭ有線工事経験有フラグ」
	,BBK_YSN_KJ_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「防爆有線工事経験有フラグ」
	,CAMERA_POLE_KCD_YSKJ_KKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「カメラ用ポール建柱大有線工事経験有フラグ」
	,COMBI_POLE_CKC_YSKJ_KKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「コンビネーション用ポール中建柱有線工事経験有フラグ」
	,HKR_CABLE_YCYSKJ_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「光ケーブル融着有線工事経験有フラグ」
	,GISN_YSN_KJ_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「外線有線工事経験有フラグ」
	,HSKJYS_USK_DNSNKN_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「配線工事有線薄鋼電線管経験有フラグ」
	,HSKJYS_OKGI_PF_KNT_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「配線工事有線屋外ＰＦ管等経験有フラグ」
	,KSH_SGYSH_KSH_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「高所作業車講習経験有フラグ」
	,TNKNK_SKSI_YSN_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「点検口作成有線経験有フラグ」
	,ARMOR_SHIELD_SK_YSN_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「アーマーシールド施工有線経験有フラグ」
	,BNDMBN_STCH_YSN_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「分電盤設置有線経験有フラグ」
	,ELV_NAI_HSKJYS_KEIKENARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＥＬＶ内配線工事有線経験有フラグ」
	,SKKKSG_SHNNSH_YSN_KIKNAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「酸欠危険作業主任者有線経験有フラグ」
	,YOBI_KEIKENARI_FLG_1  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ１」
	,YOBI_KEIKENARI_FLG_2  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ２」
	,YOBI_KEIKENARI_FLG_3  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ３」
	,YOBI_KEIKENARI_FLG_4  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ４」
	,YOBI_KEIKENARI_FLG_5  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ５」
	,YOBI_KEIKENARI_FLG_6  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ６」
	,YOBI_KEIKENARI_FLG_7  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ７」
	,YOBI_KEIKENARI_FLG_8  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ８」
	,YOBI_KEIKENARI_FLG_9  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ９」
	,YOBI_KEIKENARI_FLG_10  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ１０」
	,YOBI_KEIKENARI_FLG_11  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ１１」
	,YOBI_KEIKENARI_FLG_12  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ１２」
	,YOBI_KEIKENARI_FLG_13  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ１３」
	,YOBI_KEIKENARI_FLG_14  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ１４」
	,YOBI_KEIKENARI_FLG_15  CHAR(1) DEFAULT '0' NOT NULL --「予備経験有フラグ１５」
	,KOJI_JUGYOIN_BIKO  VARCHAR2(100) --「工事従業員備考」
	,KENKO_SHINDAN_JISSHI_YMD  DATE --「健康診断実施年月日」
	,JUJISHA_SAIKO_BP  NUMBER(9,0) DEFAULT '0' NOT NULL --「従事者最高血圧」
	,JUJISHA_SAITEI_BP  NUMBER(9,0) DEFAULT '0' NOT NULL --「従事者最低血圧」
	,TAISHOKU_YOTEI_YMD  DATE --「退職予定年月日」
	,HENKYAKU_YMD  DATE --「返却年月日」
	,HAIKI_YMD  DATE --「廃棄年月日」
	,KOJI_JUJISHA_TOROKU_KAIJO_RIYU  VARCHAR2(100) --「工事従事者登録解除理由」
	,KENKO_HOKEN_NAIYO  VARCHAR2(20) --「健康保険内容」
	,KOSEI_NENKIN_HOKEN_NAIYO  VARCHAR2(20) --「厚生年金保険内容」
	,RODO_HOKEN_NAIYO  VARCHAR2(20) --「労働保険内容」
	,KOYO_HOKEN_NAIYO  VARCHAR2(20) --「雇用保険内容」
	,ROSAI_HOKEN_NAIYO  VARCHAR2(20) --「労災保険内容」
	,TOKUBETSU_KANYU_KBN  CHAR(1) NOT NULL --「特別加入区分」
	,KINKYU_RENRAKUSAKI_NM  VARCHAR2(60) --「緊急連絡先氏名」
	,KNKY_RNRKSK_ZKGR_NAIYO  VARCHAR2(10) --「緊急連絡先続柄内容」
	,KINKYU_RENRAKUSAKI_JUSHO_CD  CHAR(11) --「緊急連絡先住所コード」
	,KNKY_RNRKSK_JUSHO_HSK_NAIYO  VARCHAR2(100) --「緊急連絡先住所補足内容」
	,KNKY_RNRKSK_DIICH_DNW_NO  VARCHAR2(20) --「緊急連絡先第一電話番号」
	,KNKY_RNRKSK_DIN_DNW_NO  VARCHAR2(20) --「緊急連絡先第二電話番号」
	,KJ_JJS_TRK_KOJSN_FILE_SKBT_KEY  VARCHAR2(255) --「工事従事者登録顔写真ファイル識別キー」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,KOJI_JUJISHA_TOROKU_JOTAI_KBN  CHAR(1) NOT NULL --「工事従事者登録状態区分」
	,SHTUK_KISH_TRHKSK_NM  VARCHAR2(40) --「下請会社取引先名称」
	,KOJI_JUJISHA_JIGYONUSHI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事従事者事業主フラグ」
	,KOJI_JUJISHA_SAGYOIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事従事者作業員フラグ」
	,KOJI_JUJISHA_KAOJASHIN_FILE_NM  VARCHAR2(255) --「工事従事者顔写真ファイル名称」
	,KOJI_SHIRYO_BUNRUI_KBN  CHAR(1) NOT NULL --「工事資料分類区分」
	,SHAGAI_RIYOSHA_NO  CHAR(8) --「社外利用者番号」
	,SHGI_RYSH_TRK_STATUS_KBN  CHAR(1) NOT NULL --「社外利用者登録ステータス区分」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1035M_PK PRIMARY KEY(
	 KJ_KYRYK_KISH_TRHKSK_CD
	,  KOJI_TORIHIKISAKI_BUSHO_CD
	,  KOJI_JUJISHA_NO
	,  KAISHA_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1035M_TBL IS '工事従業員マスタ'
/

COMMENT ON COLUMN ED1035M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1035M_TBL.KJ_KYRYK_KISH_TRHKSK_CD IS '工事協力会社取引先コード'
/
COMMENT ON COLUMN ED1035M_TBL.KOJI_TORIHIKISAKI_BUSHO_CD IS '工事取引先部署コード'
/
COMMENT ON COLUMN ED1035M_TBL.KOJI_JUJISHA_NO IS '工事従事者番号'
/
COMMENT ON COLUMN ED1035M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED1035M_TBL.KANRISHA_TAISHO_FLG IS '管理者対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.HANCHO_TAISHO_FLG IS '班長対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.KJ_KYRYK_KISH_JGYIN_TRK_KBN IS '工事協力会社従業員登録区分'
/
COMMENT ON COLUMN ED1035M_TBL.KOJI_BLOCK_CD IS '工事ブロックコード'
/
COMMENT ON COLUMN ED1035M_TBL.JUJISHASHO_NO IS '従事者証番号'
/
COMMENT ON COLUMN ED1035M_TBL.KJ_KYRYK_KISH_TNTSI_KN_NM IS '工事協力会社担当姓カナ氏名'
/
COMMENT ON COLUMN ED1035M_TBL.KJ_KYRYK_KISH_TNTMI_KN_NM IS '工事協力会社担当名カナ氏名'
/
COMMENT ON COLUMN ED1035M_TBL.KJ_KYRYK_KISH_TNTSI_NM IS '工事協力会社担当姓氏名'
/
COMMENT ON COLUMN ED1035M_TBL.KJ_KYRYK_KISH_TNTMI_NM IS '工事協力会社担当名氏名'
/
COMMENT ON COLUMN ED1035M_TBL.SEI_YMD IS '生年月日'
/
COMMENT ON COLUMN ED1035M_TBL.SEIBETSU_KBN IS '性別区分'
/
COMMENT ON COLUMN ED1035M_TBL.KETSUEKIGATA_KBN IS '血液型区分'
/
COMMENT ON COLUMN ED1035M_TBL.KOJI_JUJISHA_ALSOK_TOROKU_YMD IS '工事従事者ＡＬＳＯＫ登録年月日'
/
COMMENT ON COLUMN ED1035M_TBL.HAKKO_YMD IS '発行年月日'
/
COMMENT ON COLUMN ED1035M_TBL.KOJI_JUJISHA_YUKO_KIGEN_YMD IS '工事従事者有効期限年月日'
/
COMMENT ON COLUMN ED1035M_TBL.SHTUK_KISH_TRHKSK_CD IS '下請会社取引先コード'
/
COMMENT ON COLUMN ED1035M_TBL.KJKRKS_JGIJS_CD IS '工事協力会社従業員住所コード'
/
COMMENT ON COLUMN ED1035M_TBL.KJKRKS_JGIJS_HOSOKU_NAIYO IS '工事協力会社従業員住所補足内容'
/
COMMENT ON COLUMN ED1035M_TBL.KJ_KYRYK_KISH_JGYIN_DNW_NO IS '工事協力会社従業員電話番号'
/
COMMENT ON COLUMN ED1035M_TBL.KJ_KYRYK_KISH_JGYIN_KITI_NO IS '工事協力会社従業員携帯番号'
/
COMMENT ON COLUMN ED1035M_TBL.GS_KOJI_SHIKAKUARI_FLG IS 'ＧＳ工事資格有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.HS_KOJI_SHIKAKUARI_FLG IS 'ＨＳ工事資格有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.SONOTA_SHIKAKUARI_FLG IS 'その他資格有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.ALMOND_KOJI_SHIKAKUARI_FLG IS 'アマンド工事資格有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.SHK_KNR_GSH_1_KY_SHKK_TISH_FLG IS '施行管理技師１級資格対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.SHK_KNR_GSH_2_KY_SHKK_TISH_FLG IS '施行管理技師２級資格対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.DNK_KJSH_1_SH_SHKK_TISH_FLG IS '電気工事士１種資格対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.DNK_KJSH_2_SH_SHKK_TISH_FLG IS '電気工事士２種資格対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.ANALOG_DIGITAL_SGS_SKK_TIS_FLG IS 'アナログデジタル総合種資格対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.ANALOG_1_SH_SHKK_TISH_FLG IS 'アナログ１種資格対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.ANALOG_2_SH_SHKK_TISH_FLG IS 'アナログ２種資格対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.ANALOG_3_SH_SHKK_TISH_FLG IS 'アナログ３種資格対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.DIGITAL_1_SH_SHKK_TISH_FLG IS 'デジタル１種資格対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.DIGITAL_2_SH_SHKK_TISH_FLG IS 'デジタル２種資格対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.DIGITAL_3_SH_SHKK_TISH_FLG IS 'デジタル３種資格対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.DNK_SHNN_GJTSSH_SHKK_TISH_FLG IS '電気主任技術者資格対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.KAT_DNK_KJ_GJTS_SKK_TIS_FLG IS '高圧電気工事技術者資格対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.SHB_STSBSH_SHKK_TISH_FLG IS '消防設備士資格対象フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.DNK_KJSH_1_SH_YK_KGN_YMD IS '電気工事士１種有効期限年月日'
/
COMMENT ON COLUMN ED1035M_TBL.DNK_KJSH_2_SH_YK_KGN_YMD IS '電気工事士２種有効期限年月日'
/
COMMENT ON COLUMN ED1035M_TBL.KANRYO_KENSA_NINTEI_NAIYO IS '完了検査認定内容'
/
COMMENT ON COLUMN ED1035M_TBL.KANRYO_KENSA_NINTEI_YMD IS '完了検査認定年月日'
/
COMMENT ON COLUMN ED1035M_TBL.SHOKUCHO_KYOIKU_JUKO_YMD IS '職長教育受講年月日'
/
COMMENT ON COLUMN ED1035M_TBL.ALMOND_KOJI_KEIKENARI_FLG IS 'アマンド工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.ATM_NIB_TMMTS_KJ_KIKNAR_FLG IS 'ＡＴＭ内部端末工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.S_859_TENANT_KJ_KIKNAR_FLG IS 'Ｓ８５９テナント工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.GTACS_KOJI_KEIKENARI_FLG IS 'ＧＴＡＣＳ工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.MANSION_TACKLES_KJ_KIKNAR_FLG IS 'マンションタクルス工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.NYUKINKI_KOJI_KEIKENARI_FLG IS '入金機工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.LEOPALACE_HS_KJ_KIKNAR_FLG IS 'レオパレスＨＳ工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.DROOM_HS_KOJI_KEIKENARI_FLG IS 'ｄｒｏｏｍＨＳ工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.KS_HOUSE_MAKER_TRJK_KIKNAR_FLG IS '各種ハウスメーカー登録状況経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.SEVEN_BKSEJI_KJ_KIKNAR_FLG IS 'セブンＢＫＳＥＪＩ工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.SHNCHK_HS_YSN_KJ_KIKNAR_FLG IS '新築ＨＳ有線工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.OLM_YUSEN_KOJI_KEIKENARI_FLG IS 'ＯＬＭ有線工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.BBK_YSN_KJ_KIKNAR_FLG IS '防爆有線工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.CAMERA_POLE_KCD_YSKJ_KKA_FLG IS 'カメラ用ポール建柱大有線工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.COMBI_POLE_CKC_YSKJ_KKA_FLG IS 'コンビネーション用ポール中建柱有線工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.HKR_CABLE_YCYSKJ_KIKNAR_FLG IS '光ケーブル融着有線工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.GISN_YSN_KJ_KIKNAR_FLG IS '外線有線工事経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.HSKJYS_USK_DNSNKN_KIKNAR_FLG IS '配線工事有線薄鋼電線管経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.HSKJYS_OKGI_PF_KNT_KIKNAR_FLG IS '配線工事有線屋外ＰＦ管等経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.KSH_SGYSH_KSH_KIKNAR_FLG IS '高所作業車講習経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.TNKNK_SKSI_YSN_KIKNAR_FLG IS '点検口作成有線経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.ARMOR_SHIELD_SK_YSN_KIKNAR_FLG IS 'アーマーシールド施工有線経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.BNDMBN_STCH_YSN_KIKNAR_FLG IS '分電盤設置有線経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.ELV_NAI_HSKJYS_KEIKENARI_FLG IS 'ＥＬＶ内配線工事有線経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.SKKKSG_SHNNSH_YSN_KIKNAR_FLG IS '酸欠危険作業主任者有線経験有フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_1 IS '予備経験有フラグ１'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_2 IS '予備経験有フラグ２'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_3 IS '予備経験有フラグ３'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_4 IS '予備経験有フラグ４'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_5 IS '予備経験有フラグ５'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_6 IS '予備経験有フラグ６'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_7 IS '予備経験有フラグ７'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_8 IS '予備経験有フラグ８'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_9 IS '予備経験有フラグ９'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_10 IS '予備経験有フラグ１０'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_11 IS '予備経験有フラグ１１'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_12 IS '予備経験有フラグ１２'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_13 IS '予備経験有フラグ１３'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_14 IS '予備経験有フラグ１４'
/
COMMENT ON COLUMN ED1035M_TBL.YOBI_KEIKENARI_FLG_15 IS '予備経験有フラグ１５'
/
COMMENT ON COLUMN ED1035M_TBL.KOJI_JUGYOIN_BIKO IS '工事従業員備考'
/
COMMENT ON COLUMN ED1035M_TBL.KENKO_SHINDAN_JISSHI_YMD IS '健康診断実施年月日'
/
COMMENT ON COLUMN ED1035M_TBL.JUJISHA_SAIKO_BP IS '従事者最高血圧'
/
COMMENT ON COLUMN ED1035M_TBL.JUJISHA_SAITEI_BP IS '従事者最低血圧'
/
COMMENT ON COLUMN ED1035M_TBL.TAISHOKU_YOTEI_YMD IS '退職予定年月日'
/
COMMENT ON COLUMN ED1035M_TBL.HENKYAKU_YMD IS '返却年月日'
/
COMMENT ON COLUMN ED1035M_TBL.HAIKI_YMD IS '廃棄年月日'
/
COMMENT ON COLUMN ED1035M_TBL.KOJI_JUJISHA_TOROKU_KAIJO_RIYU IS '工事従事者登録解除理由'
/
COMMENT ON COLUMN ED1035M_TBL.KENKO_HOKEN_NAIYO IS '健康保険内容'
/
COMMENT ON COLUMN ED1035M_TBL.KOSEI_NENKIN_HOKEN_NAIYO IS '厚生年金保険内容'
/
COMMENT ON COLUMN ED1035M_TBL.RODO_HOKEN_NAIYO IS '労働保険内容'
/
COMMENT ON COLUMN ED1035M_TBL.KOYO_HOKEN_NAIYO IS '雇用保険内容'
/
COMMENT ON COLUMN ED1035M_TBL.ROSAI_HOKEN_NAIYO IS '労災保険内容'
/
COMMENT ON COLUMN ED1035M_TBL.TOKUBETSU_KANYU_KBN IS '特別加入区分'
/
COMMENT ON COLUMN ED1035M_TBL.KINKYU_RENRAKUSAKI_NM IS '緊急連絡先氏名'
/
COMMENT ON COLUMN ED1035M_TBL.KNKY_RNRKSK_ZKGR_NAIYO IS '緊急連絡先続柄内容'
/
COMMENT ON COLUMN ED1035M_TBL.KINKYU_RENRAKUSAKI_JUSHO_CD IS '緊急連絡先住所コード'
/
COMMENT ON COLUMN ED1035M_TBL.KNKY_RNRKSK_JUSHO_HSK_NAIYO IS '緊急連絡先住所補足内容'
/
COMMENT ON COLUMN ED1035M_TBL.KNKY_RNRKSK_DIICH_DNW_NO IS '緊急連絡先第一電話番号'
/
COMMENT ON COLUMN ED1035M_TBL.KNKY_RNRKSK_DIN_DNW_NO IS '緊急連絡先第二電話番号'
/
COMMENT ON COLUMN ED1035M_TBL.KJ_JJS_TRK_KOJSN_FILE_SKBT_KEY IS '工事従事者登録顔写真ファイル識別キー'
/
COMMENT ON COLUMN ED1035M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED1035M_TBL.KOJI_JUJISHA_TOROKU_JOTAI_KBN IS '工事従事者登録状態区分'
/
COMMENT ON COLUMN ED1035M_TBL.SHTUK_KISH_TRHKSK_NM IS '下請会社取引先名称'
/
COMMENT ON COLUMN ED1035M_TBL.KOJI_JUJISHA_JIGYONUSHI_FLG IS '工事従事者事業主フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.KOJI_JUJISHA_SAGYOIN_FLG IS '工事従事者作業員フラグ'
/
COMMENT ON COLUMN ED1035M_TBL.KOJI_JUJISHA_KAOJASHIN_FILE_NM IS '工事従事者顔写真ファイル名称'
/
COMMENT ON COLUMN ED1035M_TBL.KOJI_SHIRYO_BUNRUI_KBN IS '工事資料分類区分'
/
COMMENT ON COLUMN ED1035M_TBL.SHAGAI_RIYOSHA_NO IS '社外利用者番号'
/
COMMENT ON COLUMN ED1035M_TBL.SHGI_RYSH_TRK_STATUS_KBN IS '社外利用者登録ステータス区分'
/
COMMENT ON COLUMN ED1035M_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1035M_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1035M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1035M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1035M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1035M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1035M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1035M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1035M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1035M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1035M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1035M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1035M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1035M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
