/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1072T_TBL.sql
-- 物理名：ED1072T_TBL
-- 論理名：工事完了検査動作確認テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1072T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1072T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_KANRYO_KENSA_NO  CHAR(16) NOT NULL --「工事完了検査番号」
	,KOJI_KANRYO_KENSA_RIREKI_NO  CHAR(2) NOT NULL --「工事完了検査履歴番号」
	,KANSHI_KOMOKU_TAISHO_KBN  CHAR(1) NOT NULL --「監視項目対象区分」
	,KANSHI_KOMOKU_SETTEI_NAIYO  VARCHAR2(10) --「監視項目設定内容」
	,DOSA_KAKUNIN_KEKKA_KBN  CHAR(1) NOT NULL --「動作確認結果区分」
	,TORIHIKISAKI_SHOYU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「取引先所有フラグ」
	,ALSOK_SHOYU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫ所有フラグ」
	,DOSA_KAKUNIN_BIKO  VARCHAR2(60) --「動作確認備考」
	,TEKKYO_KOJI_KBN  CHAR(1) NOT NULL --「撤去工事区分」
	,TEKKYO_KOJI_BIKO  VARCHAR2(20) --「撤去工事備考」
	,KANSHI_KOMOKU_BIKO  VARCHAR2(60) --「監視項目備考」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1072T_PK PRIMARY KEY(
	 KOJI_KANRYO_KENSA_NO
	,  KOJI_KANRYO_KENSA_RIREKI_NO
	,  KANSHI_KOMOKU_TAISHO_KBN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1072T_TBL IS '工事完了検査動作確認テーブル'
/

COMMENT ON COLUMN ED1072T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1072T_TBL.KOJI_KANRYO_KENSA_NO IS '工事完了検査番号'
/
COMMENT ON COLUMN ED1072T_TBL.KOJI_KANRYO_KENSA_RIREKI_NO IS '工事完了検査履歴番号'
/
COMMENT ON COLUMN ED1072T_TBL.KANSHI_KOMOKU_TAISHO_KBN IS '監視項目対象区分'
/
COMMENT ON COLUMN ED1072T_TBL.KANSHI_KOMOKU_SETTEI_NAIYO IS '監視項目設定内容'
/
COMMENT ON COLUMN ED1072T_TBL.DOSA_KAKUNIN_KEKKA_KBN IS '動作確認結果区分'
/
COMMENT ON COLUMN ED1072T_TBL.TORIHIKISAKI_SHOYU_FLG IS '取引先所有フラグ'
/
COMMENT ON COLUMN ED1072T_TBL.ALSOK_SHOYU_FLG IS 'ＡＬＳＯＫ所有フラグ'
/
COMMENT ON COLUMN ED1072T_TBL.DOSA_KAKUNIN_BIKO IS '動作確認備考'
/
COMMENT ON COLUMN ED1072T_TBL.TEKKYO_KOJI_KBN IS '撤去工事区分'
/
COMMENT ON COLUMN ED1072T_TBL.TEKKYO_KOJI_BIKO IS '撤去工事備考'
/
COMMENT ON COLUMN ED1072T_TBL.KANSHI_KOMOKU_BIKO IS '監視項目備考'
/
COMMENT ON COLUMN ED1072T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1072T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1072T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1072T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1072T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1072T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1072T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1072T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1072T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1072T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1072T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1072T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1072T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1072T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
