/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1060T_TBL.sql
-- 物理名：ED1060T_TBL
-- 論理名：工事完了検査カメラ状況テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1060T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1060T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_KANRYO_KENSA_NO  CHAR(16) NOT NULL --「工事完了検査番号」
	,KOJI_KANRYO_KENSA_RIREKI_NO  CHAR(2) NOT NULL --「工事完了検査履歴番号」
	,CAMERA_JOKYO_SN  CHAR(3) NOT NULL --「カメラ状況連番」
	,KJ_KNR_KNS_CAMERA_ST_JK_HJ_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「工事完了検査カメラ設置状況表示順」
	,CAMERA_NM  VARCHAR2(15) --「カメラ名称」
	,GAKAKU_KBN  CHAR(1) NOT NULL --「画角区分」
	,SETCHI_BASHO_KBN  CHAR(1) NOT NULL --「設置場所区分」
	,OKUGAI_OKUNAI_KBN  CHAR(1) NOT NULL --「屋外屋内区分」
	,CAMERA_JOKYO_SHUBETSU_KBN  CHAR(1) NOT NULL --「カメラ状況種別区分」
	,SNT_CAMERA_JKY_SHBTS_NM  VARCHAR2(15) --「その他カメラ状況種別名称」
	,IP_ADDRESS_KBN  CHAR(1) NOT NULL --「ＩＰアドレス区分」
	,IP_ADDRESS  VARCHAR2(40) --「ＩＰアドレス」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1060T_PK PRIMARY KEY(
	 KOJI_KANRYO_KENSA_NO
	,  KOJI_KANRYO_KENSA_RIREKI_NO
	,  CAMERA_JOKYO_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1060T_TBL IS '工事完了検査カメラ状況テーブル'
/

COMMENT ON COLUMN ED1060T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1060T_TBL.KOJI_KANRYO_KENSA_NO IS '工事完了検査番号'
/
COMMENT ON COLUMN ED1060T_TBL.KOJI_KANRYO_KENSA_RIREKI_NO IS '工事完了検査履歴番号'
/
COMMENT ON COLUMN ED1060T_TBL.CAMERA_JOKYO_SN IS 'カメラ状況連番'
/
COMMENT ON COLUMN ED1060T_TBL.KJ_KNR_KNS_CAMERA_ST_JK_HJ_JUN IS '工事完了検査カメラ設置状況表示順'
/
COMMENT ON COLUMN ED1060T_TBL.CAMERA_NM IS 'カメラ名称'
/
COMMENT ON COLUMN ED1060T_TBL.GAKAKU_KBN IS '画角区分'
/
COMMENT ON COLUMN ED1060T_TBL.SETCHI_BASHO_KBN IS '設置場所区分'
/
COMMENT ON COLUMN ED1060T_TBL.OKUGAI_OKUNAI_KBN IS '屋外屋内区分'
/
COMMENT ON COLUMN ED1060T_TBL.CAMERA_JOKYO_SHUBETSU_KBN IS 'カメラ状況種別区分'
/
COMMENT ON COLUMN ED1060T_TBL.SNT_CAMERA_JKY_SHBTS_NM IS 'その他カメラ状況種別名称'
/
COMMENT ON COLUMN ED1060T_TBL.IP_ADDRESS_KBN IS 'ＩＰアドレス区分'
/
COMMENT ON COLUMN ED1060T_TBL.IP_ADDRESS IS 'ＩＰアドレス'
/
COMMENT ON COLUMN ED1060T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1060T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1060T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1060T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1060T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1060T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1060T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1060T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1060T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1060T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1060T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1060T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1060T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1060T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
