/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1005T_TBL.sql
-- 物理名：ED1005T_TBL
-- 論理名：撤去機材テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1005T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1005T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,TEKKYO_KIZAI_SN  CHAR(14) NOT NULL --「撤去機材連番」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,BAIKYAKU_TAISHO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「売却対象フラグ」
	,KOTAI_NO  VARCHAR2(30) --「個体番号」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,SETCHI_KIKI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「設置機器数量」
	,TEKKYO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「撤去数量」
	,TEKKYO_KIKI_IRAI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「撤去機器依頼数量」
	,TEKKYO_KIKI_HENKYAKU_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「撤去機器返却数量」
	,HENKYAKU_KIBO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「返却希望数量」
	,TEKKYO_KIKI_HENKYAKUSAKI_KBN  CHAR(1) NOT NULL --「撤去機器返却先区分」
	,TEKKYO_KIKI_HOSHU_KBN  CHAR(1) NOT NULL --「撤去機器補修区分」
	,TEKKYO_KIZAI_BIKO  VARCHAR2(100) --「撤去機材備考」
	,TKKY_KK_TKKY_KKNNSH_NM  VARCHAR2(60) --「撤去機器撤去確認者氏名」
	,TEKKYO_KIKI_TEKKYO_KAKUNIN_YMD  DATE --「撤去機器撤去確認年月日」
	,TKKY_KK_HNKYK_TRKSH_NM  VARCHAR2(60) --「撤去機器返却登録者氏名」
	,TKKY_KK_HNKYK_TRK_YMD  DATE --「撤去機器返却登録年月日」
	,TEKKYO_KIKI_HENKYAKU_YOTEI_YMD  DATE --「撤去機器返却予定年月日」
	,SAISECCHI_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「再設置有フラグ」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1005T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  TEKKYO_KIZAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1005T_TBL IS '撤去機材テーブル'
/

COMMENT ON COLUMN ED1005T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1005T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED1005T_TBL.TEKKYO_KIZAI_SN IS '撤去機材連番'
/
COMMENT ON COLUMN ED1005T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED1005T_TBL.BAIKYAKU_TAISHO_FLG IS '売却対象フラグ'
/
COMMENT ON COLUMN ED1005T_TBL.KOTAI_NO IS '個体番号'
/
COMMENT ON COLUMN ED1005T_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED1005T_TBL.SETCHI_KIKI_SURYO IS '設置機器数量'
/
COMMENT ON COLUMN ED1005T_TBL.TEKKYO_SURYO IS '撤去数量'
/
COMMENT ON COLUMN ED1005T_TBL.TEKKYO_KIKI_IRAI_SURYO IS '撤去機器依頼数量'
/
COMMENT ON COLUMN ED1005T_TBL.TEKKYO_KIKI_HENKYAKU_SURYO IS '撤去機器返却数量'
/
COMMENT ON COLUMN ED1005T_TBL.HENKYAKU_KIBO_SURYO IS '返却希望数量'
/
COMMENT ON COLUMN ED1005T_TBL.TEKKYO_KIKI_HENKYAKUSAKI_KBN IS '撤去機器返却先区分'
/
COMMENT ON COLUMN ED1005T_TBL.TEKKYO_KIKI_HOSHU_KBN IS '撤去機器補修区分'
/
COMMENT ON COLUMN ED1005T_TBL.TEKKYO_KIZAI_BIKO IS '撤去機材備考'
/
COMMENT ON COLUMN ED1005T_TBL.TKKY_KK_TKKY_KKNNSH_NM IS '撤去機器撤去確認者氏名'
/
COMMENT ON COLUMN ED1005T_TBL.TEKKYO_KIKI_TEKKYO_KAKUNIN_YMD IS '撤去機器撤去確認年月日'
/
COMMENT ON COLUMN ED1005T_TBL.TKKY_KK_HNKYK_TRKSH_NM IS '撤去機器返却登録者氏名'
/
COMMENT ON COLUMN ED1005T_TBL.TKKY_KK_HNKYK_TRK_YMD IS '撤去機器返却登録年月日'
/
COMMENT ON COLUMN ED1005T_TBL.TEKKYO_KIKI_HENKYAKU_YOTEI_YMD IS '撤去機器返却予定年月日'
/
COMMENT ON COLUMN ED1005T_TBL.SAISECCHI_ARI_FLG IS '再設置有フラグ'
/
COMMENT ON COLUMN ED1005T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1005T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1005T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1005T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1005T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1005T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1005T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1005T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1005T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1005T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1005T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1005T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1005T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1005T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
