/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1004T_TBL.sql
-- 物理名：ED1004T_TBL
-- 論理名：工事依頼明細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1004T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1004T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,KOJI_IRAI_MEISAI_SN  CHAR(14) NOT NULL --「工事依頼明細連番」
	,BNKTSMT_KJ_IRI_MISI_SN  CHAR(14) --「分割元工事依頼明細連番」
	,KOJI_SHIGOTO_SN  CHAR(14) --「工事仕事連番」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,KOJI_KBN  CHAR(1) NOT NULL --「工事区分」
	,KOJI_NM  VARCHAR2(30) --「工事名称」
	,KOJI_TOKKI_JIKO  VARCHAR2(100) --「工事特記事項」
	,SEKISAN_KBN  CHAR(1) NOT NULL --「積算区分」
	,SEKISAN_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「積算原価金額」
	,KOJI_HATCHU_AMT_SHONINZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事発注金額承認済フラグ」
	,KOJI_HATCHUZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事発注済フラグ」
	,KOJI_KYORYOKU_KAISHA_KBN  CHAR(1) NOT NULL --「工事協力会社区分」
	,ALSOK_KOJIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫ工事有フラグ」
	,KJ_KYRYK_KISH_TRHKSK_CD  CHAR(9) --「工事協力会社取引先コード」
	,KOJI_TORIHIKISAKI_BUSHO_CD  CHAR(4) --「工事取引先部署コード」
	,KYORYOKU_KAISHA_MITSUMORI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「協力会社見積金額」
	,KYORYOKU_KAISHA_MITSUMORI_NO  CHAR(15) --「協力会社見積番号」
	,SEKISAN_NO  CHAR(17) --「積算番号」
	,KYORYOKU_KAISHA_MITSUMORI_YMD  DATE --「協力会社見積年月日」
	,HATCHU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「発注金額」
	,KOJI_IRAI_MEISAI_SHUSEIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事依頼明細修正有フラグ」
	,KOJI_KOTEI_WARIATEZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事工程割当済フラグ」
	,SEIKYU_KAKUNINZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「請求確認済フラグ」
	,KANRYO_KENSA_JUMBIZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「完了検査準備済フラグ」
	,KANRYO_KENSA_JISSHIZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「完了検査実施済フラグ」
	,SHOKI_TOROKUZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「初期登録済フラグ」
	,MKKNN_TISHTSBTSAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「未確認提出物有フラグ」
	,SHTIGI_KISH_HTCHZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「指定外会社発注済フラグ」
	,ITAKU_KENSA_TANTO_KBN  CHAR(1) NOT NULL --「委託検査担当区分」
	,KOJI_CHUMON_KBN  CHAR(1) NOT NULL --「工事注文区分」
	,HATCHU_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「発注原価金額」
	,SHONIN_GENDO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「承認限度金額」
	,ITAKU_KENSAHI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「委託検査費金額」
	,HATCHU_SHOHIZEI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「発注消費税金額」
	,HATCHU_SHOHIZEI_CHOSEI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「発注消費税調整金額」
	,KJ_HTCH_AMT_HNK_SHNNZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事発注金額変更承認済フラグ」
	,KOJI_IRAI_MEISAI_BIKO  VARCHAR2(20) --「工事依頼明細備考」
	,CHOKUSO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「直送フラグ」
	,KYRYK_KISH_WRATZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「協力会社割当済フラグ」
	,KJ_IRI_KJ_KTI_WRATZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事依頼工事工程割当済フラグ」
	,KJ_CHUMONZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事注文済フラグ」
	,KJ_CHUMON_BKTZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事注文書分割済フラグ」
	,KJ_CHUMONUKEZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事注文請済フラグ」
	,KOJI_IRAI_KOJI_CHAKKOZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事依頼工事着工済フラグ」
	,KJ_SCZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事ＳＣ済フラグ」
	,KJ_NP_TEISHUTUZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事日報提出済フラグ」
	,KJ_BKTKENSHUZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事分割検収済フラグ」
	,ITB_KJ_BKTKENSHUZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「一部工事分割検収済フラグ」
	,KJ_BKTBARAI_SHSGZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事分割払支払照合済フラグ」
	,KOJI_IRAI_KOJI_SHURYO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事依頼工事終了フラグ」
	,KJ_KJKRKS_SEIKYUZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事協力会社請求済フラグ」
	,KJ_SHSHOGOZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事支払照合済フラグ」
	,KJ_SHSHONINZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事支払承認済フラグ」
	,KJ_SHKAKUTEIZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事支払確定済フラグ」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1004T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  KOJI_IRAI_MEISAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1004T_TBL IS '工事依頼明細テーブル'
/

COMMENT ON COLUMN ED1004T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1004T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_IRAI_MEISAI_SN IS '工事依頼明細連番'
/
COMMENT ON COLUMN ED1004T_TBL.BNKTSMT_KJ_IRI_MISI_SN IS '分割元工事依頼明細連番'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_SHIGOTO_SN IS '工事仕事連番'
/
COMMENT ON COLUMN ED1004T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_KBN IS '工事区分'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_NM IS '工事名称'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_TOKKI_JIKO IS '工事特記事項'
/
COMMENT ON COLUMN ED1004T_TBL.SEKISAN_KBN IS '積算区分'
/
COMMENT ON COLUMN ED1004T_TBL.SEKISAN_GENKA_AMT IS '積算原価金額'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_HATCHU_AMT_SHONINZUMI_FLG IS '工事発注金額承認済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_HATCHUZUMI_FLG IS '工事発注済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_KYORYOKU_KAISHA_KBN IS '工事協力会社区分'
/
COMMENT ON COLUMN ED1004T_TBL.ALSOK_KOJIARI_FLG IS 'ＡＬＳＯＫ工事有フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KJ_KYRYK_KISH_TRHKSK_CD IS '工事協力会社取引先コード'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_TORIHIKISAKI_BUSHO_CD IS '工事取引先部署コード'
/
COMMENT ON COLUMN ED1004T_TBL.KYORYOKU_KAISHA_MITSUMORI_AMT IS '協力会社見積金額'
/
COMMENT ON COLUMN ED1004T_TBL.KYORYOKU_KAISHA_MITSUMORI_NO IS '協力会社見積番号'
/
COMMENT ON COLUMN ED1004T_TBL.SEKISAN_NO IS '積算番号'
/
COMMENT ON COLUMN ED1004T_TBL.KYORYOKU_KAISHA_MITSUMORI_YMD IS '協力会社見積年月日'
/
COMMENT ON COLUMN ED1004T_TBL.HATCHU_AMT IS '発注金額'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_IRAI_MEISAI_SHUSEIARI_FLG IS '工事依頼明細修正有フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_KOTEI_WARIATEZUMI_FLG IS '工事工程割当済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.SEIKYU_KAKUNINZUMI_FLG IS '請求確認済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KANRYO_KENSA_JUMBIZUMI_FLG IS '完了検査準備済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KANRYO_KENSA_JISSHIZUMI_FLG IS '完了検査実施済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.SHOKI_TOROKUZUMI_FLG IS '初期登録済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.MKKNN_TISHTSBTSAR_FLG IS '未確認提出物有フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.SHTIGI_KISH_HTCHZM_FLG IS '指定外会社発注済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.ITAKU_KENSA_TANTO_KBN IS '委託検査担当区分'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_CHUMON_KBN IS '工事注文区分'
/
COMMENT ON COLUMN ED1004T_TBL.HATCHU_GENKA_AMT IS '発注原価金額'
/
COMMENT ON COLUMN ED1004T_TBL.SHONIN_GENDO_AMT IS '承認限度金額'
/
COMMENT ON COLUMN ED1004T_TBL.ITAKU_KENSAHI_AMT IS '委託検査費金額'
/
COMMENT ON COLUMN ED1004T_TBL.HATCHU_SHOHIZEI_AMT IS '発注消費税金額'
/
COMMENT ON COLUMN ED1004T_TBL.HATCHU_SHOHIZEI_CHOSEI_AMT IS '発注消費税調整金額'
/
COMMENT ON COLUMN ED1004T_TBL.KJ_HTCH_AMT_HNK_SHNNZM_FLG IS '工事発注金額変更承認済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_IRAI_MEISAI_BIKO IS '工事依頼明細備考'
/
COMMENT ON COLUMN ED1004T_TBL.CHOKUSO_FLG IS '直送フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KYRYK_KISH_WRATZM_FLG IS '協力会社割当済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KJ_IRI_KJ_KTI_WRATZM_FLG IS '工事依頼工事工程割当済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KJ_CHUMONZM_FLG IS '工事注文済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KJ_CHUMON_BKTZM_FLG IS '工事注文書分割済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KJ_CHUMONUKEZM_FLG IS '工事注文請済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_IRAI_KOJI_CHAKKOZUMI_FLG IS '工事依頼工事着工済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KJ_SCZM_FLG IS '工事ＳＣ済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KJ_NP_TEISHUTUZM_FLG IS '工事日報提出済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KJ_BKTKENSHUZM_FLG IS '工事分割検収済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.ITB_KJ_BKTKENSHUZM_FLG IS '一部工事分割検収済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KJ_BKTBARAI_SHSGZM_FLG IS '工事分割払支払照合済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KOJI_IRAI_KOJI_SHURYO_FLG IS '工事依頼工事終了フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KJ_KJKRKS_SEIKYUZM_FLG IS '工事協力会社請求済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KJ_SHSHOGOZM_FLG IS '工事支払照合済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KJ_SHSHONINZM_FLG IS '工事支払承認済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.KJ_SHKAKUTEIZM_FLG IS '工事支払確定済フラグ'
/
COMMENT ON COLUMN ED1004T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1004T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1004T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1004T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1004T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1004T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1004T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1004T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1004T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1004T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1004T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1004T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1004T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1004T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
