/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1065T_TBL.sql
-- 物理名：ED1065T_TBL
-- 論理名：工事完了検査出入管理状況確認テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1065T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1065T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_KANRYO_KENSA_NO  CHAR(16) NOT NULL --「工事完了検査番号」
	,KOJI_KANRYO_KENSA_RIREKI_NO  CHAR(2) NOT NULL --「工事完了検査履歴番号」
	,SHTSNY_KNR_JKY_KKNN_SN  CHAR(3) NOT NULL --「出入管理状況確認連番」
	,SHTSNY_KNR_JKY_KKNN_HYJ_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「出入管理状況確認表示順」
	,SHTSNY_KNR_JKY_KKNN_NM  VARCHAR2(15) --「出入管理状況確認名称」
	,SOSAKI_KBN  CHAR(1) NOT NULL --「操作器区分」
	,KEIHO_KIKI_SHURUI_KBN  CHAR(1) NOT NULL --「警報機器種類区分」
	,PANIC_OPEN_KBN  CHAR(1) NOT NULL --「パニックオープン区分」
	,SEIGYO_TAISHO_KBN  CHAR(1) NOT NULL --「制御対象区分」
	,SONOTA_SEIGYO_TAISHO_NM  VARCHAR2(15) --「その他制御対象名称」
	,ANTIPANIC_KBN  CHAR(1) NOT NULL --「アンチパニック区分」
	,SHTSNY_KNR_JKY_KKNN_BIKO  VARCHAR2(20) --「出入管理状況確認備考」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1065T_PK PRIMARY KEY(
	 KOJI_KANRYO_KENSA_NO
	,  KOJI_KANRYO_KENSA_RIREKI_NO
	,  SHTSNY_KNR_JKY_KKNN_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1065T_TBL IS '工事完了検査出入管理状況確認テーブル'
/

COMMENT ON COLUMN ED1065T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1065T_TBL.KOJI_KANRYO_KENSA_NO IS '工事完了検査番号'
/
COMMENT ON COLUMN ED1065T_TBL.KOJI_KANRYO_KENSA_RIREKI_NO IS '工事完了検査履歴番号'
/
COMMENT ON COLUMN ED1065T_TBL.SHTSNY_KNR_JKY_KKNN_SN IS '出入管理状況確認連番'
/
COMMENT ON COLUMN ED1065T_TBL.SHTSNY_KNR_JKY_KKNN_HYJ_JUN IS '出入管理状況確認表示順'
/
COMMENT ON COLUMN ED1065T_TBL.SHTSNY_KNR_JKY_KKNN_NM IS '出入管理状況確認名称'
/
COMMENT ON COLUMN ED1065T_TBL.SOSAKI_KBN IS '操作器区分'
/
COMMENT ON COLUMN ED1065T_TBL.KEIHO_KIKI_SHURUI_KBN IS '警報機器種類区分'
/
COMMENT ON COLUMN ED1065T_TBL.PANIC_OPEN_KBN IS 'パニックオープン区分'
/
COMMENT ON COLUMN ED1065T_TBL.SEIGYO_TAISHO_KBN IS '制御対象区分'
/
COMMENT ON COLUMN ED1065T_TBL.SONOTA_SEIGYO_TAISHO_NM IS 'その他制御対象名称'
/
COMMENT ON COLUMN ED1065T_TBL.ANTIPANIC_KBN IS 'アンチパニック区分'
/
COMMENT ON COLUMN ED1065T_TBL.SHTSNY_KNR_JKY_KKNN_BIKO IS '出入管理状況確認備考'
/
COMMENT ON COLUMN ED1065T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1065T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1065T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1065T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1065T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1065T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1065T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1065T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1065T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1065T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1065T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1065T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1065T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1065T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
