/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1031T_TBL.sql
-- 物理名：ED1031T_TBL
-- 論理名：設備テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1031T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1031T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TAISHOSAKI_CD  CHAR(9) NOT NULL --「対象先コード」
	,SETSUBI_SN  CHAR(14) NOT NULL --「設備連番」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,SETSUBI_NM  VARCHAR2(10) --「設備名称」
	,MAKER_NM  VARCHAR2(100) --「メーカ名称」
	,KATASHIKI_NM  VARCHAR2(15) --「型式名称」
	,TANSHI_NM  VARCHAR2(16) --「端子名称」
	,KEIHO_SETSUBI_BIKO  VARCHAR2(20) --「警報設備備考」
	,KEIHO_SETSUBI_SHOCHI_KBN  CHAR(1) NOT NULL --「警報設備処置区分」
	,HOZEN_KEIHO_KBN  CHAR(1) NOT NULL --「保全警報区分」
	,DEMPYO_YMD  DATE NOT NULL --「伝票年月日」
	,SETSUBI_SHIKEN_KEKKA_KBN  CHAR(1) DEFAULT '1' NOT NULL --「設備試験結果区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1031T_PK PRIMARY KEY(
	 TAISHOSAKI_CD
	,  SETSUBI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1031T_TBL IS '設備テーブル'
/

COMMENT ON COLUMN ED1031T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1031T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED1031T_TBL.SETSUBI_SN IS '設備連番'
/
COMMENT ON COLUMN ED1031T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED1031T_TBL.SETSUBI_NM IS '設備名称'
/
COMMENT ON COLUMN ED1031T_TBL.MAKER_NM IS 'メーカ名称'
/
COMMENT ON COLUMN ED1031T_TBL.KATASHIKI_NM IS '型式名称'
/
COMMENT ON COLUMN ED1031T_TBL.TANSHI_NM IS '端子名称'
/
COMMENT ON COLUMN ED1031T_TBL.KEIHO_SETSUBI_BIKO IS '警報設備備考'
/
COMMENT ON COLUMN ED1031T_TBL.KEIHO_SETSUBI_SHOCHI_KBN IS '警報設備処置区分'
/
COMMENT ON COLUMN ED1031T_TBL.HOZEN_KEIHO_KBN IS '保全警報区分'
/
COMMENT ON COLUMN ED1031T_TBL.DEMPYO_YMD IS '伝票年月日'
/
COMMENT ON COLUMN ED1031T_TBL.SETSUBI_SHIKEN_KEKKA_KBN IS '設備試験結果区分'
/
COMMENT ON COLUMN ED1031T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1031T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1031T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1031T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1031T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1031T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1031T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1031T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1031T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1031T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1031T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1031T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
