/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1026T_TBL.sql
-- 物理名：ED1026T_TBL
-- 論理名：工事完了検査テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1026T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1026T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_KANRYO_KENSA_NO  CHAR(16) NOT NULL --「工事完了検査番号」
	,KOJI_KANRYO_KENSA_RIREKI_NO  CHAR(2) NOT NULL --「工事完了検査履歴番号」
	,KANRYO_KENSA_YMD  DATE --「完了検査年月日」
	,KANRYO_KENSA_KAISHI_DT  TIMESTAMP --「完了検査開始日時」
	,KANRYO_KENSA_SHURYO_DT  TIMESTAMP --「完了検査終了日時」
	,HD_TOOL_TRKM_XML_FILE_SKBT_KEY  VARCHAR2(255) --「ＨＤツール取込ＸＭＬファイル識別キー」
	,XML_FILE_ZENKAI_TORIKOMI_DT  TIMESTAMP --「ＸＭＬファイル前回取込日時」
	,ALMOND_TAIO_KANRYO_KENSAYO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「アマンド対応完了検査要フラグ」
	,GAZO_SENSOR_KANRYO_KENSAYO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「画像センサー完了検査要フラグ」
	,KEIYAKUSAKI_TORIHIKISAKI_NM  VARCHAR2(40) --「契約先取引先名称」
	,KEISHO_KBN  CHAR(1) NOT NULL --「敬称区分」
	,OKYAKUSAMA_SHISETSU_NM  VARCHAR2(60) --「お客様施設名称」
	,TORIHIKISAKI_TANTOSHA_NM  VARCHAR2(60) --「取引先担当者氏名」
	,KJ_KNRY_KNS_ITKSK_KBN  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査委託先区分」
	,KOJI_NM  VARCHAR2(30) --「工事名称」
	,KOJI_KAISHI_YMD  DATE --「工事開始年月日」
	,KOJI_SHURYO_YMD  DATE --「工事終了年月日」
	,HONKENSA_JISSHI_D  DATE --「本検査実施日」
	,HONKENSA_KENSASHA_NM  VARCHAR2(60) --「本検査検査者氏名」
	,TSUIKENSA_JISSHI_D  DATE --「追検査実施日」
	,TSUIKENSA_KENSASHA_NM  VARCHAR2(60) --「追検査検査者氏名」
	,KANRYO_KENSA_KENSHU_YMD  DATE --「完了検査検収年月日」
	,OKYKSM_YBMTH_MSHOKR_JIKO  VARCHAR2(300) --「お客様要望又は申送り事項」
	,T_1_GC_SHINGO_JUSHIN_KBN  CHAR(1) NOT NULL --「Ｔ１ＧＣ信号受信区分」
	,P_1_TAMPER_SIGY_SIGYSCHTAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「Ｐ１タンパー制御装置等有フラグ」
	,SONOTA_P_1_TAMPER_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「その他Ｐ１タンパー有フラグ」
	,SONOTA_P_1_TAMPER_BIKO  VARCHAR2(20) --「その他Ｐ１タンパー備考」
	,P_1_TAMPER_GC_SHNG_JSHN_KBN  CHAR(1) NOT NULL --「Ｐ１タンパーＧＣ信号受信区分」
	,GC_SHNG_JSHN_KKNN_HH_KBN  CHAR(1) NOT NULL --「ＧＣ信号受信確認方法区分」
	,GC_SHNG_JSHN_KKNN_HH_NM  VARCHAR2(20) --「ＧＣ信号受信確認方法名称」
	,ONSEI_MESSAGE_BUZZER_KBN  CHAR(1) NOT NULL --「音声メッセージブザー区分」
	,HYOJI_LAMP_KBN  CHAR(1) NOT NULL --「表示ランプ区分」
	,KEIBI_KAISHI_SHURYO_SOSA_KBN  CHAR(1) NOT NULL --「警備開始終了操作区分」
	,JUNKAI_KAISHI_SHURYO_SOSA_KBN  CHAR(1) NOT NULL --「巡回開始終了操作区分」
	,FRY_TIKN_BSH_KN_SD_KBN  CHAR(1) NOT NULL --「不良退館防止機能作動区分」
	,NYUKAN_TIMER_JIKAN  NUMBER(9,0) --「入館タイマー時間」
	,TAIKAN_TIMER_JIKAN  NUMBER(9,0) --「退館タイマー時間」
	,SEIGYO_SOCHI_KBN  CHAR(1) NOT NULL --「制御装置区分」
	,SOSAKI_SHIKEN_KEKKA_KBN  CHAR(1) NOT NULL --「操作器試験結果区分」
	,ALSOK_LIGHT_KBN  CHAR(1) NOT NULL --「ＡＬＳＯＫライト区分」
	,SONOTA_SHASHIN_BIKO  VARCHAR2(50) --「その他写真備考」
	,HD_KJ_KNR_KNS_SIG_SC_KTSK_NM  VARCHAR2(15) --「ＨＤ工事完了検査制御装置型式名称」
	,HD_KOJI_KANRYO_KENSA_SEIZO_NO  VARCHAR2(30) --「ＨＤ工事完了検査製造番号」
	,RECORDER_KATASHIKI_NM  CHAR(20) --「レコーダー型式名称」
	,DENGEN_SETSUZOKU_BASHO_NM  VARCHAR2(15) --「電源接続場所名称」
	,SHOKI_PASSWORD_HENKO_KBN  CHAR(1) NOT NULL --「初期パスワード変更区分」
	,SNT_SHK_PASSWORD_HNK_BIKO  VARCHAR2(10) --「その他初期パスワード変更備考」
	,ROKUGA_JIKAN_BIKO  VARCHAR2(20) --「録画時間備考」
	,REPEAT_ROKUGA_KBN  CHAR(1) NOT NULL --「リピート録画区分」
	,NETWORK_SETSUZOKU_KBN  CHAR(1) NOT NULL --「ネットワーク接続区分」
	,IP_ADDRESS_KBN  CHAR(1) NOT NULL --「ＩＰアドレス区分」
	,IP_ADDRESS  VARCHAR2(40) --「ＩＰアドレス」
	,ALARM_NYURYOKU_KBN  CHAR(1) NOT NULL --「アラーム入力区分」
	,ALARM_NYURYOKU_BIKO  VARCHAR2(20) --「アラーム入力備考」
	,IHO_SHUTSURYOKU_KBN  CHAR(1) NOT NULL --「移報出力区分」
	,IHO_SHUTSURYOKU_BIKO  VARCHAR2(20) --「移報出力備考」
	,HIZUKE_YOBI_SETTEI_KAKUNIN_KBN  CHAR(1) NOT NULL --「日付曜日設定確認区分」
	,ROKUGA_LAMP_SHASHIN_KBN  CHAR(1) NOT NULL --「録画ランプ写真区分」
	,SETTEI_GAMEN_SHASHIN_KBN  CHAR(1) NOT NULL --「設定画面写真区分」
	,ROKUGA_JOTAI_SHASHIN_KBN  CHAR(1) NOT NULL --「録画状態写真区分」
	,DATA_BACKUP_KBN  CHAR(1) NOT NULL --「データバックアップ区分」
	,SHUTSUNYU_KANRI_SOFT_KBN  CHAR(1) NOT NULL --「出入管理ソフト区分」
	,SHUTSUNYU_KANRI_SOFT_NM  VARCHAR2(15) --「出入管理ソフト名称」
	,DATA_SHASHIN_KBN  CHAR(1) NOT NULL --「データ写真区分」
	,DENSHI_SIGN_FUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「電子サイン不可フラグ」
	,DENSHI_SIGN_FUKA_RIYU_KBN  CHAR(1) NOT NULL --「電子サイン不可理由区分」
	,DNSH_SIGN_Y_FILE_SHKBTS_KEY  VARCHAR2(255) --「電子サイン年ファイル識別キー」
	,DNSH_SIGN_M_FILE_SHKBTS_KEY  VARCHAR2(255) --「電子サイン月ファイル識別キー」
	,DNSH_SIGN_D_FILE_SHKBTS_KEY  VARCHAR2(255) --「電子サイン日ファイル識別キー」
	,DNSH_SIGN_NM_FILE_SHKBTS_KEY  VARCHAR2(255) --「電子サイン氏名ファイル識別キー」
	,DENSHI_SIGN_SHOMEI_YMD  DATE --「電子サイン署名年月日」
	,KJ_KRKSH_SS_ICHJ_HZNZM_FLG_1  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細一時保存済フラグ１」
	,KJ_KRKSH_SS_TOROKUZUMI_FLG_1  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細登録済フラグ１」
	,KJ_KRKSH_SS_ICHJ_HZNZM_FLG_2  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細一時保存済フラグ２」
	,KJ_KRKSH_SS_TOROKUZUMI_FLG_2  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細登録済フラグ２」
	,KJ_KRKSH_SS_ICHJ_HZNZM_FLG_3  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細一時保存済フラグ３」
	,KJ_KRKSH_SS_TOROKUZUMI_FLG_3  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細登録済フラグ３」
	,KJ_KRKSH_SS_ICHJ_HZNZM_FLG_4  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細一時保存済フラグ４」
	,KJ_KRKSH_SS_TOROKUZUMI_FLG_4  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細登録済フラグ４」
	,KJ_KRKSH_SS_ICHJ_HZNZM_FLG_5  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細一時保存済フラグ５」
	,KJ_KRKSH_SS_TOROKUZUMI_FLG_5  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細登録済フラグ５」
	,KJ_KRKSH_SS_ICHJ_HZNZM_FLG_6  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細一時保存済フラグ６」
	,KJ_KRKSH_SS_TOROKUZUMI_FLG_6  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細登録済フラグ６」
	,KJ_KRKSH_SS_ICHJ_HZNZM_FLG_7  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細一時保存済フラグ７」
	,KJ_KRKSH_SS_TOROKUZUMI_FLG_7  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細登録済フラグ７」
	,KJ_KRKSH_SS_ICHJ_HZNZM_FLG_8  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細一時保存済フラグ８」
	,KJ_KRKSH_SS_TOROKUZUMI_FLG_8  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細登録済フラグ８」
	,KJ_KRKSH_SS_ICHJ_HZNZM_FLG_9  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細一時保存済フラグ９」
	,KJ_KRKSH_SS_TOROKUZUMI_FLG_9  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細登録済フラグ９」
	,KJ_KRKSH_SS_ICHJ_HZNZM_FLG_10  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細一時保存済フラグ１０」
	,KJ_KRKSH_SS_TOROKUZUMI_FLG_10  CHAR(1) DEFAULT '0' NOT NULL --「工事完了検査表詳細登録済フラグ１０」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1026T_PK PRIMARY KEY(
	 KOJI_KANRYO_KENSA_NO
	,  KOJI_KANRYO_KENSA_RIREKI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1026T_TBL IS '工事完了検査テーブル'
/

COMMENT ON COLUMN ED1026T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1026T_TBL.KOJI_KANRYO_KENSA_NO IS '工事完了検査番号'
/
COMMENT ON COLUMN ED1026T_TBL.KOJI_KANRYO_KENSA_RIREKI_NO IS '工事完了検査履歴番号'
/
COMMENT ON COLUMN ED1026T_TBL.KANRYO_KENSA_YMD IS '完了検査年月日'
/
COMMENT ON COLUMN ED1026T_TBL.KANRYO_KENSA_KAISHI_DT IS '完了検査開始日時'
/
COMMENT ON COLUMN ED1026T_TBL.KANRYO_KENSA_SHURYO_DT IS '完了検査終了日時'
/
COMMENT ON COLUMN ED1026T_TBL.HD_TOOL_TRKM_XML_FILE_SKBT_KEY IS 'ＨＤツール取込ＸＭＬファイル識別キー'
/
COMMENT ON COLUMN ED1026T_TBL.XML_FILE_ZENKAI_TORIKOMI_DT IS 'ＸＭＬファイル前回取込日時'
/
COMMENT ON COLUMN ED1026T_TBL.ALMOND_TAIO_KANRYO_KENSAYO_FLG IS 'アマンド対応完了検査要フラグ'
/
COMMENT ON COLUMN ED1026T_TBL.GAZO_SENSOR_KANRYO_KENSAYO_FLG IS '画像センサー完了検査要フラグ'
/
COMMENT ON COLUMN ED1026T_TBL.KEIYAKUSAKI_TORIHIKISAKI_NM IS '契約先取引先名称'
/
COMMENT ON COLUMN ED1026T_TBL.KEISHO_KBN IS '敬称区分'
/
COMMENT ON COLUMN ED1026T_TBL.OKYAKUSAMA_SHISETSU_NM IS 'お客様施設名称'
/
COMMENT ON COLUMN ED1026T_TBL.TORIHIKISAKI_TANTOSHA_NM IS '取引先担当者氏名'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KNRY_KNS_ITKSK_KBN IS '工事完了検査委託先区分'
/
COMMENT ON COLUMN ED1026T_TBL.KOJI_NM IS '工事名称'
/
COMMENT ON COLUMN ED1026T_TBL.KOJI_KAISHI_YMD IS '工事開始年月日'
/
COMMENT ON COLUMN ED1026T_TBL.KOJI_SHURYO_YMD IS '工事終了年月日'
/
COMMENT ON COLUMN ED1026T_TBL.HONKENSA_JISSHI_D IS '本検査実施日'
/
COMMENT ON COLUMN ED1026T_TBL.HONKENSA_KENSASHA_NM IS '本検査検査者氏名'
/
COMMENT ON COLUMN ED1026T_TBL.TSUIKENSA_JISSHI_D IS '追検査実施日'
/
COMMENT ON COLUMN ED1026T_TBL.TSUIKENSA_KENSASHA_NM IS '追検査検査者氏名'
/
COMMENT ON COLUMN ED1026T_TBL.KANRYO_KENSA_KENSHU_YMD IS '完了検査検収年月日'
/
COMMENT ON COLUMN ED1026T_TBL.OKYKSM_YBMTH_MSHOKR_JIKO IS 'お客様要望又は申送り事項'
/
COMMENT ON COLUMN ED1026T_TBL.T_1_GC_SHINGO_JUSHIN_KBN IS 'Ｔ１ＧＣ信号受信区分'
/
COMMENT ON COLUMN ED1026T_TBL.P_1_TAMPER_SIGY_SIGYSCHTAR_FLG IS 'Ｐ１タンパー制御装置等有フラグ'
/
COMMENT ON COLUMN ED1026T_TBL.SONOTA_P_1_TAMPER_ARI_FLG IS 'その他Ｐ１タンパー有フラグ'
/
COMMENT ON COLUMN ED1026T_TBL.SONOTA_P_1_TAMPER_BIKO IS 'その他Ｐ１タンパー備考'
/
COMMENT ON COLUMN ED1026T_TBL.P_1_TAMPER_GC_SHNG_JSHN_KBN IS 'Ｐ１タンパーＧＣ信号受信区分'
/
COMMENT ON COLUMN ED1026T_TBL.GC_SHNG_JSHN_KKNN_HH_KBN IS 'ＧＣ信号受信確認方法区分'
/
COMMENT ON COLUMN ED1026T_TBL.GC_SHNG_JSHN_KKNN_HH_NM IS 'ＧＣ信号受信確認方法名称'
/
COMMENT ON COLUMN ED1026T_TBL.ONSEI_MESSAGE_BUZZER_KBN IS '音声メッセージブザー区分'
/
COMMENT ON COLUMN ED1026T_TBL.HYOJI_LAMP_KBN IS '表示ランプ区分'
/
COMMENT ON COLUMN ED1026T_TBL.KEIBI_KAISHI_SHURYO_SOSA_KBN IS '警備開始終了操作区分'
/
COMMENT ON COLUMN ED1026T_TBL.JUNKAI_KAISHI_SHURYO_SOSA_KBN IS '巡回開始終了操作区分'
/
COMMENT ON COLUMN ED1026T_TBL.FRY_TIKN_BSH_KN_SD_KBN IS '不良退館防止機能作動区分'
/
COMMENT ON COLUMN ED1026T_TBL.NYUKAN_TIMER_JIKAN IS '入館タイマー時間'
/
COMMENT ON COLUMN ED1026T_TBL.TAIKAN_TIMER_JIKAN IS '退館タイマー時間'
/
COMMENT ON COLUMN ED1026T_TBL.SEIGYO_SOCHI_KBN IS '制御装置区分'
/
COMMENT ON COLUMN ED1026T_TBL.SOSAKI_SHIKEN_KEKKA_KBN IS '操作器試験結果区分'
/
COMMENT ON COLUMN ED1026T_TBL.ALSOK_LIGHT_KBN IS 'ＡＬＳＯＫライト区分'
/
COMMENT ON COLUMN ED1026T_TBL.SONOTA_SHASHIN_BIKO IS 'その他写真備考'
/
COMMENT ON COLUMN ED1026T_TBL.HD_KJ_KNR_KNS_SIG_SC_KTSK_NM IS 'ＨＤ工事完了検査制御装置型式名称'
/
COMMENT ON COLUMN ED1026T_TBL.HD_KOJI_KANRYO_KENSA_SEIZO_NO IS 'ＨＤ工事完了検査製造番号'
/
COMMENT ON COLUMN ED1026T_TBL.RECORDER_KATASHIKI_NM IS 'レコーダー型式名称'
/
COMMENT ON COLUMN ED1026T_TBL.DENGEN_SETSUZOKU_BASHO_NM IS '電源接続場所名称'
/
COMMENT ON COLUMN ED1026T_TBL.SHOKI_PASSWORD_HENKO_KBN IS '初期パスワード変更区分'
/
COMMENT ON COLUMN ED1026T_TBL.SNT_SHK_PASSWORD_HNK_BIKO IS 'その他初期パスワード変更備考'
/
COMMENT ON COLUMN ED1026T_TBL.ROKUGA_JIKAN_BIKO IS '録画時間備考'
/
COMMENT ON COLUMN ED1026T_TBL.REPEAT_ROKUGA_KBN IS 'リピート録画区分'
/
COMMENT ON COLUMN ED1026T_TBL.NETWORK_SETSUZOKU_KBN IS 'ネットワーク接続区分'
/
COMMENT ON COLUMN ED1026T_TBL.IP_ADDRESS_KBN IS 'ＩＰアドレス区分'
/
COMMENT ON COLUMN ED1026T_TBL.IP_ADDRESS IS 'ＩＰアドレス'
/
COMMENT ON COLUMN ED1026T_TBL.ALARM_NYURYOKU_KBN IS 'アラーム入力区分'
/
COMMENT ON COLUMN ED1026T_TBL.ALARM_NYURYOKU_BIKO IS 'アラーム入力備考'
/
COMMENT ON COLUMN ED1026T_TBL.IHO_SHUTSURYOKU_KBN IS '移報出力区分'
/
COMMENT ON COLUMN ED1026T_TBL.IHO_SHUTSURYOKU_BIKO IS '移報出力備考'
/
COMMENT ON COLUMN ED1026T_TBL.HIZUKE_YOBI_SETTEI_KAKUNIN_KBN IS '日付曜日設定確認区分'
/
COMMENT ON COLUMN ED1026T_TBL.ROKUGA_LAMP_SHASHIN_KBN IS '録画ランプ写真区分'
/
COMMENT ON COLUMN ED1026T_TBL.SETTEI_GAMEN_SHASHIN_KBN IS '設定画面写真区分'
/
COMMENT ON COLUMN ED1026T_TBL.ROKUGA_JOTAI_SHASHIN_KBN IS '録画状態写真区分'
/
COMMENT ON COLUMN ED1026T_TBL.DATA_BACKUP_KBN IS 'データバックアップ区分'
/
COMMENT ON COLUMN ED1026T_TBL.SHUTSUNYU_KANRI_SOFT_KBN IS '出入管理ソフト区分'
/
COMMENT ON COLUMN ED1026T_TBL.SHUTSUNYU_KANRI_SOFT_NM IS '出入管理ソフト名称'
/
COMMENT ON COLUMN ED1026T_TBL.DATA_SHASHIN_KBN IS 'データ写真区分'
/
COMMENT ON COLUMN ED1026T_TBL.DENSHI_SIGN_FUKA_FLG IS '電子サイン不可フラグ'
/
COMMENT ON COLUMN ED1026T_TBL.DENSHI_SIGN_FUKA_RIYU_KBN IS '電子サイン不可理由区分'
/
COMMENT ON COLUMN ED1026T_TBL.DNSH_SIGN_Y_FILE_SHKBTS_KEY IS '電子サイン年ファイル識別キー'
/
COMMENT ON COLUMN ED1026T_TBL.DNSH_SIGN_M_FILE_SHKBTS_KEY IS '電子サイン月ファイル識別キー'
/
COMMENT ON COLUMN ED1026T_TBL.DNSH_SIGN_D_FILE_SHKBTS_KEY IS '電子サイン日ファイル識別キー'
/
COMMENT ON COLUMN ED1026T_TBL.DNSH_SIGN_NM_FILE_SHKBTS_KEY IS '電子サイン氏名ファイル識別キー'
/
COMMENT ON COLUMN ED1026T_TBL.DENSHI_SIGN_SHOMEI_YMD IS '電子サイン署名年月日'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_ICHJ_HZNZM_FLG_1 IS '工事完了検査表詳細一時保存済フラグ１'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_TOROKUZUMI_FLG_1 IS '工事完了検査表詳細登録済フラグ１'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_ICHJ_HZNZM_FLG_2 IS '工事完了検査表詳細一時保存済フラグ２'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_TOROKUZUMI_FLG_2 IS '工事完了検査表詳細登録済フラグ２'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_ICHJ_HZNZM_FLG_3 IS '工事完了検査表詳細一時保存済フラグ３'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_TOROKUZUMI_FLG_3 IS '工事完了検査表詳細登録済フラグ３'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_ICHJ_HZNZM_FLG_4 IS '工事完了検査表詳細一時保存済フラグ４'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_TOROKUZUMI_FLG_4 IS '工事完了検査表詳細登録済フラグ４'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_ICHJ_HZNZM_FLG_5 IS '工事完了検査表詳細一時保存済フラグ５'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_TOROKUZUMI_FLG_5 IS '工事完了検査表詳細登録済フラグ５'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_ICHJ_HZNZM_FLG_6 IS '工事完了検査表詳細一時保存済フラグ６'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_TOROKUZUMI_FLG_6 IS '工事完了検査表詳細登録済フラグ６'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_ICHJ_HZNZM_FLG_7 IS '工事完了検査表詳細一時保存済フラグ７'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_TOROKUZUMI_FLG_7 IS '工事完了検査表詳細登録済フラグ７'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_ICHJ_HZNZM_FLG_8 IS '工事完了検査表詳細一時保存済フラグ８'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_TOROKUZUMI_FLG_8 IS '工事完了検査表詳細登録済フラグ８'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_ICHJ_HZNZM_FLG_9 IS '工事完了検査表詳細一時保存済フラグ９'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_TOROKUZUMI_FLG_9 IS '工事完了検査表詳細登録済フラグ９'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_ICHJ_HZNZM_FLG_10 IS '工事完了検査表詳細一時保存済フラグ１０'
/
COMMENT ON COLUMN ED1026T_TBL.KJ_KRKSH_SS_TOROKUZUMI_FLG_10 IS '工事完了検査表詳細登録済フラグ１０'
/
COMMENT ON COLUMN ED1026T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1026T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1026T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1026T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1026T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1026T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1026T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1026T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1026T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1026T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1026T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1026T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1026T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1026T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
