/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1053M_TBL.sql
-- 物理名：ED1053M_TBL
-- 論理名：工事提出書類マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1053M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1053M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_TEISHUTSU_SHORUI_KBN  CHAR(1) NOT NULL --「工事提出書類区分」
	,KJ_TISHTS_SHRI_TKY_KISH_YMD  DATE NOT NULL --「工事提出書類適用開始年月日」
	,KJ_TISHTS_SHRI_TKY_SHRY_YMD  DATE NOT NULL --「工事提出書類適用終了年月日」
	,KOJI_TEISHUTSU_SHORUI_FILE_NM  VARCHAR2(500) --「工事提出書類ファイル名称」
	,KJ_TISHTS_SHRI_STSMI_NAIYO  VARCHAR2(100) --「工事提出書類説明内容」
	,KOJI_TEISHUTSU_SHORUI_MUKO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事提出書類無効フラグ」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1053M_PK PRIMARY KEY(
	 KOJI_TEISHUTSU_SHORUI_KBN
	,  KAISHA_CD
	,  KJ_TISHTS_SHRI_TKY_KISH_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1053M_TBL IS '工事提出書類マスタ'
/

COMMENT ON COLUMN ED1053M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1053M_TBL.KOJI_TEISHUTSU_SHORUI_KBN IS '工事提出書類区分'
/
COMMENT ON COLUMN ED1053M_TBL.KJ_TISHTS_SHRI_TKY_KISH_YMD IS '工事提出書類適用開始年月日'
/
COMMENT ON COLUMN ED1053M_TBL.KJ_TISHTS_SHRI_TKY_SHRY_YMD IS '工事提出書類適用終了年月日'
/
COMMENT ON COLUMN ED1053M_TBL.KOJI_TEISHUTSU_SHORUI_FILE_NM IS '工事提出書類ファイル名称'
/
COMMENT ON COLUMN ED1053M_TBL.KJ_TISHTS_SHRI_STSMI_NAIYO IS '工事提出書類説明内容'
/
COMMENT ON COLUMN ED1053M_TBL.KOJI_TEISHUTSU_SHORUI_MUKO_FLG IS '工事提出書類無効フラグ'
/
COMMENT ON COLUMN ED1053M_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1053M_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1053M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1053M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1053M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1053M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1053M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1053M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1053M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1053M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1053M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1053M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1053M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1053M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
