/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1036T_TBL.sql
-- 物理名：ED1036T_TBL
-- 論理名：工事日報修正テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1036T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1036T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_SHIGOTO_SN  CHAR(14) NOT NULL --「工事仕事連番」
	,KOJI_KOTEI_SN  CHAR(14) NOT NULL --「工事工程連番」
	,TAISHOSAKI_CD  CHAR(9) NOT NULL --「対象先コード」
	,KOJI_NIPPO_SHUSEI_SN  CHAR(14) NOT NULL --「工事日報修正連番」
	,HOKOKUSHO_SHUSEI_RIYU_NAIYO  VARCHAR2(100) --「報告書修正理由内容」
	,SHUSEI_YMD  DATE --「修正年月日」
	,SHUSEI_TM  CHAR(4) --「修正時刻」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1036T_PK PRIMARY KEY(
	 KOJI_SHIGOTO_SN
	,  KOJI_KOTEI_SN
	,  TAISHOSAKI_CD
	,  KOJI_NIPPO_SHUSEI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1036T_TBL IS '工事日報修正テーブル'
/

COMMENT ON COLUMN ED1036T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1036T_TBL.KOJI_SHIGOTO_SN IS '工事仕事連番'
/
COMMENT ON COLUMN ED1036T_TBL.KOJI_KOTEI_SN IS '工事工程連番'
/
COMMENT ON COLUMN ED1036T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED1036T_TBL.KOJI_NIPPO_SHUSEI_SN IS '工事日報修正連番'
/
COMMENT ON COLUMN ED1036T_TBL.HOKOKUSHO_SHUSEI_RIYU_NAIYO IS '報告書修正理由内容'
/
COMMENT ON COLUMN ED1036T_TBL.SHUSEI_YMD IS '修正年月日'
/
COMMENT ON COLUMN ED1036T_TBL.SHUSEI_TM IS '修正時刻'
/
COMMENT ON COLUMN ED1036T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1036T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1036T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1036T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1036T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1036T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1036T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1036T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1036T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1036T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1036T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1036T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1036T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1036T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
