/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1016T_TBL.sql
-- 物理名：ED1016T_TBL
-- 論理名：セルフチェックテーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1016T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1016T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_SHIGOTO_SN  CHAR(14) NOT NULL --「工事仕事連番」
	,KOJI_KOTEI_SN  CHAR(14) NOT NULL --「工事工程連番」
	,TAISHOSAKI_CD  CHAR(9) NOT NULL --「対象先コード」
	,SELF_CHECK_SHURUI_KBN  CHAR(1) NOT NULL --「セルフチェック種類区分」
	,KOJI_TANTO_JIGYOSHO_CD  CHAR(6) --「工事担当事業所コード」
	,KOJI_KAISHI_YMD  DATE --「工事開始年月日」
	,KOJI_SHURYO_YMD  DATE --「工事終了年月日」
	,ALSOK_GEMBA_TACHIAI_TAISHO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫ現場立会対象フラグ」
	,GEMBA_TACHIAI_SHAIN_NM  VARCHAR2(60) --「現場立会社員氏名」
	,SELF_CHECK_JISSHI_YMD  DATE --「セルフチェック実施年月日」
	,KOJI_KBN  CHAR(1) NOT NULL --「工事区分」
	,KJ_KYRYK_KISH_TRHKSK_CD  CHAR(9) --「工事協力会社取引先コード」
	,KOJI_TORIHIKISAKI_BUSHO_CD  CHAR(4) --「工事取引先部署コード」
	,SGYIN_MIB_SKNNSHMI_NAIYO  VARCHAR2(100) --「作業員名簿責任者名内容」
	,KOJI_NINZU  NUMBER(9,0) DEFAULT '0' NOT NULL --「工事人数」
	,HONJITSU_ANZEN_SHIJI_CHUI_JIKO  VARCHAR2(100) --「本日安全指示注意事項」
	,SELF_CHECK_KOMOKU_VERSION_NO  CHAR(8) --「セルフチェック項目バージョン番号」
	,SELF_CHECK_KOMOKU_VERSION_YMD  DATE --「セルフチェック項目バージョン年月日」
	,SELF_CHECK_TEISHUTSUZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「セルフチェック提出済フラグ」
	,SELF_CHECK_TEISHUTSU_YMD  DATE --「セルフチェック提出年月日」
	,SELF_CHECK_1_BIKO  VARCHAR2(100) --「セルフチェック１備考」
	,SELF_CHECK_2_BIKO  VARCHAR2(100) --「セルフチェック２備考」
	,SELF_CHECK_3_BIKO  VARCHAR2(100) --「セルフチェック３備考」
	,SELF_CHECK_4_BIKO  VARCHAR2(100) --「セルフチェック４備考」
	,SELF_CHECK_5_BIKO  VARCHAR2(100) --「セルフチェック５備考」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1016T_PK PRIMARY KEY(
	 KOJI_SHIGOTO_SN
	,  KOJI_KOTEI_SN
	,  TAISHOSAKI_CD
	,  SELF_CHECK_SHURUI_KBN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1016T_TBL IS 'セルフチェックテーブル'
/

COMMENT ON COLUMN ED1016T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1016T_TBL.KOJI_SHIGOTO_SN IS '工事仕事連番'
/
COMMENT ON COLUMN ED1016T_TBL.KOJI_KOTEI_SN IS '工事工程連番'
/
COMMENT ON COLUMN ED1016T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED1016T_TBL.SELF_CHECK_SHURUI_KBN IS 'セルフチェック種類区分'
/
COMMENT ON COLUMN ED1016T_TBL.KOJI_TANTO_JIGYOSHO_CD IS '工事担当事業所コード'
/
COMMENT ON COLUMN ED1016T_TBL.KOJI_KAISHI_YMD IS '工事開始年月日'
/
COMMENT ON COLUMN ED1016T_TBL.KOJI_SHURYO_YMD IS '工事終了年月日'
/
COMMENT ON COLUMN ED1016T_TBL.ALSOK_GEMBA_TACHIAI_TAISHO_FLG IS 'ＡＬＳＯＫ現場立会対象フラグ'
/
COMMENT ON COLUMN ED1016T_TBL.GEMBA_TACHIAI_SHAIN_NM IS '現場立会社員氏名'
/
COMMENT ON COLUMN ED1016T_TBL.SELF_CHECK_JISSHI_YMD IS 'セルフチェック実施年月日'
/
COMMENT ON COLUMN ED1016T_TBL.KOJI_KBN IS '工事区分'
/
COMMENT ON COLUMN ED1016T_TBL.KJ_KYRYK_KISH_TRHKSK_CD IS '工事協力会社取引先コード'
/
COMMENT ON COLUMN ED1016T_TBL.KOJI_TORIHIKISAKI_BUSHO_CD IS '工事取引先部署コード'
/
COMMENT ON COLUMN ED1016T_TBL.SGYIN_MIB_SKNNSHMI_NAIYO IS '作業員名簿責任者名内容'
/
COMMENT ON COLUMN ED1016T_TBL.KOJI_NINZU IS '工事人数'
/
COMMENT ON COLUMN ED1016T_TBL.HONJITSU_ANZEN_SHIJI_CHUI_JIKO IS '本日安全指示注意事項'
/
COMMENT ON COLUMN ED1016T_TBL.SELF_CHECK_KOMOKU_VERSION_NO IS 'セルフチェック項目バージョン番号'
/
COMMENT ON COLUMN ED1016T_TBL.SELF_CHECK_KOMOKU_VERSION_YMD IS 'セルフチェック項目バージョン年月日'
/
COMMENT ON COLUMN ED1016T_TBL.SELF_CHECK_TEISHUTSUZUMI_FLG IS 'セルフチェック提出済フラグ'
/
COMMENT ON COLUMN ED1016T_TBL.SELF_CHECK_TEISHUTSU_YMD IS 'セルフチェック提出年月日'
/
COMMENT ON COLUMN ED1016T_TBL.SELF_CHECK_1_BIKO IS 'セルフチェック１備考'
/
COMMENT ON COLUMN ED1016T_TBL.SELF_CHECK_2_BIKO IS 'セルフチェック２備考'
/
COMMENT ON COLUMN ED1016T_TBL.SELF_CHECK_3_BIKO IS 'セルフチェック３備考'
/
COMMENT ON COLUMN ED1016T_TBL.SELF_CHECK_4_BIKO IS 'セルフチェック４備考'
/
COMMENT ON COLUMN ED1016T_TBL.SELF_CHECK_5_BIKO IS 'セルフチェック５備考'
/
COMMENT ON COLUMN ED1016T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1016T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1016T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1016T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1016T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1016T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1016T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1016T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1016T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1016T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1016T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1016T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1016T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1016T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
