/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1075T_TBL.sql
-- 物理名：ED1075T_TBL
-- 論理名：工事完了検査報告詳細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1075T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1075T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_KANRYO_KENSA_YOYAKU_NO  CHAR(16) NOT NULL --「工事完了検査予約番号」
	,KOJI_KANRYO_KENSA_YOYAKU_SN  NUMBER(1,0) DEFAULT '0' NOT NULL --「工事完了検査予約連番」
	,KANRYO_KENSA_HOKOKU_SHOSAI_SN  CHAR(1) NOT NULL --「完了検査報告詳細連番」
	,KIKI_SHUBETSU_KBN  CHAR(1) NOT NULL --「機器種別区分」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,SONOTA_JIKO_HOKI_NM  VARCHAR2(20) --「その他事項補記名称」
	,KANRYO_KENSA_MIJISSHI_JIKO_KBN  CHAR(1) NOT NULL --「完了検査未実施事項区分」
	,JIKO_HOKI_BIKO  VARCHAR2(20) --「事項補記備考」
	,SHIJI_YMD  DATE --「指示年月日」
	,SHIJISHA_NM  VARCHAR2(60) --「指示者氏名」
	,SHIJI_NAIYO  VARCHAR2(20) --「指示内容」
	,KENSA_YMD  DATE --「検査年月日」
	,KENSASHA_NM  VARCHAR2(60) --「検査者氏名」
	,SADO_SHIKEN_NAIYO  VARCHAR2(20) --「作動試験内容」
	,KENSAHYO_TSUIKI_YMD  DATE --「検査表追記年月日」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1075T_PK PRIMARY KEY(
	 KOJI_KANRYO_KENSA_YOYAKU_NO
	,  KOJI_KANRYO_KENSA_YOYAKU_SN
	,  KANRYO_KENSA_HOKOKU_SHOSAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1075T_TBL IS '工事完了検査報告詳細テーブル'
/

COMMENT ON COLUMN ED1075T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1075T_TBL.KOJI_KANRYO_KENSA_YOYAKU_NO IS '工事完了検査予約番号'
/
COMMENT ON COLUMN ED1075T_TBL.KOJI_KANRYO_KENSA_YOYAKU_SN IS '工事完了検査予約連番'
/
COMMENT ON COLUMN ED1075T_TBL.KANRYO_KENSA_HOKOKU_SHOSAI_SN IS '完了検査報告詳細連番'
/
COMMENT ON COLUMN ED1075T_TBL.KIKI_SHUBETSU_KBN IS '機器種別区分'
/
COMMENT ON COLUMN ED1075T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED1075T_TBL.SONOTA_JIKO_HOKI_NM IS 'その他事項補記名称'
/
COMMENT ON COLUMN ED1075T_TBL.KANRYO_KENSA_MIJISSHI_JIKO_KBN IS '完了検査未実施事項区分'
/
COMMENT ON COLUMN ED1075T_TBL.JIKO_HOKI_BIKO IS '事項補記備考'
/
COMMENT ON COLUMN ED1075T_TBL.SHIJI_YMD IS '指示年月日'
/
COMMENT ON COLUMN ED1075T_TBL.SHIJISHA_NM IS '指示者氏名'
/
COMMENT ON COLUMN ED1075T_TBL.SHIJI_NAIYO IS '指示内容'
/
COMMENT ON COLUMN ED1075T_TBL.KENSA_YMD IS '検査年月日'
/
COMMENT ON COLUMN ED1075T_TBL.KENSASHA_NM IS '検査者氏名'
/
COMMENT ON COLUMN ED1075T_TBL.SADO_SHIKEN_NAIYO IS '作動試験内容'
/
COMMENT ON COLUMN ED1075T_TBL.KENSAHYO_TSUIKI_YMD IS '検査表追記年月日'
/
COMMENT ON COLUMN ED1075T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1075T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1075T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1075T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1075T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1075T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1075T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1075T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1075T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1075T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1075T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1075T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1075T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1075T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
