/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1027T_TBL.sql
-- 物理名：ED1027T_TBL
-- 論理名：警報機器テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1027T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1027T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TAISHOSAKI_CD  CHAR(9) NOT NULL --「対象先コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,KEIHO_DEMPYO_NO  CHAR(14) NOT NULL --「警報伝票番号」
	,KEIHO_KIKI_SN  CHAR(14) NOT NULL --「警報機器連番」
	,JIGYO_SEGMENT_CD  CHAR(3) --「事業セグメントコード」
	,SHOCHI_KBN  CHAR(1) NOT NULL --「処置区分」
	,ZOKUSEI_KBN  CHAR(1) NOT NULL --「属性区分」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,CHINTAI_BAIKYAKU_TASHAHIN_KBN  CHAR(1) NOT NULL --「賃貸売却他社品区分」
	,SHIMPIN_KBN  CHAR(1) NOT NULL --「新品区分」
	,KEIHO_KIKI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「警報機器数量」
	,HOSHU_JUCHU_KEIYAKU_NO  CHAR(15) --「保守受注契約番号」
	,TEKKYO_YMD  DATE --「撤去年月日」
	,TAISHOSAKI_SHOSAI_TOKKI_JIKO  VARCHAR2(300) --「対象先詳細特記事項」
	,SEIZO_NO  VARCHAR2(30) --「製造番号」
	,KEIHO_KIKI_TEN_KEY_NO  CHAR(16) --「警報機器テンキー番号」
	,KEIHO_KIKI_TIMER_SEIGYOCHI  NUMBER(9,0) DEFAULT '0' NOT NULL --「警報機器タイマー制御値」
	,OYA_CENTER_SOCHI_HIMMEI_CD  CHAR(8) --「親センタ装置品名コード」
	,KEIHO_KIKI_TOKKI_JIKO  VARCHAR2(20) --「警報機器特記事項」
	,KANREN_JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「関連受注契約番号」
	,HOZEN_KEIHO_KBN  CHAR(1) NOT NULL --「保全警報区分」
	,DEMPYO_YMD  DATE NOT NULL --「伝票年月日」
	,HENKYAKU_KIBO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「返却希望数量」
	,TEKKYOHIN_HAISO_YOTEI_YMD  DATE --「撤去品配送予定年月日」
	,SHUKEI_KEIHO_KIKI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「集計警報機器数量」
	,TEKKYOHIN_KANRI_ID  CHAR(16) --「撤去品管理ＩＤ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1027T_PK PRIMARY KEY(
	 TAISHOSAKI_CD
	,  JUCHU_KEIYAKU_NO
	,  KEIHO_KIKI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1027T_TBL IS '警報機器テーブル'
/

COMMENT ON COLUMN ED1027T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1027T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED1027T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED1027T_TBL.KEIHO_DEMPYO_NO IS '警報伝票番号'
/
COMMENT ON COLUMN ED1027T_TBL.KEIHO_KIKI_SN IS '警報機器連番'
/
COMMENT ON COLUMN ED1027T_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED1027T_TBL.SHOCHI_KBN IS '処置区分'
/
COMMENT ON COLUMN ED1027T_TBL.ZOKUSEI_KBN IS '属性区分'
/
COMMENT ON COLUMN ED1027T_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED1027T_TBL.CHINTAI_BAIKYAKU_TASHAHIN_KBN IS '賃貸売却他社品区分'
/
COMMENT ON COLUMN ED1027T_TBL.SHIMPIN_KBN IS '新品区分'
/
COMMENT ON COLUMN ED1027T_TBL.KEIHO_KIKI_SURYO IS '警報機器数量'
/
COMMENT ON COLUMN ED1027T_TBL.HOSHU_JUCHU_KEIYAKU_NO IS '保守受注契約番号'
/
COMMENT ON COLUMN ED1027T_TBL.TEKKYO_YMD IS '撤去年月日'
/
COMMENT ON COLUMN ED1027T_TBL.TAISHOSAKI_SHOSAI_TOKKI_JIKO IS '対象先詳細特記事項'
/
COMMENT ON COLUMN ED1027T_TBL.SEIZO_NO IS '製造番号'
/
COMMENT ON COLUMN ED1027T_TBL.KEIHO_KIKI_TEN_KEY_NO IS '警報機器テンキー番号'
/
COMMENT ON COLUMN ED1027T_TBL.KEIHO_KIKI_TIMER_SEIGYOCHI IS '警報機器タイマー制御値'
/
COMMENT ON COLUMN ED1027T_TBL.OYA_CENTER_SOCHI_HIMMEI_CD IS '親センタ装置品名コード'
/
COMMENT ON COLUMN ED1027T_TBL.KEIHO_KIKI_TOKKI_JIKO IS '警報機器特記事項'
/
COMMENT ON COLUMN ED1027T_TBL.KANREN_JUCHU_KEIYAKU_NO IS '関連受注契約番号'
/
COMMENT ON COLUMN ED1027T_TBL.HOZEN_KEIHO_KBN IS '保全警報区分'
/
COMMENT ON COLUMN ED1027T_TBL.DEMPYO_YMD IS '伝票年月日'
/
COMMENT ON COLUMN ED1027T_TBL.HENKYAKU_KIBO_SURYO IS '返却希望数量'
/
COMMENT ON COLUMN ED1027T_TBL.TEKKYOHIN_HAISO_YOTEI_YMD IS '撤去品配送予定年月日'
/
COMMENT ON COLUMN ED1027T_TBL.SHUKEI_KEIHO_KIKI_SURYO IS '集計警報機器数量'
/
COMMENT ON COLUMN ED1027T_TBL.TEKKYOHIN_KANRI_ID IS '撤去品管理ＩＤ'
/
COMMENT ON COLUMN ED1027T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1027T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1027T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1027T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1027T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1027T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1027T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1027T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1027T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1027T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1027T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1027T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
