/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1056T_TBL.sql
-- 物理名：ED1056T_TBL
-- 論理名：工事協力会社請求明細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1056T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1056T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_SEIKYUSHO_NO  VARCHAR2(22) NOT NULL --「工事請求書番号」
	,KJ_KYRYK_KISH_SIKY_MISI_SN  CHAR(14) NOT NULL --「工事協力会社請求明細連番」
	,HATCHU_HOHO_KBN  CHAR(1) DEFAULT '1' NOT NULL --「発注方法区分」
	,KOJI_CHUMONSHO_NO  CHAR(13) --「工事注文書番号」
	,KOJI_CHUMONSHO_MEISAI_SN  CHAR(14) --「工事注文書明細連番」
	,KOJI_CHUMONSHO_KAIHAN_NO  CHAR(1) --「工事注文書改版番号」
	,KOJI_TANTO_JIGYOSHO_CD  CHAR(6) --「工事担当事業所コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,KOJI_CHUMON_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「工事注文金額」
	,ITAKU_KENSAHI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「委託検査費金額」
	,KOJI_CHUMON_SHOHIZEI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「工事注文消費税金額」
	,KOJI_CHUMON_SHOHIZEI_KBN  CHAR(1) NOT NULL --「工事注文消費税区分」
	,KOJI_CHUMON_SHOHI_ZEIRITSU_CD  CHAR(2) --「工事注文消費税率コード」
	,KOJI_CHUMON_ZEIKOMI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「工事注文税込金額」
	,KOJI_CHUMON_DT  TIMESTAMP --「工事注文日時」
	,KOJI_CHUMONUKE_DT  TIMESTAMP --「工事注文請日時」
	,KANRYO_KENSA_SHONINZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「完了検査承認済フラグ」
	,KOJI_NAIYO  VARCHAR2(100) --「工事内容」
	,KOKI_CHAKKO_D  DATE --「工期着工日」
	,KOKI_HIKIWATASHI_D  DATE --「工期引渡日」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1056T_PK PRIMARY KEY(
	 KOJI_SEIKYUSHO_NO
	,  KJ_KYRYK_KISH_SIKY_MISI_SN
	,  HATCHU_HOHO_KBN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1056T_TBL IS '工事協力会社請求明細テーブル'
/

COMMENT ON COLUMN ED1056T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1056T_TBL.KOJI_SEIKYUSHO_NO IS '工事請求書番号'
/
COMMENT ON COLUMN ED1056T_TBL.KJ_KYRYK_KISH_SIKY_MISI_SN IS '工事協力会社請求明細連番'
/
COMMENT ON COLUMN ED1056T_TBL.HATCHU_HOHO_KBN IS '発注方法区分'
/
COMMENT ON COLUMN ED1056T_TBL.KOJI_CHUMONSHO_NO IS '工事注文書番号'
/
COMMENT ON COLUMN ED1056T_TBL.KOJI_CHUMONSHO_MEISAI_SN IS '工事注文書明細連番'
/
COMMENT ON COLUMN ED1056T_TBL.KOJI_CHUMONSHO_KAIHAN_NO IS '工事注文書改版番号'
/
COMMENT ON COLUMN ED1056T_TBL.KOJI_TANTO_JIGYOSHO_CD IS '工事担当事業所コード'
/
COMMENT ON COLUMN ED1056T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED1056T_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED1056T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED1056T_TBL.KOJI_CHUMON_AMT IS '工事注文金額'
/
COMMENT ON COLUMN ED1056T_TBL.ITAKU_KENSAHI_AMT IS '委託検査費金額'
/
COMMENT ON COLUMN ED1056T_TBL.KOJI_CHUMON_SHOHIZEI_AMT IS '工事注文消費税金額'
/
COMMENT ON COLUMN ED1056T_TBL.KOJI_CHUMON_SHOHIZEI_KBN IS '工事注文消費税区分'
/
COMMENT ON COLUMN ED1056T_TBL.KOJI_CHUMON_SHOHI_ZEIRITSU_CD IS '工事注文消費税率コード'
/
COMMENT ON COLUMN ED1056T_TBL.KOJI_CHUMON_ZEIKOMI_AMT IS '工事注文税込金額'
/
COMMENT ON COLUMN ED1056T_TBL.KOJI_CHUMON_DT IS '工事注文日時'
/
COMMENT ON COLUMN ED1056T_TBL.KOJI_CHUMONUKE_DT IS '工事注文請日時'
/
COMMENT ON COLUMN ED1056T_TBL.KANRYO_KENSA_SHONINZUMI_FLG IS '完了検査承認済フラグ'
/
COMMENT ON COLUMN ED1056T_TBL.KOJI_NAIYO IS '工事内容'
/
COMMENT ON COLUMN ED1056T_TBL.KOKI_CHAKKO_D IS '工期着工日'
/
COMMENT ON COLUMN ED1056T_TBL.KOKI_HIKIWATASHI_D IS '工期引渡日'
/
COMMENT ON COLUMN ED1056T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1056T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1056T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1056T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1056T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1056T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1056T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1056T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1056T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1056T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1056T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1056T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1056T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1056T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
