/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1066T_TBL.sql
-- 物理名：ED1066T_TBL
-- 論理名：工事完了検査信号受信試験テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1066T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1066T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_KANRYO_KENSA_NO  CHAR(16) NOT NULL --「工事完了検査番号」
	,KOJI_KANRYO_KENSA_RIREKI_NO  CHAR(2) NOT NULL --「工事完了検査履歴番号」
	,SHINGO_JUSHIN_SHIKEN_SN  CHAR(3) NOT NULL --「信号受信試験連番」
	,SHINGO_JUSHIN_SHIKEN_HYOJI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「信号受信試験表示順」
	,SUB_SHINGO_ADDRESS_NM  VARCHAR2(6) --「サブ信号アドレス名称」
	,TANSHI_ADDRESS_NM  VARCHAR2(12) --「端子アドレス名称」
	,SHINGO_SHUBETSU_NO  VARCHAR2(4) --「信号種別番号」
	,SHINGO_JUSHIN_SHIKEN_NM  VARCHAR2(15) --「信号受信試験名称」
	,JUSHIN_LEVEL_KBN  CHAR(1) NOT NULL --「受信レベル区分」
	,GC_SHINGO_JUSHIN_KBN  CHAR(1) NOT NULL --「ＧＣ信号受信区分」
	,SHOKI_SETSUZOKU_SENSOR_NO  VARCHAR2(9) --「初期接続センサー番号」
	,SETSUZOKU_SENSOR_NO_1  VARCHAR2(9) --「接続センサー番号１」
	,SETSUZOKU_SENSOR_JOTAI_KBN_1  CHAR(1) DEFAULT '0' NOT NULL --「接続センサー状態区分１」
	,SETSUZOKU_SENSOR_NO_2  VARCHAR2(9) --「接続センサー番号２」
	,SETSUZOKU_SENSOR_JOTAI_KBN_2  CHAR(1) DEFAULT '0' NOT NULL --「接続センサー状態区分２」
	,SETSUZOKU_SENSOR_NO_3  VARCHAR2(9) --「接続センサー番号３」
	,SETSUZOKU_SENSOR_JOTAI_KBN_3  CHAR(1) DEFAULT '0' NOT NULL --「接続センサー状態区分３」
	,SETSUZOKU_SENSOR_NO_4  VARCHAR2(9) --「接続センサー番号４」
	,SETSUZOKU_SENSOR_JOTAI_KBN_4  CHAR(1) DEFAULT '0' NOT NULL --「接続センサー状態区分４」
	,SETSUZOKU_SENSOR_NO_5  VARCHAR2(9) --「接続センサー番号５」
	,SETSUZOKU_SENSOR_JOTAI_KBN_5  CHAR(1) DEFAULT '0' NOT NULL --「接続センサー状態区分５」
	,SETSUZOKU_SENSOR_NO_6  VARCHAR2(9) --「接続センサー番号６」
	,SETSUZOKU_SENSOR_JOTAI_KBN_6  CHAR(1) DEFAULT '0' NOT NULL --「接続センサー状態区分６」
	,SETSUZOKU_SENSOR_NO_7  VARCHAR2(9) --「接続センサー番号７」
	,SETSUZOKU_SENSOR_JOTAI_KBN_7  CHAR(1) DEFAULT '0' NOT NULL --「接続センサー状態区分７」
	,SETSUZOKU_SENSOR_NO_8  VARCHAR2(9) --「接続センサー番号８」
	,SETSUZOKU_SENSOR_JOTAI_KBN_8  CHAR(1) DEFAULT '0' NOT NULL --「接続センサー状態区分８」
	,SETSUZOKU_SENSOR_NO_9  VARCHAR2(9) --「接続センサー番号９」
	,SETSUZOKU_SENSOR_JOTAI_KBN_9  CHAR(1) DEFAULT '0' NOT NULL --「接続センサー状態区分９」
	,SETSUZOKU_SENSOR_NO_10  VARCHAR2(9) --「接続センサー番号１０」
	,SETSUZOKU_SENSOR_JOTAI_KBN_10  CHAR(1) DEFAULT '0' NOT NULL --「接続センサー状態区分１０」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1066T_PK PRIMARY KEY(
	 KOJI_KANRYO_KENSA_NO
	,  KOJI_KANRYO_KENSA_RIREKI_NO
	,  SHINGO_JUSHIN_SHIKEN_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1066T_TBL IS '工事完了検査信号受信試験テーブル'
/

COMMENT ON COLUMN ED1066T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1066T_TBL.KOJI_KANRYO_KENSA_NO IS '工事完了検査番号'
/
COMMENT ON COLUMN ED1066T_TBL.KOJI_KANRYO_KENSA_RIREKI_NO IS '工事完了検査履歴番号'
/
COMMENT ON COLUMN ED1066T_TBL.SHINGO_JUSHIN_SHIKEN_SN IS '信号受信試験連番'
/
COMMENT ON COLUMN ED1066T_TBL.SHINGO_JUSHIN_SHIKEN_HYOJI_JUN IS '信号受信試験表示順'
/
COMMENT ON COLUMN ED1066T_TBL.SUB_SHINGO_ADDRESS_NM IS 'サブ信号アドレス名称'
/
COMMENT ON COLUMN ED1066T_TBL.TANSHI_ADDRESS_NM IS '端子アドレス名称'
/
COMMENT ON COLUMN ED1066T_TBL.SHINGO_SHUBETSU_NO IS '信号種別番号'
/
COMMENT ON COLUMN ED1066T_TBL.SHINGO_JUSHIN_SHIKEN_NM IS '信号受信試験名称'
/
COMMENT ON COLUMN ED1066T_TBL.JUSHIN_LEVEL_KBN IS '受信レベル区分'
/
COMMENT ON COLUMN ED1066T_TBL.GC_SHINGO_JUSHIN_KBN IS 'ＧＣ信号受信区分'
/
COMMENT ON COLUMN ED1066T_TBL.SHOKI_SETSUZOKU_SENSOR_NO IS '初期接続センサー番号'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_NO_1 IS '接続センサー番号１'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_JOTAI_KBN_1 IS '接続センサー状態区分１'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_NO_2 IS '接続センサー番号２'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_JOTAI_KBN_2 IS '接続センサー状態区分２'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_NO_3 IS '接続センサー番号３'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_JOTAI_KBN_3 IS '接続センサー状態区分３'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_NO_4 IS '接続センサー番号４'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_JOTAI_KBN_4 IS '接続センサー状態区分４'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_NO_5 IS '接続センサー番号５'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_JOTAI_KBN_5 IS '接続センサー状態区分５'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_NO_6 IS '接続センサー番号６'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_JOTAI_KBN_6 IS '接続センサー状態区分６'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_NO_7 IS '接続センサー番号７'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_JOTAI_KBN_7 IS '接続センサー状態区分７'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_NO_8 IS '接続センサー番号８'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_JOTAI_KBN_8 IS '接続センサー状態区分８'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_NO_9 IS '接続センサー番号９'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_JOTAI_KBN_9 IS '接続センサー状態区分９'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_NO_10 IS '接続センサー番号１０'
/
COMMENT ON COLUMN ED1066T_TBL.SETSUZOKU_SENSOR_JOTAI_KBN_10 IS '接続センサー状態区分１０'
/
COMMENT ON COLUMN ED1066T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1066T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1066T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1066T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1066T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1066T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1066T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1066T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1066T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1066T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1066T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1066T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1066T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1066T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
