/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1028T_TBL.sql
-- 物理名：ED1028T_TBL
-- 論理名：警報機器明細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1028T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1028T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TAISHOSAKI_CD  CHAR(9) NOT NULL --「対象先コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,KEIHO_DEMPYO_NO  CHAR(14) NOT NULL --「警報伝票番号」
	,KEIHO_KIKI_SN  CHAR(14) NOT NULL --「警報機器連番」
	,KEIHO_KIKI_MEISAI_SN  CHAR(14) NOT NULL --「警報機器明細連番」
	,KOTAI_NO  VARCHAR2(30) --「個体番号」
	,KOKANHIN_KOKAN_HITSUYOSEI_KBN  CHAR(1) NOT NULL --「交換品交換必要性区分」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,KEIHO_KIKI_FUZOKUHIN_KOKAN_YMD  DATE --「警報機器付属品交換年月日」
	,KIH_KK_FZKHN_KKN_KNKK_TSUKISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「警報機器付属品交換間隔月数」
	,KIH_KK_FZKHN_KKN_YTI_YMD  DATE --「警報機器付属品交換予定年月日」
	,KEIHO_KIKI_FUZOKUHIN_BIKO  VARCHAR2(30) --「警報機器付属品備考」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1028T_PK PRIMARY KEY(
	 TAISHOSAKI_CD
	,  JUCHU_KEIYAKU_NO
	,  KEIHO_KIKI_SN
	,  KEIHO_KIKI_MEISAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1028T_TBL IS '警報機器明細テーブル'
/

COMMENT ON COLUMN ED1028T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1028T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED1028T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED1028T_TBL.KEIHO_DEMPYO_NO IS '警報伝票番号'
/
COMMENT ON COLUMN ED1028T_TBL.KEIHO_KIKI_SN IS '警報機器連番'
/
COMMENT ON COLUMN ED1028T_TBL.KEIHO_KIKI_MEISAI_SN IS '警報機器明細連番'
/
COMMENT ON COLUMN ED1028T_TBL.KOTAI_NO IS '個体番号'
/
COMMENT ON COLUMN ED1028T_TBL.KOKANHIN_KOKAN_HITSUYOSEI_KBN IS '交換品交換必要性区分'
/
COMMENT ON COLUMN ED1028T_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED1028T_TBL.KEIHO_KIKI_FUZOKUHIN_KOKAN_YMD IS '警報機器付属品交換年月日'
/
COMMENT ON COLUMN ED1028T_TBL.KIH_KK_FZKHN_KKN_KNKK_TSUKISU IS '警報機器付属品交換間隔月数'
/
COMMENT ON COLUMN ED1028T_TBL.KIH_KK_FZKHN_KKN_YTI_YMD IS '警報機器付属品交換予定年月日'
/
COMMENT ON COLUMN ED1028T_TBL.KEIHO_KIKI_FUZOKUHIN_BIKO IS '警報機器付属品備考'
/
COMMENT ON COLUMN ED1028T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1028T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1028T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1028T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1028T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1028T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1028T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1028T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1028T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1028T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1028T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1028T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
