/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1064T_TBL.sql
-- 物理名：ED1064T_TBL
-- 論理名：工事完了検査出入管理テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1064T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1064T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_KANRYO_KENSA_NO  CHAR(16) NOT NULL --「工事完了検査番号」
	,KOJI_KANRYO_KENSA_RIREKI_NO  CHAR(2) NOT NULL --「工事完了検査履歴番号」
	,SHUTSUNYU_KANRI_SN  CHAR(2) NOT NULL --「出入管理連番」
	,SHUTSUNYU_KANRI_HYOJI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「出入管理表示順」
	,YOTO_KBN  CHAR(1) NOT NULL --「用途区分」
	,SONOTA_YOTO_NM  VARCHAR2(10) --「その他用途名称」
	,SOCHI_SETSUBI_SHIKEN_NAIYO  VARCHAR2(15) --「装置設備試験内容」
	,KEKKA_KBN  CHAR(1) NOT NULL --「結果区分」
	,SETSUZOKU_TANSHI_NM  VARCHAR2(10) --「接続端子名称」
	,SETSUZOKU_BASHO_NM  VARCHAR2(15) --「接続場所名称」
	,SIGY_SHNG_SHTSRYK_NAIYO_KBN  CHAR(1) NOT NULL --「制御信号出力内容区分」
	,SIG_SNG_STRK_NAIYO_SSI_KBN  CHAR(1) NOT NULL --「制御信号出力内容詳細区分」
	,SIG_SNG_STRK_NAIYO_SSI_BIKO  VARCHAR2(20) --「制御信号出力内容詳細備考」
	,NUKITORI_KINSHIFUDA_JOTAI_KBN  CHAR(1) NOT NULL --「抜取禁止札状態区分」
	,SHASHIN_JOTAI_KBN  CHAR(1) NOT NULL --「写真状態区分」
	,LOG_KBN  CHAR(1) NOT NULL --「ログ区分」
	,RENDO_JOKEN_SHIKEN_HOHOTO_BIKO  VARCHAR2(60) --「連動条件試験方法等備考」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1064T_PK PRIMARY KEY(
	 KOJI_KANRYO_KENSA_NO
	,  KOJI_KANRYO_KENSA_RIREKI_NO
	,  SHUTSUNYU_KANRI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1064T_TBL IS '工事完了検査出入管理テーブル'
/

COMMENT ON COLUMN ED1064T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1064T_TBL.KOJI_KANRYO_KENSA_NO IS '工事完了検査番号'
/
COMMENT ON COLUMN ED1064T_TBL.KOJI_KANRYO_KENSA_RIREKI_NO IS '工事完了検査履歴番号'
/
COMMENT ON COLUMN ED1064T_TBL.SHUTSUNYU_KANRI_SN IS '出入管理連番'
/
COMMENT ON COLUMN ED1064T_TBL.SHUTSUNYU_KANRI_HYOJI_JUN IS '出入管理表示順'
/
COMMENT ON COLUMN ED1064T_TBL.YOTO_KBN IS '用途区分'
/
COMMENT ON COLUMN ED1064T_TBL.SONOTA_YOTO_NM IS 'その他用途名称'
/
COMMENT ON COLUMN ED1064T_TBL.SOCHI_SETSUBI_SHIKEN_NAIYO IS '装置設備試験内容'
/
COMMENT ON COLUMN ED1064T_TBL.KEKKA_KBN IS '結果区分'
/
COMMENT ON COLUMN ED1064T_TBL.SETSUZOKU_TANSHI_NM IS '接続端子名称'
/
COMMENT ON COLUMN ED1064T_TBL.SETSUZOKU_BASHO_NM IS '接続場所名称'
/
COMMENT ON COLUMN ED1064T_TBL.SIGY_SHNG_SHTSRYK_NAIYO_KBN IS '制御信号出力内容区分'
/
COMMENT ON COLUMN ED1064T_TBL.SIG_SNG_STRK_NAIYO_SSI_KBN IS '制御信号出力内容詳細区分'
/
COMMENT ON COLUMN ED1064T_TBL.SIG_SNG_STRK_NAIYO_SSI_BIKO IS '制御信号出力内容詳細備考'
/
COMMENT ON COLUMN ED1064T_TBL.NUKITORI_KINSHIFUDA_JOTAI_KBN IS '抜取禁止札状態区分'
/
COMMENT ON COLUMN ED1064T_TBL.SHASHIN_JOTAI_KBN IS '写真状態区分'
/
COMMENT ON COLUMN ED1064T_TBL.LOG_KBN IS 'ログ区分'
/
COMMENT ON COLUMN ED1064T_TBL.RENDO_JOKEN_SHIKEN_HOHOTO_BIKO IS '連動条件試験方法等備考'
/
COMMENT ON COLUMN ED1064T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1064T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1064T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1064T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1064T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1064T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1064T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1064T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1064T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1064T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1064T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1064T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1064T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1064T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
