/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1074T_TBL.sql
-- 物理名：ED1074T_TBL
-- 論理名：工事完了検査画像センサーテーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1074T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1074T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_KANRYO_KENSA_NO  CHAR(16) NOT NULL --「工事完了検査番号」
	,KOJI_KANRYO_KENSA_RIREKI_NO  CHAR(2) NOT NULL --「工事完了検査履歴番号」
	,GAZO_SENSOR_SN  CHAR(2) NOT NULL --「画像センサー連番」
	,GAZO_SENSOR_HYOJI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「画像センサー表示順」
	,GAZO_SENSOR_CAMERA_NO  VARCHAR2(11) --「画像センサーカメラ番号」
	,GAZO_SENSOR_NM  VARCHAR2(15) --「画像センサー名称」
	,GAKAKU_KBN  CHAR(1) NOT NULL --「画角区分」
	,SETCHI_BASHO_KBN  CHAR(1) NOT NULL --「設置場所区分」
	,GAZO_JUSHIN_KEKKA_KBN  CHAR(1) NOT NULL --「画像受信結果区分」
	,GAZO_HOZON_KEKKA_KBN  CHAR(1) NOT NULL --「画像保存結果区分」
	,GAZO_SENSOR_BIKO  VARCHAR2(20) --「画像センサー備考」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1074T_PK PRIMARY KEY(
	 KOJI_KANRYO_KENSA_NO
	,  KOJI_KANRYO_KENSA_RIREKI_NO
	,  GAZO_SENSOR_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1074T_TBL IS '工事完了検査画像センサーテーブル'
/

COMMENT ON COLUMN ED1074T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1074T_TBL.KOJI_KANRYO_KENSA_NO IS '工事完了検査番号'
/
COMMENT ON COLUMN ED1074T_TBL.KOJI_KANRYO_KENSA_RIREKI_NO IS '工事完了検査履歴番号'
/
COMMENT ON COLUMN ED1074T_TBL.GAZO_SENSOR_SN IS '画像センサー連番'
/
COMMENT ON COLUMN ED1074T_TBL.GAZO_SENSOR_HYOJI_JUN IS '画像センサー表示順'
/
COMMENT ON COLUMN ED1074T_TBL.GAZO_SENSOR_CAMERA_NO IS '画像センサーカメラ番号'
/
COMMENT ON COLUMN ED1074T_TBL.GAZO_SENSOR_NM IS '画像センサー名称'
/
COMMENT ON COLUMN ED1074T_TBL.GAKAKU_KBN IS '画角区分'
/
COMMENT ON COLUMN ED1074T_TBL.SETCHI_BASHO_KBN IS '設置場所区分'
/
COMMENT ON COLUMN ED1074T_TBL.GAZO_JUSHIN_KEKKA_KBN IS '画像受信結果区分'
/
COMMENT ON COLUMN ED1074T_TBL.GAZO_HOZON_KEKKA_KBN IS '画像保存結果区分'
/
COMMENT ON COLUMN ED1074T_TBL.GAZO_SENSOR_BIKO IS '画像センサー備考'
/
COMMENT ON COLUMN ED1074T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1074T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1074T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1074T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1074T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1074T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1074T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1074T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1074T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1074T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1074T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1074T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1074T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1074T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
