/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1041M_TBL.sql
-- 物理名：ED1041M_TBL
-- 論理名：工事協力会社班マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1041M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1041M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KOJI_KYORYOKU_KAISHA_HAN_CD  CHAR(9) NOT NULL --「工事協力会社班コード」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,KOJI_KYORYOKU_KAISHA_HAN_NM  VARCHAR2(20) --「工事協力会社班名称」
	,KJ_KYRYK_KISH_TRHKSK_CD  CHAR(9) --「工事協力会社取引先コード」
	,KOJI_TORIHIKISAKI_BUSHO_CD  CHAR(4) --「工事取引先部署コード」
	,KOJI_BLOCK_CD  CHAR(3) --「工事ブロックコード」
	,TANTO_JIGYOSHO_CD  CHAR(6) --「担当事業所コード」
	,SHOKUCHO_KOJI_JUJISHA_NO  CHAR(8) --「職長工事従事者番号」
	,KOJI_KYORYOKU_KAISHA_HAN_BIKO  VARCHAR2(100) --「工事協力会社班備考」
	,KJ_KYRYK_KISH_HN_YK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事協力会社班有効フラグ」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1041M_PK PRIMARY KEY(
	 KOJI_KYORYOKU_KAISHA_HAN_CD
	,  KAISHA_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1041M_TBL IS '工事協力会社班マスタ'
/

COMMENT ON COLUMN ED1041M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1041M_TBL.KOJI_KYORYOKU_KAISHA_HAN_CD IS '工事協力会社班コード'
/
COMMENT ON COLUMN ED1041M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED1041M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED1041M_TBL.KOJI_KYORYOKU_KAISHA_HAN_NM IS '工事協力会社班名称'
/
COMMENT ON COLUMN ED1041M_TBL.KJ_KYRYK_KISH_TRHKSK_CD IS '工事協力会社取引先コード'
/
COMMENT ON COLUMN ED1041M_TBL.KOJI_TORIHIKISAKI_BUSHO_CD IS '工事取引先部署コード'
/
COMMENT ON COLUMN ED1041M_TBL.KOJI_BLOCK_CD IS '工事ブロックコード'
/
COMMENT ON COLUMN ED1041M_TBL.TANTO_JIGYOSHO_CD IS '担当事業所コード'
/
COMMENT ON COLUMN ED1041M_TBL.SHOKUCHO_KOJI_JUJISHA_NO IS '職長工事従事者番号'
/
COMMENT ON COLUMN ED1041M_TBL.KOJI_KYORYOKU_KAISHA_HAN_BIKO IS '工事協力会社班備考'
/
COMMENT ON COLUMN ED1041M_TBL.KJ_KYRYK_KISH_HN_YK_FLG IS '工事協力会社班有効フラグ'
/
COMMENT ON COLUMN ED1041M_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1041M_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1041M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1041M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1041M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1041M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1041M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1041M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1041M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1041M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1041M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1041M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1041M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1041M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
