/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1543T_TBL.sql
-- 物理名：ED1543T_TBL
-- 論理名：調達売上テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1543T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1543T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,URIAGE_DEMPYO_NO  CHAR(17) NOT NULL --「売上伝票番号」
	,URIAGE_DEMPYONAI_SN  CHAR(14) NOT NULL --「売上伝票内連番」
	,AKAKURO_KBN  CHAR(1) NOT NULL --「赤黒区分」
	,SAISHIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「最新フラグ」
	,JIGYOSHO_CD  CHAR(6) --「事業所コード」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,JISSHI_JIGYOSHO_CD  CHAR(6) --「実施事業所コード」
	,URIAGE_TSUKEKAE_KBN  CHAR(1) NOT NULL --「売上付替区分」
	,URIAGE_TORIHIKI_KBN  CHAR(1) NOT NULL --「売上取引区分」
	,CHOKUSO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「直送フラグ」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,TOKUISAKI_TORIHIKISAKI_CD  CHAR(9) --「得意先取引先コード」
	,TKISK_TRHKSK_BSH_CD  CHAR(4) --「得意先取引先部署コード」
	,SHIIRESAKI_TORIHIKISAKI_CD  CHAR(9) --「仕入先取引先コード」
	,SHIRSK_TRHKSK_BSH_CD  CHAR(4) --「仕入先取引先部署コード」
	,NOHINSAKI_KBN  CHAR(1) --「納品先区分」
	,NOHINSAKI_TORIHIKISAKI_CD  CHAR(9) --「納品先取引先コード」
	,NHNSK_TRHKSK_BSH_CD  CHAR(4) --「納品先取引先部署コード」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,KIYKSK_TRHKSK_BSH_CD  CHAR(4) --「契約先取引先部署コード」
	,NOHINSAKI_JIGYOSHO_CD  CHAR(6) --「納品先事業所コード」
	,NOHINSAKI_SOKO_CD  CHAR(6) --「納品先倉庫コード」
	,SONOTA_NOHINSAKI_KN_NM  VARCHAR2(40) --「その他納品先カナ名称」
	,SONOTA_NOHINSAKI_NM  VARCHAR2(30) --「その他納品先名称」
	,SONOTA_NOHINSAKI_DENWA_NO  VARCHAR2(20) --「その他納品先電話番号」
	,SONOTA_NOHINSAKI_YUBIN_NO  CHAR(7) --「その他納品先郵便番号」
	,SONOTA_NOHINSAKI_JUSHO_1  VARCHAR2(60) --「その他納品先住所１」
	,SONOTA_NOHINSAKI_JUSHO_2  VARCHAR2(60) --「その他納品先住所２」
	,SONOTA_NOHINSAKI_BUSHO_NM  VARCHAR2(40) --「その他納品先部署名称」
	,SONOTA_NOHINSAKI_TANTO_NM  VARCHAR2(30) --「その他納品先担当名称」
	,PICKING_KANRI_NO  CHAR(10) --「ピッキング管理番号」
	,SHIWAKE_SAKUSEI_KBN  CHAR(1) --「仕訳作成区分」
	,DEMPYO_JOTAI_KBN  CHAR(1) DEFAULT '0' NOT NULL --「伝票状態区分」
	,URIAGE_KEIJO_YMD  DATE --「売上計上年月日」
	,URIAGE_TANTO_SHAIN_NO  VARCHAR2(8) --「売上担当社員番号」
	,HNKN_MT_AITE_KAISHA_CD  CHAR(5) --「変換元相手会社コード」
	,URIAGE_KEIJOZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「売上計上済フラグ」
	,URIAGE_DEMPYO_HAKKOZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「売上伝票発行済フラグ」
	,NOHIN_DEMPYO_HAKKOZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「納品伝票発行済フラグ」
	,SURYO_TEISEIZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「数量訂正済フラグ」
	,CHOTATSU_SEIKYU_KBN  CHAR(1) NOT NULL --「調達請求区分」
	,URIAGE_DEMPYO_BIKO  VARCHAR2(40) --「売上伝票備考」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,JUHATCHU_NO  CHAR(10) --「受発注番号」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1543T_PK PRIMARY KEY(
	 URIAGE_DEMPYO_NO
	,  URIAGE_DEMPYONAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1543T_TBL IS '調達売上テーブル'
/

COMMENT ON COLUMN ED1543T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1543T_TBL.URIAGE_DEMPYO_NO IS '売上伝票番号'
/
COMMENT ON COLUMN ED1543T_TBL.URIAGE_DEMPYONAI_SN IS '売上伝票内連番'
/
COMMENT ON COLUMN ED1543T_TBL.AKAKURO_KBN IS '赤黒区分'
/
COMMENT ON COLUMN ED1543T_TBL.SAISHIN_FLG IS '最新フラグ'
/
COMMENT ON COLUMN ED1543T_TBL.JIGYOSHO_CD IS '事業所コード'
/
COMMENT ON COLUMN ED1543T_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED1543T_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED1543T_TBL.URIAGE_TSUKEKAE_KBN IS '売上付替区分'
/
COMMENT ON COLUMN ED1543T_TBL.URIAGE_TORIHIKI_KBN IS '売上取引区分'
/
COMMENT ON COLUMN ED1543T_TBL.CHOKUSO_FLG IS '直送フラグ'
/
COMMENT ON COLUMN ED1543T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED1543T_TBL.TOKUISAKI_TORIHIKISAKI_CD IS '得意先取引先コード'
/
COMMENT ON COLUMN ED1543T_TBL.TKISK_TRHKSK_BSH_CD IS '得意先取引先部署コード'
/
COMMENT ON COLUMN ED1543T_TBL.SHIIRESAKI_TORIHIKISAKI_CD IS '仕入先取引先コード'
/
COMMENT ON COLUMN ED1543T_TBL.SHIRSK_TRHKSK_BSH_CD IS '仕入先取引先部署コード'
/
COMMENT ON COLUMN ED1543T_TBL.NOHINSAKI_KBN IS '納品先区分'
/
COMMENT ON COLUMN ED1543T_TBL.NOHINSAKI_TORIHIKISAKI_CD IS '納品先取引先コード'
/
COMMENT ON COLUMN ED1543T_TBL.NHNSK_TRHKSK_BSH_CD IS '納品先取引先部署コード'
/
COMMENT ON COLUMN ED1543T_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED1543T_TBL.KIYKSK_TRHKSK_BSH_CD IS '契約先取引先部署コード'
/
COMMENT ON COLUMN ED1543T_TBL.NOHINSAKI_JIGYOSHO_CD IS '納品先事業所コード'
/
COMMENT ON COLUMN ED1543T_TBL.NOHINSAKI_SOKO_CD IS '納品先倉庫コード'
/
COMMENT ON COLUMN ED1543T_TBL.SONOTA_NOHINSAKI_KN_NM IS 'その他納品先カナ名称'
/
COMMENT ON COLUMN ED1543T_TBL.SONOTA_NOHINSAKI_NM IS 'その他納品先名称'
/
COMMENT ON COLUMN ED1543T_TBL.SONOTA_NOHINSAKI_DENWA_NO IS 'その他納品先電話番号'
/
COMMENT ON COLUMN ED1543T_TBL.SONOTA_NOHINSAKI_YUBIN_NO IS 'その他納品先郵便番号'
/
COMMENT ON COLUMN ED1543T_TBL.SONOTA_NOHINSAKI_JUSHO_1 IS 'その他納品先住所１'
/
COMMENT ON COLUMN ED1543T_TBL.SONOTA_NOHINSAKI_JUSHO_2 IS 'その他納品先住所２'
/
COMMENT ON COLUMN ED1543T_TBL.SONOTA_NOHINSAKI_BUSHO_NM IS 'その他納品先部署名称'
/
COMMENT ON COLUMN ED1543T_TBL.SONOTA_NOHINSAKI_TANTO_NM IS 'その他納品先担当名称'
/
COMMENT ON COLUMN ED1543T_TBL.PICKING_KANRI_NO IS 'ピッキング管理番号'
/
COMMENT ON COLUMN ED1543T_TBL.SHIWAKE_SAKUSEI_KBN IS '仕訳作成区分'
/
COMMENT ON COLUMN ED1543T_TBL.DEMPYO_JOTAI_KBN IS '伝票状態区分'
/
COMMENT ON COLUMN ED1543T_TBL.URIAGE_KEIJO_YMD IS '売上計上年月日'
/
COMMENT ON COLUMN ED1543T_TBL.URIAGE_TANTO_SHAIN_NO IS '売上担当社員番号'
/
COMMENT ON COLUMN ED1543T_TBL.HNKN_MT_AITE_KAISHA_CD IS '変換元相手会社コード'
/
COMMENT ON COLUMN ED1543T_TBL.URIAGE_KEIJOZUMI_FLG IS '売上計上済フラグ'
/
COMMENT ON COLUMN ED1543T_TBL.URIAGE_DEMPYO_HAKKOZUMI_FLG IS '売上伝票発行済フラグ'
/
COMMENT ON COLUMN ED1543T_TBL.NOHIN_DEMPYO_HAKKOZUMI_FLG IS '納品伝票発行済フラグ'
/
COMMENT ON COLUMN ED1543T_TBL.SURYO_TEISEIZUMI_FLG IS '数量訂正済フラグ'
/
COMMENT ON COLUMN ED1543T_TBL.CHOTATSU_SEIKYU_KBN IS '調達請求区分'
/
COMMENT ON COLUMN ED1543T_TBL.URIAGE_DEMPYO_BIKO IS '売上伝票備考'
/
COMMENT ON COLUMN ED1543T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED1543T_TBL.JUHATCHU_NO IS '受発注番号'
/
COMMENT ON COLUMN ED1543T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1543T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1543T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1543T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1543T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1543T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1543T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1543T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1543T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1543T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1543T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1543T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1543T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1543T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
