/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1506T_TBL.sql
-- 物理名：ED1506T_TBL
-- 論理名：ＥＤＩ出荷テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1506T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1506T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUHATCHU_NO  CHAR(10) NOT NULL --「受発注番号」
	,JUHATCHU_MEISAI_SN  NUMBER(3,0) DEFAULT '0' NOT NULL --「受発注明細連番」
	,BUNNO_KAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「分納回数」
	,BUNNO_KAISUNAI_SN  CHAR(14) NOT NULL --「分納回数内連番」
	,AKAKURO_KBN  CHAR(1) NOT NULL --「赤黒区分」
	,SAISHIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「最新フラグ」
	,SHIIRESAKI_TORIHIKISAKI_CD  CHAR(9) --「仕入先取引先コード」
	,SHIRSK_TRHKSK_BSH_CD  CHAR(4) --「仕入先取引先部署コード」
	,SHUKKA_YMD  DATE --「出荷年月日」
	,SHUKKA_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「出荷数量」
	,SHUKKA_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「出荷単価金額」
	,SHUKKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「出荷金額」
	,OKURIJO_NO  VARCHAR2(50) --「送り状番号」
	,NYUSHUKKA_JOKYO_KBN  CHAR(1) DEFAULT '1' NOT NULL --「入出荷状況区分」
	,SHKK_DATA_SHSI_IRI_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「出荷データ修正依頼対象フラグ」
	,SHUKKA_TOROKU_TORIHIKISAKI_CD  CHAR(9) --「出荷登録取引先コード」
	,SHKK_TRK_SHGI_RYSH_NO  CHAR(8) --「出荷登録社外利用者番号」
	,SHUKKA_TOROKU_DT  TIMESTAMP --「出荷登録日時」
	,SHUKKA_KAKUTEI_TORIHIKISAKI_CD  CHAR(9) --「出荷確定取引先コード」
	,SHKK_KKTI_SHGI_RYSH_NO  CHAR(8) --「出荷確定社外利用者番号」
	,SHUKKA_KAKUTEI_DT  TIMESTAMP --「出荷確定日時」
	,JUHATCHU_DEMPYONAI_SN  CHAR(14) --「受発注伝票内連番」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1506T_PK PRIMARY KEY(
	 JUHATCHU_NO
	,  JUHATCHU_MEISAI_SN
	,  BUNNO_KAISU
	,  BUNNO_KAISUNAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1506T_TBL IS 'ＥＤＩ出荷テーブル'
/

COMMENT ON COLUMN ED1506T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1506T_TBL.JUHATCHU_NO IS '受発注番号'
/
COMMENT ON COLUMN ED1506T_TBL.JUHATCHU_MEISAI_SN IS '受発注明細連番'
/
COMMENT ON COLUMN ED1506T_TBL.BUNNO_KAISU IS '分納回数'
/
COMMENT ON COLUMN ED1506T_TBL.BUNNO_KAISUNAI_SN IS '分納回数内連番'
/
COMMENT ON COLUMN ED1506T_TBL.AKAKURO_KBN IS '赤黒区分'
/
COMMENT ON COLUMN ED1506T_TBL.SAISHIN_FLG IS '最新フラグ'
/
COMMENT ON COLUMN ED1506T_TBL.SHIIRESAKI_TORIHIKISAKI_CD IS '仕入先取引先コード'
/
COMMENT ON COLUMN ED1506T_TBL.SHIRSK_TRHKSK_BSH_CD IS '仕入先取引先部署コード'
/
COMMENT ON COLUMN ED1506T_TBL.SHUKKA_YMD IS '出荷年月日'
/
COMMENT ON COLUMN ED1506T_TBL.SHUKKA_SURYO IS '出荷数量'
/
COMMENT ON COLUMN ED1506T_TBL.SHUKKA_TANKA_AMT IS '出荷単価金額'
/
COMMENT ON COLUMN ED1506T_TBL.SHUKKA_AMT IS '出荷金額'
/
COMMENT ON COLUMN ED1506T_TBL.OKURIJO_NO IS '送り状番号'
/
COMMENT ON COLUMN ED1506T_TBL.NYUSHUKKA_JOKYO_KBN IS '入出荷状況区分'
/
COMMENT ON COLUMN ED1506T_TBL.SHKK_DATA_SHSI_IRI_TISH_FLG IS '出荷データ修正依頼対象フラグ'
/
COMMENT ON COLUMN ED1506T_TBL.SHUKKA_TOROKU_TORIHIKISAKI_CD IS '出荷登録取引先コード'
/
COMMENT ON COLUMN ED1506T_TBL.SHKK_TRK_SHGI_RYSH_NO IS '出荷登録社外利用者番号'
/
COMMENT ON COLUMN ED1506T_TBL.SHUKKA_TOROKU_DT IS '出荷登録日時'
/
COMMENT ON COLUMN ED1506T_TBL.SHUKKA_KAKUTEI_TORIHIKISAKI_CD IS '出荷確定取引先コード'
/
COMMENT ON COLUMN ED1506T_TBL.SHKK_KKTI_SHGI_RYSH_NO IS '出荷確定社外利用者番号'
/
COMMENT ON COLUMN ED1506T_TBL.SHUKKA_KAKUTEI_DT IS '出荷確定日時'
/
COMMENT ON COLUMN ED1506T_TBL.JUHATCHU_DEMPYONAI_SN IS '受発注伝票内連番'
/
COMMENT ON COLUMN ED1506T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1506T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1506T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1506T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1506T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1506T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1506T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1506T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1506T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1506T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1506T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1506T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1506T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1506T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
