/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1569W_TBL.sql
-- 物理名：ED1569W_TBL
-- 論理名：ＣＤＣ移管情報ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1569W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1569W_TBL (
	 BATCH_SHORI_KANRI_SN  CHAR(14) NOT NULL --「バッチ処理管理連番」
	,CARD_IKAN_DATA_TORIKOMI_SN  CHAR(14) NOT NULL --「カード移管データ取込連番」
	,CDC_HANYO_SHIKIBETSU_NO  CHAR(4) --「ＣＤＣ＿汎用識別番号」
	,CDC_HANYO_JOHO_SHIKIBETSU_KEY  CHAR(10) --「ＣＤＣ＿汎用情報識別キー」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,CDC_CARD_CHUMON_NO  CHAR(10) --「ＣＤＣ＿カード注文番号」
	,TOROKU_TORIKESHI_KBN  CHAR(1) --「登録取消区分」
	,SHIZAI_SOBI_KBN  CHAR(1) --「資材装備区分」
	,IKAMMOTO_JIGYOSHO_CD  CHAR(6) --「移管元事業所コード」
	,JISSHI_JIGYOSHO_CD  CHAR(6) --「実施事業所コード」
	,DEMPYO_GROUP_NO  CHAR(4) --「伝票グループ番号」
	,IKAN_SHUKKA_YMD  DATE --「移管出荷年月日」
	,CDC_MEISAI_KOBAN  CHAR(2) --「ＣＤＣ＿明細項番」
	,CDC_CHUMON_MEISAI_KOBAN  CHAR(2) --「ＣＤＣ＿注文番号項番」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,SHIMPIN_KBN  CHAR(1) --「新品区分」
	,CARD_IKAN_SURYO  NUMBER(9,0) --「カード移管数量」
	,IKAN_TORIKESHI_FLG  CHAR(1) --「移管取消フラグ」
	,CARD_IKAN_DATA_TRKM_JKY_KBN  CHAR(1) --「カード移管データ取込状態区分」
	,CHUMON_NO  CHAR(17) --「注文番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1569W_PK PRIMARY KEY(
	 BATCH_SHORI_KANRI_SN
	,  CARD_IKAN_DATA_TORIKOMI_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1569W_TBL IS 'ＣＤＣ移管情報ワーク'
/

COMMENT ON COLUMN ED1569W_TBL.BATCH_SHORI_KANRI_SN IS 'バッチ処理管理連番'
/
COMMENT ON COLUMN ED1569W_TBL.CARD_IKAN_DATA_TORIKOMI_SN IS 'カード移管データ取込連番'
/
COMMENT ON COLUMN ED1569W_TBL.CDC_HANYO_SHIKIBETSU_NO IS 'ＣＤＣ＿汎用識別番号'
/
COMMENT ON COLUMN ED1569W_TBL.CDC_HANYO_JOHO_SHIKIBETSU_KEY IS 'ＣＤＣ＿汎用情報識別キー'
/
COMMENT ON COLUMN ED1569W_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED1569W_TBL.CDC_CARD_CHUMON_NO IS 'ＣＤＣ＿カード注文番号'
/
COMMENT ON COLUMN ED1569W_TBL.TOROKU_TORIKESHI_KBN IS '登録取消区分'
/
COMMENT ON COLUMN ED1569W_TBL.SHIZAI_SOBI_KBN IS '資材装備区分'
/
COMMENT ON COLUMN ED1569W_TBL.IKAMMOTO_JIGYOSHO_CD IS '移管元事業所コード'
/
COMMENT ON COLUMN ED1569W_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED1569W_TBL.DEMPYO_GROUP_NO IS '伝票グループ番号'
/
COMMENT ON COLUMN ED1569W_TBL.IKAN_SHUKKA_YMD IS '移管出荷年月日'
/
COMMENT ON COLUMN ED1569W_TBL.CDC_MEISAI_KOBAN IS 'ＣＤＣ＿明細項番'
/
COMMENT ON COLUMN ED1569W_TBL.CDC_CHUMON_MEISAI_KOBAN IS 'ＣＤＣ＿注文番号項番'
/
COMMENT ON COLUMN ED1569W_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED1569W_TBL.SHIMPIN_KBN IS '新品区分'
/
COMMENT ON COLUMN ED1569W_TBL.CARD_IKAN_SURYO IS 'カード移管数量'
/
COMMENT ON COLUMN ED1569W_TBL.IKAN_TORIKESHI_FLG IS '移管取消フラグ'
/
COMMENT ON COLUMN ED1569W_TBL.CARD_IKAN_DATA_TRKM_JKY_KBN IS 'カード移管データ取込状態区分'
/
COMMENT ON COLUMN ED1569W_TBL.CHUMON_NO IS '注文番号'
/
COMMENT ON COLUMN ED1569W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1569W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1569W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1569W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1569W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1569W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1569W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1569W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1569W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1569W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1569W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1569W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
