/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1538T_TBL.sql
-- 物理名：ED1538T_TBL
-- 論理名：受発注明細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1538T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1538T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUHATCHU_NO  CHAR(10) NOT NULL --「受発注番号」
	,JUHATCHU_DEMPYONAI_SN  CHAR(14) NOT NULL --「受発注伝票内連番」
	,JUHATCHU_MEISAI_SN  NUMBER(3,0) DEFAULT '0' NOT NULL --「受発注明細連番」
	,AKAKURO_KBN  CHAR(1) NOT NULL --「赤黒区分」
	,SAISHIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「最新フラグ」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,JUHATCHU_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「受発注数量」
	,HIKIATE_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「引当数量」
	,SHUKKA_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「出荷数量」
	,NOHIN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「納品数量」
	,JUCHU_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「受注単価金額」
	,JUCHU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「受注金額」
	,HATCHU_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「発注単価金額」
	,HATCHU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「発注金額」
	,SHUKKA_YMD  DATE --「出荷年月日」
	,SHUKKA_YOTEI_YMD  DATE --「出荷予定年月日」
	,NOHIN_YMD  DATE --「納品年月日」
	,SOKO_CD  CHAR(6) --「倉庫コード」
	,SOKO_HIKIATE_SHITEI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「倉庫引当指定フラグ」
	,NOHIN_JOTAI_KBN  CHAR(1) --「納品状態区分」
	,NOHIN_KAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「納品回数」
	,HITCHAKUBI_SHITEI_CMNT  VARCHAR2(30) --「必着日指定コメント」
	,SHOHIN_SHIYO_CMNT  VARCHAR2(30) --「商品仕様コメント」
	,SYSTEM_HYOJI_BIKO  VARCHAR2(60) --「システム表示備考」
	,CHOTATSUBU_ATE_CMNT  VARCHAR2(60) --「調達部宛てコメント」
	,MAKER_NOKI_KAITO_CMNT  VARCHAR2(60) --「メーカー納期回答コメント」
	,ALSOK_NOKI_KAITO_CMNT  VARCHAR2(60) --「ＡＬＳＯＫ納期回答コメント」
	,HIKIATEZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「引当済フラグ」
	,HIKIATE_JOGAI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「引当除外フラグ」
	,HATCHU_TEKIYOCHU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「発注適用中フラグ」
	,CHOTATSU_STATUS_KBN  CHAR(2) NOT NULL --「調達ステータス区分」
	,CHUMON_TEISEI_HORYU_KBN  CHAR(1) --「注文訂正保留区分」
	,HATCHU_IRAI_MAIL_SN  CHAR(14) --「発注依頼メール連番」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,JUCHU_KEIYAKU_MEISAI_SN  CHAR(14) --「受注契約明細連番」
	,CHUMON_NO  CHAR(17) --「注文番号」
	,CHUMON_DEMPYO_MEISAI_SN  CHAR(14) --「注文伝票明細連番」
	,EDI_CHUMON_NO  CHAR(10) --「ＥＤＩ注文番号」
	,EDI_CHUMON_MEISAI_NO  CHAR(3) --「ＥＤＩ注文明細番号」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1538T_PK PRIMARY KEY(
	 JUHATCHU_NO
	,  JUHATCHU_DEMPYONAI_SN
	,  JUHATCHU_MEISAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1538T_TBL IS '受発注明細テーブル'
/

COMMENT ON COLUMN ED1538T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1538T_TBL.JUHATCHU_NO IS '受発注番号'
/
COMMENT ON COLUMN ED1538T_TBL.JUHATCHU_DEMPYONAI_SN IS '受発注伝票内連番'
/
COMMENT ON COLUMN ED1538T_TBL.JUHATCHU_MEISAI_SN IS '受発注明細連番'
/
COMMENT ON COLUMN ED1538T_TBL.AKAKURO_KBN IS '赤黒区分'
/
COMMENT ON COLUMN ED1538T_TBL.SAISHIN_FLG IS '最新フラグ'
/
COMMENT ON COLUMN ED1538T_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED1538T_TBL.JUHATCHU_SURYO IS '受発注数量'
/
COMMENT ON COLUMN ED1538T_TBL.HIKIATE_SURYO IS '引当数量'
/
COMMENT ON COLUMN ED1538T_TBL.SHUKKA_SURYO IS '出荷数量'
/
COMMENT ON COLUMN ED1538T_TBL.NOHIN_SURYO IS '納品数量'
/
COMMENT ON COLUMN ED1538T_TBL.JUCHU_TANKA_AMT IS '受注単価金額'
/
COMMENT ON COLUMN ED1538T_TBL.JUCHU_AMT IS '受注金額'
/
COMMENT ON COLUMN ED1538T_TBL.HATCHU_TANKA_AMT IS '発注単価金額'
/
COMMENT ON COLUMN ED1538T_TBL.HATCHU_AMT IS '発注金額'
/
COMMENT ON COLUMN ED1538T_TBL.SHUKKA_YMD IS '出荷年月日'
/
COMMENT ON COLUMN ED1538T_TBL.SHUKKA_YOTEI_YMD IS '出荷予定年月日'
/
COMMENT ON COLUMN ED1538T_TBL.NOHIN_YMD IS '納品年月日'
/
COMMENT ON COLUMN ED1538T_TBL.SOKO_CD IS '倉庫コード'
/
COMMENT ON COLUMN ED1538T_TBL.SOKO_HIKIATE_SHITEI_FLG IS '倉庫引当指定フラグ'
/
COMMENT ON COLUMN ED1538T_TBL.NOHIN_JOTAI_KBN IS '納品状態区分'
/
COMMENT ON COLUMN ED1538T_TBL.NOHIN_KAISU IS '納品回数'
/
COMMENT ON COLUMN ED1538T_TBL.HITCHAKUBI_SHITEI_CMNT IS '必着日指定コメント'
/
COMMENT ON COLUMN ED1538T_TBL.SHOHIN_SHIYO_CMNT IS '商品仕様コメント'
/
COMMENT ON COLUMN ED1538T_TBL.SYSTEM_HYOJI_BIKO IS 'システム表示備考'
/
COMMENT ON COLUMN ED1538T_TBL.CHOTATSUBU_ATE_CMNT IS '調達部宛てコメント'
/
COMMENT ON COLUMN ED1538T_TBL.MAKER_NOKI_KAITO_CMNT IS 'メーカー納期回答コメント'
/
COMMENT ON COLUMN ED1538T_TBL.ALSOK_NOKI_KAITO_CMNT IS 'ＡＬＳＯＫ納期回答コメント'
/
COMMENT ON COLUMN ED1538T_TBL.HIKIATEZUMI_FLG IS '引当済フラグ'
/
COMMENT ON COLUMN ED1538T_TBL.HIKIATE_JOGAI_FLG IS '引当除外フラグ'
/
COMMENT ON COLUMN ED1538T_TBL.HATCHU_TEKIYOCHU_FLG IS '発注適用中フラグ'
/
COMMENT ON COLUMN ED1538T_TBL.CHOTATSU_STATUS_KBN IS '調達ステータス区分'
/
COMMENT ON COLUMN ED1538T_TBL.CHUMON_TEISEI_HORYU_KBN IS '注文訂正保留区分'
/
COMMENT ON COLUMN ED1538T_TBL.HATCHU_IRAI_MAIL_SN IS '発注依頼メール連番'
/
COMMENT ON COLUMN ED1538T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED1538T_TBL.JUCHU_KEIYAKU_MEISAI_SN IS '受注契約明細連番'
/
COMMENT ON COLUMN ED1538T_TBL.CHUMON_NO IS '注文番号'
/
COMMENT ON COLUMN ED1538T_TBL.CHUMON_DEMPYO_MEISAI_SN IS '注文伝票明細連番'
/
COMMENT ON COLUMN ED1538T_TBL.EDI_CHUMON_NO IS 'ＥＤＩ注文番号'
/
COMMENT ON COLUMN ED1538T_TBL.EDI_CHUMON_MEISAI_NO IS 'ＥＤＩ注文明細番号'
/
COMMENT ON COLUMN ED1538T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1538T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1538T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1538T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1538T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1538T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1538T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1538T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1538T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1538T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1538T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1538T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1538T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1538T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
