/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1516M_TBL.sql
-- 物理名：ED1516M_TBL
-- 論理名：ＥＤＩ得意先変換マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1516M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1516M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,CHUMON_KBN  CHAR(1) NOT NULL --「注文区分」
	,EDI_TOKUISAKI_KBN  CHAR(1) NOT NULL --「ＥＤＩ得意先区分」
	,EDI_SEIKYU_JIGYOSHO_CD  CHAR(6) NOT NULL --「ＥＤＩ請求事業所コード」
	,EDI_SEIKYU_JIGYOSHO_NM  VARCHAR2(200) --「ＥＤＩ請求事業所名称」
	,TOKUISAKI_TORIHIKISAKI_CD  CHAR(9) --「得意先取引先コード」
	,TKISK_TRHKSK_BSH_CD  CHAR(4) --「得意先取引先部署コード」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1516M_PK PRIMARY KEY(
	 CHUMON_KBN
	,  EDI_TOKUISAKI_KBN
	,  EDI_SEIKYU_JIGYOSHO_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1516M_TBL IS 'ＥＤＩ得意先変換マスタ'
/

COMMENT ON COLUMN ED1516M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1516M_TBL.CHUMON_KBN IS '注文区分'
/
COMMENT ON COLUMN ED1516M_TBL.EDI_TOKUISAKI_KBN IS 'ＥＤＩ得意先区分'
/
COMMENT ON COLUMN ED1516M_TBL.EDI_SEIKYU_JIGYOSHO_CD IS 'ＥＤＩ請求事業所コード'
/
COMMENT ON COLUMN ED1516M_TBL.EDI_SEIKYU_JIGYOSHO_NM IS 'ＥＤＩ請求事業所名称'
/
COMMENT ON COLUMN ED1516M_TBL.TOKUISAKI_TORIHIKISAKI_CD IS '得意先取引先コード'
/
COMMENT ON COLUMN ED1516M_TBL.TKISK_TRHKSK_BSH_CD IS '得意先取引先部署コード'
/
COMMENT ON COLUMN ED1516M_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1516M_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1516M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1516M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1516M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1516M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1516M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1516M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1516M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1516M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1516M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1516M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1516M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1516M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
