/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1522T_TBL.sql
-- 物理名：ED1522T_TBL
-- 論理名：ピッキング管理テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1522T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1522T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,PICKING_KANRI_NO  CHAR(10) NOT NULL --「ピッキング管理番号」
	,PICKING_YMD  DATE --「ピッキング年月日」
	,PICKING_TM  CHAR(4) --「ピッキング時刻」
	,JIGYOSHO_CD  CHAR(6) --「事業所コード」
	,SOKO_CD  CHAR(6) --「倉庫コード」
	,SHUKKA_YOTEI_KAISHI_YMD  DATE --「出荷予定開始年月日」
	,SHUKKA_YOTEI_SHURYO_YMD  DATE --「出荷予定終了年月日」
	,TOKUISAKI_TORIHIKISAKI_CD  CHAR(9) --「得意先取引先コード」
	,TKISK_TRHKSK_BSH_CD  CHAR(4) --「得意先取引先部署コード」
	,URIAGE_KEIJOZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「売上計上済フラグ」
	,PICKING_NPP_SHTSRYKZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ピッキング日報出力済フラグ」
	,DMPY_ACE_SHTSRYK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「伝票エース出力済フラグ」
	,URIAGE_KEIJO_YMD  DATE --「売上計上年月日」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1522T_PK PRIMARY KEY(
	 PICKING_KANRI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1522T_TBL IS 'ピッキング管理テーブル'
/

COMMENT ON COLUMN ED1522T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1522T_TBL.PICKING_KANRI_NO IS 'ピッキング管理番号'
/
COMMENT ON COLUMN ED1522T_TBL.PICKING_YMD IS 'ピッキング年月日'
/
COMMENT ON COLUMN ED1522T_TBL.PICKING_TM IS 'ピッキング時刻'
/
COMMENT ON COLUMN ED1522T_TBL.JIGYOSHO_CD IS '事業所コード'
/
COMMENT ON COLUMN ED1522T_TBL.SOKO_CD IS '倉庫コード'
/
COMMENT ON COLUMN ED1522T_TBL.SHUKKA_YOTEI_KAISHI_YMD IS '出荷予定開始年月日'
/
COMMENT ON COLUMN ED1522T_TBL.SHUKKA_YOTEI_SHURYO_YMD IS '出荷予定終了年月日'
/
COMMENT ON COLUMN ED1522T_TBL.TOKUISAKI_TORIHIKISAKI_CD IS '得意先取引先コード'
/
COMMENT ON COLUMN ED1522T_TBL.TKISK_TRHKSK_BSH_CD IS '得意先取引先部署コード'
/
COMMENT ON COLUMN ED1522T_TBL.URIAGE_KEIJOZUMI_FLG IS '売上計上済フラグ'
/
COMMENT ON COLUMN ED1522T_TBL.PICKING_NPP_SHTSRYKZM_FLG IS 'ピッキング日報出力済フラグ'
/
COMMENT ON COLUMN ED1522T_TBL.DMPY_ACE_SHTSRYK_FLG IS '伝票エース出力済フラグ'
/
COMMENT ON COLUMN ED1522T_TBL.URIAGE_KEIJO_YMD IS '売上計上年月日'
/
COMMENT ON COLUMN ED1522T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1522T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1522T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1522T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1522T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1522T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1522T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1522T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1522T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1522T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1522T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1522T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1522T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1522T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
