/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1508T_TBL.sql
-- 物理名：ED1508T_TBL
-- 論理名：ＥＤＩ入荷受付明細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1508T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1508T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,NYUKA_UKETSUKE_NO  CHAR(10) NOT NULL --「入荷受付番号」
	,NYUKA_UKETSUKE_BANGONAI_SN  CHAR(14) NOT NULL --「入荷受付番号内連番」
	,NYUKA_UKETSUKE_MEISAI_NO  CHAR(2) NOT NULL --「入荷受付明細番号」
	,AKAKURO_KBN  CHAR(1) NOT NULL --「赤黒区分」
	,SAISHIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「最新フラグ」
	,NYUKA_TORIKOMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「入荷取込フラグ」
	,NYUKA_TORIKOMI_DT  TIMESTAMP --「入荷取込日時」
	,SHUKKA_ERROR_KBN  CHAR(1) NOT NULL --「出荷エラー区分」
	,SHUKKA_ERROR_SHURUI_KBN  CHAR(1) NOT NULL --「出荷エラー種類区分」
	,JUHATCHU_NO  CHAR(10) --「受発注番号」
	,JUHATCHU_MEISAI_SN  NUMBER(3,0) DEFAULT '0' NOT NULL --「受発注明細連番」
	,BUNNO_KAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「分納回数」
	,BUNNO_KAISUNAI_SN  CHAR(14) --「分納回数内連番」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1508T_PK PRIMARY KEY(
	 NYUKA_UKETSUKE_NO
	,  NYUKA_UKETSUKE_BANGONAI_SN
	,  NYUKA_UKETSUKE_MEISAI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1508T_TBL IS 'ＥＤＩ入荷受付明細テーブル'
/

COMMENT ON COLUMN ED1508T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1508T_TBL.NYUKA_UKETSUKE_NO IS '入荷受付番号'
/
COMMENT ON COLUMN ED1508T_TBL.NYUKA_UKETSUKE_BANGONAI_SN IS '入荷受付番号内連番'
/
COMMENT ON COLUMN ED1508T_TBL.NYUKA_UKETSUKE_MEISAI_NO IS '入荷受付明細番号'
/
COMMENT ON COLUMN ED1508T_TBL.AKAKURO_KBN IS '赤黒区分'
/
COMMENT ON COLUMN ED1508T_TBL.SAISHIN_FLG IS '最新フラグ'
/
COMMENT ON COLUMN ED1508T_TBL.NYUKA_TORIKOMI_FLG IS '入荷取込フラグ'
/
COMMENT ON COLUMN ED1508T_TBL.NYUKA_TORIKOMI_DT IS '入荷取込日時'
/
COMMENT ON COLUMN ED1508T_TBL.SHUKKA_ERROR_KBN IS '出荷エラー区分'
/
COMMENT ON COLUMN ED1508T_TBL.SHUKKA_ERROR_SHURUI_KBN IS '出荷エラー種類区分'
/
COMMENT ON COLUMN ED1508T_TBL.JUHATCHU_NO IS '受発注番号'
/
COMMENT ON COLUMN ED1508T_TBL.JUHATCHU_MEISAI_SN IS '受発注明細連番'
/
COMMENT ON COLUMN ED1508T_TBL.BUNNO_KAISU IS '分納回数'
/
COMMENT ON COLUMN ED1508T_TBL.BUNNO_KAISUNAI_SN IS '分納回数内連番'
/
COMMENT ON COLUMN ED1508T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1508T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1508T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1508T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1508T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1508T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1508T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1508T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1508T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1508T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1508T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1508T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1508T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1508T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
