/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1501T_TBL.sql
-- 物理名：ED1501T_TBL
-- 論理名：ＥＤＩ注文連携受入テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1501T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1501T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,EDI_CHUMON_FILE_NO  CHAR(10) NOT NULL --「ＥＤＩ注文ファイル番号」
	,EDI_CHUMON_GROUP_NO  NUMBER(4,0) DEFAULT '0' NOT NULL --「ＥＤＩ注文グループ番号」
	,EDI_CHUMON_FILE_MEISAI_SN  CHAR(14) NOT NULL --「ＥＤＩ注文ファイル明細連番」
	,EDI_CHUMONSAKI_GYOSHA_CD  CHAR(6) --「ＥＤＩ注文先業者コード」
	,EDI_HATCHU_JIGYOSHO_CD  CHAR(6) --「ＥＤＩ発注事業所コード」
	,EDI_OKURISAKI_JIGYOSHO_CD  CHAR(6) --「ＥＤＩ送り先事業所コード」
	,EDI_SEIKYU_JIGYOSHO_CD  CHAR(6) --「ＥＤＩ請求事業所コード」
	,EDI_CHOKI_DENKEI_NO  CHAR(9) --「ＥＤＩ長期電計番号」
	,EDI_TANKI_DENKEI_NO  CHAR(9) --「ＥＤＩ短期電計番号」
	,EDI_JUCHU_JIGYOSHO_CD  CHAR(6) --「ＥＤＩ受注事業所コード」
	,CHUMON_KBN  CHAR(1) NOT NULL --「注文区分」
	,CHUMON_YMD  DATE --「注文年月日」
	,NOHIN_KIBO_YMD  DATE --「納品希望年月日」
	,EDI_TOKUISAKI_KBN  CHAR(1) NOT NULL --「ＥＤＩ得意先区分」
	,EDI_DEMPYO_NO  CHAR(10) --「ＥＤＩ伝票番号」
	,EDI_DEMPYO_MEISAI_NO  CHAR(2) --「ＥＤＩ伝票明細番号」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,TANKA_RIREKI_NO  CHAR(4) --「単価履歴番号」
	,HIMMEI_NM  VARCHAR2(60) --「品名名称」
	,CHUMON_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「注文数量」
	,EDI_TANI_NM  VARCHAR2(2) --「ＥＤＩ単位名称」
	,JUSHIN_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「受信単価金額」
	,CHOTATSUBU_ATE_CMNT  VARCHAR2(60) --「調達部宛てコメント」
	,CHUMON_ERROR_KBN  CHAR(1) NOT NULL --「注文エラー区分」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1501T_PK PRIMARY KEY(
	 EDI_CHUMON_FILE_NO
	,  EDI_CHUMON_GROUP_NO
	,  EDI_CHUMON_FILE_MEISAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1501T_TBL IS 'ＥＤＩ注文連携受入テーブル'
/

COMMENT ON COLUMN ED1501T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1501T_TBL.EDI_CHUMON_FILE_NO IS 'ＥＤＩ注文ファイル番号'
/
COMMENT ON COLUMN ED1501T_TBL.EDI_CHUMON_GROUP_NO IS 'ＥＤＩ注文グループ番号'
/
COMMENT ON COLUMN ED1501T_TBL.EDI_CHUMON_FILE_MEISAI_SN IS 'ＥＤＩ注文ファイル明細連番'
/
COMMENT ON COLUMN ED1501T_TBL.EDI_CHUMONSAKI_GYOSHA_CD IS 'ＥＤＩ注文先業者コード'
/
COMMENT ON COLUMN ED1501T_TBL.EDI_HATCHU_JIGYOSHO_CD IS 'ＥＤＩ発注事業所コード'
/
COMMENT ON COLUMN ED1501T_TBL.EDI_OKURISAKI_JIGYOSHO_CD IS 'ＥＤＩ送り先事業所コード'
/
COMMENT ON COLUMN ED1501T_TBL.EDI_SEIKYU_JIGYOSHO_CD IS 'ＥＤＩ請求事業所コード'
/
COMMENT ON COLUMN ED1501T_TBL.EDI_CHOKI_DENKEI_NO IS 'ＥＤＩ長期電計番号'
/
COMMENT ON COLUMN ED1501T_TBL.EDI_TANKI_DENKEI_NO IS 'ＥＤＩ短期電計番号'
/
COMMENT ON COLUMN ED1501T_TBL.EDI_JUCHU_JIGYOSHO_CD IS 'ＥＤＩ受注事業所コード'
/
COMMENT ON COLUMN ED1501T_TBL.CHUMON_KBN IS '注文区分'
/
COMMENT ON COLUMN ED1501T_TBL.CHUMON_YMD IS '注文年月日'
/
COMMENT ON COLUMN ED1501T_TBL.NOHIN_KIBO_YMD IS '納品希望年月日'
/
COMMENT ON COLUMN ED1501T_TBL.EDI_TOKUISAKI_KBN IS 'ＥＤＩ得意先区分'
/
COMMENT ON COLUMN ED1501T_TBL.EDI_DEMPYO_NO IS 'ＥＤＩ伝票番号'
/
COMMENT ON COLUMN ED1501T_TBL.EDI_DEMPYO_MEISAI_NO IS 'ＥＤＩ伝票明細番号'
/
COMMENT ON COLUMN ED1501T_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED1501T_TBL.TANKA_RIREKI_NO IS '単価履歴番号'
/
COMMENT ON COLUMN ED1501T_TBL.HIMMEI_NM IS '品名名称'
/
COMMENT ON COLUMN ED1501T_TBL.CHUMON_SURYO IS '注文数量'
/
COMMENT ON COLUMN ED1501T_TBL.EDI_TANI_NM IS 'ＥＤＩ単位名称'
/
COMMENT ON COLUMN ED1501T_TBL.JUSHIN_TANKA_AMT IS '受信単価金額'
/
COMMENT ON COLUMN ED1501T_TBL.CHOTATSUBU_ATE_CMNT IS '調達部宛てコメント'
/
COMMENT ON COLUMN ED1501T_TBL.CHUMON_ERROR_KBN IS '注文エラー区分'
/
COMMENT ON COLUMN ED1501T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1501T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1501T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1501T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1501T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1501T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1501T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1501T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1501T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1501T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1501T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1501T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1501T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1501T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
