/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1544T_TBL.sql
-- 物理名：ED1544T_TBL
-- 論理名：調達売上明細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1544T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1544T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,URIAGE_DEMPYO_NO  CHAR(17) NOT NULL --「売上伝票番号」
	,URIAGE_DEMPYONAI_SN  CHAR(14) NOT NULL --「売上伝票内連番」
	,URIAGE_DEMPYO_MEISAI_SN  NUMBER(3,0) DEFAULT '0' NOT NULL --「売上伝票明細連番」
	,AKAKURO_KBN  CHAR(1) NOT NULL --「赤黒区分」
	,SAISHIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「最新フラグ」
	,TSUKEKAE_MIJISSHI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「付替未実施フラグ」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,SOKO_CD  CHAR(6) --「倉庫コード」
	,URIAGE_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「売上数量」
	,SHIIRE_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「仕入単価金額」
	,URIAGE_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上単価金額」
	,SHIIRE_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「仕入金額」
	,URIAGE_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上金額」
	,ARARI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「粗利金額」
	,HYOJIYO_CHUMON_NO  VARCHAR2(17) --「表示用注文番号」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,JUCHU_KEIYAKU_MEISAI_SN  CHAR(14) --「受注契約明細連番」
	,JUHATCHU_NO  CHAR(10) --「受発注番号」
	,JUHATCHU_MEISAI_SN  NUMBER(3,0) --「受発注明細連番」
	,SHIIRE_DEMPYO_NO  CHAR(17) --「仕入伝票番号」
	,SHIIRE_DEMPYO_MEISAI_SN  NUMBER(3,0) --「仕入伝票明細連番」
	,NOHIN_DEMPYO_NO  CHAR(17) --「納品伝票番号」
	,NOHIN_DEMPYO_MEISAI_SN  CHAR(14) --「納品伝票明細連番」
	,BUNNO_KAISU  NUMBER(9,0) DEFAULT '0' --「分納回数」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1544T_PK PRIMARY KEY(
	 URIAGE_DEMPYO_NO
	,  URIAGE_DEMPYONAI_SN
	,  URIAGE_DEMPYO_MEISAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1544T_TBL IS '調達売上明細テーブル'
/

COMMENT ON COLUMN ED1544T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1544T_TBL.URIAGE_DEMPYO_NO IS '売上伝票番号'
/
COMMENT ON COLUMN ED1544T_TBL.URIAGE_DEMPYONAI_SN IS '売上伝票内連番'
/
COMMENT ON COLUMN ED1544T_TBL.URIAGE_DEMPYO_MEISAI_SN IS '売上伝票明細連番'
/
COMMENT ON COLUMN ED1544T_TBL.AKAKURO_KBN IS '赤黒区分'
/
COMMENT ON COLUMN ED1544T_TBL.SAISHIN_FLG IS '最新フラグ'
/
COMMENT ON COLUMN ED1544T_TBL.TSUKEKAE_MIJISSHI_FLG IS '付替未実施フラグ'
/
COMMENT ON COLUMN ED1544T_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED1544T_TBL.SOKO_CD IS '倉庫コード'
/
COMMENT ON COLUMN ED1544T_TBL.URIAGE_SURYO IS '売上数量'
/
COMMENT ON COLUMN ED1544T_TBL.SHIIRE_TANKA_AMT IS '仕入単価金額'
/
COMMENT ON COLUMN ED1544T_TBL.URIAGE_TANKA_AMT IS '売上単価金額'
/
COMMENT ON COLUMN ED1544T_TBL.SHIIRE_AMT IS '仕入金額'
/
COMMENT ON COLUMN ED1544T_TBL.URIAGE_AMT IS '売上金額'
/
COMMENT ON COLUMN ED1544T_TBL.ARARI_AMT IS '粗利金額'
/
COMMENT ON COLUMN ED1544T_TBL.HYOJIYO_CHUMON_NO IS '表示用注文番号'
/
COMMENT ON COLUMN ED1544T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED1544T_TBL.JUCHU_KEIYAKU_MEISAI_SN IS '受注契約明細連番'
/
COMMENT ON COLUMN ED1544T_TBL.JUHATCHU_NO IS '受発注番号'
/
COMMENT ON COLUMN ED1544T_TBL.JUHATCHU_MEISAI_SN IS '受発注明細連番'
/
COMMENT ON COLUMN ED1544T_TBL.SHIIRE_DEMPYO_NO IS '仕入伝票番号'
/
COMMENT ON COLUMN ED1544T_TBL.SHIIRE_DEMPYO_MEISAI_SN IS '仕入伝票明細連番'
/
COMMENT ON COLUMN ED1544T_TBL.NOHIN_DEMPYO_NO IS '納品伝票番号'
/
COMMENT ON COLUMN ED1544T_TBL.NOHIN_DEMPYO_MEISAI_SN IS '納品伝票明細連番'
/
COMMENT ON COLUMN ED1544T_TBL.BUNNO_KAISU IS '分納回数'
/
COMMENT ON COLUMN ED1544T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1544T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1544T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1544T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1544T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1544T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1544T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1544T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1544T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1544T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1544T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1544T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1544T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1544T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
