/* ---------------------------------------------------------------------- */
-- インデックス作成DDL(ORACLE用)
-- ファイル名：ED1537T_IDX.sql
-- 対象テーブル（物理名）：ED1537T_TBL
-- 対象テーブル（論理名）：受発注テーブル
/* ---------------------------------------------------------------------- */

CREATE INDEX ED1537T_IDX01 ON ED1537T_TBL(
	SHIIRESAKI_TORIHIKISAKI_CD,
	SHIRSK_TRHKSK_BSH_CD 
)
/

CREATE INDEX ED1537T_IDX02 ON ED1537T_TBL(
	TOKUISAKI_TORIHIKISAKI_CD,
	TKISK_TRHKSK_BSH_CD 
)
/

CREATE INDEX ED1537T_IDX03 ON ED1537T_TBL(
	JUCHU_KEIYAKU_NO 
)
/

CREATE INDEX ED1537T_IDX04 ON ED1537T_TBL(
	SHINSEI_SHONIN_NO 
)
/

CREATE INDEX ED1537T_IDX05 ON ED1537T_TBL(
	CHUMON_NO 
)
/

CREATE INDEX ED1537T_IDX06 ON ED1537T_TBL(
	NOHIN_KIBO_YMD 
)
/

CREATE INDEX ED1537T_IDX07 ON ED1537T_TBL(
	CHOTATSU_JUCHU_YMD,
	TOKUISAKI_TORIHIKISAKI_CD,
	TKISK_TRHKSK_BSH_CD 
)
/

CREATE INDEX ED1537T_IDX08 ON ED1537T_TBL(
	HATCHU_YMD,
	SHIIRESAKI_TORIHIKISAKI_CD,
	SHIRSK_TRHKSK_BSH_CD 
)
/

CREATE INDEX ED1537T_IDX09 ON ED1537T_TBL(
	HYOJIYO_CHUMON_NO 
)
/

CREATE INDEX ED1537T_IDX10 ON ED1537T_TBL(
	HATCHU_IRAI_MAIL_SN 
)
/
