/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1507T_TBL.sql
-- 物理名：ED1507T_TBL
-- 論理名：ＥＤＩ入荷受付テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1507T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1507T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,NYUKA_UKETSUKE_NO  CHAR(10) NOT NULL --「入荷受付番号」
	,NYUKA_UKETSUKE_BANGONAI_SN  CHAR(14) NOT NULL --「入荷受付番号内連番」
	,AKAKURO_KBN  CHAR(1) NOT NULL --「赤黒区分」
	,SAISHIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「最新フラグ」
	,SHIIRESAKI_TORIHIKISAKI_CD  CHAR(9) --「仕入先取引先コード」
	,SHIRSK_TRHKSK_BSH_CD  CHAR(4) --「仕入先取引先部署コード」
	,SHIIRE_YMD  DATE --「仕入年月日」
	,NYUKA_KAKUNIN_KBN  CHAR(1) NOT NULL --「入荷確認区分」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1507T_PK PRIMARY KEY(
	 NYUKA_UKETSUKE_NO
	,  NYUKA_UKETSUKE_BANGONAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1507T_TBL IS 'ＥＤＩ入荷受付テーブル'
/

COMMENT ON COLUMN ED1507T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1507T_TBL.NYUKA_UKETSUKE_NO IS '入荷受付番号'
/
COMMENT ON COLUMN ED1507T_TBL.NYUKA_UKETSUKE_BANGONAI_SN IS '入荷受付番号内連番'
/
COMMENT ON COLUMN ED1507T_TBL.AKAKURO_KBN IS '赤黒区分'
/
COMMENT ON COLUMN ED1507T_TBL.SAISHIN_FLG IS '最新フラグ'
/
COMMENT ON COLUMN ED1507T_TBL.SHIIRESAKI_TORIHIKISAKI_CD IS '仕入先取引先コード'
/
COMMENT ON COLUMN ED1507T_TBL.SHIRSK_TRHKSK_BSH_CD IS '仕入先取引先部署コード'
/
COMMENT ON COLUMN ED1507T_TBL.SHIIRE_YMD IS '仕入年月日'
/
COMMENT ON COLUMN ED1507T_TBL.NYUKA_KAKUNIN_KBN IS '入荷確認区分'
/
COMMENT ON COLUMN ED1507T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1507T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1507T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1507T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1507T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1507T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1507T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1507T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1507T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1507T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1507T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1507T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1507T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1507T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
