/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1570W_TBL.sql
-- 物理名：ED1570W_TBL
-- 論理名：ＣＤＣ出荷情報ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1570W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1570W_TBL (
	 BATCH_SHORI_KANRI_SN  CHAR(14) NOT NULL --「バッチ処理管理連番」
	,CARD_SHUKKA_DATA_TORIKOMI_SN  CHAR(14) NOT NULL --「カード出荷データ取込連番」
	,CDC_HANYO_SHIKIBETSU_NO  CHAR(4) --「ＣＤＣ＿汎用識別番号」
	,CDC_HANYO_JOHO_SHIKIBETSU_KEY  CHAR(10) --「ＣＤＣ＿汎用情報識別キー」
	,SHUKKASAKI_JIGYOSHO_CD  CHAR(6) --「出荷先事業所コード」
	,SHIZAI_SOBI_KBN  CHAR(1) --「資材装備区分」
	,TOROKU_TORIKESHI_KBN  CHAR(1) --「登録取消区分」
	,CDC_MEISAI_KOBAN  CHAR(2) --「ＣＤＣ＿明細項番」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,TANKA_RIREKI_NO  CHAR(4) --「単価履歴番号」
	,TONYU_TSUIKA_CARD_MAISU  NUMBER(9,0) --「投入追加カード枚数」
	,CARD_SHIIRE_TANKA_AMT  NUMBER(13,0) --「カード仕入単価金額」
	,DEMPYO_GROUP_NO  CHAR(4) --「伝票グループ番号」
	,SHUKKA_KBN  CHAR(1) --「出荷区分」
	,SHUKKA_YMD  DATE --「出荷年月日」
	,GENKA_KEIJO_YMD  DATE --「原価計上年月日」
	,CDC_YOBI_NO  VARCHAR2(10) --「ＣＤＣ＿予備番号」
	,SHIMPIN_KBN  CHAR(1) --「新品区分」
	,KOJI_KBN  CHAR(1) --「工事区分」
	,GAICHU_KBN  CHAR(1) --「外注区分」
	,RONRI_SAKUJO_FLG  CHAR(1) --「論理削除フラグ」
	,CARD_SHUKKA_DATA_TRKM_JKY_KBN  CHAR(1) --「カード出荷データ取込状態区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1570W_PK PRIMARY KEY(
	 BATCH_SHORI_KANRI_SN
	,  CARD_SHUKKA_DATA_TORIKOMI_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1570W_TBL IS 'ＣＤＣ出荷情報ワーク'
/

COMMENT ON COLUMN ED1570W_TBL.BATCH_SHORI_KANRI_SN IS 'バッチ処理管理連番'
/
COMMENT ON COLUMN ED1570W_TBL.CARD_SHUKKA_DATA_TORIKOMI_SN IS 'カード出荷データ取込連番'
/
COMMENT ON COLUMN ED1570W_TBL.CDC_HANYO_SHIKIBETSU_NO IS 'ＣＤＣ＿汎用識別番号'
/
COMMENT ON COLUMN ED1570W_TBL.CDC_HANYO_JOHO_SHIKIBETSU_KEY IS 'ＣＤＣ＿汎用情報識別キー'
/
COMMENT ON COLUMN ED1570W_TBL.SHUKKASAKI_JIGYOSHO_CD IS '出荷先事業所コード'
/
COMMENT ON COLUMN ED1570W_TBL.SHIZAI_SOBI_KBN IS '資材装備区分'
/
COMMENT ON COLUMN ED1570W_TBL.TOROKU_TORIKESHI_KBN IS '登録取消区分'
/
COMMENT ON COLUMN ED1570W_TBL.CDC_MEISAI_KOBAN IS 'ＣＤＣ＿明細項番'
/
COMMENT ON COLUMN ED1570W_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED1570W_TBL.TANKA_RIREKI_NO IS '単価履歴番号'
/
COMMENT ON COLUMN ED1570W_TBL.TONYU_TSUIKA_CARD_MAISU IS '投入追加カード枚数'
/
COMMENT ON COLUMN ED1570W_TBL.CARD_SHIIRE_TANKA_AMT IS 'カード仕入単価金額'
/
COMMENT ON COLUMN ED1570W_TBL.DEMPYO_GROUP_NO IS '伝票グループ番号'
/
COMMENT ON COLUMN ED1570W_TBL.SHUKKA_KBN IS '出荷区分'
/
COMMENT ON COLUMN ED1570W_TBL.SHUKKA_YMD IS '出荷年月日'
/
COMMENT ON COLUMN ED1570W_TBL.GENKA_KEIJO_YMD IS '原価計上年月日'
/
COMMENT ON COLUMN ED1570W_TBL.CDC_YOBI_NO IS 'ＣＤＣ＿予備番号'
/
COMMENT ON COLUMN ED1570W_TBL.SHIMPIN_KBN IS '新品区分'
/
COMMENT ON COLUMN ED1570W_TBL.KOJI_KBN IS '工事区分'
/
COMMENT ON COLUMN ED1570W_TBL.GAICHU_KBN IS '外注区分'
/
COMMENT ON COLUMN ED1570W_TBL.RONRI_SAKUJO_FLG IS '論理削除フラグ'
/
COMMENT ON COLUMN ED1570W_TBL.CARD_SHUKKA_DATA_TRKM_JKY_KBN IS 'カード出荷データ取込状態区分'
/
COMMENT ON COLUMN ED1570W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1570W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1570W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1570W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1570W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1570W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1570W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1570W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1570W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1570W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1570W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1570W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
