/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1567T_TBL.sql
-- 物理名：ED1567T_TBL
-- 論理名：発注添付ファイル管理テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1567T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1567T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUHATCHU_NO  CHAR(10) NOT NULL --「受発注番号」
	,TEMPU_FILE_KANRI_SN  CHAR(14) NOT NULL --「添付ファイル管理連番」
	,KYOTSU_UPLOAD_FILE_NM  VARCHAR2(255) --「共通アップロードファイル名称」
	,KYTS_UPLOAD_FILE_SHKBTS_KEY  VARCHAR2(255) --「共通アップロードファイル識別キー」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1567T_PK PRIMARY KEY(
	 JUHATCHU_NO
	,  TEMPU_FILE_KANRI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1567T_TBL IS '発注添付ファイル管理テーブル'
/

COMMENT ON COLUMN ED1567T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1567T_TBL.JUHATCHU_NO IS '受発注番号'
/
COMMENT ON COLUMN ED1567T_TBL.TEMPU_FILE_KANRI_SN IS '添付ファイル管理連番'
/
COMMENT ON COLUMN ED1567T_TBL.KYOTSU_UPLOAD_FILE_NM IS '共通アップロードファイル名称'
/
COMMENT ON COLUMN ED1567T_TBL.KYTS_UPLOAD_FILE_SHKBTS_KEY IS '共通アップロードファイル識別キー'
/
COMMENT ON COLUMN ED1567T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1567T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1567T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1567T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1567T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1567T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1567T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1567T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1567T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1567T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1567T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1567T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
