/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1568T_TBL.sql
-- 物理名：ED1568T_TBL
-- 論理名：特定商品添付ファイル管理テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1568T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1568T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,FILE_SHIKIBETSU_KEY  VARCHAR2(255) NOT NULL --「ファイル識別キー」
	,TOKUTEI_SHOHIN_FILE_NM  VARCHAR2(60) --「特定商品ファイル名称」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,EDI_CHUMON_NO  CHAR(10) --「ＥＤＩ注文番号」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1568T_PK PRIMARY KEY(
	 FILE_SHIKIBETSU_KEY
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1568T_TBL IS '特定商品添付ファイル管理テーブル'
/

COMMENT ON COLUMN ED1568T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1568T_TBL.FILE_SHIKIBETSU_KEY IS 'ファイル識別キー'
/
COMMENT ON COLUMN ED1568T_TBL.TOKUTEI_SHOHIN_FILE_NM IS '特定商品ファイル名称'
/
COMMENT ON COLUMN ED1568T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED1568T_TBL.EDI_CHUMON_NO IS 'ＥＤＩ注文番号'
/
COMMENT ON COLUMN ED1568T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1568T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1568T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1568T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1568T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1568T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1568T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1568T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1568T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1568T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1568T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1568T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1568T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1568T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
