/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1550T_TBL.sql
-- 物理名：ED1550T_TBL
-- 論理名：注文納期回答テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1550T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1550T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,CHUMON_NO  CHAR(17) NOT NULL --「注文番号」
	,CHUMON_DEMPYO_MEISAI_SN  CHAR(14) NOT NULL --「注文伝票明細連番」
	,NOKI_KAITO_MEISAI_SN  CHAR(14) NOT NULL --「納期回答明細連番」
	,NOHIN_YOTEI_YMD  DATE --「納品予定年月日」
	,NOHIN_YOTEI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「納品予定数量」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1550T_PK PRIMARY KEY(
	 CHUMON_NO
	,  CHUMON_DEMPYO_MEISAI_SN
	,  NOKI_KAITO_MEISAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1550T_TBL IS '注文納期回答テーブル'
/

COMMENT ON COLUMN ED1550T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1550T_TBL.CHUMON_NO IS '注文番号'
/
COMMENT ON COLUMN ED1550T_TBL.CHUMON_DEMPYO_MEISAI_SN IS '注文伝票明細連番'
/
COMMENT ON COLUMN ED1550T_TBL.NOKI_KAITO_MEISAI_SN IS '納期回答明細連番'
/
COMMENT ON COLUMN ED1550T_TBL.NOHIN_YOTEI_YMD IS '納品予定年月日'
/
COMMENT ON COLUMN ED1550T_TBL.NOHIN_YOTEI_SURYO IS '納品予定数量'
/
COMMENT ON COLUMN ED1550T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1550T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1550T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1550T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1550T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1550T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1550T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1550T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1550T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1550T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1550T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1550T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1550T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1550T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
