/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1542T_TBL.sql
-- 物理名：ED1542T_TBL
-- 論理名：在庫振替伝票明細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1542T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1542T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,ZAIKO_FURIKAE_DEMPYO_NO  CHAR(17) NOT NULL --「在庫振替伝票番号」
	,ZAIKO_FURIKAE_DEMPYO_MEISAI_SN  CHAR(14) NOT NULL --「在庫振替伝票明細連番」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,SHIMPIN_KBN  CHAR(1) --「新品区分」
	,SHIIRE_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「仕入単価金額」
	,ZAIKO_FURIKAE_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「在庫振替数量」
	,ZAIKO_FURIKAE_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「在庫振替金額」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1542T_PK PRIMARY KEY(
	 ZAIKO_FURIKAE_DEMPYO_NO
	,  ZAIKO_FURIKAE_DEMPYO_MEISAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1542T_TBL IS '在庫振替伝票明細テーブル'
/

COMMENT ON COLUMN ED1542T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1542T_TBL.ZAIKO_FURIKAE_DEMPYO_NO IS '在庫振替伝票番号'
/
COMMENT ON COLUMN ED1542T_TBL.ZAIKO_FURIKAE_DEMPYO_MEISAI_SN IS '在庫振替伝票明細連番'
/
COMMENT ON COLUMN ED1542T_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED1542T_TBL.SHIMPIN_KBN IS '新品区分'
/
COMMENT ON COLUMN ED1542T_TBL.SHIIRE_TANKA_AMT IS '仕入単価金額'
/
COMMENT ON COLUMN ED1542T_TBL.ZAIKO_FURIKAE_SURYO IS '在庫振替数量'
/
COMMENT ON COLUMN ED1542T_TBL.ZAIKO_FURIKAE_AMT IS '在庫振替金額'
/
COMMENT ON COLUMN ED1542T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1542T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1542T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1542T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1542T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1542T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1542T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1542T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1542T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1542T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1542T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1542T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1542T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1542T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
