/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1537T_TBL.sql
-- 物理名：ED1537T_TBL
-- 論理名：受発注テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1537T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1537T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUHATCHU_NO  CHAR(10) NOT NULL --「受発注番号」
	,JUHATCHU_DEMPYONAI_SN  CHAR(14) NOT NULL --「受発注伝票内連番」
	,AKAKURO_KBN  CHAR(1) NOT NULL --「赤黒区分」
	,SAISHIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「最新フラグ」
	,JUHATCHU_DEMPYO_KBN  CHAR(1) NOT NULL --「受発注伝票区分」
	,TOKUISAKI_TORIHIKISAKI_CD  CHAR(9) --「得意先取引先コード」
	,TKISK_TRHKSK_BSH_CD  CHAR(4) --「得意先取引先部署コード」
	,JIGYOSHO_CD  CHAR(6) --「事業所コード」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,JISSHI_JIGYOSHO_CD  CHAR(6) --「実施事業所コード」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,KIYKSK_TRHKSK_BSH_CD  CHAR(4) --「契約先取引先部署コード」
	,SHIIRESAKI_TORIHIKISAKI_CD  CHAR(9) --「仕入先取引先コード」
	,SHIRSK_TRHKSK_BSH_CD  CHAR(4) --「仕入先取引先部署コード」
	,CHOTATSU_BUMON_KUBUNCHI_CD  CHAR(4) --「調達部門区分値コード」
	,NOHINSAKI_KBN  CHAR(1) --「納品先区分」
	,NOHINSAKI_TORIHIKISAKI_CD  CHAR(9) --「納品先取引先コード」
	,NHNSK_TRHKSK_BSH_CD  CHAR(4) --「納品先取引先部署コード」
	,NOHINSAKI_JIGYOSHO_CD  CHAR(6) --「納品先事業所コード」
	,NOHINSAKI_SOKO_CD  CHAR(6) --「納品先倉庫コード」
	,SONOTA_NOHINSAKI_KN_NM  VARCHAR2(40) --「その他納品先カナ名称」
	,SONOTA_NOHINSAKI_NM  VARCHAR2(30) --「その他納品先名称」
	,SONOTA_NOHINSAKI_DENWA_NO  VARCHAR2(20) --「その他納品先電話番号」
	,SONOTA_NOHINSAKI_YUBIN_NO  CHAR(7) --「その他納品先郵便番号」
	,SONOTA_NOHINSAKI_JUSHO_1  VARCHAR2(60) --「その他納品先住所１」
	,SONOTA_NOHINSAKI_JUSHO_2  VARCHAR2(60) --「その他納品先住所２」
	,SONOTA_NOHINSAKI_BUSHO_NM  VARCHAR2(40) --「その他納品先部署名称」
	,SONOTA_NOHINSAKI_TANTO_NM  VARCHAR2(30) --「その他納品先担当名称」
	,CHOTATSU_JUCHU_YMD  DATE --「調達受注年月日」
	,SOSHIN_YMD  DATE --「送信年月日」
	,ZENKAI_SOSHIN_YMD  DATE --「前回送信年月日」
	,JUSHIN_YMD  DATE --「受信年月日」
	,HATCHU_YMD  DATE --「発注年月日」
	,NOHIN_KIBO_YMD  DATE --「納品希望年月日」
	,JUHATCHU_BIKO  VARCHAR2(40) --「受発注備考」
	,CHOTATSU_SYSTEM_RIYO_KBN  CHAR(1) NOT NULL --「調達システム利用区分」
	,DEMPYO_JOTAI_KBN  CHAR(1) DEFAULT '0' NOT NULL --「伝票状態区分」
	,SETCHI_BASHO_NM  VARCHAR2(60) --「設置場所名称」
	,SETCHI_BASHO_YUBIN_NO  CHAR(7) --「設置場所郵便番号」
	,SETCHI_BASHO_JUSHO  VARCHAR2(60) --「設置場所住所」
	,SETCHI_BASHO_DENWA_NO  VARCHAR2(20) --「設置場所電話番号」
	,HNKN_MT_AITE_KAISHA_CD  CHAR(5) --「変換元相手会社コード」
	,ATOSHORI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「後処理フラグ」
	,CHOTATSU_KANRYO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「調達完了フラグ」
	,CHOKUSO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「直送フラグ」
	,HATCHUSHO_INSATSUZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「発注書印刷済フラグ」
	,HOJU_HATCHU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「補充発注フラグ」
	,SHOKAI_HATCHU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「初回発注フラグ」
	,HATCHU_TEKIYOCHU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「発注適用中フラグ」
	,CARD_SHIKIBETSU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「カード識別フラグ」
	,CARD_SYSTEM_RENKEIZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「カードシステム連携済フラグ」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,CHUMON_NO  CHAR(17) --「注文番号」
	,HATCHUMOTO_CHUMON_NO  VARCHAR2(12) --「発注元注文番号」
	,HYOJIYO_CHUMON_NO  VARCHAR2(17) --「表示用注文番号」
	,EDI_CHUMON_NO  CHAR(10) --「ＥＤＩ注文番号」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,HATCHU_IRAI_MAIL_SN  CHAR(14) --「発注依頼メール連番」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1537T_PK PRIMARY KEY(
	 JUHATCHU_NO
	,  JUHATCHU_DEMPYONAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1537T_TBL IS '受発注テーブル'
/

COMMENT ON COLUMN ED1537T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1537T_TBL.JUHATCHU_NO IS '受発注番号'
/
COMMENT ON COLUMN ED1537T_TBL.JUHATCHU_DEMPYONAI_SN IS '受発注伝票内連番'
/
COMMENT ON COLUMN ED1537T_TBL.AKAKURO_KBN IS '赤黒区分'
/
COMMENT ON COLUMN ED1537T_TBL.SAISHIN_FLG IS '最新フラグ'
/
COMMENT ON COLUMN ED1537T_TBL.JUHATCHU_DEMPYO_KBN IS '受発注伝票区分'
/
COMMENT ON COLUMN ED1537T_TBL.TOKUISAKI_TORIHIKISAKI_CD IS '得意先取引先コード'
/
COMMENT ON COLUMN ED1537T_TBL.TKISK_TRHKSK_BSH_CD IS '得意先取引先部署コード'
/
COMMENT ON COLUMN ED1537T_TBL.JIGYOSHO_CD IS '事業所コード'
/
COMMENT ON COLUMN ED1537T_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED1537T_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED1537T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED1537T_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED1537T_TBL.KIYKSK_TRHKSK_BSH_CD IS '契約先取引先部署コード'
/
COMMENT ON COLUMN ED1537T_TBL.SHIIRESAKI_TORIHIKISAKI_CD IS '仕入先取引先コード'
/
COMMENT ON COLUMN ED1537T_TBL.SHIRSK_TRHKSK_BSH_CD IS '仕入先取引先部署コード'
/
COMMENT ON COLUMN ED1537T_TBL.CHOTATSU_BUMON_KUBUNCHI_CD IS '調達部門区分値コード'
/
COMMENT ON COLUMN ED1537T_TBL.NOHINSAKI_KBN IS '納品先区分'
/
COMMENT ON COLUMN ED1537T_TBL.NOHINSAKI_TORIHIKISAKI_CD IS '納品先取引先コード'
/
COMMENT ON COLUMN ED1537T_TBL.NHNSK_TRHKSK_BSH_CD IS '納品先取引先部署コード'
/
COMMENT ON COLUMN ED1537T_TBL.NOHINSAKI_JIGYOSHO_CD IS '納品先事業所コード'
/
COMMENT ON COLUMN ED1537T_TBL.NOHINSAKI_SOKO_CD IS '納品先倉庫コード'
/
COMMENT ON COLUMN ED1537T_TBL.SONOTA_NOHINSAKI_KN_NM IS 'その他納品先カナ名称'
/
COMMENT ON COLUMN ED1537T_TBL.SONOTA_NOHINSAKI_NM IS 'その他納品先名称'
/
COMMENT ON COLUMN ED1537T_TBL.SONOTA_NOHINSAKI_DENWA_NO IS 'その他納品先電話番号'
/
COMMENT ON COLUMN ED1537T_TBL.SONOTA_NOHINSAKI_YUBIN_NO IS 'その他納品先郵便番号'
/
COMMENT ON COLUMN ED1537T_TBL.SONOTA_NOHINSAKI_JUSHO_1 IS 'その他納品先住所１'
/
COMMENT ON COLUMN ED1537T_TBL.SONOTA_NOHINSAKI_JUSHO_2 IS 'その他納品先住所２'
/
COMMENT ON COLUMN ED1537T_TBL.SONOTA_NOHINSAKI_BUSHO_NM IS 'その他納品先部署名称'
/
COMMENT ON COLUMN ED1537T_TBL.SONOTA_NOHINSAKI_TANTO_NM IS 'その他納品先担当名称'
/
COMMENT ON COLUMN ED1537T_TBL.CHOTATSU_JUCHU_YMD IS '調達受注年月日'
/
COMMENT ON COLUMN ED1537T_TBL.SOSHIN_YMD IS '送信年月日'
/
COMMENT ON COLUMN ED1537T_TBL.ZENKAI_SOSHIN_YMD IS '前回送信年月日'
/
COMMENT ON COLUMN ED1537T_TBL.JUSHIN_YMD IS '受信年月日'
/
COMMENT ON COLUMN ED1537T_TBL.HATCHU_YMD IS '発注年月日'
/
COMMENT ON COLUMN ED1537T_TBL.NOHIN_KIBO_YMD IS '納品希望年月日'
/
COMMENT ON COLUMN ED1537T_TBL.JUHATCHU_BIKO IS '受発注備考'
/
COMMENT ON COLUMN ED1537T_TBL.CHOTATSU_SYSTEM_RIYO_KBN IS '調達システム利用区分'
/
COMMENT ON COLUMN ED1537T_TBL.DEMPYO_JOTAI_KBN IS '伝票状態区分'
/
COMMENT ON COLUMN ED1537T_TBL.SETCHI_BASHO_NM IS '設置場所名称'
/
COMMENT ON COLUMN ED1537T_TBL.SETCHI_BASHO_YUBIN_NO IS '設置場所郵便番号'
/
COMMENT ON COLUMN ED1537T_TBL.SETCHI_BASHO_JUSHO IS '設置場所住所'
/
COMMENT ON COLUMN ED1537T_TBL.SETCHI_BASHO_DENWA_NO IS '設置場所電話番号'
/
COMMENT ON COLUMN ED1537T_TBL.HNKN_MT_AITE_KAISHA_CD IS '変換元相手会社コード'
/
COMMENT ON COLUMN ED1537T_TBL.ATOSHORI_FLG IS '後処理フラグ'
/
COMMENT ON COLUMN ED1537T_TBL.CHOTATSU_KANRYO_FLG IS '調達完了フラグ'
/
COMMENT ON COLUMN ED1537T_TBL.CHOKUSO_FLG IS '直送フラグ'
/
COMMENT ON COLUMN ED1537T_TBL.HATCHUSHO_INSATSUZUMI_FLG IS '発注書印刷済フラグ'
/
COMMENT ON COLUMN ED1537T_TBL.HOJU_HATCHU_FLG IS '補充発注フラグ'
/
COMMENT ON COLUMN ED1537T_TBL.SHOKAI_HATCHU_FLG IS '初回発注フラグ'
/
COMMENT ON COLUMN ED1537T_TBL.HATCHU_TEKIYOCHU_FLG IS '発注適用中フラグ'
/
COMMENT ON COLUMN ED1537T_TBL.CARD_SHIKIBETSU_FLG IS 'カード識別フラグ'
/
COMMENT ON COLUMN ED1537T_TBL.CARD_SYSTEM_RENKEIZUMI_FLG IS 'カードシステム連携済フラグ'
/
COMMENT ON COLUMN ED1537T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED1537T_TBL.CHUMON_NO IS '注文番号'
/
COMMENT ON COLUMN ED1537T_TBL.HATCHUMOTO_CHUMON_NO IS '発注元注文番号'
/
COMMENT ON COLUMN ED1537T_TBL.HYOJIYO_CHUMON_NO IS '表示用注文番号'
/
COMMENT ON COLUMN ED1537T_TBL.EDI_CHUMON_NO IS 'ＥＤＩ注文番号'
/
COMMENT ON COLUMN ED1537T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED1537T_TBL.HATCHU_IRAI_MAIL_SN IS '発注依頼メール連番'
/
COMMENT ON COLUMN ED1537T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1537T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1537T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1537T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1537T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1537T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1537T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1537T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1537T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1537T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1537T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1537T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1537T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1537T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
