/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1561T_TBL.sql
-- 物理名：ED1561T_TBL
-- 論理名：返納伝票テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1561T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1561T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,HENNO_DEMPYO_NO  CHAR(17) NOT NULL --「返納伝票番号」
	,SHIZAI_SOBI_KBN  CHAR(1) --「資材装備区分」
	,HENNO_YMD  DATE --「返納年月日」
	,JIGYOSHO_CD  CHAR(6) --「事業所コード」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,DEMPYO_GROUP_NO  CHAR(4) --「伝票グループ番号」
	,SOBI_SHUKKA_NAIYO_NM  VARCHAR2(16) --「装備出荷内容名称」
	,SHUKKA_KBN  CHAR(1) --「出荷区分」
	,SHIWAKE_SAKUSEI_KBN  CHAR(1) --「仕訳作成区分」
	,DEMPYO_JOTAI_KBN  CHAR(1) DEFAULT '0' NOT NULL --「伝票状態区分」
	,HOZEN_HENNO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全返納フラグ」
	,HENNO_YOTEI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「返納予定フラグ」
	,HOZEN_SHIKIBETSU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全識別フラグ」
	,HOZEN_RENKEIZUMII_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全連携済フラグ」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,CHUMON_NO  CHAR(17) --「注文番号」
	,SHUKKA_DEMPYO_NO  CHAR(17) --「出荷伝票番号」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1561T_PK PRIMARY KEY(
	 HENNO_DEMPYO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1561T_TBL IS '返納伝票テーブル'
/

COMMENT ON COLUMN ED1561T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1561T_TBL.HENNO_DEMPYO_NO IS '返納伝票番号'
/
COMMENT ON COLUMN ED1561T_TBL.SHIZAI_SOBI_KBN IS '資材装備区分'
/
COMMENT ON COLUMN ED1561T_TBL.HENNO_YMD IS '返納年月日'
/
COMMENT ON COLUMN ED1561T_TBL.JIGYOSHO_CD IS '事業所コード'
/
COMMENT ON COLUMN ED1561T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED1561T_TBL.DEMPYO_GROUP_NO IS '伝票グループ番号'
/
COMMENT ON COLUMN ED1561T_TBL.SOBI_SHUKKA_NAIYO_NM IS '装備出荷内容名称'
/
COMMENT ON COLUMN ED1561T_TBL.SHUKKA_KBN IS '出荷区分'
/
COMMENT ON COLUMN ED1561T_TBL.SHIWAKE_SAKUSEI_KBN IS '仕訳作成区分'
/
COMMENT ON COLUMN ED1561T_TBL.DEMPYO_JOTAI_KBN IS '伝票状態区分'
/
COMMENT ON COLUMN ED1561T_TBL.HOZEN_HENNO_FLG IS '保全返納フラグ'
/
COMMENT ON COLUMN ED1561T_TBL.HENNO_YOTEI_FLG IS '返納予定フラグ'
/
COMMENT ON COLUMN ED1561T_TBL.HOZEN_SHIKIBETSU_FLG IS '保全識別フラグ'
/
COMMENT ON COLUMN ED1561T_TBL.HOZEN_RENKEIZUMII_FLG IS '保全連携済フラグ'
/
COMMENT ON COLUMN ED1561T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED1561T_TBL.CHUMON_NO IS '注文番号'
/
COMMENT ON COLUMN ED1561T_TBL.SHUKKA_DEMPYO_NO IS '出荷伝票番号'
/
COMMENT ON COLUMN ED1561T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1561T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1561T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1561T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1561T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1561T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1561T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1561T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1561T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1561T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1561T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1561T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1561T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1561T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
