/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1513T_TBL.sql
-- 物理名：ED1513T_TBL
-- 論理名：ＥＤＩ掲示板テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1513T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1513T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,EDI_KEIJIBAN_NO  NUMBER(10,0) DEFAULT '0' NOT NULL --「ＥＤＩ掲示板番号」
	,EDI_KEIJIBAN_KBN  CHAR(1) NOT NULL --「ＥＤＩ掲示板区分」
	,EDI_KEIJIBAN_SHOSAI_KBN  CHAR(1) DEFAULT '0' NOT NULL --「ＥＤＩ掲示板詳細区分」
	,EDI_KEIJIBAN_TITLE_NAIYO  VARCHAR2(60) --「ＥＤＩ掲示板タイトル内容」
	,EDI_KEIJIBAN_NAIYO  VARCHAR2(500) --「ＥＤＩ掲示板内容」
	,EDI_KEIJIBAN_HYOJI_KAISHI_DT  TIMESTAMP --「ＥＤＩ掲示板表示開始日時」
	,EDI_KEIJIBAN_HYOJI_KIGEN_DT  TIMESTAMP --「ＥＤＩ掲示板表示期限日時」
	,EDI_KEIJIBAN_YUSEN_HYOJI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＥＤＩ掲示板優先表示フラグ」
	,EDI_KIJBN_KKNN_KNRY_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＥＤＩ掲示板確認完了フラグ」
	,EDI_KEIJIBAN_LINK_URL  VARCHAR2(300) --「ＥＤＩ掲示板リンクＵＲＬ」
	,RIYOSAKI_TORIHIKISAKI_CD  CHAR(9) --「利用先取引先コード」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1513T_PK PRIMARY KEY(
	 EDI_KEIJIBAN_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1513T_TBL IS 'ＥＤＩ掲示板テーブル'
/

COMMENT ON COLUMN ED1513T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1513T_TBL.EDI_KEIJIBAN_NO IS 'ＥＤＩ掲示板番号'
/
COMMENT ON COLUMN ED1513T_TBL.EDI_KEIJIBAN_KBN IS 'ＥＤＩ掲示板区分'
/
COMMENT ON COLUMN ED1513T_TBL.EDI_KEIJIBAN_SHOSAI_KBN IS 'ＥＤＩ掲示板詳細区分'
/
COMMENT ON COLUMN ED1513T_TBL.EDI_KEIJIBAN_TITLE_NAIYO IS 'ＥＤＩ掲示板タイトル内容'
/
COMMENT ON COLUMN ED1513T_TBL.EDI_KEIJIBAN_NAIYO IS 'ＥＤＩ掲示板内容'
/
COMMENT ON COLUMN ED1513T_TBL.EDI_KEIJIBAN_HYOJI_KAISHI_DT IS 'ＥＤＩ掲示板表示開始日時'
/
COMMENT ON COLUMN ED1513T_TBL.EDI_KEIJIBAN_HYOJI_KIGEN_DT IS 'ＥＤＩ掲示板表示期限日時'
/
COMMENT ON COLUMN ED1513T_TBL.EDI_KEIJIBAN_YUSEN_HYOJI_FLG IS 'ＥＤＩ掲示板優先表示フラグ'
/
COMMENT ON COLUMN ED1513T_TBL.EDI_KIJBN_KKNN_KNRY_FLG IS 'ＥＤＩ掲示板確認完了フラグ'
/
COMMENT ON COLUMN ED1513T_TBL.EDI_KEIJIBAN_LINK_URL IS 'ＥＤＩ掲示板リンクＵＲＬ'
/
COMMENT ON COLUMN ED1513T_TBL.RIYOSAKI_TORIHIKISAKI_CD IS '利用先取引先コード'
/
COMMENT ON COLUMN ED1513T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1513T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1513T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1513T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1513T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1513T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1513T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1513T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1513T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1513T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1513T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1513T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1513T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1513T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
