/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED1551T_TBL.sql
-- 物理名：ED1551T_TBL
-- 論理名：生産計画テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED1551T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED1551T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SEISAN_KEIKAKU_NENDO  CHAR(2) NOT NULL --「生産計画年度」
	,SHIIRESAKI_TORIHIKISAKI_CD  CHAR(9) NOT NULL --「仕入先取引先コード」
	,SHIRSK_TRHKSK_BSH_CD  CHAR(4) NOT NULL --「仕入先取引先部署コード」
	,JISSEKIYO_HIMMEI_CD  CHAR(8) NOT NULL --「実績用品名コード」
	,HATCHUYO_HIMMEI_CD  CHAR(8) NOT NULL --「発注用品名コード」
	,SOKO_CD  CHAR(6) NOT NULL --「倉庫コード」
	,SEISAN_KEIKAKU_KOSHINZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「生産計画更新済フラグ」
	,SEISAN_KEIKAKU_BIKO  VARCHAR2(300) --「生産計画備考」
	,SHGI_TRKSH_SHGI_RYSH_NO  CHAR(8) --「社外登録者社外利用者番号」
	,SHGI_KSHNSH_SHGI_RYSH_NO  CHAR(8) --「社外更新者社外利用者番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED1551T_PK PRIMARY KEY(
	 SEISAN_KEIKAKU_NENDO
	,  SHIIRESAKI_TORIHIKISAKI_CD
	,  SHIRSK_TRHKSK_BSH_CD
	,  JISSEKIYO_HIMMEI_CD
	,  HATCHUYO_HIMMEI_CD
	,  SOKO_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED1551T_TBL IS '生産計画テーブル'
/

COMMENT ON COLUMN ED1551T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED1551T_TBL.SEISAN_KEIKAKU_NENDO IS '生産計画年度'
/
COMMENT ON COLUMN ED1551T_TBL.SHIIRESAKI_TORIHIKISAKI_CD IS '仕入先取引先コード'
/
COMMENT ON COLUMN ED1551T_TBL.SHIRSK_TRHKSK_BSH_CD IS '仕入先取引先部署コード'
/
COMMENT ON COLUMN ED1551T_TBL.JISSEKIYO_HIMMEI_CD IS '実績用品名コード'
/
COMMENT ON COLUMN ED1551T_TBL.HATCHUYO_HIMMEI_CD IS '発注用品名コード'
/
COMMENT ON COLUMN ED1551T_TBL.SOKO_CD IS '倉庫コード'
/
COMMENT ON COLUMN ED1551T_TBL.SEISAN_KEIKAKU_KOSHINZUMI_FLG IS '生産計画更新済フラグ'
/
COMMENT ON COLUMN ED1551T_TBL.SEISAN_KEIKAKU_BIKO IS '生産計画備考'
/
COMMENT ON COLUMN ED1551T_TBL.SHGI_TRKSH_SHGI_RYSH_NO IS '社外登録者社外利用者番号'
/
COMMENT ON COLUMN ED1551T_TBL.SHGI_KSHNSH_SHGI_RYSH_NO IS '社外更新者社外利用者番号'
/
COMMENT ON COLUMN ED1551T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED1551T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED1551T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED1551T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED1551T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED1551T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED1551T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED1551T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED1551T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED1551T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED1551T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED1551T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
