/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2011M_TBL.sql
-- 物理名：ED2011M_TBL
-- 論理名：区分値マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2011M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2011M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KBN_CD  CHAR(4) DEFAULT '0' NOT NULL --「区分コード」
	,KUBUNCHI_CD  CHAR(4) NOT NULL --「区分値コード」
	,KUBUNCHI_NM  VARCHAR2(60) NOT NULL --「区分値名称」
	,KUBUNCHI_SETSUMEI_NAIYO  VARCHAR2(100) --「区分値説明内容」
	,TTSH_KBN_CHECK_PATTERN_KBN_1  CHAR(1) DEFAULT '0' NOT NULL --「特定商品区分チェックパターン区分１」
	,TTSH_KBN_CHECK_PATTERN_KBN_2  CHAR(1) DEFAULT '0' NOT NULL --「特定商品区分チェックパターン区分２」
	,TTSH_KBN_CHECK_PATTERN_KBN_3  CHAR(1) DEFAULT '0' NOT NULL --「特定商品区分チェックパターン区分３」
	,TTSH_KBN_CHECK_PATTERN_KBN_4  CHAR(1) DEFAULT '0' NOT NULL --「特定商品区分チェックパターン区分４」
	,TTSH_KBN_CHECK_PATTERN_KBN_5  CHAR(1) DEFAULT '0' NOT NULL --「特定商品区分チェックパターン区分５」
	,TTSH_KBN_CHECK_PATTERN_KBN_6  CHAR(1) DEFAULT '0' NOT NULL --「特定商品区分チェックパターン区分６」
	,TTSH_KBN_CHECK_PATTERN_KBN_7  CHAR(1) DEFAULT '0' NOT NULL --「特定商品区分チェックパターン区分７」
	,TTSH_KBN_CHECK_PATTERN_KBN_8  CHAR(1) DEFAULT '0' NOT NULL --「特定商品区分チェックパターン区分８」
	,TTSH_KBN_CHECK_PATTERN_KBN_9  CHAR(1) DEFAULT '0' NOT NULL --「特定商品区分チェックパターン区分９」
	,TTSH_KBN_CHECK_PATTERN_KBN_10  CHAR(1) DEFAULT '0' NOT NULL --「特定商品区分チェックパターン区分１０」
	,KUBUNCHI_NARABI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「区分値並び順」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2011M_PK PRIMARY KEY(
	 KBN_CD
	,  KUBUNCHI_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2011M_TBL IS '区分値マスタ'
/

COMMENT ON COLUMN ED2011M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2011M_TBL.KBN_CD IS '区分コード'
/
COMMENT ON COLUMN ED2011M_TBL.KUBUNCHI_CD IS '区分値コード'
/
COMMENT ON COLUMN ED2011M_TBL.KUBUNCHI_NM IS '区分値名称'
/
COMMENT ON COLUMN ED2011M_TBL.KUBUNCHI_SETSUMEI_NAIYO IS '区分値説明内容'
/
COMMENT ON COLUMN ED2011M_TBL.TTSH_KBN_CHECK_PATTERN_KBN_1 IS '特定商品区分チェックパターン区分１'
/
COMMENT ON COLUMN ED2011M_TBL.TTSH_KBN_CHECK_PATTERN_KBN_2 IS '特定商品区分チェックパターン区分２'
/
COMMENT ON COLUMN ED2011M_TBL.TTSH_KBN_CHECK_PATTERN_KBN_3 IS '特定商品区分チェックパターン区分３'
/
COMMENT ON COLUMN ED2011M_TBL.TTSH_KBN_CHECK_PATTERN_KBN_4 IS '特定商品区分チェックパターン区分４'
/
COMMENT ON COLUMN ED2011M_TBL.TTSH_KBN_CHECK_PATTERN_KBN_5 IS '特定商品区分チェックパターン区分５'
/
COMMENT ON COLUMN ED2011M_TBL.TTSH_KBN_CHECK_PATTERN_KBN_6 IS '特定商品区分チェックパターン区分６'
/
COMMENT ON COLUMN ED2011M_TBL.TTSH_KBN_CHECK_PATTERN_KBN_7 IS '特定商品区分チェックパターン区分７'
/
COMMENT ON COLUMN ED2011M_TBL.TTSH_KBN_CHECK_PATTERN_KBN_8 IS '特定商品区分チェックパターン区分８'
/
COMMENT ON COLUMN ED2011M_TBL.TTSH_KBN_CHECK_PATTERN_KBN_9 IS '特定商品区分チェックパターン区分９'
/
COMMENT ON COLUMN ED2011M_TBL.TTSH_KBN_CHECK_PATTERN_KBN_10 IS '特定商品区分チェックパターン区分１０'
/
COMMENT ON COLUMN ED2011M_TBL.KUBUNCHI_NARABI_JUN IS '区分値並び順'
/
COMMENT ON COLUMN ED2011M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2011M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2011M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2011M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2011M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2011M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2011M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2011M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2011M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2011M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2011M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2011M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
