/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2008M_TBL.sql
-- 物理名：ED2008M_TBL
-- 論理名：貸与先マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2008M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2008M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TAIYO_TAISHOSAKI_KBN  CHAR(1) NOT NULL --「貸与対象先区分」
	,TAIYOSAKI_CD  VARCHAR2(8) NOT NULL --「貸与先コード」
	,ZAISHOKU_FLG  CHAR(1) DEFAULT '1' NOT NULL --「在職フラグ」
	,JIGYO_SEGMENT_CD  CHAR(3) --「事業セグメントコード」
	,GENKA_HANKAN_KBN  CHAR(1) NOT NULL --「原価販管区分」
	,NYUSHA_YMD  DATE --「入社年月日」
	,TAISHOKU_YMD  DATE --「退職年月日」
	,TAIYOSAKI_NM  VARCHAR2(40) NOT NULL --「貸与先名称」
	,TAIYOSAKI_KN_NM  VARCHAR2(40) --「貸与先カナ名称」
	,TAIYOSAKI_JUSHO_CD  CHAR(11) --「貸与先住所コード」
	,KENSAKUYO_TAIYOSAKI_NM  VARCHAR2(40) --「検索用貸与先名称」
	,KENSAKUYO_TAIYOSAKI_KN_NM  VARCHAR2(40) --「検索用貸与先カナ名称」
	,TAIYOSAKI_YUBIN_NO  CHAR(7) --「貸与先郵便番号」
	,TAIYOSAKI_JUSHO_BANCHI  VARCHAR2(50) --「貸与先住所番地」
	,TAIYOSAKI_TATEMONO_NM  VARCHAR2(50) --「貸与先建物名称」
	,TAIYOSAKI_TATEMONO_KN_NM  VARCHAR2(50) --「貸与先建物カナ名称」
	,TAIYOSAKI_TO_NM  VARCHAR2(50) --「貸与先棟名称」
	,TAIYOSAKI_KAI_NM  VARCHAR2(50) --「貸与先階名称」
	,TAIYOSAKI_KUKAKU_NM  VARCHAR2(50) --「貸与先区画名称」
	,TAIYOSAKI_HEYA_NM  VARCHAR2(50) --「貸与先部屋名称」
	,TAIYOSAKI_DENWA_NO  VARCHAR2(20) --「貸与先電話番号」
	,IDO_SHORICHU_KBN  CHAR(1) NOT NULL --「異動処理中区分」
	,SHOZOKU_JIGYOSHO_CD  CHAR(6) NOT NULL --「所属事業所コード」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2008M_PK PRIMARY KEY(
	 TAIYOSAKI_CD
	,  TAIYO_TAISHOSAKI_KBN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2008M_TBL IS '貸与先マスタ'
/

COMMENT ON COLUMN ED2008M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2008M_TBL.TAIYO_TAISHOSAKI_KBN IS '貸与対象先区分'
/
COMMENT ON COLUMN ED2008M_TBL.TAIYOSAKI_CD IS '貸与先コード'
/
COMMENT ON COLUMN ED2008M_TBL.ZAISHOKU_FLG IS '在職フラグ'
/
COMMENT ON COLUMN ED2008M_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED2008M_TBL.GENKA_HANKAN_KBN IS '原価販管区分'
/
COMMENT ON COLUMN ED2008M_TBL.NYUSHA_YMD IS '入社年月日'
/
COMMENT ON COLUMN ED2008M_TBL.TAISHOKU_YMD IS '退職年月日'
/
COMMENT ON COLUMN ED2008M_TBL.TAIYOSAKI_NM IS '貸与先名称'
/
COMMENT ON COLUMN ED2008M_TBL.TAIYOSAKI_KN_NM IS '貸与先カナ名称'
/
COMMENT ON COLUMN ED2008M_TBL.TAIYOSAKI_JUSHO_CD IS '貸与先住所コード'
/
COMMENT ON COLUMN ED2008M_TBL.KENSAKUYO_TAIYOSAKI_NM IS '検索用貸与先名称'
/
COMMENT ON COLUMN ED2008M_TBL.KENSAKUYO_TAIYOSAKI_KN_NM IS '検索用貸与先カナ名称'
/
COMMENT ON COLUMN ED2008M_TBL.TAIYOSAKI_YUBIN_NO IS '貸与先郵便番号'
/
COMMENT ON COLUMN ED2008M_TBL.TAIYOSAKI_JUSHO_BANCHI IS '貸与先住所番地'
/
COMMENT ON COLUMN ED2008M_TBL.TAIYOSAKI_TATEMONO_NM IS '貸与先建物名称'
/
COMMENT ON COLUMN ED2008M_TBL.TAIYOSAKI_TATEMONO_KN_NM IS '貸与先建物カナ名称'
/
COMMENT ON COLUMN ED2008M_TBL.TAIYOSAKI_TO_NM IS '貸与先棟名称'
/
COMMENT ON COLUMN ED2008M_TBL.TAIYOSAKI_KAI_NM IS '貸与先階名称'
/
COMMENT ON COLUMN ED2008M_TBL.TAIYOSAKI_KUKAKU_NM IS '貸与先区画名称'
/
COMMENT ON COLUMN ED2008M_TBL.TAIYOSAKI_HEYA_NM IS '貸与先部屋名称'
/
COMMENT ON COLUMN ED2008M_TBL.TAIYOSAKI_DENWA_NO IS '貸与先電話番号'
/
COMMENT ON COLUMN ED2008M_TBL.IDO_SHORICHU_KBN IS '異動処理中区分'
/
COMMENT ON COLUMN ED2008M_TBL.SHOZOKU_JIGYOSHO_CD IS '所属事業所コード'
/
COMMENT ON COLUMN ED2008M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2008M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2008M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2008M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2008M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2008M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2008M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2008M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2008M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2008M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2008M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2008M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
