/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2117T_TBL.sql
-- 物理名：ED2117T_TBL
-- 論理名：貸与品明細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2117T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2117T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TAIYOHIN_KANRI_ID  CHAR(16) NOT NULL --「貸与品管理ＩＤ」
	,TAIYOHIN_MEISAI_SN  CHAR(14) NOT NULL --「貸与品明細連番」
	,KOTAI_NO  VARCHAR2(30) --「個体番号」
	,SHOHI_KIGEN_YM  CHAR(6) --「消費期限年月」
	,TAIYO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「貸与数量」
	,HOKAN_KAISHI_YMD  DATE --「保管開始年月日」
	,HAIKI_YMD  DATE --「廃棄年月日」
	,TAIYOHIN_MEISAI_BIKO  VARCHAR2(100) --「貸与品明細備考」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2117T_PK PRIMARY KEY(
	 TAIYOHIN_KANRI_ID
	,  TAIYOHIN_MEISAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2117T_TBL IS '貸与品明細テーブル'
/

COMMENT ON COLUMN ED2117T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2117T_TBL.TAIYOHIN_KANRI_ID IS '貸与品管理ＩＤ'
/
COMMENT ON COLUMN ED2117T_TBL.TAIYOHIN_MEISAI_SN IS '貸与品明細連番'
/
COMMENT ON COLUMN ED2117T_TBL.KOTAI_NO IS '個体番号'
/
COMMENT ON COLUMN ED2117T_TBL.SHOHI_KIGEN_YM IS '消費期限年月'
/
COMMENT ON COLUMN ED2117T_TBL.TAIYO_SURYO IS '貸与数量'
/
COMMENT ON COLUMN ED2117T_TBL.HOKAN_KAISHI_YMD IS '保管開始年月日'
/
COMMENT ON COLUMN ED2117T_TBL.HAIKI_YMD IS '廃棄年月日'
/
COMMENT ON COLUMN ED2117T_TBL.TAIYOHIN_MEISAI_BIKO IS '貸与品明細備考'
/
COMMENT ON COLUMN ED2117T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2117T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2117T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2117T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2117T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2117T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2117T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2117T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2117T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2117T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2117T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2117T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
