/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2120T_TBL.sql
-- 物理名：ED2120T_TBL
-- 論理名：貸与先異動テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2120T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2120T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TAIYO_TAISHOSAKI_KBN  CHAR(1) NOT NULL --「貸与対象先区分」
	,TAIYOSAKI_CD  VARCHAR2(8) NOT NULL --「貸与先コード」
	,DEMPYO_KIHYO_JIGYOSHO_CD  CHAR(6) NOT NULL --「伝票起票事業所コード」
	,IDO_YMD  DATE NOT NULL --「異動年月日」
	,IDO_NYUSHUTSU_KBN  CHAR(1) NOT NULL --「異動入出区分」
	,IDOMOTO_KANRI_JIGYOSHO_CD  CHAR(6) NOT NULL --「異動元管理事業所コード」
	,IDOMOTO_SHOZOKU_JIGYOSHO_CD  CHAR(6) NOT NULL --「異動元所属事業所コード」
	,IDOSAKI_KANRI_JIGYOSHO_CD  CHAR(6) NOT NULL --「異動先管理事業所コード」
	,IDOSAKI_SHOZOKU_JIGYOSHO_CD  CHAR(6) NOT NULL --「異動先所属事業所コード」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2120T_PK PRIMARY KEY(
	 TAIYOSAKI_CD
	,  TAIYO_TAISHOSAKI_KBN
	,  IDO_YMD
	,  DEMPYO_KIHYO_JIGYOSHO_CD
	,  IDO_NYUSHUTSU_KBN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2120T_TBL IS '貸与先異動テーブル'
/

COMMENT ON COLUMN ED2120T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2120T_TBL.TAIYO_TAISHOSAKI_KBN IS '貸与対象先区分'
/
COMMENT ON COLUMN ED2120T_TBL.TAIYOSAKI_CD IS '貸与先コード'
/
COMMENT ON COLUMN ED2120T_TBL.DEMPYO_KIHYO_JIGYOSHO_CD IS '伝票起票事業所コード'
/
COMMENT ON COLUMN ED2120T_TBL.IDO_YMD IS '異動年月日'
/
COMMENT ON COLUMN ED2120T_TBL.IDO_NYUSHUTSU_KBN IS '異動入出区分'
/
COMMENT ON COLUMN ED2120T_TBL.IDOMOTO_KANRI_JIGYOSHO_CD IS '異動元管理事業所コード'
/
COMMENT ON COLUMN ED2120T_TBL.IDOMOTO_SHOZOKU_JIGYOSHO_CD IS '異動元所属事業所コード'
/
COMMENT ON COLUMN ED2120T_TBL.IDOSAKI_KANRI_JIGYOSHO_CD IS '異動先管理事業所コード'
/
COMMENT ON COLUMN ED2120T_TBL.IDOSAKI_SHOZOKU_JIGYOSHO_CD IS '異動先所属事業所コード'
/
COMMENT ON COLUMN ED2120T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED2120T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2120T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2120T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2120T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2120T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2120T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2120T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2120T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2120T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2120T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2120T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2120T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
