/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2104T_TBL.sql
-- 物理名：ED2104T_TBL
-- 論理名：商品振替テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2104T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2104T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SHOHIN_FURIKAE_DEMPYO_NO  CHAR(17) NOT NULL --「商品振替伝票番号」
	,DEMPYO_JOTAI_KBN  CHAR(1) NOT NULL --「伝票状態区分」
	,SHIZAI_SOBI_KBN  CHAR(1) NOT NULL --「資材装備区分」
	,DEMPYO_KIHYO_JIGYOSHO_CD  CHAR(6) NOT NULL --「伝票起票事業所コード」
	,SHOHIN_FURIKAE_JIGYOSHO_CD  CHAR(6) NOT NULL --「商品振替事業所コード」
	,SHOHIN_FURIKAE_SOKO_CD  CHAR(6) NOT NULL --「商品振替倉庫コード」
	,SHOHIN_FURIKAE_KBN  CHAR(1) NOT NULL --「商品振替区分」
	,SHOHIN_FURIKAE_YMD  DATE --「商品振替年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2104T_PK PRIMARY KEY(
	 SHOHIN_FURIKAE_DEMPYO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2104T_TBL IS '商品振替テーブル'
/

COMMENT ON COLUMN ED2104T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2104T_TBL.SHOHIN_FURIKAE_DEMPYO_NO IS '商品振替伝票番号'
/
COMMENT ON COLUMN ED2104T_TBL.DEMPYO_JOTAI_KBN IS '伝票状態区分'
/
COMMENT ON COLUMN ED2104T_TBL.SHIZAI_SOBI_KBN IS '資材装備区分'
/
COMMENT ON COLUMN ED2104T_TBL.DEMPYO_KIHYO_JIGYOSHO_CD IS '伝票起票事業所コード'
/
COMMENT ON COLUMN ED2104T_TBL.SHOHIN_FURIKAE_JIGYOSHO_CD IS '商品振替事業所コード'
/
COMMENT ON COLUMN ED2104T_TBL.SHOHIN_FURIKAE_SOKO_CD IS '商品振替倉庫コード'
/
COMMENT ON COLUMN ED2104T_TBL.SHOHIN_FURIKAE_KBN IS '商品振替区分'
/
COMMENT ON COLUMN ED2104T_TBL.SHOHIN_FURIKAE_YMD IS '商品振替年月日'
/
COMMENT ON COLUMN ED2104T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2104T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2104T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2104T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2104T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2104T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2104T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2104T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2104T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2104T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2104T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2104T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
