/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2105T_TBL.sql
-- 物理名：ED2105T_TBL
-- 論理名：商品振替明細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2105T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2105T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SHOHIN_FURIKAE_DEMPYO_NO  CHAR(17) NOT NULL --「商品振替伝票番号」
	,SHHN_FRKE_DMPY_MISI_SN  CHAR(14) NOT NULL --「商品振替伝票明細連番」
	,FURIKAE_MOTOSAKI_KBN  CHAR(1) NOT NULL --「振替元先区分」
	,HIMMEI_CD  CHAR(8) NOT NULL --「品名コード」
	,TANKA_RIREKI_NO  CHAR(4) NOT NULL --「単価履歴番号」
	,FURIKAE_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「振替数量」
	,FURIKAE_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「振替単価金額」
	,JIGYO_SEGMENT_CD  CHAR(3) NOT NULL --「事業セグメントコード」
	,CHOZOHIN_KBN  CHAR(2) NOT NULL --「貯蔵品区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2105T_PK PRIMARY KEY(
	 SHOHIN_FURIKAE_DEMPYO_NO
	,  SHHN_FRKE_DMPY_MISI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2105T_TBL IS '商品振替明細テーブル'
/

COMMENT ON COLUMN ED2105T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2105T_TBL.SHOHIN_FURIKAE_DEMPYO_NO IS '商品振替伝票番号'
/
COMMENT ON COLUMN ED2105T_TBL.SHHN_FRKE_DMPY_MISI_SN IS '商品振替伝票明細連番'
/
COMMENT ON COLUMN ED2105T_TBL.FURIKAE_MOTOSAKI_KBN IS '振替元先区分'
/
COMMENT ON COLUMN ED2105T_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED2105T_TBL.TANKA_RIREKI_NO IS '単価履歴番号'
/
COMMENT ON COLUMN ED2105T_TBL.FURIKAE_SURYO IS '振替数量'
/
COMMENT ON COLUMN ED2105T_TBL.FURIKAE_TANKA_AMT IS '振替単価金額'
/
COMMENT ON COLUMN ED2105T_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED2105T_TBL.CHOZOHIN_KBN IS '貯蔵品区分'
/
COMMENT ON COLUMN ED2105T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2105T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2105T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2105T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2105T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2105T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2105T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2105T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2105T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2105T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2105T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2105T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
