/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2126T_TBL.sql
-- 物理名：ED2126T_TBL
-- 論理名：在庫テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2126T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2126T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SHIZAI_SOBI_KBN  CHAR(1) NOT NULL --「資材装備区分」
	,CHOZOHIN_SHUKAN_JIGYOSHO_CD  CHAR(6) NOT NULL --「貯蔵品主管事業所コード」
	,CHOZOHIN_SHUKAN_SOKO_CD  CHAR(6) NOT NULL --「貯蔵品主管倉庫コード」
	,HIMMEI_CD  CHAR(8) NOT NULL --「品名コード」
	,TANKA_RIREKI_NO  CHAR(4) NOT NULL --「単価履歴番号」
	,SHIMPIN_KBN  CHAR(1) NOT NULL --「新品区分」
	,SHIIRE_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「仕入単価金額」
	,UKEIRE_YMD  DATE --「受入年月日」
	,CHOBO_ZAIKO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「帳簿在庫数量」
	,YUKO_ZAIKO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「有効在庫数量」
	,KAKUHOZUMI_YUKO_ZAIKO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「確保済有効在庫数量」
	,SHURICHU_ZAIKO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「修理中在庫数量」
	,HAIKI_YOTEIHIN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「廃棄予定品数量」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2126T_PK PRIMARY KEY(
	 HIMMEI_CD
	,  CHOZOHIN_SHUKAN_JIGYOSHO_CD
	,  CHOZOHIN_SHUKAN_SOKO_CD
	,  KAISHA_CD
	,  TANKA_RIREKI_NO
	,  SHIMPIN_KBN
	,  SHIZAI_SOBI_KBN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2126T_TBL IS '在庫テーブル'
/

COMMENT ON COLUMN ED2126T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2126T_TBL.SHIZAI_SOBI_KBN IS '資材装備区分'
/
COMMENT ON COLUMN ED2126T_TBL.CHOZOHIN_SHUKAN_JIGYOSHO_CD IS '貯蔵品主管事業所コード'
/
COMMENT ON COLUMN ED2126T_TBL.CHOZOHIN_SHUKAN_SOKO_CD IS '貯蔵品主管倉庫コード'
/
COMMENT ON COLUMN ED2126T_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED2126T_TBL.TANKA_RIREKI_NO IS '単価履歴番号'
/
COMMENT ON COLUMN ED2126T_TBL.SHIMPIN_KBN IS '新品区分'
/
COMMENT ON COLUMN ED2126T_TBL.SHIIRE_TANKA_AMT IS '仕入単価金額'
/
COMMENT ON COLUMN ED2126T_TBL.UKEIRE_YMD IS '受入年月日'
/
COMMENT ON COLUMN ED2126T_TBL.CHOBO_ZAIKO_SURYO IS '帳簿在庫数量'
/
COMMENT ON COLUMN ED2126T_TBL.YUKO_ZAIKO_SURYO IS '有効在庫数量'
/
COMMENT ON COLUMN ED2126T_TBL.KAKUHOZUMI_YUKO_ZAIKO_SURYO IS '確保済有効在庫数量'
/
COMMENT ON COLUMN ED2126T_TBL.SHURICHU_ZAIKO_SURYO IS '修理中在庫数量'
/
COMMENT ON COLUMN ED2126T_TBL.HAIKI_YOTEIHIN_SURYO IS '廃棄予定品数量'
/
COMMENT ON COLUMN ED2126T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2126T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2126T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2126T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2126T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2126T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2126T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2126T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2126T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2126T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2126T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2126T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
