/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2127T_TBL.sql
-- 物理名：ED2127T_TBL
-- 論理名：入出庫テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2127T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2127T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,DEMPYO_SHOSAI_KBN  CHAR(3) NOT NULL --「伝票詳細区分」
	,DEMPYO_NO  CHAR(17) NOT NULL --「伝票番号」
	,DEMPYO_MEISAI_SN  CHAR(14) NOT NULL --「伝票明細連番」
	,NYUSHUKKO_SN  CHAR(14) NOT NULL --「入出庫連番」
	,SHIZAI_SOBI_KBN  CHAR(1) NOT NULL --「資材装備区分」
	,CHOZOHIN_SHUKAN_JIGYOSHO_CD  CHAR(6) NOT NULL --「貯蔵品主管事業所コード」
	,CHOZOHIN_SHUKAN_SOKO_CD  CHAR(6) NOT NULL --「貯蔵品主管倉庫コード」
	,HIMMEI_CD  CHAR(8) NOT NULL --「品名コード」
	,TANKA_RIREKI_NO  CHAR(4) NOT NULL --「単価履歴番号」
	,SHIMPIN_KBN  CHAR(1) NOT NULL --「新品区分」
	,DEMPYO_KBN  CHAR(1) NOT NULL --「伝票区分」
	,NYUSHUKKO_KBN  CHAR(1) NOT NULL --「入出庫区分」
	,NYUKO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「入庫数量」
	,SHUKKO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「出庫数量」
	,NYUSHUKKO_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「入出庫数量」
	,NYUSHUKKO_YMD  DATE --「入出庫年月日」
	,NYUSHUKKO_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「入出庫単価金額」
	,NYUSHUKKO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「入出庫金額」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,NYUSHUKKO_TORIHIKISAKI_CD  CHAR(9) --「入出庫取引先コード」
	,NYSHKK_TRHKSK_BSH_CD  CHAR(4) --「入出庫取引先部署コード」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2127T_PK PRIMARY KEY(
	 DEMPYO_NO
	,  DEMPYO_MEISAI_SN
	,  NYUSHUKKO_SN
	,  DEMPYO_SHOSAI_KBN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2127T_TBL IS '入出庫テーブル'
/

COMMENT ON COLUMN ED2127T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2127T_TBL.DEMPYO_SHOSAI_KBN IS '伝票詳細区分'
/
COMMENT ON COLUMN ED2127T_TBL.DEMPYO_NO IS '伝票番号'
/
COMMENT ON COLUMN ED2127T_TBL.DEMPYO_MEISAI_SN IS '伝票明細連番'
/
COMMENT ON COLUMN ED2127T_TBL.NYUSHUKKO_SN IS '入出庫連番'
/
COMMENT ON COLUMN ED2127T_TBL.SHIZAI_SOBI_KBN IS '資材装備区分'
/
COMMENT ON COLUMN ED2127T_TBL.CHOZOHIN_SHUKAN_JIGYOSHO_CD IS '貯蔵品主管事業所コード'
/
COMMENT ON COLUMN ED2127T_TBL.CHOZOHIN_SHUKAN_SOKO_CD IS '貯蔵品主管倉庫コード'
/
COMMENT ON COLUMN ED2127T_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED2127T_TBL.TANKA_RIREKI_NO IS '単価履歴番号'
/
COMMENT ON COLUMN ED2127T_TBL.SHIMPIN_KBN IS '新品区分'
/
COMMENT ON COLUMN ED2127T_TBL.DEMPYO_KBN IS '伝票区分'
/
COMMENT ON COLUMN ED2127T_TBL.NYUSHUKKO_KBN IS '入出庫区分'
/
COMMENT ON COLUMN ED2127T_TBL.NYUKO_SURYO IS '入庫数量'
/
COMMENT ON COLUMN ED2127T_TBL.SHUKKO_SURYO IS '出庫数量'
/
COMMENT ON COLUMN ED2127T_TBL.NYUSHUKKO_SURYO IS '入出庫数量'
/
COMMENT ON COLUMN ED2127T_TBL.NYUSHUKKO_YMD IS '入出庫年月日'
/
COMMENT ON COLUMN ED2127T_TBL.NYUSHUKKO_TANKA_AMT IS '入出庫単価金額'
/
COMMENT ON COLUMN ED2127T_TBL.NYUSHUKKO_AMT IS '入出庫金額'
/
COMMENT ON COLUMN ED2127T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED2127T_TBL.NYUSHUKKO_TORIHIKISAKI_CD IS '入出庫取引先コード'
/
COMMENT ON COLUMN ED2127T_TBL.NYSHKK_TRHKSK_BSH_CD IS '入出庫取引先部署コード'
/
COMMENT ON COLUMN ED2127T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2127T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2127T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2127T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2127T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2127T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2127T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2127T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2127T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2127T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2127T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2127T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
