/* ---------------------------------------------------------------------- */
-- インデックス作成DDL(ORACLE用)
-- ファイル名：ED2103T_IDX.sql
-- 対象テーブル（物理名）：ED2103T_TBL
-- 対象テーブル（論理名）：修理管理台帳テーブル
/* ---------------------------------------------------------------------- */

CREATE INDEX ED2103T_IDX01 ON ED2103T_TBL(
	SHINSEI_SHONIN_NO 
)
/

CREATE INDEX ED2103T_IDX02 ON ED2103T_TBL(
	SHURI_IRAIMOTO_JIGYOSHO_CD,
	SHURI_SHINCHOKU_JOKYO_KBN 
)
/

CREATE INDEX ED2103T_IDX03 ON ED2103T_TBL(
	SHRH_SIKYSK_TRHKSK_CD,
	SHURI_SHINCHOKU_JOKYO_KBN 
)
/

CREATE INDEX ED2103T_IDX04 ON ED2103T_TBL(
	HIMMEI_CD 
)
/

CREATE INDEX ED2103T_IDX05 ON ED2103T_TBL(
	BIKYKHN_HMBI_JCH_KIYK_NO 
)
/

CREATE INDEX ED2103T_IDX06 ON ED2103T_TBL(
	SHRH_SIKY_JCH_KIYK_NO 
)
/

CREATE INDEX ED2103T_IDX07 ON ED2103T_TBL(
	URIAGE_DEMPYO_NO 
)
/
