/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2123T_TBL.sql
-- 物理名：ED2123T_TBL
-- 論理名：事業所別月次状況テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2123T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2123T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,EIGYO_KANRI_YM  CHAR(6) NOT NULL --「営業管理年月」
	,SHIZAI_SOBI_KBN  CHAR(1) NOT NULL --「資材装備区分」
	,GETSUJI_SHORI_JIGYOSHO_CD  CHAR(6) NOT NULL --「月次処理事業所コード」
	,TANAOROSHI_JOKYO_KBN  CHAR(1) NOT NULL --「棚卸状況区分」
	,KARIJIME_CHECK_JOKYO_KBN  CHAR(1) NOT NULL --「仮締めチェック状況区分」
	,GEPPO_TOKKI_JIKO  VARCHAR2(1000) --「月報特記事項」
	,GETSUJI_ZAIKO_KAKUTEI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「月次在庫確定フラグ」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2123T_PK PRIMARY KEY(
	 GETSUJI_SHORI_JIGYOSHO_CD
	,  KAISHA_CD
	,  EIGYO_KANRI_YM
	,  SHIZAI_SOBI_KBN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2123T_TBL IS '事業所別月次状況テーブル'
/

COMMENT ON COLUMN ED2123T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2123T_TBL.EIGYO_KANRI_YM IS '営業管理年月'
/
COMMENT ON COLUMN ED2123T_TBL.SHIZAI_SOBI_KBN IS '資材装備区分'
/
COMMENT ON COLUMN ED2123T_TBL.GETSUJI_SHORI_JIGYOSHO_CD IS '月次処理事業所コード'
/
COMMENT ON COLUMN ED2123T_TBL.TANAOROSHI_JOKYO_KBN IS '棚卸状況区分'
/
COMMENT ON COLUMN ED2123T_TBL.KARIJIME_CHECK_JOKYO_KBN IS '仮締めチェック状況区分'
/
COMMENT ON COLUMN ED2123T_TBL.GEPPO_TOKKI_JIKO IS '月報特記事項'
/
COMMENT ON COLUMN ED2123T_TBL.GETSUJI_ZAIKO_KAKUTEI_FLG IS '月次在庫確定フラグ'
/
COMMENT ON COLUMN ED2123T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED2123T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2123T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2123T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2123T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2123T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2123T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2123T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2123T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2123T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2123T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2123T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2123T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
