/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2106T_TBL.sql
-- 物理名：ED2106T_TBL
-- 論理名：返品テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2106T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2106T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,HEMPIN_DEMPYO_NO  CHAR(17) NOT NULL --「返品伝票番号」
	,DEMPYO_JOTAI_KBN  CHAR(1) NOT NULL --「伝票状態区分」
	,SHIZAI_SOBI_KBN  CHAR(1) NOT NULL --「資材装備区分」
	,DEMPYO_KIHYO_JIGYOSHO_CD  CHAR(6) NOT NULL --「伝票起票事業所コード」
	,HATCHUSAKI_KBN  CHAR(1) NOT NULL --「発注先区分」
	,HEMPIMMOTO_JIGYOSHO_CD  CHAR(6) NOT NULL --「返品元事業所コード」
	,HEMPIMMOTO_SOKO_CD  CHAR(6) NOT NULL --「返品元倉庫コード」
	,HMPNSK_GYSH_TRHKSK_CD  CHAR(9) --「返品先業者取引先コード」
	,HMPNSK_GYSH_TRHKSK_BSH_CD  CHAR(4) --「返品先業者取引先部署コード」
	,SOSAI_KBN  CHAR(1) NOT NULL --「相殺区分」
	,HARAIMODOSHI_JIGYOSHO_CD  CHAR(6) NOT NULL --「払戻事業所コード」
	,HEMPIN_IRAI_YMD  DATE NOT NULL --「返品依頼年月日」
	,HEMPIN_YMD  DATE --「返品年月日」
	,NOHIN_DEMPYO_NO  CHAR(17) --「納品伝票番号」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2106T_PK PRIMARY KEY(
	 HEMPIN_DEMPYO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2106T_TBL IS '返品テーブル'
/

COMMENT ON COLUMN ED2106T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2106T_TBL.HEMPIN_DEMPYO_NO IS '返品伝票番号'
/
COMMENT ON COLUMN ED2106T_TBL.DEMPYO_JOTAI_KBN IS '伝票状態区分'
/
COMMENT ON COLUMN ED2106T_TBL.SHIZAI_SOBI_KBN IS '資材装備区分'
/
COMMENT ON COLUMN ED2106T_TBL.DEMPYO_KIHYO_JIGYOSHO_CD IS '伝票起票事業所コード'
/
COMMENT ON COLUMN ED2106T_TBL.HATCHUSAKI_KBN IS '発注先区分'
/
COMMENT ON COLUMN ED2106T_TBL.HEMPIMMOTO_JIGYOSHO_CD IS '返品元事業所コード'
/
COMMENT ON COLUMN ED2106T_TBL.HEMPIMMOTO_SOKO_CD IS '返品元倉庫コード'
/
COMMENT ON COLUMN ED2106T_TBL.HMPNSK_GYSH_TRHKSK_CD IS '返品先業者取引先コード'
/
COMMENT ON COLUMN ED2106T_TBL.HMPNSK_GYSH_TRHKSK_BSH_CD IS '返品先業者取引先部署コード'
/
COMMENT ON COLUMN ED2106T_TBL.SOSAI_KBN IS '相殺区分'
/
COMMENT ON COLUMN ED2106T_TBL.HARAIMODOSHI_JIGYOSHO_CD IS '払戻事業所コード'
/
COMMENT ON COLUMN ED2106T_TBL.HEMPIN_IRAI_YMD IS '返品依頼年月日'
/
COMMENT ON COLUMN ED2106T_TBL.HEMPIN_YMD IS '返品年月日'
/
COMMENT ON COLUMN ED2106T_TBL.NOHIN_DEMPYO_NO IS '納品伝票番号'
/
COMMENT ON COLUMN ED2106T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED2106T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2106T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2106T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2106T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2106T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2106T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2106T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2106T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2106T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2106T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2106T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2106T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
