/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2200W_TBL.sql
-- 物理名：ED2200W_TBL
-- 論理名：通知配信ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2200W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2200W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TSUCHI_HAISHIN_KANRI_ID  CHAR(16) NOT NULL --「通知配信管理ＩＤ」
	,HAISHIN_HOHO_KBN  CHAR(1) NOT NULL --「配信方法区分」
	,IRAIMOTO_KAISHA_CD  CHAR(5) --「依頼元会社コード」
	,IRIMT_JIGYOSHO_CD  CHAR(6) --「依頼元事業所コード」
	,IRIMT_SHAIN_NO  VARCHAR2(8) --「依頼元社員番号」
	,ATESAKI_KAISHA_CD  CHAR(5) --「宛先会社コード」
	,ATESAKI_JIGYOSHO_CD  CHAR(6) --「宛先事業所コード」
	,ATESAKI_SHAIN_NO  VARCHAR2(8) --「宛先社員番号」
	,RENRAKU_YMD  DATE --「連絡年月日」
	,TSUCHIZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「通知済フラグ」
	,TASK_TSUCHI_BUNRUI_CD  CHAR(6) --「タスク通知分類コード」
	,TASK_TSUCHI_NAIYO_PARAMETER  VARCHAR2(1000) --「タスク通知内容パラメータ」
	,SENISAKI_GAMEN_ID  CHAR(15) --「遷移先画面ＩＤ」
	,KIDO_PARAMETER  CLOB --「起動パラメータ」
	,ATESAKI_MAIL_ADDRESS  VARCHAR2(200) --「宛先メールアドレス」
	,EDI_MAIL_TEMPLATE_ID  NUMBER(4,0) DEFAULT '0' NOT NULL --「ＥＤＩメールテンプレートＩＤ」
	,MAIL_PARAMETER  VARCHAR2(100) --「メールパラメータ」
	,TSUCHIMOTO_DATA_SHKBTS_KEY_1  VARCHAR2(50) --「通知元データ識別キー１」
	,TSUCHIMOTO_DATA_SHKBTS_KEY_2  VARCHAR2(50) --「通知元データ識別キー２」
	,TSUCHIMOTO_DATA_SHKBTS_KEY_3  VARCHAR2(50) --「通知元データ識別キー３」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2200W_PK PRIMARY KEY(
	 TSUCHI_HAISHIN_KANRI_ID
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2200W_TBL IS '通知配信ワーク'
/

COMMENT ON COLUMN ED2200W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2200W_TBL.TSUCHI_HAISHIN_KANRI_ID IS '通知配信管理ＩＤ'
/
COMMENT ON COLUMN ED2200W_TBL.HAISHIN_HOHO_KBN IS '配信方法区分'
/
COMMENT ON COLUMN ED2200W_TBL.IRAIMOTO_KAISHA_CD IS '依頼元会社コード'
/
COMMENT ON COLUMN ED2200W_TBL.IRIMT_JIGYOSHO_CD IS '依頼元事業所コード'
/
COMMENT ON COLUMN ED2200W_TBL.IRIMT_SHAIN_NO IS '依頼元社員番号'
/
COMMENT ON COLUMN ED2200W_TBL.ATESAKI_KAISHA_CD IS '宛先会社コード'
/
COMMENT ON COLUMN ED2200W_TBL.ATESAKI_JIGYOSHO_CD IS '宛先事業所コード'
/
COMMENT ON COLUMN ED2200W_TBL.ATESAKI_SHAIN_NO IS '宛先社員番号'
/
COMMENT ON COLUMN ED2200W_TBL.RENRAKU_YMD IS '連絡年月日'
/
COMMENT ON COLUMN ED2200W_TBL.TSUCHIZUMI_FLG IS '通知済フラグ'
/
COMMENT ON COLUMN ED2200W_TBL.TASK_TSUCHI_BUNRUI_CD IS 'タスク通知分類コード'
/
COMMENT ON COLUMN ED2200W_TBL.TASK_TSUCHI_NAIYO_PARAMETER IS 'タスク通知内容パラメータ'
/
COMMENT ON COLUMN ED2200W_TBL.SENISAKI_GAMEN_ID IS '遷移先画面ＩＤ'
/
COMMENT ON COLUMN ED2200W_TBL.KIDO_PARAMETER IS '起動パラメータ'
/
COMMENT ON COLUMN ED2200W_TBL.ATESAKI_MAIL_ADDRESS IS '宛先メールアドレス'
/
COMMENT ON COLUMN ED2200W_TBL.EDI_MAIL_TEMPLATE_ID IS 'ＥＤＩメールテンプレートＩＤ'
/
COMMENT ON COLUMN ED2200W_TBL.MAIL_PARAMETER IS 'メールパラメータ'
/
COMMENT ON COLUMN ED2200W_TBL.TSUCHIMOTO_DATA_SHKBTS_KEY_1 IS '通知元データ識別キー１'
/
COMMENT ON COLUMN ED2200W_TBL.TSUCHIMOTO_DATA_SHKBTS_KEY_2 IS '通知元データ識別キー２'
/
COMMENT ON COLUMN ED2200W_TBL.TSUCHIMOTO_DATA_SHKBTS_KEY_3 IS '通知元データ識別キー３'
/
COMMENT ON COLUMN ED2200W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2200W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2200W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2200W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2200W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2200W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2200W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2200W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2200W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2200W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2200W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2200W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
