/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2503T_TBL.sql
-- 物理名：ED2503T_TBL
-- 論理名：業務委託先申請テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2503T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2503T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,GYM_ITKSK_TRHKSK_CD  CHAR(9) NOT NULL --「業務委託先取引先コード」
	,GYM_ITKSK_TRHKSK_BSH_CD  CHAR(4) NOT NULL --「業務委託先取引先部署コード」
	,GYOMU_ITAKUSAKI_SHINSEI_SN  CHAR(14) NOT NULL --「業務委託先申請連番」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,SHINSEI_SHONIN_STATUS_KBN  CHAR(1) NOT NULL --「申請承認ステータス区分」
	,GYOMU_ITAKUSAKI_SHINSEI_KBN  CHAR(1) NOT NULL --「業務委託先申請区分」
	,GYOMU_ITAKUSAKI_SHINSEI_YMD  DATE --「業務委託先申請年月日」
	,GYM_ITKSK_SHNSI_JIGYOSHO_CD  CHAR(6) --「業務委託先申請事業所コード」
	,GYM_ITKSK_SHNSI_SISH_SHNN_YMD  DATE --「業務委託先申請最終承認年月日」
	,GYM_ITKSK_SHNSI_RIYU_NAIYO  VARCHAR2(100) --「業務委託先申請理由内容」
	,GYOMU_SHURUI_KBN  CHAR(1) NOT NULL --「業務種類区分」
	,GYOMU_ITAKU_TORIHIKISAKI_SN  CHAR(14) --「業務委託取引先連番」
	,KKI_KIB_TDKD_TIK_SHOSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「機械警備届出待機所数」
	,KIKAI_KEIBI_KICHI_KYOKUSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「機械警備基地局数」
	,KEISO_GENSOSHA_HOYU_DAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「警送現送車保有台数」
	,KIS_SHRY_BHN_SCH_SB_HYK_KBN  CHAR(1) NOT NULL --「警送車両防犯装置装備評価区分」
	,KEISO_UNKO_KANRISHA_NINZU  NUMBER(9,0) DEFAULT '0' NOT NULL --「警送運行管理者人数」
	,KEISO_UNKO_KANRI_TAISEI_KBN  CHAR(1) NOT NULL --「警送運行管理体制区分」
	,KEISO_KINKO_MENSEKI  NUMBER(9,0) DEFAULT '0' NOT NULL --「警送金庫面積」
	,KIS_KNK_BHN_CAMERA_AR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警送金庫防犯カメラ有フラグ」
	,KIS_KNK_SHTSNY_KNR_HH_NAIYO  VARCHAR2(50) --「警送金庫出入管理方法内容」
	,KIS_KNK_KIB_JKYT_NAIYO  VARCHAR2(50) --「警送金庫警備状況等内容」
	,KEISO_KEIBI_YUSO_JISSEKI_NENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「警送警備輸送実績年数」
	,KIS_GNKN_SIST_JSSK_NENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「警送現金精査等実績年数」
	,KEISO_HOKAN_JISSEKI_NENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「警送保管実績年数」
	,SOGO_KANRI_SEISO_KANRYOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「綜合管理清掃管理有フラグ」
	,SG_KNR_KNKY_EISI_KNRYAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「綜合管理環境衛生管理有フラグ」
	,SG_KNR_STSB_KNRYAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「綜合管理設備管理有フラグ」
	,SG_KNR_KNCHKBN_HZN_KNRYAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「綜合管理建築分保全管理有フラグ」
	,SG_KNR_KNR_SERVICE_AR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「綜合管理管理サービス有フラグ」
	,SOGO_KANRI_KOJIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「綜合管理工事有フラグ」
	,SOGO_KANRI_SONOTAARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「綜合管理その他有フラグ」
	,BOSAI_TENKENARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「防災点検有フラグ」
	,BOSAI_KOJIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「防災工事有フラグ」
	,SNT_ITK_GYM_SHSI_NAIYO  VARCHAR2(30) --「その他委託業務詳細内容」
	,GMITS_SKST_TRHKSK_SHHRI_JH_CD  CHAR(4) --「業務委託先初期設定取引先支払情報コード」
	,GYM_ITKSK_KYTI_JIKO_TIKTS_YMD  DATE --「業務委託先協定事項締結年月日」
	,GMITS_KJGM_KTJK_TEIKETSU_YMD  DATE --「業務委託先工事業務協定事項締結年月日」
	,GYOMU_ITAKUSAKI_KYOTEI_JIKO_NM  VARCHAR2(10) --「業務委託先協定事項名称」
	,GYM_ITKSK_SISHNS_KKN_NENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「業務委託先再審査期間年数」
	,GYM_ITKSK_KYTI_JIKO_KSHN_YMD  DATE --「業務委託先協定事項更新年月日」
	,GYM_ITKSK_KYTI_JIKO_MNRY_YM  CHAR(6) --「業務委託先協定事項満了年月」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2503T_PK PRIMARY KEY(
	 GYM_ITKSK_TRHKSK_CD
	,  GYM_ITKSK_TRHKSK_BSH_CD
	,  GYOMU_ITAKUSAKI_SHINSEI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2503T_TBL IS '業務委託先申請テーブル'
/

COMMENT ON COLUMN ED2503T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2503T_TBL.GYM_ITKSK_TRHKSK_CD IS '業務委託先取引先コード'
/
COMMENT ON COLUMN ED2503T_TBL.GYM_ITKSK_TRHKSK_BSH_CD IS '業務委託先取引先部署コード'
/
COMMENT ON COLUMN ED2503T_TBL.GYOMU_ITAKUSAKI_SHINSEI_SN IS '業務委託先申請連番'
/
COMMENT ON COLUMN ED2503T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED2503T_TBL.SHINSEI_SHONIN_STATUS_KBN IS '申請承認ステータス区分'
/
COMMENT ON COLUMN ED2503T_TBL.GYOMU_ITAKUSAKI_SHINSEI_KBN IS '業務委託先申請区分'
/
COMMENT ON COLUMN ED2503T_TBL.GYOMU_ITAKUSAKI_SHINSEI_YMD IS '業務委託先申請年月日'
/
COMMENT ON COLUMN ED2503T_TBL.GYM_ITKSK_SHNSI_JIGYOSHO_CD IS '業務委託先申請事業所コード'
/
COMMENT ON COLUMN ED2503T_TBL.GYM_ITKSK_SHNSI_SISH_SHNN_YMD IS '業務委託先申請最終承認年月日'
/
COMMENT ON COLUMN ED2503T_TBL.GYM_ITKSK_SHNSI_RIYU_NAIYO IS '業務委託先申請理由内容'
/
COMMENT ON COLUMN ED2503T_TBL.GYOMU_SHURUI_KBN IS '業務種類区分'
/
COMMENT ON COLUMN ED2503T_TBL.GYOMU_ITAKU_TORIHIKISAKI_SN IS '業務委託取引先連番'
/
COMMENT ON COLUMN ED2503T_TBL.KKI_KIB_TDKD_TIK_SHOSU IS '機械警備届出待機所数'
/
COMMENT ON COLUMN ED2503T_TBL.KIKAI_KEIBI_KICHI_KYOKUSU IS '機械警備基地局数'
/
COMMENT ON COLUMN ED2503T_TBL.KEISO_GENSOSHA_HOYU_DAISU IS '警送現送車保有台数'
/
COMMENT ON COLUMN ED2503T_TBL.KIS_SHRY_BHN_SCH_SB_HYK_KBN IS '警送車両防犯装置装備評価区分'
/
COMMENT ON COLUMN ED2503T_TBL.KEISO_UNKO_KANRISHA_NINZU IS '警送運行管理者人数'
/
COMMENT ON COLUMN ED2503T_TBL.KEISO_UNKO_KANRI_TAISEI_KBN IS '警送運行管理体制区分'
/
COMMENT ON COLUMN ED2503T_TBL.KEISO_KINKO_MENSEKI IS '警送金庫面積'
/
COMMENT ON COLUMN ED2503T_TBL.KIS_KNK_BHN_CAMERA_AR_FLG IS '警送金庫防犯カメラ有フラグ'
/
COMMENT ON COLUMN ED2503T_TBL.KIS_KNK_SHTSNY_KNR_HH_NAIYO IS '警送金庫出入管理方法内容'
/
COMMENT ON COLUMN ED2503T_TBL.KIS_KNK_KIB_JKYT_NAIYO IS '警送金庫警備状況等内容'
/
COMMENT ON COLUMN ED2503T_TBL.KEISO_KEIBI_YUSO_JISSEKI_NENSU IS '警送警備輸送実績年数'
/
COMMENT ON COLUMN ED2503T_TBL.KIS_GNKN_SIST_JSSK_NENSU IS '警送現金精査等実績年数'
/
COMMENT ON COLUMN ED2503T_TBL.KEISO_HOKAN_JISSEKI_NENSU IS '警送保管実績年数'
/
COMMENT ON COLUMN ED2503T_TBL.SOGO_KANRI_SEISO_KANRYOARI_FLG IS '綜合管理清掃管理有フラグ'
/
COMMENT ON COLUMN ED2503T_TBL.SG_KNR_KNKY_EISI_KNRYAR_FLG IS '綜合管理環境衛生管理有フラグ'
/
COMMENT ON COLUMN ED2503T_TBL.SG_KNR_STSB_KNRYAR_FLG IS '綜合管理設備管理有フラグ'
/
COMMENT ON COLUMN ED2503T_TBL.SG_KNR_KNCHKBN_HZN_KNRYAR_FLG IS '綜合管理建築分保全管理有フラグ'
/
COMMENT ON COLUMN ED2503T_TBL.SG_KNR_KNR_SERVICE_AR_FLG IS '綜合管理管理サービス有フラグ'
/
COMMENT ON COLUMN ED2503T_TBL.SOGO_KANRI_KOJIARI_FLG IS '綜合管理工事有フラグ'
/
COMMENT ON COLUMN ED2503T_TBL.SOGO_KANRI_SONOTAARI_FLG IS '綜合管理その他有フラグ'
/
COMMENT ON COLUMN ED2503T_TBL.BOSAI_TENKENARI_FLG IS '防災点検有フラグ'
/
COMMENT ON COLUMN ED2503T_TBL.BOSAI_KOJIARI_FLG IS '防災工事有フラグ'
/
COMMENT ON COLUMN ED2503T_TBL.SNT_ITK_GYM_SHSI_NAIYO IS 'その他委託業務詳細内容'
/
COMMENT ON COLUMN ED2503T_TBL.GMITS_SKST_TRHKSK_SHHRI_JH_CD IS '業務委託先初期設定取引先支払情報コード'
/
COMMENT ON COLUMN ED2503T_TBL.GYM_ITKSK_KYTI_JIKO_TIKTS_YMD IS '業務委託先協定事項締結年月日'
/
COMMENT ON COLUMN ED2503T_TBL.GMITS_KJGM_KTJK_TEIKETSU_YMD IS '業務委託先工事業務協定事項締結年月日'
/
COMMENT ON COLUMN ED2503T_TBL.GYOMU_ITAKUSAKI_KYOTEI_JIKO_NM IS '業務委託先協定事項名称'
/
COMMENT ON COLUMN ED2503T_TBL.GYM_ITKSK_SISHNS_KKN_NENSU IS '業務委託先再審査期間年数'
/
COMMENT ON COLUMN ED2503T_TBL.GYM_ITKSK_KYTI_JIKO_KSHN_YMD IS '業務委託先協定事項更新年月日'
/
COMMENT ON COLUMN ED2503T_TBL.GYM_ITKSK_KYTI_JIKO_MNRY_YM IS '業務委託先協定事項満了年月'
/
COMMENT ON COLUMN ED2503T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2503T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2503T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2503T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2503T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2503T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2503T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2503T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2503T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2503T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2503T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2503T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
