/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2534W_TBL.sql
-- 物理名：ED2534W_TBL
-- 論理名：当月関係先送信ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2534W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2534W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,AED_KANRI_NO  CHAR(8) NOT NULL --「ＡＥＤ管理番号」
	,GYOMU_KAISHI_YMD  DATE --「業務開始年月日」
	,TORIHIKISAKI_CD  CHAR(9) --「取引先コード」
	,TORIHIKISAKI_SEISHIKI_NM  VARCHAR2(50) --「取引先正式名称」
	,TORIHIKISAKI_BUSHO_CD  CHAR(4) --「取引先部署コード」
	,TORIHIKISAKI_BUSHO_NM  VARCHAR2(40) --「取引先部署名称」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,TAISHOSAKI_NM  VARCHAR2(40) --「対象先名称」
	,TAISHOSAKI_YUBIN_NO  CHAR(7) --「対象先郵便番号」
	,TAISHOSAKI_JUSHO_CD  CHAR(11) --「対象先住所コード」
	,TODOFUKEN_NM  VARCHAR2(4) --「都道府県名称」
	,TAISHOSAKI_KETSUGO_JUSHO  VARCHAR2(200) --「対象先結合住所」
	,AED_END_USER_SETCHI_BASHO_NM  VARCHAR2(60) --「ＡＥＤエンドユーザ設置場所名称」
	,AED_END_USER_TANTO_BUSHO_NM  VARCHAR2(40) --「ＡＥＤエンドユーザ担当部署名称」
	,AED_END_USER_TANTOSHA_NM  VARCHAR2(60) --「ＡＥＤエンドユーザ担当者氏名」
	,AED_END_USER_TANTOSHA_DENWA_NO  VARCHAR2(20) --「ＡＥＤエンドユーザ担当者電話番号」
	,AED_KANRI_STATUS_KBN  CHAR(1) NOT NULL --「ＡＥＤ管理ステータス区分」
	,AED_SONOTA_BIKO  VARCHAR2(500) --「ＡＥＤその他備考」
	,AED_KANRI_SHURYO_YMD  DATE --「ＡＥＤ管理終了年月日」
	,AED_SEIHIN_KATASHIKI_NO  CHAR(12) --「ＡＥＤ製品型式番号」
	,AED_SERIAL_NO  VARCHAR2(20) --「ＡＥＤシリアル番号」
	,AED_KOKAN_RIYU_KBN  CHAR(1) NOT NULL --「ＡＥＤ交換理由区分」
	,AED_HAIKI_YMD  DATE --「ＡＥＤ廃棄年月日」
	,AED_HOKAN_JIGYOSHO_CD  CHAR(6) --「ＡＥＤ保管事業所コード」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2534W_PK PRIMARY KEY(
	 AED_KANRI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2534W_TBL IS '当月関係先送信ワーク'
/

COMMENT ON COLUMN ED2534W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2534W_TBL.AED_KANRI_NO IS 'ＡＥＤ管理番号'
/
COMMENT ON COLUMN ED2534W_TBL.GYOMU_KAISHI_YMD IS '業務開始年月日'
/
COMMENT ON COLUMN ED2534W_TBL.TORIHIKISAKI_CD IS '取引先コード'
/
COMMENT ON COLUMN ED2534W_TBL.TORIHIKISAKI_SEISHIKI_NM IS '取引先正式名称'
/
COMMENT ON COLUMN ED2534W_TBL.TORIHIKISAKI_BUSHO_CD IS '取引先部署コード'
/
COMMENT ON COLUMN ED2534W_TBL.TORIHIKISAKI_BUSHO_NM IS '取引先部署名称'
/
COMMENT ON COLUMN ED2534W_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED2534W_TBL.TAISHOSAKI_NM IS '対象先名称'
/
COMMENT ON COLUMN ED2534W_TBL.TAISHOSAKI_YUBIN_NO IS '対象先郵便番号'
/
COMMENT ON COLUMN ED2534W_TBL.TAISHOSAKI_JUSHO_CD IS '対象先住所コード'
/
COMMENT ON COLUMN ED2534W_TBL.TODOFUKEN_NM IS '都道府県名称'
/
COMMENT ON COLUMN ED2534W_TBL.TAISHOSAKI_KETSUGO_JUSHO IS '対象先結合住所'
/
COMMENT ON COLUMN ED2534W_TBL.AED_END_USER_SETCHI_BASHO_NM IS 'ＡＥＤエンドユーザ設置場所名称'
/
COMMENT ON COLUMN ED2534W_TBL.AED_END_USER_TANTO_BUSHO_NM IS 'ＡＥＤエンドユーザ担当部署名称'
/
COMMENT ON COLUMN ED2534W_TBL.AED_END_USER_TANTOSHA_NM IS 'ＡＥＤエンドユーザ担当者氏名'
/
COMMENT ON COLUMN ED2534W_TBL.AED_END_USER_TANTOSHA_DENWA_NO IS 'ＡＥＤエンドユーザ担当者電話番号'
/
COMMENT ON COLUMN ED2534W_TBL.AED_KANRI_STATUS_KBN IS 'ＡＥＤ管理ステータス区分'
/
COMMENT ON COLUMN ED2534W_TBL.AED_SONOTA_BIKO IS 'ＡＥＤその他備考'
/
COMMENT ON COLUMN ED2534W_TBL.AED_KANRI_SHURYO_YMD IS 'ＡＥＤ管理終了年月日'
/
COMMENT ON COLUMN ED2534W_TBL.AED_SEIHIN_KATASHIKI_NO IS 'ＡＥＤ製品型式番号'
/
COMMENT ON COLUMN ED2534W_TBL.AED_SERIAL_NO IS 'ＡＥＤシリアル番号'
/
COMMENT ON COLUMN ED2534W_TBL.AED_KOKAN_RIYU_KBN IS 'ＡＥＤ交換理由区分'
/
COMMENT ON COLUMN ED2534W_TBL.AED_HAIKI_YMD IS 'ＡＥＤ廃棄年月日'
/
COMMENT ON COLUMN ED2534W_TBL.AED_HOKAN_JIGYOSHO_CD IS 'ＡＥＤ保管事業所コード'
/
COMMENT ON COLUMN ED2534W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2534W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2534W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2534W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2534W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2534W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2534W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2534W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2534W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2534W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2534W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2534W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
