/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2525W_TBL.sql
-- 物理名：ED2525W_TBL
-- 論理名：警備事故発生報告書ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2525W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2525W_TBL (
	 KJH_KAISHA_CD  CHAR(5) NOT NULL --「ＫＪＨ＿会社コード」
	,KJH_SN  NUMBER(14,0) DEFAULT '0' NOT NULL --「ＫＪＨ＿連番」
	,KJH_DENKEI_NO  CHAR(9) --「ＫＪＨ＿電計番号」
	,KJH_KEIBISAKI_NM_1  VARCHAR2(40) --「ＫＪＨ＿警備先名称１」
	,KJH_KEIBISAKI_NM_2  VARCHAR2(20) --「ＫＪＨ＿警備先名称２」
	,KJH_KOBETSU_NM  VARCHAR2(20) --「ＫＪＨ＿個別名称」
	,KJH_SET_DT_YMD  CHAR(10) --「ＫＪＨ＿セット日時年月日」
	,KJH_SET_DT_JIFUN  CHAR(5) --「ＫＪＨ＿セット日時時分」
	,KJH_KEIBI_JOHO_MD_JIFUN_YMD  CHAR(10) --「ＫＪＨ＿警備情報月日時分年月日」
	,KJH_KEIBI_JOHO_MD_JIFUN_JIFUN  CHAR(5) --「ＫＪＨ＿警備情報月日時分時分」
	,KJH_KEIBI_JOHO  CHAR(20) --「ＫＪＨ＿警備情報」
	,KJH_GENIN_CD  CHAR(3) --「ＫＪＨ＿原因コード」
	,KJH_GENIN_SHOSAI_NAIYO_1  VARCHAR2(30) --「ＫＪＨ＿原因詳細内容１」
	,KJH_GENIN_SHOSAI_NAIYO_2  VARCHAR2(30) --「ＫＪＨ＿原因詳細内容２」
	,KJH_GENIN_SHOSAI_NAIYO_3  VARCHAR2(30) --「ＫＪＨ＿原因詳細内容３」
	,KJH_KEKKA_1  VARCHAR2(80) --「ＫＪＨ＿結果１」
	,KJH_KEKKA_2  VARCHAR2(80) --「ＫＪＨ＿結果２」
	,KJH_KEKKA_3  VARCHAR2(80) --「ＫＪＨ＿結果３」
	,KJH_KEKKA_4  VARCHAR2(80) --「ＫＪＨ＿結果４」
	,KJH_KEKKA_5  VARCHAR2(80) --「ＫＪＨ＿結果５」
	,KJH_KEKKA_6  VARCHAR2(80) --「ＫＪＨ＿結果６」
	,KJH_KEKKA_7  VARCHAR2(80) --「ＫＪＨ＿結果７」
	,KJH_KEKKA_8  VARCHAR2(80) --「ＫＪＨ＿結果８」
	,KJH_KEKKA_9  VARCHAR2(80) --「ＫＪＨ＿結果９」
	,KJH_KEKKA_10  VARCHAR2(80) --「ＫＪＨ＿結果１０」
	,KJH_TANTO_GENCHAKU  CHAR(4) --「ＫＪＨ＿担当現着」
	,KJH_KIDO_TAIKAN  CHAR(4) --「ＫＪＨ＿機動退館」
	,KJH_OEN_GENCHAKU  CHAR(4) --「ＫＪＨ＿応援現着」
	,KJH_KEISATSU_TOCHAKU  CHAR(4) --「ＫＪＨ＿警察到着」
	,KJH_KEISATSU_TAIKAN  CHAR(4) --「ＫＪＨ＿警察退館」
	,KJH_SHOBO_TOCHAKU  CHAR(4) --「ＫＪＨ＿消防到着」
	,KJH_SHOBO_TAIKAN  CHAR(4) --「ＫＪＨ＿消防退館」
	,KJH_SOCHI_1  VARCHAR2(80) --「ＫＪＨ＿措置１」
	,KJH_SOCHI_2  VARCHAR2(80) --「ＫＪＨ＿措置２」
	,KJH_SOCHI_3  VARCHAR2(80) --「ＫＪＨ＿措置３」
	,KJH_SOCHI_4  VARCHAR2(80) --「ＫＪＨ＿措置４」
	,KJH_SOCHI_5  VARCHAR2(80) --「ＫＪＨ＿措置５」
	,KJH_SOCHI_6  VARCHAR2(80) --「ＫＪＨ＿措置６」
	,KJH_SOCHI_7  VARCHAR2(80) --「ＫＪＨ＿措置７」
	,KJH_SOCHI_8  VARCHAR2(80) --「ＫＪＨ＿措置８」
	,KJH_SOCHI_9  VARCHAR2(80) --「ＫＪＨ＿措置９」
	,KJH_SOCHI_10  VARCHAR2(80) --「ＫＪＨ＿措置１０」
	,KJH_SOCHI_11  VARCHAR2(80) --「ＫＪＨ＿措置１１」
	,KJH_SOCHI_12  VARCHAR2(80) --「ＫＪＨ＿措置１２」
	,KJH_SOCHI_13  VARCHAR2(80) --「ＫＪＨ＿措置１３」
	,KJH_SOCHI_14  VARCHAR2(80) --「ＫＪＨ＿措置１４」
	,KJH_SOCHI_15  VARCHAR2(80) --「ＫＪＨ＿措置１５」
	,KJH_SOCHI_16  VARCHAR2(80) --「ＫＪＨ＿措置１６」
	,KJH_SOCHI_17  VARCHAR2(80) --「ＫＪＨ＿措置１７」
	,KJH_SOCHI_18  VARCHAR2(80) --「ＫＪＨ＿措置１８」
	,KJH_SOCHI_19  VARCHAR2(80) --「ＫＪＨ＿措置１９」
	,KJH_SOCHI_20  VARCHAR2(80) --「ＫＪＨ＿措置２０」
	,KJH_SOCHI_21  VARCHAR2(80) --「ＫＪＨ＿措置２１」
	,KJH_SOCHI_22  VARCHAR2(80) --「ＫＪＨ＿措置２２」
	,KJH_SOCHI_23  VARCHAR2(80) --「ＫＪＨ＿措置２３」
	,KJH_SOCHI_24  VARCHAR2(80) --「ＫＪＨ＿措置２４」
	,KJH_SOCHI_25  VARCHAR2(80) --「ＫＪＨ＿措置２５」
	,KJH_SOCHI_26  VARCHAR2(80) --「ＫＪＨ＿措置２６」
	,KJH_SOCHI_27  VARCHAR2(80) --「ＫＪＨ＿措置２７」
	,KJH_SOCHI_28  VARCHAR2(80) --「ＫＪＨ＿措置２８」
	,KJH_SOCHI_29  VARCHAR2(80) --「ＫＪＨ＿措置２９」
	,KJH_SOCHI_30  VARCHAR2(80) --「ＫＪＨ＿措置３０」
	,KJH_SOCHI_31  VARCHAR2(80) --「ＫＪＨ＿措置３１」
	,KJH_SOCHI_32  VARCHAR2(80) --「ＫＪＨ＿措置３２」
	,KJH_SOCHI_33  VARCHAR2(80) --「ＫＪＨ＿措置３３」
	,KJH_SOCHI_34  VARCHAR2(80) --「ＫＪＨ＿措置３４」
	,KJH_SOCHI_35  VARCHAR2(80) --「ＫＪＨ＿措置３５」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2525W_PK PRIMARY KEY(
	 KJH_SN
	,  KJH_KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2525W_TBL IS '警備事故発生報告書ワーク'
/

COMMENT ON COLUMN ED2525W_TBL.KJH_KAISHA_CD IS 'ＫＪＨ＿会社コード'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SN IS 'ＫＪＨ＿連番'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_DENKEI_NO IS 'ＫＪＨ＿電計番号'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEIBISAKI_NM_1 IS 'ＫＪＨ＿警備先名称１'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEIBISAKI_NM_2 IS 'ＫＪＨ＿警備先名称２'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KOBETSU_NM IS 'ＫＪＨ＿個別名称'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SET_DT_YMD IS 'ＫＪＨ＿セット日時年月日'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SET_DT_JIFUN IS 'ＫＪＨ＿セット日時時分'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEIBI_JOHO_MD_JIFUN_YMD IS 'ＫＪＨ＿警備情報月日時分年月日'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEIBI_JOHO_MD_JIFUN_JIFUN IS 'ＫＪＨ＿警備情報月日時分時分'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEIBI_JOHO IS 'ＫＪＨ＿警備情報'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_GENIN_CD IS 'ＫＪＨ＿原因コード'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_GENIN_SHOSAI_NAIYO_1 IS 'ＫＪＨ＿原因詳細内容１'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_GENIN_SHOSAI_NAIYO_2 IS 'ＫＪＨ＿原因詳細内容２'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_GENIN_SHOSAI_NAIYO_3 IS 'ＫＪＨ＿原因詳細内容３'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEKKA_1 IS 'ＫＪＨ＿結果１'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEKKA_2 IS 'ＫＪＨ＿結果２'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEKKA_3 IS 'ＫＪＨ＿結果３'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEKKA_4 IS 'ＫＪＨ＿結果４'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEKKA_5 IS 'ＫＪＨ＿結果５'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEKKA_6 IS 'ＫＪＨ＿結果６'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEKKA_7 IS 'ＫＪＨ＿結果７'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEKKA_8 IS 'ＫＪＨ＿結果８'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEKKA_9 IS 'ＫＪＨ＿結果９'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEKKA_10 IS 'ＫＪＨ＿結果１０'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_TANTO_GENCHAKU IS 'ＫＪＨ＿担当現着'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KIDO_TAIKAN IS 'ＫＪＨ＿機動退館'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_OEN_GENCHAKU IS 'ＫＪＨ＿応援現着'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEISATSU_TOCHAKU IS 'ＫＪＨ＿警察到着'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_KEISATSU_TAIKAN IS 'ＫＪＨ＿警察退館'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SHOBO_TOCHAKU IS 'ＫＪＨ＿消防到着'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SHOBO_TAIKAN IS 'ＫＪＨ＿消防退館'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_1 IS 'ＫＪＨ＿措置１'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_2 IS 'ＫＪＨ＿措置２'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_3 IS 'ＫＪＨ＿措置３'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_4 IS 'ＫＪＨ＿措置４'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_5 IS 'ＫＪＨ＿措置５'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_6 IS 'ＫＪＨ＿措置６'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_7 IS 'ＫＪＨ＿措置７'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_8 IS 'ＫＪＨ＿措置８'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_9 IS 'ＫＪＨ＿措置９'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_10 IS 'ＫＪＨ＿措置１０'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_11 IS 'ＫＪＨ＿措置１１'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_12 IS 'ＫＪＨ＿措置１２'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_13 IS 'ＫＪＨ＿措置１３'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_14 IS 'ＫＪＨ＿措置１４'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_15 IS 'ＫＪＨ＿措置１５'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_16 IS 'ＫＪＨ＿措置１６'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_17 IS 'ＫＪＨ＿措置１７'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_18 IS 'ＫＪＨ＿措置１８'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_19 IS 'ＫＪＨ＿措置１９'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_20 IS 'ＫＪＨ＿措置２０'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_21 IS 'ＫＪＨ＿措置２１'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_22 IS 'ＫＪＨ＿措置２２'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_23 IS 'ＫＪＨ＿措置２３'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_24 IS 'ＫＪＨ＿措置２４'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_25 IS 'ＫＪＨ＿措置２５'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_26 IS 'ＫＪＨ＿措置２６'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_27 IS 'ＫＪＨ＿措置２７'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_28 IS 'ＫＪＨ＿措置２８'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_29 IS 'ＫＪＨ＿措置２９'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_30 IS 'ＫＪＨ＿措置３０'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_31 IS 'ＫＪＨ＿措置３１'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_32 IS 'ＫＪＨ＿措置３２'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_33 IS 'ＫＪＨ＿措置３３'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_34 IS 'ＫＪＨ＿措置３４'
/
COMMENT ON COLUMN ED2525W_TBL.KJH_SOCHI_35 IS 'ＫＪＨ＿措置３５'
/
COMMENT ON COLUMN ED2525W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2525W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2525W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2525W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2525W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2525W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2525W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2525W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2525W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2525W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2525W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2525W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
