/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2507T_TBL.sql
-- 物理名：ED2507T_TBL
-- 論理名：業務委託支払予定テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2507T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2507T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,GM_ITK_SHRI_YTI_SHRI_MISI_SN  CHAR(14) NOT NULL --「業務委託支払予定支払明細連番」
	,GYOMU_SHITEI_KBN  CHAR(2) NOT NULL --「業務指定区分」
	,GYM_ITKSK_TRHKSK_CD  CHAR(9) --「業務委託先取引先コード」
	,GYM_ITKSK_TRHKSK_BSH_CD  CHAR(4) --「業務委託先取引先部署コード」
	,GYM_ITKSK_TRHKSK_SHHRI_JH_CD  CHAR(4) --「業務委託先取引先支払情報コード」
	,JISSHI_JIGYOSHO_CD  CHAR(6) --「実施事業所コード」
	,SHIHARAI_SHOGO_JIGYOSHO_CD  CHAR(6) --「支払照合事業所コード」
	,DAIHYO_GYOMU_TAISHOSAKI_CD  CHAR(9) --「代表業務対象先コード」
	,SEIKYU_SHIHARAI_CD  CHAR(3) --「請求支払コード」
	,GYM_ITKH_SNSHTS_KISH_YMD  DATE --「業務委託費算出開始年月日」
	,GYM_ITKH_SNSHTS_KNRY_YMD  DATE --「業務委託費算出完了年月日」
	,GYM_ITK_HATCHUSHO_NO  CHAR(28) --「業務委託発注書番号」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,GYM_ITKH_SHHRI_ZIKM_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「業務委託費支払税込金額」
	,GYM_ITKH_SHHRI_ZINK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「業務委託費支払税抜金額」
	,GYM_ITKH_SHHRI_SHHZI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「業務委託費支払消費税金額」
	,SHOHIZEI_KBN  CHAR(1) NOT NULL --「消費税区分」
	,SHOHI_ZEIRITSU_CD  CHAR(2) --「消費税率コード」
	,JURYO_SEIKYUSHO_NO  VARCHAR2(22) --「受領請求書番号」
	,GYOMU_ITAKU_SHIHARAI_YOTEI_YMD  DATE --「業務委託支払予定年月日」
	,JIDO_TOTSUGO_KANRYO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「自動突合完了フラグ」
	,SHOGOZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「照合済フラグ」
	,SOKYU_SAKUJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「遡及削除フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2507T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  GM_ITK_SHRI_YTI_SHRI_MISI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2507T_TBL IS '業務委託支払予定テーブル'
/

COMMENT ON COLUMN ED2507T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2507T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED2507T_TBL.GM_ITK_SHRI_YTI_SHRI_MISI_SN IS '業務委託支払予定支払明細連番'
/
COMMENT ON COLUMN ED2507T_TBL.GYOMU_SHITEI_KBN IS '業務指定区分'
/
COMMENT ON COLUMN ED2507T_TBL.GYM_ITKSK_TRHKSK_CD IS '業務委託先取引先コード'
/
COMMENT ON COLUMN ED2507T_TBL.GYM_ITKSK_TRHKSK_BSH_CD IS '業務委託先取引先部署コード'
/
COMMENT ON COLUMN ED2507T_TBL.GYM_ITKSK_TRHKSK_SHHRI_JH_CD IS '業務委託先取引先支払情報コード'
/
COMMENT ON COLUMN ED2507T_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED2507T_TBL.SHIHARAI_SHOGO_JIGYOSHO_CD IS '支払照合事業所コード'
/
COMMENT ON COLUMN ED2507T_TBL.DAIHYO_GYOMU_TAISHOSAKI_CD IS '代表業務対象先コード'
/
COMMENT ON COLUMN ED2507T_TBL.SEIKYU_SHIHARAI_CD IS '請求支払コード'
/
COMMENT ON COLUMN ED2507T_TBL.GYM_ITKH_SNSHTS_KISH_YMD IS '業務委託費算出開始年月日'
/
COMMENT ON COLUMN ED2507T_TBL.GYM_ITKH_SNSHTS_KNRY_YMD IS '業務委託費算出完了年月日'
/
COMMENT ON COLUMN ED2507T_TBL.GYM_ITK_HATCHUSHO_NO IS '業務委託発注書番号'
/
COMMENT ON COLUMN ED2507T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED2507T_TBL.GYM_ITKH_SHHRI_ZIKM_AMT IS '業務委託費支払税込金額'
/
COMMENT ON COLUMN ED2507T_TBL.GYM_ITKH_SHHRI_ZINK_AMT IS '業務委託費支払税抜金額'
/
COMMENT ON COLUMN ED2507T_TBL.GYM_ITKH_SHHRI_SHHZI_AMT IS '業務委託費支払消費税金額'
/
COMMENT ON COLUMN ED2507T_TBL.SHOHIZEI_KBN IS '消費税区分'
/
COMMENT ON COLUMN ED2507T_TBL.SHOHI_ZEIRITSU_CD IS '消費税率コード'
/
COMMENT ON COLUMN ED2507T_TBL.JURYO_SEIKYUSHO_NO IS '受領請求書番号'
/
COMMENT ON COLUMN ED2507T_TBL.GYOMU_ITAKU_SHIHARAI_YOTEI_YMD IS '業務委託支払予定年月日'
/
COMMENT ON COLUMN ED2507T_TBL.JIDO_TOTSUGO_KANRYO_FLG IS '自動突合完了フラグ'
/
COMMENT ON COLUMN ED2507T_TBL.SHOGOZUMI_FLG IS '照合済フラグ'
/
COMMENT ON COLUMN ED2507T_TBL.SOKYU_SAKUJO_FLG IS '遡及削除フラグ'
/
COMMENT ON COLUMN ED2507T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2507T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2507T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2507T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2507T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2507T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2507T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2507T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2507T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2507T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2507T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2507T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
