/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2526T_TBL.sql
-- 物理名：ED2526T_TBL
-- 論理名：業務再委託先テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2526T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2526T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,GYOMU_SAIITAKU_SN  CHAR(14) NOT NULL --「業務再委託連番」
	,GYOMU_SAIITAKU_KAISO_NO  NUMBER(2,0) DEFAULT '0' NOT NULL --「業務再委託階層番号」
	,GYM_ITKMT_TRHKSK_CD  CHAR(9) --「業務委託元取引先コード」
	,GYM_ITKMT_TRHKSK_BSH_CD  CHAR(4) --「業務委託元取引先部署コード」
	,GYM_ITKMT_TRHKSK_SISHK_NM  VARCHAR2(50) --「業務委託元取引先正式名称」
	,GYOMU_ITAKUMOTO_BUSHO_NM  VARCHAR2(40) --「業務委託元部署名称」
	,GYM_ITKSK_TRHKSK_CD  CHAR(9) --「業務委託先取引先コード」
	,GYM_ITKSK_TRHKSK_BSH_CD  CHAR(4) --「業務委託先取引先部署コード」
	,GYM_ITKSK_TRHKSK_SISHK_NM  VARCHAR2(50) --「業務委託先取引先正式名称」
	,GYOMU_ITAKUSAKI_BUSHO_NM  VARCHAR2(40) --「業務委託先部署名称」
	,GYOMU_ITAKUSAKI_JUSHO_CD  CHAR(11) --「業務委託先住所コード」
	,GYOMU_ITAKUSAKI_SHOSAI_JUSHO  VARCHAR2(60) --「業務委託先詳細住所」
	,GYOMU_ITAKUSAKI_DENWA_NO  VARCHAR2(20) --「業務委託先電話番号」
	,GYOMU_SAIITAKUSAKI_BIKO  VARCHAR2(30) --「業務再委託先備考」
	,GYM_SIITKSK_SISH_KSHN_YMD  DATE --「業務再委託先最終更新年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2526T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  GYOMU_SAIITAKU_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2526T_TBL IS '業務再委託先テーブル'
/

COMMENT ON COLUMN ED2526T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2526T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED2526T_TBL.GYOMU_SAIITAKU_SN IS '業務再委託連番'
/
COMMENT ON COLUMN ED2526T_TBL.GYOMU_SAIITAKU_KAISO_NO IS '業務再委託階層番号'
/
COMMENT ON COLUMN ED2526T_TBL.GYM_ITKMT_TRHKSK_CD IS '業務委託元取引先コード'
/
COMMENT ON COLUMN ED2526T_TBL.GYM_ITKMT_TRHKSK_BSH_CD IS '業務委託元取引先部署コード'
/
COMMENT ON COLUMN ED2526T_TBL.GYM_ITKMT_TRHKSK_SISHK_NM IS '業務委託元取引先正式名称'
/
COMMENT ON COLUMN ED2526T_TBL.GYOMU_ITAKUMOTO_BUSHO_NM IS '業務委託元部署名称'
/
COMMENT ON COLUMN ED2526T_TBL.GYM_ITKSK_TRHKSK_CD IS '業務委託先取引先コード'
/
COMMENT ON COLUMN ED2526T_TBL.GYM_ITKSK_TRHKSK_BSH_CD IS '業務委託先取引先部署コード'
/
COMMENT ON COLUMN ED2526T_TBL.GYM_ITKSK_TRHKSK_SISHK_NM IS '業務委託先取引先正式名称'
/
COMMENT ON COLUMN ED2526T_TBL.GYOMU_ITAKUSAKI_BUSHO_NM IS '業務委託先部署名称'
/
COMMENT ON COLUMN ED2526T_TBL.GYOMU_ITAKUSAKI_JUSHO_CD IS '業務委託先住所コード'
/
COMMENT ON COLUMN ED2526T_TBL.GYOMU_ITAKUSAKI_SHOSAI_JUSHO IS '業務委託先詳細住所'
/
COMMENT ON COLUMN ED2526T_TBL.GYOMU_ITAKUSAKI_DENWA_NO IS '業務委託先電話番号'
/
COMMENT ON COLUMN ED2526T_TBL.GYOMU_SAIITAKUSAKI_BIKO IS '業務再委託先備考'
/
COMMENT ON COLUMN ED2526T_TBL.GYM_SIITKSK_SISH_KSHN_YMD IS '業務再委託先最終更新年月日'
/
COMMENT ON COLUMN ED2526T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2526T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2526T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2526T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2526T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2526T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2526T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2526T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2526T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2526T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2526T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2526T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
