/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2552T_TBL.sql
-- 物理名：ED2552T_TBL
-- 論理名：常駐警備現況報告書一覧テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2552T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2552T_TBL (
	 JUCHU_KAISHA_CD  CHAR(5) NOT NULL --「受注会社コード」
	,UNY_JSS_JK_HKKSH_SKSI_TISH_YM  CHAR(6) NOT NULL --「運用実施状況報告書作成対象年月」
	,JCHKIB_GNKY_GTSJ_HKK_KBN  CHAR(1) NOT NULL --「常駐警備現況月次報告区分」
	,JCHKIB_GNKY_GTSJ_HKK_KBN_NM  VARCHAR2(60) --「常駐警備現況月次報告区分名称」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,DIHY_GYMITKMT_JUCHU_KEIYAKU_NO  CHAR(15) --「代表業務委託元受注契約番号」
	,DIHY_GYMITKSK_JUCHU_KEIYAKU_NO  CHAR(15) --「代表業務委託先受注契約番号」
	,GYOMU_SAIITAKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「業務再委託有フラグ」
	,KEIBI_NIMMU_NAIYO  VARCHAR2(30) --「警備任務内容」
	,UNYO_KBN  CHAR(1) NOT NULL --「運用区分」
	,JUCHUGAISHA_NM  VARCHAR2(40) --「受注会社名称」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,JUCHU_JIGYOSHO_NM  VARCHAR2(200) --「受注事業所名称」
	,JISSHI_JIGYOSHO_CD  CHAR(6) NOT NULL --「実施事業所コード」
	,JISSHI_JIGYOSHO_NM  VARCHAR2(200) --「実施事業所名称」
	,GYM_ITKSK_KAISHA_CD  CHAR(5) --「業務委託先会社コード」
	,GYM_ITKSK_KAISHA_NM  VARCHAR2(40) --「業務委託先会社名称」
	,GYM_ITKSK_TRHKSK_CD  CHAR(9) NOT NULL --「業務委託先取引先コード」
	,GYM_ITKSK_TRHKSK_NM  VARCHAR2(40) --「業務委託先取引先名称」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,KEIYAKUSAKI_TORIHIKISAKI_NM  VARCHAR2(40) --「契約先取引先名称」
	,KIYKSK_TRHKSK_BSH_CD  CHAR(4) --「契約先取引先部署コード」
	,WK_KIYKSK_TRHKSK_BWK_NM  VARCHAR2(40) --「ワーク用契約先取引先部署名称」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,TAISHOSAKI_NM  VARCHAR2(40) --「対象先名称」
	,JUSHO_CD_TAIO_JUSHO  VARCHAR2(61) --「住所コード対応住所」
	,NENKAN_JITSU_RODO_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「年間実労働時間」
	,EIGYO_KEISU  NUMBER(12,3) DEFAULT '0.0' NOT NULL --「営業係数」
	,JCH_KIB_JIKKO_ANBUN_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「常駐警備実行按分率」
	,JININ_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「人員単価金額」
	,GTSGK_KIB_RYKN_ANBN_AMT  NUMBER(15,2) DEFAULT '0' NOT NULL --「月額警備料金按分金額」
	,GYOMU_ITAKU_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「業務委託料金金額」
	,GYOMU_ITAKU_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「業務委託率」
	,GYOMU_KAISHI_YMD  DATE --「業務開始年月日」
	,KEIYAKUSAKI_GYOSHU_CD  CHAR(4) --「契約先業種コード」
	,KEIYAKUSAKI_GYOSHU_NM  VARCHAR2(60) --「契約先業種名称」
	,TAISHOSAKI_GYOSHU_KBN  CHAR(3) NOT NULL --「対象先業種区分」
	,KEIBI_TAISHO_GYOSHU_NM  VARCHAR2(60) --「警備対象業種名称」
	,HAICHISAKI_CD  VARCHAR2(6) --「配置先コード」
	,HAICHISAKI_NM  VARCHAR2(200) --「配置先名称」
	,HAICHI_GOKEI_NINZU  NUMBER(12,3) DEFAULT '0' NOT NULL --「配置合計人数」
	,SHOYO_JININ_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「所要人員率」
	,BAISHO_GENDO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「賠償限度金額」
	,NOBEYUKA_MENSEKI  NUMBER(12,3) DEFAULT '0.0' NOT NULL --「延べ床面積」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2552T_PK PRIMARY KEY(
	 UNY_JSS_JK_HKKSH_SKSI_TISH_YM
	,  JCHKIB_GNKY_GTSJ_HKK_KBN
	,  JUCHU_KEIYAKU_NO
	,  JISSHI_JIGYOSHO_CD
	,  GYM_ITKSK_TRHKSK_CD
	,  JUCHU_KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2552T_TBL IS '常駐警備現況報告書一覧テーブル'
/

COMMENT ON COLUMN ED2552T_TBL.JUCHU_KAISHA_CD IS '受注会社コード'
/
COMMENT ON COLUMN ED2552T_TBL.UNY_JSS_JK_HKKSH_SKSI_TISH_YM IS '運用実施状況報告書作成対象年月'
/
COMMENT ON COLUMN ED2552T_TBL.JCHKIB_GNKY_GTSJ_HKK_KBN IS '常駐警備現況月次報告区分'
/
COMMENT ON COLUMN ED2552T_TBL.JCHKIB_GNKY_GTSJ_HKK_KBN_NM IS '常駐警備現況月次報告区分名称'
/
COMMENT ON COLUMN ED2552T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED2552T_TBL.DIHY_GYMITKMT_JUCHU_KEIYAKU_NO IS '代表業務委託元受注契約番号'
/
COMMENT ON COLUMN ED2552T_TBL.DIHY_GYMITKSK_JUCHU_KEIYAKU_NO IS '代表業務委託先受注契約番号'
/
COMMENT ON COLUMN ED2552T_TBL.GYOMU_SAIITAKUARI_FLG IS '業務再委託有フラグ'
/
COMMENT ON COLUMN ED2552T_TBL.KEIBI_NIMMU_NAIYO IS '警備任務内容'
/
COMMENT ON COLUMN ED2552T_TBL.UNYO_KBN IS '運用区分'
/
COMMENT ON COLUMN ED2552T_TBL.JUCHUGAISHA_NM IS '受注会社名称'
/
COMMENT ON COLUMN ED2552T_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED2552T_TBL.JUCHU_JIGYOSHO_NM IS '受注事業所名称'
/
COMMENT ON COLUMN ED2552T_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED2552T_TBL.JISSHI_JIGYOSHO_NM IS '実施事業所名称'
/
COMMENT ON COLUMN ED2552T_TBL.GYM_ITKSK_KAISHA_CD IS '業務委託先会社コード'
/
COMMENT ON COLUMN ED2552T_TBL.GYM_ITKSK_KAISHA_NM IS '業務委託先会社名称'
/
COMMENT ON COLUMN ED2552T_TBL.GYM_ITKSK_TRHKSK_CD IS '業務委託先取引先コード'
/
COMMENT ON COLUMN ED2552T_TBL.GYM_ITKSK_TRHKSK_NM IS '業務委託先取引先名称'
/
COMMENT ON COLUMN ED2552T_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED2552T_TBL.KEIYAKUSAKI_TORIHIKISAKI_NM IS '契約先取引先名称'
/
COMMENT ON COLUMN ED2552T_TBL.KIYKSK_TRHKSK_BSH_CD IS '契約先取引先部署コード'
/
COMMENT ON COLUMN ED2552T_TBL.WK_KIYKSK_TRHKSK_BWK_NM IS 'ワーク用契約先取引先部署名称'
/
COMMENT ON COLUMN ED2552T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED2552T_TBL.TAISHOSAKI_NM IS '対象先名称'
/
COMMENT ON COLUMN ED2552T_TBL.JUSHO_CD_TAIO_JUSHO IS '住所コード対応住所'
/
COMMENT ON COLUMN ED2552T_TBL.NENKAN_JITSU_RODO_JIKAN IS '年間実労働時間'
/
COMMENT ON COLUMN ED2552T_TBL.EIGYO_KEISU IS '営業係数'
/
COMMENT ON COLUMN ED2552T_TBL.JCH_KIB_JIKKO_ANBUN_RITSU IS '常駐警備実行按分率'
/
COMMENT ON COLUMN ED2552T_TBL.JININ_TANKA_AMT IS '人員単価金額'
/
COMMENT ON COLUMN ED2552T_TBL.GTSGK_KIB_RYKN_ANBN_AMT IS '月額警備料金按分金額'
/
COMMENT ON COLUMN ED2552T_TBL.GYOMU_ITAKU_RYOKIN_AMT IS '業務委託料金金額'
/
COMMENT ON COLUMN ED2552T_TBL.GYOMU_ITAKU_RITSU IS '業務委託率'
/
COMMENT ON COLUMN ED2552T_TBL.GYOMU_KAISHI_YMD IS '業務開始年月日'
/
COMMENT ON COLUMN ED2552T_TBL.KEIYAKUSAKI_GYOSHU_CD IS '契約先業種コード'
/
COMMENT ON COLUMN ED2552T_TBL.KEIYAKUSAKI_GYOSHU_NM IS '契約先業種名称'
/
COMMENT ON COLUMN ED2552T_TBL.TAISHOSAKI_GYOSHU_KBN IS '対象先業種区分'
/
COMMENT ON COLUMN ED2552T_TBL.KEIBI_TAISHO_GYOSHU_NM IS '警備対象業種名称'
/
COMMENT ON COLUMN ED2552T_TBL.HAICHISAKI_CD IS '配置先コード'
/
COMMENT ON COLUMN ED2552T_TBL.HAICHISAKI_NM IS '配置先名称'
/
COMMENT ON COLUMN ED2552T_TBL.HAICHI_GOKEI_NINZU IS '配置合計人数'
/
COMMENT ON COLUMN ED2552T_TBL.SHOYO_JININ_RITSU IS '所要人員率'
/
COMMENT ON COLUMN ED2552T_TBL.BAISHO_GENDO_AMT IS '賠償限度金額'
/
COMMENT ON COLUMN ED2552T_TBL.NOBEYUKA_MENSEKI IS '延べ床面積'
/
COMMENT ON COLUMN ED2552T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2552T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2552T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2552T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2552T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2552T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2552T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2552T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2552T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2552T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2552T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2552T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
