/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2524W_TBL.sql
-- 物理名：ED2524W_TBL
-- 論理名：入出金機格納投入ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2524W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2524W_TBL (
	 NSM_KAISHA_CD  CHAR(5) NOT NULL --「ＮＳＭ＿会社コード」
	,NSM_TOROKU_YM  CHAR(6) NOT NULL --「ＮＳＭ＿登録年月」
	,NSM_SN  NUMBER(14,0) DEFAULT '0' NOT NULL --「ＮＳＭ＿連番」
	,NSM_JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「ＮＳＭ＿受注契約番号」
	,NSM_YM  CHAR(7) NOT NULL --「ＮＳＭ＿年月」
	,NSM_TAMMATSU_NO  CHAR(6) NOT NULL --「ＮＳＭ＿端末番号」
	,NSM_NYUKINKIMEI  VARCHAR2(80) NOT NULL --「ＮＳＭ＿入金機名」
	,NSM_KISHU  CHAR(2) NOT NULL --「ＮＳＭ＿機種」
	,NSM_KISHUMEI  VARCHAR2(20) NOT NULL --「ＮＳＭ＿機種名」
	,NSM_KEIYAKUSAKI_CD  CHAR(9) NOT NULL --「ＮＳＭ＿契約先コード」
	,NSM_KEIYAKUSAKIMEI  VARCHAR2(20) NOT NULL --「ＮＳＭ＿契約先名」
	,NSM_TEMPO_CD  CHAR(6) NOT NULL --「ＮＳＭ＿店舗コード」
	,NSM_TEMPOMEI  VARCHAR2(80) NOT NULL --「ＮＳＭ＿店舗名」
	,NSM_GYOMU_KAISHI  CHAR(8) NOT NULL --「ＮＳＭ＿業務開始」
	,NSM_GYOMU_SHURYO  CHAR(8) NOT NULL --「ＮＳＭ＿業務終了」
	,NSM_JUCHU_JIGYOSHO  CHAR(6) NOT NULL --「ＮＳＭ＿受注事業所」
	,NSM_JUCHU_JIGYOSHOMEI  VARCHAR2(20) NOT NULL --「ＮＳＭ＿受注事業所名」
	,NSM_KEISO_JIGYOSHO  CHAR(6) NOT NULL --「ＮＳＭ＿警送事業所」
	,NSM_KEISO_JIGYOSHOMEI  VARCHAR2(20) NOT NULL --「ＮＳＭ＿警送事業所名」
	,NSM_SEISA_JIGYOSHO  CHAR(6) NOT NULL --「ＮＳＭ＿精査事業所」
	,NSM_SEISA_JIGYOSHOMEI  VARCHAR2(20) NOT NULL --「ＮＳＭ＿精査事業所名」
	,NSM_TONYU_AMT_GOKEI  CHAR(15) NOT NULL --「ＮＳＭ＿投入金額合計」
	,NSM_SHIHEI_GOKEI  CHAR(10) NOT NULL --「ＮＳＭ＿紙幣合計」
	,NSM_KOKA_GOKEI  CHAR(10) NOT NULL --「ＮＳＭ＿硬貨合計」
	,NSM_TONYU_NISSU  CHAR(3) NOT NULL --「ＮＳＭ＿投入日数」
	,NSM_KAISHU_KAISU  CHAR(3) NOT NULL --「ＮＳＭ＿回収回数」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2524W_PK PRIMARY KEY(
	 NSM_TOROKU_YM
	,  NSM_SN
	,  NSM_KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2524W_TBL IS '入出金機格納投入ワーク'
/

COMMENT ON COLUMN ED2524W_TBL.NSM_KAISHA_CD IS 'ＮＳＭ＿会社コード'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_TOROKU_YM IS 'ＮＳＭ＿登録年月'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_SN IS 'ＮＳＭ＿連番'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_JUCHU_KEIYAKU_NO IS 'ＮＳＭ＿受注契約番号'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_YM IS 'ＮＳＭ＿年月'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_TAMMATSU_NO IS 'ＮＳＭ＿端末番号'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_NYUKINKIMEI IS 'ＮＳＭ＿入金機名'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_KISHU IS 'ＮＳＭ＿機種'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_KISHUMEI IS 'ＮＳＭ＿機種名'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_KEIYAKUSAKI_CD IS 'ＮＳＭ＿契約先コード'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_KEIYAKUSAKIMEI IS 'ＮＳＭ＿契約先名'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_TEMPO_CD IS 'ＮＳＭ＿店舗コード'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_TEMPOMEI IS 'ＮＳＭ＿店舗名'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_GYOMU_KAISHI IS 'ＮＳＭ＿業務開始'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_GYOMU_SHURYO IS 'ＮＳＭ＿業務終了'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_JUCHU_JIGYOSHO IS 'ＮＳＭ＿受注事業所'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_JUCHU_JIGYOSHOMEI IS 'ＮＳＭ＿受注事業所名'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_KEISO_JIGYOSHO IS 'ＮＳＭ＿警送事業所'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_KEISO_JIGYOSHOMEI IS 'ＮＳＭ＿警送事業所名'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_SEISA_JIGYOSHO IS 'ＮＳＭ＿精査事業所'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_SEISA_JIGYOSHOMEI IS 'ＮＳＭ＿精査事業所名'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_TONYU_AMT_GOKEI IS 'ＮＳＭ＿投入金額合計'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_SHIHEI_GOKEI IS 'ＮＳＭ＿紙幣合計'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_KOKA_GOKEI IS 'ＮＳＭ＿硬貨合計'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_TONYU_NISSU IS 'ＮＳＭ＿投入日数'
/
COMMENT ON COLUMN ED2524W_TBL.NSM_KAISHU_KAISU IS 'ＮＳＭ＿回収回数'
/
COMMENT ON COLUMN ED2524W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2524W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2524W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2524W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2524W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2524W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2524W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2524W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2524W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2524W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2524W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2524W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
