/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2554W_TBL.sql
-- 物理名：ED2554W_TBL
-- 論理名：常駐警備処理月実施受注契約長期自社ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2554W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2554W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,KDHY_HICH_POST_SN  CHAR(14) NOT NULL --「稼働表配置ポスト連番」
	,UNY_JSS_JK_HKKSH_SKSI_TISH_YM  CHAR(6) NOT NULL --「運用実施状況報告書作成対象年月」
	,JISSHI_JIGYOSHO_CD  CHAR(6) NOT NULL --「実施事業所コード」
	,NENKAN_SHOTEINAI_RODO_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「年間所定内労働時間」
	,NENKAN_HAITCHI_NISSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「年間配置日数」
	,D_TANI_KEIBI_JISSEKI_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「日単位警備実績時間」
	,SHOYO_JININ_NINZU  NUMBER(12,3) DEFAULT '0' NOT NULL --「所要人員人数」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2554W_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KDHY_HICH_POST_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2554W_TBL IS '常駐警備処理月実施受注契約長期自社ワーク'
/

COMMENT ON COLUMN ED2554W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2554W_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED2554W_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED2554W_TBL.KDHY_HICH_POST_SN IS '稼働表配置ポスト連番'
/
COMMENT ON COLUMN ED2554W_TBL.UNY_JSS_JK_HKKSH_SKSI_TISH_YM IS '運用実施状況報告書作成対象年月'
/
COMMENT ON COLUMN ED2554W_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED2554W_TBL.NENKAN_SHOTEINAI_RODO_JIKAN IS '年間所定内労働時間'
/
COMMENT ON COLUMN ED2554W_TBL.NENKAN_HAITCHI_NISSU IS '年間配置日数'
/
COMMENT ON COLUMN ED2554W_TBL.D_TANI_KEIBI_JISSEKI_JIKAN IS '日単位警備実績時間'
/
COMMENT ON COLUMN ED2554W_TBL.SHOYO_JININ_NINZU IS '所要人員人数'
/
COMMENT ON COLUMN ED2554W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2554W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2554W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2554W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2554W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2554W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2554W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2554W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2554W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2554W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2554W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2554W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
