/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2511T_TBL.sql
-- 物理名：ED2511T_TBL
-- 論理名：出動実績明細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2511T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2511T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,SHUTSUDO_JISSEKI_NO  CHAR(5) NOT NULL --「出動実績番号」
	,SHUTSUDO_JISSEKI_MEISAI_NO  CHAR(3) NOT NULL --「出動実績明細番号」
	,KAKIN_BUNRUI_KBN  CHAR(1) NOT NULL --「課金分類区分」
	,TANKA_SHITEI_TYPE_CD  CHAR(3) NOT NULL --「単価指定タイプコード」
	,KAKIN_JOKEN_NAIYO  VARCHAR2(30) --「課金条件内容」
	,SHUTSUDO_KAKIN_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「出動課金単価金額」
	,JISSEKI_SURYO  NUMBER(13,0) DEFAULT '0' NOT NULL --「実績数量」
	,JURYO_JISSEKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「従量実績金額」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2511T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  SHUTSUDO_JISSEKI_NO
	,  SHUTSUDO_JISSEKI_MEISAI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2511T_TBL IS '出動実績明細テーブル'
/

COMMENT ON COLUMN ED2511T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2511T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED2511T_TBL.SHUTSUDO_JISSEKI_NO IS '出動実績番号'
/
COMMENT ON COLUMN ED2511T_TBL.SHUTSUDO_JISSEKI_MEISAI_NO IS '出動実績明細番号'
/
COMMENT ON COLUMN ED2511T_TBL.KAKIN_BUNRUI_KBN IS '課金分類区分'
/
COMMENT ON COLUMN ED2511T_TBL.TANKA_SHITEI_TYPE_CD IS '単価指定タイプコード'
/
COMMENT ON COLUMN ED2511T_TBL.KAKIN_JOKEN_NAIYO IS '課金条件内容'
/
COMMENT ON COLUMN ED2511T_TBL.SHUTSUDO_KAKIN_TANKA_AMT IS '出動課金単価金額'
/
COMMENT ON COLUMN ED2511T_TBL.JISSEKI_SURYO IS '実績数量'
/
COMMENT ON COLUMN ED2511T_TBL.JURYO_JISSEKI_AMT IS '従量実績金額'
/
COMMENT ON COLUMN ED2511T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2511T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2511T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2511T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2511T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2511T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2511T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2511T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2511T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2511T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2511T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2511T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
