/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2521T_TBL.sql
-- 物理名：ED2521T_TBL
-- 論理名：警備事故発生報告書テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2521T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2521T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KIB_JK_HKKSH_KIB_JH_YMD  DATE NOT NULL --「警備事故報告書警備情報年月日」
	,KIB_JK_HKKSH_KIB_JH_TM  CHAR(4) NOT NULL --「警備事故報告書警備情報時刻」
	,KIB_JK_HKKSH_KIB_JH_SHNG_CD  CHAR(20) NOT NULL --「警備事故報告書警備情報信号コード」
	,KIB_JK_HKKSH_DIBNRI_GNIN_CD  CHAR(1) NOT NULL --「警備事故報告書大分類原因コード」
	,KIB_JK_HKKSH_CHBNRI_GNIN_CD  CHAR(1) NOT NULL --「警備事故報告書中分類原因コード」
	,KIB_JK_HKKSH_SHBNRI_GNIN_CD  CHAR(1) NOT NULL --「警備事故報告書小分類原因コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,DENKEI_NO  CHAR(9) NOT NULL --「電計番号」
	,TORIHIKISAKI_CD  CHAR(9) --「取引先コード」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,TAISHOSAKI_JUSHO_CD  CHAR(11) --「対象先住所コード」
	,TAISHOSAKI_EIGYO_NAIYO_CD  CHAR(3) --「対象先営業内容コード」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,JUCHU_TANTO_SHAIN_NO  VARCHAR2(8) --「受注担当社員番号」
	,JISSHI_JIGYOSHO_CD  CHAR(6) --「実施事業所コード」
	,KIB_JK_HKKSH_KIBSK_NM_1  VARCHAR2(40) --「警備事故報告書警備先名称１」
	,KIB_JK_HKKSH_KIBSK_NM_2  VARCHAR2(20) --「警備事故報告書警備先名称２」
	,KIB_JK_HKKSH_KBTS_NM  VARCHAR2(20) --「警備事故報告書個別名称」
	,KEIBI_JIKO_HOKOKUSHO_SET_YMD  DATE --「警備事故報告書セット年月日」
	,KEIBI_JIKO_HOKOKUSHO_SET_TM  CHAR(4) --「警備事故報告書セット時刻」
	,KIB_JK_HKKSH_GNIN_SHSI_NAIYO_1  VARCHAR2(30) --「警備事故報告書原因詳細内容１」
	,KIB_JK_HKKSH_GNIN_SHSI_NAIYO_2  VARCHAR2(30) --「警備事故報告書原因詳細内容２」
	,KIB_JK_HKKSH_GNIN_SHSI_NAIYO_3  VARCHAR2(30) --「警備事故報告書原因詳細内容３」
	,KIB_JK_HKKSH_KEKKA_NAIYO_1  VARCHAR2(100) --「警備事故報告書結果内容１」
	,KIB_JK_HKKSH_KEKKA_NAIYO_2  VARCHAR2(100) --「警備事故報告書結果内容２」
	,KIB_JK_HKKSH_KEKKA_NAIYO_3  VARCHAR2(100) --「警備事故報告書結果内容３」
	,KIB_JK_HKKSH_KEKKA_NAIYO_4  VARCHAR2(100) --「警備事故報告書結果内容４」
	,KIB_JK_HKKSH_KEKKA_NAIYO_5  VARCHAR2(100) --「警備事故報告書結果内容５」
	,KIB_JK_HKKSH_KEKKA_NAIYO_6  VARCHAR2(100) --「警備事故報告書結果内容６」
	,KIB_JK_HKKSH_KEKKA_NAIYO_7  VARCHAR2(100) --「警備事故報告書結果内容７」
	,KIB_JK_HKKSH_KEKKA_NAIYO_8  VARCHAR2(100) --「警備事故報告書結果内容８」
	,KIB_JK_HKKSH_KEKKA_NAIYO_9  VARCHAR2(100) --「警備事故報告書結果内容９」
	,KIB_JK_HKKSH_KEKKA_NAIYO_10  VARCHAR2(100) --「警備事故報告書結果内容１０」
	,KIB_JK_HKKSH_TNT_GNCHK_TM  CHAR(4) --「警備事故報告書担当現着時刻」
	,KIB_JK_HKKSH_KD_TIKN_TM  CHAR(4) --「警備事故報告書機動退館時刻」
	,KIB_JK_HKKSH_OEN_GNCHK_TM  CHAR(4) --「警備事故報告書応援現着時刻」
	,KIB_JK_HKKSH_KISTS_TCHK_TM  CHAR(4) --「警備事故報告書警察到着時刻」
	,KIB_JK_HKKSH_KISTS_TIKN_TM  CHAR(4) --「警備事故報告書警察退館時刻」
	,KIB_JK_HKKSH_SHB_TCHK_TM  CHAR(4) --「警備事故報告書消防到着時刻」
	,KIB_JK_HKKSH_SHB_TIKN_TM  CHAR(4) --「警備事故報告書消防退館時刻」
	,KIB_JK_HKKSH_SCH_NAIYO_1  VARCHAR2(100) --「警備事故報告書措置内容１」
	,KIB_JK_HKKSH_SCH_NAIYO_2  VARCHAR2(100) --「警備事故報告書措置内容２」
	,KIB_JK_HKKSH_SCH_NAIYO_3  VARCHAR2(100) --「警備事故報告書措置内容３」
	,KIB_JK_HKKSH_SCH_NAIYO_4  VARCHAR2(100) --「警備事故報告書措置内容４」
	,KIB_JK_HKKSH_SCH_NAIYO_5  VARCHAR2(100) --「警備事故報告書措置内容５」
	,KIB_JK_HKKSH_SCH_NAIYO_6  VARCHAR2(100) --「警備事故報告書措置内容６」
	,KIB_JK_HKKSH_SCH_NAIYO_7  VARCHAR2(100) --「警備事故報告書措置内容７」
	,KIB_JK_HKKSH_SCH_NAIYO_8  VARCHAR2(100) --「警備事故報告書措置内容８」
	,KIB_JK_HKKSH_SCH_NAIYO_9  VARCHAR2(100) --「警備事故報告書措置内容９」
	,KIB_JK_HKKSH_SCH_NAIYO_10  VARCHAR2(100) --「警備事故報告書措置内容１０」
	,KIB_JK_HKKSH_SCH_NAIYO_11  VARCHAR2(100) --「警備事故報告書措置内容１１」
	,KIB_JK_HKKSH_SCH_NAIYO_12  VARCHAR2(100) --「警備事故報告書措置内容１２」
	,KIB_JK_HKKSH_SCH_NAIYO_13  VARCHAR2(100) --「警備事故報告書措置内容１３」
	,KIB_JK_HKKSH_SCH_NAIYO_14  VARCHAR2(100) --「警備事故報告書措置内容１４」
	,KIB_JK_HKKSH_SCH_NAIYO_15  VARCHAR2(100) --「警備事故報告書措置内容１５」
	,KIB_JK_HKKSH_SCH_NAIYO_16  VARCHAR2(100) --「警備事故報告書措置内容１６」
	,KIB_JK_HKKSH_SCH_NAIYO_17  VARCHAR2(100) --「警備事故報告書措置内容１７」
	,KIB_JK_HKKSH_SCH_NAIYO_18  VARCHAR2(100) --「警備事故報告書措置内容１８」
	,KIB_JK_HKKSH_SCH_NAIYO_19  VARCHAR2(100) --「警備事故報告書措置内容１９」
	,KIB_JK_HKKSH_SCH_NAIYO_20  VARCHAR2(100) --「警備事故報告書措置内容２０」
	,KIB_JK_HKKSH_SCH_NAIYO_21  VARCHAR2(100) --「警備事故報告書措置内容２１」
	,KIB_JK_HKKSH_SCH_NAIYO_22  VARCHAR2(100) --「警備事故報告書措置内容２２」
	,KIB_JK_HKKSH_SCH_NAIYO_23  VARCHAR2(100) --「警備事故報告書措置内容２３」
	,KIB_JK_HKKSH_SCH_NAIYO_24  VARCHAR2(100) --「警備事故報告書措置内容２４」
	,KIB_JK_HKKSH_SCH_NAIYO_25  VARCHAR2(100) --「警備事故報告書措置内容２５」
	,KIB_JK_HKKSH_SCH_NAIYO_26  VARCHAR2(100) --「警備事故報告書措置内容２６」
	,KIB_JK_HKKSH_SCH_NAIYO_27  VARCHAR2(100) --「警備事故報告書措置内容２７」
	,KIB_JK_HKKSH_SCH_NAIYO_28  VARCHAR2(100) --「警備事故報告書措置内容２８」
	,KIB_JK_HKKSH_SCH_NAIYO_29  VARCHAR2(100) --「警備事故報告書措置内容２９」
	,KIB_JK_HKKSH_SCH_NAIYO_30  VARCHAR2(100) --「警備事故報告書措置内容３０」
	,KIB_JK_HKKSH_SCH_NAIYO_31  VARCHAR2(100) --「警備事故報告書措置内容３１」
	,KIB_JK_HKKSH_SCH_NAIYO_32  VARCHAR2(100) --「警備事故報告書措置内容３２」
	,KIB_JK_HKKSH_SCH_NAIYO_33  VARCHAR2(100) --「警備事故報告書措置内容３３」
	,KIB_JK_HKKSH_SCH_NAIYO_34  VARCHAR2(100) --「警備事故報告書措置内容３４」
	,KIB_JK_HKKSH_SCH_NAIYO_35  VARCHAR2(100) --「警備事故報告書措置内容３５」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2521T_PK PRIMARY KEY(
	 KIB_JK_HKKSH_KIB_JH_YMD
	,  KIB_JK_HKKSH_KIB_JH_TM
	,  KIB_JK_HKKSH_KIB_JH_SHNG_CD
	,  KIB_JK_HKKSH_DIBNRI_GNIN_CD
	,  KIB_JK_HKKSH_CHBNRI_GNIN_CD
	,  KIB_JK_HKKSH_SHBNRI_GNIN_CD
	,  DENKEI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2521T_TBL IS '警備事故発生報告書テーブル'
/

COMMENT ON COLUMN ED2521T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KIB_JH_YMD IS '警備事故報告書警備情報年月日'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KIB_JH_TM IS '警備事故報告書警備情報時刻'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KIB_JH_SHNG_CD IS '警備事故報告書警備情報信号コード'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_DIBNRI_GNIN_CD IS '警備事故報告書大分類原因コード'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_CHBNRI_GNIN_CD IS '警備事故報告書中分類原因コード'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SHBNRI_GNIN_CD IS '警備事故報告書小分類原因コード'
/
COMMENT ON COLUMN ED2521T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED2521T_TBL.DENKEI_NO IS '電計番号'
/
COMMENT ON COLUMN ED2521T_TBL.TORIHIKISAKI_CD IS '取引先コード'
/
COMMENT ON COLUMN ED2521T_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED2521T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED2521T_TBL.TAISHOSAKI_JUSHO_CD IS '対象先住所コード'
/
COMMENT ON COLUMN ED2521T_TBL.TAISHOSAKI_EIGYO_NAIYO_CD IS '対象先営業内容コード'
/
COMMENT ON COLUMN ED2521T_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED2521T_TBL.JUCHU_TANTO_SHAIN_NO IS '受注担当社員番号'
/
COMMENT ON COLUMN ED2521T_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KIBSK_NM_1 IS '警備事故報告書警備先名称１'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KIBSK_NM_2 IS '警備事故報告書警備先名称２'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KBTS_NM IS '警備事故報告書個別名称'
/
COMMENT ON COLUMN ED2521T_TBL.KEIBI_JIKO_HOKOKUSHO_SET_YMD IS '警備事故報告書セット年月日'
/
COMMENT ON COLUMN ED2521T_TBL.KEIBI_JIKO_HOKOKUSHO_SET_TM IS '警備事故報告書セット時刻'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_GNIN_SHSI_NAIYO_1 IS '警備事故報告書原因詳細内容１'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_GNIN_SHSI_NAIYO_2 IS '警備事故報告書原因詳細内容２'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_GNIN_SHSI_NAIYO_3 IS '警備事故報告書原因詳細内容３'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KEKKA_NAIYO_1 IS '警備事故報告書結果内容１'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KEKKA_NAIYO_2 IS '警備事故報告書結果内容２'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KEKKA_NAIYO_3 IS '警備事故報告書結果内容３'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KEKKA_NAIYO_4 IS '警備事故報告書結果内容４'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KEKKA_NAIYO_5 IS '警備事故報告書結果内容５'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KEKKA_NAIYO_6 IS '警備事故報告書結果内容６'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KEKKA_NAIYO_7 IS '警備事故報告書結果内容７'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KEKKA_NAIYO_8 IS '警備事故報告書結果内容８'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KEKKA_NAIYO_9 IS '警備事故報告書結果内容９'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KEKKA_NAIYO_10 IS '警備事故報告書結果内容１０'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_TNT_GNCHK_TM IS '警備事故報告書担当現着時刻'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KD_TIKN_TM IS '警備事故報告書機動退館時刻'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_OEN_GNCHK_TM IS '警備事故報告書応援現着時刻'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KISTS_TCHK_TM IS '警備事故報告書警察到着時刻'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_KISTS_TIKN_TM IS '警備事故報告書警察退館時刻'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SHB_TCHK_TM IS '警備事故報告書消防到着時刻'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SHB_TIKN_TM IS '警備事故報告書消防退館時刻'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_1 IS '警備事故報告書措置内容１'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_2 IS '警備事故報告書措置内容２'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_3 IS '警備事故報告書措置内容３'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_4 IS '警備事故報告書措置内容４'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_5 IS '警備事故報告書措置内容５'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_6 IS '警備事故報告書措置内容６'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_7 IS '警備事故報告書措置内容７'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_8 IS '警備事故報告書措置内容８'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_9 IS '警備事故報告書措置内容９'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_10 IS '警備事故報告書措置内容１０'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_11 IS '警備事故報告書措置内容１１'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_12 IS '警備事故報告書措置内容１２'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_13 IS '警備事故報告書措置内容１３'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_14 IS '警備事故報告書措置内容１４'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_15 IS '警備事故報告書措置内容１５'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_16 IS '警備事故報告書措置内容１６'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_17 IS '警備事故報告書措置内容１７'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_18 IS '警備事故報告書措置内容１８'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_19 IS '警備事故報告書措置内容１９'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_20 IS '警備事故報告書措置内容２０'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_21 IS '警備事故報告書措置内容２１'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_22 IS '警備事故報告書措置内容２２'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_23 IS '警備事故報告書措置内容２３'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_24 IS '警備事故報告書措置内容２４'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_25 IS '警備事故報告書措置内容２５'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_26 IS '警備事故報告書措置内容２６'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_27 IS '警備事故報告書措置内容２７'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_28 IS '警備事故報告書措置内容２８'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_29 IS '警備事故報告書措置内容２９'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_30 IS '警備事故報告書措置内容３０'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_31 IS '警備事故報告書措置内容３１'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_32 IS '警備事故報告書措置内容３２'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_33 IS '警備事故報告書措置内容３３'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_34 IS '警備事故報告書措置内容３４'
/
COMMENT ON COLUMN ED2521T_TBL.KIB_JK_HKKSH_SCH_NAIYO_35 IS '警備事故報告書措置内容３５'
/
COMMENT ON COLUMN ED2521T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2521T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2521T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2521T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2521T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2521T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2521T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2521T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2521T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2521T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2521T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2521T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
