/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2502T_TBL.sql
-- 物理名：ED2502T_TBL
-- 論理名：運用綜管防災予実テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2502T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2502T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,SOKAN_BOSAI_KAISHI_YOTEI_YM  CHAR(6) NOT NULL --「綜管防災開始予定年月」
	,UNYO_SOKAN_BOSAI_YOJITSU_SN  CHAR(14) NOT NULL --「運用綜管防災予実連番」
	,GYM_ITKSK_TRHKSK_CD  CHAR(9) --「業務委託先取引先コード」
	,GYM_ITKSK_TRHKSK_BSH_CD  CHAR(4) --「業務委託先取引先部署コード」
	,SKSN_KNR_KOMOKU_DIKMK_CD  CHAR(10) --「積算管理項目大項目コード」
	,SKSN_KNR_KOMOKU_CHKMK_CD  CHAR(10) --「積算管理項目中項目コード」
	,SKSN_KNR_KOMOKU_SHKMK_NAIYO  VARCHAR2(100) --「積算管理項目小項目内容」
	,SOKAN_BOSAI_KAISHI_YOTEI_D  CHAR(2) --「綜管防災開始予定日」
	,SOKAN_BOSAI_KAISHI_YOTEI_TM  CHAR(4) --「綜管防災開始予定時刻」
	,KIYK_KITI_KBN  CHAR(1) NOT NULL --「契約形態区分」
	,SOKAN_BOSAI_JISSHI_KBN  CHAR(1) NOT NULL --「綜管防災実施区分」
	,SOKAN_BOSAI_SHURYO_YOTEI_YM  CHAR(6) --「綜管防災終了予定年月」
	,SOKAN_BOSAI_SHURYO_YOTEI_D  CHAR(2) --「綜管防災終了予定日」
	,SOKAN_BOSAI_SHURYO_YOTEI_TM  CHAR(4) --「綜管防災終了予定時刻」
	,KIKAI_KEIBIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「機械警備有フラグ」
	,ZENKAI_JISSHI_YMD  DATE --「前回実施年月日」
	,HTI_SHRI_GYSI_TISHTS_YTI_YM  CHAR(6) --「法定書類行政提出予定年月」
	,HTI_SHRI_GYSI_TISHTS_YMD  DATE --「法定書類行政提出年月日」
	,JKI_HTI_SRI_GSI_TIST_YTI_YM  CHAR(6) --「次回法定書類行政提出予定年月」
	,SOKAN_BOSAI_JISSHI_KEKKA_KBN  CHAR(1) NOT NULL --「綜管防災実施結果区分」
	,SKN_BSI_JSS_KIS_UKTKS_SIN_NO  VARCHAR2(8) --「綜管防災実施開始受付者社員番号」
	,SOKAN_BOSAI_JISSHI_KAISHI_YM  CHAR(6) --「綜管防災実施開始年月」
	,SOKAN_BOSAI_JISSHI_KAISHI_D  CHAR(2) --「綜管防災実施開始日」
	,SOKAN_BOSAI_JISSHI_KAISHI_TM  CHAR(4) --「綜管防災実施開始時刻」
	,SOKAN_BOSAI_JISSHI_SHURYO_YM  CHAR(6) --「綜管防災実施終了年月」
	,SOKAN_BOSAI_JISSHI_SHURYO_D  CHAR(2) --「綜管防災実施終了日」
	,SOKAN_BOSAI_JISSHI_SHURYO_TM  CHAR(4) --「綜管防災実施終了時刻」
	,SKN_BSI_JSS_SR_UKTKS_SIN_NO  VARCHAR2(8) --「綜管防災実施終了受付者社員番号」
	,SOKAN_BOSAI_KENSHU_KEKKA_KBN  CHAR(1) NOT NULL --「綜管防災検収結果区分」
	,UNYO_SOKAN_BOSAI_YOJITSU_BIKO  VARCHAR2(60) --「運用綜管防災予実備考」
	,GYOMU_ITAKU_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「業務委託料金金額」
	,SKN_BSI_SIKYSH_KKNN_YMD  DATE --「綜管防災請求書確認年月日」
	,SKN_BSI_SIKYSH_KKNNSH_SHIN_NO  VARCHAR2(8) --「綜管防災請求書確認者社員番号」
	,SKN_BSI_HKKSH_KKNN_YMD  DATE --「綜管防災報告書確認年月日」
	,SKN_BSI_HKKSH_KKNNSH_SHIN_NO  VARCHAR2(8) --「綜管防災報告書確認者社員番号」
	,HOKOKUSHO_TEISHUTSUSAKI_KBN  CHAR(1) NOT NULL --「報告書提出先区分」
	,HOKOKUSHO_TEISHUTSU_BUSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「報告書提出部数」
	,HOKOKUSHO_TEISHUTSU_HOHO_KBN  CHAR(1) NOT NULL --「報告書提出方法区分」
	,SEIKYU_HOHO_KBN  CHAR(1) NOT NULL --「請求方法区分」
	,NTTI_RNRK_JSSH_BSH_KBN  CHAR(1) NOT NULL --「日程連絡実施部署区分」
	,YTI_JSSK_NYRYK_BSH_KBN  CHAR(1) NOT NULL --「予定実績入力部署区分」
	,NENKAN_JISSHI_KAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「年間実施回数」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2502T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  SOKAN_BOSAI_KAISHI_YOTEI_YM
	,  UNYO_SOKAN_BOSAI_YOJITSU_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2502T_TBL IS '運用綜管防災予実テーブル'
/

COMMENT ON COLUMN ED2502T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2502T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_KAISHI_YOTEI_YM IS '綜管防災開始予定年月'
/
COMMENT ON COLUMN ED2502T_TBL.UNYO_SOKAN_BOSAI_YOJITSU_SN IS '運用綜管防災予実連番'
/
COMMENT ON COLUMN ED2502T_TBL.GYM_ITKSK_TRHKSK_CD IS '業務委託先取引先コード'
/
COMMENT ON COLUMN ED2502T_TBL.GYM_ITKSK_TRHKSK_BSH_CD IS '業務委託先取引先部署コード'
/
COMMENT ON COLUMN ED2502T_TBL.SKSN_KNR_KOMOKU_DIKMK_CD IS '積算管理項目大項目コード'
/
COMMENT ON COLUMN ED2502T_TBL.SKSN_KNR_KOMOKU_CHKMK_CD IS '積算管理項目中項目コード'
/
COMMENT ON COLUMN ED2502T_TBL.SKSN_KNR_KOMOKU_SHKMK_NAIYO IS '積算管理項目小項目内容'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_KAISHI_YOTEI_D IS '綜管防災開始予定日'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_KAISHI_YOTEI_TM IS '綜管防災開始予定時刻'
/
COMMENT ON COLUMN ED2502T_TBL.KIYK_KITI_KBN IS '契約形態区分'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_JISSHI_KBN IS '綜管防災実施区分'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_SHURYO_YOTEI_YM IS '綜管防災終了予定年月'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_SHURYO_YOTEI_D IS '綜管防災終了予定日'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_SHURYO_YOTEI_TM IS '綜管防災終了予定時刻'
/
COMMENT ON COLUMN ED2502T_TBL.KIKAI_KEIBIARI_FLG IS '機械警備有フラグ'
/
COMMENT ON COLUMN ED2502T_TBL.ZENKAI_JISSHI_YMD IS '前回実施年月日'
/
COMMENT ON COLUMN ED2502T_TBL.HTI_SHRI_GYSI_TISHTS_YTI_YM IS '法定書類行政提出予定年月'
/
COMMENT ON COLUMN ED2502T_TBL.HTI_SHRI_GYSI_TISHTS_YMD IS '法定書類行政提出年月日'
/
COMMENT ON COLUMN ED2502T_TBL.JKI_HTI_SRI_GSI_TIST_YTI_YM IS '次回法定書類行政提出予定年月'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_JISSHI_KEKKA_KBN IS '綜管防災実施結果区分'
/
COMMENT ON COLUMN ED2502T_TBL.SKN_BSI_JSS_KIS_UKTKS_SIN_NO IS '綜管防災実施開始受付者社員番号'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_JISSHI_KAISHI_YM IS '綜管防災実施開始年月'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_JISSHI_KAISHI_D IS '綜管防災実施開始日'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_JISSHI_KAISHI_TM IS '綜管防災実施開始時刻'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_JISSHI_SHURYO_YM IS '綜管防災実施終了年月'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_JISSHI_SHURYO_D IS '綜管防災実施終了日'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_JISSHI_SHURYO_TM IS '綜管防災実施終了時刻'
/
COMMENT ON COLUMN ED2502T_TBL.SKN_BSI_JSS_SR_UKTKS_SIN_NO IS '綜管防災実施終了受付者社員番号'
/
COMMENT ON COLUMN ED2502T_TBL.SOKAN_BOSAI_KENSHU_KEKKA_KBN IS '綜管防災検収結果区分'
/
COMMENT ON COLUMN ED2502T_TBL.UNYO_SOKAN_BOSAI_YOJITSU_BIKO IS '運用綜管防災予実備考'
/
COMMENT ON COLUMN ED2502T_TBL.GYOMU_ITAKU_RYOKIN_AMT IS '業務委託料金金額'
/
COMMENT ON COLUMN ED2502T_TBL.SKN_BSI_SIKYSH_KKNN_YMD IS '綜管防災請求書確認年月日'
/
COMMENT ON COLUMN ED2502T_TBL.SKN_BSI_SIKYSH_KKNNSH_SHIN_NO IS '綜管防災請求書確認者社員番号'
/
COMMENT ON COLUMN ED2502T_TBL.SKN_BSI_HKKSH_KKNN_YMD IS '綜管防災報告書確認年月日'
/
COMMENT ON COLUMN ED2502T_TBL.SKN_BSI_HKKSH_KKNNSH_SHIN_NO IS '綜管防災報告書確認者社員番号'
/
COMMENT ON COLUMN ED2502T_TBL.HOKOKUSHO_TEISHUTSUSAKI_KBN IS '報告書提出先区分'
/
COMMENT ON COLUMN ED2502T_TBL.HOKOKUSHO_TEISHUTSU_BUSU IS '報告書提出部数'
/
COMMENT ON COLUMN ED2502T_TBL.HOKOKUSHO_TEISHUTSU_HOHO_KBN IS '報告書提出方法区分'
/
COMMENT ON COLUMN ED2502T_TBL.SEIKYU_HOHO_KBN IS '請求方法区分'
/
COMMENT ON COLUMN ED2502T_TBL.NTTI_RNRK_JSSH_BSH_KBN IS '日程連絡実施部署区分'
/
COMMENT ON COLUMN ED2502T_TBL.YTI_JSSK_NYRYK_BSH_KBN IS '予定実績入力部署区分'
/
COMMENT ON COLUMN ED2502T_TBL.NENKAN_JISSHI_KAISU IS '年間実施回数'
/
COMMENT ON COLUMN ED2502T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2502T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2502T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2502T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2502T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2502T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2502T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2502T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2502T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2502T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2502T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2502T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
