/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2520T_TBL.sql
-- 物理名：ED2520T_TBL
-- 論理名：機械警備運用台帳ファイル管理テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2520T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2520T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KIKAIKEIBI_UNYODAICHO_FILE_SN  NUMBER(14,0) DEFAULT '0' NOT NULL --「機械警備運用台帳ファイル連番」
	,KKIKIB_UNYDIC_KIBKI_RNKIZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「機械警備運用台帳警備系連携済フラグ」
	,KKIKIB_UNYDIC_FILE_SHKBTS_KEY  VARCHAR2(255) --「機械警備運用台帳ファイル識別キー」
	,KIKAIKEIBI_UNYODAICHO_FILE_NM  VARCHAR2(255) --「機械警備運用台帳ファイル名称」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,DENKEI_NO  CHAR(9) --「電計番号」
	,GC_GOKI_NO  CHAR(11) --「ＧＣ号機番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2520T_PK PRIMARY KEY(
	 KIKAIKEIBI_UNYODAICHO_FILE_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2520T_TBL IS '機械警備運用台帳ファイル管理テーブル'
/

COMMENT ON COLUMN ED2520T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2520T_TBL.KIKAIKEIBI_UNYODAICHO_FILE_SN IS '機械警備運用台帳ファイル連番'
/
COMMENT ON COLUMN ED2520T_TBL.KKIKIB_UNYDIC_KIBKI_RNKIZM_FLG IS '機械警備運用台帳警備系連携済フラグ'
/
COMMENT ON COLUMN ED2520T_TBL.KKIKIB_UNYDIC_FILE_SHKBTS_KEY IS '機械警備運用台帳ファイル識別キー'
/
COMMENT ON COLUMN ED2520T_TBL.KIKAIKEIBI_UNYODAICHO_FILE_NM IS '機械警備運用台帳ファイル名称'
/
COMMENT ON COLUMN ED2520T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED2520T_TBL.DENKEI_NO IS '電計番号'
/
COMMENT ON COLUMN ED2520T_TBL.GC_GOKI_NO IS 'ＧＣ号機番号'
/
COMMENT ON COLUMN ED2520T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2520T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2520T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2520T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2520T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2520T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2520T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2520T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2520T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2520T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2520T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2520T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
