/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2546T_TBL.sql
-- 物理名：ED2546T_TBL
-- 論理名：常駐警備充足率テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2546T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2546T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,UNY_JSS_JK_HKKSH_SKSI_TISH_YM  CHAR(6) NOT NULL --「運用実施状況報告書作成対象年月」
	,JISSHI_KAISHA_NM  VARCHAR2(40) --「実施会社名称」
	,JISSHI_JIGYOSHO_CD  CHAR(6) NOT NULL --「実施事業所コード」
	,JISSHI_JIGYOSHO_NM  VARCHAR2(200) --「実施事業所名称」
	,NENKAN_SHOTEINAI_RODO_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「年間所定内労働時間」
	,SHOYO_JININ_NINZU  NUMBER(12,3) DEFAULT '0' NOT NULL --「所要人員人数」
	,HAICHI_JININ_NINZU  NUMBER(9,0) DEFAULT '0' NOT NULL --「配置人員人数」
	,JUSOKU_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「充足率」
	,RINJI_KEIBI_JISSEKI_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「臨時警備実績時間」
	,RINJI_KEIBI_JISSEKI_NINZU  NUMBER(9,0) DEFAULT '0' NOT NULL --「臨時警備実績人数」
	,RINJI_KEIBI_KOMI_JUSOKU_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「臨時警備込充足率」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2546T_PK PRIMARY KEY(
	 UNY_JSS_JK_HKKSH_SKSI_TISH_YM
	,  JISSHI_JIGYOSHO_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2546T_TBL IS '常駐警備充足率テーブル'
/

COMMENT ON COLUMN ED2546T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2546T_TBL.UNY_JSS_JK_HKKSH_SKSI_TISH_YM IS '運用実施状況報告書作成対象年月'
/
COMMENT ON COLUMN ED2546T_TBL.JISSHI_KAISHA_NM IS '実施会社名称'
/
COMMENT ON COLUMN ED2546T_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED2546T_TBL.JISSHI_JIGYOSHO_NM IS '実施事業所名称'
/
COMMENT ON COLUMN ED2546T_TBL.NENKAN_SHOTEINAI_RODO_JIKAN IS '年間所定内労働時間'
/
COMMENT ON COLUMN ED2546T_TBL.SHOYO_JININ_NINZU IS '所要人員人数'
/
COMMENT ON COLUMN ED2546T_TBL.HAICHI_JININ_NINZU IS '配置人員人数'
/
COMMENT ON COLUMN ED2546T_TBL.JUSOKU_RITSU IS '充足率'
/
COMMENT ON COLUMN ED2546T_TBL.RINJI_KEIBI_JISSEKI_JIKAN IS '臨時警備実績時間'
/
COMMENT ON COLUMN ED2546T_TBL.RINJI_KEIBI_JISSEKI_NINZU IS '臨時警備実績人数'
/
COMMENT ON COLUMN ED2546T_TBL.RINJI_KEIBI_KOMI_JUSOKU_RITSU IS '臨時警備込充足率'
/
COMMENT ON COLUMN ED2546T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2546T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2546T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2546T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2546T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2546T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2546T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2546T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2546T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2546T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2546T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2546T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
