/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2522W_TBL.sql
-- 物理名：ED2522W_TBL
-- 論理名：運用実績情報ＧＣ実績ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2522W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2522W_TBL (
	 GC_KAISHA_CD  CHAR(5) NOT NULL --「ＧＣ＿会社コード」
	,GC_SN  NUMBER(14,0) DEFAULT '0' NOT NULL --「ＧＣ＿連番」
	,GC_FILE_JOTAI  CHAR(1) --「ＧＣ＿ファイル状態」
	,GC_NO  CHAR(4) --「ＧＣ＿番号」
	,GC_SGS_RONRI_NO  NUMBER(10,0) --「ＧＣ＿ＳＧＳ論理番号」
	,GC_DENKEI_NO  CHAR(9) NOT NULL --「ＧＣ＿電計番号」
	,GC_JIAN_HASSEI_HIZUKE  CHAR(14) NOT NULL --「ＧＣ＿事案発生日付」
	,GC_RAKUCHAKU_HIZUKE  CHAR(12) NOT NULL --「ＧＣ＿落着日付」
	,GC_NYUKAN_JIKAN  CHAR(4) NOT NULL --「ＧＣ＿入館時間」
	,GC_SHURYO_JIKAN  CHAR(4) --「ＧＣ＿終了時間」
	,GC_GENIN_SHOSAI_NAIYO  VARCHAR2(30) NOT NULL --「ＧＣ＿原因詳細内容」
	,GC_GENIN_NAIYO_1  VARCHAR2(30) --「ＧＣ＿原因内容１」
	,GC_GENIN_NAIYO_2  VARCHAR2(30) --「ＧＣ＿原因内容２」
	,GC_JIGYOSHO_CD  CHAR(6) NOT NULL --「ＧＣ＿事業所コード」
	,GC_SUB_ADDRESS  CHAR(4) --「ＧＣ＿サブアドレス」
	,GC_SGS_GENIN_CD  CHAR(3) NOT NULL --「ＧＣ＿ＳＧＳ原因コード」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2522W_PK PRIMARY KEY(
	 GC_SN
	,  GC_KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2522W_TBL IS '運用実績情報ＧＣ実績ワーク'
/

COMMENT ON COLUMN ED2522W_TBL.GC_KAISHA_CD IS 'ＧＣ＿会社コード'
/
COMMENT ON COLUMN ED2522W_TBL.GC_SN IS 'ＧＣ＿連番'
/
COMMENT ON COLUMN ED2522W_TBL.GC_FILE_JOTAI IS 'ＧＣ＿ファイル状態'
/
COMMENT ON COLUMN ED2522W_TBL.GC_NO IS 'ＧＣ＿番号'
/
COMMENT ON COLUMN ED2522W_TBL.GC_SGS_RONRI_NO IS 'ＧＣ＿ＳＧＳ論理番号'
/
COMMENT ON COLUMN ED2522W_TBL.GC_DENKEI_NO IS 'ＧＣ＿電計番号'
/
COMMENT ON COLUMN ED2522W_TBL.GC_JIAN_HASSEI_HIZUKE IS 'ＧＣ＿事案発生日付'
/
COMMENT ON COLUMN ED2522W_TBL.GC_RAKUCHAKU_HIZUKE IS 'ＧＣ＿落着日付'
/
COMMENT ON COLUMN ED2522W_TBL.GC_NYUKAN_JIKAN IS 'ＧＣ＿入館時間'
/
COMMENT ON COLUMN ED2522W_TBL.GC_SHURYO_JIKAN IS 'ＧＣ＿終了時間'
/
COMMENT ON COLUMN ED2522W_TBL.GC_GENIN_SHOSAI_NAIYO IS 'ＧＣ＿原因詳細内容'
/
COMMENT ON COLUMN ED2522W_TBL.GC_GENIN_NAIYO_1 IS 'ＧＣ＿原因内容１'
/
COMMENT ON COLUMN ED2522W_TBL.GC_GENIN_NAIYO_2 IS 'ＧＣ＿原因内容２'
/
COMMENT ON COLUMN ED2522W_TBL.GC_JIGYOSHO_CD IS 'ＧＣ＿事業所コード'
/
COMMENT ON COLUMN ED2522W_TBL.GC_SUB_ADDRESS IS 'ＧＣ＿サブアドレス'
/
COMMENT ON COLUMN ED2522W_TBL.GC_SGS_GENIN_CD IS 'ＧＣ＿ＳＧＳ原因コード'
/
COMMENT ON COLUMN ED2522W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2522W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2522W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2522W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2522W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2522W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2522W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2522W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2522W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2522W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2522W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2522W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
