/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2523W_TBL.sql
-- 物理名：ED2523W_TBL
-- 論理名：運用実績情報コスモ実績ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2523W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2523W_TBL (
	 CC_KAISHA_CD  CHAR(5) NOT NULL --「ＣＣ＿会社コード」
	,CC_SN  NUMBER(14,0) DEFAULT '0' NOT NULL --「ＣＣ＿連番」
	,CC_DENKEI_NO  CHAR(9) NOT NULL --「ＣＣ＿電計番号」
	,CC_KEIYAKUSAKI_CD  CHAR(4) --「ＣＣ＿契約先コード」
	,CC_KEIYAKUSAKIMEI  VARCHAR2(30) --「ＣＣ＿契約先名」
	,CC_SHITEN_CD  CHAR(5) NOT NULL --「ＣＣ＿支店コード」
	,CC_BN  CHAR(3) NOT NULL --「ＣＣ＿枝番」
	,CC_KOKYAKUSAKI_NM  VARCHAR2(50) --「ＣＣ＿顧客先名称」
	,CC_KEIYAKUSAKI_UKETSUKE_DT  CHAR(12) NOT NULL --「ＣＣ＿契約先受付日時」
	,CC_KEIYAKUSAKI_HASSHINSHA  VARCHAR2(20) --「ＣＣ＿契約先発信者」
	,CC_YOSEI_MD  CHAR(4) NOT NULL --「ＣＣ＿要請月日」
	,CC_SHUTSUDO_SHOGAI_CD  CHAR(4) NOT NULL --「ＣＣ＿出動障害コード」
	,CC_SHUTSUDO_SHOGAI_NAIYO  VARCHAR2(20) NOT NULL --「ＣＣ＿出動障害内容」
	,CC_SHUTSUDO_KYAKUMACHI  CHAR(1) --「ＣＣ＿出動客待ち」
	,CC_SHIREI_SHOYO  CHAR(3) --「ＣＣ＿指令所要」
	,CC_TOCHAKU_SHOYO  CHAR(3) --「ＣＣ＿到着所要」
	,CC_SHOCHI_SHOYO  CHAR(3) --「ＣＣ＿処置所要」
	,CC_NYUKAN_SHOYO  CHAR(3) --「ＣＣ＿入館所要」
	,CC_TACHIAI_SHOYO  CHAR(3) --「ＣＣ＿立会所要」
	,CC_SOSHOYO  CHAR(3) --「ＣＣ＿総所要」
	,CC_SOSHINSAKI_KBN  CHAR(1) --「ＣＣ＿送信先区分」
	,CC_TANTO_SHISHA  NUMBER(6,0) --「ＣＣ＿担当支社」
	,CC_JIGYOSHO_NM  VARCHAR2(15) --「ＣＣ＿事業所名称」
	,CC_RAKUCHAKU_TOROKU_HIZUKE  CHAR(12) NOT NULL --「ＣＣ＿落着登録日付」
	,CC_YOSEI_TM  CHAR(4) --「ＣＣ＿要請時刻」
	,CC_SHOYO_MIKOMI  CHAR(3) --「ＣＣ＿所要見込み」
	,CC_SHIJI_TM  CHAR(4) --「ＣＣ＿指示時刻」
	,CC_GENCHAKU_TM  CHAR(4) --「ＣＣ＿現着時刻」
	,CC_KAISHI_TM  CHAR(4) --「ＣＣ＿開始時刻」
	,CC_SHURYO_TM  CHAR(4) --「ＣＣ＿終了時刻」
	,CC_TAIKAN_TM  CHAR(4) NOT NULL --「ＣＣ＿退館時刻」
	,CC_HOSHU_TOCHAKU_TM  CHAR(4) --「ＣＣ＿保守到着時刻」
	,CC_HOSHU_TAIKAN_TM  CHAR(4) --「ＣＣ＿保守退館時刻」
	,CC_HOSHU_KAISHAMEI  VARCHAR2(20) --「ＣＣ＿保守会社名」
	,CC_HOSHUIN  VARCHAR2(20) --「ＣＣ＿保守員」
	,CC_ATM_NO  VARCHAR2(4) NOT NULL --「ＣＣ＿ＡＴＭ番号」
	,CC_SHITEI_DT  CHAR(12) --「ＣＣ＿指定日時」
	,CC_HOSHU_YOTEI  CHAR(12) --「ＣＣ＿保守予定」
	,CC_TACHAKU_YOTEI  CHAR(12) --「ＣＣ＿他着予定」
	,CC_SHOCHI_NAIYO_1  VARCHAR2(40) --「ＣＣ＿処置内容１」
	,CC_SHOCHI_NAIYO_2  VARCHAR2(40) --「ＣＣ＿処置内容２」
	,CC_BIKO_1  VARCHAR2(50) --「ＣＣ＿備考１」
	,CC_BIKO_2  VARCHAR2(50) --「ＣＣ＿備考２」
	,CC_BIKO_3  VARCHAR2(50) --「ＣＣ＿備考３」
	,CC_BIKO_4  VARCHAR2(50) --「ＣＣ＿備考４」
	,CC_BIKO_5  VARCHAR2(50) --「ＣＣ＿備考５」
	,CC_BIKO_6  VARCHAR2(50) --「ＣＣ＿備考６」
	,CC_BIKO_7  VARCHAR2(50) --「ＣＣ＿備考７」
	,CC_BIKO_8  VARCHAR2(50) --「ＣＣ＿備考８」
	,CC_BIKO_9  VARCHAR2(50) --「ＣＣ＿備考９」
	,CC_BIKO_10  VARCHAR2(50) --「ＣＣ＿備考１０」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2523W_PK PRIMARY KEY(
	 CC_SN
	,  CC_KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2523W_TBL IS '運用実績情報コスモ実績ワーク'
/

COMMENT ON COLUMN ED2523W_TBL.CC_KAISHA_CD IS 'ＣＣ＿会社コード'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SN IS 'ＣＣ＿連番'
/
COMMENT ON COLUMN ED2523W_TBL.CC_DENKEI_NO IS 'ＣＣ＿電計番号'
/
COMMENT ON COLUMN ED2523W_TBL.CC_KEIYAKUSAKI_CD IS 'ＣＣ＿契約先コード'
/
COMMENT ON COLUMN ED2523W_TBL.CC_KEIYAKUSAKIMEI IS 'ＣＣ＿契約先名'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SHITEN_CD IS 'ＣＣ＿支店コード'
/
COMMENT ON COLUMN ED2523W_TBL.CC_BN IS 'ＣＣ＿枝番'
/
COMMENT ON COLUMN ED2523W_TBL.CC_KOKYAKUSAKI_NM IS 'ＣＣ＿顧客先名称'
/
COMMENT ON COLUMN ED2523W_TBL.CC_KEIYAKUSAKI_UKETSUKE_DT IS 'ＣＣ＿契約先受付日時'
/
COMMENT ON COLUMN ED2523W_TBL.CC_KEIYAKUSAKI_HASSHINSHA IS 'ＣＣ＿契約先発信者'
/
COMMENT ON COLUMN ED2523W_TBL.CC_YOSEI_MD IS 'ＣＣ＿要請月日'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SHUTSUDO_SHOGAI_CD IS 'ＣＣ＿出動障害コード'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SHUTSUDO_SHOGAI_NAIYO IS 'ＣＣ＿出動障害内容'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SHUTSUDO_KYAKUMACHI IS 'ＣＣ＿出動客待ち'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SHIREI_SHOYO IS 'ＣＣ＿指令所要'
/
COMMENT ON COLUMN ED2523W_TBL.CC_TOCHAKU_SHOYO IS 'ＣＣ＿到着所要'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SHOCHI_SHOYO IS 'ＣＣ＿処置所要'
/
COMMENT ON COLUMN ED2523W_TBL.CC_NYUKAN_SHOYO IS 'ＣＣ＿入館所要'
/
COMMENT ON COLUMN ED2523W_TBL.CC_TACHIAI_SHOYO IS 'ＣＣ＿立会所要'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SOSHOYO IS 'ＣＣ＿総所要'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SOSHINSAKI_KBN IS 'ＣＣ＿送信先区分'
/
COMMENT ON COLUMN ED2523W_TBL.CC_TANTO_SHISHA IS 'ＣＣ＿担当支社'
/
COMMENT ON COLUMN ED2523W_TBL.CC_JIGYOSHO_NM IS 'ＣＣ＿事業所名称'
/
COMMENT ON COLUMN ED2523W_TBL.CC_RAKUCHAKU_TOROKU_HIZUKE IS 'ＣＣ＿落着登録日付'
/
COMMENT ON COLUMN ED2523W_TBL.CC_YOSEI_TM IS 'ＣＣ＿要請時刻'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SHOYO_MIKOMI IS 'ＣＣ＿所要見込み'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SHIJI_TM IS 'ＣＣ＿指示時刻'
/
COMMENT ON COLUMN ED2523W_TBL.CC_GENCHAKU_TM IS 'ＣＣ＿現着時刻'
/
COMMENT ON COLUMN ED2523W_TBL.CC_KAISHI_TM IS 'ＣＣ＿開始時刻'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SHURYO_TM IS 'ＣＣ＿終了時刻'
/
COMMENT ON COLUMN ED2523W_TBL.CC_TAIKAN_TM IS 'ＣＣ＿退館時刻'
/
COMMENT ON COLUMN ED2523W_TBL.CC_HOSHU_TOCHAKU_TM IS 'ＣＣ＿保守到着時刻'
/
COMMENT ON COLUMN ED2523W_TBL.CC_HOSHU_TAIKAN_TM IS 'ＣＣ＿保守退館時刻'
/
COMMENT ON COLUMN ED2523W_TBL.CC_HOSHU_KAISHAMEI IS 'ＣＣ＿保守会社名'
/
COMMENT ON COLUMN ED2523W_TBL.CC_HOSHUIN IS 'ＣＣ＿保守員'
/
COMMENT ON COLUMN ED2523W_TBL.CC_ATM_NO IS 'ＣＣ＿ＡＴＭ番号'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SHITEI_DT IS 'ＣＣ＿指定日時'
/
COMMENT ON COLUMN ED2523W_TBL.CC_HOSHU_YOTEI IS 'ＣＣ＿保守予定'
/
COMMENT ON COLUMN ED2523W_TBL.CC_TACHAKU_YOTEI IS 'ＣＣ＿他着予定'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SHOCHI_NAIYO_1 IS 'ＣＣ＿処置内容１'
/
COMMENT ON COLUMN ED2523W_TBL.CC_SHOCHI_NAIYO_2 IS 'ＣＣ＿処置内容２'
/
COMMENT ON COLUMN ED2523W_TBL.CC_BIKO_1 IS 'ＣＣ＿備考１'
/
COMMENT ON COLUMN ED2523W_TBL.CC_BIKO_2 IS 'ＣＣ＿備考２'
/
COMMENT ON COLUMN ED2523W_TBL.CC_BIKO_3 IS 'ＣＣ＿備考３'
/
COMMENT ON COLUMN ED2523W_TBL.CC_BIKO_4 IS 'ＣＣ＿備考４'
/
COMMENT ON COLUMN ED2523W_TBL.CC_BIKO_5 IS 'ＣＣ＿備考５'
/
COMMENT ON COLUMN ED2523W_TBL.CC_BIKO_6 IS 'ＣＣ＿備考６'
/
COMMENT ON COLUMN ED2523W_TBL.CC_BIKO_7 IS 'ＣＣ＿備考７'
/
COMMENT ON COLUMN ED2523W_TBL.CC_BIKO_8 IS 'ＣＣ＿備考８'
/
COMMENT ON COLUMN ED2523W_TBL.CC_BIKO_9 IS 'ＣＣ＿備考９'
/
COMMENT ON COLUMN ED2523W_TBL.CC_BIKO_10 IS 'ＣＣ＿備考１０'
/
COMMENT ON COLUMN ED2523W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2523W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2523W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2523W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2523W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2523W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2523W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2523W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2523W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2523W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2523W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2523W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
