/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2540W_TBL.sql
-- 物理名：ED2540W_TBL
-- 論理名：請求対象選定用ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2540W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2540W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SEIKYU_TAISHO_SENTEIYO_SN  NUMBER(14,0) DEFAULT '0' NOT NULL --「請求対象選定用連番」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,SHUTSUDO_JISSEKI_NO  CHAR(5) NOT NULL --「出動実績番号」
	,JISSEKI_SEIKYU_TAISHO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「実績請求対象フラグ」
	,JSSK_SIKY_SKJ_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「実績請求削除対象フラグ」
	,SHTSD_SIKY_SKJ_SHNSI_CMNT  VARCHAR2(30) --「出動請求削除申請コメント」
	,SEIKYUSHO_TEMPLATE_NO  CHAR(14) --「請求書テンプレート番号」
	,SHUTSUDO_JITSUSEIKYU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「出動実請求金額」
	,GYOMU_ITAKU_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「業務委託料金金額」
	,SHUTSUDO_GENIN_NAIYO_1  VARCHAR2(100) --「出動原因内容１」
	,SHUTSUDO_GENIN_NAIYO_2  VARCHAR2(100) --「出動原因内容２」
	,SHUTSUDO_JISSHI_NAIYO  VARCHAR2(30) --「出動実施内容」
	,SHUTSUDO_YOSEI_YMD  DATE --「出動要請年月日」
	,SHUTSUDO_YOSEI_TM  CHAR(4) --「出動要請時刻」
	,SHUTSUDO_SHIJI_TM  CHAR(4) --「出動指示時刻」
	,SHUTSUDO_GENCHAKU_YMD  DATE --「出動現着年月日」
	,SHUTSUDO_GENCHAKU_TM  CHAR(4) --「出動現着時刻」
	,SHUTSUDO_KAISHI_YMD  DATE --「出動開始年月日」
	,SHUTSUDO_KAISHI_TM  CHAR(4) --「出動開始時刻」
	,SHUTSUDO_SHURYO_YMD  DATE --「出動終了年月日」
	,SHUTSUDO_SHURYO_TM  CHAR(4) --「出動終了時刻」
	,SHUTSUDO_JISSEKI_KAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「出動実績回数」
	,SHUTSUDO_TAIKAN_YMD  DATE --「出動退館年月日」
	,SHUTSUDO_TAIKAN_TM  CHAR(4) --「出動退館時刻」
	,SHOHIN_SERVICE_NM  VARCHAR2(60) --「商品サービス名称」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,KIYKSK_TRHKSK_SISHK_NM  VARCHAR2(50) --「契約先取引先正式名称」
	,KIYKSK_TRHKSK_BSH_CD  CHAR(4) --「契約先取引先部署コード」
	,KEIYAKUSAKI_BUSHO_NM  VARCHAR2(40) --「契約先部署名称」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,TAISHOSAKI_NM  VARCHAR2(40) --「対象先名称」
	,JISSHI_JIGYOSHO_CD  CHAR(6) --「実施事業所コード」
	,JISSHI_JIGYOSHO_NM  VARCHAR2(200) --「実施事業所名称」
	,GYM_ITKSK_TRHKSK_CD  CHAR(9) --「業務委託先取引先コード」
	,GYM_ITKSK_TRHKSK_SISHK_NM  VARCHAR2(50) --「業務委託先取引先正式名称」
	,GYM_ITKSK_TRHKSK_BSH_CD  CHAR(4) --「業務委託先取引先部署コード」
	,GYOMU_ITAKUSAKI_BUSHO_NM  VARCHAR2(40) --「業務委託先部署名称」
	,KEISO_URIAGE_HAIBUN_KBN  CHAR(2) NOT NULL --「警送売上配分区分」
	,COSMO_MISEBAN_NO  CHAR(15) --「コスモ店番番号」
	,COSMO_MISEBAN_NO_BN  CHAR(5) --「コスモ店番番号枝番」
	,COSMO_GIB_SHTSD_SHGI_NAIYO_KBN  CHAR(4) --「コスモ外部出動障害内容区分」
	,SHUTSUDO_SHOGAI_NAIYO  VARCHAR2(30) --「出動障害内容」
	,HOSHU_SHUTSUDO_TOCHAKU_YMD  DATE --「保守出動到着年月日」
	,HOSHU_SHUTSUDO_TOCHAKU_TM  CHAR(4) --「保守出動到着時刻」
	,HOSHU_SHUTSUDO_TAIKAN_YMD  DATE --「保守出動退館年月日」
	,HOSHU_SHUTSUDO_TAIKAN_TM  CHAR(4) --「保守出動退館時刻」
	,COSMO_GAIBU_HOSHU_KAISHA_NM  VARCHAR2(40) --「コスモ外部保守会社名称」
	,COSMO_GIB_HSH_TNT_SHIN_NM  VARCHAR2(60) --「コスモ外部保守担当社員氏名」
	,COSMO_SHOCHI_NAIYO_1  VARCHAR2(60) --「コスモ処置内容１」
	,COSMO_SHOCHI_NAIYO_2  VARCHAR2(60) --「コスモ処置内容２」
	,SHUTSUDO_NAIYO_BIKO  VARCHAR2(500) --「出動内容備考」
	,SHUTSUDO_RYOKIN_KAKIN_JOKEN_CD  CHAR(3) --「出動料金課金条件コード」
	,SHUTSUDO_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「出動料金金額」
	,STD_HS_TCAI_RKN_KKN_JKN_CD  CHAR(3) --「出動保守立会料金課金条件コード」
	,SHTSD_HSH_TCHAI_RYKN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「出動保守立会料金金額」
	,SHTSD_SNT_RYKN_KKN_JKN_CD  CHAR(3) --「出動その他料金課金条件コード」
	,SHUTSUDO_SONOTA_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「出動その他料金金額」
	,SHUTSUDO_JISSEKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「出動実績金額」
	,SHTSD_RNJ_JCH_KIYK_NO  CHAR(15) --「出動臨時受注契約番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2540W_PK PRIMARY KEY(
	 SEIKYU_TAISHO_SENTEIYO_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2540W_TBL IS '請求対象選定用ワーク'
/

COMMENT ON COLUMN ED2540W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2540W_TBL.SEIKYU_TAISHO_SENTEIYO_SN IS '請求対象選定用連番'
/
COMMENT ON COLUMN ED2540W_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_JISSEKI_NO IS '出動実績番号'
/
COMMENT ON COLUMN ED2540W_TBL.JISSEKI_SEIKYU_TAISHO_FLG IS '実績請求対象フラグ'
/
COMMENT ON COLUMN ED2540W_TBL.JSSK_SIKY_SKJ_TISH_FLG IS '実績請求削除対象フラグ'
/
COMMENT ON COLUMN ED2540W_TBL.SHTSD_SIKY_SKJ_SHNSI_CMNT IS '出動請求削除申請コメント'
/
COMMENT ON COLUMN ED2540W_TBL.SEIKYUSHO_TEMPLATE_NO IS '請求書テンプレート番号'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_JITSUSEIKYU_AMT IS '出動実請求金額'
/
COMMENT ON COLUMN ED2540W_TBL.GYOMU_ITAKU_RYOKIN_AMT IS '業務委託料金金額'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_GENIN_NAIYO_1 IS '出動原因内容１'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_GENIN_NAIYO_2 IS '出動原因内容２'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_JISSHI_NAIYO IS '出動実施内容'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_YOSEI_YMD IS '出動要請年月日'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_YOSEI_TM IS '出動要請時刻'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_SHIJI_TM IS '出動指示時刻'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_GENCHAKU_YMD IS '出動現着年月日'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_GENCHAKU_TM IS '出動現着時刻'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_KAISHI_YMD IS '出動開始年月日'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_KAISHI_TM IS '出動開始時刻'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_SHURYO_YMD IS '出動終了年月日'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_SHURYO_TM IS '出動終了時刻'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_JISSEKI_KAISU IS '出動実績回数'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_TAIKAN_YMD IS '出動退館年月日'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_TAIKAN_TM IS '出動退館時刻'
/
COMMENT ON COLUMN ED2540W_TBL.SHOHIN_SERVICE_NM IS '商品サービス名称'
/
COMMENT ON COLUMN ED2540W_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED2540W_TBL.KIYKSK_TRHKSK_SISHK_NM IS '契約先取引先正式名称'
/
COMMENT ON COLUMN ED2540W_TBL.KIYKSK_TRHKSK_BSH_CD IS '契約先取引先部署コード'
/
COMMENT ON COLUMN ED2540W_TBL.KEIYAKUSAKI_BUSHO_NM IS '契約先部署名称'
/
COMMENT ON COLUMN ED2540W_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED2540W_TBL.TAISHOSAKI_NM IS '対象先名称'
/
COMMENT ON COLUMN ED2540W_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED2540W_TBL.JISSHI_JIGYOSHO_NM IS '実施事業所名称'
/
COMMENT ON COLUMN ED2540W_TBL.GYM_ITKSK_TRHKSK_CD IS '業務委託先取引先コード'
/
COMMENT ON COLUMN ED2540W_TBL.GYM_ITKSK_TRHKSK_SISHK_NM IS '業務委託先取引先正式名称'
/
COMMENT ON COLUMN ED2540W_TBL.GYM_ITKSK_TRHKSK_BSH_CD IS '業務委託先取引先部署コード'
/
COMMENT ON COLUMN ED2540W_TBL.GYOMU_ITAKUSAKI_BUSHO_NM IS '業務委託先部署名称'
/
COMMENT ON COLUMN ED2540W_TBL.KEISO_URIAGE_HAIBUN_KBN IS '警送売上配分区分'
/
COMMENT ON COLUMN ED2540W_TBL.COSMO_MISEBAN_NO IS 'コスモ店番番号'
/
COMMENT ON COLUMN ED2540W_TBL.COSMO_MISEBAN_NO_BN IS 'コスモ店番番号枝番'
/
COMMENT ON COLUMN ED2540W_TBL.COSMO_GIB_SHTSD_SHGI_NAIYO_KBN IS 'コスモ外部出動障害内容区分'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_SHOGAI_NAIYO IS '出動障害内容'
/
COMMENT ON COLUMN ED2540W_TBL.HOSHU_SHUTSUDO_TOCHAKU_YMD IS '保守出動到着年月日'
/
COMMENT ON COLUMN ED2540W_TBL.HOSHU_SHUTSUDO_TOCHAKU_TM IS '保守出動到着時刻'
/
COMMENT ON COLUMN ED2540W_TBL.HOSHU_SHUTSUDO_TAIKAN_YMD IS '保守出動退館年月日'
/
COMMENT ON COLUMN ED2540W_TBL.HOSHU_SHUTSUDO_TAIKAN_TM IS '保守出動退館時刻'
/
COMMENT ON COLUMN ED2540W_TBL.COSMO_GAIBU_HOSHU_KAISHA_NM IS 'コスモ外部保守会社名称'
/
COMMENT ON COLUMN ED2540W_TBL.COSMO_GIB_HSH_TNT_SHIN_NM IS 'コスモ外部保守担当社員氏名'
/
COMMENT ON COLUMN ED2540W_TBL.COSMO_SHOCHI_NAIYO_1 IS 'コスモ処置内容１'
/
COMMENT ON COLUMN ED2540W_TBL.COSMO_SHOCHI_NAIYO_2 IS 'コスモ処置内容２'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_NAIYO_BIKO IS '出動内容備考'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_RYOKIN_KAKIN_JOKEN_CD IS '出動料金課金条件コード'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_RYOKIN_AMT IS '出動料金金額'
/
COMMENT ON COLUMN ED2540W_TBL.STD_HS_TCAI_RKN_KKN_JKN_CD IS '出動保守立会料金課金条件コード'
/
COMMENT ON COLUMN ED2540W_TBL.SHTSD_HSH_TCHAI_RYKN_AMT IS '出動保守立会料金金額'
/
COMMENT ON COLUMN ED2540W_TBL.SHTSD_SNT_RYKN_KKN_JKN_CD IS '出動その他料金課金条件コード'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_SONOTA_RYOKIN_AMT IS '出動その他料金金額'
/
COMMENT ON COLUMN ED2540W_TBL.SHUTSUDO_JISSEKI_AMT IS '出動実績金額'
/
COMMENT ON COLUMN ED2540W_TBL.SHTSD_RNJ_JCH_KIYK_NO IS '出動臨時受注契約番号'
/
COMMENT ON COLUMN ED2540W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2540W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2540W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2540W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2540W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2540W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2540W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2540W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2540W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2540W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2540W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2540W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
