/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2537W_TBL.sql
-- 物理名：ED2537W_TBL
-- 論理名：ＡＥＤ機器情報一括取込用ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2537W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2537W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,AED_KIKI_JOHO_IKKT_TRKMY_SN  NUMBER(14,0) DEFAULT '0' NOT NULL --「ＡＥＤ機器情報一括取込用連番」
	,AED_BATCH_TOROKU_KBN  CHAR(1) NOT NULL --「ＡＥＤバッチ登録区分」
	,AED_KANRI_NO  CHAR(8) NOT NULL --「ＡＥＤ管理番号」
	,AED_KIKI_NO  NUMBER(2,0) DEFAULT '0' NOT NULL --「ＡＥＤ機器番号」
	,AED_KOKAN_SN  CHAR(14) NOT NULL --「ＡＥＤ交換連番」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,AED_SEIHIN_BUNRUI_KBN  CHAR(1) NOT NULL --「ＡＥＤ製品分類区分」
	,AED_SERIAL_NO  VARCHAR2(20) --「ＡＥＤシリアル番号」
	,AED_LOT_NO  VARCHAR2(15) --「ＡＥＤロット番号」
	,AED_KOKAN_YOTEI_YM  CHAR(6) --「ＡＥＤ交換予定年月」
	,AED_KOKAN_JIGYOSHO_CD  CHAR(6) --「ＡＥＤ交換事業所コード」
	,AED_KOKANSHA_SHAIN_NO  VARCHAR2(8) --「ＡＥＤ交換者社員番号」
	,AED_SHMHN_KKN_SHNCHK_JKY_KBN  CHAR(1) NOT NULL --「ＡＥＤ消耗品交換進捗状況区分」
	,AED_JIKAI_KOKAN_YOTEI_YM  CHAR(6) --「ＡＥＤ次回交換予定年月」
	,AED_JKI_TIK_KKN_DIKN_KBN  CHAR(1) NOT NULL --「ＡＥＤ次回定期交換代金区分」
	,AED_YUKO_KIGEN_YM  CHAR(6) --「ＡＥＤ有効期限年月」
	,AED_NYUKA_YMD  DATE --「ＡＥＤ入荷年月日」
	,AED_NYUKA_KAKUNINSHA_SHAIN_NO  VARCHAR2(8) --「ＡＥＤ入荷確認者社員番号」
	,AED_NYUKAJI_HINSHITSU_KBN  CHAR(1) NOT NULL --「ＡＥＤ入荷時品質区分」
	,AED_SHUKKA_YMD  DATE --「ＡＥＤ出荷年月日」
	,AED_SHUKKA_KAKUNINSHA_SHAIN_NO  VARCHAR2(8) --「ＡＥＤ出荷確認者社員番号」
	,AED_SHUKKAJI_HINSHITSU_KBN  CHAR(1) DEFAULT '1' NOT NULL --「ＡＥＤ出荷時品質区分」
	,AED_HAIKI_YMD  DATE --「ＡＥＤ廃棄年月日」
	,AED_HOKAN_JIGYOSHO_CD  CHAR(6) --「ＡＥＤ保管事業所コード」
	,AED_SAIRIYOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＥＤ再利用有フラグ」
	,AED_RNRK_STICKER_ZNTISHAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＥＤ連絡ステッカー全対象有フラグ」
	,AED_SMH_KKJK_HJ_LABEL_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＥＤ消耗品交換時期表示ラベル有フラグ」
	,AED_KIKI_JOHO_BIKO  VARCHAR2(30) --「ＡＥＤ機器情報備考」
	,AED_KANRI_STATUS_KBN  CHAR(1) NOT NULL --「ＡＥＤ管理ステータス区分」
	,AED_KANRI_SHURYO_YMD  DATE --「ＡＥＤ管理終了年月日」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,AED_CHTTS_IRI_JCH_KIYK_NO  CHAR(15) --「ＡＥＤ調達依頼受注契約番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2537W_PK PRIMARY KEY(
	 AED_KIKI_JOHO_IKKT_TRKMY_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2537W_TBL IS 'ＡＥＤ機器情報一括取込用ワーク'
/

COMMENT ON COLUMN ED2537W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2537W_TBL.AED_KIKI_JOHO_IKKT_TRKMY_SN IS 'ＡＥＤ機器情報一括取込用連番'
/
COMMENT ON COLUMN ED2537W_TBL.AED_BATCH_TOROKU_KBN IS 'ＡＥＤバッチ登録区分'
/
COMMENT ON COLUMN ED2537W_TBL.AED_KANRI_NO IS 'ＡＥＤ管理番号'
/
COMMENT ON COLUMN ED2537W_TBL.AED_KIKI_NO IS 'ＡＥＤ機器番号'
/
COMMENT ON COLUMN ED2537W_TBL.AED_KOKAN_SN IS 'ＡＥＤ交換連番'
/
COMMENT ON COLUMN ED2537W_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED2537W_TBL.AED_SEIHIN_BUNRUI_KBN IS 'ＡＥＤ製品分類区分'
/
COMMENT ON COLUMN ED2537W_TBL.AED_SERIAL_NO IS 'ＡＥＤシリアル番号'
/
COMMENT ON COLUMN ED2537W_TBL.AED_LOT_NO IS 'ＡＥＤロット番号'
/
COMMENT ON COLUMN ED2537W_TBL.AED_KOKAN_YOTEI_YM IS 'ＡＥＤ交換予定年月'
/
COMMENT ON COLUMN ED2537W_TBL.AED_KOKAN_JIGYOSHO_CD IS 'ＡＥＤ交換事業所コード'
/
COMMENT ON COLUMN ED2537W_TBL.AED_KOKANSHA_SHAIN_NO IS 'ＡＥＤ交換者社員番号'
/
COMMENT ON COLUMN ED2537W_TBL.AED_SHMHN_KKN_SHNCHK_JKY_KBN IS 'ＡＥＤ消耗品交換進捗状況区分'
/
COMMENT ON COLUMN ED2537W_TBL.AED_JIKAI_KOKAN_YOTEI_YM IS 'ＡＥＤ次回交換予定年月'
/
COMMENT ON COLUMN ED2537W_TBL.AED_JKI_TIK_KKN_DIKN_KBN IS 'ＡＥＤ次回定期交換代金区分'
/
COMMENT ON COLUMN ED2537W_TBL.AED_YUKO_KIGEN_YM IS 'ＡＥＤ有効期限年月'
/
COMMENT ON COLUMN ED2537W_TBL.AED_NYUKA_YMD IS 'ＡＥＤ入荷年月日'
/
COMMENT ON COLUMN ED2537W_TBL.AED_NYUKA_KAKUNINSHA_SHAIN_NO IS 'ＡＥＤ入荷確認者社員番号'
/
COMMENT ON COLUMN ED2537W_TBL.AED_NYUKAJI_HINSHITSU_KBN IS 'ＡＥＤ入荷時品質区分'
/
COMMENT ON COLUMN ED2537W_TBL.AED_SHUKKA_YMD IS 'ＡＥＤ出荷年月日'
/
COMMENT ON COLUMN ED2537W_TBL.AED_SHUKKA_KAKUNINSHA_SHAIN_NO IS 'ＡＥＤ出荷確認者社員番号'
/
COMMENT ON COLUMN ED2537W_TBL.AED_SHUKKAJI_HINSHITSU_KBN IS 'ＡＥＤ出荷時品質区分'
/
COMMENT ON COLUMN ED2537W_TBL.AED_HAIKI_YMD IS 'ＡＥＤ廃棄年月日'
/
COMMENT ON COLUMN ED2537W_TBL.AED_HOKAN_JIGYOSHO_CD IS 'ＡＥＤ保管事業所コード'
/
COMMENT ON COLUMN ED2537W_TBL.AED_SAIRIYOARI_FLG IS 'ＡＥＤ再利用有フラグ'
/
COMMENT ON COLUMN ED2537W_TBL.AED_RNRK_STICKER_ZNTISHAR_FLG IS 'ＡＥＤ連絡ステッカー全対象有フラグ'
/
COMMENT ON COLUMN ED2537W_TBL.AED_SMH_KKJK_HJ_LABEL_ARI_FLG IS 'ＡＥＤ消耗品交換時期表示ラベル有フラグ'
/
COMMENT ON COLUMN ED2537W_TBL.AED_KIKI_JOHO_BIKO IS 'ＡＥＤ機器情報備考'
/
COMMENT ON COLUMN ED2537W_TBL.AED_KANRI_STATUS_KBN IS 'ＡＥＤ管理ステータス区分'
/
COMMENT ON COLUMN ED2537W_TBL.AED_KANRI_SHURYO_YMD IS 'ＡＥＤ管理終了年月日'
/
COMMENT ON COLUMN ED2537W_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED2537W_TBL.AED_CHTTS_IRI_JCH_KIYK_NO IS 'ＡＥＤ調達依頼受注契約番号'
/
COMMENT ON COLUMN ED2537W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2537W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2537W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2537W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2537W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2537W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2537W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2537W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2537W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2537W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2537W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2537W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
