/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2501T_TBL.sql
-- 物理名：ED2501T_TBL
-- 論理名：仕掛案件一覧テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2501T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2501T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,KEIYAKU_KBN  CHAR(1) NOT NULL --「契約区分」
	,JUCHU_TANTO_SHAIN_NO  VARCHAR2(8) --「受注担当社員番号」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,JISSHI_JIGYOSHO_CD  CHAR(6) --「実施事業所コード」
	,GYM_ITKSK_TRHKSK_CD  CHAR(9) --「業務委託先取引先コード」
	,GYM_ITKSK_TRHKSK_BSH_CD  CHAR(4) --「業務委託先取引先部署コード」
	,TORIHIKISAKI_CD  CHAR(9) --「取引先コード」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,JUCHU_GROUP_NO  CHAR(9) --「受注グループ番号」
	,TO_CD  CHAR(8) --「棟コード」
	,SHOHIN_SERVICE_SHUBETSU_CD  CHAR(3) --「商品サービス種別コード」
	,SHOHIN_SERVICE_CD  CHAR(3) --「商品サービスコード」
	,KINKYU_SOKUJI_TSUHOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「緊急即時通報有フラグ」
	,SHOBOCHO_TODOKEDE_SHONIN_NO  VARCHAR2(15) --「消防庁届出承認番号」
	,SKAK_KIYK_SHNCHK_NAIYO_KBN  CHAR(5) NOT NULL --「仕掛案件契約進捗内容区分」
	,SKAK_KOJI_SHINCHOKU_NAIYO_KBN  CHAR(5) --「仕掛案件工事進捗内容区分」
	,SKAK_CHTTS_SHNCHK_NAIYO_KBN  CHAR(5) --「仕掛案件調達進捗内容区分」
	,SKAK_UNY_SHNCHK_NAIYO_KBN  CHAR(5) --「仕掛案件運用進捗内容区分」
	,SKAK_GM_ITK_UKSNCK_NAIYO_KBN  CHAR(1) --「仕掛案件業務委託請進捗内容区分」
	,SKAK_JIKAN_HNK_SHNSI_JKY_KBN  CHAR(5) --「仕掛案件時間変更申請状況区分」
	,SKAK_SIKY_JKN_SHNSI_JKY_KBN  CHAR(5) --「仕掛案件請求条件申請状況区分」
	,GYOMU_JISSHI_KAISHI_YMD  DATE --「業務実施開始年月日」
	,GYOMU_JISSHI_SHURYO_YMD  DATE --「業務実施終了年月日」
	,GYOMU_JISSHI_KAISHI_YOTEI_YMD  DATE --「業務実施開始予定年月日」
	,GYOMU_JISSHI_SHURYO_YOTEI_YMD  DATE --「業務実施終了予定年月日」
	,NYUKIN_YMD  DATE --「入金年月日」
	,DENKEI_NO  CHAR(9) --「電計番号」
	,KEIYAKUSHO_KAISHUZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「契約書回収済フラグ」
	,UNYO_MEMO_KOSHIN_SHAIN_NO  VARCHAR2(8) --「運用メモ更新社員番号」
	,UNYO_MEMO_NAIYO  VARCHAR2(150) --「運用メモ内容」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2501T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2501T_TBL IS '仕掛案件一覧テーブル'
/

COMMENT ON COLUMN ED2501T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED2501T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED2501T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED2501T_TBL.KEIYAKU_KBN IS '契約区分'
/
COMMENT ON COLUMN ED2501T_TBL.JUCHU_TANTO_SHAIN_NO IS '受注担当社員番号'
/
COMMENT ON COLUMN ED2501T_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED2501T_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED2501T_TBL.GYM_ITKSK_TRHKSK_CD IS '業務委託先取引先コード'
/
COMMENT ON COLUMN ED2501T_TBL.GYM_ITKSK_TRHKSK_BSH_CD IS '業務委託先取引先部署コード'
/
COMMENT ON COLUMN ED2501T_TBL.TORIHIKISAKI_CD IS '取引先コード'
/
COMMENT ON COLUMN ED2501T_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED2501T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED2501T_TBL.JUCHU_GROUP_NO IS '受注グループ番号'
/
COMMENT ON COLUMN ED2501T_TBL.TO_CD IS '棟コード'
/
COMMENT ON COLUMN ED2501T_TBL.SHOHIN_SERVICE_SHUBETSU_CD IS '商品サービス種別コード'
/
COMMENT ON COLUMN ED2501T_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED2501T_TBL.KINKYU_SOKUJI_TSUHOARI_FLG IS '緊急即時通報有フラグ'
/
COMMENT ON COLUMN ED2501T_TBL.SHOBOCHO_TODOKEDE_SHONIN_NO IS '消防庁届出承認番号'
/
COMMENT ON COLUMN ED2501T_TBL.SKAK_KIYK_SHNCHK_NAIYO_KBN IS '仕掛案件契約進捗内容区分'
/
COMMENT ON COLUMN ED2501T_TBL.SKAK_KOJI_SHINCHOKU_NAIYO_KBN IS '仕掛案件工事進捗内容区分'
/
COMMENT ON COLUMN ED2501T_TBL.SKAK_CHTTS_SHNCHK_NAIYO_KBN IS '仕掛案件調達進捗内容区分'
/
COMMENT ON COLUMN ED2501T_TBL.SKAK_UNY_SHNCHK_NAIYO_KBN IS '仕掛案件運用進捗内容区分'
/
COMMENT ON COLUMN ED2501T_TBL.SKAK_GM_ITK_UKSNCK_NAIYO_KBN IS '仕掛案件業務委託請進捗内容区分'
/
COMMENT ON COLUMN ED2501T_TBL.SKAK_JIKAN_HNK_SHNSI_JKY_KBN IS '仕掛案件時間変更申請状況区分'
/
COMMENT ON COLUMN ED2501T_TBL.SKAK_SIKY_JKN_SHNSI_JKY_KBN IS '仕掛案件請求条件申請状況区分'
/
COMMENT ON COLUMN ED2501T_TBL.GYOMU_JISSHI_KAISHI_YMD IS '業務実施開始年月日'
/
COMMENT ON COLUMN ED2501T_TBL.GYOMU_JISSHI_SHURYO_YMD IS '業務実施終了年月日'
/
COMMENT ON COLUMN ED2501T_TBL.GYOMU_JISSHI_KAISHI_YOTEI_YMD IS '業務実施開始予定年月日'
/
COMMENT ON COLUMN ED2501T_TBL.GYOMU_JISSHI_SHURYO_YOTEI_YMD IS '業務実施終了予定年月日'
/
COMMENT ON COLUMN ED2501T_TBL.NYUKIN_YMD IS '入金年月日'
/
COMMENT ON COLUMN ED2501T_TBL.DENKEI_NO IS '電計番号'
/
COMMENT ON COLUMN ED2501T_TBL.KEIYAKUSHO_KAISHUZUMI_FLG IS '契約書回収済フラグ'
/
COMMENT ON COLUMN ED2501T_TBL.UNYO_MEMO_KOSHIN_SHAIN_NO IS '運用メモ更新社員番号'
/
COMMENT ON COLUMN ED2501T_TBL.UNYO_MEMO_NAIYO IS '運用メモ内容'
/
COMMENT ON COLUMN ED2501T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2501T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2501T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2501T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2501T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2501T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2501T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2501T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2501T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2501T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2501T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2501T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
