/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2530W_TBL.sql
-- 物理名：ED2530W_TBL
-- 論理名：臨時回収実績ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2530W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2530W_TBL (
	 RK_KAISHA_CD  CHAR(5) NOT NULL --「ＲＫ＿会社コード」
	,RK_SN  NUMBER(14,0) DEFAULT '0' NOT NULL --「ＲＫ＿連番」
	,RK_UKETSUKE_DT  VARCHAR2(6) NOT NULL --「ＲＫ＿受付日時」
	,RK_UKETSUKE_JIKAN  CHAR(5) NOT NULL --「ＲＫ＿受付時間」
	,RK_NYUKINKI_NO  CHAR(6) NOT NULL --「ＲＫ＿入金機番号」
	,RK_KEIYAKUSAKIMEI  VARCHAR2(20) --「ＲＫ＿契約先名」
	,RK_TEMPOMEI  VARCHAR2(80) --「ＲＫ＿店舗名」
	,RK_KISHU  VARCHAR2(20) --「ＲＫ＿機種」
	,RK_TAIO_NAIYO  VARCHAR2(10) NOT NULL --「ＲＫ＿対応内容」
	,RK_JUCHU_JIGYOSHO  VARCHAR2(20) --「ＲＫ＿受注事業所」
	,RK_JISSHI_JIGYOSHO  VARCHAR2(20) --「ＲＫ＿実施事業所」
	,RK_KEIYAKUSAKI_TAIOSHAMEI  VARCHAR2(24) --「ＲＫ＿契約先対応者名」
	,RK_SEIKYU_CHOSEI  VARCHAR2(200) --「ＲＫ＿請求調整」
	,RK_TAIO_D  VARCHAR2(6) NOT NULL --「ＲＫ＿対応日」
	,RK_SEIKYU_JOKYO  VARCHAR2(1) --「ＲＫ＿請求状況」
	,RK_SEIKYU_D  VARCHAR2(6) --「ＲＫ＿請求日」
	,RK_SEIKYU_NO  CHAR(1) --「ＲＫ＿請求番号」
	,RK_TANTOSHA  VARCHAR2(1) --「ＲＫ＿担当者」
	,RK_TOKKI_JIKO  VARCHAR2(1) --「ＲＫ＿特記事項」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2530W_PK PRIMARY KEY(
	 RK_SN
	,  RK_KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2530W_TBL IS '臨時回収実績ワーク'
/

COMMENT ON COLUMN ED2530W_TBL.RK_KAISHA_CD IS 'ＲＫ＿会社コード'
/
COMMENT ON COLUMN ED2530W_TBL.RK_SN IS 'ＲＫ＿連番'
/
COMMENT ON COLUMN ED2530W_TBL.RK_UKETSUKE_DT IS 'ＲＫ＿受付日時'
/
COMMENT ON COLUMN ED2530W_TBL.RK_UKETSUKE_JIKAN IS 'ＲＫ＿受付時間'
/
COMMENT ON COLUMN ED2530W_TBL.RK_NYUKINKI_NO IS 'ＲＫ＿入金機番号'
/
COMMENT ON COLUMN ED2530W_TBL.RK_KEIYAKUSAKIMEI IS 'ＲＫ＿契約先名'
/
COMMENT ON COLUMN ED2530W_TBL.RK_TEMPOMEI IS 'ＲＫ＿店舗名'
/
COMMENT ON COLUMN ED2530W_TBL.RK_KISHU IS 'ＲＫ＿機種'
/
COMMENT ON COLUMN ED2530W_TBL.RK_TAIO_NAIYO IS 'ＲＫ＿対応内容'
/
COMMENT ON COLUMN ED2530W_TBL.RK_JUCHU_JIGYOSHO IS 'ＲＫ＿受注事業所'
/
COMMENT ON COLUMN ED2530W_TBL.RK_JISSHI_JIGYOSHO IS 'ＲＫ＿実施事業所'
/
COMMENT ON COLUMN ED2530W_TBL.RK_KEIYAKUSAKI_TAIOSHAMEI IS 'ＲＫ＿契約先対応者名'
/
COMMENT ON COLUMN ED2530W_TBL.RK_SEIKYU_CHOSEI IS 'ＲＫ＿請求調整'
/
COMMENT ON COLUMN ED2530W_TBL.RK_TAIO_D IS 'ＲＫ＿対応日'
/
COMMENT ON COLUMN ED2530W_TBL.RK_SEIKYU_JOKYO IS 'ＲＫ＿請求状況'
/
COMMENT ON COLUMN ED2530W_TBL.RK_SEIKYU_D IS 'ＲＫ＿請求日'
/
COMMENT ON COLUMN ED2530W_TBL.RK_SEIKYU_NO IS 'ＲＫ＿請求番号'
/
COMMENT ON COLUMN ED2530W_TBL.RK_TANTOSHA IS 'ＲＫ＿担当者'
/
COMMENT ON COLUMN ED2530W_TBL.RK_TOKKI_JIKO IS 'ＲＫ＿特記事項'
/
COMMENT ON COLUMN ED2530W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2530W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2530W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2530W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2530W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2530W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2530W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2530W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2530W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2530W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2530W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2530W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
