/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED2533W_TBL.sql
-- 物理名：ED2533W_TBL
-- 論理名：ＭＭＫ従量実績ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED2533W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED2533W_TBL (
	 MMK_KAISHA_CD  CHAR(5) NOT NULL --「ＭＭＫ＿会社コード」
	,MMK_SN  NUMBER(14,0) DEFAULT '0' NOT NULL --「ＭＭＫ＿連番」
	,MMK_JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「ＭＭＫ＿受注契約番号」
	,MMK_SEIKYU_AMT  NUMBER(12,0) DEFAULT '0' NOT NULL --「ＭＭＫ＿請求金額」
	,MMK_JISSHI_YMD  VARCHAR2(8) NOT NULL --「ＭＭＫ＿実施年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED2533W_PK PRIMARY KEY(
	 MMK_SN
	,  MMK_KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED2533W_TBL IS 'ＭＭＫ従量実績ワーク'
/

COMMENT ON COLUMN ED2533W_TBL.MMK_KAISHA_CD IS 'ＭＭＫ＿会社コード'
/
COMMENT ON COLUMN ED2533W_TBL.MMK_SN IS 'ＭＭＫ＿連番'
/
COMMENT ON COLUMN ED2533W_TBL.MMK_JUCHU_KEIYAKU_NO IS 'ＭＭＫ＿受注契約番号'
/
COMMENT ON COLUMN ED2533W_TBL.MMK_SEIKYU_AMT IS 'ＭＭＫ＿請求金額'
/
COMMENT ON COLUMN ED2533W_TBL.MMK_JISSHI_YMD IS 'ＭＭＫ＿実施年月日'
/
COMMENT ON COLUMN ED2533W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED2533W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED2533W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED2533W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED2533W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED2533W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED2533W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED2533W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED2533W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED2533W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED2533W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED2533W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
