/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3033T_TBL.sql
-- 物理名：ED3033T_TBL
-- 論理名：図面持出管理簿テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3033T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3033T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JOI_JIGYOSHO_CD  CHAR(6) NOT NULL --「上位事業所コード」
	,ZUMEN_MOCHIDASHI_HOKOKU_YM  CHAR(6) NOT NULL --「図面持出報告年月」
	,ZUMEN_MOCHIDASHI_ID  CHAR(14) NOT NULL --「図面持出ＩＤ」
	,ZUMEN_MOCHIDASHI_MEISAI_SN  NUMBER(14,0) DEFAULT '0' NOT NULL --「図面持出明細連番」
	,ZMN_KSHDSH_MHNKYK_TSCH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「図面貸出未返却通知フラグ」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,KIYKSK_TRHKSK_SISHK_NM  VARCHAR2(50) --「契約先取引先正式名称」
	,TAISHOSAKI_NM  VARCHAR2(40) --「対象先名称」
	,GENZU_KANRI_NO  CHAR(10) --「原図管理番号」
	,ZMN_MCDS_SNSIS_SZK_JGYSH_NM  VARCHAR2(200) --「図面持出申請者所属事業所名称」
	,ZMN_MCHDSH_SHNSISH_SHIN_NM  VARCHAR2(60) --「図面持出申請者社員氏名」
	,ZMN_MCHDSH_SHNNSH_SHIN_NM  VARCHAR2(60) --「図面持出承認者社員氏名」
	,ZMN_MCHDSH_YOTO_NAIYO  VARCHAR2(60) --「図面持出用途内容」
	,ZUMEN_MOCHIDASHI_KANRI_NO  CHAR(17) --「図面持出管理番号」
	,MOCHIDASHI_DT  TIMESTAMP --「持出日時」
	,ZUMEN_MOCHIDASHI_KBN  CHAR(1) NOT NULL --「図面持出区分」
	,ZUMEN_FUKUSHA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「図面複写フラグ」
	,ZUMEN_FAX_FLG  CHAR(1) DEFAULT '0' NOT NULL --「図面ＦＡＸフラグ」
	,ZUMEN_MAIL_FLG  CHAR(1) DEFAULT '0' NOT NULL --「図面メールフラグ」
	,ZUMEN_YUSO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「図面郵送フラグ」
	,ZUMEN_NAS_FLG  CHAR(1) DEFAULT '0' NOT NULL --「図面ＮＡＳフラグ」
	,ZUMEN_HENKYAKU_KIGEN_YMD  DATE --「図面返却期限年月日」
	,ZUMEN_INSATSU_BUSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「図面印刷部数」
	,ZUMEN_DL_DT  TIMESTAMP --「図面ＤＬ日時」
	,ZUMEN_HENKYAKU_ID  CHAR(14) --「図面返却ＩＤ」
	,HENKYAKU_DT  TIMESTAMP --「返却日時」
	,ZMN_INSTSBTS_HK_KKNN_TNTSH_NM  VARCHAR2(60) --「図面印刷物破棄確認担当者氏名」
	,ZUMEN_FILE_SAKUJO_KAKUNIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「図面ファイル削除確認フラグ」
	,ZMN_INSTSBTS_HK_KKNN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「図面印刷物破棄確認フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3033T_PK PRIMARY KEY(
	 JOI_JIGYOSHO_CD
	,  ZUMEN_MOCHIDASHI_HOKOKU_YM
	,  ZUMEN_MOCHIDASHI_ID
	,  ZUMEN_MOCHIDASHI_MEISAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3033T_TBL IS '図面持出管理簿テーブル'
/

COMMENT ON COLUMN ED3033T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3033T_TBL.JOI_JIGYOSHO_CD IS '上位事業所コード'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_MOCHIDASHI_HOKOKU_YM IS '図面持出報告年月'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_MOCHIDASHI_ID IS '図面持出ＩＤ'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_MOCHIDASHI_MEISAI_SN IS '図面持出明細連番'
/
COMMENT ON COLUMN ED3033T_TBL.ZMN_KSHDSH_MHNKYK_TSCH_FLG IS '図面貸出未返却通知フラグ'
/
COMMENT ON COLUMN ED3033T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED3033T_TBL.KIYKSK_TRHKSK_SISHK_NM IS '契約先取引先正式名称'
/
COMMENT ON COLUMN ED3033T_TBL.TAISHOSAKI_NM IS '対象先名称'
/
COMMENT ON COLUMN ED3033T_TBL.GENZU_KANRI_NO IS '原図管理番号'
/
COMMENT ON COLUMN ED3033T_TBL.ZMN_MCDS_SNSIS_SZK_JGYSH_NM IS '図面持出申請者所属事業所名称'
/
COMMENT ON COLUMN ED3033T_TBL.ZMN_MCHDSH_SHNSISH_SHIN_NM IS '図面持出申請者社員氏名'
/
COMMENT ON COLUMN ED3033T_TBL.ZMN_MCHDSH_SHNNSH_SHIN_NM IS '図面持出承認者社員氏名'
/
COMMENT ON COLUMN ED3033T_TBL.ZMN_MCHDSH_YOTO_NAIYO IS '図面持出用途内容'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_MOCHIDASHI_KANRI_NO IS '図面持出管理番号'
/
COMMENT ON COLUMN ED3033T_TBL.MOCHIDASHI_DT IS '持出日時'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_MOCHIDASHI_KBN IS '図面持出区分'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_FUKUSHA_FLG IS '図面複写フラグ'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_FAX_FLG IS '図面ＦＡＸフラグ'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_MAIL_FLG IS '図面メールフラグ'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_YUSO_FLG IS '図面郵送フラグ'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_NAS_FLG IS '図面ＮＡＳフラグ'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_HENKYAKU_KIGEN_YMD IS '図面返却期限年月日'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_INSATSU_BUSU IS '図面印刷部数'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_DL_DT IS '図面ＤＬ日時'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_HENKYAKU_ID IS '図面返却ＩＤ'
/
COMMENT ON COLUMN ED3033T_TBL.HENKYAKU_DT IS '返却日時'
/
COMMENT ON COLUMN ED3033T_TBL.ZMN_INSTSBTS_HK_KKNN_TNTSH_NM IS '図面印刷物破棄確認担当者氏名'
/
COMMENT ON COLUMN ED3033T_TBL.ZUMEN_FILE_SAKUJO_KAKUNIN_FLG IS '図面ファイル削除確認フラグ'
/
COMMENT ON COLUMN ED3033T_TBL.ZMN_INSTSBTS_HK_KKNN_FLG IS '図面印刷物破棄確認フラグ'
/
COMMENT ON COLUMN ED3033T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3033T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3033T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3033T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3033T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3033T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3033T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3033T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3033T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3033T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3033T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3033T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
