/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3022T_TBL.sql
-- 物理名：ED3022T_TBL
-- 論理名：原図登録テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3022T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3022T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,GENZU_KANRI_NO  CHAR(10) NOT NULL --「原図管理番号」
	,GENZU_RIREKI_NO  NUMBER(4,0) NOT NULL --「原図履歴番号」
	,GENZU_TOROKU_JOKYO_KBN  CHAR(1) NOT NULL --「原図登録状況区分」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,GNZ_TRK_SHNSI_JCH_KIYK_NO  CHAR(15) NOT NULL --「原図登録申請受注契約番号」
	,GENZU_TOROKU_BIKO  VARCHAR2(100) --「原図登録備考」
	,GENZU_TOROKU_KOSHIN_KBN  CHAR(1) NOT NULL --「原図登録更新区分」
	,GENZU_KEIBIKEI_RENKEI_KBN  CHAR(1) NOT NULL --「原図警備系連携区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3022T_PK PRIMARY KEY(
	 GENZU_KANRI_NO
	,  GENZU_RIREKI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3022T_TBL IS '原図登録テーブル'
/

COMMENT ON COLUMN ED3022T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3022T_TBL.GENZU_KANRI_NO IS '原図管理番号'
/
COMMENT ON COLUMN ED3022T_TBL.GENZU_RIREKI_NO IS '原図履歴番号'
/
COMMENT ON COLUMN ED3022T_TBL.GENZU_TOROKU_JOKYO_KBN IS '原図登録状況区分'
/
COMMENT ON COLUMN ED3022T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED3022T_TBL.GNZ_TRK_SHNSI_JCH_KIYK_NO IS '原図登録申請受注契約番号'
/
COMMENT ON COLUMN ED3022T_TBL.GENZU_TOROKU_BIKO IS '原図登録備考'
/
COMMENT ON COLUMN ED3022T_TBL.GENZU_TOROKU_KOSHIN_KBN IS '原図登録更新区分'
/
COMMENT ON COLUMN ED3022T_TBL.GENZU_KEIBIKEI_RENKEI_KBN IS '原図警備系連携区分'
/
COMMENT ON COLUMN ED3022T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3022T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3022T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3022T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3022T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3022T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3022T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3022T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3022T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3022T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3022T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3022T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
