/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3004T_TBL.sql
-- 物理名：ED3004T_TBL
-- 論理名：保全実務確認カードテーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3004T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3004T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,HOZEN_DEMPYO_NO  CHAR(15) NOT NULL --「保全伝票番号」
	,SHINGO_KAKUNIN_HOHO_KBN  CHAR(1) NOT NULL --「信号確認方法区分」
	,SONOTA_SHINGO_KAKUNIN_HOHO_NM  VARCHAR2(20) --「その他信号確認方法名称」
	,SOGO_TENKEN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「総合点検フラグ」
	,GAIKAN_KINO_TENKEN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「外観機能点検フラグ」
	,RINJI_HOZEN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「臨時保全フラグ」
	,IRAI_TENKEN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「依頼点検フラグ」
	,YUSHO_HOSHU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「有償保守フラグ」
	,SONOTA_TENKEN_SAGYO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「その他点検作業フラグ」
	,SONOTA_TENKEN_SAGYO_NM  VARCHAR2(20) --「その他点検作業名称」
	,HOZEN_SAGYO_TEGAKI_GAZO_KOMOKU  CLOB --「保全作業手描画像項目」
	,HOZEN_SAGYO_NAIYO  VARCHAR2(300) --「保全作業内容」
	,HOZEN_SHIZAI_SHORIHYO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全資材処理票フラグ」
	,HZN_SHZI_SHRHY_KKNN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全資材処理票確認フラグ」
	,HZN_SHZI_SHRHY_KKNNSH_SHIN_NO  VARCHAR2(8) --「保全資材処理票確認者社員番号」
	,HOZEN_MOSHIOKURI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全申送りフラグ」
	,HOZEN_MOSHIOKURI_HOHO_KBN  CHAR(1) NOT NULL --「保全申送り方法区分」
	,SNT_HZN_MSHOKR_HH_NM  VARCHAR2(20) --「その他保全申送り方法名称」
	,HOZEN_MOSHIOKURI_NAIYO  VARCHAR2(300) --「保全申送り内容」
	,HOZEN_MOSHIOKURISAKI_SHAIN_NO  VARCHAR2(8) --「保全申送り先社員番号」
	,HOZEN_MOSHIOKURI_YMD  DATE --「保全申送り年月日」
	,HOZEN_MOSHIOKURI_KAKUNIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全申送り確認フラグ」
	,HZN_MSHOKR_KKNNSH_SHIN_NO  VARCHAR2(8) --「保全申送り確認者社員番号」
	,HOZEN_TANRAKU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全短絡フラグ」
	,HOZEN_TANRAKU_RIYU  VARCHAR2(300) --「保全短絡理由」
	,HOZEN_TANRAKU_FUKKYU_YOTEI_YMD  DATE --「保全短絡復旧予定年月日」
	,HOZEN_TANRAKU_KAKUNIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全短絡確認フラグ」
	,HZN_TNRK_KKNNSH_SHIN_NO  VARCHAR2(8) --「保全短絡確認者社員番号」
	,HOZEN_KEIBI_KAGI_SHIYO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全警備鍵使用フラグ」
	,HOZEN_ZUMEN_MOCHIDASHI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全図面持出フラグ」
	,HOZEN_ZUMEN_SHOGO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全図面照合フラグ」
	,HOZEN_ZUMEN_TEISEI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全図面訂正フラグ」
	,HOZEN_ZUMEN_TEISEI_KANRYO_YMD  DATE --「保全図面訂正完了年月日」
	,HOZEN_ZUMEN_KAKUNIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全図面確認フラグ」
	,HZN_ZMN_KKNNSH_SHIN_NO  VARCHAR2(8) --「保全図面確認者社員番号」
	,SEISO_ATOSHIMATSU_JISSHI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「清掃後始末実施フラグ」
	,SHMI_BNDMBN_TIICH_KKNN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「照明分電盤定位置確認フラグ」
	,RESET_HYOJI_KAKUNIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「リセット表示確認フラグ」
	,KAGI_ZUMEN_SHOJI_KAKUNIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「鍵図面所持確認フラグ」
	,KEIKOHIN_SHOJI_KAKUNIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「携行品所持確認フラグ」
	,SEJO_KAKUNIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「施錠確認フラグ」
	,KEIBI_SET_JOTAI_KAKUNIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「警備セット状態確認フラグ」
	,KAIHEI_TACHIAITO_JISSHI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「開閉立会等実施フラグ」
	,SNT_TIKN_KKNN_KOMOKU_FLG_1  CHAR(1) DEFAULT '0' NOT NULL --「その他退館確認項目フラグ１」
	,SNT_TIKN_KKNN_KOMOKU_NM_1  VARCHAR2(20) --「その他退館確認項目名称１」
	,SNT_TIKN_KKNN_KOMOKU_FLG_2  CHAR(1) DEFAULT '0' NOT NULL --「その他退館確認項目フラグ２」
	,SNT_TIKN_KKNN_KOMOKU_NM_2  VARCHAR2(20) --「その他退館確認項目名称２」
	,HZN_KEKKA_NYRYK_KNRY_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全結果入力完了フラグ」
	,HZN_KEKKA_NYRYK_KNRY_SHIN_NO  VARCHAR2(8) --「保全結果入力完了社員番号」
	,HOZEN_KEKKA_SAISHU_KAKUNIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全結果最終確認フラグ」
	,HZN_KEKKA_SISH_KKNNSH_SHIN_NO  VARCHAR2(8) --「保全結果最終確認者社員番号」
	,HOZEN_KEKKA_SAISHU_KAKUNIN_YMD  DATE --「保全結果最終確認年月日」
	,HZN_INTERFACE_SOSHINZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保全インターフェース送信済フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3004T_PK PRIMARY KEY(
	 HOZEN_DEMPYO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3004T_TBL IS '保全実務確認カードテーブル'
/

COMMENT ON COLUMN ED3004T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_DEMPYO_NO IS '保全伝票番号'
/
COMMENT ON COLUMN ED3004T_TBL.SHINGO_KAKUNIN_HOHO_KBN IS '信号確認方法区分'
/
COMMENT ON COLUMN ED3004T_TBL.SONOTA_SHINGO_KAKUNIN_HOHO_NM IS 'その他信号確認方法名称'
/
COMMENT ON COLUMN ED3004T_TBL.SOGO_TENKEN_FLG IS '総合点検フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.GAIKAN_KINO_TENKEN_FLG IS '外観機能点検フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.RINJI_HOZEN_FLG IS '臨時保全フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.IRAI_TENKEN_FLG IS '依頼点検フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.YUSHO_HOSHU_FLG IS '有償保守フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.SONOTA_TENKEN_SAGYO_FLG IS 'その他点検作業フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.SONOTA_TENKEN_SAGYO_NM IS 'その他点検作業名称'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_SAGYO_TEGAKI_GAZO_KOMOKU IS '保全作業手描画像項目'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_SAGYO_NAIYO IS '保全作業内容'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_SHIZAI_SHORIHYO_FLG IS '保全資材処理票フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.HZN_SHZI_SHRHY_KKNN_FLG IS '保全資材処理票確認フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.HZN_SHZI_SHRHY_KKNNSH_SHIN_NO IS '保全資材処理票確認者社員番号'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_MOSHIOKURI_FLG IS '保全申送りフラグ'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_MOSHIOKURI_HOHO_KBN IS '保全申送り方法区分'
/
COMMENT ON COLUMN ED3004T_TBL.SNT_HZN_MSHOKR_HH_NM IS 'その他保全申送り方法名称'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_MOSHIOKURI_NAIYO IS '保全申送り内容'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_MOSHIOKURISAKI_SHAIN_NO IS '保全申送り先社員番号'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_MOSHIOKURI_YMD IS '保全申送り年月日'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_MOSHIOKURI_KAKUNIN_FLG IS '保全申送り確認フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.HZN_MSHOKR_KKNNSH_SHIN_NO IS '保全申送り確認者社員番号'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_TANRAKU_FLG IS '保全短絡フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_TANRAKU_RIYU IS '保全短絡理由'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_TANRAKU_FUKKYU_YOTEI_YMD IS '保全短絡復旧予定年月日'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_TANRAKU_KAKUNIN_FLG IS '保全短絡確認フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.HZN_TNRK_KKNNSH_SHIN_NO IS '保全短絡確認者社員番号'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_KEIBI_KAGI_SHIYO_FLG IS '保全警備鍵使用フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_ZUMEN_MOCHIDASHI_FLG IS '保全図面持出フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_ZUMEN_SHOGO_FLG IS '保全図面照合フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_ZUMEN_TEISEI_FLG IS '保全図面訂正フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_ZUMEN_TEISEI_KANRYO_YMD IS '保全図面訂正完了年月日'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_ZUMEN_KAKUNIN_FLG IS '保全図面確認フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.HZN_ZMN_KKNNSH_SHIN_NO IS '保全図面確認者社員番号'
/
COMMENT ON COLUMN ED3004T_TBL.SEISO_ATOSHIMATSU_JISSHI_FLG IS '清掃後始末実施フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.SHMI_BNDMBN_TIICH_KKNN_FLG IS '照明分電盤定位置確認フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.RESET_HYOJI_KAKUNIN_FLG IS 'リセット表示確認フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.KAGI_ZUMEN_SHOJI_KAKUNIN_FLG IS '鍵図面所持確認フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.KEIKOHIN_SHOJI_KAKUNIN_FLG IS '携行品所持確認フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.SEJO_KAKUNIN_FLG IS '施錠確認フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.KEIBI_SET_JOTAI_KAKUNIN_FLG IS '警備セット状態確認フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.KAIHEI_TACHIAITO_JISSHI_FLG IS '開閉立会等実施フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.SNT_TIKN_KKNN_KOMOKU_FLG_1 IS 'その他退館確認項目フラグ１'
/
COMMENT ON COLUMN ED3004T_TBL.SNT_TIKN_KKNN_KOMOKU_NM_1 IS 'その他退館確認項目名称１'
/
COMMENT ON COLUMN ED3004T_TBL.SNT_TIKN_KKNN_KOMOKU_FLG_2 IS 'その他退館確認項目フラグ２'
/
COMMENT ON COLUMN ED3004T_TBL.SNT_TIKN_KKNN_KOMOKU_NM_2 IS 'その他退館確認項目名称２'
/
COMMENT ON COLUMN ED3004T_TBL.HZN_KEKKA_NYRYK_KNRY_FLG IS '保全結果入力完了フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.HZN_KEKKA_NYRYK_KNRY_SHIN_NO IS '保全結果入力完了社員番号'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_KEKKA_SAISHU_KAKUNIN_FLG IS '保全結果最終確認フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.HZN_KEKKA_SISH_KKNNSH_SHIN_NO IS '保全結果最終確認者社員番号'
/
COMMENT ON COLUMN ED3004T_TBL.HOZEN_KEKKA_SAISHU_KAKUNIN_YMD IS '保全結果最終確認年月日'
/
COMMENT ON COLUMN ED3004T_TBL.HZN_INTERFACE_SOSHINZUMI_FLG IS '保全インターフェース送信済フラグ'
/
COMMENT ON COLUMN ED3004T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3004T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3004T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3004T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3004T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3004T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3004T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3004T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3004T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3004T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3004T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3004T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
