/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3043T_TBL.sql
-- 物理名：ED3043T_TBL
-- 論理名：消耗品交換テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3043T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3043T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TAISHOSAKI_CD  CHAR(9) NOT NULL --「対象先コード」
	,SHOMOHIN_KOKAN_SN  NUMBER(14,0) DEFAULT '0' NOT NULL --「消耗品交換連番」
	,SHOMOHIN_KOKANGYO_NO  NUMBER(4,0) DEFAULT '0' NOT NULL --「消耗品交換行番号」
	,HOZEN_DEMPYO_NO  CHAR(15) NOT NULL --「保全伝票番号」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,SHOMOHIN_KOKAN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「消耗品交換数量」
	,SHOMOHIN_KOKAN_YMD  DATE --「消耗品交換年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3043T_PK PRIMARY KEY(
	 TAISHOSAKI_CD
	,  SHOMOHIN_KOKAN_SN
	,  SHOMOHIN_KOKANGYO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3043T_TBL IS '消耗品交換テーブル'
/

COMMENT ON COLUMN ED3043T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3043T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED3043T_TBL.SHOMOHIN_KOKAN_SN IS '消耗品交換連番'
/
COMMENT ON COLUMN ED3043T_TBL.SHOMOHIN_KOKANGYO_NO IS '消耗品交換行番号'
/
COMMENT ON COLUMN ED3043T_TBL.HOZEN_DEMPYO_NO IS '保全伝票番号'
/
COMMENT ON COLUMN ED3043T_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED3043T_TBL.SHOMOHIN_KOKAN_SURYO IS '消耗品交換数量'
/
COMMENT ON COLUMN ED3043T_TBL.SHOMOHIN_KOKAN_YMD IS '消耗品交換年月日'
/
COMMENT ON COLUMN ED3043T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3043T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3043T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3043T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3043T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3043T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3043T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3043T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3043T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3043T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3043T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3043T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
