/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3029T_TBL.sql
-- 物理名：ED3029T_TBL
-- 論理名：回線管理報告明細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3029T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3029T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JOI_JIGYOSHO_CD  CHAR(6) NOT NULL --「上位事業所コード」
	,KAISEN_KANRI_HOKOKU_YM  CHAR(6) NOT NULL --「回線管理報告年月」
	,KAISEN_KANRI_NO  CHAR(10) NOT NULL --「回線管理番号」
	,KAISEN_SHOYU_KBN  CHAR(1) NOT NULL --「回線所有区分」
	,KAISEN_KAITSU_JOKYO_KBN  CHAR(1) NOT NULL --「回線開通状況区分」
	,EIGYO_TANTOSHA_SHAIN_NO  VARCHAR2(8) --「営業担当者社員番号」
	,EIGYO_TANTO_SHAIN_NM  VARCHAR2(60) --「営業担当社員氏名」
	,KAISEN_KAITSU_SHINSEI_YMD  DATE --「回線開通申請年月日」
	,KAISEN_KAITSU_YMD  DATE --「回線開通年月日」
	,KAISEN_KYUSHI_MOSHIKOMI_YMD  DATE --「回線休止申込年月日」
	,KAISEN_SAIKAI_MOSHIKOMI_YMD  DATE --「回線再開申込年月日」
	,KAISEN_KAIYAKU_MOSHIKOMI_YMD  DATE --「回線解約申込年月日」
	,KAISEN_MOSHIOKURI_NAIYO  VARCHAR2(300) --「回線申送り内容」
	,DENWA_NO  VARCHAR2(20) --「電話番号」
	,KAISEN_KEIYAKU_USER_NM  VARCHAR2(20) --「回線契約ユーザ名称」
	,KAISEN_GETSUGAKURYO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「回線月額料金額」
	,KAISEN_SHUBETSU_CD  CHAR(3) --「回線種別コード」
	,KAISEN_SHUBETSU_NM  VARCHAR2(60) --「回線種別名称」
	,KAISEN_KANRI_KOMOKU_1_NM  VARCHAR2(60) --「回線管理項目１名称」
	,KAISEN_KANRI_KOMOKU_2_NM  VARCHAR2(60) --「回線管理項目２名称」
	,KAISEN_KANRI_KOMOKU_3_NM  VARCHAR2(60) --「回線管理項目３名称」
	,KAISEN_KANRI_KOMOKU_4_NM  VARCHAR2(60) --「回線管理項目４名称」
	,KAISEN_KANRI_KOMOKU_5_NM  VARCHAR2(60) --「回線管理項目５名称」
	,KAISEN_KANRI_KOMOKU_6_NM  VARCHAR2(60) --「回線管理項目６名称」
	,KAISEN_KANRI_KOMOKU_7_NM  VARCHAR2(60) --「回線管理項目７名称」
	,KAISEN_KANRI_KOMOKU_8_NM  VARCHAR2(60) --「回線管理項目８名称」
	,KAISEN_KANRI_KOMOKU_9_NM  VARCHAR2(60) --「回線管理項目９名称」
	,KAISEN_KANRI_KOMOKU_10_NM  VARCHAR2(60) --「回線管理項目１０名称」
	,KAISEN_KANRI_KOMOKU_11_NM  VARCHAR2(60) --「回線管理項目１１名称」
	,KAISEN_KANRI_KOMOKU_12_NM  VARCHAR2(60) --「回線管理項目１２名称」
	,KAISEN_KANRI_KOMOKU_13_NM  VARCHAR2(60) --「回線管理項目１３名称」
	,KAISEN_KANRI_KOMOKU_14_NM  VARCHAR2(60) --「回線管理項目１４名称」
	,KAISEN_KANRI_KOMOKU_15_NM  VARCHAR2(60) --「回線管理項目１５名称」
	,KAISEN_KANRI_KOMOKU_16_NM  VARCHAR2(60) --「回線管理項目１６名称」
	,KAISEN_KANRI_KOMOKU_17_NM  VARCHAR2(60) --「回線管理項目１７名称」
	,KAISEN_KANRI_KOMOKU_18_NM  VARCHAR2(60) --「回線管理項目１８名称」
	,KAISEN_KANRI_KOMOKU_19_NM  VARCHAR2(60) --「回線管理項目１９名称」
	,KAISEN_KANRI_KOMOKU_20_NM  VARCHAR2(60) --「回線管理項目２０名称」
	,KAISEN_KANRI_KOMOKU_1_NAIYO  VARCHAR2(100) --「回線管理項目１内容」
	,KAISEN_KANRI_KOMOKU_2_NAIYO  VARCHAR2(100) --「回線管理項目２内容」
	,KAISEN_KANRI_KOMOKU_3_NAIYO  VARCHAR2(100) --「回線管理項目３内容」
	,KAISEN_KANRI_KOMOKU_4_NAIYO  VARCHAR2(100) --「回線管理項目４内容」
	,KAISEN_KANRI_KOMOKU_5_NAIYO  VARCHAR2(100) --「回線管理項目５内容」
	,KAISEN_KANRI_KOMOKU_6_NAIYO  VARCHAR2(100) --「回線管理項目６内容」
	,KAISEN_KANRI_KOMOKU_7_NAIYO  VARCHAR2(100) --「回線管理項目７内容」
	,KAISEN_KANRI_KOMOKU_8_NAIYO  VARCHAR2(100) --「回線管理項目８内容」
	,KAISEN_KANRI_KOMOKU_9_NAIYO  VARCHAR2(100) --「回線管理項目９内容」
	,KAISEN_KANRI_KOMOKU_10_NAIYO  VARCHAR2(100) --「回線管理項目１０内容」
	,KAISEN_KANRI_KOMOKU_11_NAIYO  VARCHAR2(100) --「回線管理項目１１内容」
	,KAISEN_KANRI_KOMOKU_12_NAIYO  VARCHAR2(100) --「回線管理項目１２内容」
	,KAISEN_KANRI_KOMOKU_13_NAIYO  VARCHAR2(100) --「回線管理項目１３内容」
	,KAISEN_KANRI_KOMOKU_14_NAIYO  VARCHAR2(100) --「回線管理項目１４内容」
	,KAISEN_KANRI_KOMOKU_15_NAIYO  VARCHAR2(100) --「回線管理項目１５内容」
	,KAISEN_KANRI_KOMOKU_16_NAIYO  VARCHAR2(100) --「回線管理項目１６内容」
	,KAISEN_KANRI_KOMOKU_17_NAIYO  VARCHAR2(100) --「回線管理項目１７内容」
	,KAISEN_KANRI_KOMOKU_18_NAIYO  VARCHAR2(100) --「回線管理項目１８内容」
	,KAISEN_KANRI_KOMOKU_19_NAIYO  VARCHAR2(100) --「回線管理項目１９内容」
	,KAISEN_KANRI_KOMOKU_20_NAIYO  VARCHAR2(100) --「回線管理項目２０内容」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3029T_PK PRIMARY KEY(
	 JOI_JIGYOSHO_CD
	,  KAISEN_KANRI_HOKOKU_YM
	,  KAISEN_KANRI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3029T_TBL IS '回線管理報告明細テーブル'
/

COMMENT ON COLUMN ED3029T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3029T_TBL.JOI_JIGYOSHO_CD IS '上位事業所コード'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_HOKOKU_YM IS '回線管理報告年月'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_NO IS '回線管理番号'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_SHOYU_KBN IS '回線所有区分'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KAITSU_JOKYO_KBN IS '回線開通状況区分'
/
COMMENT ON COLUMN ED3029T_TBL.EIGYO_TANTOSHA_SHAIN_NO IS '営業担当者社員番号'
/
COMMENT ON COLUMN ED3029T_TBL.EIGYO_TANTO_SHAIN_NM IS '営業担当社員氏名'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KAITSU_SHINSEI_YMD IS '回線開通申請年月日'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KAITSU_YMD IS '回線開通年月日'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KYUSHI_MOSHIKOMI_YMD IS '回線休止申込年月日'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_SAIKAI_MOSHIKOMI_YMD IS '回線再開申込年月日'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KAIYAKU_MOSHIKOMI_YMD IS '回線解約申込年月日'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_MOSHIOKURI_NAIYO IS '回線申送り内容'
/
COMMENT ON COLUMN ED3029T_TBL.DENWA_NO IS '電話番号'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KEIYAKU_USER_NM IS '回線契約ユーザ名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_GETSUGAKURYO_AMT IS '回線月額料金額'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_SHUBETSU_CD IS '回線種別コード'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_SHUBETSU_NM IS '回線種別名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_1_NM IS '回線管理項目１名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_2_NM IS '回線管理項目２名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_3_NM IS '回線管理項目３名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_4_NM IS '回線管理項目４名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_5_NM IS '回線管理項目５名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_6_NM IS '回線管理項目６名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_7_NM IS '回線管理項目７名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_8_NM IS '回線管理項目８名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_9_NM IS '回線管理項目９名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_10_NM IS '回線管理項目１０名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_11_NM IS '回線管理項目１１名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_12_NM IS '回線管理項目１２名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_13_NM IS '回線管理項目１３名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_14_NM IS '回線管理項目１４名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_15_NM IS '回線管理項目１５名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_16_NM IS '回線管理項目１６名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_17_NM IS '回線管理項目１７名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_18_NM IS '回線管理項目１８名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_19_NM IS '回線管理項目１９名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_20_NM IS '回線管理項目２０名称'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_1_NAIYO IS '回線管理項目１内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_2_NAIYO IS '回線管理項目２内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_3_NAIYO IS '回線管理項目３内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_4_NAIYO IS '回線管理項目４内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_5_NAIYO IS '回線管理項目５内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_6_NAIYO IS '回線管理項目６内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_7_NAIYO IS '回線管理項目７内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_8_NAIYO IS '回線管理項目８内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_9_NAIYO IS '回線管理項目９内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_10_NAIYO IS '回線管理項目１０内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_11_NAIYO IS '回線管理項目１１内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_12_NAIYO IS '回線管理項目１２内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_13_NAIYO IS '回線管理項目１３内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_14_NAIYO IS '回線管理項目１４内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_15_NAIYO IS '回線管理項目１５内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_16_NAIYO IS '回線管理項目１６内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_17_NAIYO IS '回線管理項目１７内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_18_NAIYO IS '回線管理項目１８内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_19_NAIYO IS '回線管理項目１９内容'
/
COMMENT ON COLUMN ED3029T_TBL.KAISEN_KANRI_KOMOKU_20_NAIYO IS '回線管理項目２０内容'
/
COMMENT ON COLUMN ED3029T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3029T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3029T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3029T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3029T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3029T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3029T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3029T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3029T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3029T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3029T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3029T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
