/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3040T_TBL.sql
-- 物理名：ED3040T_TBL
-- 論理名：定期保全年間計画明細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3040T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3040T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KI_NO  NUMBER(3,0) NOT NULL --「期番号」
	,JOI_JIGYOSHO_CD  CHAR(6) NOT NULL --「上位事業所コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,SEIGYO_SOCHI_HIMMEI_CD  CHAR(8) NOT NULL --「制御装置品名コード」
	,TIK_HZN_KIKK_MISI_SKSI_YMD  DATE --「定期保全計画明細作成年月日」
	,TEIKI_HOZEN_SEISA_NAIYO_CD  CHAR(2) --「定期保全精査内容コード」
	,TEIKI_HOZEN_SEISA_ERROR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「定期保全精査エラーフラグ」
	,TIK_HZN_SIS_MESSAGE_ID  CHAR(10) --「定期保全精査メッセージＩＤ」
	,TIK_HZN_SIS_MESSAGE_NAIYO  VARCHAR2(100) --「定期保全精査メッセージ内容」
	,SEIGYO_SOCHI_HIMMEI_NM  VARCHAR2(60) --「制御装置品名名称」
	,SIGY_SCH_TNKN_SHK_NENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「制御装置点検周期年数」
	,TIK_HZN_KIKK_MISI_BIKO  VARCHAR2(100) --「定期保全計画明細備考」
	,SOGO_TENKEN_SHUBETSU_KBN  CHAR(1) NOT NULL --「総合点検種別区分」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,JUCHU_JIGYOSHO_NM  VARCHAR2(200) --「受注事業所名称」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,KIYKSK_TRHKSK_SISHK_NM  VARCHAR2(50) --「契約先取引先正式名称」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,TAISHOSAKI_NM  VARCHAR2(40) --「対象先名称」
	,HOZEN_TAISHOSAKI_KETSUGO_JUSHO  VARCHAR2(200) --「保全対象先結合住所」
	,HZN_TISHSK_KTSG_TTMN_NM  VARCHAR2(300) --「保全対象先結合建物名称」
	,HOZEN_TAISHOSAKI_DENWA_NO  VARCHAR2(20) --「保全対象先電話番号」
	,HOZEN_AREA_CD  CHAR(3) --「保全エリアコード」
	,HZN_AREA_KIBTI_HICHSK_CD  VARCHAR2(6) --「保全エリア警備隊配置先コード」
	,KIKAI_KEIBITAI_NM  VARCHAR2(200) --「機械警備隊名称」
	,HZN_AREA_HZN_GJTSGKR_HICHSK_CD  VARCHAR2(6) --「保全エリア保全技術係配置先コード」
	,HOZEN_GIJUTSUGAKARI_NM  VARCHAR2(200) --「保全技術係名称」
	,GC_GOKI_NO  VARCHAR2(11) --「ＧＣ号機番号」
	,SHOHIN_SERVICE_CD  CHAR(3) --「商品サービスコード」
	,SHOHIN_SERVICE_NM  VARCHAR2(60) --「商品サービス名称」
	,TIK_HZN_KIKK_JCKY_NO_JFK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「定期保全計画明細受注番号重複フラグ」
	,KEIYAKU_STATUS_KBN  CHAR(1) NOT NULL --「契約ステータス区分」
	,GYOMU_KAISHI_YMD  DATE --「業務開始年月日」
	,TKHZ_KKTK_KOMOKU_1_NAIYO  VARCHAR2(100) --「定期保全計画追加項目１内容」
	,TKHZ_KKTK_KOMOKU_2_NAIYO  VARCHAR2(100) --「定期保全計画追加項目２内容」
	,TKHZ_KKTK_KOMOKU_3_NAIYO  VARCHAR2(100) --「定期保全計画追加項目３内容」
	,SAISHU_GAIKAN_KINO_TENKEN_YMD  DATE --「最終外観機能点検年月日」
	,SAISHU_SOGO_TENKEN_YMD  DATE --「最終総合点検年月日」
	,KEIYAKU_TENKEN_NENJI_NO  NUMBER(2,0) DEFAULT '0' NOT NULL --「契約点検年次番号」
	,SHINKI_TAISHOSAKI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「新規対象先フラグ」
	,DENKEI_NO  CHAR(9) --「電計番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3040T_PK PRIMARY KEY(
	 KI_NO
	,  JOI_JIGYOSHO_CD
	,  JUCHU_KEIYAKU_NO
	,  SEIGYO_SOCHI_HIMMEI_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3040T_TBL IS '定期保全年間計画明細テーブル'
/

COMMENT ON COLUMN ED3040T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3040T_TBL.KI_NO IS '期番号'
/
COMMENT ON COLUMN ED3040T_TBL.JOI_JIGYOSHO_CD IS '上位事業所コード'
/
COMMENT ON COLUMN ED3040T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED3040T_TBL.SEIGYO_SOCHI_HIMMEI_CD IS '制御装置品名コード'
/
COMMENT ON COLUMN ED3040T_TBL.TIK_HZN_KIKK_MISI_SKSI_YMD IS '定期保全計画明細作成年月日'
/
COMMENT ON COLUMN ED3040T_TBL.TEIKI_HOZEN_SEISA_NAIYO_CD IS '定期保全精査内容コード'
/
COMMENT ON COLUMN ED3040T_TBL.TEIKI_HOZEN_SEISA_ERROR_FLG IS '定期保全精査エラーフラグ'
/
COMMENT ON COLUMN ED3040T_TBL.TIK_HZN_SIS_MESSAGE_ID IS '定期保全精査メッセージＩＤ'
/
COMMENT ON COLUMN ED3040T_TBL.TIK_HZN_SIS_MESSAGE_NAIYO IS '定期保全精査メッセージ内容'
/
COMMENT ON COLUMN ED3040T_TBL.SEIGYO_SOCHI_HIMMEI_NM IS '制御装置品名名称'
/
COMMENT ON COLUMN ED3040T_TBL.SIGY_SCH_TNKN_SHK_NENSU IS '制御装置点検周期年数'
/
COMMENT ON COLUMN ED3040T_TBL.TIK_HZN_KIKK_MISI_BIKO IS '定期保全計画明細備考'
/
COMMENT ON COLUMN ED3040T_TBL.SOGO_TENKEN_SHUBETSU_KBN IS '総合点検種別区分'
/
COMMENT ON COLUMN ED3040T_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED3040T_TBL.JUCHU_JIGYOSHO_NM IS '受注事業所名称'
/
COMMENT ON COLUMN ED3040T_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED3040T_TBL.KIYKSK_TRHKSK_SISHK_NM IS '契約先取引先正式名称'
/
COMMENT ON COLUMN ED3040T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED3040T_TBL.TAISHOSAKI_NM IS '対象先名称'
/
COMMENT ON COLUMN ED3040T_TBL.HOZEN_TAISHOSAKI_KETSUGO_JUSHO IS '保全対象先結合住所'
/
COMMENT ON COLUMN ED3040T_TBL.HZN_TISHSK_KTSG_TTMN_NM IS '保全対象先結合建物名称'
/
COMMENT ON COLUMN ED3040T_TBL.HOZEN_TAISHOSAKI_DENWA_NO IS '保全対象先電話番号'
/
COMMENT ON COLUMN ED3040T_TBL.HOZEN_AREA_CD IS '保全エリアコード'
/
COMMENT ON COLUMN ED3040T_TBL.HZN_AREA_KIBTI_HICHSK_CD IS '保全エリア警備隊配置先コード'
/
COMMENT ON COLUMN ED3040T_TBL.KIKAI_KEIBITAI_NM IS '機械警備隊名称'
/
COMMENT ON COLUMN ED3040T_TBL.HZN_AREA_HZN_GJTSGKR_HICHSK_CD IS '保全エリア保全技術係配置先コード'
/
COMMENT ON COLUMN ED3040T_TBL.HOZEN_GIJUTSUGAKARI_NM IS '保全技術係名称'
/
COMMENT ON COLUMN ED3040T_TBL.GC_GOKI_NO IS 'ＧＣ号機番号'
/
COMMENT ON COLUMN ED3040T_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED3040T_TBL.SHOHIN_SERVICE_NM IS '商品サービス名称'
/
COMMENT ON COLUMN ED3040T_TBL.TIK_HZN_KIKK_JCKY_NO_JFK_FLG IS '定期保全計画明細受注番号重複フラグ'
/
COMMENT ON COLUMN ED3040T_TBL.KEIYAKU_STATUS_KBN IS '契約ステータス区分'
/
COMMENT ON COLUMN ED3040T_TBL.GYOMU_KAISHI_YMD IS '業務開始年月日'
/
COMMENT ON COLUMN ED3040T_TBL.TKHZ_KKTK_KOMOKU_1_NAIYO IS '定期保全計画追加項目１内容'
/
COMMENT ON COLUMN ED3040T_TBL.TKHZ_KKTK_KOMOKU_2_NAIYO IS '定期保全計画追加項目２内容'
/
COMMENT ON COLUMN ED3040T_TBL.TKHZ_KKTK_KOMOKU_3_NAIYO IS '定期保全計画追加項目３内容'
/
COMMENT ON COLUMN ED3040T_TBL.SAISHU_GAIKAN_KINO_TENKEN_YMD IS '最終外観機能点検年月日'
/
COMMENT ON COLUMN ED3040T_TBL.SAISHU_SOGO_TENKEN_YMD IS '最終総合点検年月日'
/
COMMENT ON COLUMN ED3040T_TBL.KEIYAKU_TENKEN_NENJI_NO IS '契約点検年次番号'
/
COMMENT ON COLUMN ED3040T_TBL.SHINKI_TAISHOSAKI_FLG IS '新規対象先フラグ'
/
COMMENT ON COLUMN ED3040T_TBL.DENKEI_NO IS '電計番号'
/
COMMENT ON COLUMN ED3040T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3040T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3040T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3040T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3040T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3040T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3040T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3040T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3040T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3040T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3040T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3040T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
