/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3045M_TBL.sql
-- 物理名：ED3045M_TBL
-- 論理名：定期保全精査内容マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3045M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3045M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TEIKI_HOZEN_SEISA_NAIYO_CD  CHAR(2) NOT NULL --「定期保全精査内容コード」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,TEIKI_HOZEN_SEISA_NAIYO_NM  VARCHAR2(60) --「定期保全精査内容名称」
	,HYOJI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順」
	,TEIKI_HOZEN_SEISA_KBN  CHAR(1) NOT NULL --「定期保全精査区分」
	,TENKEN_TAISHOGAI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「点検対象外フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3045M_PK PRIMARY KEY(
	 TEIKI_HOZEN_SEISA_NAIYO_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3045M_TBL IS '定期保全精査内容マスタ'
/

COMMENT ON COLUMN ED3045M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3045M_TBL.TEIKI_HOZEN_SEISA_NAIYO_CD IS '定期保全精査内容コード'
/
COMMENT ON COLUMN ED3045M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED3045M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED3045M_TBL.TEIKI_HOZEN_SEISA_NAIYO_NM IS '定期保全精査内容名称'
/
COMMENT ON COLUMN ED3045M_TBL.HYOJI_JUN IS '表示順'
/
COMMENT ON COLUMN ED3045M_TBL.TEIKI_HOZEN_SEISA_KBN IS '定期保全精査区分'
/
COMMENT ON COLUMN ED3045M_TBL.TENKEN_TAISHOGAI_FLG IS '点検対象外フラグ'
/
COMMENT ON COLUMN ED3045M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3045M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3045M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3045M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3045M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3045M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3045M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3045M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3045M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3045M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3045M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3045M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
