/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3063M_TBL.sql
-- 物理名：ED3063M_TBL
-- 論理名：作業予定表グループ枠マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3063M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3063M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SAGYO_YOTEIHYO_SOSHIKI_ID  CHAR(14) NOT NULL --「作業予定表組織ＩＤ」
	,SAGYO_YOTEIHYO_GROUP_WAKU_ID  CHAR(14) NOT NULL --「作業予定表グループ枠ＩＤ」
	,SAGYO_YOTEIHYO_GROUP_WAKU_NM  VARCHAR2(60) --「作業予定表グループ枠名称」
	,HYOJI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順」
	,GROUP_WAKU_TASK_BUNRUI_KBN  CHAR(1) NOT NULL --「グループ枠タスク分類区分」
	,SHIYO_FUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「使用不可フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3063M_PK PRIMARY KEY(
	 SAGYO_YOTEIHYO_SOSHIKI_ID
	,  SAGYO_YOTEIHYO_GROUP_WAKU_ID
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3063M_TBL IS '作業予定表グループ枠マスタ'
/

COMMENT ON COLUMN ED3063M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3063M_TBL.SAGYO_YOTEIHYO_SOSHIKI_ID IS '作業予定表組織ＩＤ'
/
COMMENT ON COLUMN ED3063M_TBL.SAGYO_YOTEIHYO_GROUP_WAKU_ID IS '作業予定表グループ枠ＩＤ'
/
COMMENT ON COLUMN ED3063M_TBL.SAGYO_YOTEIHYO_GROUP_WAKU_NM IS '作業予定表グループ枠名称'
/
COMMENT ON COLUMN ED3063M_TBL.HYOJI_JUN IS '表示順'
/
COMMENT ON COLUMN ED3063M_TBL.GROUP_WAKU_TASK_BUNRUI_KBN IS 'グループ枠タスク分類区分'
/
COMMENT ON COLUMN ED3063M_TBL.SHIYO_FUKA_FLG IS '使用不可フラグ'
/
COMMENT ON COLUMN ED3063M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3063M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3063M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3063M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3063M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3063M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3063M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3063M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3063M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3063M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3063M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3063M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
