/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3061M_TBL.sql
-- 物理名：ED3061M_TBL
-- 論理名：作業予定表タスク分類マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3061M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3061M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TASK_BUNRUI_ID  CHAR(14) NOT NULL --「タスク分類ＩＤ」
	,TASK_BUNRUI_NM  VARCHAR2(20) --「タスク分類名称」
	,TASK_BUNRUI_KBN  CHAR(1) NOT NULL --「タスク分類区分」
	,TASK_BUNRUI_COLOR_CD  CHAR(7) --「タスク分類カラーコード」
	,TASK_RIREKI_HYOJI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「タスク履歴表示フラグ」
	,HYOJI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順」
	,SHIYO_FUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「使用不可フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3061M_PK PRIMARY KEY(
	 TASK_BUNRUI_ID
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3061M_TBL IS '作業予定表タスク分類マスタ'
/

COMMENT ON COLUMN ED3061M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3061M_TBL.TASK_BUNRUI_ID IS 'タスク分類ＩＤ'
/
COMMENT ON COLUMN ED3061M_TBL.TASK_BUNRUI_NM IS 'タスク分類名称'
/
COMMENT ON COLUMN ED3061M_TBL.TASK_BUNRUI_KBN IS 'タスク分類区分'
/
COMMENT ON COLUMN ED3061M_TBL.TASK_BUNRUI_COLOR_CD IS 'タスク分類カラーコード'
/
COMMENT ON COLUMN ED3061M_TBL.TASK_RIREKI_HYOJI_FLG IS 'タスク履歴表示フラグ'
/
COMMENT ON COLUMN ED3061M_TBL.HYOJI_JUN IS '表示順'
/
COMMENT ON COLUMN ED3061M_TBL.SHIYO_FUKA_FLG IS '使用不可フラグ'
/
COMMENT ON COLUMN ED3061M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3061M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3061M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3061M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3061M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3061M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3061M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3061M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3061M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3061M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3061M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3061M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
