/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3070W_TBL.sql
-- 物理名：ED3070W_TBL
-- 論理名：運用実績情報警報装置管理ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3070W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3070W_TBL (
	 UNJ_JUCHU_KEIYAKU_NO  CHAR(9) --「ＵＮＪ＿受注契約番号」
	,UNJ_TENKEN_TAISHOGAI  CHAR(1) --「ＵＮＪ＿点検数対象外」
	,UNJ_HOZEN_JISSHIBI  CHAR(8) --「ＵＮＪ＿保全実施日」
	,UNJ_HOZEN_KAISHI_JIKAN  CHAR(4) --「ＵＮＪ＿保全開始時間」
	,UNJ_HOZEN_SHURYO_JIKAN  CHAR(4) --「ＵＮＪ＿保全終了時間」
	,UNJ_HOZEN_JISSHISHA_1  CHAR(8) --「ＵＮＪ＿保全実施者１」
	,UNJ_HOZEN_JISSHISHA_2  CHAR(8) --「ＵＮＪ＿保全実施者２」
	,UNJ_TENKEN_SHURUI_1  CHAR(1) --「ＵＮＪ＿点検種類１」
	,UNJ_TENKEN_SHURUI_2  CHAR(1) --「ＵＮＪ＿点検種類２」
	,UNJ_TENKEN_SHURUI_3  CHAR(1) --「ＵＮＪ＿点検種類３」
	,UNJ_TENKEN_NAIYO_1  CHAR(3) --「ＵＮＪ＿点検内容１」
	,UNJ_TENKEN_NAIYO_2  CHAR(3) --「ＵＮＪ＿点検内容２」
	,UNJ_TENKEN_NAIYO_3  CHAR(3) --「ＵＮＪ＿点検内容３」
	,UNJ_ZUMEN_TEISEI_UM  CHAR(1) --「ＵＮＪ＿図面訂正有無」
	,UNJ_JISSHI_NAIYO_1  VARCHAR2(60) --「ＵＮＪ＿実施内容１」
	,UNJ_JISSHI_NAIYO_2  VARCHAR2(60) --「ＵＮＪ＿実施内容２」
	,DATA_RENKEI_FILE_NM  VARCHAR2(255) --「データ連携ファイル名称」
	,KAISHA_CD  CHAR(5) --「会社コード」
	,SHORI_JOKYO_KBN  CHAR(1) NOT NULL --「処理状況区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3070W_TBL IS '運用実績情報警報装置管理ワーク'
/

COMMENT ON COLUMN ED3070W_TBL.UNJ_JUCHU_KEIYAKU_NO IS 'ＵＮＪ＿受注契約番号'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_TENKEN_TAISHOGAI IS 'ＵＮＪ＿点検数対象外'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_HOZEN_JISSHIBI IS 'ＵＮＪ＿保全実施日'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_HOZEN_KAISHI_JIKAN IS 'ＵＮＪ＿保全開始時間'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_HOZEN_SHURYO_JIKAN IS 'ＵＮＪ＿保全終了時間'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_HOZEN_JISSHISHA_1 IS 'ＵＮＪ＿保全実施者１'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_HOZEN_JISSHISHA_2 IS 'ＵＮＪ＿保全実施者２'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_TENKEN_SHURUI_1 IS 'ＵＮＪ＿点検種類１'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_TENKEN_SHURUI_2 IS 'ＵＮＪ＿点検種類２'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_TENKEN_SHURUI_3 IS 'ＵＮＪ＿点検種類３'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_TENKEN_NAIYO_1 IS 'ＵＮＪ＿点検内容１'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_TENKEN_NAIYO_2 IS 'ＵＮＪ＿点検内容２'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_TENKEN_NAIYO_3 IS 'ＵＮＪ＿点検内容３'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_ZUMEN_TEISEI_UM IS 'ＵＮＪ＿図面訂正有無'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_JISSHI_NAIYO_1 IS 'ＵＮＪ＿実施内容１'
/
COMMENT ON COLUMN ED3070W_TBL.UNJ_JISSHI_NAIYO_2 IS 'ＵＮＪ＿実施内容２'
/
COMMENT ON COLUMN ED3070W_TBL.DATA_RENKEI_FILE_NM IS 'データ連携ファイル名称'
/
COMMENT ON COLUMN ED3070W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3070W_TBL.SHORI_JOKYO_KBN IS '処理状況区分'
/
COMMENT ON COLUMN ED3070W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3070W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3070W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3070W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3070W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3070W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3070W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3070W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3070W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3070W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3070W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3070W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
