/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3003T_TBL.sql
-- 物理名：ED3003T_TBL
-- 論理名：保全作業報告書点検結果テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3003T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3003T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,HOZEN_DEMPYO_NO  CHAR(15) NOT NULL --「保全伝票番号」
	,SGY_HKKSH_TNKN_KOMOKU_ID  CHAR(4) NOT NULL --「作業報告書点検項目ＩＤ」
	,HYOJI_JUN  NUMBER(4,0) DEFAULT '0' --「表示順」
	,TENKEN_DAIKOMOKU_ID  CHAR(4) --「点検大項目ＩＤ」
	,TENKEN_CHUKOMOKU_ID  CHAR(4) --「点検中項目ＩＤ」
	,TENKEN_KOMOKU_BUNRUI_KBN  CHAR(1) NOT NULL --「点検項目分類区分」
	,SGY_HKKSH_TNKN_KOMOKU_NM  VARCHAR2(60) --「作業報告書点検項目名称」
	,TENKEN_CHUKOMOKU_KEKKA_KBN  CHAR(1) --「点検中項目結果区分」
	,TENKEN_SHOKOMOKU_SENTAKU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「点検小項目選択フラグ」
	,TNKN_KOMOKU_NM_NYRYK_KN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「点検項目名称入力可能フラグ」
	,SONOTA_TENKEN_KOMOKU_NM  VARCHAR2(60) --「その他点検項目名称」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3003T_PK PRIMARY KEY(
	 HOZEN_DEMPYO_NO
	,  SGY_HKKSH_TNKN_KOMOKU_ID
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3003T_TBL IS '保全作業報告書点検結果テーブル'
/

COMMENT ON COLUMN ED3003T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3003T_TBL.HOZEN_DEMPYO_NO IS '保全伝票番号'
/
COMMENT ON COLUMN ED3003T_TBL.SGY_HKKSH_TNKN_KOMOKU_ID IS '作業報告書点検項目ＩＤ'
/
COMMENT ON COLUMN ED3003T_TBL.HYOJI_JUN IS '表示順'
/
COMMENT ON COLUMN ED3003T_TBL.TENKEN_DAIKOMOKU_ID IS '点検大項目ＩＤ'
/
COMMENT ON COLUMN ED3003T_TBL.TENKEN_CHUKOMOKU_ID IS '点検中項目ＩＤ'
/
COMMENT ON COLUMN ED3003T_TBL.TENKEN_KOMOKU_BUNRUI_KBN IS '点検項目分類区分'
/
COMMENT ON COLUMN ED3003T_TBL.SGY_HKKSH_TNKN_KOMOKU_NM IS '作業報告書点検項目名称'
/
COMMENT ON COLUMN ED3003T_TBL.TENKEN_CHUKOMOKU_KEKKA_KBN IS '点検中項目結果区分'
/
COMMENT ON COLUMN ED3003T_TBL.TENKEN_SHOKOMOKU_SENTAKU_FLG IS '点検小項目選択フラグ'
/
COMMENT ON COLUMN ED3003T_TBL.TNKN_KOMOKU_NM_NYRYK_KN_FLG IS '点検項目名称入力可能フラグ'
/
COMMENT ON COLUMN ED3003T_TBL.SONOTA_TENKEN_KOMOKU_NM IS 'その他点検項目名称'
/
COMMENT ON COLUMN ED3003T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3003T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3003T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3003T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3003T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3003T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3003T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3003T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3003T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3003T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3003T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3003T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
