/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3015T_TBL.sql
-- 物理名：ED3015T_TBL
-- 論理名：保守点検契約実績テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3015T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3015T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KI_NO  NUMBER(3,0) NOT NULL --「期番号」
	,JOI_JIGYOSHO_CD  CHAR(6) NOT NULL --「上位事業所コード」
	,HOSHU_TENKEN_KEIYAKU_KANRI_NO  CHAR(10) NOT NULL --「保守点検契約管理番号」
	,HSH_TNKN_KIYK_JSSK_SN  NUMBER(14,0) DEFAULT '0' NOT NULL --「保守点検契約実績連番」
	,HSH_TNKN_KIYK_JSSH_YMD  DATE --「保守点検契約実施年月日」
	,HSH_TNKN_KIYK_TNKN_SHRI_KBN  CHAR(1) NOT NULL --「保守点検契約点検種類区分」
	,HSH_TNKN_KIYK_JSSH_TNTSH_NM  VARCHAR2(60) --「保守点検契約実施担当者氏名」
	,HOSHU_TENKEN_KEIYAKU_BIKO  VARCHAR2(300) --「保守点検契約備考」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3015T_PK PRIMARY KEY(
	 KI_NO
	,  JOI_JIGYOSHO_CD
	,  HOSHU_TENKEN_KEIYAKU_KANRI_NO
	,  HSH_TNKN_KIYK_JSSK_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3015T_TBL IS '保守点検契約実績テーブル'
/

COMMENT ON COLUMN ED3015T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3015T_TBL.KI_NO IS '期番号'
/
COMMENT ON COLUMN ED3015T_TBL.JOI_JIGYOSHO_CD IS '上位事業所コード'
/
COMMENT ON COLUMN ED3015T_TBL.HOSHU_TENKEN_KEIYAKU_KANRI_NO IS '保守点検契約管理番号'
/
COMMENT ON COLUMN ED3015T_TBL.HSH_TNKN_KIYK_JSSK_SN IS '保守点検契約実績連番'
/
COMMENT ON COLUMN ED3015T_TBL.HSH_TNKN_KIYK_JSSH_YMD IS '保守点検契約実施年月日'
/
COMMENT ON COLUMN ED3015T_TBL.HSH_TNKN_KIYK_TNKN_SHRI_KBN IS '保守点検契約点検種類区分'
/
COMMENT ON COLUMN ED3015T_TBL.HSH_TNKN_KIYK_JSSH_TNTSH_NM IS '保守点検契約実施担当者氏名'
/
COMMENT ON COLUMN ED3015T_TBL.HOSHU_TENKEN_KEIYAKU_BIKO IS '保守点検契約備考'
/
COMMENT ON COLUMN ED3015T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3015T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3015T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3015T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3015T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3015T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3015T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3015T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3015T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3015T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3015T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3015T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
