/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3016T_TBL.sql
-- 物理名：ED3016T_TBL
-- 論理名：原図テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3016T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3016T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,GENZU_KANRI_NO  CHAR(10) NOT NULL --「原図管理番号」
	,GENZU_KANRI_JOI_JIGYOSHO_CD  CHAR(6) NOT NULL --「原図管理上位事業所コード」
	,GENZU_NM  VARCHAR2(60) --「原図名称」
	,SAISHU_SHONIN_GENZU_RIREKI_NO  NUMBER(4,0) --「最終承認原図履歴番号」
	,SAISHIN_GENZU_RIREKI_NO  NUMBER(4,0) --「最新原図履歴番号」
	,GENZU_SHOKAI_SHONIN_YMD  DATE --「原図初回承認年月日」
	,GENZU_SAKUJO_YOTEI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「原図削除予定フラグ」
	,GENZU_SAKUJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「原図削除フラグ」
	,GENZU_IKO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「原図移行フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3016T_PK PRIMARY KEY(
	 GENZU_KANRI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3016T_TBL IS '原図テーブル'
/

COMMENT ON COLUMN ED3016T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3016T_TBL.GENZU_KANRI_NO IS '原図管理番号'
/
COMMENT ON COLUMN ED3016T_TBL.GENZU_KANRI_JOI_JIGYOSHO_CD IS '原図管理上位事業所コード'
/
COMMENT ON COLUMN ED3016T_TBL.GENZU_NM IS '原図名称'
/
COMMENT ON COLUMN ED3016T_TBL.SAISHU_SHONIN_GENZU_RIREKI_NO IS '最終承認原図履歴番号'
/
COMMENT ON COLUMN ED3016T_TBL.SAISHIN_GENZU_RIREKI_NO IS '最新原図履歴番号'
/
COMMENT ON COLUMN ED3016T_TBL.GENZU_SHOKAI_SHONIN_YMD IS '原図初回承認年月日'
/
COMMENT ON COLUMN ED3016T_TBL.GENZU_SAKUJO_YOTEI_FLG IS '原図削除予定フラグ'
/
COMMENT ON COLUMN ED3016T_TBL.GENZU_SAKUJO_FLG IS '原図削除フラグ'
/
COMMENT ON COLUMN ED3016T_TBL.GENZU_IKO_FLG IS '原図移行フラグ'
/
COMMENT ON COLUMN ED3016T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3016T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3016T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3016T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3016T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3016T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3016T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3016T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3016T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3016T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3016T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3016T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
