/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3031T_TBL.sql
-- 物理名：ED3031T_TBL
-- 論理名：図面持出報告テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3031T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3031T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JOI_JIGYOSHO_CD  CHAR(6) NOT NULL --「上位事業所コード」
	,ZUMEN_MOCHIDASHI_HOKOKU_YM  CHAR(6) NOT NULL --「図面持出報告年月」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,JIGYOSHO_NM  VARCHAR2(200) --「事業所名称」
	,KOJIN_JOHO_HOGO_KANRISHA_NM  VARCHAR2(60) --「個人情報保護管理者氏名」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3031T_PK PRIMARY KEY(
	 JOI_JIGYOSHO_CD
	,  ZUMEN_MOCHIDASHI_HOKOKU_YM
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3031T_TBL IS '図面持出報告テーブル'
/

COMMENT ON COLUMN ED3031T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3031T_TBL.JOI_JIGYOSHO_CD IS '上位事業所コード'
/
COMMENT ON COLUMN ED3031T_TBL.ZUMEN_MOCHIDASHI_HOKOKU_YM IS '図面持出報告年月'
/
COMMENT ON COLUMN ED3031T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED3031T_TBL.JIGYOSHO_NM IS '事業所名称'
/
COMMENT ON COLUMN ED3031T_TBL.KOJIN_JOHO_HOGO_KANRISHA_NM IS '個人情報保護管理者氏名'
/
COMMENT ON COLUMN ED3031T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3031T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3031T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3031T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3031T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3031T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3031T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3031T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3031T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3031T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3031T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3031T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
