/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3036T_TBL.sql
-- 物理名：ED3036T_TBL
-- 論理名：定期保全保守点検契約テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3036T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3036T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KI_NO  NUMBER(3,0) NOT NULL --「期番号」
	,JOI_JIGYOSHO_CD  CHAR(6) NOT NULL --「上位事業所コード」
	,HOSHU_TENKEN_KEIYAKU_KANRI_NO  CHAR(10) NOT NULL --「保守点検契約管理番号」
	,HSH_TNKN_KIYK_TSIK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「保守点検契約追加フラグ」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,SEIGYO_SOCHI_HIMMEI_CD  CHAR(8) --「制御装置品名コード」
	,SEIGYO_SOCHI_HIMMEI_NM  VARCHAR2(60) --「制御装置品名名称」
	,HSH_TNKN_KIYK_MISI_BIKO  VARCHAR2(60) --「保守点検契約明細備考」
	,SOGO_TENKEN_SHUBETSU_KBN  CHAR(1) NOT NULL --「総合点検種別区分」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,JUCHU_JIGYOSHO_NM  VARCHAR2(200) --「受注事業所名称」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,KIYKSK_TRHKSK_SISHK_NM  VARCHAR2(50) --「契約先取引先正式名称」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,TAISHOSAKI_NM  VARCHAR2(40) --「対象先名称」
	,HOZEN_TAISHOSAKI_KETSUGO_JUSHO  VARCHAR2(200) --「保全対象先結合住所」
	,HZN_TISHSK_KTSG_TTMN_NM  VARCHAR2(300) --「保全対象先結合建物名称」
	,HOZEN_TAISHOSAKI_DENWA_NO  VARCHAR2(20) --「保全対象先電話番号」
	,HOZEN_AREA_CD  CHAR(3) --「保全エリアコード」
	,HZN_AREA_KIBTI_HICHSK_CD  VARCHAR2(6) --「保全エリア警備隊配置先コード」
	,KIKAI_KEIBITAI_NM  VARCHAR2(200) --「機械警備隊名称」
	,HZN_AREA_HZN_GJTSGKR_HICHSK_CD  VARCHAR2(6) --「保全エリア保全技術係配置先コード」
	,HOZEN_GIJUTSUGAKARI_NM  VARCHAR2(200) --「保全技術係名称」
	,GC_GOKI_NO  VARCHAR2(11) --「ＧＣ号機番号」
	,SHOHIN_SERVICE_CD  CHAR(3) --「商品サービスコード」
	,SHOHIN_SERVICE_NM  VARCHAR2(60) --「商品サービス名称」
	,SAISHU_GAIKAN_KINO_TENKEN_YMD  DATE --「最終外観機能点検年月日」
	,SAISHU_SOGO_TENKEN_YMD  DATE --「最終総合点検年月日」
	,KEIYAKU_STATUS_KBN  CHAR(1) NOT NULL --「契約ステータス区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3036T_PK PRIMARY KEY(
	 KI_NO
	,  JOI_JIGYOSHO_CD
	,  HOSHU_TENKEN_KEIYAKU_KANRI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3036T_TBL IS '定期保全保守点検契約テーブル'
/

COMMENT ON COLUMN ED3036T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3036T_TBL.KI_NO IS '期番号'
/
COMMENT ON COLUMN ED3036T_TBL.JOI_JIGYOSHO_CD IS '上位事業所コード'
/
COMMENT ON COLUMN ED3036T_TBL.HOSHU_TENKEN_KEIYAKU_KANRI_NO IS '保守点検契約管理番号'
/
COMMENT ON COLUMN ED3036T_TBL.HSH_TNKN_KIYK_TSIK_FLG IS '保守点検契約追加フラグ'
/
COMMENT ON COLUMN ED3036T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED3036T_TBL.SEIGYO_SOCHI_HIMMEI_CD IS '制御装置品名コード'
/
COMMENT ON COLUMN ED3036T_TBL.SEIGYO_SOCHI_HIMMEI_NM IS '制御装置品名名称'
/
COMMENT ON COLUMN ED3036T_TBL.HSH_TNKN_KIYK_MISI_BIKO IS '保守点検契約明細備考'
/
COMMENT ON COLUMN ED3036T_TBL.SOGO_TENKEN_SHUBETSU_KBN IS '総合点検種別区分'
/
COMMENT ON COLUMN ED3036T_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED3036T_TBL.JUCHU_JIGYOSHO_NM IS '受注事業所名称'
/
COMMENT ON COLUMN ED3036T_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED3036T_TBL.KIYKSK_TRHKSK_SISHK_NM IS '契約先取引先正式名称'
/
COMMENT ON COLUMN ED3036T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED3036T_TBL.TAISHOSAKI_NM IS '対象先名称'
/
COMMENT ON COLUMN ED3036T_TBL.HOZEN_TAISHOSAKI_KETSUGO_JUSHO IS '保全対象先結合住所'
/
COMMENT ON COLUMN ED3036T_TBL.HZN_TISHSK_KTSG_TTMN_NM IS '保全対象先結合建物名称'
/
COMMENT ON COLUMN ED3036T_TBL.HOZEN_TAISHOSAKI_DENWA_NO IS '保全対象先電話番号'
/
COMMENT ON COLUMN ED3036T_TBL.HOZEN_AREA_CD IS '保全エリアコード'
/
COMMENT ON COLUMN ED3036T_TBL.HZN_AREA_KIBTI_HICHSK_CD IS '保全エリア警備隊配置先コード'
/
COMMENT ON COLUMN ED3036T_TBL.KIKAI_KEIBITAI_NM IS '機械警備隊名称'
/
COMMENT ON COLUMN ED3036T_TBL.HZN_AREA_HZN_GJTSGKR_HICHSK_CD IS '保全エリア保全技術係配置先コード'
/
COMMENT ON COLUMN ED3036T_TBL.HOZEN_GIJUTSUGAKARI_NM IS '保全技術係名称'
/
COMMENT ON COLUMN ED3036T_TBL.GC_GOKI_NO IS 'ＧＣ号機番号'
/
COMMENT ON COLUMN ED3036T_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED3036T_TBL.SHOHIN_SERVICE_NM IS '商品サービス名称'
/
COMMENT ON COLUMN ED3036T_TBL.SAISHU_GAIKAN_KINO_TENKEN_YMD IS '最終外観機能点検年月日'
/
COMMENT ON COLUMN ED3036T_TBL.SAISHU_SOGO_TENKEN_YMD IS '最終総合点検年月日'
/
COMMENT ON COLUMN ED3036T_TBL.KEIYAKU_STATUS_KBN IS '契約ステータス区分'
/
COMMENT ON COLUMN ED3036T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3036T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3036T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3036T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3036T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3036T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3036T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3036T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3036T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3036T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3036T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3036T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
