/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3035A_TBL.sql
-- 物理名：ED3035A_TBL
-- 論理名：図面閲覧ダウンロード履歴
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3035A_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3035A_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,ZUMEN_DL_RIREKI_ID  CHAR(14) NOT NULL --「図面ＤＬ履歴ＩＤ」
	,GENZU_KANRI_NO  CHAR(10) NOT NULL --「原図管理番号」
	,GENZU_RIREKI_NO  NUMBER(4,0) NOT NULL --「原図履歴番号」
	,GENZU_FILE_SN  NUMBER(14,0) NOT NULL --「原図ファイル連番」
	,GENZU_FILE_NM  VARCHAR2(255) --「原図ファイル名称」
	,ZUMEN_MOCHIDASHI_ID  CHAR(14) --「図面持出ＩＤ」
	,ZUMEN_MOCHIDASHI_MEISAI_SN  NUMBER(14,0) --「図面持出明細連番」
	,ZUMEN_MOCHIDASHI_KBN  CHAR(1) --「図面持出区分」
	,ZUMEN_DL_DT  TIMESTAMP --「図面ＤＬ日時」
	,ZUMEN_DL_GAMEN_ID  CHAR(15) --「図面ＤＬ画面ＩＤ」
	,ZUMEN_DL_TANTOSHA_SHAIN_NO  VARCHAR2(8) --「図面ＤＬ担当者社員番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3035A_PK PRIMARY KEY(
	 ZUMEN_DL_RIREKI_ID
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3035A_TBL IS '図面閲覧ダウンロード履歴'
/

COMMENT ON COLUMN ED3035A_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3035A_TBL.ZUMEN_DL_RIREKI_ID IS '図面ＤＬ履歴ＩＤ'
/
COMMENT ON COLUMN ED3035A_TBL.GENZU_KANRI_NO IS '原図管理番号'
/
COMMENT ON COLUMN ED3035A_TBL.GENZU_RIREKI_NO IS '原図履歴番号'
/
COMMENT ON COLUMN ED3035A_TBL.GENZU_FILE_SN IS '原図ファイル連番'
/
COMMENT ON COLUMN ED3035A_TBL.GENZU_FILE_NM IS '原図ファイル名称'
/
COMMENT ON COLUMN ED3035A_TBL.ZUMEN_MOCHIDASHI_ID IS '図面持出ＩＤ'
/
COMMENT ON COLUMN ED3035A_TBL.ZUMEN_MOCHIDASHI_MEISAI_SN IS '図面持出明細連番'
/
COMMENT ON COLUMN ED3035A_TBL.ZUMEN_MOCHIDASHI_KBN IS '図面持出区分'
/
COMMENT ON COLUMN ED3035A_TBL.ZUMEN_DL_DT IS '図面ＤＬ日時'
/
COMMENT ON COLUMN ED3035A_TBL.ZUMEN_DL_GAMEN_ID IS '図面ＤＬ画面ＩＤ'
/
COMMENT ON COLUMN ED3035A_TBL.ZUMEN_DL_TANTOSHA_SHAIN_NO IS '図面ＤＬ担当者社員番号'
/
COMMENT ON COLUMN ED3035A_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3035A_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3035A_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3035A_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3035A_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3035A_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3035A_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3035A_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3035A_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3035A_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3035A_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3035A_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
