/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3524W_TBL.sql
-- 物理名：ED3524W_TBL
-- 論理名：次回分請求書事業セグメント明細ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3524W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3524W_TBL (
	 SEIKYU_YOTEI_ID  CHAR(14) NOT NULL --「請求予定ＩＤ」
	,JIGYO_SEGMENT_CD  CHAR(3) NOT NULL --「事業セグメントコード」
	,KAISHA_CD  CHAR(5) --「会社コード」
	,SEIKYU_KANRI_MEISAI_NO  CHAR(14) --「請求管理明細番号」
	,ZEINUKI_SEIKYU_AMT  NUMBER(13,0) --「税抜請求金額」
	,SHOHIZEI_AMT  NUMBER(13,0) --「消費税金額」
	,ZEIKOMI_SEIKYU_AMT  NUMBER(13,0) --「税込請求金額」
	,FURIWAKE_NO  CHAR(2) --「振分番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3524W_PK PRIMARY KEY(
	 SEIKYU_YOTEI_ID
	,  JIGYO_SEGMENT_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3524W_TBL IS '次回分請求書事業セグメント明細ワーク'
/

COMMENT ON COLUMN ED3524W_TBL.SEIKYU_YOTEI_ID IS '請求予定ＩＤ'
/
COMMENT ON COLUMN ED3524W_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED3524W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3524W_TBL.SEIKYU_KANRI_MEISAI_NO IS '請求管理明細番号'
/
COMMENT ON COLUMN ED3524W_TBL.ZEINUKI_SEIKYU_AMT IS '税抜請求金額'
/
COMMENT ON COLUMN ED3524W_TBL.SHOHIZEI_AMT IS '消費税金額'
/
COMMENT ON COLUMN ED3524W_TBL.ZEIKOMI_SEIKYU_AMT IS '税込請求金額'
/
COMMENT ON COLUMN ED3524W_TBL.FURIWAKE_NO IS '振分番号'
/
COMMENT ON COLUMN ED3524W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3524W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3524W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3524W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3524W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3524W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3524W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3524W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3524W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3524W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3524W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3524W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
