/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3508T_TBL.sql
-- 物理名：ED3508T_TBL
-- 論理名：任意請求書テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3508T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3508T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,NINI_SEIKYUSHO_ID  CHAR(14) NOT NULL --「任意請求書ＩＤ」
	,NINI_SEIKYUSHO_STATUS_KBN  CHAR(1) NOT NULL --「任意請求書ステータス区分」
	,NINI_SEIKYUSHO_NM  VARCHAR2(80) --「任意請求書名称」
	,NINI_SEIKYUSHO_GAIYO_CMNT  VARCHAR2(100) --「任意請求書概要コメント」
	,SEIKYUSHO_HAKKO_IRAI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「請求書発行依頼フラグ」
	,SEIKYUSHO_HASSO_HOHO_KBN  CHAR(1) --「請求書発送方法区分」
	,SEIKYUSHO_HAKKO_HOHO_KBN  CHAR(1) --「請求書発行方法区分」
	,SEIKYUSHO_HAKKO_YOTEI_YMD  DATE --「請求書発行予定年月日」
	,SEIKYUSHO_SHOSHIKI_KBN  CHAR(1) NOT NULL --「請求書書式区分」
	,SEIKYUSHO_ATENA_NM_1  VARCHAR2(31) --「請求書宛名名称１」
	,SEIKYUSHO_ATENA_NM_2  VARCHAR2(31) --「請求書宛名名称２」
	,SEIKYUSHO_SOFUSAKI_YUBIN_NO  CHAR(7) --「請求書送付先郵便番号」
	,SEIKYUSHO_SOFUSAKI_JUSHO_1  VARCHAR2(30) --「請求書送付先住所１」
	,SEIKYUSHO_SOFUSAKI_JUSHO_2  VARCHAR2(30) --「請求書送付先住所２」
	,SEIKYUSHO_SOFUSAKI_JUSHO_3  VARCHAR2(30) --「請求書送付先住所３」
	,SEIKYUSHO_SOFUSAKI_KEISHO_KBN  CHAR(1) NOT NULL --「請求書送付先敬称区分」
	,SEIKYUSHO_INJI_OKYAKUSAMA_NO  VARCHAR2(20) --「請求書印字お客様番号」
	,SIKYSH_INJ_JSH_TRHKSK_SISHK_NM  VARCHAR2(50) --「請求書印字自社取引先正式名称」
	,SEIKYU_KANRI_JIGYOSHO_NM  VARCHAR2(200) --「請求管理事業所名称」
	,SEIKYU_KANRI_JIGYOSHO_YUBIN_NO  CHAR(7) --「請求管理事業所郵便番号」
	,SEIKYU_KANRI_JIGYOSHO_JUSHO_1  VARCHAR2(30) --「請求管理事業所住所１」
	,SEIKYU_KANRI_JIGYOSHO_JUSHO_2  VARCHAR2(30) --「請求管理事業所住所２」
	,SEIKYU_KANRI_JIGYOSHO_JUSHO_3  VARCHAR2(30) --「請求管理事業所住所３」
	,SEIKYU_KANRI_JIGYOSHO_JUSHO_4  VARCHAR2(30) --「請求管理事業所住所４」
	,SEIKYU_KANRI_JIGYOSHO_DENWA_NO  VARCHAR2(20) --「請求管理事業所電話番号」
	,SIKYSK_TRHKSKI_SISHK_NM_1  VARCHAR2(27) --「請求先取引先正式名称１」
	,SIKYSK_TRHKSKI_SISHK_NM_2  VARCHAR2(27) --「請求先取引先正式名称２」
	,SEIKYUSAKI_KEISHO_KBN  CHAR(1) NOT NULL --「請求先敬称区分」
	,KOKYAKU_SHIHARAI_HOHO_KBN  CHAR(2) NOT NULL --「顧客支払方法区分」
	,SHIHARAI_JISHA_KOZA_CD  CHAR(4) --「支払自社口座コード」
	,SHIHARAI_KIJITSU  DATE --「支払期日」
	,ZANDAKA_HYOJI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「残高表示フラグ」
	,ZENKAI_SEIKYU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「前回請求金額」
	,ZENKAI_NYUKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「前回入金金額」
	,SEIKYUSHO_SAKUSEI_YMD  DATE --「請求書作成年月日」
	,INJI_JIGYOSHO_NM  VARCHAR2(200) --「印字事業所名称」
	,INJI_JIGYOSHO_YUBIN_NO  CHAR(7) --「印字事業所郵便番号」
	,INJI_JIGYOSHO_JUSHO_1  VARCHAR2(30) --「印字事業所住所１」
	,INJI_JIGYOSHO_JUSHO_2  VARCHAR2(30) --「印字事業所住所２」
	,INJI_JIGYOSHO_SHISHACHO_NM  VARCHAR2(60) --「印字事業所支社長氏名」
	,SHOHIZEI_KEISAN_TANI_KBN  CHAR(1) NOT NULL --「消費税計算単位区分」
	,INEI_GAZO_ID  CHAR(5) --「印影画像ＩＤ」
	,HAGAKI_KOKOKU_GAZO_ID  CHAR(4) --「はがき広告画像ＩＤ」
	,FUSHO_KOKOKU_GAZO_ID  CHAR(4) --「封書広告画像ＩＤ」
	,KOKOKU_GAZO_KBN  CHAR(1) NOT NULL --「広告画像区分」
	,NINI_SEIKYUSHO_SEIKYUSHO_NO  CHAR(14) --「任意請求書請求書番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3508T_PK PRIMARY KEY(
	 NINI_SEIKYUSHO_ID
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3508T_TBL IS '任意請求書テーブル'
/

COMMENT ON COLUMN ED3508T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3508T_TBL.NINI_SEIKYUSHO_ID IS '任意請求書ＩＤ'
/
COMMENT ON COLUMN ED3508T_TBL.NINI_SEIKYUSHO_STATUS_KBN IS '任意請求書ステータス区分'
/
COMMENT ON COLUMN ED3508T_TBL.NINI_SEIKYUSHO_NM IS '任意請求書名称'
/
COMMENT ON COLUMN ED3508T_TBL.NINI_SEIKYUSHO_GAIYO_CMNT IS '任意請求書概要コメント'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSHO_HAKKO_IRAI_FLG IS '請求書発行依頼フラグ'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSHO_HASSO_HOHO_KBN IS '請求書発送方法区分'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSHO_HAKKO_HOHO_KBN IS '請求書発行方法区分'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSHO_HAKKO_YOTEI_YMD IS '請求書発行予定年月日'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSHO_SHOSHIKI_KBN IS '請求書書式区分'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSHO_ATENA_NM_1 IS '請求書宛名名称１'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSHO_ATENA_NM_2 IS '請求書宛名名称２'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSHO_SOFUSAKI_YUBIN_NO IS '請求書送付先郵便番号'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSHO_SOFUSAKI_JUSHO_1 IS '請求書送付先住所１'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSHO_SOFUSAKI_JUSHO_2 IS '請求書送付先住所２'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSHO_SOFUSAKI_JUSHO_3 IS '請求書送付先住所３'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSHO_SOFUSAKI_KEISHO_KBN IS '請求書送付先敬称区分'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSHO_INJI_OKYAKUSAMA_NO IS '請求書印字お客様番号'
/
COMMENT ON COLUMN ED3508T_TBL.SIKYSH_INJ_JSH_TRHKSK_SISHK_NM IS '請求書印字自社取引先正式名称'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYU_KANRI_JIGYOSHO_NM IS '請求管理事業所名称'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYU_KANRI_JIGYOSHO_YUBIN_NO IS '請求管理事業所郵便番号'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYU_KANRI_JIGYOSHO_JUSHO_1 IS '請求管理事業所住所１'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYU_KANRI_JIGYOSHO_JUSHO_2 IS '請求管理事業所住所２'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYU_KANRI_JIGYOSHO_JUSHO_3 IS '請求管理事業所住所３'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYU_KANRI_JIGYOSHO_JUSHO_4 IS '請求管理事業所住所４'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYU_KANRI_JIGYOSHO_DENWA_NO IS '請求管理事業所電話番号'
/
COMMENT ON COLUMN ED3508T_TBL.SIKYSK_TRHKSKI_SISHK_NM_1 IS '請求先取引先正式名称１'
/
COMMENT ON COLUMN ED3508T_TBL.SIKYSK_TRHKSKI_SISHK_NM_2 IS '請求先取引先正式名称２'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSAKI_KEISHO_KBN IS '請求先敬称区分'
/
COMMENT ON COLUMN ED3508T_TBL.KOKYAKU_SHIHARAI_HOHO_KBN IS '顧客支払方法区分'
/
COMMENT ON COLUMN ED3508T_TBL.SHIHARAI_JISHA_KOZA_CD IS '支払自社口座コード'
/
COMMENT ON COLUMN ED3508T_TBL.SHIHARAI_KIJITSU IS '支払期日'
/
COMMENT ON COLUMN ED3508T_TBL.ZANDAKA_HYOJI_FLG IS '残高表示フラグ'
/
COMMENT ON COLUMN ED3508T_TBL.ZENKAI_SEIKYU_AMT IS '前回請求金額'
/
COMMENT ON COLUMN ED3508T_TBL.ZENKAI_NYUKIN_AMT IS '前回入金金額'
/
COMMENT ON COLUMN ED3508T_TBL.SEIKYUSHO_SAKUSEI_YMD IS '請求書作成年月日'
/
COMMENT ON COLUMN ED3508T_TBL.INJI_JIGYOSHO_NM IS '印字事業所名称'
/
COMMENT ON COLUMN ED3508T_TBL.INJI_JIGYOSHO_YUBIN_NO IS '印字事業所郵便番号'
/
COMMENT ON COLUMN ED3508T_TBL.INJI_JIGYOSHO_JUSHO_1 IS '印字事業所住所１'
/
COMMENT ON COLUMN ED3508T_TBL.INJI_JIGYOSHO_JUSHO_2 IS '印字事業所住所２'
/
COMMENT ON COLUMN ED3508T_TBL.INJI_JIGYOSHO_SHISHACHO_NM IS '印字事業所支社長氏名'
/
COMMENT ON COLUMN ED3508T_TBL.SHOHIZEI_KEISAN_TANI_KBN IS '消費税計算単位区分'
/
COMMENT ON COLUMN ED3508T_TBL.INEI_GAZO_ID IS '印影画像ＩＤ'
/
COMMENT ON COLUMN ED3508T_TBL.HAGAKI_KOKOKU_GAZO_ID IS 'はがき広告画像ＩＤ'
/
COMMENT ON COLUMN ED3508T_TBL.FUSHO_KOKOKU_GAZO_ID IS '封書広告画像ＩＤ'
/
COMMENT ON COLUMN ED3508T_TBL.KOKOKU_GAZO_KBN IS '広告画像区分'
/
COMMENT ON COLUMN ED3508T_TBL.NINI_SEIKYUSHO_SEIKYUSHO_NO IS '任意請求書請求書番号'
/
COMMENT ON COLUMN ED3508T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3508T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3508T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3508T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3508T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3508T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3508T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3508T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3508T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3508T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3508T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3508T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
