/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3523W_TBL.sql
-- 物理名：ED3523W_TBL
-- 論理名：次回分請求管理明細ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3523W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3523W_TBL (
	 SEIKYU_YOTEI_ID  CHAR(14) NOT NULL --「請求予定ＩＤ」
	,KAISHA_CD  CHAR(5) --「会社コード」
	,SEIKYU_KANRI_MEISAI_NO  CHAR(14) --「請求管理明細番号」
	,ZNKI_BN_SIKY_KNR_MISI_NO  CHAR(14) --「前回分請求管理明細番号」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) --「請求先取引先コード」
	,SEIKYUSAKIBETSU_TEMPLATE_SN  CHAR(5) --「請求先別テンプレート連番」
	,SEIKYUSHO_HAKKO_YOTEI_YM  CHAR(6) --「請求書発行予定年月」
	,SEIKYUSHO_GROUP_NO  CHAR(3) --「請求書グループ番号」
	,SEIKYUSHO_HYOJI_JUN  NUMBER(7,0) --「請求書表示順」
	,KEIYAKU_CHOKI_RINJI_KBN  CHAR(1) --「契約長期臨時区分」
	,SEIKYU_SHIHARAI_CD  CHAR(3) --「請求支払コード」
	,CHK_KIYK_RYKN_KIZK_SIKY_KBN  CHAR(1) --「長期契約料金継続請求区分」
	,ZEINUKI_SEIKYU_AMT  NUMBER(13,0) --「税抜請求金額」
	,SHOHIZEI_KBN  CHAR(1) --「消費税区分」
	,SHOHI_ZEIRITSU_CD  CHAR(2) --「消費税率コード」
	,SHOHIZEI_AMT  NUMBER(13,0) --「消費税金額」
	,ZEIKOMI_SEIKYU_AMT  NUMBER(13,0) --「税込請求金額」
	,SEIKYUSHO_HYOJI_KAISHI_YMD  DATE --「請求書表示開始年月日」
	,SEIKYUSHO_HYOJI_SHURYO_YMD  DATE --「請求書表示終了年月日」
	,SIKYSH_TEKIYO_HYJ_KISHK_KBN  CHAR(1) --「請求書摘要表示形式区分」
	,SEIKYUSHO_MEISAI_TEKIYO  VARCHAR2(62) --「請求書明細摘要」
	,SEIKYUSHO_MEISAI_BIKO  VARCHAR2(54) --「請求書明細備考」
	,ZIRTSBTS_KISN_TISH_FLG  CHAR(1) --「税率別計算対象フラグ」
	,CHOSEIGO_SHOHIZEI_AMT  NUMBER(13,0) --「調整後消費税金額」
	,GASSANSAKI_SEIKYU_YOTEI_ID  CHAR(14) --「合算先請求予定ＩＤ」
	,GSSNSK_SIKY_KNR_MISI_NO  CHAR(14) --「合算先請求管理明細番号」
	,BUNKATSUMOTO_SEIKYU_YOTEI_ID  CHAR(14) --「分割元請求予定ＩＤ」
	,BNKTSMT_SIKY_KNR_MISI_NO  CHAR(14) --「分割元請求管理明細番号」
	,GASSANSAKI_FLG  CHAR(1) --「合算先フラグ」
	,BUNKATSUZUMI_FLG  CHAR(1) --「分割済フラグ」
	,GASSAN_MOTO_FLG  CHAR(1) --「合算元フラグ」
	,BUNKATSU_SAKI_FLG  CHAR(1) --「分割先フラグ」
	,BNKTS_SIKY_KNR_MISI_SN  CHAR(14) --「分割請求管理明細連番」
	,NYUKIN_YOTEI_YMD  DATE --「入金予定年月日」
	,TOSHO_NYUKIN_YOTEI_YMD  DATE --「当初入金予定年月日」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,JISSHI_JIGYOSHO_CD  CHAR(6) --「実施事業所コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「受注契約変更番号」
	,HENKOMOTO_JUCHU_KEIYAKU_NO  CHAR(6) --「変更元受注契約変更番号」
	,KANREN_JUCHU_KEIYAKU_NO  CHAR(15) --「関連受注契約番号」
	,JUCHU_SHORI_KBN  CHAR(2) --「受注処理区分」
	,RYOKIN_KBN  CHAR(5) --「料金区分」
	,KEIYAKU_RYOKIN_SEIKYUSAKI_KBN  CHAR(1) --「契約料金請求先区分」
	,KEIYAKU_RYOKIN_SN  CHAR(14) --「契約料金連番」
	,DAISANSHA_SHIHARAI_SN  CHAR(14) --「第三者支払連番」
	,SEIKYU_DAIKO_KANRI_NO  CHAR(13) --「請求代行管理番号」
	,SEIKYU_DAIKO_IRAISHO_NO  CHAR(10) --「請求代行依頼書番号」
	,SKYDK_IRSK_TRHSK_GRP_KIS_FLG  CHAR(1) --「請求代行依頼先取引先グループ会社フラグ」
	,SIKY_DIK_TSRY_KISN_HH_KBN  CHAR(1) --「請求代行手数料計算方法区分」
	,SEIKYU_DAIKO_TESURYO_RITSU  NUMBER(7,3) --「請求代行手数料率」
	,SEIKYU_DAIKO_TESURYO_AMT  NUMBER(13,0) --「請求代行手数料金額」
	,SIKY_DIK_TSRY_SHHRI_HH_KBN  CHAR(1) --「請求代行手数料支払方法区分」
	,TSH_SIKYSH_HKK_YTI_YMD  DATE --「当初請求書発行予定年月日」
	,TOSHO_SHOHI_ZEIRITSU_CD  CHAR(2) --「当初消費税率コード」
	,TSH_SIKYSK_TRHKSK_CD  CHAR(9) --「当初請求先取引先コード」
	,TSH_SIKYSKBTS_TEMPLATE_SN  CHAR(5) --「当初請求先別テンプレート連番」
	,TSH_SIKYSH_HKK_IRI_SHM_YMD  DATE --「当初請求書発行依頼締年月日」
	,SEIKYU_KANRI_STATUS_KBN  CHAR(2) --「請求管理ステータス区分」
	,TOSHO_SHOHIZEI_KBN  CHAR(1) --「当初消費税区分」
	,SEIKYU_KAISU_KBN  CHAR(1) --「請求回数区分」
	,BUNKATSU_SHIHARAI_SEIKYU_KAISU  NUMBER(9,0) --「分割支払請求回数」
	,SIKY_KKNBTS_SHKI_SKSI_MISI_FLG  CHAR(1) --「請求期間別初回作成明細フラグ」
	,JKIBN_SIKY_YTI_TRK_SHR_KBN  CHAR(1) --「次回分請求予定登録処理区分」
	,SEIKYU_AMT_SHURUI_KBN  CHAR(2) --「請求金額種類区分」
	,FURIWAKE_NO  CHAR(2) --「振分番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3523W_PK PRIMARY KEY(
	 SEIKYU_YOTEI_ID
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3523W_TBL IS '次回分請求管理明細ワーク'
/

COMMENT ON COLUMN ED3523W_TBL.SEIKYU_YOTEI_ID IS '請求予定ＩＤ'
/
COMMENT ON COLUMN ED3523W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYU_KANRI_MEISAI_NO IS '請求管理明細番号'
/
COMMENT ON COLUMN ED3523W_TBL.ZNKI_BN_SIKY_KNR_MISI_NO IS '前回分請求管理明細番号'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYUSAKIBETSU_TEMPLATE_SN IS '請求先別テンプレート連番'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYUSHO_HAKKO_YOTEI_YM IS '請求書発行予定年月'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYUSHO_GROUP_NO IS '請求書グループ番号'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYUSHO_HYOJI_JUN IS '請求書表示順'
/
COMMENT ON COLUMN ED3523W_TBL.KEIYAKU_CHOKI_RINJI_KBN IS '契約長期臨時区分'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYU_SHIHARAI_CD IS '請求支払コード'
/
COMMENT ON COLUMN ED3523W_TBL.CHK_KIYK_RYKN_KIZK_SIKY_KBN IS '長期契約料金継続請求区分'
/
COMMENT ON COLUMN ED3523W_TBL.ZEINUKI_SEIKYU_AMT IS '税抜請求金額'
/
COMMENT ON COLUMN ED3523W_TBL.SHOHIZEI_KBN IS '消費税区分'
/
COMMENT ON COLUMN ED3523W_TBL.SHOHI_ZEIRITSU_CD IS '消費税率コード'
/
COMMENT ON COLUMN ED3523W_TBL.SHOHIZEI_AMT IS '消費税金額'
/
COMMENT ON COLUMN ED3523W_TBL.ZEIKOMI_SEIKYU_AMT IS '税込請求金額'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYUSHO_HYOJI_KAISHI_YMD IS '請求書表示開始年月日'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYUSHO_HYOJI_SHURYO_YMD IS '請求書表示終了年月日'
/
COMMENT ON COLUMN ED3523W_TBL.SIKYSH_TEKIYO_HYJ_KISHK_KBN IS '請求書摘要表示形式区分'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYUSHO_MEISAI_TEKIYO IS '請求書明細摘要'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYUSHO_MEISAI_BIKO IS '請求書明細備考'
/
COMMENT ON COLUMN ED3523W_TBL.ZIRTSBTS_KISN_TISH_FLG IS '税率別計算対象フラグ'
/
COMMENT ON COLUMN ED3523W_TBL.CHOSEIGO_SHOHIZEI_AMT IS '調整後消費税金額'
/
COMMENT ON COLUMN ED3523W_TBL.GASSANSAKI_SEIKYU_YOTEI_ID IS '合算先請求予定ＩＤ'
/
COMMENT ON COLUMN ED3523W_TBL.GSSNSK_SIKY_KNR_MISI_NO IS '合算先請求管理明細番号'
/
COMMENT ON COLUMN ED3523W_TBL.BUNKATSUMOTO_SEIKYU_YOTEI_ID IS '分割元請求予定ＩＤ'
/
COMMENT ON COLUMN ED3523W_TBL.BNKTSMT_SIKY_KNR_MISI_NO IS '分割元請求管理明細番号'
/
COMMENT ON COLUMN ED3523W_TBL.GASSANSAKI_FLG IS '合算先フラグ'
/
COMMENT ON COLUMN ED3523W_TBL.BUNKATSUZUMI_FLG IS '分割済フラグ'
/
COMMENT ON COLUMN ED3523W_TBL.GASSAN_MOTO_FLG IS '合算元フラグ'
/
COMMENT ON COLUMN ED3523W_TBL.BUNKATSU_SAKI_FLG IS '分割先フラグ'
/
COMMENT ON COLUMN ED3523W_TBL.BNKTS_SIKY_KNR_MISI_SN IS '分割請求管理明細連番'
/
COMMENT ON COLUMN ED3523W_TBL.NYUKIN_YOTEI_YMD IS '入金予定年月日'
/
COMMENT ON COLUMN ED3523W_TBL.TOSHO_NYUKIN_YOTEI_YMD IS '当初入金予定年月日'
/
COMMENT ON COLUMN ED3523W_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED3523W_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED3523W_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED3523W_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED3523W_TBL.HENKOMOTO_JUCHU_KEIYAKU_NO IS '変更元受注契約変更番号'
/
COMMENT ON COLUMN ED3523W_TBL.KANREN_JUCHU_KEIYAKU_NO IS '関連受注契約番号'
/
COMMENT ON COLUMN ED3523W_TBL.JUCHU_SHORI_KBN IS '受注処理区分'
/
COMMENT ON COLUMN ED3523W_TBL.RYOKIN_KBN IS '料金区分'
/
COMMENT ON COLUMN ED3523W_TBL.KEIYAKU_RYOKIN_SEIKYUSAKI_KBN IS '契約料金請求先区分'
/
COMMENT ON COLUMN ED3523W_TBL.KEIYAKU_RYOKIN_SN IS '契約料金連番'
/
COMMENT ON COLUMN ED3523W_TBL.DAISANSHA_SHIHARAI_SN IS '第三者支払連番'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYU_DAIKO_KANRI_NO IS '請求代行管理番号'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYU_DAIKO_IRAISHO_NO IS '請求代行依頼書番号'
/
COMMENT ON COLUMN ED3523W_TBL.SKYDK_IRSK_TRHSK_GRP_KIS_FLG IS '請求代行依頼先取引先グループ会社フラグ'
/
COMMENT ON COLUMN ED3523W_TBL.SIKY_DIK_TSRY_KISN_HH_KBN IS '請求代行手数料計算方法区分'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYU_DAIKO_TESURYO_RITSU IS '請求代行手数料率'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYU_DAIKO_TESURYO_AMT IS '請求代行手数料金額'
/
COMMENT ON COLUMN ED3523W_TBL.SIKY_DIK_TSRY_SHHRI_HH_KBN IS '請求代行手数料支払方法区分'
/
COMMENT ON COLUMN ED3523W_TBL.TSH_SIKYSH_HKK_YTI_YMD IS '当初請求書発行予定年月日'
/
COMMENT ON COLUMN ED3523W_TBL.TOSHO_SHOHI_ZEIRITSU_CD IS '当初消費税率コード'
/
COMMENT ON COLUMN ED3523W_TBL.TSH_SIKYSK_TRHKSK_CD IS '当初請求先取引先コード'
/
COMMENT ON COLUMN ED3523W_TBL.TSH_SIKYSKBTS_TEMPLATE_SN IS '当初請求先別テンプレート連番'
/
COMMENT ON COLUMN ED3523W_TBL.TSH_SIKYSH_HKK_IRI_SHM_YMD IS '当初請求書発行依頼締年月日'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYU_KANRI_STATUS_KBN IS '請求管理ステータス区分'
/
COMMENT ON COLUMN ED3523W_TBL.TOSHO_SHOHIZEI_KBN IS '当初消費税区分'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYU_KAISU_KBN IS '請求回数区分'
/
COMMENT ON COLUMN ED3523W_TBL.BUNKATSU_SHIHARAI_SEIKYU_KAISU IS '分割支払請求回数'
/
COMMENT ON COLUMN ED3523W_TBL.SIKY_KKNBTS_SHKI_SKSI_MISI_FLG IS '請求期間別初回作成明細フラグ'
/
COMMENT ON COLUMN ED3523W_TBL.JKIBN_SIKY_YTI_TRK_SHR_KBN IS '次回分請求予定登録処理区分'
/
COMMENT ON COLUMN ED3523W_TBL.SEIKYU_AMT_SHURUI_KBN IS '請求金額種類区分'
/
COMMENT ON COLUMN ED3523W_TBL.FURIWAKE_NO IS '振分番号'
/
COMMENT ON COLUMN ED3523W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3523W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3523W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3523W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3523W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3523W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3523W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3523W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3523W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3523W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3523W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3523W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
