/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3510T_TBL.sql
-- 物理名：ED3510T_TBL
-- 論理名：営業外収益請求テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3510T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3510T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,EIGYOGAI_SHUEKI_SEIKYU_JOHO_NO  CHAR(14) NOT NULL --「営業外収益請求情報番号」
	,SEIKYUSHO_NO  CHAR(14) --「請求書番号」
	,EIGYOGAI_SEIKYUSHO_STATUS_KBN  CHAR(2) NOT NULL --「営業外請求書ステータス区分」
	,SEIKYUSHO_HASSO_HOHO_KBN  CHAR(1) NOT NULL --「請求書発送方法区分」
	,SEIKYUSHO_HAKKO_HOHO_KBN  CHAR(1) NOT NULL --「請求書発行方法区分」
	,SEIKYUSHO_HAKKO_YOTEI_YMD  DATE --「請求書発行予定年月日」
	,SHIHARAI_KIJITSU  DATE --「支払期日」
	,SEIKYU_KANRI_JIGYOSHO_CD  CHAR(6) --「請求管理事業所コード」
	,SIKY_KNR_JGYSH_TNTSH_SHIN_NO  VARCHAR2(8) --「請求管理事業所担当者社員番号」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) --「請求先取引先コード」
	,SEIKYUSAKI_TANTO_BUSHO_NM  VARCHAR2(40) --「請求先担当部署名称」
	,SEIKYUSAKI_TANTOSHA_NM  VARCHAR2(60) --「請求先担当者氏名」
	,SEIKYUSHO_HAKKO_JIGYOSHO_CD  CHAR(6) --「請求書発行事業所コード」
	,NYUKIN_JIGYOSHO_CD  CHAR(6) --「入金事業所コード」
	,KOKYAKU_SHIHARAI_HOHO_KBN  CHAR(2) NOT NULL --「顧客支払方法区分」
	,JISHA_KOZA_CD  CHAR(4) --「自社口座コード」
	,SEIKYUSHO_SOFUSAKI_KBN  CHAR(1) NOT NULL --「請求書送付先区分」
	,SOFUSAKI_TORIHIKISAKI_CD  CHAR(9) --「送付先取引先コード」
	,SOFUSAKI_TORIHIKISAKI_BUSHO_CD  CHAR(4) --「送付先取引先部署コード」
	,SOFUSAKI_TAISHOSAKI_CD  CHAR(9) --「送付先対象先コード」
	,SEIKYUSHO_ATENA_TSUIKI_JIKO  VARCHAR2(60) --「請求書宛名追記事項」
	,SEIKYUSHO_SOFUSAKI_KEISHO_KBN  CHAR(1) NOT NULL --「請求書送付先敬称区分」
	,SOFUSAKI_TANTO_BUSHO_NM  VARCHAR2(40) --「送付先担当部署名称」
	,SOFUSAKI_TANTOSHA_NM  VARCHAR2(60) --「送付先担当者氏名」
	,SEIKYUSHO_SHOSHIKI_KBN  CHAR(1) NOT NULL --「請求書書式区分」
	,HAGAKI_KOKOKU_GAZO_ID  CHAR(4) --「はがき広告画像ＩＤ」
	,FUSHO_KOKOKU_GAZO_ID  CHAR(4) --「封書広告画像ＩＤ」
	,SEIKYUSHO_SAKUSEI_YMD_INJI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「請求書作成年月日印字フラグ」
	,INEI_GAZO_ID  CHAR(5) --「印影画像ＩＤ」
	,SIKYSH_SHSHCHMI_INJ_KBN  CHAR(1) NOT NULL --「請求書支社長名印字区分」
	,INJI_JIGYOSHO_CD  CHAR(6) --「印字事業所コード」
	,INJ_JGYSH_SHSHCH_SHIN_NO  VARCHAR2(8) --「印字事業所支社長社員番号」
	,SEIKYUSHO_HAKKOJI_SHIJI_JIKO  VARCHAR2(60) --「請求書発行時指示事項」
	,KOKOKU_GAZO_KBN  CHAR(1) NOT NULL --「広告画像区分」
	,EGGSE_SKS_TMP_FILE_SHKBTS_KEY  VARCHAR2(255) --「営業外収益請求書添付ファイル識別キー」
	,EIGYGI_SHEK_SIKYSH_TMP_FILE_NM  VARCHAR2(60) --「営業外収益請求書添付ファイル名称」
	,ZEIKOMI_SEIKYU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「税込請求金額」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,SHINSEISHA_SHAIN_NO  VARCHAR2(8) --「申請者社員番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3510T_PK PRIMARY KEY(
	 EIGYOGAI_SHUEKI_SEIKYU_JOHO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3510T_TBL IS '営業外収益請求テーブル'
/

COMMENT ON COLUMN ED3510T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3510T_TBL.EIGYOGAI_SHUEKI_SEIKYU_JOHO_NO IS '営業外収益請求情報番号'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYUSHO_NO IS '請求書番号'
/
COMMENT ON COLUMN ED3510T_TBL.EIGYOGAI_SEIKYUSHO_STATUS_KBN IS '営業外請求書ステータス区分'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYUSHO_HASSO_HOHO_KBN IS '請求書発送方法区分'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYUSHO_HAKKO_HOHO_KBN IS '請求書発行方法区分'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYUSHO_HAKKO_YOTEI_YMD IS '請求書発行予定年月日'
/
COMMENT ON COLUMN ED3510T_TBL.SHIHARAI_KIJITSU IS '支払期日'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYU_KANRI_JIGYOSHO_CD IS '請求管理事業所コード'
/
COMMENT ON COLUMN ED3510T_TBL.SIKY_KNR_JGYSH_TNTSH_SHIN_NO IS '請求管理事業所担当者社員番号'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYUSAKI_TANTO_BUSHO_NM IS '請求先担当部署名称'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYUSAKI_TANTOSHA_NM IS '請求先担当者氏名'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYUSHO_HAKKO_JIGYOSHO_CD IS '請求書発行事業所コード'
/
COMMENT ON COLUMN ED3510T_TBL.NYUKIN_JIGYOSHO_CD IS '入金事業所コード'
/
COMMENT ON COLUMN ED3510T_TBL.KOKYAKU_SHIHARAI_HOHO_KBN IS '顧客支払方法区分'
/
COMMENT ON COLUMN ED3510T_TBL.JISHA_KOZA_CD IS '自社口座コード'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYUSHO_SOFUSAKI_KBN IS '請求書送付先区分'
/
COMMENT ON COLUMN ED3510T_TBL.SOFUSAKI_TORIHIKISAKI_CD IS '送付先取引先コード'
/
COMMENT ON COLUMN ED3510T_TBL.SOFUSAKI_TORIHIKISAKI_BUSHO_CD IS '送付先取引先部署コード'
/
COMMENT ON COLUMN ED3510T_TBL.SOFUSAKI_TAISHOSAKI_CD IS '送付先対象先コード'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYUSHO_ATENA_TSUIKI_JIKO IS '請求書宛名追記事項'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYUSHO_SOFUSAKI_KEISHO_KBN IS '請求書送付先敬称区分'
/
COMMENT ON COLUMN ED3510T_TBL.SOFUSAKI_TANTO_BUSHO_NM IS '送付先担当部署名称'
/
COMMENT ON COLUMN ED3510T_TBL.SOFUSAKI_TANTOSHA_NM IS '送付先担当者氏名'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYUSHO_SHOSHIKI_KBN IS '請求書書式区分'
/
COMMENT ON COLUMN ED3510T_TBL.HAGAKI_KOKOKU_GAZO_ID IS 'はがき広告画像ＩＤ'
/
COMMENT ON COLUMN ED3510T_TBL.FUSHO_KOKOKU_GAZO_ID IS '封書広告画像ＩＤ'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYUSHO_SAKUSEI_YMD_INJI_FLG IS '請求書作成年月日印字フラグ'
/
COMMENT ON COLUMN ED3510T_TBL.INEI_GAZO_ID IS '印影画像ＩＤ'
/
COMMENT ON COLUMN ED3510T_TBL.SIKYSH_SHSHCHMI_INJ_KBN IS '請求書支社長名印字区分'
/
COMMENT ON COLUMN ED3510T_TBL.INJI_JIGYOSHO_CD IS '印字事業所コード'
/
COMMENT ON COLUMN ED3510T_TBL.INJ_JGYSH_SHSHCH_SHIN_NO IS '印字事業所支社長社員番号'
/
COMMENT ON COLUMN ED3510T_TBL.SEIKYUSHO_HAKKOJI_SHIJI_JIKO IS '請求書発行時指示事項'
/
COMMENT ON COLUMN ED3510T_TBL.KOKOKU_GAZO_KBN IS '広告画像区分'
/
COMMENT ON COLUMN ED3510T_TBL.EGGSE_SKS_TMP_FILE_SHKBTS_KEY IS '営業外収益請求書添付ファイル識別キー'
/
COMMENT ON COLUMN ED3510T_TBL.EIGYGI_SHEK_SIKYSH_TMP_FILE_NM IS '営業外収益請求書添付ファイル名称'
/
COMMENT ON COLUMN ED3510T_TBL.ZEIKOMI_SEIKYU_AMT IS '税込請求金額'
/
COMMENT ON COLUMN ED3510T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED3510T_TBL.SHINSEISHA_SHAIN_NO IS '申請者社員番号'
/
COMMENT ON COLUMN ED3510T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3510T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3510T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3510T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3510T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3510T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3510T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3510T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3510T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3510T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3510T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3510T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
