/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3618T_TBL.sql
-- 物理名：ED3618T_TBL
-- 論理名：受取手形決済管理テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3618T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3618T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SHUKIN_NO  CHAR(14) NOT NULL --「集金番号」
	,UKETORI_TEGATA_KANRI_NO  NUMBER(9,0) DEFAULT '0' NOT NULL --「受取手形管理番号」
	,RINGI_KEMMEI  VARCHAR2(30) --「稟議件名」
	,RINGI_KIAN_NO  VARCHAR2(20) --「稟議起案番号」
	,TEGATA_JURYO_YMD  DATE NOT NULL --「手形受領年月日」
	,TEGATA_NO  CHAR(10) NOT NULL --「手形番号」
	,TEGATA_SHURUI_KBN  CHAR(1) NOT NULL --「手形種類区分」
	,TEGATA_FURIDASHININ_NM  VARCHAR2(30) NOT NULL --「手形振出人名称」
	,TEGATA_SHIHARAI_BASHO_NM  VARCHAR2(30) NOT NULL --「手形支払場所名称」
	,TEGATA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「手形金額」
	,TEGATA_FURIDASHI_YMD  DATE NOT NULL --「手形振出年月日」
	,TEGATA_SHIHARAI_YMD  DATE NOT NULL --「手形支払年月日」
	,TEGATA_URAGAKIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「手形裏書有フラグ」
	,TGT_URGK_RNZKSIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「手形裏書連続性有フラグ」
	,TGT_OMTMN_GZ_FILE_SHKBTS_KEY  VARCHAR2(255) --「手形表面画像ファイル識別キー」
	,TGT_URMN_GZ_FILE_SHKBTS_KEY  VARCHAR2(255) --「手形裏面画像ファイル識別キー」
	,TEGATA_HASSO_YMD  DATE --「手形発送年月日」
	,TEGATA_NYUKIN_SHORI_YMD  DATE --「手形入金処理年月日」
	,TEGATA_HONSHA_UKETSUKE_YMD  DATE --「手形本社受付年月日」
	,TGT_KNY_KKN_MCHKM_YMD  DATE --「手形金融機関持込年月日」
	,TEGATA_KESSAI_YMD  DATE --「手形決済年月日」
	,TEGATA_KESSAI_KEKKA_KBN  CHAR(1) DEFAULT '0' NOT NULL --「手形決済結果区分」
	,FUWATARI_RIYU_CMNT  VARCHAR2(30) --「不渡理由コメント」
	,NYUSHUKKIN_NO  NUMBER(14,0) --「入出金番号」
	,KANJO_KAMOKU_CD  VARCHAR2(12) --「勘定科目コード」
	,KANJO_KAMOKU_NM  VARCHAR2(64) --「勘定科目名称」
	,HOJO_KAMOKU_CD  VARCHAR2(12) --「補助科目コード」
	,HOJO_KAMOKU_NM  VARCHAR2(64) --「補助科目名称」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) --「請求先取引先コード」
	,DAIHYO_SEIKYUSHO_TEKIYO  VARCHAR2(62) --「代表請求書摘要」
	,SEIKYUSHO_BIKO  VARCHAR2(60) --「請求書備考」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3618T_PK PRIMARY KEY(
	 SHUKIN_NO
	,  UKETORI_TEGATA_KANRI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3618T_TBL IS '受取手形決済管理テーブル'
/

COMMENT ON COLUMN ED3618T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3618T_TBL.SHUKIN_NO IS '集金番号'
/
COMMENT ON COLUMN ED3618T_TBL.UKETORI_TEGATA_KANRI_NO IS '受取手形管理番号'
/
COMMENT ON COLUMN ED3618T_TBL.RINGI_KEMMEI IS '稟議件名'
/
COMMENT ON COLUMN ED3618T_TBL.RINGI_KIAN_NO IS '稟議起案番号'
/
COMMENT ON COLUMN ED3618T_TBL.TEGATA_JURYO_YMD IS '手形受領年月日'
/
COMMENT ON COLUMN ED3618T_TBL.TEGATA_NO IS '手形番号'
/
COMMENT ON COLUMN ED3618T_TBL.TEGATA_SHURUI_KBN IS '手形種類区分'
/
COMMENT ON COLUMN ED3618T_TBL.TEGATA_FURIDASHININ_NM IS '手形振出人名称'
/
COMMENT ON COLUMN ED3618T_TBL.TEGATA_SHIHARAI_BASHO_NM IS '手形支払場所名称'
/
COMMENT ON COLUMN ED3618T_TBL.TEGATA_AMT IS '手形金額'
/
COMMENT ON COLUMN ED3618T_TBL.TEGATA_FURIDASHI_YMD IS '手形振出年月日'
/
COMMENT ON COLUMN ED3618T_TBL.TEGATA_SHIHARAI_YMD IS '手形支払年月日'
/
COMMENT ON COLUMN ED3618T_TBL.TEGATA_URAGAKIARI_FLG IS '手形裏書有フラグ'
/
COMMENT ON COLUMN ED3618T_TBL.TGT_URGK_RNZKSIAR_FLG IS '手形裏書連続性有フラグ'
/
COMMENT ON COLUMN ED3618T_TBL.TGT_OMTMN_GZ_FILE_SHKBTS_KEY IS '手形表面画像ファイル識別キー'
/
COMMENT ON COLUMN ED3618T_TBL.TGT_URMN_GZ_FILE_SHKBTS_KEY IS '手形裏面画像ファイル識別キー'
/
COMMENT ON COLUMN ED3618T_TBL.TEGATA_HASSO_YMD IS '手形発送年月日'
/
COMMENT ON COLUMN ED3618T_TBL.TEGATA_NYUKIN_SHORI_YMD IS '手形入金処理年月日'
/
COMMENT ON COLUMN ED3618T_TBL.TEGATA_HONSHA_UKETSUKE_YMD IS '手形本社受付年月日'
/
COMMENT ON COLUMN ED3618T_TBL.TGT_KNY_KKN_MCHKM_YMD IS '手形金融機関持込年月日'
/
COMMENT ON COLUMN ED3618T_TBL.TEGATA_KESSAI_YMD IS '手形決済年月日'
/
COMMENT ON COLUMN ED3618T_TBL.TEGATA_KESSAI_KEKKA_KBN IS '手形決済結果区分'
/
COMMENT ON COLUMN ED3618T_TBL.FUWATARI_RIYU_CMNT IS '不渡理由コメント'
/
COMMENT ON COLUMN ED3618T_TBL.NYUSHUKKIN_NO IS '入出金番号'
/
COMMENT ON COLUMN ED3618T_TBL.KANJO_KAMOKU_CD IS '勘定科目コード'
/
COMMENT ON COLUMN ED3618T_TBL.KANJO_KAMOKU_NM IS '勘定科目名称'
/
COMMENT ON COLUMN ED3618T_TBL.HOJO_KAMOKU_CD IS '補助科目コード'
/
COMMENT ON COLUMN ED3618T_TBL.HOJO_KAMOKU_NM IS '補助科目名称'
/
COMMENT ON COLUMN ED3618T_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED3618T_TBL.DAIHYO_SEIKYUSHO_TEKIYO IS '代表請求書摘要'
/
COMMENT ON COLUMN ED3618T_TBL.SEIKYUSHO_BIKO IS '請求書備考'
/
COMMENT ON COLUMN ED3618T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3618T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3618T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3618T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3618T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3618T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3618T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3618T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3618T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3618T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3618T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3618T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
