/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3601T_TBL.sql
-- 物理名：ED3601T_TBL
-- 論理名：入出金テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3601T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3601T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,NYUSHUKKIN_NO  NUMBER(14,0) NOT NULL --「入出金番号」
	,NYUSHUKKIN_KBN  CHAR(1) NOT NULL --「入出金区分」
	,NYUSHUKKIN_YMD  DATE --「入出金年月日」
	,NYUSHUKKIN_HOHO_KBN  CHAR(2) NOT NULL --「入出金方法区分」
	,NYUSHUKKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「入出金金額」
	,NYUSHUKKIN_SHORI_YMD  DATE --「入出金処理年月日」
	,MISHORI_NYUSHUKKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「未処理入出金金額」
	,SHIMUKE_KINYU_KIKAN_KN_NM  VARCHAR2(30) --「仕向金融機関カナ名称」
	,SHMK_KNY_KKN_SHTN_KN_NM  VARCHAR2(30) --「仕向金融機関支店カナ名称」
	,FURIKOMI_IRAININ_KN_NM  VARCHAR2(60) --「振込依頼人カナ名称」
	,NYUSHUKKIN_CMNT  VARCHAR2(60) --「入出金コメント」
	,JISHA_KOZA_CD  CHAR(4) --「自社口座コード」
	,NYUSHUKKIN_STATUS_KBN  CHAR(1) NOT NULL --「入出金ステータス区分」
	,KS_KZ_KNY_KKN_SHTN_CD  CHAR(3) --「仮想口座金融機関支店コード」
	,KASO_KOZA_NO  CHAR(7) --「仮想口座番号」
	,RONRI_SAKUJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「論理削除フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3601T_PK PRIMARY KEY(
	 NYUSHUKKIN_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3601T_TBL IS '入出金テーブル'
/

COMMENT ON COLUMN ED3601T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3601T_TBL.NYUSHUKKIN_NO IS '入出金番号'
/
COMMENT ON COLUMN ED3601T_TBL.NYUSHUKKIN_KBN IS '入出金区分'
/
COMMENT ON COLUMN ED3601T_TBL.NYUSHUKKIN_YMD IS '入出金年月日'
/
COMMENT ON COLUMN ED3601T_TBL.NYUSHUKKIN_HOHO_KBN IS '入出金方法区分'
/
COMMENT ON COLUMN ED3601T_TBL.NYUSHUKKIN_AMT IS '入出金金額'
/
COMMENT ON COLUMN ED3601T_TBL.NYUSHUKKIN_SHORI_YMD IS '入出金処理年月日'
/
COMMENT ON COLUMN ED3601T_TBL.MISHORI_NYUSHUKKIN_AMT IS '未処理入出金金額'
/
COMMENT ON COLUMN ED3601T_TBL.SHIMUKE_KINYU_KIKAN_KN_NM IS '仕向金融機関カナ名称'
/
COMMENT ON COLUMN ED3601T_TBL.SHMK_KNY_KKN_SHTN_KN_NM IS '仕向金融機関支店カナ名称'
/
COMMENT ON COLUMN ED3601T_TBL.FURIKOMI_IRAININ_KN_NM IS '振込依頼人カナ名称'
/
COMMENT ON COLUMN ED3601T_TBL.NYUSHUKKIN_CMNT IS '入出金コメント'
/
COMMENT ON COLUMN ED3601T_TBL.JISHA_KOZA_CD IS '自社口座コード'
/
COMMENT ON COLUMN ED3601T_TBL.NYUSHUKKIN_STATUS_KBN IS '入出金ステータス区分'
/
COMMENT ON COLUMN ED3601T_TBL.KS_KZ_KNY_KKN_SHTN_CD IS '仮想口座金融機関支店コード'
/
COMMENT ON COLUMN ED3601T_TBL.KASO_KOZA_NO IS '仮想口座番号'
/
COMMENT ON COLUMN ED3601T_TBL.RONRI_SAKUJO_FLG IS '論理削除フラグ'
/
COMMENT ON COLUMN ED3601T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3601T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3601T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3601T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3601T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3601T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3601T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3601T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3601T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3601T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3601T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3601T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
