/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3619T_TBL.sql
-- 物理名：ED3619T_TBL
-- 論理名：預かり保証金管理テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3619T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3619T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,AZKR_HSHKN_SHR_RRK_NO  CHAR(14) NOT NULL --「預かり保証金処理履歴番号」
	,SEIKYUSHO_NO  CHAR(14) --「請求書番号」
	,NYUKIN_YMD  DATE --「入金年月日」
	,NYUKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「入金金額」
	,AZUKARI_HOSHOKIN_SHORI_YMD  DATE --「預かり保証金処理年月日」
	,AZUKARI_HOSHOKIN_SHORI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「預かり保証金処理金額」
	,AZKR_HSHKN_SHR_UCHWK_KBN  CHAR(1) NOT NULL --「預かり保証金処理内訳区分」
	,KEIJO_YMD  DATE --「計上年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3619T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  AZKR_HSHKN_SHR_RRK_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3619T_TBL IS '預かり保証金管理テーブル'
/

COMMENT ON COLUMN ED3619T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3619T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED3619T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED3619T_TBL.AZKR_HSHKN_SHR_RRK_NO IS '預かり保証金処理履歴番号'
/
COMMENT ON COLUMN ED3619T_TBL.SEIKYUSHO_NO IS '請求書番号'
/
COMMENT ON COLUMN ED3619T_TBL.NYUKIN_YMD IS '入金年月日'
/
COMMENT ON COLUMN ED3619T_TBL.NYUKIN_AMT IS '入金金額'
/
COMMENT ON COLUMN ED3619T_TBL.AZUKARI_HOSHOKIN_SHORI_YMD IS '預かり保証金処理年月日'
/
COMMENT ON COLUMN ED3619T_TBL.AZUKARI_HOSHOKIN_SHORI_AMT IS '預かり保証金処理金額'
/
COMMENT ON COLUMN ED3619T_TBL.AZKR_HSHKN_SHR_UCHWK_KBN IS '預かり保証金処理内訳区分'
/
COMMENT ON COLUMN ED3619T_TBL.KEIJO_YMD IS '計上年月日'
/
COMMENT ON COLUMN ED3619T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3619T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3619T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3619T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3619T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3619T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3619T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3619T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3619T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3619T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3619T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3619T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
