/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3606T_TBL.sql
-- 物理名：ED3606T_TBL
-- 論理名：返金管理テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3606T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3606T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,HENKIN_SHINSEI_NO  CHAR(14) NOT NULL --「返金申請番号」
	,NYUSHUKKIN_NO  NUMBER(14,0) DEFAULT '0' NOT NULL --「入出金番号」
	,NYUSHUKKIN_NO_BN  CHAR(6) --「入出金番号枝番」
	,NYUSHUKKIN_FURIKAE_KAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「入出金振替回数」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) --「請求先取引先コード」
	,SEIKYUSAKIBETSU_TEMPLATE_SN  CHAR(5) --「請求先別テンプレート連番」
	,SEIKYU_YM  CHAR(6) --「請求年月」
	,SEIKYUSHO_GROUP_NO  CHAR(3) --「請求書グループ番号」
	,SEIKYUSHO_NO  CHAR(14) --「請求書番号」
	,HENKIN_KBN  CHAR(1) NOT NULL --「返金区分」
	,HENKIN_IRAISHA_NM  VARCHAR2(60) NOT NULL --「返金依頼者氏名」
	,HNKNSK_RNRKSK_DNW_NO  VARCHAR2(20) NOT NULL --「返金先連絡先電話番号」
	,HENKIN_IRAI_YMD  DATE NOT NULL --「返金依頼年月日」
	,HENKIN_YOTEI_YMD  DATE NOT NULL --「返金予定年月日」
	,HENKINSAKI_TORIHIKISAKI_CD  CHAR(9) NOT NULL --「返金先取引先コード」
	,HNKNSK_TRHKSK_SHHRI_JH_CD  CHAR(4) --「返金先取引先支払情報コード」
	,KINYU_KIKAN_CD  CHAR(4) --「金融機関コード」
	,KINYU_KIKAN_SHITEN_CD  CHAR(3) --「金融機関支店コード」
	,KOZA_SHUBETSU_KBN  CHAR(1) --「口座種別区分」
	,KOZA_NO  CHAR(7) --「口座番号」
	,KOZA_MEIGININ_HKN_NM  VARCHAR2(60) --「口座名義人半角カナ氏名」
	,FURIKOMI_TESURYO_KBN  CHAR(1) --「振込手数料区分」
	,KZ_KKNN_SHRI_FILE_SHKBTS_KEY  VARCHAR2(255) --「口座確認書類ファイル識別キー」
	,KOZA_KAKUNIN_SHORUI_FILE_NM  VARCHAR2(255) --「口座確認書類ファイル名称」
	,GNKN_HNKN_TNTSH_SHIN_NO  VARCHAR2(8) --「現金返金担当者社員番号」
	,GENKIN_HENKIN_DOKOSHA_SHAIN_NO  VARCHAR2(8) --「現金返金同行者社員番号」
	,HENKIN_RIYU  VARCHAR2(100) NOT NULL --「返金理由」
	,HENKIN_SHINSEISHA_SHAIN_NO  VARCHAR2(8) NOT NULL --「返金申請者社員番号」
	,HENKIN_SHINSEI_JIGYOSHO_CD  CHAR(6) NOT NULL --「返金申請事業所コード」
	,HENKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「返金金額」
	,KINKYU_GENKIN_HENKIN_RIYU  VARCHAR2(1000) --「緊急現金返金理由」
	,HENKIN_SHONIN_STATUS_KBN  CHAR(1) NOT NULL --「返金承認ステータス区分」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,HENKIN_KEIJO_YMD  DATE --「返金計上年月日」
	,RONRI_SAKUJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「論理削除フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3606T_PK PRIMARY KEY(
	 HENKIN_SHINSEI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3606T_TBL IS '返金管理テーブル'
/

COMMENT ON COLUMN ED3606T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3606T_TBL.HENKIN_SHINSEI_NO IS '返金申請番号'
/
COMMENT ON COLUMN ED3606T_TBL.NYUSHUKKIN_NO IS '入出金番号'
/
COMMENT ON COLUMN ED3606T_TBL.NYUSHUKKIN_NO_BN IS '入出金番号枝番'
/
COMMENT ON COLUMN ED3606T_TBL.NYUSHUKKIN_FURIKAE_KAISU IS '入出金振替回数'
/
COMMENT ON COLUMN ED3606T_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED3606T_TBL.SEIKYUSAKIBETSU_TEMPLATE_SN IS '請求先別テンプレート連番'
/
COMMENT ON COLUMN ED3606T_TBL.SEIKYU_YM IS '請求年月'
/
COMMENT ON COLUMN ED3606T_TBL.SEIKYUSHO_GROUP_NO IS '請求書グループ番号'
/
COMMENT ON COLUMN ED3606T_TBL.SEIKYUSHO_NO IS '請求書番号'
/
COMMENT ON COLUMN ED3606T_TBL.HENKIN_KBN IS '返金区分'
/
COMMENT ON COLUMN ED3606T_TBL.HENKIN_IRAISHA_NM IS '返金依頼者氏名'
/
COMMENT ON COLUMN ED3606T_TBL.HNKNSK_RNRKSK_DNW_NO IS '返金先連絡先電話番号'
/
COMMENT ON COLUMN ED3606T_TBL.HENKIN_IRAI_YMD IS '返金依頼年月日'
/
COMMENT ON COLUMN ED3606T_TBL.HENKIN_YOTEI_YMD IS '返金予定年月日'
/
COMMENT ON COLUMN ED3606T_TBL.HENKINSAKI_TORIHIKISAKI_CD IS '返金先取引先コード'
/
COMMENT ON COLUMN ED3606T_TBL.HNKNSK_TRHKSK_SHHRI_JH_CD IS '返金先取引先支払情報コード'
/
COMMENT ON COLUMN ED3606T_TBL.KINYU_KIKAN_CD IS '金融機関コード'
/
COMMENT ON COLUMN ED3606T_TBL.KINYU_KIKAN_SHITEN_CD IS '金融機関支店コード'
/
COMMENT ON COLUMN ED3606T_TBL.KOZA_SHUBETSU_KBN IS '口座種別区分'
/
COMMENT ON COLUMN ED3606T_TBL.KOZA_NO IS '口座番号'
/
COMMENT ON COLUMN ED3606T_TBL.KOZA_MEIGININ_HKN_NM IS '口座名義人半角カナ氏名'
/
COMMENT ON COLUMN ED3606T_TBL.FURIKOMI_TESURYO_KBN IS '振込手数料区分'
/
COMMENT ON COLUMN ED3606T_TBL.KZ_KKNN_SHRI_FILE_SHKBTS_KEY IS '口座確認書類ファイル識別キー'
/
COMMENT ON COLUMN ED3606T_TBL.KOZA_KAKUNIN_SHORUI_FILE_NM IS '口座確認書類ファイル名称'
/
COMMENT ON COLUMN ED3606T_TBL.GNKN_HNKN_TNTSH_SHIN_NO IS '現金返金担当者社員番号'
/
COMMENT ON COLUMN ED3606T_TBL.GENKIN_HENKIN_DOKOSHA_SHAIN_NO IS '現金返金同行者社員番号'
/
COMMENT ON COLUMN ED3606T_TBL.HENKIN_RIYU IS '返金理由'
/
COMMENT ON COLUMN ED3606T_TBL.HENKIN_SHINSEISHA_SHAIN_NO IS '返金申請者社員番号'
/
COMMENT ON COLUMN ED3606T_TBL.HENKIN_SHINSEI_JIGYOSHO_CD IS '返金申請事業所コード'
/
COMMENT ON COLUMN ED3606T_TBL.HENKIN_AMT IS '返金金額'
/
COMMENT ON COLUMN ED3606T_TBL.KINKYU_GENKIN_HENKIN_RIYU IS '緊急現金返金理由'
/
COMMENT ON COLUMN ED3606T_TBL.HENKIN_SHONIN_STATUS_KBN IS '返金承認ステータス区分'
/
COMMENT ON COLUMN ED3606T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED3606T_TBL.HENKIN_KEIJO_YMD IS '返金計上年月日'
/
COMMENT ON COLUMN ED3606T_TBL.RONRI_SAKUJO_FLG IS '論理削除フラグ'
/
COMMENT ON COLUMN ED3606T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3606T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3606T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3606T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3606T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3606T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3606T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3606T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3606T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3606T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3606T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3606T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
