/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3604T_TBL.sql
-- 物理名：ED3604T_TBL
-- 論理名：仮受金テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3604T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3604T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,NYUSHUKKIN_NO  NUMBER(14,0) NOT NULL --「入出金番号」
	,NYUSHUKKIN_NO_BN  CHAR(6) NOT NULL --「入出金番号枝番」
	,NYUSHUKKIN_FURIKAE_KAISU  NUMBER(9,0) NOT NULL --「入出金振替回数」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) --「請求先取引先コード」
	,SEIKYUSHO_TEMPLATE_NO  CHAR(14) --「請求書テンプレート番号」
	,KARIUKEKIN_SHORI_KBN  CHAR(1) NOT NULL --「仮受金処理区分」
	,KARIUKEKIN_EIGYO_CMNT  VARCHAR2(60) --「仮受金営業コメント」
	,EIGYO_KAIKEI_CMNT  VARCHAR2(60) --「営業会計コメント」
	,RONRI_SAKUJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「論理削除フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3604T_PK PRIMARY KEY(
	 NYUSHUKKIN_NO
	,  NYUSHUKKIN_NO_BN
	,  NYUSHUKKIN_FURIKAE_KAISU
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3604T_TBL IS '仮受金テーブル'
/

COMMENT ON COLUMN ED3604T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3604T_TBL.NYUSHUKKIN_NO IS '入出金番号'
/
COMMENT ON COLUMN ED3604T_TBL.NYUSHUKKIN_NO_BN IS '入出金番号枝番'
/
COMMENT ON COLUMN ED3604T_TBL.NYUSHUKKIN_FURIKAE_KAISU IS '入出金振替回数'
/
COMMENT ON COLUMN ED3604T_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED3604T_TBL.SEIKYUSHO_TEMPLATE_NO IS '請求書テンプレート番号'
/
COMMENT ON COLUMN ED3604T_TBL.KARIUKEKIN_SHORI_KBN IS '仮受金処理区分'
/
COMMENT ON COLUMN ED3604T_TBL.KARIUKEKIN_EIGYO_CMNT IS '仮受金営業コメント'
/
COMMENT ON COLUMN ED3604T_TBL.EIGYO_KAIKEI_CMNT IS '営業会計コメント'
/
COMMENT ON COLUMN ED3604T_TBL.RONRI_SAKUJO_FLG IS '論理削除フラグ'
/
COMMENT ON COLUMN ED3604T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3604T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3604T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3604T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3604T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3604T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3604T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3604T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3604T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3604T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3604T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3604T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
