/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3615T_TBL.sql
-- 物理名：ED3615T_TBL
-- 論理名：領収証テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3615T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3615T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,RYOSHUSHO_KANRI_NO  CHAR(14) NOT NULL --「領収証管理番号」
	,RYOSHUSHO_HAKKO_KAISU  NUMBER(9,0) DEFAULT '1' NOT NULL --「領収証発行回数」
	,RYOSHUSHO_NO  CHAR(14) --「領収証番号」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) NOT NULL --「請求先取引先コード」
	,DIHY_KIYKSK_TRHKSK_CD  CHAR(9) NOT NULL --「代表契約先取引先コード」
	,RYOSHUSHO_HAKKO_KIIN_KBN  CHAR(1) NOT NULL --「領収証発行起因区分」
	,HAKKOJI_NYUKINARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「発行時入金有フラグ」
	,RYOSHUSHO_TADASHIGAKI_NAIYO_1  VARCHAR2(62) --「領収証但書内容１」
	,RYOSHUSHO_TADASHIGAKI_NAIYO_2  VARCHAR2(54) --「領収証但書内容２」
	,RYOSHU_ZEIKOMI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「領収税込金額」
	,RYOSHU_ZEINUKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「領収税抜金額」
	,RYOSHU_SHOHIZEI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「領収消費税金額」
	,RYOSHUSHO_HYOJI_YMD  DATE --「領収証表示年月日」
	,RYOSHUSHO_HAKKO_YOTEI_YMD  DATE --「領収証発行予定年月日」
	,RYOSHUSHO_YUKO_KIGEN_YMD  DATE --「領収証有効期限年月日」
	,DAIHYO_GYOMU_TAISHOSAKI_CD  CHAR(9) NOT NULL --「代表業務対象先コード」
	,DAIHYO_JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「代表受注契約番号」
	,RYOSHUSHO_HAKKO_JIGYOSHO_CD  CHAR(6) --「領収証発行事業所コード」
	,RYOSHUSHO_HAKKO_SHAIN_NO  VARCHAR2(8) --「領収証発行社員番号」
	,RYOSHUSHO_HAKKO_YMD  DATE --「領収証発行年月日」
	,RYOSHUSHO_SHINSEI_JIGYOSHO_CD  CHAR(6) NOT NULL --「領収証申請事業所コード」
	,RYOSHUSHO_SHINSEI_SHAIN_NO  VARCHAR2(8) NOT NULL --「領収証申請社員番号」
	,RYOSHUSHO_SHINSEI_YMD  DATE NOT NULL --「領収証申請年月日」
	,JISHA_KOZA_CD  CHAR(4) --「自社口座コード」
	,RYOSHUSHO_STATUS_KBN  CHAR(1) DEFAULT '1' NOT NULL --「領収証ステータス区分」
	,RYOSHUSHO_HAKKO_KBN  CHAR(1) --「領収証発行区分」
	,RYSHSH_TRKSHND_RIYU_KBN  CHAR(3) --「領収証取消等理由区分」
	,RYOSHUSHO_ENCHO_NISSU_KBN  CHAR(1) --「領収証延長日数区分」
	,RYOSHUSHO_TORIKESHINADO_RIYU  VARCHAR2(30) --「領収証取消等理由」
	,RYSHSH_TRKSHND_SHNSI_SHIN_NO  VARCHAR2(8) --「領収証取消等申請社員番号」
	,RYSHSH_TRKSHND_IRI_YMD  DATE --「領収証取消等依頼年月日」
	,SHUKIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「集金フラグ」
	,SHUKIN_NO  CHAR(14) --「集金番号」
	,SHUKIN_RIYU_KBN  CHAR(1) --「集金理由区分」
	,SHUKIN_RIYU_NAIYO  VARCHAR2(100) --「集金理由内容」
	,SHUKIN_YOTEI_YMD  DATE --「集金予定年月日」
	,RINGI_KIAN_NO  VARCHAR2(20) --「稟議起案番号」
	,INEI_GAZO_ID  CHAR(5) --「印影画像ＩＤ」
	,RYSHSH_IKKTS_SHNSI_SHNN_NO  CHAR(14) --「領収証一括申請承認番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3615T_PK PRIMARY KEY(
	 RYOSHUSHO_KANRI_NO
	,  RYOSHUSHO_HAKKO_KAISU
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3615T_TBL IS '領収証テーブル'
/

COMMENT ON COLUMN ED3615T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_KANRI_NO IS '領収証管理番号'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_HAKKO_KAISU IS '領収証発行回数'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_NO IS '領収証番号'
/
COMMENT ON COLUMN ED3615T_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED3615T_TBL.DIHY_KIYKSK_TRHKSK_CD IS '代表契約先取引先コード'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_HAKKO_KIIN_KBN IS '領収証発行起因区分'
/
COMMENT ON COLUMN ED3615T_TBL.HAKKOJI_NYUKINARI_FLG IS '発行時入金有フラグ'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_TADASHIGAKI_NAIYO_1 IS '領収証但書内容１'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_TADASHIGAKI_NAIYO_2 IS '領収証但書内容２'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHU_ZEIKOMI_AMT IS '領収税込金額'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHU_ZEINUKI_AMT IS '領収税抜金額'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHU_SHOHIZEI_AMT IS '領収消費税金額'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_HYOJI_YMD IS '領収証表示年月日'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_HAKKO_YOTEI_YMD IS '領収証発行予定年月日'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_YUKO_KIGEN_YMD IS '領収証有効期限年月日'
/
COMMENT ON COLUMN ED3615T_TBL.DAIHYO_GYOMU_TAISHOSAKI_CD IS '代表業務対象先コード'
/
COMMENT ON COLUMN ED3615T_TBL.DAIHYO_JUCHU_KEIYAKU_NO IS '代表受注契約番号'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_HAKKO_JIGYOSHO_CD IS '領収証発行事業所コード'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_HAKKO_SHAIN_NO IS '領収証発行社員番号'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_HAKKO_YMD IS '領収証発行年月日'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_SHINSEI_JIGYOSHO_CD IS '領収証申請事業所コード'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_SHINSEI_SHAIN_NO IS '領収証申請社員番号'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_SHINSEI_YMD IS '領収証申請年月日'
/
COMMENT ON COLUMN ED3615T_TBL.JISHA_KOZA_CD IS '自社口座コード'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_STATUS_KBN IS '領収証ステータス区分'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_HAKKO_KBN IS '領収証発行区分'
/
COMMENT ON COLUMN ED3615T_TBL.RYSHSH_TRKSHND_RIYU_KBN IS '領収証取消等理由区分'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_ENCHO_NISSU_KBN IS '領収証延長日数区分'
/
COMMENT ON COLUMN ED3615T_TBL.RYOSHUSHO_TORIKESHINADO_RIYU IS '領収証取消等理由'
/
COMMENT ON COLUMN ED3615T_TBL.RYSHSH_TRKSHND_SHNSI_SHIN_NO IS '領収証取消等申請社員番号'
/
COMMENT ON COLUMN ED3615T_TBL.RYSHSH_TRKSHND_IRI_YMD IS '領収証取消等依頼年月日'
/
COMMENT ON COLUMN ED3615T_TBL.SHUKIN_FLG IS '集金フラグ'
/
COMMENT ON COLUMN ED3615T_TBL.SHUKIN_NO IS '集金番号'
/
COMMENT ON COLUMN ED3615T_TBL.SHUKIN_RIYU_KBN IS '集金理由区分'
/
COMMENT ON COLUMN ED3615T_TBL.SHUKIN_RIYU_NAIYO IS '集金理由内容'
/
COMMENT ON COLUMN ED3615T_TBL.SHUKIN_YOTEI_YMD IS '集金予定年月日'
/
COMMENT ON COLUMN ED3615T_TBL.RINGI_KIAN_NO IS '稟議起案番号'
/
COMMENT ON COLUMN ED3615T_TBL.INEI_GAZO_ID IS '印影画像ＩＤ'
/
COMMENT ON COLUMN ED3615T_TBL.RYSHSH_IKKTS_SHNSI_SHNN_NO IS '領収証一括申請承認番号'
/
COMMENT ON COLUMN ED3615T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3615T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3615T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3615T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3615T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3615T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3615T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3615T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3615T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3615T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3615T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3615T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
