/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3616T_TBL.sql
-- 物理名：ED3616T_TBL
-- 論理名：領収証請求紐付テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3616T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3616T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,RYOSHUSHO_KANRI_NO  CHAR(14) NOT NULL --「領収証管理番号」
	,RYOSHUSHO_HAKKO_KAISU  NUMBER(9,0) DEFAULT '1' NOT NULL --「領収証発行回数」
	,RYOSHUSHO_NO  CHAR(14) --「領収証番号」
	,SEIKYUSHO_NO  CHAR(14) NOT NULL --「請求書番号」
	,SEIKYUSHO_MEISAI_SN  CHAR(14) NOT NULL --「請求書明細連番」
	,KNKI_RYSHSH_HKK_ZIKM_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「今回領収証発行税込金額」
	,KNKI_RYSHSH_HKK_ZINK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「今回領収証発行税抜金額」
	,KNKI_RYSHSH_HKK_SHHZI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「今回領収証発行消費税金額」
	,RONRI_SAKUJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「論理削除フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3616T_PK PRIMARY KEY(
	 RYOSHUSHO_KANRI_NO
	,  RYOSHUSHO_HAKKO_KAISU
	,  SEIKYUSHO_NO
	,  SEIKYUSHO_MEISAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3616T_TBL IS '領収証請求紐付テーブル'
/

COMMENT ON COLUMN ED3616T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3616T_TBL.RYOSHUSHO_KANRI_NO IS '領収証管理番号'
/
COMMENT ON COLUMN ED3616T_TBL.RYOSHUSHO_HAKKO_KAISU IS '領収証発行回数'
/
COMMENT ON COLUMN ED3616T_TBL.RYOSHUSHO_NO IS '領収証番号'
/
COMMENT ON COLUMN ED3616T_TBL.SEIKYUSHO_NO IS '請求書番号'
/
COMMENT ON COLUMN ED3616T_TBL.SEIKYUSHO_MEISAI_SN IS '請求書明細連番'
/
COMMENT ON COLUMN ED3616T_TBL.KNKI_RYSHSH_HKK_ZIKM_AMT IS '今回領収証発行税込金額'
/
COMMENT ON COLUMN ED3616T_TBL.KNKI_RYSHSH_HKK_ZINK_AMT IS '今回領収証発行税抜金額'
/
COMMENT ON COLUMN ED3616T_TBL.KNKI_RYSHSH_HKK_SHHZI_AMT IS '今回領収証発行消費税金額'
/
COMMENT ON COLUMN ED3616T_TBL.RONRI_SAKUJO_FLG IS '論理削除フラグ'
/
COMMENT ON COLUMN ED3616T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3616T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3616T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3616T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3616T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3616T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3616T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3616T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3616T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3616T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3616T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3616T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
