/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3624W_TBL.sql
-- 物理名：ED3624W_TBL
-- 論理名：振替実績ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3624W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3624W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,FURIKAE_JISSEKI_ID  CHAR(16) NOT NULL --「振替実績ＩＤ」
	,SEIKYU_KANRI_MEISAI_NO  CHAR(14) --「請求管理明細番号」
	,SEIKYUSHO_NO  CHAR(14) --「請求書番号」
	,SEIKYUSHO_MEISAI_SN  CHAR(14) --「請求書明細連番」
	,GASSAN_UCHIWAKE_MEISAI_SN  CHAR(14) --「合算内訳明細連番」
	,JIGYO_SEGMENT_CD  CHAR(3) NOT NULL --「事業セグメントコード」
	,SEIKYUSHO_HYOJI_KAISHI_YMD  DATE --「請求書表示開始年月日」
	,SEIKYUSHO_HYOJI_SHURYO_YMD  DATE --「請求書表示終了年月日」
	,NYUSHUKKIN_NO  NUMBER(14,0) DEFAULT '0' NOT NULL --「入出金番号」
	,NYUSHUKKIN_NO_BN  CHAR(6) --「入出金番号枝番」
	,FURIKAE_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「振替金額」
	,RONRI_SAKUJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「論理削除フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3624W_PK PRIMARY KEY(
	 FURIKAE_JISSEKI_ID
	,  JIGYO_SEGMENT_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3624W_TBL IS '振替実績ワーク'
/

COMMENT ON COLUMN ED3624W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3624W_TBL.FURIKAE_JISSEKI_ID IS '振替実績ＩＤ'
/
COMMENT ON COLUMN ED3624W_TBL.SEIKYU_KANRI_MEISAI_NO IS '請求管理明細番号'
/
COMMENT ON COLUMN ED3624W_TBL.SEIKYUSHO_NO IS '請求書番号'
/
COMMENT ON COLUMN ED3624W_TBL.SEIKYUSHO_MEISAI_SN IS '請求書明細連番'
/
COMMENT ON COLUMN ED3624W_TBL.GASSAN_UCHIWAKE_MEISAI_SN IS '合算内訳明細連番'
/
COMMENT ON COLUMN ED3624W_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED3624W_TBL.SEIKYUSHO_HYOJI_KAISHI_YMD IS '請求書表示開始年月日'
/
COMMENT ON COLUMN ED3624W_TBL.SEIKYUSHO_HYOJI_SHURYO_YMD IS '請求書表示終了年月日'
/
COMMENT ON COLUMN ED3624W_TBL.NYUSHUKKIN_NO IS '入出金番号'
/
COMMENT ON COLUMN ED3624W_TBL.NYUSHUKKIN_NO_BN IS '入出金番号枝番'
/
COMMENT ON COLUMN ED3624W_TBL.FURIKAE_AMT IS '振替金額'
/
COMMENT ON COLUMN ED3624W_TBL.RONRI_SAKUJO_FLG IS '論理削除フラグ'
/
COMMENT ON COLUMN ED3624W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3624W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3624W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3624W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3624W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3624W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3624W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3624W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3624W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3624W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3624W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3624W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
