/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3627W_TBL.sql
-- 物理名：ED3627W_TBL
-- 論理名：自動消込ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3627W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3627W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,NYUSHUKKIN_NO  NUMBER(14,0) NOT NULL --「入出金番号」
	,SEIKYUSHO_NO  CHAR(14) NOT NULL --「請求書番号」
	,KESHIKOMI_TANI_ID  CHAR(16) NOT NULL --「消込単位ＩＤ」
	,KESHIKOMI_RULE_CATEGORY_KBN  CHAR(1) NOT NULL --「消込ルールカテゴリ区分」
	,KESHIKOMI_RULE_NO  NUMBER(2,0) NOT NULL --「消込ルール番号」
	,NYUSHUKKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「入出金金額」
	,SEIKYUSHO_STATUS_KBN  CHAR(2) NOT NULL --「請求書ステータス区分」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) --「請求先取引先コード」
	,SEIKYUSAKIBETSU_TEMPLATE_SN  CHAR(5) --「請求先別テンプレート連番」
	,GOKEI_ZEIKOMI_SEIKYU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「合計税込請求金額」
	,KESHIKOMI_KBN  CHAR(1) NOT NULL --「消込区分」
	,KESHIKOMI_HENKO_YOTEI_KBN  CHAR(1) NOT NULL --「消込変更予定区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3627W_PK PRIMARY KEY(
	 KAISHA_CD
	,  NYUSHUKKIN_NO
	,  SEIKYUSHO_NO
	,  KESHIKOMI_TANI_ID
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3627W_TBL IS '自動消込ワーク'
/

COMMENT ON COLUMN ED3627W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3627W_TBL.NYUSHUKKIN_NO IS '入出金番号'
/
COMMENT ON COLUMN ED3627W_TBL.SEIKYUSHO_NO IS '請求書番号'
/
COMMENT ON COLUMN ED3627W_TBL.KESHIKOMI_TANI_ID IS '消込単位ＩＤ'
/
COMMENT ON COLUMN ED3627W_TBL.KESHIKOMI_RULE_CATEGORY_KBN IS '消込ルールカテゴリ区分'
/
COMMENT ON COLUMN ED3627W_TBL.KESHIKOMI_RULE_NO IS '消込ルール番号'
/
COMMENT ON COLUMN ED3627W_TBL.NYUSHUKKIN_AMT IS '入出金金額'
/
COMMENT ON COLUMN ED3627W_TBL.SEIKYUSHO_STATUS_KBN IS '請求書ステータス区分'
/
COMMENT ON COLUMN ED3627W_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED3627W_TBL.SEIKYUSAKIBETSU_TEMPLATE_SN IS '請求先別テンプレート連番'
/
COMMENT ON COLUMN ED3627W_TBL.GOKEI_ZEIKOMI_SEIKYU_AMT IS '合計税込請求金額'
/
COMMENT ON COLUMN ED3627W_TBL.KESHIKOMI_KBN IS '消込区分'
/
COMMENT ON COLUMN ED3627W_TBL.KESHIKOMI_HENKO_YOTEI_KBN IS '消込変更予定区分'
/
COMMENT ON COLUMN ED3627W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3627W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3627W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3627W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3627W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3627W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3627W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3627W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3627W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3627W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3627W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3627W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
