/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3620T_TBL.sql
-- 物理名：ED3620T_TBL
-- 論理名：預かり保証金月次テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3620T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3620T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TAISHO_YM  CHAR(6) NOT NULL --「対象年月」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,SEIKYU_KANRI_JIGYOSHO_CD  CHAR(6) --「請求管理事業所コード」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,JUCHU_TANTO_SHAIN_NO  VARCHAR2(8) --「受注担当社員番号」
	,NYUKIN_YMD  DATE --「入金年月日」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) --「請求先取引先コード」
	,SHOHIN_SERVICE_CD  CHAR(3) --「商品サービスコード」
	,GYOMU_KAISHI_YMD  DATE --「業務開始年月日」
	,KEIYAKU_MANRYO_YMD  DATE --「契約満了年月日」
	,AZUKARI_HOSHOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「預かり保証金金額」
	,AZUKARI_HOSHOKIN_ZANDAKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「預かり保証金残高金額」
	,KAIYAKU_YMD  DATE --「解約年月日」
	,AZUKARI_HOSHOKIN_SHORI_YMD  DATE --「預かり保証金処理年月日」
	,AZKR_HSHKN_SHR_UCHWK_KBN  CHAR(1) NOT NULL --「預かり保証金処理内訳区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3620T_PK PRIMARY KEY(
	 TAISHO_YM
	,  JUCHU_KEIYAKU_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3620T_TBL IS '預かり保証金月次テーブル'
/

COMMENT ON COLUMN ED3620T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3620T_TBL.TAISHO_YM IS '対象年月'
/
COMMENT ON COLUMN ED3620T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED3620T_TBL.SEIKYU_KANRI_JIGYOSHO_CD IS '請求管理事業所コード'
/
COMMENT ON COLUMN ED3620T_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED3620T_TBL.JUCHU_TANTO_SHAIN_NO IS '受注担当社員番号'
/
COMMENT ON COLUMN ED3620T_TBL.NYUKIN_YMD IS '入金年月日'
/
COMMENT ON COLUMN ED3620T_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED3620T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED3620T_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED3620T_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED3620T_TBL.GYOMU_KAISHI_YMD IS '業務開始年月日'
/
COMMENT ON COLUMN ED3620T_TBL.KEIYAKU_MANRYO_YMD IS '契約満了年月日'
/
COMMENT ON COLUMN ED3620T_TBL.AZUKARI_HOSHOKIN_AMT IS '預かり保証金金額'
/
COMMENT ON COLUMN ED3620T_TBL.AZUKARI_HOSHOKIN_ZANDAKA_AMT IS '預かり保証金残高金額'
/
COMMENT ON COLUMN ED3620T_TBL.KAIYAKU_YMD IS '解約年月日'
/
COMMENT ON COLUMN ED3620T_TBL.AZUKARI_HOSHOKIN_SHORI_YMD IS '預かり保証金処理年月日'
/
COMMENT ON COLUMN ED3620T_TBL.AZKR_HSHKN_SHR_UCHWK_KBN IS '預かり保証金処理内訳区分'
/
COMMENT ON COLUMN ED3620T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3620T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3620T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3620T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3620T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3620T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3620T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3620T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3620T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3620T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3620T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3620T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
