/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3736W_TBL.sql
-- 物理名：ED3736W_TBL
-- 論理名：売掛債権日次請求書明細ワークバックアップ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3736W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3736W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SEIKYUSHO_NO  CHAR(14) NOT NULL --「請求書番号」
	,SEIKYUSHO_MEISAI_SN  CHAR(14) NOT NULL --「請求書明細連番」
	,GASSAN_UCHIWAKE_MEISAI_SN  CHAR(14) NOT NULL --「合算内訳明細連番」
	,JIGYO_SEGMENT_CD  CHAR(3) NOT NULL --「事業セグメントコード」
	,SEIKYUSHO_MEISAI_GASSAN_KBN  CHAR(1) NOT NULL --「請求書明細合算区分」
	,SEIKYU_KANRI_MEISAI_NO  CHAR(14) --「請求管理明細番号」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「受注契約変更番号」
	,SEIKYU_SHIHARAI_CD  CHAR(3) --「請求支払コード」
	,TOSHO_NYUKIN_YOTEI_YMD  DATE --「当初入金予定年月日」
	,SEIKYUSHO_MEISAI_TEKIYO  VARCHAR2(62) --「請求書明細摘要」
	,SEIKYUSHO_MEISAI_BIKO  VARCHAR2(54) --「請求書明細備考」
	,SEIKYU_DAIKO_KANRI_NO  CHAR(13) --「請求代行管理番号」
	,NYUKINZUMI_AMT  NUMBER(13,0) NOT NULL --「入金済金額」
	,ZEIKOMI_SEIKYU_AMT  NUMBER(13,0) NOT NULL --「税込請求金額」
	,ZEINUKI_SEIKYU_AMT  NUMBER(13,0) NOT NULL --「税抜請求金額」
	,ZEIKOMI_SAIKEN_ZANDAKA_AMT  NUMBER(13,0) NOT NULL --「税込債権残高金額」
	,TAIRYU_TSUKISU  NUMBER(9,0) --「滞留月数」
	,SHOHI_ZEIRITSU_CD  CHAR(2) --「消費税率コード」
	,URIKAKE_SAIKEN_ZANDAKA_AMT  NUMBER(13,0) NOT NULL --「売掛債権残高金額」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3736W_PK PRIMARY KEY(
	 SEIKYUSHO_NO
	,  SEIKYUSHO_MEISAI_SN
	,  GASSAN_UCHIWAKE_MEISAI_SN
	,  JIGYO_SEGMENT_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3736W_TBL IS '売掛債権日次請求書明細ワークバックアップ'
/

COMMENT ON COLUMN ED3736W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3736W_TBL.SEIKYUSHO_NO IS '請求書番号'
/
COMMENT ON COLUMN ED3736W_TBL.SEIKYUSHO_MEISAI_SN IS '請求書明細連番'
/
COMMENT ON COLUMN ED3736W_TBL.GASSAN_UCHIWAKE_MEISAI_SN IS '合算内訳明細連番'
/
COMMENT ON COLUMN ED3736W_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED3736W_TBL.SEIKYUSHO_MEISAI_GASSAN_KBN IS '請求書明細合算区分'
/
COMMENT ON COLUMN ED3736W_TBL.SEIKYU_KANRI_MEISAI_NO IS '請求管理明細番号'
/
COMMENT ON COLUMN ED3736W_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED3736W_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED3736W_TBL.SEIKYU_SHIHARAI_CD IS '請求支払コード'
/
COMMENT ON COLUMN ED3736W_TBL.TOSHO_NYUKIN_YOTEI_YMD IS '当初入金予定年月日'
/
COMMENT ON COLUMN ED3736W_TBL.SEIKYUSHO_MEISAI_TEKIYO IS '請求書明細摘要'
/
COMMENT ON COLUMN ED3736W_TBL.SEIKYUSHO_MEISAI_BIKO IS '請求書明細備考'
/
COMMENT ON COLUMN ED3736W_TBL.SEIKYU_DAIKO_KANRI_NO IS '請求代行管理番号'
/
COMMENT ON COLUMN ED3736W_TBL.NYUKINZUMI_AMT IS '入金済金額'
/
COMMENT ON COLUMN ED3736W_TBL.ZEIKOMI_SEIKYU_AMT IS '税込請求金額'
/
COMMENT ON COLUMN ED3736W_TBL.ZEINUKI_SEIKYU_AMT IS '税抜請求金額'
/
COMMENT ON COLUMN ED3736W_TBL.ZEIKOMI_SAIKEN_ZANDAKA_AMT IS '税込債権残高金額'
/
COMMENT ON COLUMN ED3736W_TBL.TAIRYU_TSUKISU IS '滞留月数'
/
COMMENT ON COLUMN ED3736W_TBL.SHOHI_ZEIRITSU_CD IS '消費税率コード'
/
COMMENT ON COLUMN ED3736W_TBL.URIKAKE_SAIKEN_ZANDAKA_AMT IS '売掛債権残高金額'
/
COMMENT ON COLUMN ED3736W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3736W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3736W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3736W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3736W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3736W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3736W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3736W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3736W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3736W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3736W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3736W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
