/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3721T_TBL.sql
-- 物理名：ED3721T_TBL
-- 論理名：滞留債権分割回収明細テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3721T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3721T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TAIRYU_SAIKEN_ID  CHAR(14) NOT NULL --「滞留債権ＩＤ」
	,BUNKATSU_KAISHU_MEISAI_NO  NUMBER(9,0) NOT NULL --「分割回収明細番号」
	,BNKTS_KISH_MISI_SHBTS_KBN  CHAR(1) NOT NULL --「分割回収明細種別区分」
	,ZEINUKI_SEIKYU_AMT  NUMBER(13,0) --「税抜請求金額」
	,SHOHIZEI_AMT  NUMBER(13,0) --「消費税金額」
	,ZEIKOMI_SEIKYU_AMT  NUMBER(13,0) --「税込請求金額」
	,SHOHIZEI_KBN  CHAR(1) NOT NULL --「消費税区分」
	,SHOHI_ZEIRITSU_CD  CHAR(2) --「消費税率コード」
	,BUNKATSU_KAISHU_SHIHARAI_YM  CHAR(6) --「分割回収支払年月」
	,BUNKATSU_KAISHU_TEKIYO  VARCHAR2(60) --「分割回収摘要」
	,BUNKATSU_KAISHU_BIKO  VARCHAR2(60) --「分割回収備考」
	,BUNKATSU_KAISHU_MEMO_NAIYO  VARCHAR2(60) --「分割回収メモ内容」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3721T_PK PRIMARY KEY(
	 TAIRYU_SAIKEN_ID
	,  BUNKATSU_KAISHU_MEISAI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3721T_TBL IS '滞留債権分割回収明細テーブル'
/

COMMENT ON COLUMN ED3721T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3721T_TBL.TAIRYU_SAIKEN_ID IS '滞留債権ＩＤ'
/
COMMENT ON COLUMN ED3721T_TBL.BUNKATSU_KAISHU_MEISAI_NO IS '分割回収明細番号'
/
COMMENT ON COLUMN ED3721T_TBL.BNKTS_KISH_MISI_SHBTS_KBN IS '分割回収明細種別区分'
/
COMMENT ON COLUMN ED3721T_TBL.ZEINUKI_SEIKYU_AMT IS '税抜請求金額'
/
COMMENT ON COLUMN ED3721T_TBL.SHOHIZEI_AMT IS '消費税金額'
/
COMMENT ON COLUMN ED3721T_TBL.ZEIKOMI_SEIKYU_AMT IS '税込請求金額'
/
COMMENT ON COLUMN ED3721T_TBL.SHOHIZEI_KBN IS '消費税区分'
/
COMMENT ON COLUMN ED3721T_TBL.SHOHI_ZEIRITSU_CD IS '消費税率コード'
/
COMMENT ON COLUMN ED3721T_TBL.BUNKATSU_KAISHU_SHIHARAI_YM IS '分割回収支払年月'
/
COMMENT ON COLUMN ED3721T_TBL.BUNKATSU_KAISHU_TEKIYO IS '分割回収摘要'
/
COMMENT ON COLUMN ED3721T_TBL.BUNKATSU_KAISHU_BIKO IS '分割回収備考'
/
COMMENT ON COLUMN ED3721T_TBL.BUNKATSU_KAISHU_MEMO_NAIYO IS '分割回収メモ内容'
/
COMMENT ON COLUMN ED3721T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3721T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3721T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3721T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3721T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3721T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3721T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3721T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3721T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3721T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3721T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3721T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
