/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3735W_TBL.sql
-- 物理名：ED3735W_TBL
-- 論理名：売掛債権日次請求書ワークバックアップ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3735W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3735W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SEIKYUSHO_NO  CHAR(14) NOT NULL --「請求書番号」
	,TAIRYU_SAIKEN_ID  CHAR(14) --「滞留債権ＩＤ」
	,SEIKYUSHO_STATUS_KBN  CHAR(2) --「請求書ステータス区分」
	,SEIKYU_KANRI_JIGYOSHO_CD  CHAR(6) --「請求管理事業所コード」
	,SEIKYU_KANRI_JIGYOSHO_NM  VARCHAR2(200) --「請求管理事業所名称」
	,SIKY_KNR_JGYSH_TNT_SHIN_NM  VARCHAR2(60) --「請求管理事業所担当社員氏名」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) --「請求先取引先コード」
	,SEIKYUSHO_SOFUSAKI_YUBIN_NO  CHAR(7) --「請求書送付先郵便番号」
	,SEIKYUSHO_SOFUSAKI_JUSHO_1  VARCHAR2(30) --「請求書送付先住所１」
	,SEIKYUSHO_SOFUSAKI_JUSHO_2  VARCHAR2(30) --「請求書送付先住所２」
	,SEIKYUSHO_SOFUSAKI_JUSHO_3  VARCHAR2(30) --「請求書送付先住所３」
	,SEIKYUSHO_SOFUSAKI_JUSHO_4  VARCHAR2(30) --「請求書送付先住所４」
	,SIKYSK_TRHKSKI_SISHK_NM_1  VARCHAR2(27) --「請求先取引先正式名称１」
	,SIKYSK_TRHKSKI_SISHK_NM_2  VARCHAR2(27) --「請求先取引先正式名称２」
	,SEIKYUSHO_ATENA_NM_1  VARCHAR2(31) --「請求書宛名名称１」
	,SEIKYUSHO_ATENA_NM_2  VARCHAR2(31) --「請求書宛名名称２」
	,SEIKYUSHO_ATENA_NM_3  VARCHAR2(31) --「請求書宛名名称３」
	,SEIKYUSHO_ATENA_NM_4  VARCHAR2(31) --「請求書宛名名称４」
	,SEIKYUSHO_ATENA_NM_5  VARCHAR2(31) --「請求書宛名名称５」
	,SEIKYUSHO_HASSO_HOHO_KBN  CHAR(1) --「請求書発送方法区分」
	,SEIKYUSHO_HAKKO_HOHO_KBN  CHAR(1) --「請求書発行方法区分」
	,SHITEI_SEIKYUSHO_SHOSHIKI_CD  CHAR(4) --「指定請求書書式コード」
	,SHITEI_SEIKYUSHO_SHOSHIKI_NM  VARCHAR2(60) --「指定請求書書式名称」
	,DAIHYO_SEIKYUSHO_TEKIYO  VARCHAR2(62) --「代表請求書摘要」
	,DAIHYO_SEIKYUSHO_BIKO  VARCHAR2(54) --「代表請求書備考」
	,SEIKYUSHO_SAKUSEI_YMD  DATE --「請求書作成年月日」
	,NYUKIN_YOTEI_YMD  DATE --「入金予定年月日」
	,SAIDAI_TAIRYU_TSUKISU  NUMBER(9,0) --「最大滞留月数」
	,SAISHO_TAIRYU_TSUKISU  NUMBER(9,0) --「最小滞留月数」
	,TIRY_SIKN_TNTSH_TSCHZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「滞留債権担当者通知済フラグ」
	,SEIKYUSHO_INJI_OKYAKUSAMA_NO  VARCHAR2(20) --「請求書印字お客様番号」
	,SEIKYUSHO_SOFUSAKI_KEISHO_KBN  CHAR(1) --「請求書送付先敬称区分」
	,CHOKI_TAIRYU_FURIKAEZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「長期滞留振替済フラグ」
	,HASAN_KOSEI_FURIKAEZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「破産更生振替済フラグ」
	,KSHDOR_SNSHTS_FRKEZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「貸倒損失振替済フラグ」
	,SEIKYUSAKIBETSU_TEMPLATE_SN  CHAR(5) --「請求先別テンプレート連番」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3735W_PK PRIMARY KEY(
	 SEIKYUSHO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3735W_TBL IS '売掛債権日次請求書ワークバックアップ'
/

COMMENT ON COLUMN ED3735W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_NO IS '請求書番号'
/
COMMENT ON COLUMN ED3735W_TBL.TAIRYU_SAIKEN_ID IS '滞留債権ＩＤ'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_STATUS_KBN IS '請求書ステータス区分'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYU_KANRI_JIGYOSHO_CD IS '請求管理事業所コード'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYU_KANRI_JIGYOSHO_NM IS '請求管理事業所名称'
/
COMMENT ON COLUMN ED3735W_TBL.SIKY_KNR_JGYSH_TNT_SHIN_NM IS '請求管理事業所担当社員氏名'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_SOFUSAKI_YUBIN_NO IS '請求書送付先郵便番号'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_SOFUSAKI_JUSHO_1 IS '請求書送付先住所１'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_SOFUSAKI_JUSHO_2 IS '請求書送付先住所２'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_SOFUSAKI_JUSHO_3 IS '請求書送付先住所３'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_SOFUSAKI_JUSHO_4 IS '請求書送付先住所４'
/
COMMENT ON COLUMN ED3735W_TBL.SIKYSK_TRHKSKI_SISHK_NM_1 IS '請求先取引先正式名称１'
/
COMMENT ON COLUMN ED3735W_TBL.SIKYSK_TRHKSKI_SISHK_NM_2 IS '請求先取引先正式名称２'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_ATENA_NM_1 IS '請求書宛名名称１'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_ATENA_NM_2 IS '請求書宛名名称２'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_ATENA_NM_3 IS '請求書宛名名称３'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_ATENA_NM_4 IS '請求書宛名名称４'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_ATENA_NM_5 IS '請求書宛名名称５'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_HASSO_HOHO_KBN IS '請求書発送方法区分'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_HAKKO_HOHO_KBN IS '請求書発行方法区分'
/
COMMENT ON COLUMN ED3735W_TBL.SHITEI_SEIKYUSHO_SHOSHIKI_CD IS '指定請求書書式コード'
/
COMMENT ON COLUMN ED3735W_TBL.SHITEI_SEIKYUSHO_SHOSHIKI_NM IS '指定請求書書式名称'
/
COMMENT ON COLUMN ED3735W_TBL.DAIHYO_SEIKYUSHO_TEKIYO IS '代表請求書摘要'
/
COMMENT ON COLUMN ED3735W_TBL.DAIHYO_SEIKYUSHO_BIKO IS '代表請求書備考'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_SAKUSEI_YMD IS '請求書作成年月日'
/
COMMENT ON COLUMN ED3735W_TBL.NYUKIN_YOTEI_YMD IS '入金予定年月日'
/
COMMENT ON COLUMN ED3735W_TBL.SAIDAI_TAIRYU_TSUKISU IS '最大滞留月数'
/
COMMENT ON COLUMN ED3735W_TBL.SAISHO_TAIRYU_TSUKISU IS '最小滞留月数'
/
COMMENT ON COLUMN ED3735W_TBL.TIRY_SIKN_TNTSH_TSCHZM_FLG IS '滞留債権担当者通知済フラグ'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_INJI_OKYAKUSAMA_NO IS '請求書印字お客様番号'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSHO_SOFUSAKI_KEISHO_KBN IS '請求書送付先敬称区分'
/
COMMENT ON COLUMN ED3735W_TBL.CHOKI_TAIRYU_FURIKAEZUMI_FLG IS '長期滞留振替済フラグ'
/
COMMENT ON COLUMN ED3735W_TBL.HASAN_KOSEI_FURIKAEZUMI_FLG IS '破産更生振替済フラグ'
/
COMMENT ON COLUMN ED3735W_TBL.KSHDOR_SNSHTS_FRKEZM_FLG IS '貸倒損失振替済フラグ'
/
COMMENT ON COLUMN ED3735W_TBL.SEIKYUSAKIBETSU_TEMPLATE_SN IS '請求先別テンプレート連番'
/
COMMENT ON COLUMN ED3735W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3735W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3735W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3735W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3735W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3735W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3735W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3735W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3735W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3735W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3735W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3735W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
