/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3733W_TBL.sql
-- 物理名：ED3733W_TBL
-- 論理名：営業債権残高ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3733W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3733W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TAISHO_YM  CHAR(6) NOT NULL --「対象年月」
	,EIGYO_SAIKEN_ZANDAKA_SN  CHAR(14) NOT NULL --「営業債権残高連番」
	,SAIKEN_DATA_SAKUSEIMOTO_KBN  CHAR(1) DEFAULT '0' NOT NULL --「債権データ作成元区分」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「受注契約変更番号」
	,SEIKYU_SHIHARAI_CD  CHAR(3) --「請求支払コード」
	,JIGYO_SEGMENT_CD  CHAR(3) --「事業セグメントコード」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) --「請求先取引先コード」
	,SEIKYUSHO_TEMPLATE_NO  CHAR(14) --「請求書テンプレート番号」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,URIAGE_KEIJO_SHUBETSU_KBN  CHAR(2) NOT NULL --「売上計上種別区分」
	,SEIKYU_KANRI_MEISAI_NO  CHAR(14) --「請求管理明細番号」
	,SEIKYUSHO_NO  CHAR(14) --「請求書番号」
	,SEIKYUSHO_MEISAI_SN  CHAR(14) --「請求書明細連番」
	,GASSAN_UCHIWAKE_MEISAI_SN  CHAR(14) --「合算内訳明細連番」
	,URIAGE_NO  CHAR(14) --「売上番号」
	,ZEIKOMI_SEIKYU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「税込請求金額」
	,NYUKINZUMI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「入金済金額」
	,URIKAKE_SAIKEN_ZANDAKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売掛債権残高金額」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3733W_PK PRIMARY KEY(
	 TAISHO_YM
	,  EIGYO_SAIKEN_ZANDAKA_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3733W_TBL IS '営業債権残高ワーク'
/

COMMENT ON COLUMN ED3733W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3733W_TBL.TAISHO_YM IS '対象年月'
/
COMMENT ON COLUMN ED3733W_TBL.EIGYO_SAIKEN_ZANDAKA_SN IS '営業債権残高連番'
/
COMMENT ON COLUMN ED3733W_TBL.SAIKEN_DATA_SAKUSEIMOTO_KBN IS '債権データ作成元区分'
/
COMMENT ON COLUMN ED3733W_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED3733W_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED3733W_TBL.SEIKYU_SHIHARAI_CD IS '請求支払コード'
/
COMMENT ON COLUMN ED3733W_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED3733W_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED3733W_TBL.SEIKYUSHO_TEMPLATE_NO IS '請求書テンプレート番号'
/
COMMENT ON COLUMN ED3733W_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED3733W_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED3733W_TBL.URIAGE_KEIJO_SHUBETSU_KBN IS '売上計上種別区分'
/
COMMENT ON COLUMN ED3733W_TBL.SEIKYU_KANRI_MEISAI_NO IS '請求管理明細番号'
/
COMMENT ON COLUMN ED3733W_TBL.SEIKYUSHO_NO IS '請求書番号'
/
COMMENT ON COLUMN ED3733W_TBL.SEIKYUSHO_MEISAI_SN IS '請求書明細連番'
/
COMMENT ON COLUMN ED3733W_TBL.GASSAN_UCHIWAKE_MEISAI_SN IS '合算内訳明細連番'
/
COMMENT ON COLUMN ED3733W_TBL.URIAGE_NO IS '売上番号'
/
COMMENT ON COLUMN ED3733W_TBL.ZEIKOMI_SEIKYU_AMT IS '税込請求金額'
/
COMMENT ON COLUMN ED3733W_TBL.NYUKINZUMI_AMT IS '入金済金額'
/
COMMENT ON COLUMN ED3733W_TBL.URIKAKE_SAIKEN_ZANDAKA_AMT IS '売掛債権残高金額'
/
COMMENT ON COLUMN ED3733W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3733W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3733W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3733W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3733W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3733W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3733W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3733W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3733W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3733W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3733W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3733W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
