/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3717T_TBL.sql
-- 物理名：ED3717T_TBL
-- 論理名：営業外債権残高テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3717T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3717T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TAISHO_YM  CHAR(6) NOT NULL --「対象年月」
	,EIGYOGAI_SHUEKI_SEIKYU_JOHO_NO  CHAR(14) NOT NULL --「営業外収益請求情報番号」
	,EIGYGI_SHEK_SIKYSH_MISI_SN  CHAR(14) NOT NULL --「営業外収益請求書明細連番」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) --「請求先取引先コード」
	,EIGYOGAI_SEIKYUSHO_STATUS_KBN  CHAR(2) NOT NULL --「営業外請求書ステータス区分」
	,SEIKYU_SHIHARAI_CD  CHAR(3) --「請求支払コード」
	,JIGYO_SEGMENT_CD  CHAR(3) --「事業セグメントコード」
	,SHIWAKE_KEIJO_JIGYOSHO_CD  CHAR(6) --「仕訳計上事業所コード」
	,EIGYOGAI_SHUEKI_KEIJO_YMD  DATE --「営業外収益計上年月日」
	,EIGYOGAI_SHUEKI_KEIJOZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「営業外収益計上済フラグ」
	,SEIKYUSHO_NO  CHAR(14) --「請求書番号」
	,SEIKYUSHO_MEISAI_SN  CHAR(14) --「請求書明細連番」
	,SEIKYUSHO_STATUS_KBN  CHAR(2) --「請求書ステータス区分」
	,SEIKYUSHO_MEISAI_STATUS_KBN  CHAR(1) --「請求書明細ステータス区分」
	,ZEIKOMI_SEIKYU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「税込請求金額」
	,NYUKINZUMI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「入金済金額」
	,EIGYOGAI_SAIKEN_ZANDAKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「営業外債権残高金額」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3717T_PK PRIMARY KEY(
	 TAISHO_YM
	,  EIGYOGAI_SHUEKI_SEIKYU_JOHO_NO
	,  EIGYGI_SHEK_SIKYSH_MISI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3717T_TBL IS '営業外債権残高テーブル'
/

COMMENT ON COLUMN ED3717T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3717T_TBL.TAISHO_YM IS '対象年月'
/
COMMENT ON COLUMN ED3717T_TBL.EIGYOGAI_SHUEKI_SEIKYU_JOHO_NO IS '営業外収益請求情報番号'
/
COMMENT ON COLUMN ED3717T_TBL.EIGYGI_SHEK_SIKYSH_MISI_SN IS '営業外収益請求書明細連番'
/
COMMENT ON COLUMN ED3717T_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED3717T_TBL.EIGYOGAI_SEIKYUSHO_STATUS_KBN IS '営業外請求書ステータス区分'
/
COMMENT ON COLUMN ED3717T_TBL.SEIKYU_SHIHARAI_CD IS '請求支払コード'
/
COMMENT ON COLUMN ED3717T_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED3717T_TBL.SHIWAKE_KEIJO_JIGYOSHO_CD IS '仕訳計上事業所コード'
/
COMMENT ON COLUMN ED3717T_TBL.EIGYOGAI_SHUEKI_KEIJO_YMD IS '営業外収益計上年月日'
/
COMMENT ON COLUMN ED3717T_TBL.EIGYOGAI_SHUEKI_KEIJOZUMI_FLG IS '営業外収益計上済フラグ'
/
COMMENT ON COLUMN ED3717T_TBL.SEIKYUSHO_NO IS '請求書番号'
/
COMMENT ON COLUMN ED3717T_TBL.SEIKYUSHO_MEISAI_SN IS '請求書明細連番'
/
COMMENT ON COLUMN ED3717T_TBL.SEIKYUSHO_STATUS_KBN IS '請求書ステータス区分'
/
COMMENT ON COLUMN ED3717T_TBL.SEIKYUSHO_MEISAI_STATUS_KBN IS '請求書明細ステータス区分'
/
COMMENT ON COLUMN ED3717T_TBL.ZEIKOMI_SEIKYU_AMT IS '税込請求金額'
/
COMMENT ON COLUMN ED3717T_TBL.NYUKINZUMI_AMT IS '入金済金額'
/
COMMENT ON COLUMN ED3717T_TBL.EIGYOGAI_SAIKEN_ZANDAKA_AMT IS '営業外債権残高金額'
/
COMMENT ON COLUMN ED3717T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3717T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3717T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3717T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3717T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3717T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3717T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3717T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3717T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3717T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3717T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3717T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
