/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3807T_TBL.sql
-- 物理名：ED3807T_TBL
-- 論理名：売上受注料金区分テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3807T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3807T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,URIAGE_RYOKIN_KBN_NO  CHAR(14) NOT NULL --「売上料金区分番号」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,URIAGE_KEIJO_SHUBETSU_KBN  CHAR(2) NOT NULL --「売上計上種別区分」
	,RYOKIN_KBN  CHAR(5) NOT NULL --「料金区分」
	,RYOKIN_SHOSAI_DAIBUNRUI_KBN  CHAR(10) --「料金詳細大分類区分」
	,RYOKIN_SHOSAI_CHUBUNRUI_KBN  CHAR(10) --「料金詳細中分類区分」
	,KEIYAKU_CHOKI_RINJI_KBN  CHAR(1) NOT NULL --「契約長期臨時区分」
	,CHK_KIYK_RYKN_KIZK_SIKY_KBN  CHAR(1) DEFAULT '0' NOT NULL --「長期契約料金継続請求区分」
	,SEIKYU_SHIHARAI_CD  CHAR(3) --「請求支払コード」
	,SHOHIZEI_KBN  CHAR(1) NOT NULL --「消費税区分」
	,SHOHI_ZEIRITSU_CD  CHAR(2) --「消費税率コード」
	,KEIKA_SHOCHI_KAISHI_YMD  DATE --「経過処置開始年月日」
	,KEIKA_SHOCHI_SHURYO_YMD  DATE --「経過処置終了年月日」
	,RONRI_SAKUJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「論理削除フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3807T_PK PRIMARY KEY(
	 URIAGE_RYOKIN_KBN_NO
	,  JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3807T_TBL IS '売上受注料金区分テーブル'
/

COMMENT ON COLUMN ED3807T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3807T_TBL.URIAGE_RYOKIN_KBN_NO IS '売上料金区分番号'
/
COMMENT ON COLUMN ED3807T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED3807T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED3807T_TBL.URIAGE_KEIJO_SHUBETSU_KBN IS '売上計上種別区分'
/
COMMENT ON COLUMN ED3807T_TBL.RYOKIN_KBN IS '料金区分'
/
COMMENT ON COLUMN ED3807T_TBL.RYOKIN_SHOSAI_DAIBUNRUI_KBN IS '料金詳細大分類区分'
/
COMMENT ON COLUMN ED3807T_TBL.RYOKIN_SHOSAI_CHUBUNRUI_KBN IS '料金詳細中分類区分'
/
COMMENT ON COLUMN ED3807T_TBL.KEIYAKU_CHOKI_RINJI_KBN IS '契約長期臨時区分'
/
COMMENT ON COLUMN ED3807T_TBL.CHK_KIYK_RYKN_KIZK_SIKY_KBN IS '長期契約料金継続請求区分'
/
COMMENT ON COLUMN ED3807T_TBL.SEIKYU_SHIHARAI_CD IS '請求支払コード'
/
COMMENT ON COLUMN ED3807T_TBL.SHOHIZEI_KBN IS '消費税区分'
/
COMMENT ON COLUMN ED3807T_TBL.SHOHI_ZEIRITSU_CD IS '消費税率コード'
/
COMMENT ON COLUMN ED3807T_TBL.KEIKA_SHOCHI_KAISHI_YMD IS '経過処置開始年月日'
/
COMMENT ON COLUMN ED3807T_TBL.KEIKA_SHOCHI_SHURYO_YMD IS '経過処置終了年月日'
/
COMMENT ON COLUMN ED3807T_TBL.RONRI_SAKUJO_FLG IS '論理削除フラグ'
/
COMMENT ON COLUMN ED3807T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3807T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3807T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3807T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3807T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3807T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3807T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3807T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3807T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3807T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3807T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3807T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
