/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3814W_TBL.sql
-- 物理名：ED3814W_TBL
-- 論理名：売上予定振分ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3814W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3814W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,OYA_JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「親受注契約変更番号」
	,JUCHU_KANRI_NO_KBN  CHAR(1) NOT NULL --「受注管理番号区分」
	,KEIYAKU_CHOKI_RINJI_KBN  CHAR(1) NOT NULL --「契約長期臨時区分」
	,JUCHU_JIGYOSHO_CD  CHAR(6) NOT NULL --「受注事業所コード」
	,JUCHU_TANTO_SHAIN_NO  VARCHAR2(8) NOT NULL --「受注担当社員番号」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) NOT NULL --「契約先取引先コード」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) NOT NULL --「請求先取引先コード」
	,SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,GYOMU_KAISHI_YMD  DATE --「業務開始年月日」
	,GYOMU_SHURYO_YMD  DATE --「業務終了年月日」
	,JUCHU_SHORI_KBN  CHAR(2) NOT NULL --「受注処理区分」
	,SOKAN_BOSAI_SHUKI_TANI_KBN  CHAR(2) --「綜管防災周期単位区分」
	,SEIKYU_SHIME_D  CHAR(2) --「請求締日」
	,SHIHARAI_JOKEN_KBN  CHAR(1) NOT NULL --「支払条件区分」
	,SHIHARAI_D  CHAR(2) NOT NULL --「支払日」
	,TOSHO_NYUKIN_YOTEI_YMD  DATE --「当初入金予定年月日」
	,TAIRYU_TSUKISU  NUMBER(9,0) --「滞留月数」
	,FURIWAKE_NO  CHAR(2) --「振分番号」
	,URAG_YTI_TRK_SHRZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「売上予定登録処理済フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3814W_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3814W_TBL IS '売上予定振分ワーク'
/

COMMENT ON COLUMN ED3814W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3814W_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED3814W_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED3814W_TBL.OYA_JUCHU_KEIYAKU_HENKO_NO IS '親受注契約変更番号'
/
COMMENT ON COLUMN ED3814W_TBL.JUCHU_KANRI_NO_KBN IS '受注管理番号区分'
/
COMMENT ON COLUMN ED3814W_TBL.KEIYAKU_CHOKI_RINJI_KBN IS '契約長期臨時区分'
/
COMMENT ON COLUMN ED3814W_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED3814W_TBL.JUCHU_TANTO_SHAIN_NO IS '受注担当社員番号'
/
COMMENT ON COLUMN ED3814W_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED3814W_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED3814W_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED3814W_TBL.GYOMU_KAISHI_YMD IS '業務開始年月日'
/
COMMENT ON COLUMN ED3814W_TBL.GYOMU_SHURYO_YMD IS '業務終了年月日'
/
COMMENT ON COLUMN ED3814W_TBL.JUCHU_SHORI_KBN IS '受注処理区分'
/
COMMENT ON COLUMN ED3814W_TBL.SOKAN_BOSAI_SHUKI_TANI_KBN IS '綜管防災周期単位区分'
/
COMMENT ON COLUMN ED3814W_TBL.SEIKYU_SHIME_D IS '請求締日'
/
COMMENT ON COLUMN ED3814W_TBL.SHIHARAI_JOKEN_KBN IS '支払条件区分'
/
COMMENT ON COLUMN ED3814W_TBL.SHIHARAI_D IS '支払日'
/
COMMENT ON COLUMN ED3814W_TBL.TOSHO_NYUKIN_YOTEI_YMD IS '当初入金予定年月日'
/
COMMENT ON COLUMN ED3814W_TBL.TAIRYU_TSUKISU IS '滞留月数'
/
COMMENT ON COLUMN ED3814W_TBL.FURIWAKE_NO IS '振分番号'
/
COMMENT ON COLUMN ED3814W_TBL.URAG_YTI_TRK_SHRZM_FLG IS '売上予定登録処理済フラグ'
/
COMMENT ON COLUMN ED3814W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3814W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3814W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3814W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3814W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3814W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3814W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3814W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3814W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3814W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3814W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3814W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
