/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3809W_TBL.sql
-- 物理名：ED3809W_TBL
-- 論理名：売上実績ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3809W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3809W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,URIAGE_JISSEKI_ID  CHAR(16) NOT NULL --「売上実績ＩＤ」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「受注契約変更番号」
	,SEIKYU_SHIHARAI_CD  CHAR(3) --「請求支払コード」
	,URIAGE_NO  CHAR(14) --「売上番号」
	,URIAGE_KEIJO_ZEIKOMI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上計上税込金額」
	,URIAGE_KEIJO_SEIKYUZUMI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上計上請求済金額」
	,TAISHO_YMD  DATE --「対象年月日」
	,TAISHO_EKIMU_KAISHI_YMD  DATE --「対象役務開始年月日」
	,TAISHO_EKIMU_SHURYO_YMD  DATE --「対象役務終了年月日」
	,JIGYO_SEGMENT_CD  CHAR(3) --「事業セグメントコード」
	,JISSHI_JIGYOSHO_CD  CHAR(6) --「実施事業所コード」
	,URIAGE_SEIKYU_TORIKESHI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「売上請求取消フラグ」
	,SEIKYUSHO_URIAGE_HIMOZUKE_NO  CHAR(14) --「請求書売上紐付番号」
	,DATA_TORIKOMIZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「データ取込済フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3809W_PK PRIMARY KEY(
	 URIAGE_JISSEKI_ID
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3809W_TBL IS '売上実績ワーク'
/

COMMENT ON COLUMN ED3809W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3809W_TBL.URIAGE_JISSEKI_ID IS '売上実績ＩＤ'
/
COMMENT ON COLUMN ED3809W_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED3809W_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED3809W_TBL.SEIKYU_SHIHARAI_CD IS '請求支払コード'
/
COMMENT ON COLUMN ED3809W_TBL.URIAGE_NO IS '売上番号'
/
COMMENT ON COLUMN ED3809W_TBL.URIAGE_KEIJO_ZEIKOMI_AMT IS '売上計上税込金額'
/
COMMENT ON COLUMN ED3809W_TBL.URIAGE_KEIJO_SEIKYUZUMI_AMT IS '売上計上請求済金額'
/
COMMENT ON COLUMN ED3809W_TBL.TAISHO_YMD IS '対象年月日'
/
COMMENT ON COLUMN ED3809W_TBL.TAISHO_EKIMU_KAISHI_YMD IS '対象役務開始年月日'
/
COMMENT ON COLUMN ED3809W_TBL.TAISHO_EKIMU_SHURYO_YMD IS '対象役務終了年月日'
/
COMMENT ON COLUMN ED3809W_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED3809W_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED3809W_TBL.URIAGE_SEIKYU_TORIKESHI_FLG IS '売上請求取消フラグ'
/
COMMENT ON COLUMN ED3809W_TBL.SEIKYUSHO_URIAGE_HIMOZUKE_NO IS '請求書売上紐付番号'
/
COMMENT ON COLUMN ED3809W_TBL.DATA_TORIKOMIZUMI_FLG IS 'データ取込済フラグ'
/
COMMENT ON COLUMN ED3809W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3809W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3809W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3809W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3809W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3809W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3809W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3809W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3809W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3809W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3809W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3809W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
