/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3958M_TBL.sql
-- 物理名：ED3958M_TBL
-- 論理名：入金決済代行会社マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3958M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3958M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,NYUKIN_KESSAI_DAIKO_KAISHA_CD  CHAR(8) NOT NULL --「入金決済代行会社コード」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,NYUKIN_KESSAI_DAIKO_KAISHA_KBN  CHAR(2) NOT NULL --「入金決済代行会社区分」
	,NYUKIN_KESSAI_DAIKO_KAISHA_NM  VARCHAR2(40) --「入金決済代行会社名称」
	,KESSAI_DAIKO_ITAKUSHA_CD  VARCHAR2(20) --「決済代行委託者コード」
	,KESSAI_DAIKO_ITAKUSHA_KN_NM  VARCHAR2(40) --「決済代行委託者カナ名称」
	,KOZA_FURIKAE_KOKYAKU_CD  VARCHAR2(20) --「口座振替顧客コード」
	,KOZA_FURIKAE_FILE_SHUBETSU_KBN  CHAR(1) --「口座振替ファイル種別区分」
	,SEIKYU_ITAKU_SAGYO_JIGYOSHO_CD  CHAR(6) --「請求委託作業事業所コード」
	,NYUKIN_JIGYOSHO_CD  CHAR(6) --「入金事業所コード」
	,JISHA_KOZA_CD  CHAR(4) --「自社口座コード」
	,CREDIT_ITAKU_KAISHA_CD  VARCHAR2(3) --「クレジット委託会社コード」
	,CREDIT_KAMEITEN_NO  CHAR(15) --「クレジット加盟店番号」
	,CREDIT_CARD_KAISHA_CD  VARCHAR2(20) --「クレジットカード会社コード」
	,SIKY_ITK_DATA_HKWTSH_KJN_NISSU  NUMBER(9,0) --「請求委託データ引渡基準日数」
	,FURIKAE_YM_SHUSEI_KIGEN_NISSU  NUMBER(9,0) --「振替年月修正期限日数」
	,SEIKYU_KEITAI_KBN  CHAR(2) --「請求形態区分」
	,SHIHARAIZUKI_KBN  CHAR(1) --「支払月区分」
	,SHIHARAI_JOKEN_KBN  CHAR(1) --「支払条件区分」
	,SHIHARAI_D  CHAR(2) --「支払日」
	,SIKY_ITK_DATA_HKWTSH_D  CHAR(2) --「請求委託データ引渡日」
	,SHNK_SIKYSK_TRKJ_SNTK_FK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「新規請求先登録時選択不可フラグ」
	,TAIRYU_SAIKEN_YUYO_NISSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「滞留債権猶予日数」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3958M_PK PRIMARY KEY(
	 NYUKIN_KESSAI_DAIKO_KAISHA_CD
	,  KAISHA_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3958M_TBL IS '入金決済代行会社マスタ'
/

COMMENT ON COLUMN ED3958M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3958M_TBL.NYUKIN_KESSAI_DAIKO_KAISHA_CD IS '入金決済代行会社コード'
/
COMMENT ON COLUMN ED3958M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED3958M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED3958M_TBL.NYUKIN_KESSAI_DAIKO_KAISHA_KBN IS '入金決済代行会社区分'
/
COMMENT ON COLUMN ED3958M_TBL.NYUKIN_KESSAI_DAIKO_KAISHA_NM IS '入金決済代行会社名称'
/
COMMENT ON COLUMN ED3958M_TBL.KESSAI_DAIKO_ITAKUSHA_CD IS '決済代行委託者コード'
/
COMMENT ON COLUMN ED3958M_TBL.KESSAI_DAIKO_ITAKUSHA_KN_NM IS '決済代行委託者カナ名称'
/
COMMENT ON COLUMN ED3958M_TBL.KOZA_FURIKAE_KOKYAKU_CD IS '口座振替顧客コード'
/
COMMENT ON COLUMN ED3958M_TBL.KOZA_FURIKAE_FILE_SHUBETSU_KBN IS '口座振替ファイル種別区分'
/
COMMENT ON COLUMN ED3958M_TBL.SEIKYU_ITAKU_SAGYO_JIGYOSHO_CD IS '請求委託作業事業所コード'
/
COMMENT ON COLUMN ED3958M_TBL.NYUKIN_JIGYOSHO_CD IS '入金事業所コード'
/
COMMENT ON COLUMN ED3958M_TBL.JISHA_KOZA_CD IS '自社口座コード'
/
COMMENT ON COLUMN ED3958M_TBL.CREDIT_ITAKU_KAISHA_CD IS 'クレジット委託会社コード'
/
COMMENT ON COLUMN ED3958M_TBL.CREDIT_KAMEITEN_NO IS 'クレジット加盟店番号'
/
COMMENT ON COLUMN ED3958M_TBL.CREDIT_CARD_KAISHA_CD IS 'クレジットカード会社コード'
/
COMMENT ON COLUMN ED3958M_TBL.SIKY_ITK_DATA_HKWTSH_KJN_NISSU IS '請求委託データ引渡基準日数'
/
COMMENT ON COLUMN ED3958M_TBL.FURIKAE_YM_SHUSEI_KIGEN_NISSU IS '振替年月修正期限日数'
/
COMMENT ON COLUMN ED3958M_TBL.SEIKYU_KEITAI_KBN IS '請求形態区分'
/
COMMENT ON COLUMN ED3958M_TBL.SHIHARAIZUKI_KBN IS '支払月区分'
/
COMMENT ON COLUMN ED3958M_TBL.SHIHARAI_JOKEN_KBN IS '支払条件区分'
/
COMMENT ON COLUMN ED3958M_TBL.SHIHARAI_D IS '支払日'
/
COMMENT ON COLUMN ED3958M_TBL.SIKY_ITK_DATA_HKWTSH_D IS '請求委託データ引渡日'
/
COMMENT ON COLUMN ED3958M_TBL.SHNK_SIKYSK_TRKJ_SNTK_FK_FLG IS '新規請求先登録時選択不可フラグ'
/
COMMENT ON COLUMN ED3958M_TBL.TAIRYU_SAIKEN_YUYO_NISSU IS '滞留債権猶予日数'
/
COMMENT ON COLUMN ED3958M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3958M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3958M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3958M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3958M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3958M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3958M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3958M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3958M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3958M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3958M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3958M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
