/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3956M_TBL.sql
-- 物理名：ED3956M_TBL
-- 論理名：自動消込ルールマスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3956M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3956M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,HOJINKAKU_JOGAI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「法人格除外フラグ」
	,KESHIKOMI_KYOYO_SABUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「消込許容差分金額」
	,KESHIKOMI_KYOYO_SABUN_NISSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「消込許容差分日数」
	,NYUKIN_KAGEN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「入金下限金額」
	,SEIKYU_KAGEN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「請求下限金額」
	,ZNG_N_EIGYB_GROUP_KSHKM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「前後Ｎ営業日グループ消込フラグ」
	,GROUP_KESHIKOMI_SHUKEI_NISSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「グループ消込集計日数」
	,MEHTTSK_GROUP_KSHKM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「前一月グループ消込フラグ」
	,ZNG_HTTSK_GROUP_KSHKM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「前後一月グループ消込フラグ」
	,NYKN_IZN_GROUP_KSHKM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「入金以前グループ消込フラグ」
	,NKNG_HTTK_IZN_GROUP_KSKM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「入金後一月以前グループ消込フラグ」
	,MUKIGEN_GROUP_KESHIKOMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「無期限グループ消込フラグ」
	,GTCH_SIKY_FKSJ_KH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「合致請求複数時候補フラグ」
	,GTCH_NYKN_FKSJ_KH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「合致入金複数時候補フラグ」
	,FURYO_SAIKEN_SONZAIJI_KOHO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「不良債権存在時候補フラグ」
	,SIKY_NYKN_AMT_KGNJ_KH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「請求入金金額下限時候補フラグ」
	,TORIKESHI_SEIKYU_KOHO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「取消請求候補フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3956M_PK PRIMARY KEY(
	 KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3956M_TBL IS '自動消込ルールマスタ'
/

COMMENT ON COLUMN ED3956M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3956M_TBL.HOJINKAKU_JOGAI_FLG IS '法人格除外フラグ'
/
COMMENT ON COLUMN ED3956M_TBL.KESHIKOMI_KYOYO_SABUN_AMT IS '消込許容差分金額'
/
COMMENT ON COLUMN ED3956M_TBL.KESHIKOMI_KYOYO_SABUN_NISSU IS '消込許容差分日数'
/
COMMENT ON COLUMN ED3956M_TBL.NYUKIN_KAGEN_AMT IS '入金下限金額'
/
COMMENT ON COLUMN ED3956M_TBL.SEIKYU_KAGEN_AMT IS '請求下限金額'
/
COMMENT ON COLUMN ED3956M_TBL.ZNG_N_EIGYB_GROUP_KSHKM_FLG IS '前後Ｎ営業日グループ消込フラグ'
/
COMMENT ON COLUMN ED3956M_TBL.GROUP_KESHIKOMI_SHUKEI_NISSU IS 'グループ消込集計日数'
/
COMMENT ON COLUMN ED3956M_TBL.MEHTTSK_GROUP_KSHKM_FLG IS '前一月グループ消込フラグ'
/
COMMENT ON COLUMN ED3956M_TBL.ZNG_HTTSK_GROUP_KSHKM_FLG IS '前後一月グループ消込フラグ'
/
COMMENT ON COLUMN ED3956M_TBL.NYKN_IZN_GROUP_KSHKM_FLG IS '入金以前グループ消込フラグ'
/
COMMENT ON COLUMN ED3956M_TBL.NKNG_HTTK_IZN_GROUP_KSKM_FLG IS '入金後一月以前グループ消込フラグ'
/
COMMENT ON COLUMN ED3956M_TBL.MUKIGEN_GROUP_KESHIKOMI_FLG IS '無期限グループ消込フラグ'
/
COMMENT ON COLUMN ED3956M_TBL.GTCH_SIKY_FKSJ_KH_FLG IS '合致請求複数時候補フラグ'
/
COMMENT ON COLUMN ED3956M_TBL.GTCH_NYKN_FKSJ_KH_FLG IS '合致入金複数時候補フラグ'
/
COMMENT ON COLUMN ED3956M_TBL.FURYO_SAIKEN_SONZAIJI_KOHO_FLG IS '不良債権存在時候補フラグ'
/
COMMENT ON COLUMN ED3956M_TBL.SIKY_NYKN_AMT_KGNJ_KH_FLG IS '請求入金金額下限時候補フラグ'
/
COMMENT ON COLUMN ED3956M_TBL.TORIKESHI_SEIKYU_KOHO_FLG IS '取消請求候補フラグ'
/
COMMENT ON COLUMN ED3956M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3956M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3956M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3956M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3956M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3956M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3956M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3956M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3956M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3956M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3956M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3956M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
