/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3904T_TBL.sql
-- 物理名：ED3904T_TBL
-- 論理名：未収入金残高月次テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3904T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3904T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TAISHO_YM  CHAR(6) NOT NULL --「対象年月」
	,NYUKIN_KESSAI_DAIKO_KAISHA_CD  CHAR(8) NOT NULL --「入金決済代行会社コード」
	,NYUKIN_YOTEI_YMD  DATE NOT NULL --「入金予定年月日」
	,KESSAI_DAIKO_FURIKAE_YMD  DATE --「決済代行振替年月日」
	,KSSI_DIK_FRKEZM_MSHNY_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「決済代行振替済未収入金額」
	,NYUKIN_JIGYOSHO_CD  CHAR(6) --「入金事業所コード」
	,JISHA_KOZA_CD  CHAR(4) --「自社口座コード」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3904T_PK PRIMARY KEY(
	 TAISHO_YM
	,  NYUKIN_KESSAI_DAIKO_KAISHA_CD
	,  NYUKIN_YOTEI_YMD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3904T_TBL IS '未収入金残高月次テーブル'
/

COMMENT ON COLUMN ED3904T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3904T_TBL.TAISHO_YM IS '対象年月'
/
COMMENT ON COLUMN ED3904T_TBL.NYUKIN_KESSAI_DAIKO_KAISHA_CD IS '入金決済代行会社コード'
/
COMMENT ON COLUMN ED3904T_TBL.NYUKIN_YOTEI_YMD IS '入金予定年月日'
/
COMMENT ON COLUMN ED3904T_TBL.KESSAI_DAIKO_FURIKAE_YMD IS '決済代行振替年月日'
/
COMMENT ON COLUMN ED3904T_TBL.KSSI_DIK_FRKEZM_MSHNY_AMT IS '決済代行振替済未収入金額'
/
COMMENT ON COLUMN ED3904T_TBL.NYUKIN_JIGYOSHO_CD IS '入金事業所コード'
/
COMMENT ON COLUMN ED3904T_TBL.JISHA_KOZA_CD IS '自社口座コード'
/
COMMENT ON COLUMN ED3904T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3904T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3904T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3904T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3904T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3904T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3904T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3904T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3904T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3904T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3904T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3904T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
