/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3910T_TBL.sql
-- 物理名：ED3910T_TBL
-- 論理名：売掛債権契約月次テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3910T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3910T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TAISHO_YM  CHAR(6) NOT NULL --「対象年月」
	,URIKAKE_SAIKEN_ID  CHAR(14) NOT NULL --「売掛債権ＩＤ」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,SAIKEN_DATA_SAKUSEIMOTO_KBN  CHAR(1) NOT NULL --「債権データ作成元区分」
	,SEIKYUSHO_NO  CHAR(14) --「請求書番号」
	,SEIKYUSHO_MEISAI_SN  CHAR(14) --「請求書明細連番」
	,SEIKYU_KANRI_MEISAI_NO  CHAR(14) --「請求管理明細番号」
	,SEIKYU_SHIHARAI_CD  CHAR(3) --「請求支払コード」
	,URIAGE_NO  CHAR(14) --「売上番号」
	,TAIRYU_SAIKEN_ID  CHAR(14) --「滞留債権ＩＤ」
	,JUCHU_TANTO_SHAIN_NO  VARCHAR2(8) --「受注担当社員番号」
	,JUCHU_TANTOSHA_NM  VARCHAR2(60) --「受注担当者氏名」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,JUCHU_JIGYOSHO_NM  VARCHAR2(200) --「受注事業所名称」
	,JISSHI_JIGYOSHO_CD  CHAR(6) NOT NULL --「実施事業所コード」
	,JISSHI_JIGYOSHO_NM  VARCHAR2(200) --「実施事業所名称」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,KIYKSK_TRHKSK_SISHK_NM  VARCHAR2(50) --「契約先取引先正式名称」
	,TAISHOSAKI_CD  CHAR(9) NOT NULL --「対象先コード」
	,TAISHOSAKI_NM  VARCHAR2(40) --「対象先名称」
	,KEIYAKU_STATUS_KBN  CHAR(1) DEFAULT '0' NOT NULL --「契約ステータス区分」
	,KEIYAKU_CHOKI_RINJI_KBN  CHAR(1) DEFAULT '0' NOT NULL --「契約長期臨時区分」
	,SHOHIN_SERVICE_CD  CHAR(3) --「商品サービスコード」
	,SHOHIN_SERVICE_NM  VARCHAR2(60) --「商品サービス名称」
	,TORIKOMIMOTO_KBN  CHAR(2) DEFAULT '0' NOT NULL --「取込元区分」
	,JUCHU_TANTO_JIGYOSHO_CD  CHAR(6) --「受注担当者事業所コード」
	,JUCHU_TANTO_JIGYOSHO_NM  VARCHAR2(200) --「受注担当者事業所名称」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3910T_PK PRIMARY KEY(
	 TAISHO_YM
	,  URIKAKE_SAIKEN_ID
	,  JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	,  JISSHI_JIGYOSHO_CD
	,  TAISHOSAKI_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3910T_TBL IS '売掛債権契約月次テーブル'
/

COMMENT ON COLUMN ED3910T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3910T_TBL.TAISHO_YM IS '対象年月'
/
COMMENT ON COLUMN ED3910T_TBL.URIKAKE_SAIKEN_ID IS '売掛債権ＩＤ'
/
COMMENT ON COLUMN ED3910T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED3910T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED3910T_TBL.SAIKEN_DATA_SAKUSEIMOTO_KBN IS '債権データ作成元区分'
/
COMMENT ON COLUMN ED3910T_TBL.SEIKYUSHO_NO IS '請求書番号'
/
COMMENT ON COLUMN ED3910T_TBL.SEIKYUSHO_MEISAI_SN IS '請求書明細連番'
/
COMMENT ON COLUMN ED3910T_TBL.SEIKYU_KANRI_MEISAI_NO IS '請求管理明細番号'
/
COMMENT ON COLUMN ED3910T_TBL.SEIKYU_SHIHARAI_CD IS '請求支払コード'
/
COMMENT ON COLUMN ED3910T_TBL.URIAGE_NO IS '売上番号'
/
COMMENT ON COLUMN ED3910T_TBL.TAIRYU_SAIKEN_ID IS '滞留債権ＩＤ'
/
COMMENT ON COLUMN ED3910T_TBL.JUCHU_TANTO_SHAIN_NO IS '受注担当社員番号'
/
COMMENT ON COLUMN ED3910T_TBL.JUCHU_TANTOSHA_NM IS '受注担当者氏名'
/
COMMENT ON COLUMN ED3910T_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED3910T_TBL.JUCHU_JIGYOSHO_NM IS '受注事業所名称'
/
COMMENT ON COLUMN ED3910T_TBL.JISSHI_JIGYOSHO_CD IS '実施事業所コード'
/
COMMENT ON COLUMN ED3910T_TBL.JISSHI_JIGYOSHO_NM IS '実施事業所名称'
/
COMMENT ON COLUMN ED3910T_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED3910T_TBL.KIYKSK_TRHKSK_SISHK_NM IS '契約先取引先正式名称'
/
COMMENT ON COLUMN ED3910T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED3910T_TBL.TAISHOSAKI_NM IS '対象先名称'
/
COMMENT ON COLUMN ED3910T_TBL.KEIYAKU_STATUS_KBN IS '契約ステータス区分'
/
COMMENT ON COLUMN ED3910T_TBL.KEIYAKU_CHOKI_RINJI_KBN IS '契約長期臨時区分'
/
COMMENT ON COLUMN ED3910T_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED3910T_TBL.SHOHIN_SERVICE_NM IS '商品サービス名称'
/
COMMENT ON COLUMN ED3910T_TBL.TORIKOMIMOTO_KBN IS '取込元区分'
/
COMMENT ON COLUMN ED3910T_TBL.JUCHU_TANTO_JIGYOSHO_CD IS '受注担当者事業所コード'
/
COMMENT ON COLUMN ED3910T_TBL.JUCHU_TANTO_JIGYOSHO_NM IS '受注担当者事業所名称'
/
COMMENT ON COLUMN ED3910T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3910T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3910T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3910T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3910T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3910T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3910T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3910T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3910T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3910T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3910T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3910T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
