/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3903T_TBL.sql
-- 物理名：ED3903T_TBL
-- 論理名：貸倒実績率算定用債権残高月次テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3903T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3903T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TAISHO_YM  CHAR(6) NOT NULL --「対象年月」
	,ICHINENCHO_TAIRYU_SAIKEN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「一年超滞留債権金額」
	,TAMPO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「担保金額」
	,CHOKI_TAIRYU_SAIKEN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「長期滞留債権金額」
	,HASAN_KOSEI_SAIKEN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「破産更生債権金額」
	,SONSHITSU_SOTEI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「損失想定金額」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3903T_PK PRIMARY KEY(
	 TAISHO_YM
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3903T_TBL IS '貸倒実績率算定用債権残高月次テーブル'
/

COMMENT ON COLUMN ED3903T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3903T_TBL.TAISHO_YM IS '対象年月'
/
COMMENT ON COLUMN ED3903T_TBL.ICHINENCHO_TAIRYU_SAIKEN_AMT IS '一年超滞留債権金額'
/
COMMENT ON COLUMN ED3903T_TBL.TAMPO_AMT IS '担保金額'
/
COMMENT ON COLUMN ED3903T_TBL.CHOKI_TAIRYU_SAIKEN_AMT IS '長期滞留債権金額'
/
COMMENT ON COLUMN ED3903T_TBL.HASAN_KOSEI_SAIKEN_AMT IS '破産更生債権金額'
/
COMMENT ON COLUMN ED3903T_TBL.SONSHITSU_SOTEI_AMT IS '損失想定金額'
/
COMMENT ON COLUMN ED3903T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3903T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3903T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3903T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3903T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3903T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3903T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3903T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3903T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3903T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3903T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3903T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
