/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED3961M_TBL.sql
-- 物理名：ED3961M_TBL
-- 論理名：仮想口座マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED3961M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED3961M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KINYU_KIKAN_CD  CHAR(4) NOT NULL --「金融機関コード」
	,KINYU_KIKAN_SHITEN_CD  CHAR(3) NOT NULL --「金融機関支店コード」
	,KASO_KOZA_NO  CHAR(7) NOT NULL --「仮想口座番号」
	,KOZA_SHUBETSU_KBN  CHAR(1) NOT NULL --「口座種別区分」
	,KASO_KOZA_RIYO_KBN  CHAR(1) NOT NULL --「仮想口座利用区分」
	,KASO_KOZA_WARIATEZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「仮想口座割当済フラグ」
	,JISHA_KOZA_CD  CHAR(4) --「自社口座コード」
	,SEIKYUSAKI_TORIHIKISAKI_CD  CHAR(9) --「請求先取引先コード」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED3961M_PK PRIMARY KEY(
	 KINYU_KIKAN_CD
	,  KINYU_KIKAN_SHITEN_CD
	,  KASO_KOZA_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED3961M_TBL IS '仮想口座マスタ'
/

COMMENT ON COLUMN ED3961M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED3961M_TBL.KINYU_KIKAN_CD IS '金融機関コード'
/
COMMENT ON COLUMN ED3961M_TBL.KINYU_KIKAN_SHITEN_CD IS '金融機関支店コード'
/
COMMENT ON COLUMN ED3961M_TBL.KASO_KOZA_NO IS '仮想口座番号'
/
COMMENT ON COLUMN ED3961M_TBL.KOZA_SHUBETSU_KBN IS '口座種別区分'
/
COMMENT ON COLUMN ED3961M_TBL.KASO_KOZA_RIYO_KBN IS '仮想口座利用区分'
/
COMMENT ON COLUMN ED3961M_TBL.KASO_KOZA_WARIATEZUMI_FLG IS '仮想口座割当済フラグ'
/
COMMENT ON COLUMN ED3961M_TBL.JISHA_KOZA_CD IS '自社口座コード'
/
COMMENT ON COLUMN ED3961M_TBL.SEIKYUSAKI_TORIHIKISAKI_CD IS '請求先取引先コード'
/
COMMENT ON COLUMN ED3961M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED3961M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED3961M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED3961M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED3961M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED3961M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED3961M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED3961M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED3961M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED3961M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED3961M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED3961M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
