/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4005M_TBL.sql
-- 物理名：ED4005M_TBL
-- 論理名：支払条件マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4005M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4005M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SHIHARAI_JOKEN_CD  CHAR(5) NOT NULL --「支払条件コード」
	,SHIHARAI_JOKEN_NM  VARCHAR2(16) NOT NULL --「支払条件名称」
	,SHIHARAI_SHIME_D  CHAR(2) NOT NULL --「支払締日」
	,SHIHARAI_CYCLE_KBN  CHAR(1) NOT NULL --「支払サイクル区分」
	,SHIHARAI_D  CHAR(2) NOT NULL --「支払日」
	,SHIHARAIBI_IDO_KBN  CHAR(1) NOT NULL --「支払日移動区分」
	,SHKN_KMKY_KNJ_KMK_CD  VARCHAR2(12) NOT NULL --「資金科目用勘定科目コード」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4005M_PK PRIMARY KEY(
	 SHIHARAI_JOKEN_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4005M_TBL IS '支払条件マスタ'
/

COMMENT ON COLUMN ED4005M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4005M_TBL.SHIHARAI_JOKEN_CD IS '支払条件コード'
/
COMMENT ON COLUMN ED4005M_TBL.SHIHARAI_JOKEN_NM IS '支払条件名称'
/
COMMENT ON COLUMN ED4005M_TBL.SHIHARAI_SHIME_D IS '支払締日'
/
COMMENT ON COLUMN ED4005M_TBL.SHIHARAI_CYCLE_KBN IS '支払サイクル区分'
/
COMMENT ON COLUMN ED4005M_TBL.SHIHARAI_D IS '支払日'
/
COMMENT ON COLUMN ED4005M_TBL.SHIHARAIBI_IDO_KBN IS '支払日移動区分'
/
COMMENT ON COLUMN ED4005M_TBL.SHKN_KMKY_KNJ_KMK_CD IS '資金科目用勘定科目コード'
/
COMMENT ON COLUMN ED4005M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4005M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4005M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4005M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4005M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4005M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4005M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4005M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4005M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4005M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4005M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4005M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
