/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4106M_TBL.sql
-- 物理名：ED4106M_TBL
-- 論理名：商品サービス明細マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4106M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4106M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,JIGYO_SEGMENT_CD  CHAR(3) --「事業セグメントコード」
	,JSSH_JGYSH_GYM_SHBTS_KBN  CHAR(2) NOT NULL --「実施事業所業務種別区分」
	,SHN_SERVICE_MEISAI_CD  CHAR(3) --「商品サービス明細コード」
	,SHN_SRVC_MEISAI_SHTSRYK_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「商品サービス明細出力順」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4106M_PK PRIMARY KEY(
	 SHOHIN_SERVICE_CD
	,  JSSH_JGYSH_GYM_SHBTS_KBN
	,  KAISHA_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4106M_TBL IS '商品サービス明細マスタ'
/

COMMENT ON COLUMN ED4106M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4106M_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4106M_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED4106M_TBL.JSSH_JGYSH_GYM_SHBTS_KBN IS '実施事業所業務種別区分'
/
COMMENT ON COLUMN ED4106M_TBL.SHN_SERVICE_MEISAI_CD IS '商品サービス明細コード'
/
COMMENT ON COLUMN ED4106M_TBL.SHN_SRVC_MEISAI_SHTSRYK_JUN IS '商品サービス明細出力順'
/
COMMENT ON COLUMN ED4106M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4106M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4106M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4106M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4106M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4106M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4106M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4106M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4106M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4106M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4106M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4106M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4106M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4106M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
