/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4142M_TBL.sql
-- 物理名：ED4142M_TBL
-- 論理名：歩掛係数マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4142M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4142M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KIKEN_SAGYOHI_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「危険作業費係数」
	,SAGYO_JIKAN_WARIMASHI_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「作業時間割増率」
	,SGY_JIKANTAI_WARIMASHI_RITSU_2  NUMBER(7,3) DEFAULT '0' NOT NULL --「作業時間帯割増率２」
	,SGY_JIKANTAI_WARIMASHI_RITSU_3  NUMBER(7,3) DEFAULT '0' NOT NULL --「作業時間帯割増率３」
	,SGY_JIKANTAI_WARIMASHI_RITSU_4  NUMBER(7,3) DEFAULT '0' NOT NULL --「作業時間帯割増率４」
	,SGY_JIKANTAI_WARIMASHI_RITSU_5  NUMBER(7,3) DEFAULT '0' NOT NULL --「作業時間帯割増率５」
	,SGY_JIKANTAI_WARIMASHI_RITSU_6  NUMBER(7,3) DEFAULT '0' NOT NULL --「作業時間帯割増率６」
	,SGY_JIKANTAI_WARIMASHI_RITSU_7  NUMBER(7,3) DEFAULT '0' NOT NULL --「作業時間帯割増率７」
	,SGY_JIKANTAI_WARIMASHI_RITSU_8  NUMBER(7,3) DEFAULT '0' NOT NULL --「作業時間帯割増率８」
	,SGY_JIKANTAI_WARIMASHI_RITSU_9  NUMBER(7,3) DEFAULT '0' NOT NULL --「作業時間帯割増率９」
	,HA_SKSN_SGY_JKNT_WRMSH_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「ＨＡ積算作業時間帯割増率」
	,HA_SKSN_SGY_JKNT_WRMSH_RITSU_2  NUMBER(7,3) DEFAULT '0' NOT NULL --「ＨＡ積算作業時間帯割増率２」
	,HA_SKSN_SGY_JKNT_WRMSH_RITSU_3  NUMBER(7,3) DEFAULT '0' NOT NULL --「ＨＡ積算作業時間帯割増率３」
	,HA_SKSN_SGY_JKNT_WRMSH_RITSU_4  NUMBER(7,3) DEFAULT '0' NOT NULL --「ＨＡ積算作業時間帯割増率４」
	,HA_SKSN_SGY_JKNT_WRMSH_RITSU_5  NUMBER(7,3) DEFAULT '0' NOT NULL --「ＨＡ積算作業時間帯割増率５」
	,HA_SKSN_SGY_JKNT_WRMSH_RITSU_6  NUMBER(7,3) DEFAULT '0' NOT NULL --「ＨＡ積算作業時間帯割増率６」
	,HA_SKSN_SGY_JKNT_WRMSH_RITSU_7  NUMBER(7,3) DEFAULT '0' NOT NULL --「ＨＡ積算作業時間帯割増率７」
	,HA_SKSN_SGY_JKNT_WRMSH_RITSU_8  NUMBER(7,3) DEFAULT '0' NOT NULL --「ＨＡ積算作業時間帯割増率８」
	,HA_SKSN_SGY_JKNT_WRMSH_RITSU_9  NUMBER(7,3) DEFAULT '0' NOT NULL --「ＨＡ積算作業時間帯割増率９」
	,ST_SKSN_SGY_JKNT_WRMSH_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「その他積算作業時間割増率」
	,ST_SKSN_SGY_JKNT_WRMSH_RITSU_2  NUMBER(7,3) DEFAULT '0' NOT NULL --「その他積算作業時間帯割増率２」
	,ST_SKSN_SGY_JKNT_WRMSH_RITSU_3  NUMBER(7,3) DEFAULT '0' NOT NULL --「その他積算作業時間帯割増率３」
	,ST_SKSN_SGY_JKNT_WRMSH_RITSU_4  NUMBER(7,3) DEFAULT '0' NOT NULL --「その他積算作業時間帯割増率４」
	,ST_SKSN_SGY_JKNT_WRMSH_RITSU_5  NUMBER(7,3) DEFAULT '0' NOT NULL --「その他積算作業時間帯割増率５」
	,ST_SKSN_SGY_JKNT_WRMSH_RITSU_6  NUMBER(7,3) DEFAULT '0' NOT NULL --「その他積算作業時間帯割増率６」
	,ST_SKSN_SGY_JKNT_WRMSH_RITSU_7  NUMBER(7,3) DEFAULT '0' NOT NULL --「その他積算作業時間帯割増率７」
	,ST_SKSN_SGY_JKNT_WRMSH_RITSU_8  NUMBER(7,3) DEFAULT '0' NOT NULL --「その他積算作業時間帯割増率８」
	,ST_SKSN_SGY_JKNT_WRMSH_RITSU_9  NUMBER(7,3) DEFAULT '0' NOT NULL --「その他積算作業時間帯割増率９」
	,KSH_SGYSH_WARIMASHI_RITSU_1  NUMBER(7,3) DEFAULT '0' NOT NULL --「高所作業割増率１」
	,KSH_SGYSH_WARIMASHI_RITSU_2  NUMBER(7,3) DEFAULT '0' NOT NULL --「高所作業割増率２」
	,SHOMOHI_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「消耗費係数」
	,KOTEI_UMPANHI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「固定運搬費金額」
	,UMPANHI_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「運搬費係数」
	,ROMUHI_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「労務費係数」
	,SHIKEN_CHOSEIHI_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「試験調整費係数」
	,IPPAN_KANRIHI_KEISU_1  NUMBER(12,3) DEFAULT '0' NOT NULL --「一般管理費係数１」
	,IPPAN_KANRIHI_KEISU_2  NUMBER(12,3) DEFAULT '0' NOT NULL --「一般管理費係数２」
	,IPPAN_KANRIHI_KEISU_3  NUMBER(12,3) DEFAULT '0' NOT NULL --「一般管理費係数３」
	,GEMBA_KIHI_KEISU_1  NUMBER(12,3) DEFAULT '0' NOT NULL --「現場経費係数１」
	,GEMBA_KIHI_KEISU_2  NUMBER(12,3) DEFAULT '0' NOT NULL --「現場経費係数２」
	,GEMBA_KIHI_KEISU_3  NUMBER(12,3) DEFAULT '0' NOT NULL --「現場経費係数３」
	,GEMBA_KIHI_KEISU_4  NUMBER(12,3) DEFAULT '0' NOT NULL --「現場経費係数４」
	,KYOTSU_KASETSUHI_KEISU_1  NUMBER(12,3) DEFAULT '0' NOT NULL --「共通仮設費係数１」
	,KYOTSU_KASETSUHI_KEISU_2  NUMBER(12,3) DEFAULT '0' NOT NULL --「共通仮設費係数２」
	,KYOTSU_KASETSUHI_KEISU_3  NUMBER(12,3) DEFAULT '0' NOT NULL --「共通仮設費係数３」
	,KYOTSU_KASETSUHI_KEISU_4  NUMBER(12,3) DEFAULT '0' NOT NULL --「共通仮設費係数４」
	,HOTEI_HUKURIHI_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「法定福利費係数」
	,TEKKYO_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「撤去単価金額」
	,HA_SKSN_TEKKYO_TANKA_GNK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＨＡ積算撤去単価原価金額」
	,SNT_SKSN_TEKKYO_TANKA_GNK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「その他積算撤去単価原価金額」
	,HA_SKSN_TEKKYO_TANKA_HYJN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＨＡ積算撤去単価標準金額」
	,SNT_SKSN_TEKKYO_TANKA_HYJN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「その他積算撤去単価標準金額」
	,HAISEN_TISHSK_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「配線対象単価金額」
	,CHOKI_ZAIRYOHI_GENKA_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「長期材料費原価率」
	,SHMH_SHHRI_GNK_KNGKH_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「消耗費支払原価金額比率」
	,UMPNH_SHHRI_GNK_KNGKH_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「運搬費支払原価金額比率」
	,RMH_SHHRI_GNK_KNGKH_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「労務費支払原価金額比率」
	,SKN_CSIH_SHRI_GNK_KNGKH_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「試験調整費支払原価金額比率」
	,SHKIH_SHHRI_GNK_KNGKH_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「諸経費支払原価金額比率」
	,CHK_IPPN_KANRIHI_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「長期一般管理費原価率」
	,CHK_GENBA_KEIHI_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「長期現場経費原価率」
	,CHK_KYOTSU_KASETSUHI_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「長期共通仮設費原価率」
	,CHK_HKRKBR_STSZKKJH_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「長期光ケーブル接続工事費原価率」
	,CHK_KISO_KOJIHI_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「長期基礎工事費原価率」
	,CHK_TEKKYOKOJIHI_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「長期撤去工事費原価率」
	,CHK_HAISEN_TAISYOHI_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「長期配線対象費原価率」
	,CHK_SNT_KOJIHI_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「長期その他工事費原価率」
	,BIKYK_ZIRYHI_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却材料費原価率」
	,BIKYK_SHMH_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却消耗費原価率」
	,BIKYK_UMPNH_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却運搬費原価率」
	,BIKYK_RMH_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却労務費原価率」
	,BIKYK_SHKN_CSIH_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却試験調整費原価率」
	,BIKYK_SHKIH_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却諸経費原価率」
	,BIKYK_KK_RYOKIN_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却機器料金原価率」
	,BIKYK_IPPN_KANRIHI_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却一般管理費原価率」
	,BIKYK_GMB_KIH_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却現場経費原価率」
	,BIKYK_KTH_KSTSH_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却共通仮設費原価率」
	,BIKYK_HKRKBRSTSZKKJH_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却光ケーブル接続工事費原価率」
	,BIKYK_KSKJH_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却基礎工事費原価率」
	,BIKYK_TKKY_KOJIHI_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却撤去工事費原価率」
	,BIKYK_HISN_TAISYOHI_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却配線対象費原価率」
	,BIKYK_SNT_KJH_GNK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却その他工事費原価率」
	,KANI_SKSN_SHKIH_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「簡易積算諸経費係数」
	,HA_SKSN_SHKIH_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「ＨＡ積算諸経費係数」
	,SONOTA_SKSN_SHKIH_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「その他積算諸経費係数」
	,KANI_SKSN_IPPN_KNRH_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「簡易積算一般管理費係数」
	,HA_SKSN_IPPN_KNRH_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「ＨＡ積算一般管理費係数」
	,SONOTA_SKSN_IPPN_KNRH_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「その他積算一般管理費係数」
	,ZAIRYOHI_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「材料費率」
	,MENSEKI_HOSEI_KIJUN_MENSEKI  NUMBER(12,3) DEFAULT '0' NOT NULL --「面積補正基準面積」
	,MENSEKI_HOSEI_MENSEKIHI_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「面積補正面積比率」
	,HA_SKSN_SENSOR_HNTE_KJN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「ＨＡ積算センサー判定基準数量」
	,SHSI_SKSN_TISH_KJN_MENSEKI  NUMBER(9,0) DEFAULT '0' NOT NULL --「詳細積算対象基準面積」
	,SHSI_SKSN_TISH_KOJI_KIJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「詳細積算対象工事基準金額」
	,SENSOR_SKSN_HIMMEI_BUNRUI_CD  CHAR(3) --「センサー積算品名分類コード」
	,HY_HNMK_SKSN_HIMMEI_BUNRUI_CD  CHAR(3) --「費用品目積算品名分類コード」
	,DENKIJO_SKSN_HIMMEI_BUNRUI_CD  CHAR(3) --「電気錠積算品名分類コード」
	,NBK_TISH_SKSN_HIMMEI_BUNRUI_CD  CHAR(3) --「値引対象積算品名分類コード」
	,SHAGAI_MTSMR_KJ_REK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「社外見積工事利益率」
	,SHSI_SKSN_MTSMR_KJ_REK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「詳細積算工事利益率」
	,KOJI_KISO_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「工事基礎係数」
	,CHK_HTI_FKRH_GNK_KNGKH_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「長期法定福利費原価金額比率」
	,BIKYK_HTI_FKRH_GNK_KNGKH_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「売却法定福利費原価金額比率」
	,SECCHI_FUTANKIN_ZAIRYOHI_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「設置負担金材料費係数」
	,SECCHI_FUTANKIN_SHOMOHI_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「設置負担金消耗費係数」
	,SECCHI_FUTANKIN_UNPANHI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「設置負担金運搬費金額」
	,SECCHI_FUTANKIN_ROMUHI_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「設置負担金労務費係数」
	,SECCHI_FUTANKIN_SKNCHSIH_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「設置負担金試験調整費係数」
	,SECCHI_FUTANKIN_HTIFKRH_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「設置負担金法定福利費係数」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4142M_PK PRIMARY KEY(
	 KAISHA_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4142M_TBL IS '歩掛係数マスタ'
/

COMMENT ON COLUMN ED4142M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4142M_TBL.KIKEN_SAGYOHI_KEISU IS '危険作業費係数'
/
COMMENT ON COLUMN ED4142M_TBL.SAGYO_JIKAN_WARIMASHI_RITSU IS '作業時間割増率'
/
COMMENT ON COLUMN ED4142M_TBL.SGY_JIKANTAI_WARIMASHI_RITSU_2 IS '作業時間帯割増率２'
/
COMMENT ON COLUMN ED4142M_TBL.SGY_JIKANTAI_WARIMASHI_RITSU_3 IS '作業時間帯割増率３'
/
COMMENT ON COLUMN ED4142M_TBL.SGY_JIKANTAI_WARIMASHI_RITSU_4 IS '作業時間帯割増率４'
/
COMMENT ON COLUMN ED4142M_TBL.SGY_JIKANTAI_WARIMASHI_RITSU_5 IS '作業時間帯割増率５'
/
COMMENT ON COLUMN ED4142M_TBL.SGY_JIKANTAI_WARIMASHI_RITSU_6 IS '作業時間帯割増率６'
/
COMMENT ON COLUMN ED4142M_TBL.SGY_JIKANTAI_WARIMASHI_RITSU_7 IS '作業時間帯割増率７'
/
COMMENT ON COLUMN ED4142M_TBL.SGY_JIKANTAI_WARIMASHI_RITSU_8 IS '作業時間帯割増率８'
/
COMMENT ON COLUMN ED4142M_TBL.SGY_JIKANTAI_WARIMASHI_RITSU_9 IS '作業時間帯割増率９'
/
COMMENT ON COLUMN ED4142M_TBL.HA_SKSN_SGY_JKNT_WRMSH_RITSU IS 'ＨＡ積算作業時間帯割増率'
/
COMMENT ON COLUMN ED4142M_TBL.HA_SKSN_SGY_JKNT_WRMSH_RITSU_2 IS 'ＨＡ積算作業時間帯割増率２'
/
COMMENT ON COLUMN ED4142M_TBL.HA_SKSN_SGY_JKNT_WRMSH_RITSU_3 IS 'ＨＡ積算作業時間帯割増率３'
/
COMMENT ON COLUMN ED4142M_TBL.HA_SKSN_SGY_JKNT_WRMSH_RITSU_4 IS 'ＨＡ積算作業時間帯割増率４'
/
COMMENT ON COLUMN ED4142M_TBL.HA_SKSN_SGY_JKNT_WRMSH_RITSU_5 IS 'ＨＡ積算作業時間帯割増率５'
/
COMMENT ON COLUMN ED4142M_TBL.HA_SKSN_SGY_JKNT_WRMSH_RITSU_6 IS 'ＨＡ積算作業時間帯割増率６'
/
COMMENT ON COLUMN ED4142M_TBL.HA_SKSN_SGY_JKNT_WRMSH_RITSU_7 IS 'ＨＡ積算作業時間帯割増率７'
/
COMMENT ON COLUMN ED4142M_TBL.HA_SKSN_SGY_JKNT_WRMSH_RITSU_8 IS 'ＨＡ積算作業時間帯割増率８'
/
COMMENT ON COLUMN ED4142M_TBL.HA_SKSN_SGY_JKNT_WRMSH_RITSU_9 IS 'ＨＡ積算作業時間帯割増率９'
/
COMMENT ON COLUMN ED4142M_TBL.ST_SKSN_SGY_JKNT_WRMSH_RITSU IS 'その他積算作業時間割増率'
/
COMMENT ON COLUMN ED4142M_TBL.ST_SKSN_SGY_JKNT_WRMSH_RITSU_2 IS 'その他積算作業時間帯割増率２'
/
COMMENT ON COLUMN ED4142M_TBL.ST_SKSN_SGY_JKNT_WRMSH_RITSU_3 IS 'その他積算作業時間帯割増率３'
/
COMMENT ON COLUMN ED4142M_TBL.ST_SKSN_SGY_JKNT_WRMSH_RITSU_4 IS 'その他積算作業時間帯割増率４'
/
COMMENT ON COLUMN ED4142M_TBL.ST_SKSN_SGY_JKNT_WRMSH_RITSU_5 IS 'その他積算作業時間帯割増率５'
/
COMMENT ON COLUMN ED4142M_TBL.ST_SKSN_SGY_JKNT_WRMSH_RITSU_6 IS 'その他積算作業時間帯割増率６'
/
COMMENT ON COLUMN ED4142M_TBL.ST_SKSN_SGY_JKNT_WRMSH_RITSU_7 IS 'その他積算作業時間帯割増率７'
/
COMMENT ON COLUMN ED4142M_TBL.ST_SKSN_SGY_JKNT_WRMSH_RITSU_8 IS 'その他積算作業時間帯割増率８'
/
COMMENT ON COLUMN ED4142M_TBL.ST_SKSN_SGY_JKNT_WRMSH_RITSU_9 IS 'その他積算作業時間帯割増率９'
/
COMMENT ON COLUMN ED4142M_TBL.KSH_SGYSH_WARIMASHI_RITSU_1 IS '高所作業割増率１'
/
COMMENT ON COLUMN ED4142M_TBL.KSH_SGYSH_WARIMASHI_RITSU_2 IS '高所作業割増率２'
/
COMMENT ON COLUMN ED4142M_TBL.SHOMOHI_KEISU IS '消耗費係数'
/
COMMENT ON COLUMN ED4142M_TBL.KOTEI_UMPANHI_AMT IS '固定運搬費金額'
/
COMMENT ON COLUMN ED4142M_TBL.UMPANHI_KEISU IS '運搬費係数'
/
COMMENT ON COLUMN ED4142M_TBL.ROMUHI_KEISU IS '労務費係数'
/
COMMENT ON COLUMN ED4142M_TBL.SHIKEN_CHOSEIHI_KEISU IS '試験調整費係数'
/
COMMENT ON COLUMN ED4142M_TBL.IPPAN_KANRIHI_KEISU_1 IS '一般管理費係数１'
/
COMMENT ON COLUMN ED4142M_TBL.IPPAN_KANRIHI_KEISU_2 IS '一般管理費係数２'
/
COMMENT ON COLUMN ED4142M_TBL.IPPAN_KANRIHI_KEISU_3 IS '一般管理費係数３'
/
COMMENT ON COLUMN ED4142M_TBL.GEMBA_KIHI_KEISU_1 IS '現場経費係数１'
/
COMMENT ON COLUMN ED4142M_TBL.GEMBA_KIHI_KEISU_2 IS '現場経費係数２'
/
COMMENT ON COLUMN ED4142M_TBL.GEMBA_KIHI_KEISU_3 IS '現場経費係数３'
/
COMMENT ON COLUMN ED4142M_TBL.GEMBA_KIHI_KEISU_4 IS '現場経費係数４'
/
COMMENT ON COLUMN ED4142M_TBL.KYOTSU_KASETSUHI_KEISU_1 IS '共通仮設費係数１'
/
COMMENT ON COLUMN ED4142M_TBL.KYOTSU_KASETSUHI_KEISU_2 IS '共通仮設費係数２'
/
COMMENT ON COLUMN ED4142M_TBL.KYOTSU_KASETSUHI_KEISU_3 IS '共通仮設費係数３'
/
COMMENT ON COLUMN ED4142M_TBL.KYOTSU_KASETSUHI_KEISU_4 IS '共通仮設費係数４'
/
COMMENT ON COLUMN ED4142M_TBL.HOTEI_HUKURIHI_KEISU IS '法定福利費係数'
/
COMMENT ON COLUMN ED4142M_TBL.TEKKYO_TANKA_AMT IS '撤去単価金額'
/
COMMENT ON COLUMN ED4142M_TBL.HA_SKSN_TEKKYO_TANKA_GNK_AMT IS 'ＨＡ積算撤去単価原価金額'
/
COMMENT ON COLUMN ED4142M_TBL.SNT_SKSN_TEKKYO_TANKA_GNK_AMT IS 'その他積算撤去単価原価金額'
/
COMMENT ON COLUMN ED4142M_TBL.HA_SKSN_TEKKYO_TANKA_HYJN_AMT IS 'ＨＡ積算撤去単価標準金額'
/
COMMENT ON COLUMN ED4142M_TBL.SNT_SKSN_TEKKYO_TANKA_HYJN_AMT IS 'その他積算撤去単価標準金額'
/
COMMENT ON COLUMN ED4142M_TBL.HAISEN_TISHSK_TANKA_AMT IS '配線対象単価金額'
/
COMMENT ON COLUMN ED4142M_TBL.CHOKI_ZAIRYOHI_GENKA_RITSU IS '長期材料費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.SHMH_SHHRI_GNK_KNGKH_RITSU IS '消耗費支払原価金額比率'
/
COMMENT ON COLUMN ED4142M_TBL.UMPNH_SHHRI_GNK_KNGKH_RITSU IS '運搬費支払原価金額比率'
/
COMMENT ON COLUMN ED4142M_TBL.RMH_SHHRI_GNK_KNGKH_RITSU IS '労務費支払原価金額比率'
/
COMMENT ON COLUMN ED4142M_TBL.SKN_CSIH_SHRI_GNK_KNGKH_RITSU IS '試験調整費支払原価金額比率'
/
COMMENT ON COLUMN ED4142M_TBL.SHKIH_SHHRI_GNK_KNGKH_RITSU IS '諸経費支払原価金額比率'
/
COMMENT ON COLUMN ED4142M_TBL.CHK_IPPN_KANRIHI_GNK_RITSU IS '長期一般管理費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.CHK_GENBA_KEIHI_GNK_RITSU IS '長期現場経費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.CHK_KYOTSU_KASETSUHI_GNK_RITSU IS '長期共通仮設費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.CHK_HKRKBR_STSZKKJH_GNK_RITSU IS '長期光ケーブル接続工事費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.CHK_KISO_KOJIHI_GNK_RITSU IS '長期基礎工事費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.CHK_TEKKYOKOJIHI_GNK_RITSU IS '長期撤去工事費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.CHK_HAISEN_TAISYOHI_GNK_RITSU IS '長期配線対象費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.CHK_SNT_KOJIHI_GNK_RITSU IS '長期その他工事費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_ZIRYHI_GNK_RITSU IS '売却材料費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_SHMH_GNK_RITSU IS '売却消耗費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_UMPNH_GNK_RITSU IS '売却運搬費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_RMH_GNK_RITSU IS '売却労務費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_SHKN_CSIH_GNK_RITSU IS '売却試験調整費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_SHKIH_GNK_RITSU IS '売却諸経費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_KK_RYOKIN_GNK_RITSU IS '売却機器料金原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_IPPN_KANRIHI_GNK_RITSU IS '売却一般管理費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_GMB_KIH_GNK_RITSU IS '売却現場経費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_KTH_KSTSH_GNK_RITSU IS '売却共通仮設費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_HKRKBRSTSZKKJH_GNK_RITSU IS '売却光ケーブル接続工事費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_KSKJH_GNK_RITSU IS '売却基礎工事費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_TKKY_KOJIHI_GNK_RITSU IS '売却撤去工事費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_HISN_TAISYOHI_GNK_RITSU IS '売却配線対象費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_SNT_KJH_GNK_RITSU IS '売却その他工事費原価率'
/
COMMENT ON COLUMN ED4142M_TBL.KANI_SKSN_SHKIH_KEISU IS '簡易積算諸経費係数'
/
COMMENT ON COLUMN ED4142M_TBL.HA_SKSN_SHKIH_KEISU IS 'ＨＡ積算諸経費係数'
/
COMMENT ON COLUMN ED4142M_TBL.SONOTA_SKSN_SHKIH_KEISU IS 'その他積算諸経費係数'
/
COMMENT ON COLUMN ED4142M_TBL.KANI_SKSN_IPPN_KNRH_KEISU IS '簡易積算一般管理費係数'
/
COMMENT ON COLUMN ED4142M_TBL.HA_SKSN_IPPN_KNRH_KEISU IS 'ＨＡ積算一般管理費係数'
/
COMMENT ON COLUMN ED4142M_TBL.SONOTA_SKSN_IPPN_KNRH_KEISU IS 'その他積算一般管理費係数'
/
COMMENT ON COLUMN ED4142M_TBL.ZAIRYOHI_RITSU IS '材料費率'
/
COMMENT ON COLUMN ED4142M_TBL.MENSEKI_HOSEI_KIJUN_MENSEKI IS '面積補正基準面積'
/
COMMENT ON COLUMN ED4142M_TBL.MENSEKI_HOSEI_MENSEKIHI_RITSU IS '面積補正面積比率'
/
COMMENT ON COLUMN ED4142M_TBL.HA_SKSN_SENSOR_HNTE_KJN_SURYO IS 'ＨＡ積算センサー判定基準数量'
/
COMMENT ON COLUMN ED4142M_TBL.SHSI_SKSN_TISH_KJN_MENSEKI IS '詳細積算対象基準面積'
/
COMMENT ON COLUMN ED4142M_TBL.SHSI_SKSN_TISH_KOJI_KIJUN_AMT IS '詳細積算対象工事基準金額'
/
COMMENT ON COLUMN ED4142M_TBL.SENSOR_SKSN_HIMMEI_BUNRUI_CD IS 'センサー積算品名分類コード'
/
COMMENT ON COLUMN ED4142M_TBL.HY_HNMK_SKSN_HIMMEI_BUNRUI_CD IS '費用品目積算品名分類コード'
/
COMMENT ON COLUMN ED4142M_TBL.DENKIJO_SKSN_HIMMEI_BUNRUI_CD IS '電気錠積算品名分類コード'
/
COMMENT ON COLUMN ED4142M_TBL.NBK_TISH_SKSN_HIMMEI_BUNRUI_CD IS '値引対象積算品名分類コード'
/
COMMENT ON COLUMN ED4142M_TBL.SHAGAI_MTSMR_KJ_REK_RITSU IS '社外見積工事利益率'
/
COMMENT ON COLUMN ED4142M_TBL.SHSI_SKSN_MTSMR_KJ_REK_RITSU IS '詳細積算工事利益率'
/
COMMENT ON COLUMN ED4142M_TBL.KOJI_KISO_KEISU IS '工事基礎係数'
/
COMMENT ON COLUMN ED4142M_TBL.CHK_HTI_FKRH_GNK_KNGKH_RITSU IS '長期法定福利費原価金額比率'
/
COMMENT ON COLUMN ED4142M_TBL.BIKYK_HTI_FKRH_GNK_KNGKH_RITSU IS '売却法定福利費原価金額比率'
/
COMMENT ON COLUMN ED4142M_TBL.SECCHI_FUTANKIN_ZAIRYOHI_KEISU IS '設置負担金材料費係数'
/
COMMENT ON COLUMN ED4142M_TBL.SECCHI_FUTANKIN_SHOMOHI_KEISU IS '設置負担金消耗費係数'
/
COMMENT ON COLUMN ED4142M_TBL.SECCHI_FUTANKIN_UNPANHI_AMT IS '設置負担金運搬費金額'
/
COMMENT ON COLUMN ED4142M_TBL.SECCHI_FUTANKIN_ROMUHI_KEISU IS '設置負担金労務費係数'
/
COMMENT ON COLUMN ED4142M_TBL.SECCHI_FUTANKIN_SKNCHSIH_KEISU IS '設置負担金試験調整費係数'
/
COMMENT ON COLUMN ED4142M_TBL.SECCHI_FUTANKIN_HTIFKRH_KEISU IS '設置負担金法定福利費係数'
/
COMMENT ON COLUMN ED4142M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4142M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4142M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4142M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4142M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4142M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4142M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4142M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4142M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4142M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4142M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4142M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4142M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4142M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
