/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4150M_TBL.sql
-- 物理名：ED4150M_TBL
-- 論理名：見積書明細区分管理マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4150M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4150M_TBL (
	 SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,CHOHYO_ID  VARCHAR2(20) NOT NULL --「帳票ＩＤ」
	,MITSUMORISHO_MEISAI_KBN  CHAR(4) NOT NULL --「見積書明細区分」
	,MITSUMORISHO_MEISAI_HYOJI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「見積書明細表示順」
	,MITSUMORISHO_MEISAI_NM  VARCHAR2(100) --「見積書明細名称」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4150M_PK PRIMARY KEY(
	 SHOHIN_SERVICE_CD
	,  CHOHYO_ID
	,  MITSUMORISHO_MEISAI_KBN
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4150M_TBL IS '見積書明細区分管理マスタ'
/

COMMENT ON COLUMN ED4150M_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4150M_TBL.CHOHYO_ID IS '帳票ＩＤ'
/
COMMENT ON COLUMN ED4150M_TBL.MITSUMORISHO_MEISAI_KBN IS '見積書明細区分'
/
COMMENT ON COLUMN ED4150M_TBL.MITSUMORISHO_MEISAI_HYOJI_JUN IS '見積書明細表示順'
/
COMMENT ON COLUMN ED4150M_TBL.MITSUMORISHO_MEISAI_NM IS '見積書明細名称'
/
COMMENT ON COLUMN ED4150M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4150M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4150M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4150M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4150M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4150M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4150M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4150M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4150M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4150M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4150M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4150M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4150M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4150M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
