/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4112M_TBL.sql
-- 物理名：ED4112M_TBL
-- 論理名：常駐資格要件マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4112M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4112M_TBL (
	 SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JOCHU_SHIKAKU_YOKEN_CD  CHAR(4) NOT NULL --「常駐資格要件コード」
	,JOCHU_SHIKAKU_YOKEN_NM  VARCHAR2(60) NOT NULL --「常駐資格要件名称」
	,HYOJI_JUN_1  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順１」
	,JOCHU_SHIKAKU_YOKEN_KOMOKU_CD  CHAR(2) NOT NULL --「常駐資格要件項目コード」
	,JOCHU_SHIKAKU_YOKEN_KOMOKU_NM  VARCHAR2(30) NOT NULL --「常駐資格要件項目名称」
	,HYOJI_JUN_2  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順２」
	,JOCHU_SHIKAKU_YOKEN_NAIYO_CD  CHAR(2) NOT NULL --「常駐資格要件内容コード」
	,JOCHU_SHIKAKU_YOKEN_NAIYO_NM  VARCHAR2(30) NOT NULL --「常駐資格要件内容名称」
	,HYOJI_JUN_3  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順３」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4112M_PK PRIMARY KEY(
	 SHOHIN_SERVICE_CD
	,  KAISHA_CD
	,  JOCHU_SHIKAKU_YOKEN_CD
	,  JOCHU_SHIKAKU_YOKEN_KOMOKU_CD
	,  JOCHU_SHIKAKU_YOKEN_NAIYO_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4112M_TBL IS '常駐資格要件マスタ'
/

COMMENT ON COLUMN ED4112M_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4112M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4112M_TBL.JOCHU_SHIKAKU_YOKEN_CD IS '常駐資格要件コード'
/
COMMENT ON COLUMN ED4112M_TBL.JOCHU_SHIKAKU_YOKEN_NM IS '常駐資格要件名称'
/
COMMENT ON COLUMN ED4112M_TBL.HYOJI_JUN_1 IS '表示順１'
/
COMMENT ON COLUMN ED4112M_TBL.JOCHU_SHIKAKU_YOKEN_KOMOKU_CD IS '常駐資格要件項目コード'
/
COMMENT ON COLUMN ED4112M_TBL.JOCHU_SHIKAKU_YOKEN_KOMOKU_NM IS '常駐資格要件項目名称'
/
COMMENT ON COLUMN ED4112M_TBL.HYOJI_JUN_2 IS '表示順２'
/
COMMENT ON COLUMN ED4112M_TBL.JOCHU_SHIKAKU_YOKEN_NAIYO_CD IS '常駐資格要件内容コード'
/
COMMENT ON COLUMN ED4112M_TBL.JOCHU_SHIKAKU_YOKEN_NAIYO_NM IS '常駐資格要件内容名称'
/
COMMENT ON COLUMN ED4112M_TBL.HYOJI_JUN_3 IS '表示順３'
/
COMMENT ON COLUMN ED4112M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4112M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4112M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4112M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4112M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4112M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4112M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4112M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4112M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4112M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4112M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4112M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4112M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4112M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
