/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4103M_TBL.sql
-- 物理名：ED4103M_TBL
-- 論理名：入出金機売上回収係数マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4103M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4103M_TBL (
	 NYUSHUKKINKI_RYOGAEKI_KBN  CHAR(1) NOT NULL --「入出金機両替機区分」
	,NYSHKKNK_FURIKOMI_D_SHITEI_CD  CHAR(3) NOT NULL --「入出金機振込日指定コード」
	,NYSHKKNK_URAGKN_KISH_KEISU_CD  CHAR(3) NOT NULL --「入出金機売上金回収係数コード」
	,URIAGE_KINRI_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「売上金利係数」
	,GEKKAN_KAISHU_KAISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「月間回収回数」
	,TSURISEN_TESURYO_RYGE_KEISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「釣銭手数料両替係数」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4103M_PK PRIMARY KEY(
	 NYUSHUKKINKI_RYOGAEKI_KBN
	,  NYSHKKNK_FURIKOMI_D_SHITEI_CD
	,  NYSHKKNK_URAGKN_KISH_KEISU_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4103M_TBL IS '入出金機売上回収係数マスタ'
/

COMMENT ON COLUMN ED4103M_TBL.NYUSHUKKINKI_RYOGAEKI_KBN IS '入出金機両替機区分'
/
COMMENT ON COLUMN ED4103M_TBL.NYSHKKNK_FURIKOMI_D_SHITEI_CD IS '入出金機振込日指定コード'
/
COMMENT ON COLUMN ED4103M_TBL.NYSHKKNK_URAGKN_KISH_KEISU_CD IS '入出金機売上金回収係数コード'
/
COMMENT ON COLUMN ED4103M_TBL.URIAGE_KINRI_KEISU IS '売上金利係数'
/
COMMENT ON COLUMN ED4103M_TBL.GEKKAN_KAISHU_KAISU IS '月間回収回数'
/
COMMENT ON COLUMN ED4103M_TBL.TSURISEN_TESURYO_RYGE_KEISU IS '釣銭手数料両替係数'
/
COMMENT ON COLUMN ED4103M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4103M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4103M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4103M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4103M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4103M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4103M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4103M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4103M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4103M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4103M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4103M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4103M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4103M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
