/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4146M_TBL.sql
-- 物理名：ED4146M_TBL
-- 論理名：監視項目種別マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4146M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4146M_TBL (
	 SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,OMONA_KANSHI_KOMOKU_KBN  CHAR(1) NOT NULL --「主な監視項目区分」
	,KANSHI_KOMOKU_SHUBETSU_CD  CHAR(3) NOT NULL --「監視項目種別コード」
	,HYOJI_JUN_1  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順１」
	,KANSHI_HOHO_KBN  CHAR(1) NOT NULL --「監視方法区分」
	,HYOJI_JUN_2  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順２」
	,KANSHI_JIKAN_KBN  CHAR(2) NOT NULL --「監視時間区分」
	,KOMOKU_SHUBETSU_NM  VARCHAR2(300) --「監視項目種別名称」
	,KANSHI_KASHOSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「監視箇所数」
	,KANSHI_KASHOSU_HENKOKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「監視箇所数変更可フラグ」
	,SHOKI_HYOJI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「初期表示フラグ」
	,KANSHI_KOMOKU_KASAN_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「監視項目加算原価金額」
	,KANSHI_KOMOKU_KASAN_HYOJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「監視項目加算標準金額」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4146M_PK PRIMARY KEY(
	 SHOHIN_SERVICE_CD
	,  OMONA_KANSHI_KOMOKU_KBN
	,  KANSHI_KOMOKU_SHUBETSU_CD
	,  KANSHI_HOHO_KBN
	,  KANSHI_JIKAN_KBN
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4146M_TBL IS '監視項目種別マスタ'
/

COMMENT ON COLUMN ED4146M_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4146M_TBL.OMONA_KANSHI_KOMOKU_KBN IS '主な監視項目区分'
/
COMMENT ON COLUMN ED4146M_TBL.KANSHI_KOMOKU_SHUBETSU_CD IS '監視項目種別コード'
/
COMMENT ON COLUMN ED4146M_TBL.HYOJI_JUN_1 IS '表示順１'
/
COMMENT ON COLUMN ED4146M_TBL.KANSHI_HOHO_KBN IS '監視方法区分'
/
COMMENT ON COLUMN ED4146M_TBL.HYOJI_JUN_2 IS '表示順２'
/
COMMENT ON COLUMN ED4146M_TBL.KANSHI_JIKAN_KBN IS '監視時間区分'
/
COMMENT ON COLUMN ED4146M_TBL.KOMOKU_SHUBETSU_NM IS '監視項目種別名称'
/
COMMENT ON COLUMN ED4146M_TBL.KANSHI_KASHOSU IS '監視箇所数'
/
COMMENT ON COLUMN ED4146M_TBL.KANSHI_KASHOSU_HENKOKA_FLG IS '監視箇所数変更可フラグ'
/
COMMENT ON COLUMN ED4146M_TBL.SHOKI_HYOJI_FLG IS '初期表示フラグ'
/
COMMENT ON COLUMN ED4146M_TBL.KANSHI_KOMOKU_KASAN_GENKA_AMT IS '監視項目加算原価金額'
/
COMMENT ON COLUMN ED4146M_TBL.KANSHI_KOMOKU_KASAN_HYOJUN_AMT IS '監視項目加算標準金額'
/
COMMENT ON COLUMN ED4146M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4146M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4146M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4146M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4146M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4146M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4146M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4146M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4146M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4146M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4146M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4146M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4146M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4146M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
