/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4138M_TBL.sql
-- 物理名：ED4138M_TBL
-- 論理名：提示価格料金構成マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4138M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4138M_TBL (
	 SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,MTSMR_SKSI_M_GMN_KNGK_KMK_KBN  CHAR(2) NOT NULL --「見積作成明細画面金額項目区分」
	,TEIJI_KAKAKU_HIYO_KBN  CHAR(2) NOT NULL --「提示価格費用区分」
	,TEIJI_KAKAKU_KBN  CHAR(2) NOT NULL --「提示価格区分」
	,HYOJI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順」
	,UCHWK_TEIJI_KAKAKU_HIYO_KBN  CHAR(2) DEFAULT '00' NOT NULL --「内訳提示価格費用区分」
	,URIAGE_KEIJO_SHUBETSU_KBN  CHAR(2) NOT NULL --「売上計上種別区分」
	,JUCHU_SHORI_KBN  CHAR(2) NOT NULL --「受注処理区分」
	,RYOKIN_KBN  CHAR(5) NOT NULL --「料金区分」
	,NENGAKU_RYOKIN_KBN  CHAR(5) NOT NULL --「年額料金区分」
	,SKSN_PATTERN_KBN  CHAR(3) NOT NULL --「積算パターン区分」
	,KIYK_R_KNGK_SKSN_R_KISN_KMK_CD  CHAR(8) --「契約料金金額積算料金計算項目コード」
	,SHNSI_KNGK_SKSN_R_KISN_KMK_CD  CHAR(8) --「申請金額積算料金計算項目コード」
	,HYOJUN_KNGK_SKSN_R_KISN_KMK_CD  CHAR(8) --「標準金額積算料金計算項目コード」
	,GENKA_KNGK_SKSN_R_KISN_KMK_CD  CHAR(8) --「原価金額積算料金計算項目コード」
	,NNGK_S_KNGK_SKSN_R_KISN_KMK_CD  CHAR(8) --「年額申請金額積算料金計算項目コード」
	,KIYK_KITI_KBN  CHAR(1) DEFAULT '0' NOT NULL --「契約形態区分」
	,TEIJI_KAKAKU_HIHYOJI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「提示価格非表示フラグ」
	,TEIJI_KAKAKU_HENKOFUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「提示価格変更不可フラグ」
	,GOKEIGYO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「合計行フラグ」
	,HASU_CHOSEI_TAISHO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「端数調整対象フラグ」
	,NEBIKI_TAISHOGAI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「値引対象外フラグ」
	,YOSHIN_JOGEN_KISN_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「与信上限額計算対象フラグ」
	,YOSHIN_JOGEN_KISN_TISH_AMT_KBN  CHAR(2) DEFAULT '00' NOT NULL --「与信上限額計算対象金額区分」
	,SHONIN_KIJUN_AMT_KBN  CHAR(2) DEFAULT '00' NOT NULL --「承認基準金額区分」
	,KIYK_JH_TRK_HYJSK_GMN_KMK_NO  NUMBER(3,0) DEFAULT '0' NOT NULL --「契約情報登録表示先画面項目番号」
	,JSSH_JGYSH_GYM_SHBTS_KBN  CHAR(2) DEFAULT '00' NOT NULL --「実施事業所業務種別区分」
	,KEIJOSAKI_NAIYO  VARCHAR2(60) --「計上先内容」
	,SHIKIN_KANRI_TAISHO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「資金管理対象フラグ」
	,GYM_ITK_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「業務委託対象フラグ」
	,SEIKYU_SHIHARAI_CD  CHAR(3) --「請求支払コード」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4138M_PK PRIMARY KEY(
	 SHOHIN_SERVICE_CD
	,  TEIJI_KAKAKU_HIYO_KBN
	,  TEIJI_KAKAKU_KBN
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4138M_TBL IS '提示価格料金構成マスタ'
/

COMMENT ON COLUMN ED4138M_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4138M_TBL.MTSMR_SKSI_M_GMN_KNGK_KMK_KBN IS '見積作成明細画面金額項目区分'
/
COMMENT ON COLUMN ED4138M_TBL.TEIJI_KAKAKU_HIYO_KBN IS '提示価格費用区分'
/
COMMENT ON COLUMN ED4138M_TBL.TEIJI_KAKAKU_KBN IS '提示価格区分'
/
COMMENT ON COLUMN ED4138M_TBL.HYOJI_JUN IS '表示順'
/
COMMENT ON COLUMN ED4138M_TBL.UCHWK_TEIJI_KAKAKU_HIYO_KBN IS '内訳提示価格費用区分'
/
COMMENT ON COLUMN ED4138M_TBL.URIAGE_KEIJO_SHUBETSU_KBN IS '売上計上種別区分'
/
COMMENT ON COLUMN ED4138M_TBL.JUCHU_SHORI_KBN IS '受注処理区分'
/
COMMENT ON COLUMN ED4138M_TBL.RYOKIN_KBN IS '料金区分'
/
COMMENT ON COLUMN ED4138M_TBL.NENGAKU_RYOKIN_KBN IS '年額料金区分'
/
COMMENT ON COLUMN ED4138M_TBL.SKSN_PATTERN_KBN IS '積算パターン区分'
/
COMMENT ON COLUMN ED4138M_TBL.KIYK_R_KNGK_SKSN_R_KISN_KMK_CD IS '契約料金金額積算料金計算項目コード'
/
COMMENT ON COLUMN ED4138M_TBL.SHNSI_KNGK_SKSN_R_KISN_KMK_CD IS '申請金額積算料金計算項目コード'
/
COMMENT ON COLUMN ED4138M_TBL.HYOJUN_KNGK_SKSN_R_KISN_KMK_CD IS '標準金額積算料金計算項目コード'
/
COMMENT ON COLUMN ED4138M_TBL.GENKA_KNGK_SKSN_R_KISN_KMK_CD IS '原価金額積算料金計算項目コード'
/
COMMENT ON COLUMN ED4138M_TBL.NNGK_S_KNGK_SKSN_R_KISN_KMK_CD IS '年額申請金額積算料金計算項目コード'
/
COMMENT ON COLUMN ED4138M_TBL.KIYK_KITI_KBN IS '契約形態区分'
/
COMMENT ON COLUMN ED4138M_TBL.TEIJI_KAKAKU_HIHYOJI_FLG IS '提示価格非表示フラグ'
/
COMMENT ON COLUMN ED4138M_TBL.TEIJI_KAKAKU_HENKOFUKA_FLG IS '提示価格変更不可フラグ'
/
COMMENT ON COLUMN ED4138M_TBL.GOKEIGYO_FLG IS '合計行フラグ'
/
COMMENT ON COLUMN ED4138M_TBL.HASU_CHOSEI_TAISHO_FLG IS '端数調整対象フラグ'
/
COMMENT ON COLUMN ED4138M_TBL.NEBIKI_TAISHOGAI_FLG IS '値引対象外フラグ'
/
COMMENT ON COLUMN ED4138M_TBL.YOSHIN_JOGEN_KISN_TISH_FLG IS '与信上限額計算対象フラグ'
/
COMMENT ON COLUMN ED4138M_TBL.YOSHIN_JOGEN_KISN_TISH_AMT_KBN IS '与信上限額計算対象金額区分'
/
COMMENT ON COLUMN ED4138M_TBL.SHONIN_KIJUN_AMT_KBN IS '承認基準金額区分'
/
COMMENT ON COLUMN ED4138M_TBL.KIYK_JH_TRK_HYJSK_GMN_KMK_NO IS '契約情報登録表示先画面項目番号'
/
COMMENT ON COLUMN ED4138M_TBL.JSSH_JGYSH_GYM_SHBTS_KBN IS '実施事業所業務種別区分'
/
COMMENT ON COLUMN ED4138M_TBL.KEIJOSAKI_NAIYO IS '計上先内容'
/
COMMENT ON COLUMN ED4138M_TBL.SHIKIN_KANRI_TAISHO_FLG IS '資金管理対象フラグ'
/
COMMENT ON COLUMN ED4138M_TBL.GYM_ITK_TISH_FLG IS '業務委託対象フラグ'
/
COMMENT ON COLUMN ED4138M_TBL.SEIKYU_SHIHARAI_CD IS '請求支払コード'
/
COMMENT ON COLUMN ED4138M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4138M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4138M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4138M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4138M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4138M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4138M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4138M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4138M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4138M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4138M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4138M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4138M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4138M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
