/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4114M_TBL.sql
-- 物理名：ED4114M_TBL
-- 論理名：入出金機オプションマスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4114M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4114M_TBL (
	 NYUSHUKKINKI_OPTION_CD  CHAR(8) NOT NULL --「入出金機オプションコード」
	,NYUSHUKKINKI_RYOGAEKI_KISHU_CD  CHAR(8) NOT NULL --「入出金機両替機機種コード」
	,NYUSHUKKINKI_OPTION_NM  VARCHAR2(60) --「入出金機オプション名称」
	,NYSHKKNK_OPTION_SHBTS_KBN  CHAR(1) NOT NULL --「入出金機オプション種別区分」
	,SURYO_SETTEIKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「数量設定可フラグ」
	,AMT_SETTEIKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「金額設定可フラグ」
	,NYKNK_SHHN_STCH_HH_KBN  CHAR(1) --「入金機商品設置方法区分」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,GETSUGAKU_OPTION_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「月額オプション原価金額」
	,KIKI_LEASE_GETSUGAKU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「機器リース月額金額」
	,DATA_TENSO_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「データ転送料金金額」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4114M_PK PRIMARY KEY(
	 NYUSHUKKINKI_OPTION_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4114M_TBL IS '入出金機オプションマスタ'
/

COMMENT ON COLUMN ED4114M_TBL.NYUSHUKKINKI_OPTION_CD IS '入出金機オプションコード'
/
COMMENT ON COLUMN ED4114M_TBL.NYUSHUKKINKI_RYOGAEKI_KISHU_CD IS '入出金機両替機機種コード'
/
COMMENT ON COLUMN ED4114M_TBL.NYUSHUKKINKI_OPTION_NM IS '入出金機オプション名称'
/
COMMENT ON COLUMN ED4114M_TBL.NYSHKKNK_OPTION_SHBTS_KBN IS '入出金機オプション種別区分'
/
COMMENT ON COLUMN ED4114M_TBL.SURYO_SETTEIKA_FLG IS '数量設定可フラグ'
/
COMMENT ON COLUMN ED4114M_TBL.AMT_SETTEIKA_FLG IS '金額設定可フラグ'
/
COMMENT ON COLUMN ED4114M_TBL.NYKNK_SHHN_STCH_HH_KBN IS '入金機商品設置方法区分'
/
COMMENT ON COLUMN ED4114M_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED4114M_TBL.GETSUGAKU_OPTION_GENKA_AMT IS '月額オプション原価金額'
/
COMMENT ON COLUMN ED4114M_TBL.KIKI_LEASE_GETSUGAKU_AMT IS '機器リース月額金額'
/
COMMENT ON COLUMN ED4114M_TBL.DATA_TENSO_RYOKIN_AMT IS 'データ転送料金金額'
/
COMMENT ON COLUMN ED4114M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4114M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4114M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4114M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4114M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4114M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4114M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4114M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4114M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4114M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4114M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4114M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4114M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4114M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
