/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4108M_TBL.sql
-- 物理名：ED4108M_TBL
-- 論理名：受注申請与信マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4108M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4108M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,YOSHIN_KOMOKU_CD  CHAR(10) NOT NULL --「与信項目コード」
	,YOSHIN_KOMOKU_MEISAI_NO  CHAR(3) NOT NULL --「与信項目明細番号」
	,KEIYAKU_BUNRUI_KBN  CHAR(1) NOT NULL --「契約分類区分」
	,YOSHIN_KOMOKU_NM  VARCHAR2(60) --「与信項目名称」
	,YOSHIN_HANTEI_SHORI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「与信判定処理順」
	,YOSHIN_KOMOKU_GAMEN_HYOJI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「与信項目画面表示順」
	,YOSHIN_HANTEI_SQL_NAIYO  VARCHAR2(1000) --「与信判定ＳＱＬ内容」
	,YOSHIN_HANTEI_PROGRAM_ID  VARCHAR2(255) --「与信判定プログラムＩＤ」
	,YOSHIN_HANTEI_JOKEN_KBN  CHAR(1) NOT NULL --「与信判定条件区分」
	,YOSHIN_HANTEICHI  NUMBER(12,3) DEFAULT '0' NOT NULL --「与信判定値」
	,YOSHIN_HANTEI_TISH_NM_1  VARCHAR2(40) --「与信判定対象名称１」
	,YOSHIN_HANTEI_TISH_NM_2  VARCHAR2(40) --「与信判定対象名称２」
	,YOSHIN_JISSHI_KBN  CHAR(1) NOT NULL --「与信実施区分」
	,YOSHIN_HANTEI_END_FLG  CHAR(1) DEFAULT '0' NOT NULL --「与信判定終了フラグ」
	,YSHN_TRHK_NIY_TEXT_BOX_HYJ_FLG  CHAR(1) DEFAULT '0' NOT NULL --「与信取引内容テキストボックス表示フラグ」
	,YOSHIN_TRHK_KNGK_SHJN_KJN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「与信取引金額昇順降順フラグ」
	,EIGYOIN_SHNN_YSHN_TRHK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「営業員承認与信取引金額」
	,KACHO_SHNN_YSHN_TRHK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「課長承認与信取引金額」
	,BUCHO_SHNN_YSHN_TRHK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「部長承認与信取引金額」
	,SHOZOKUCHO_SHNN_YSHN_TRHK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「所属長承認与信取引金額」
	,CHIK_HNBCH_SHNN_YSHN_TRHK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「地域本部長承認与信取引金額」
	,YOSHIN_JOHO_SHOSAI_NAIYO  VARCHAR2(40) --「与信情報詳細内容」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4108M_PK PRIMARY KEY(
	 YOSHIN_KOMOKU_CD
	,  KAISHA_CD
	,  YOSHIN_KOMOKU_MEISAI_NO
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4108M_TBL IS '受注申請与信マスタ'
/

COMMENT ON COLUMN ED4108M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_KOMOKU_CD IS '与信項目コード'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_KOMOKU_MEISAI_NO IS '与信項目明細番号'
/
COMMENT ON COLUMN ED4108M_TBL.KEIYAKU_BUNRUI_KBN IS '契約分類区分'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_KOMOKU_NM IS '与信項目名称'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_HANTEI_SHORI_JUN IS '与信判定処理順'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_KOMOKU_GAMEN_HYOJI_JUN IS '与信項目画面表示順'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_HANTEI_SQL_NAIYO IS '与信判定ＳＱＬ内容'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_HANTEI_PROGRAM_ID IS '与信判定プログラムＩＤ'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_HANTEI_JOKEN_KBN IS '与信判定条件区分'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_HANTEICHI IS '与信判定値'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_HANTEI_TISH_NM_1 IS '与信判定対象名称１'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_HANTEI_TISH_NM_2 IS '与信判定対象名称２'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_JISSHI_KBN IS '与信実施区分'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_HANTEI_END_FLG IS '与信判定終了フラグ'
/
COMMENT ON COLUMN ED4108M_TBL.YSHN_TRHK_NIY_TEXT_BOX_HYJ_FLG IS '与信取引内容テキストボックス表示フラグ'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_TRHK_KNGK_SHJN_KJN_FLG IS '与信取引金額昇順降順フラグ'
/
COMMENT ON COLUMN ED4108M_TBL.EIGYOIN_SHNN_YSHN_TRHK_AMT IS '営業員承認与信取引金額'
/
COMMENT ON COLUMN ED4108M_TBL.KACHO_SHNN_YSHN_TRHK_AMT IS '課長承認与信取引金額'
/
COMMENT ON COLUMN ED4108M_TBL.BUCHO_SHNN_YSHN_TRHK_AMT IS '部長承認与信取引金額'
/
COMMENT ON COLUMN ED4108M_TBL.SHOZOKUCHO_SHNN_YSHN_TRHK_AMT IS '所属長承認与信取引金額'
/
COMMENT ON COLUMN ED4108M_TBL.CHIK_HNBCH_SHNN_YSHN_TRHK_AMT IS '地域本部長承認与信取引金額'
/
COMMENT ON COLUMN ED4108M_TBL.YOSHIN_JOHO_SHOSAI_NAIYO IS '与信情報詳細内容'
/
COMMENT ON COLUMN ED4108M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4108M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4108M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4108M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4108M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4108M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4108M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4108M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4108M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4108M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4108M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4108M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4108M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4108M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
