/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4120M_TBL.sql
-- 物理名：ED4120M_TBL
-- 論理名：制御装置機器構成マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4120M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4120M_TBL (
	 SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,SEIGYO_SOCHI_HIMMEI_CD  CHAR(8) NOT NULL --「制御装置品名コード」
	,SEKISAN_KAISEN_SHUBETSU_CD  CHAR(3) DEFAULT '0' NOT NULL --「積算回線種別コード」
	,KAISEN_SHOYU_KBN  CHAR(1) NOT NULL --「回線所有区分」
	,SEIGYO_SOCHI_KIKI_KOSEI_SN  CHAR(14) NOT NULL --「制御装置機器構成連番」
	,KOSEIHIN_HIMMEI_CD  CHAR(8) --「構成品品名コード」
	,HYOJI_JUN_1  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順１」
	,JIGYO_SEGMENT_CD  CHAR(3) --「事業セグメントコード」
	,KIKI_HYOJUN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「機器標準数量」
	,BAIKYAKUHINARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「売却品有フラグ」
	,OKUGAI_KANTSU_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「屋外貫通有フラグ」
	,OKUGAI_KANTSU_KASHOSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「屋外貫通箇所数」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4120M_PK PRIMARY KEY(
	 SHOHIN_SERVICE_CD
	,  SEIGYO_SOCHI_HIMMEI_CD
	,  SEKISAN_KAISEN_SHUBETSU_CD
	,  KAISEN_SHOYU_KBN
	,  SEIGYO_SOCHI_KIKI_KOSEI_SN
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4120M_TBL IS '制御装置機器構成マスタ'
/

COMMENT ON COLUMN ED4120M_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4120M_TBL.SEIGYO_SOCHI_HIMMEI_CD IS '制御装置品名コード'
/
COMMENT ON COLUMN ED4120M_TBL.SEKISAN_KAISEN_SHUBETSU_CD IS '積算回線種別コード'
/
COMMENT ON COLUMN ED4120M_TBL.KAISEN_SHOYU_KBN IS '回線所有区分'
/
COMMENT ON COLUMN ED4120M_TBL.SEIGYO_SOCHI_KIKI_KOSEI_SN IS '制御装置機器構成連番'
/
COMMENT ON COLUMN ED4120M_TBL.KOSEIHIN_HIMMEI_CD IS '構成品品名コード'
/
COMMENT ON COLUMN ED4120M_TBL.HYOJI_JUN_1 IS '表示順１'
/
COMMENT ON COLUMN ED4120M_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED4120M_TBL.KIKI_HYOJUN_SURYO IS '機器標準数量'
/
COMMENT ON COLUMN ED4120M_TBL.BAIKYAKUHINARI_FLG IS '売却品有フラグ'
/
COMMENT ON COLUMN ED4120M_TBL.OKUGAI_KANTSU_ARI_FLG IS '屋外貫通有フラグ'
/
COMMENT ON COLUMN ED4120M_TBL.OKUGAI_KANTSU_KASHOSU IS '屋外貫通箇所数'
/
COMMENT ON COLUMN ED4120M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4120M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4120M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4120M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4120M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4120M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4120M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4120M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4120M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4120M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4120M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4120M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4120M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4120M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
