/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4135M_TBL.sql
-- 物理名：ED4135M_TBL
-- 論理名：承認率マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4135M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4135M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SEKISAN_SHONINRITSU_CD  CHAR(5) NOT NULL --「積算承認率コード」
	,SEKISAN_SHONIN_TANI_KBN  CHAR(1) NOT NULL --「積算承認単位区分」
	,KEIYAKU_BUNRUI_KBN  CHAR(1) NOT NULL --「契約分類区分」
	,RYOKIN_TANI_KBN  CHAR(1) NOT NULL --「料金単位区分」
	,SHOHIN_SERVICE_CD  CHAR(3) --「商品サービスコード」
	,SEIGYO_SOCHI_HIMMEI_CD  CHAR(8) --「制御装置品名コード」
	,SHOHIN_SERVICE_NAIYO_CD  CHAR(3) --「商品サービス内容コード」
	,SONOTA_HIYO_CD  CHAR(8) --「その他費用コード」
	,OPTION_SERVICE_CD  CHAR(4) --「オプションサービスコード」
	,KIHON_KYOTSU_KEIYAKU_NO  CHAR(9) --「基本共通契約番号」
	,NEBIKI_CD  CHAR(6) --「値引コード」
	,TORIHIKISAKI_CD  CHAR(9) --「取引先コード」
	,TORIHIKISAKI_BUSHO_CD  CHAR(4) --「取引先部署コード」
	,JIGYOSHO_CD  CHAR(6) --「事業所コード」
	,EIGYOIN_SHONIN_KANOU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「営業員承認可能フラグ」
	,EIGYOIN_SHONIN_JOGEN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「営業員承認上限金額」
	,TOSHI_KAISHU_TSKS_KSN_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「投資回収月数加算係数」
	,SHOHIN_SERVICE_KISO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「商品サービス基礎金額」
	,SHOHIN_SERVICE_TOSHI_HI_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「商品サービス投資比率」
	,SITI_GTSGK_KNGK_SHNN_TKY_FLG  CHAR(1) DEFAULT '0' NOT NULL --「最低月額金額承認適用フラグ」
	,SITI_GTSGK_KNGK_SHJN_KJN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「最低月額金額昇順降順フラグ」
	,EIGYOIN_SHNN_SITI_GTSGK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「営業員承認最低月額金額」
	,KACHO_SHNN_SITI_GTSGK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「課長承認最低月額金額」
	,BUCHO_SHNN_SITI_GTSGK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「部長承認最低月額金額」
	,SHOZOKUCHO_SHNN_SITI_GTSGK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「所属長承認最低月額金額」
	,CHIK_HNBCH_SHNN_SITI_GTSGK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「地域本部長承認最低月額金額」
	,HNSH_MTM_SHNN_SITI_GTSGK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「本社まとめ承認最低月額金額」
	,TSH_KISH_TSKS_SHNN_TKY_FLG  CHAR(1) DEFAULT '0' NOT NULL --「投資回収月数承認適用フラグ」
	,TSH_KISH_TSKS_SHJN_KJN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「投資回収月数昇順降順フラグ」
	,EIGYIN_SHNN_TSHKISH_TSUKISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「営業員承認投資回収月数」
	,KACHO_SHNN_TSHKISH_TSUKISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「課長承認投資回収月数」
	,BUCHO_SHNN_TSHKISH_TSUKISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「部長承認投資回収月数」
	,SHZKCH_SHNN_TSHKISH_TSUKISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「所属長承認投資回収月数」
	,CHIKHMBCH_SHNN_TSHKISH_TSUKISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「地域本部長承認投資回収月数」
	,HNSH_MTM_SHNN_TSHKISH_TSUKISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「本社まとめ承認投資回収月数」
	,HYJN_KNGK_NBKRTS_SHNN_TKY_FLG  CHAR(1) DEFAULT '0' NOT NULL --「標準金額値引率承認適用フラグ」
	,HYJN_KNGK_NBKRTS_SHJN_KJN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「標準金額値引率昇順降順フラグ」
	,EIGYIN_SHNN_HYJNKNGK_NBK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「営業員承認標準金額値引率」
	,KACHO_SHNN_HYJNKNGK_NBK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「課長承認標準金額値引率」
	,BUCHO_SHNN_HYJNKNGK_NBK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「部長承認標準金額値引率」
	,SHZKCH_SHNN_HYJNKNGK_NBK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「所属長承認標準金額値引率」
	,C_HBCH_SHNN_HYJNKNGK_NBK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「地域本部長承認標準金額値引率」
	,H_MTM_SHNN_HYJNKNGK_NBK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「本社まとめ承認標準金額値引率」
	,REK_KNGK_NBKRTS_SHNN_TKY_FLG  CHAR(1) DEFAULT '0' NOT NULL --「利益金額値引率承認適用フラグ」
	,REK_KNGK_NBKRTS_SHJN_KJN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「利益金額値引率昇順降順フラグ」
	,EIGYOIN_SHNN_REKKNGK_NBK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「営業員承認利益金額値引率」
	,KACHO_SHNN_REKKNGK_NBK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「課長承認利益金額値引率」
	,BUCHO_SHNN_REKKNGK_NBK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「部長承認利益金額値引率」
	,SHZKCH_SHNN_REKKNGK_NBK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「所属長承認利益金額値引率」
	,C_HBCH_SHNN_REKKNGK_NBK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「地域本部長承認利益金額値引率」
	,H_MTM_SHNN_REKKNGK_NBK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「本社まとめ承認利益金額値引率」
	,OTS_FTN_KNGK_SHNN_TKY_FLG  CHAR(1) DEFAULT '0' NOT NULL --「乙負担金額承認適用フラグ」
	,OTS_FTN_KNGK_SHJN_KJN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「乙負担金額昇順降順フラグ」
	,EIGYOIN_SHNN_OTS_FTN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「営業員承認乙負担金額」
	,KACHO_SHNN_OTS_FTN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「課長承認乙負担金額」
	,BUCHO_SHNN_OTS_FTN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「部長承認乙負担金額」
	,SHZKCH_SHNN_OTS_FTN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「所属長承認乙負担金額」
	,C_HBCH_SHNN_OTS_FTN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「地域本部長承認乙負担金額」
	,H_MTM_SHNN_OTS_FTN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「本社まとめ承認金額」
	,ARR_RTS_SHNN_TKY_FLG  CHAR(1) DEFAULT '0' NOT NULL --「粗利益率承認適用フラグ」
	,ARR_RTS_SHJN_KJN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「粗利益率昇順降順フラグ」
	,EIGYOIN_SHNN_ARR_REK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「営業員承認粗利益率」
	,KACHO_SHNN_ARR_REK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「課長承認粗利益率」
	,BUCHO_SHNN_ARR_REK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「部長承認粗利益率」
	,SHZKCH_SHNN_ARR_REK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「所属長承認粗利益率」
	,C_HBCH_SHNN_ARR_REK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「地域本部長承認粗利益率」
	,H_MTM_SHNN_ARR_REK_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「本社まとめ承認粗利益率」
	,SHINSEI_SHONIN_KAISO_NO  CHAR(2) --「申請承認階層番号」
	,SHINSEI_SHONIN_ID  CHAR(6) --「申請承認ＩＤ」
	,SHINSEI_SHONIN_ROUTE_SN  NUMBER(3,0) DEFAULT '0' NOT NULL --「申請承認ルート連番」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4135M_PK PRIMARY KEY(
	 SEKISAN_SHONINRITSU_CD
	,  KAISHA_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4135M_TBL IS '承認率マスタ'
/

COMMENT ON COLUMN ED4135M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4135M_TBL.SEKISAN_SHONINRITSU_CD IS '積算承認率コード'
/
COMMENT ON COLUMN ED4135M_TBL.SEKISAN_SHONIN_TANI_KBN IS '積算承認単位区分'
/
COMMENT ON COLUMN ED4135M_TBL.KEIYAKU_BUNRUI_KBN IS '契約分類区分'
/
COMMENT ON COLUMN ED4135M_TBL.RYOKIN_TANI_KBN IS '料金単位区分'
/
COMMENT ON COLUMN ED4135M_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4135M_TBL.SEIGYO_SOCHI_HIMMEI_CD IS '制御装置品名コード'
/
COMMENT ON COLUMN ED4135M_TBL.SHOHIN_SERVICE_NAIYO_CD IS '商品サービス内容コード'
/
COMMENT ON COLUMN ED4135M_TBL.SONOTA_HIYO_CD IS 'その他費用コード'
/
COMMENT ON COLUMN ED4135M_TBL.OPTION_SERVICE_CD IS 'オプションサービスコード'
/
COMMENT ON COLUMN ED4135M_TBL.KIHON_KYOTSU_KEIYAKU_NO IS '基本共通契約番号'
/
COMMENT ON COLUMN ED4135M_TBL.NEBIKI_CD IS '値引コード'
/
COMMENT ON COLUMN ED4135M_TBL.TORIHIKISAKI_CD IS '取引先コード'
/
COMMENT ON COLUMN ED4135M_TBL.TORIHIKISAKI_BUSHO_CD IS '取引先部署コード'
/
COMMENT ON COLUMN ED4135M_TBL.JIGYOSHO_CD IS '事業所コード'
/
COMMENT ON COLUMN ED4135M_TBL.EIGYOIN_SHONIN_KANOU_FLG IS '営業員承認可能フラグ'
/
COMMENT ON COLUMN ED4135M_TBL.EIGYOIN_SHONIN_JOGEN_AMT IS '営業員承認上限金額'
/
COMMENT ON COLUMN ED4135M_TBL.TOSHI_KAISHU_TSKS_KSN_KEISU IS '投資回収月数加算係数'
/
COMMENT ON COLUMN ED4135M_TBL.SHOHIN_SERVICE_KISO_AMT IS '商品サービス基礎金額'
/
COMMENT ON COLUMN ED4135M_TBL.SHOHIN_SERVICE_TOSHI_HI_RITSU IS '商品サービス投資比率'
/
COMMENT ON COLUMN ED4135M_TBL.SITI_GTSGK_KNGK_SHNN_TKY_FLG IS '最低月額金額承認適用フラグ'
/
COMMENT ON COLUMN ED4135M_TBL.SITI_GTSGK_KNGK_SHJN_KJN_FLG IS '最低月額金額昇順降順フラグ'
/
COMMENT ON COLUMN ED4135M_TBL.EIGYOIN_SHNN_SITI_GTSGK_AMT IS '営業員承認最低月額金額'
/
COMMENT ON COLUMN ED4135M_TBL.KACHO_SHNN_SITI_GTSGK_AMT IS '課長承認最低月額金額'
/
COMMENT ON COLUMN ED4135M_TBL.BUCHO_SHNN_SITI_GTSGK_AMT IS '部長承認最低月額金額'
/
COMMENT ON COLUMN ED4135M_TBL.SHOZOKUCHO_SHNN_SITI_GTSGK_AMT IS '所属長承認最低月額金額'
/
COMMENT ON COLUMN ED4135M_TBL.CHIK_HNBCH_SHNN_SITI_GTSGK_AMT IS '地域本部長承認最低月額金額'
/
COMMENT ON COLUMN ED4135M_TBL.HNSH_MTM_SHNN_SITI_GTSGK_AMT IS '本社まとめ承認最低月額金額'
/
COMMENT ON COLUMN ED4135M_TBL.TSH_KISH_TSKS_SHNN_TKY_FLG IS '投資回収月数承認適用フラグ'
/
COMMENT ON COLUMN ED4135M_TBL.TSH_KISH_TSKS_SHJN_KJN_FLG IS '投資回収月数昇順降順フラグ'
/
COMMENT ON COLUMN ED4135M_TBL.EIGYIN_SHNN_TSHKISH_TSUKISU IS '営業員承認投資回収月数'
/
COMMENT ON COLUMN ED4135M_TBL.KACHO_SHNN_TSHKISH_TSUKISU IS '課長承認投資回収月数'
/
COMMENT ON COLUMN ED4135M_TBL.BUCHO_SHNN_TSHKISH_TSUKISU IS '部長承認投資回収月数'
/
COMMENT ON COLUMN ED4135M_TBL.SHZKCH_SHNN_TSHKISH_TSUKISU IS '所属長承認投資回収月数'
/
COMMENT ON COLUMN ED4135M_TBL.CHIKHMBCH_SHNN_TSHKISH_TSUKISU IS '地域本部長承認投資回収月数'
/
COMMENT ON COLUMN ED4135M_TBL.HNSH_MTM_SHNN_TSHKISH_TSUKISU IS '本社まとめ承認投資回収月数'
/
COMMENT ON COLUMN ED4135M_TBL.HYJN_KNGK_NBKRTS_SHNN_TKY_FLG IS '標準金額値引率承認適用フラグ'
/
COMMENT ON COLUMN ED4135M_TBL.HYJN_KNGK_NBKRTS_SHJN_KJN_FLG IS '標準金額値引率昇順降順フラグ'
/
COMMENT ON COLUMN ED4135M_TBL.EIGYIN_SHNN_HYJNKNGK_NBK_RITSU IS '営業員承認標準金額値引率'
/
COMMENT ON COLUMN ED4135M_TBL.KACHO_SHNN_HYJNKNGK_NBK_RITSU IS '課長承認標準金額値引率'
/
COMMENT ON COLUMN ED4135M_TBL.BUCHO_SHNN_HYJNKNGK_NBK_RITSU IS '部長承認標準金額値引率'
/
COMMENT ON COLUMN ED4135M_TBL.SHZKCH_SHNN_HYJNKNGK_NBK_RITSU IS '所属長承認標準金額値引率'
/
COMMENT ON COLUMN ED4135M_TBL.C_HBCH_SHNN_HYJNKNGK_NBK_RITSU IS '地域本部長承認標準金額値引率'
/
COMMENT ON COLUMN ED4135M_TBL.H_MTM_SHNN_HYJNKNGK_NBK_RITSU IS '本社まとめ承認標準金額値引率'
/
COMMENT ON COLUMN ED4135M_TBL.REK_KNGK_NBKRTS_SHNN_TKY_FLG IS '利益金額値引率承認適用フラグ'
/
COMMENT ON COLUMN ED4135M_TBL.REK_KNGK_NBKRTS_SHJN_KJN_FLG IS '利益金額値引率昇順降順フラグ'
/
COMMENT ON COLUMN ED4135M_TBL.EIGYOIN_SHNN_REKKNGK_NBK_RITSU IS '営業員承認利益金額値引率'
/
COMMENT ON COLUMN ED4135M_TBL.KACHO_SHNN_REKKNGK_NBK_RITSU IS '課長承認利益金額値引率'
/
COMMENT ON COLUMN ED4135M_TBL.BUCHO_SHNN_REKKNGK_NBK_RITSU IS '部長承認利益金額値引率'
/
COMMENT ON COLUMN ED4135M_TBL.SHZKCH_SHNN_REKKNGK_NBK_RITSU IS '所属長承認利益金額値引率'
/
COMMENT ON COLUMN ED4135M_TBL.C_HBCH_SHNN_REKKNGK_NBK_RITSU IS '地域本部長承認利益金額値引率'
/
COMMENT ON COLUMN ED4135M_TBL.H_MTM_SHNN_REKKNGK_NBK_RITSU IS '本社まとめ承認利益金額値引率'
/
COMMENT ON COLUMN ED4135M_TBL.OTS_FTN_KNGK_SHNN_TKY_FLG IS '乙負担金額承認適用フラグ'
/
COMMENT ON COLUMN ED4135M_TBL.OTS_FTN_KNGK_SHJN_KJN_FLG IS '乙負担金額昇順降順フラグ'
/
COMMENT ON COLUMN ED4135M_TBL.EIGYOIN_SHNN_OTS_FTN_AMT IS '営業員承認乙負担金額'
/
COMMENT ON COLUMN ED4135M_TBL.KACHO_SHNN_OTS_FTN_AMT IS '課長承認乙負担金額'
/
COMMENT ON COLUMN ED4135M_TBL.BUCHO_SHNN_OTS_FTN_AMT IS '部長承認乙負担金額'
/
COMMENT ON COLUMN ED4135M_TBL.SHZKCH_SHNN_OTS_FTN_AMT IS '所属長承認乙負担金額'
/
COMMENT ON COLUMN ED4135M_TBL.C_HBCH_SHNN_OTS_FTN_AMT IS '地域本部長承認乙負担金額'
/
COMMENT ON COLUMN ED4135M_TBL.H_MTM_SHNN_OTS_FTN_AMT IS '本社まとめ承認金額'
/
COMMENT ON COLUMN ED4135M_TBL.ARR_RTS_SHNN_TKY_FLG IS '粗利益率承認適用フラグ'
/
COMMENT ON COLUMN ED4135M_TBL.ARR_RTS_SHJN_KJN_FLG IS '粗利益率昇順降順フラグ'
/
COMMENT ON COLUMN ED4135M_TBL.EIGYOIN_SHNN_ARR_REK_RITSU IS '営業員承認粗利益率'
/
COMMENT ON COLUMN ED4135M_TBL.KACHO_SHNN_ARR_REK_RITSU IS '課長承認粗利益率'
/
COMMENT ON COLUMN ED4135M_TBL.BUCHO_SHNN_ARR_REK_RITSU IS '部長承認粗利益率'
/
COMMENT ON COLUMN ED4135M_TBL.SHZKCH_SHNN_ARR_REK_RITSU IS '所属長承認粗利益率'
/
COMMENT ON COLUMN ED4135M_TBL.C_HBCH_SHNN_ARR_REK_RITSU IS '地域本部長承認粗利益率'
/
COMMENT ON COLUMN ED4135M_TBL.H_MTM_SHNN_ARR_REK_RITSU IS '本社まとめ承認粗利益率'
/
COMMENT ON COLUMN ED4135M_TBL.SHINSEI_SHONIN_KAISO_NO IS '申請承認階層番号'
/
COMMENT ON COLUMN ED4135M_TBL.SHINSEI_SHONIN_ID IS '申請承認ＩＤ'
/
COMMENT ON COLUMN ED4135M_TBL.SHINSEI_SHONIN_ROUTE_SN IS '申請承認ルート連番'
/
COMMENT ON COLUMN ED4135M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4135M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4135M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4135M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4135M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4135M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4135M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4135M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4135M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4135M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4135M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4135M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4135M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4135M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
