/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4215M_TBL.sql
-- 物理名：ED4215M_TBL
-- 論理名：空撮サービス料金マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4215M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4215M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KUSATSU_SERVICE_RYOKIN_CD  CHAR(8) NOT NULL --「空撮サービス料金コード」
	,MEGA_SOLAR_SETSUBI_M_W  NUMBER(12,3) DEFAULT '0' NOT NULL --「メガソーラー設備メガワット」
	,KUSATSU_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「空撮料金金額」
	,KUSATSU_JISSHI_NISSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「空撮実施日数」
	,KUSATSU_ITAKUSAKI_SHIHARAI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「空撮委託先支払金額」
	,KUSATSU_KIKI_HOKENRYO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「空撮機器保険料金額」
	,KUSATSU_JIGYOSHO_RIEKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「空撮事業所利益金額」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4215M_PK PRIMARY KEY(
	 KUSATSU_SERVICE_RYOKIN_CD
	,  KAISHA_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4215M_TBL IS '空撮サービス料金マスタ'
/

COMMENT ON COLUMN ED4215M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4215M_TBL.KUSATSU_SERVICE_RYOKIN_CD IS '空撮サービス料金コード'
/
COMMENT ON COLUMN ED4215M_TBL.MEGA_SOLAR_SETSUBI_M_W IS 'メガソーラー設備メガワット'
/
COMMENT ON COLUMN ED4215M_TBL.KUSATSU_RYOKIN_AMT IS '空撮料金金額'
/
COMMENT ON COLUMN ED4215M_TBL.KUSATSU_JISSHI_NISSU IS '空撮実施日数'
/
COMMENT ON COLUMN ED4215M_TBL.KUSATSU_ITAKUSAKI_SHIHARAI_AMT IS '空撮委託先支払金額'
/
COMMENT ON COLUMN ED4215M_TBL.KUSATSU_KIKI_HOKENRYO_AMT IS '空撮機器保険料金額'
/
COMMENT ON COLUMN ED4215M_TBL.KUSATSU_JIGYOSHO_RIEKI_AMT IS '空撮事業所利益金額'
/
COMMENT ON COLUMN ED4215M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4215M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4215M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4215M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4215M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4215M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4215M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4215M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4215M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4215M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4215M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4215M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4215M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4215M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
