/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4252M_TBL.sql
-- 物理名：ED4252M_TBL
-- 論理名：救急トレーニング料金マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4252M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4252M_TBL (
	 SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,KYUKYU_TRAINING_COURSE_KBN  CHAR(1) NOT NULL --「救急トレーニングコース区分」
	,HYOJI_JUN_1  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順１」
	,KYKY_TRINNG_HIYO_SHBTS_KBN  CHAR(1) NOT NULL --「救急トレーニング費用種別区分」
	,KYUKYU_TRAINING_KOMOKU_CD  CHAR(4) NOT NULL --「救急トレーニング項目コード」
	,KYUKYU_TRAINING_KOMOKU_NM  VARCHAR2(100) --「救急トレーニング項目名称」
	,KYKY_TRAINING_KYZI_PLAN_KBN  CHAR(1) NOT NULL --「救急トレーニング教材プラン区分」
	,HYOJI_JUN_2  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順２」
	,KYUKYU_TRAINING_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「救急トレーニング原価金額」
	,KYUKYU_TRAINING_HYOJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「救急トレーニング標準金額」
	,KYKY_TRINNG_TSIK_GNK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「救急トレーニング追加原価金額」
	,KYKY_TRINNG_TSIK_HYJN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「救急トレーニング追加標準金額」
	,KYKY_TRINNG_RYKN_SNSHTS_KEISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「救急トレーニング料金算出係数」
	,KYKY_TRINNG_KSHS_SNSHTS_KEISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「救急トレーニング講師数算出係数」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4252M_PK PRIMARY KEY(
	 SHOHIN_SERVICE_CD
	,  KYUKYU_TRAINING_COURSE_KBN
	,  KYKY_TRINNG_HIYO_SHBTS_KBN
	,  KYUKYU_TRAINING_KOMOKU_CD
	,  KYKY_TRAINING_KYZI_PLAN_KBN
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4252M_TBL IS '救急トレーニング料金マスタ'
/

COMMENT ON COLUMN ED4252M_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4252M_TBL.KYUKYU_TRAINING_COURSE_KBN IS '救急トレーニングコース区分'
/
COMMENT ON COLUMN ED4252M_TBL.HYOJI_JUN_1 IS '表示順１'
/
COMMENT ON COLUMN ED4252M_TBL.KYKY_TRINNG_HIYO_SHBTS_KBN IS '救急トレーニング費用種別区分'
/
COMMENT ON COLUMN ED4252M_TBL.KYUKYU_TRAINING_KOMOKU_CD IS '救急トレーニング項目コード'
/
COMMENT ON COLUMN ED4252M_TBL.KYUKYU_TRAINING_KOMOKU_NM IS '救急トレーニング項目名称'
/
COMMENT ON COLUMN ED4252M_TBL.KYKY_TRAINING_KYZI_PLAN_KBN IS '救急トレーニング教材プラン区分'
/
COMMENT ON COLUMN ED4252M_TBL.HYOJI_JUN_2 IS '表示順２'
/
COMMENT ON COLUMN ED4252M_TBL.KYUKYU_TRAINING_GENKA_AMT IS '救急トレーニング原価金額'
/
COMMENT ON COLUMN ED4252M_TBL.KYUKYU_TRAINING_HYOJUN_AMT IS '救急トレーニング標準金額'
/
COMMENT ON COLUMN ED4252M_TBL.KYKY_TRINNG_TSIK_GNK_AMT IS '救急トレーニング追加原価金額'
/
COMMENT ON COLUMN ED4252M_TBL.KYKY_TRINNG_TSIK_HYJN_AMT IS '救急トレーニング追加標準金額'
/
COMMENT ON COLUMN ED4252M_TBL.KYKY_TRINNG_RYKN_SNSHTS_KEISU IS '救急トレーニング料金算出係数'
/
COMMENT ON COLUMN ED4252M_TBL.KYKY_TRINNG_KSHS_SNSHTS_KEISU IS '救急トレーニング講師数算出係数'
/
COMMENT ON COLUMN ED4252M_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED4252M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4252M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4252M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4252M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4252M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4252M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4252M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4252M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4252M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4252M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4252M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4252M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4252M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4252M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
