/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4245M_TBL.sql
-- 物理名：ED4245M_TBL
-- 論理名：ＭＭＫ機種マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4245M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4245M_TBL (
	 MMK_KISHU_CD  CHAR(4) NOT NULL --「ＭＭＫ機種コード」
	,HYOJI_JUN_1  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順１」
	,MMK_KISHU_NM  VARCHAR2(30) --「ＭＭＫ機種名称」
	,MMK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＭＭＫ金額」
	,MMK_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＭＭＫ原価金額」
	,KKIKIB_GTSGK_KHNRYKN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「機械警備月額基本料金金額」
	,KKIKIB_GTSGK_KHNRYKN_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「機械警備月額基本料金原価金額」
	,COSMO_KHNRYKN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「コスモ基本料金金額」
	,COSMO_KHNRYKN_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「コスモ基本料金原価金額」
	,KIS_KHNRYKN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「警送基本料金金額」
	,KIS_KHNRYKN_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「警送基本料金原価金額」
	,KIS_RNG_KHNRYKN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「警送臨時料金金額」
	,KIS_RNG_KHNRYKN_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「警送臨時料金原価金額」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4245M_PK PRIMARY KEY(
	 MMK_KISHU_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4245M_TBL IS 'ＭＭＫ機種マスタ'
/

COMMENT ON COLUMN ED4245M_TBL.MMK_KISHU_CD IS 'ＭＭＫ機種コード'
/
COMMENT ON COLUMN ED4245M_TBL.HYOJI_JUN_1 IS '表示順１'
/
COMMENT ON COLUMN ED4245M_TBL.MMK_KISHU_NM IS 'ＭＭＫ機種名称'
/
COMMENT ON COLUMN ED4245M_TBL.MMK_AMT IS 'ＭＭＫ金額'
/
COMMENT ON COLUMN ED4245M_TBL.MMK_GENKA_AMT IS 'ＭＭＫ原価金額'
/
COMMENT ON COLUMN ED4245M_TBL.KKIKIB_GTSGK_KHNRYKN_AMT IS '機械警備月額基本料金金額'
/
COMMENT ON COLUMN ED4245M_TBL.KKIKIB_GTSGK_KHNRYKN_GENKA_AMT IS '機械警備月額基本料金原価金額'
/
COMMENT ON COLUMN ED4245M_TBL.COSMO_KHNRYKN_AMT IS 'コスモ基本料金金額'
/
COMMENT ON COLUMN ED4245M_TBL.COSMO_KHNRYKN_GENKA_AMT IS 'コスモ基本料金原価金額'
/
COMMENT ON COLUMN ED4245M_TBL.KIS_KHNRYKN_AMT IS '警送基本料金金額'
/
COMMENT ON COLUMN ED4245M_TBL.KIS_KHNRYKN_GENKA_AMT IS '警送基本料金原価金額'
/
COMMENT ON COLUMN ED4245M_TBL.KIS_RNG_KHNRYKN_AMT IS '警送臨時料金金額'
/
COMMENT ON COLUMN ED4245M_TBL.KIS_RNG_KHNRYKN_GENKA_AMT IS '警送臨時料金原価金額'
/
COMMENT ON COLUMN ED4245M_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4245M_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4245M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4245M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4245M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4245M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4245M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4245M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4245M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4245M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4245M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4245M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4245M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4245M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
