/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4334T_TBL.sql
-- 物理名：ED4334T_TBL
-- 論理名：警備診断機械テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4334T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4334T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIBI_SHINDAN_NO  CHAR(17) NOT NULL --「警備診断番号」
	,KAZOKU_KOSEI_KBN  CHAR(1) NOT NULL --「家族構成区分」
	,DOKYO_KAZOKU_HAIGUSHA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「同居家族配偶者フラグ」
	,DOKYO_KAZOKU_KO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「同居家族子フラグ」
	,DOKYO_KAZOKU_OYA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「同居家族親フラグ」
	,DOKYO_KAZOKU_SOFUBO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「同居家族祖父母フラグ」
	,DOKYO_KAZOKU_MAGO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「同居家族孫フラグ」
	,DOKYO_KAZOKU_KYODAI_SHIMAI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「同居家族兄弟姉妹フラグ」
	,SNT_DKY_KZK_ZKGR_AR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「その他同居家族続柄有フラグ」
	,SNT_DKY_KZK_ZKGR_NM  VARCHAR2(100) --「その他同居家族続柄名称」
	,KEIBIYO_DENGEN_JOHO_KBN  CHAR(1) NOT NULL --「警備用電源情報区分」
	,BUNDEMBAN_AKINASHI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「分電盤空き無フラグ」
	,DENGEN_SETCHI_BASHO_KBN  CHAR(1) NOT NULL --「電源設置場所区分」
	,KAISEN_SETCHI_BASHO_KBN  CHAR(1) NOT NULL --「回線設置場所区分」
	,SHOHIN_SERVICE_CD  CHAR(3) --「商品サービスコード」
	,SEIGYO_SOCHI_CD  CHAR(8) --「制御装置コード」
	,BOHAN_KANSHI_KOMOKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「防犯監視項目有フラグ」
	,HIJO_KANSHI_KOMOKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「非常監視項目有フラグ」
	,KASAI_KANSHI_KOMOKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「火災監視項目有フラグ」
	,SETSUBI_KANSHI_KOMOKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「設備監視項目有フラグ」
	,KEIBI_KUKAKUSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「警備区画数」
	,SOSA_KEY_KBN  CHAR(1) NOT NULL --「操作キー区分」
	,SONOTA_SOSA_KEY_NM  VARCHAR2(30) --「その他操作キー名称」
	,SOSA_KEY_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「操作キー数量」
	,YSN_TYPE_OSH_BUTTON_GT_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「有線タイプ押ボタン型数量」
	,MUSEN_TYPE_CARD_GATA_MAISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「無線タイプカード型枚数」
	,SONOTA_YUSEN_MUSEN_TYPE_NM  VARCHAR2(30) --「その他有線無線タイプ名称」
	,SONOTA_YUSEN_MUSEN_TYPE_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「その他有線無線タイプ数量」
	,KASAI_SHINGO_TEST_TEHAI_KBN  CHAR(1) NOT NULL --「火災信号テスト手配区分」
	,JKH_STSB_TNKN_JGYSH_NM  VARCHAR2(200) --「自火報設備点検事業所名称」
	,SETSUBI_SHINGO_TEST_TEHAI_KBN  CHAR(1) NOT NULL --「設備信号テスト手配区分」
	,ALSOK_GUARD_SYSTEM_SGHKYB_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＡＬＳＯＫガードシステム総合保険要望フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4334T_PK PRIMARY KEY(
	 KEIBI_SHINDAN_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4334T_TBL IS '警備診断機械テーブル'
/

COMMENT ON COLUMN ED4334T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4334T_TBL.KEIBI_SHINDAN_NO IS '警備診断番号'
/
COMMENT ON COLUMN ED4334T_TBL.KAZOKU_KOSEI_KBN IS '家族構成区分'
/
COMMENT ON COLUMN ED4334T_TBL.DOKYO_KAZOKU_HAIGUSHA_FLG IS '同居家族配偶者フラグ'
/
COMMENT ON COLUMN ED4334T_TBL.DOKYO_KAZOKU_KO_FLG IS '同居家族子フラグ'
/
COMMENT ON COLUMN ED4334T_TBL.DOKYO_KAZOKU_OYA_FLG IS '同居家族親フラグ'
/
COMMENT ON COLUMN ED4334T_TBL.DOKYO_KAZOKU_SOFUBO_FLG IS '同居家族祖父母フラグ'
/
COMMENT ON COLUMN ED4334T_TBL.DOKYO_KAZOKU_MAGO_FLG IS '同居家族孫フラグ'
/
COMMENT ON COLUMN ED4334T_TBL.DOKYO_KAZOKU_KYODAI_SHIMAI_FLG IS '同居家族兄弟姉妹フラグ'
/
COMMENT ON COLUMN ED4334T_TBL.SNT_DKY_KZK_ZKGR_AR_FLG IS 'その他同居家族続柄有フラグ'
/
COMMENT ON COLUMN ED4334T_TBL.SNT_DKY_KZK_ZKGR_NM IS 'その他同居家族続柄名称'
/
COMMENT ON COLUMN ED4334T_TBL.KEIBIYO_DENGEN_JOHO_KBN IS '警備用電源情報区分'
/
COMMENT ON COLUMN ED4334T_TBL.BUNDEMBAN_AKINASHI_FLG IS '分電盤空き無フラグ'
/
COMMENT ON COLUMN ED4334T_TBL.DENGEN_SETCHI_BASHO_KBN IS '電源設置場所区分'
/
COMMENT ON COLUMN ED4334T_TBL.KAISEN_SETCHI_BASHO_KBN IS '回線設置場所区分'
/
COMMENT ON COLUMN ED4334T_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4334T_TBL.SEIGYO_SOCHI_CD IS '制御装置コード'
/
COMMENT ON COLUMN ED4334T_TBL.BOHAN_KANSHI_KOMOKUARI_FLG IS '防犯監視項目有フラグ'
/
COMMENT ON COLUMN ED4334T_TBL.HIJO_KANSHI_KOMOKUARI_FLG IS '非常監視項目有フラグ'
/
COMMENT ON COLUMN ED4334T_TBL.KASAI_KANSHI_KOMOKUARI_FLG IS '火災監視項目有フラグ'
/
COMMENT ON COLUMN ED4334T_TBL.SETSUBI_KANSHI_KOMOKUARI_FLG IS '設備監視項目有フラグ'
/
COMMENT ON COLUMN ED4334T_TBL.KEIBI_KUKAKUSU IS '警備区画数'
/
COMMENT ON COLUMN ED4334T_TBL.SOSA_KEY_KBN IS '操作キー区分'
/
COMMENT ON COLUMN ED4334T_TBL.SONOTA_SOSA_KEY_NM IS 'その他操作キー名称'
/
COMMENT ON COLUMN ED4334T_TBL.SOSA_KEY_SURYO IS '操作キー数量'
/
COMMENT ON COLUMN ED4334T_TBL.YSN_TYPE_OSH_BUTTON_GT_SURYO IS '有線タイプ押ボタン型数量'
/
COMMENT ON COLUMN ED4334T_TBL.MUSEN_TYPE_CARD_GATA_MAISU IS '無線タイプカード型枚数'
/
COMMENT ON COLUMN ED4334T_TBL.SONOTA_YUSEN_MUSEN_TYPE_NM IS 'その他有線無線タイプ名称'
/
COMMENT ON COLUMN ED4334T_TBL.SONOTA_YUSEN_MUSEN_TYPE_SURYO IS 'その他有線無線タイプ数量'
/
COMMENT ON COLUMN ED4334T_TBL.KASAI_SHINGO_TEST_TEHAI_KBN IS '火災信号テスト手配区分'
/
COMMENT ON COLUMN ED4334T_TBL.JKH_STSB_TNKN_JGYSH_NM IS '自火報設備点検事業所名称'
/
COMMENT ON COLUMN ED4334T_TBL.SETSUBI_SHINGO_TEST_TEHAI_KBN IS '設備信号テスト手配区分'
/
COMMENT ON COLUMN ED4334T_TBL.ALSOK_GUARD_SYSTEM_SGHKYB_FLG IS 'ＡＬＳＯＫガードシステム総合保険要望フラグ'
/
COMMENT ON COLUMN ED4334T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4334T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4334T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4334T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4334T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4334T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4334T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4334T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4334T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4334T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4334T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4334T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
