/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4358T_TBL.sql
-- 物理名：ED4358T_TBL
-- 論理名：警備診断テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4358T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4358T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIBI_SHINDAN_NO  CHAR(17) NOT NULL --「警備診断番号」
	,ANKEN_NO  CHAR(13) --「案件番号」
	,ANKEN_SHOHIN_SN  CHAR(3) --「案件商品連番」
	,ANKEN_TAISHOSAKI_SN  CHAR(7) --「案件対象先連番」
	,YOBO_JIKO_NAIYO  VARCHAR2(500) --「要望事項内容」
	,TAIO_JIKO_NAIYO  VARCHAR2(500) --「対応事項内容」
	,KEIBI_TAISHO_SHITSUSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「警備対象室数」
	,TATEMONO_SUMPO_TAKASA_M  NUMBER(9,0) DEFAULT '0' NOT NULL --「建物寸法高さメートル」
	,TATEMONO_KOZO_KBN  CHAR(1) NOT NULL --「建物構造区分」
	,TATEMONO_SUMPO_KBN  CHAR(1) NOT NULL --「建物寸法区分」
	,TATEMONO_SUMPOTATE_M  NUMBER(12,3) DEFAULT '0' NOT NULL --「建物寸法縦メートル」
	,TATEMONO_SUMPOYOKO_M  NUMBER(12,3) DEFAULT '0' NOT NULL --「建物寸法横メートル」
	,TATEMONO_SUMPO_MENSEKI  NUMBER(12,3) DEFAULT '0' NOT NULL --「建物寸法面積」
	,TATEMONO_KOJI_SHUBETSU_KBN  CHAR(1) NOT NULL --「建物工事種別区分」
	,KOSHO_SAGYOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「高所作業有フラグ」
	,TATEMONO_KEITAI_KBN  CHAR(1) NOT NULL --「建物形態区分」
	,SONOTA_TATEMONO_KEITAI_NAIYO  VARCHAR2(30) --「その他建物形態内容」
	,TATEMONO_SHOYU_KBN  CHAR(1) NOT NULL --「建物所有区分」
	,KYOJU_KEITAI_KBN  CHAR(1) NOT NULL --「居住形態区分」
	,SONOTA_KYOJU_KEITAI_NAIYO  VARCHAR2(100) --「その他居住形態内容」
	,TENJO_KOZO_KBN  CHAR(1) NOT NULL --「天井構造区分」
	,TENKENKO_KBN  CHAR(1) NOT NULL --「点検口区分」
	,SHOMEI_KBN  CHAR(1) NOT NULL --「照明区分」
	,TENJOBARI_KBN  CHAR(1) NOT NULL --「天井梁区分」
	,HAISEN_ROSHUTSUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「配線露出有フラグ」
	,SHUKAISEN_SHUBETSU_CD  CHAR(3) --「主回線種別コード」
	,SONOTA_SHUKAISEN_SHUBETSU_NM  VARCHAR2(60) --「その他主回線種別名称」
	,SHUKAISEN_SHOYU_KBN  CHAR(1) NOT NULL --「主回線所有区分」
	,SHUKAISEN_CHOSA_KEKKA_CD  CHAR(2) --「主回線調査結果コード」
	,SHUKAISEN_DEMPA_LEVEL_NAIYO  VARCHAR2(100) --「主回線電波レベル内容」
	,SHUKAISEN_JIGYOSHA_KBN  CHAR(3) NOT NULL --「主回線事業者区分」
	,SONOTA_SHUKAISEN_JIGYOSHA_NM  VARCHAR2(30) --「その他主回線事業者名称」
	,SHUKAISEN_PROVIDER_KBN  CHAR(3) NOT NULL --「主回線プロバイダ区分」
	,SONOTA_SHUKAISEN_PROVIDER_NM  VARCHAR2(30) --「その他主回線プロバイダ名称」
	,SHUKAISEN_SETSUZOKU_BASHO_NM  VARCHAR2(15) --「主回線接続場所名称」
	,SHUKAISEN_KAITSU_JOKYO_KBN  CHAR(1) NOT NULL --「主回線開通状況区分」
	,SHUKAISEN_KAITSU_YOTEI_YMD  DATE --「主回線開通予定年月日」
	,SHUKAISEN_KYOYU_KBN  CHAR(1) NOT NULL --「主回線共有区分」
	,SHUKAISEN_OYAJUCHU_KEIYAKU_NO  CHAR(15) --「主回線親受注契約番号」
	,FUKUKAISEN_SHUBETSU_CD  CHAR(3) --「副回線種別コード」
	,SONOTA_FUKUKAISEN_SHUBETSU_NM  VARCHAR2(60) --「その他副回線種別名称」
	,FUKUKAISEN_SHOYU_KBN  CHAR(1) NOT NULL --「副回線所有区分」
	,FUKUKAISEN_CHOSA_KEKKA_CD  CHAR(2) --「副回線調査結果コード」
	,FUKUKAISEN_DEMPA_LEVEL_NAIYO  VARCHAR2(100) --「副回線電波レベル内容」
	,FUKUKAISEN_JIGYOSHA_KBN  CHAR(3) NOT NULL --「副回線事業者区分」
	,SONOTA_FUKUKAISEN_JIGYOSHA_NM  VARCHAR2(30) --「その他副回線事業者名称」
	,FUKUKAISEN_PROVIDER_KBN  CHAR(3) NOT NULL --「副回線プロバイダ区分」
	,SONOTA_FUKUKAISEN_PROVIDER_NM  VARCHAR2(30) --「その他副回線プロバイダ名称」
	,FUKUKAISEN_SETSUZOKU_BASHO_NM  VARCHAR2(15) --「副回線接続場所名称」
	,FUKUKAISEN_KAITSU_JOKYO_KBN  CHAR(1) NOT NULL --「副回線開通状況区分」
	,FUKUKAISEN_KAITSU_YOTEI_YMD  DATE --「副回線開通予定年月日」
	,FUKUKAISEN_KYOYU_KBN  CHAR(1) NOT NULL --「副回線共有区分」
	,FUKUKAISEN_OYAJUCHU_KEIYAKU_NO  CHAR(15) --「副回線親受注契約番号」
	,ROUTER_KATASHIKI_NM  VARCHAR2(15) --「ルータ型式名称」
	,ROUTER_STCH_BSH_ZMN_KSIAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ルータ設置場所図面記載有フラグ」
	,AKI_PORT_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「空きポート有フラグ」
	,NETWORK_KANRISHAARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ネットワーク管理者有フラグ」
	,NETWORK_KANRISHA_NM  VARCHAR2(60) --「ネットワーク管理者氏名」
	,KOJI_TOJITSU_TACHIAIYO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「工事当日立会い要フラグ」
	,TISHSK_KISN_MTSMR_TIJ_AMT_KBN  CHAR(1) NOT NULL --「対象先回線見積提示金額区分」
	,KIB_NHN_KISH_KB_JK_KBN  CHAR(1) NOT NULL --「警備納品開始希望時期区分」
	,KIBO_YMD  DATE --「希望年月日」
	,KOJI_KIBO_YOBI_KBN  CHAR(1) NOT NULL --「工事希望曜日区分」
	,KOJI_KIBO_JIKANTAI_KBN  CHAR(1) NOT NULL --「工事希望時間帯区分」
	,YOTAKU_KAGI_TSUCHIZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「預託鍵通知済フラグ」
	,KNKY_RNRKSK_MIB_TSCHAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「緊急連絡先名簿通知有フラグ」
	,HEARING_NAIYO  VARCHAR2(500) --「ヒアリング内容」
	,BAIKYAKU_KOJIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「売却工事有フラグ」
	,BIKYK_KJ_HTCH_KITI_KBN  CHAR(1) NOT NULL --「売却工事発注形態区分」
	,JIKAI_HOMON_YOTEI_YMD  DATE --「次回訪問予定年月日」
	,HOMON_KAISHI_TM  CHAR(4) --「訪問開始時刻」
	,HOMON_SHURYO_TM  CHAR(4) --「訪問終了時刻」
	,KAKUNIN_AITE_BUSHO_NM  VARCHAR2(40) --「確認相手部署名称」
	,KAKUNIN_AITE_NM  VARCHAR2(60) --「確認相手氏名」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4358T_PK PRIMARY KEY(
	 KEIBI_SHINDAN_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4358T_TBL IS '警備診断テーブル'
/

COMMENT ON COLUMN ED4358T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4358T_TBL.KEIBI_SHINDAN_NO IS '警備診断番号'
/
COMMENT ON COLUMN ED4358T_TBL.ANKEN_NO IS '案件番号'
/
COMMENT ON COLUMN ED4358T_TBL.ANKEN_SHOHIN_SN IS '案件商品連番'
/
COMMENT ON COLUMN ED4358T_TBL.ANKEN_TAISHOSAKI_SN IS '案件対象先連番'
/
COMMENT ON COLUMN ED4358T_TBL.YOBO_JIKO_NAIYO IS '要望事項内容'
/
COMMENT ON COLUMN ED4358T_TBL.TAIO_JIKO_NAIYO IS '対応事項内容'
/
COMMENT ON COLUMN ED4358T_TBL.KEIBI_TAISHO_SHITSUSU IS '警備対象室数'
/
COMMENT ON COLUMN ED4358T_TBL.TATEMONO_SUMPO_TAKASA_M IS '建物寸法高さメートル'
/
COMMENT ON COLUMN ED4358T_TBL.TATEMONO_KOZO_KBN IS '建物構造区分'
/
COMMENT ON COLUMN ED4358T_TBL.TATEMONO_SUMPO_KBN IS '建物寸法区分'
/
COMMENT ON COLUMN ED4358T_TBL.TATEMONO_SUMPOTATE_M IS '建物寸法縦メートル'
/
COMMENT ON COLUMN ED4358T_TBL.TATEMONO_SUMPOYOKO_M IS '建物寸法横メートル'
/
COMMENT ON COLUMN ED4358T_TBL.TATEMONO_SUMPO_MENSEKI IS '建物寸法面積'
/
COMMENT ON COLUMN ED4358T_TBL.TATEMONO_KOJI_SHUBETSU_KBN IS '建物工事種別区分'
/
COMMENT ON COLUMN ED4358T_TBL.KOSHO_SAGYOARI_FLG IS '高所作業有フラグ'
/
COMMENT ON COLUMN ED4358T_TBL.TATEMONO_KEITAI_KBN IS '建物形態区分'
/
COMMENT ON COLUMN ED4358T_TBL.SONOTA_TATEMONO_KEITAI_NAIYO IS 'その他建物形態内容'
/
COMMENT ON COLUMN ED4358T_TBL.TATEMONO_SHOYU_KBN IS '建物所有区分'
/
COMMENT ON COLUMN ED4358T_TBL.KYOJU_KEITAI_KBN IS '居住形態区分'
/
COMMENT ON COLUMN ED4358T_TBL.SONOTA_KYOJU_KEITAI_NAIYO IS 'その他居住形態内容'
/
COMMENT ON COLUMN ED4358T_TBL.TENJO_KOZO_KBN IS '天井構造区分'
/
COMMENT ON COLUMN ED4358T_TBL.TENKENKO_KBN IS '点検口区分'
/
COMMENT ON COLUMN ED4358T_TBL.SHOMEI_KBN IS '照明区分'
/
COMMENT ON COLUMN ED4358T_TBL.TENJOBARI_KBN IS '天井梁区分'
/
COMMENT ON COLUMN ED4358T_TBL.HAISEN_ROSHUTSUARI_FLG IS '配線露出有フラグ'
/
COMMENT ON COLUMN ED4358T_TBL.SHUKAISEN_SHUBETSU_CD IS '主回線種別コード'
/
COMMENT ON COLUMN ED4358T_TBL.SONOTA_SHUKAISEN_SHUBETSU_NM IS 'その他主回線種別名称'
/
COMMENT ON COLUMN ED4358T_TBL.SHUKAISEN_SHOYU_KBN IS '主回線所有区分'
/
COMMENT ON COLUMN ED4358T_TBL.SHUKAISEN_CHOSA_KEKKA_CD IS '主回線調査結果コード'
/
COMMENT ON COLUMN ED4358T_TBL.SHUKAISEN_DEMPA_LEVEL_NAIYO IS '主回線電波レベル内容'
/
COMMENT ON COLUMN ED4358T_TBL.SHUKAISEN_JIGYOSHA_KBN IS '主回線事業者区分'
/
COMMENT ON COLUMN ED4358T_TBL.SONOTA_SHUKAISEN_JIGYOSHA_NM IS 'その他主回線事業者名称'
/
COMMENT ON COLUMN ED4358T_TBL.SHUKAISEN_PROVIDER_KBN IS '主回線プロバイダ区分'
/
COMMENT ON COLUMN ED4358T_TBL.SONOTA_SHUKAISEN_PROVIDER_NM IS 'その他主回線プロバイダ名称'
/
COMMENT ON COLUMN ED4358T_TBL.SHUKAISEN_SETSUZOKU_BASHO_NM IS '主回線接続場所名称'
/
COMMENT ON COLUMN ED4358T_TBL.SHUKAISEN_KAITSU_JOKYO_KBN IS '主回線開通状況区分'
/
COMMENT ON COLUMN ED4358T_TBL.SHUKAISEN_KAITSU_YOTEI_YMD IS '主回線開通予定年月日'
/
COMMENT ON COLUMN ED4358T_TBL.SHUKAISEN_KYOYU_KBN IS '主回線共有区分'
/
COMMENT ON COLUMN ED4358T_TBL.SHUKAISEN_OYAJUCHU_KEIYAKU_NO IS '主回線親受注契約番号'
/
COMMENT ON COLUMN ED4358T_TBL.FUKUKAISEN_SHUBETSU_CD IS '副回線種別コード'
/
COMMENT ON COLUMN ED4358T_TBL.SONOTA_FUKUKAISEN_SHUBETSU_NM IS 'その他副回線種別名称'
/
COMMENT ON COLUMN ED4358T_TBL.FUKUKAISEN_SHOYU_KBN IS '副回線所有区分'
/
COMMENT ON COLUMN ED4358T_TBL.FUKUKAISEN_CHOSA_KEKKA_CD IS '副回線調査結果コード'
/
COMMENT ON COLUMN ED4358T_TBL.FUKUKAISEN_DEMPA_LEVEL_NAIYO IS '副回線電波レベル内容'
/
COMMENT ON COLUMN ED4358T_TBL.FUKUKAISEN_JIGYOSHA_KBN IS '副回線事業者区分'
/
COMMENT ON COLUMN ED4358T_TBL.SONOTA_FUKUKAISEN_JIGYOSHA_NM IS 'その他副回線事業者名称'
/
COMMENT ON COLUMN ED4358T_TBL.FUKUKAISEN_PROVIDER_KBN IS '副回線プロバイダ区分'
/
COMMENT ON COLUMN ED4358T_TBL.SONOTA_FUKUKAISEN_PROVIDER_NM IS 'その他副回線プロバイダ名称'
/
COMMENT ON COLUMN ED4358T_TBL.FUKUKAISEN_SETSUZOKU_BASHO_NM IS '副回線接続場所名称'
/
COMMENT ON COLUMN ED4358T_TBL.FUKUKAISEN_KAITSU_JOKYO_KBN IS '副回線開通状況区分'
/
COMMENT ON COLUMN ED4358T_TBL.FUKUKAISEN_KAITSU_YOTEI_YMD IS '副回線開通予定年月日'
/
COMMENT ON COLUMN ED4358T_TBL.FUKUKAISEN_KYOYU_KBN IS '副回線共有区分'
/
COMMENT ON COLUMN ED4358T_TBL.FUKUKAISEN_OYAJUCHU_KEIYAKU_NO IS '副回線親受注契約番号'
/
COMMENT ON COLUMN ED4358T_TBL.ROUTER_KATASHIKI_NM IS 'ルータ型式名称'
/
COMMENT ON COLUMN ED4358T_TBL.ROUTER_STCH_BSH_ZMN_KSIAR_FLG IS 'ルータ設置場所図面記載有フラグ'
/
COMMENT ON COLUMN ED4358T_TBL.AKI_PORT_ARI_FLG IS '空きポート有フラグ'
/
COMMENT ON COLUMN ED4358T_TBL.NETWORK_KANRISHAARI_FLG IS 'ネットワーク管理者有フラグ'
/
COMMENT ON COLUMN ED4358T_TBL.NETWORK_KANRISHA_NM IS 'ネットワーク管理者氏名'
/
COMMENT ON COLUMN ED4358T_TBL.KOJI_TOJITSU_TACHIAIYO_FLG IS '工事当日立会い要フラグ'
/
COMMENT ON COLUMN ED4358T_TBL.TISHSK_KISN_MTSMR_TIJ_AMT_KBN IS '対象先回線見積提示金額区分'
/
COMMENT ON COLUMN ED4358T_TBL.KIB_NHN_KISH_KB_JK_KBN IS '警備納品開始希望時期区分'
/
COMMENT ON COLUMN ED4358T_TBL.KIBO_YMD IS '希望年月日'
/
COMMENT ON COLUMN ED4358T_TBL.KOJI_KIBO_YOBI_KBN IS '工事希望曜日区分'
/
COMMENT ON COLUMN ED4358T_TBL.KOJI_KIBO_JIKANTAI_KBN IS '工事希望時間帯区分'
/
COMMENT ON COLUMN ED4358T_TBL.YOTAKU_KAGI_TSUCHIZUMI_FLG IS '預託鍵通知済フラグ'
/
COMMENT ON COLUMN ED4358T_TBL.KNKY_RNRKSK_MIB_TSCHAR_FLG IS '緊急連絡先名簿通知有フラグ'
/
COMMENT ON COLUMN ED4358T_TBL.HEARING_NAIYO IS 'ヒアリング内容'
/
COMMENT ON COLUMN ED4358T_TBL.BAIKYAKU_KOJIARI_FLG IS '売却工事有フラグ'
/
COMMENT ON COLUMN ED4358T_TBL.BIKYK_KJ_HTCH_KITI_KBN IS '売却工事発注形態区分'
/
COMMENT ON COLUMN ED4358T_TBL.JIKAI_HOMON_YOTEI_YMD IS '次回訪問予定年月日'
/
COMMENT ON COLUMN ED4358T_TBL.HOMON_KAISHI_TM IS '訪問開始時刻'
/
COMMENT ON COLUMN ED4358T_TBL.HOMON_SHURYO_TM IS '訪問終了時刻'
/
COMMENT ON COLUMN ED4358T_TBL.KAKUNIN_AITE_BUSHO_NM IS '確認相手部署名称'
/
COMMENT ON COLUMN ED4358T_TBL.KAKUNIN_AITE_NM IS '確認相手氏名'
/
COMMENT ON COLUMN ED4358T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4358T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4358T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4358T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4358T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4358T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4358T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4358T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4358T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4358T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4358T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4358T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
