/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4317T_TBL.sql
-- 物理名：ED4317T_TBL
-- 論理名：積算提案保険テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4317T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4317T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIYAKU_ID  CHAR(18) NOT NULL --「契約ＩＤ」
	,SEKISAN_HOKEN_CD  CHAR(4) NOT NULL --「積算保険コード」
	,HYOJI_JUN_1  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順１」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「受注契約変更番号」
	,ANKEN_NO  CHAR(13) --「案件番号」
	,ANKEN_SHOHIN_SN  CHAR(3) --「案件商品連番」
	,ANKEN_TAISHOSAKI_SN  CHAR(7) --「案件対象先連番」
	,SHOHIN_SERVICE_CD  CHAR(3) --「商品サービスコード」
	,HEARING_SHEET_SHTSRYK_ZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ヒアリングシート出力済フラグ」
	,TEIAN_SENTAKU_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「提案選択有フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4317T_PK PRIMARY KEY(
	 KEIYAKU_ID
	,  SEKISAN_HOKEN_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4317T_TBL IS '積算提案保険テーブル'
/

COMMENT ON COLUMN ED4317T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4317T_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED4317T_TBL.SEKISAN_HOKEN_CD IS '積算保険コード'
/
COMMENT ON COLUMN ED4317T_TBL.HYOJI_JUN_1 IS '表示順１'
/
COMMENT ON COLUMN ED4317T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED4317T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED4317T_TBL.ANKEN_NO IS '案件番号'
/
COMMENT ON COLUMN ED4317T_TBL.ANKEN_SHOHIN_SN IS '案件商品連番'
/
COMMENT ON COLUMN ED4317T_TBL.ANKEN_TAISHOSAKI_SN IS '案件対象先連番'
/
COMMENT ON COLUMN ED4317T_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4317T_TBL.HEARING_SHEET_SHTSRYK_ZUMI_FLG IS 'ヒアリングシート出力済フラグ'
/
COMMENT ON COLUMN ED4317T_TBL.TEIAN_SENTAKU_ARI_FLG IS '提案選択有フラグ'
/
COMMENT ON COLUMN ED4317T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4317T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4317T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4317T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4317T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4317T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4317T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4317T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4317T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4317T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4317T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4317T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
