/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4307T_TBL.sql
-- 物理名：ED4307T_TBL
-- 論理名：積算契約ステータス表示テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4307T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4307T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIYAKU_ID  CHAR(18) NOT NULL --「契約ＩＤ」
	,KEIBI_SHINDAN_NO  CHAR(17) --「警備診断番号」
	,SEKISAN_NO  CHAR(17) --「積算番号」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「受注契約変更番号」
	,SKSN_KIYK_STATUS_HYJ_AREA_KBN  CHAR(1) NOT NULL --「積算契約ステータス表示エリア区分」
	,SKSN_KIYK_STATUS_HYJ_SN  CHAR(14) NOT NULL --「積算契約ステータス表示連番」
	,SKSNKYK_KYKKNRN_GMKT_STATUS_CD  CHAR(5) NOT NULL --「積算契約契約関連画面共通ステータスコード」
	,SKSNKYK_KYKKNRN_GMKT_STATUS_NM  VARCHAR2(60) --「積算契約契約関連画面共通ステータス名称」
	,SKSN_KIYK_STATUS_KASSEI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「積算契約ステータス活性フラグ」
	,SKSN_KIYK_STATUS_KNRY_JDST_FLG  CHAR(1) DEFAULT '0' NOT NULL --「積算契約ステータス完了自動設定フラグ」
	,SKSN_KIYK_STATUS_KNRY_HJ_NAIYO  VARCHAR2(1000) --「積算契約ステータス完了判定条件内容」
	,HITSUYO_SHORUIRAN_HYOJI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「必要書類欄表示フラグ」
	,SKSN_KIYK_STATUS_KNRY_FLG  CHAR(1) DEFAULT '0' NOT NULL --「積算契約ステータス完了フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4307T_PK PRIMARY KEY(
	 KEIYAKU_ID
	,  SKSN_KIYK_STATUS_HYJ_AREA_KBN
	,  SKSN_KIYK_STATUS_HYJ_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4307T_TBL IS '積算契約ステータス表示テーブル'
/

COMMENT ON COLUMN ED4307T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4307T_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED4307T_TBL.KEIBI_SHINDAN_NO IS '警備診断番号'
/
COMMENT ON COLUMN ED4307T_TBL.SEKISAN_NO IS '積算番号'
/
COMMENT ON COLUMN ED4307T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED4307T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED4307T_TBL.SKSN_KIYK_STATUS_HYJ_AREA_KBN IS '積算契約ステータス表示エリア区分'
/
COMMENT ON COLUMN ED4307T_TBL.SKSN_KIYK_STATUS_HYJ_SN IS '積算契約ステータス表示連番'
/
COMMENT ON COLUMN ED4307T_TBL.SKSNKYK_KYKKNRN_GMKT_STATUS_CD IS '積算契約契約関連画面共通ステータスコード'
/
COMMENT ON COLUMN ED4307T_TBL.SKSNKYK_KYKKNRN_GMKT_STATUS_NM IS '積算契約契約関連画面共通ステータス名称'
/
COMMENT ON COLUMN ED4307T_TBL.SKSN_KIYK_STATUS_KASSEI_FLG IS '積算契約ステータス活性フラグ'
/
COMMENT ON COLUMN ED4307T_TBL.SKSN_KIYK_STATUS_KNRY_JDST_FLG IS '積算契約ステータス完了自動設定フラグ'
/
COMMENT ON COLUMN ED4307T_TBL.SKSN_KIYK_STATUS_KNRY_HJ_NAIYO IS '積算契約ステータス完了判定条件内容'
/
COMMENT ON COLUMN ED4307T_TBL.HITSUYO_SHORUIRAN_HYOJI_FLG IS '必要書類欄表示フラグ'
/
COMMENT ON COLUMN ED4307T_TBL.SKSN_KIYK_STATUS_KNRY_FLG IS '積算契約ステータス完了フラグ'
/
COMMENT ON COLUMN ED4307T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4307T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4307T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4307T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4307T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4307T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4307T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4307T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4307T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4307T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4307T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4307T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
