/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4347T_TBL.sql
-- 物理名：ED4347T_TBL
-- 論理名：詳細積算依頼テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4347T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4347T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIYAKU_ID  CHAR(18) NOT NULL --「契約ＩＤ」
	,SHOSAI_SEKISAN_IRAI_SN  CHAR(14) NOT NULL --「詳細積算依頼連番」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,IRAI_DT  TIMESTAMP NOT NULL --「依頼日時」
	,TAISHOSAKI_TANTOSHA_NM  VARCHAR2(60) --「対象先担当者氏名」
	,TAISHOSAKI_TANTOSHA_BUSHO_NM  VARCHAR2(40) --「対象先担当者部署名称」
	,TISHSK_TNTSH_YKSHK_NM  VARCHAR2(200) --「対象先担当者役職名称」
	,DENWA_NO  VARCHAR2(20) --「電話番号」
	,KAITO_KIBO_YMD  DATE NOT NULL --「回答希望年月日」
	,ZENTAI_CMNT_NAIYO  VARCHAR2(1000) --「全体コメント内容」
	,SHINSEISHA_JIGYOSHO_CD  CHAR(6) --「申請者事業所コード」
	,SHINSEISHA_SHAIN_NO  VARCHAR2(8) --「申請者社員番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4347T_PK PRIMARY KEY(
	 KEIYAKU_ID
	,  SHOSAI_SEKISAN_IRAI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4347T_TBL IS '詳細積算依頼テーブル'
/

COMMENT ON COLUMN ED4347T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4347T_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED4347T_TBL.SHOSAI_SEKISAN_IRAI_SN IS '詳細積算依頼連番'
/
COMMENT ON COLUMN ED4347T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED4347T_TBL.IRAI_DT IS '依頼日時'
/
COMMENT ON COLUMN ED4347T_TBL.TAISHOSAKI_TANTOSHA_NM IS '対象先担当者氏名'
/
COMMENT ON COLUMN ED4347T_TBL.TAISHOSAKI_TANTOSHA_BUSHO_NM IS '対象先担当者部署名称'
/
COMMENT ON COLUMN ED4347T_TBL.TISHSK_TNTSH_YKSHK_NM IS '対象先担当者役職名称'
/
COMMENT ON COLUMN ED4347T_TBL.DENWA_NO IS '電話番号'
/
COMMENT ON COLUMN ED4347T_TBL.KAITO_KIBO_YMD IS '回答希望年月日'
/
COMMENT ON COLUMN ED4347T_TBL.ZENTAI_CMNT_NAIYO IS '全体コメント内容'
/
COMMENT ON COLUMN ED4347T_TBL.SHINSEISHA_JIGYOSHO_CD IS '申請者事業所コード'
/
COMMENT ON COLUMN ED4347T_TBL.SHINSEISHA_SHAIN_NO IS '申請者社員番号'
/
COMMENT ON COLUMN ED4347T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4347T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4347T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4347T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4347T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4347T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4347T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4347T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4347T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4347T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4347T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4347T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
