/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4312T_TBL.sql
-- 物理名：ED4312T_TBL
-- 論理名：受注申請テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4312T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4312T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_SHINSEI_NO  CHAR(20) NOT NULL --「受注申請番号」
	,ANKEN_NO  CHAR(13) --「案件番号」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,JUCHU_SHINSEI_DT  TIMESTAMP --「受注申請日時」
	,JUCHU_SHINSEI_MEMO_NAIYO  VARCHAR2(200) --「受注申請メモ内容」
	,SHINSEISHA_SHAIN_NO  VARCHAR2(8) --「申請者社員番号」
	,TANTO_SHAIN_NO  VARCHAR2(8) --「担当社員番号」
	,SKSN_HNSH_MTM_SHNN_KBN  CHAR(1) NOT NULL --「積算本社まとめ承認区分」
	,JUCHU_SHONIN_DT  TIMESTAMP --「受注承認日時」
	,JUCHU_SHINSEI_JIGYOSHO_CD  CHAR(6) --「受注申請事業所コード」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4312T_PK PRIMARY KEY(
	 JUCHU_SHINSEI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4312T_TBL IS '受注申請テーブル'
/

COMMENT ON COLUMN ED4312T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4312T_TBL.JUCHU_SHINSEI_NO IS '受注申請番号'
/
COMMENT ON COLUMN ED4312T_TBL.ANKEN_NO IS '案件番号'
/
COMMENT ON COLUMN ED4312T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED4312T_TBL.JUCHU_SHINSEI_DT IS '受注申請日時'
/
COMMENT ON COLUMN ED4312T_TBL.JUCHU_SHINSEI_MEMO_NAIYO IS '受注申請メモ内容'
/
COMMENT ON COLUMN ED4312T_TBL.SHINSEISHA_SHAIN_NO IS '申請者社員番号'
/
COMMENT ON COLUMN ED4312T_TBL.TANTO_SHAIN_NO IS '担当社員番号'
/
COMMENT ON COLUMN ED4312T_TBL.SKSN_HNSH_MTM_SHNN_KBN IS '積算本社まとめ承認区分'
/
COMMENT ON COLUMN ED4312T_TBL.JUCHU_SHONIN_DT IS '受注承認日時'
/
COMMENT ON COLUMN ED4312T_TBL.JUCHU_SHINSEI_JIGYOSHO_CD IS '受注申請事業所コード'
/
COMMENT ON COLUMN ED4312T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4312T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4312T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4312T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4312T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4312T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4312T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4312T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4312T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4312T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4312T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4312T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
