/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4344T_TBL.sql
-- 物理名：ED4344T_TBL
-- 論理名：見積書テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4344T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4344T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,MITSUMORISHO_GROUP_ID  NUMBER(11,0) DEFAULT '0' NOT NULL --「見積書グループＩＤ」
	,MITSUMORISHO_GROUP_MEISAI_NO  NUMBER(12,0) DEFAULT '0' NOT NULL --「見積書グループ明細番号」
	,MITSUMORISHO_RIREKI_SN  CHAR(14) NOT NULL --「見積書履歴連番」
	,SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,JUCHU_SHINSEI_NO  CHAR(20) --「受注申請番号」
	,MITSUMORISHO_NO  CHAR(20) --「見積書番号」
	,KEIYAKU_ID  CHAR(18) --「契約ＩＤ」
	,MITSUMORI_TEIJI_GETSUGAKU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「見積提示月額金額」
	,MITSUMORI_TEIJI_NENGAKU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「見積提示年額金額」
	,MITSUMORISHO_TEIJI_SOGAKU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「見積提示総額金額」
	,MITSUMORI_TEIJI_KOJIGAKU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「見積提示工事額金額」
	,MTSMR_TIJ_BIKYK_KKGK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「見積提示売却機器額金額」
	,MTSMR_TIJ_BIKYK_KJGK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「見積提示売却工事額金額」
	,MTSMR_TIJ_HOSHO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「見積提示保証金額」
	,MTSMR_TIJ_HOKEN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「見積提示保険金額」
	,MITSUMORI_YMD  DATE --「見積年月日」
	,MITSUMORI_YUKO_KIGEN_YMD  DATE --「見積有効期限年月日」
	,MITSUMORISHO_TEIAN_NAIYO  VARCHAR2(100) --「見積書提案内容」
	,INEIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「印影有フラグ」
	,TEIGITAI_VERSION_NO  CHAR(8) --「定義体バージョン番号」
	,MITSUMORISHO_HENKO_DT  TIMESTAMP --「見積書変更日時」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,MITSUMORI_TEMPU_SHORUI_NM  VARCHAR2(30) --「見積添付書類名称」
	,MITSUMORI_INSATSU_YMD  DATE --「見積印刷年月日」
	,SONOTA_MTSMR_HY_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「その他見積費用金額」
	,MITSUMORISHO_RIREKI_HYOJI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「見積書履歴表示フラグ」
	,SHOKI_HYOJI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「初期表示フラグ」
	,MITSUMORISHO_FILE_NM  VARCHAR2(60) NOT NULL --「見積書ファイル名称」
	,KAIYAKU_AMT_HYOJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「解約金額標準金額」
	,KEIYAKU_HYOJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「契約標準金額」
	,KEIYAKU_SOGAKU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「契約総額金額」
	,ANKEN_HANEI_ZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「案件反映済フラグ」
	,SEKISAN_NO  CHAR(17) --「積算番号」
	,ANKEN_NO  CHAR(13) --「案件番号」
	,SET_HAMBAI_TAISHO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「セット販売対象フラグ」
	,MTSMRSH_SHONINSHA_SHAIN_NO  VARCHAR2(8) --「見積書承認者社員番号」
	,MTSMRSH_HYOJI_JIGYOSHO_CD  CHAR(6) --「見積書表示事業所コード」
	,MTSMRSH_SHTSRYK_SHHN_SRVC_CD  CHAR(3) NOT NULL --「見積書出力商品サービスコード」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4344T_PK PRIMARY KEY(
	 MITSUMORISHO_GROUP_ID
	,  MITSUMORISHO_GROUP_MEISAI_NO
	,  MITSUMORISHO_RIREKI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4344T_TBL IS '見積書テーブル'
/

COMMENT ON COLUMN ED4344T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORISHO_GROUP_ID IS '見積書グループＩＤ'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORISHO_GROUP_MEISAI_NO IS '見積書グループ明細番号'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORISHO_RIREKI_SN IS '見積書履歴連番'
/
COMMENT ON COLUMN ED4344T_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4344T_TBL.JUCHU_SHINSEI_NO IS '受注申請番号'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORISHO_NO IS '見積書番号'
/
COMMENT ON COLUMN ED4344T_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORI_TEIJI_GETSUGAKU_AMT IS '見積提示月額金額'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORI_TEIJI_NENGAKU_AMT IS '見積提示年額金額'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORISHO_TEIJI_SOGAKU_AMT IS '見積提示総額金額'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORI_TEIJI_KOJIGAKU_AMT IS '見積提示工事額金額'
/
COMMENT ON COLUMN ED4344T_TBL.MTSMR_TIJ_BIKYK_KKGK_AMT IS '見積提示売却機器額金額'
/
COMMENT ON COLUMN ED4344T_TBL.MTSMR_TIJ_BIKYK_KJGK_AMT IS '見積提示売却工事額金額'
/
COMMENT ON COLUMN ED4344T_TBL.MTSMR_TIJ_HOSHO_AMT IS '見積提示保証金額'
/
COMMENT ON COLUMN ED4344T_TBL.MTSMR_TIJ_HOKEN_AMT IS '見積提示保険金額'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORI_YMD IS '見積年月日'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORI_YUKO_KIGEN_YMD IS '見積有効期限年月日'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORISHO_TEIAN_NAIYO IS '見積書提案内容'
/
COMMENT ON COLUMN ED4344T_TBL.INEIARI_FLG IS '印影有フラグ'
/
COMMENT ON COLUMN ED4344T_TBL.TEIGITAI_VERSION_NO IS '定義体バージョン番号'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORISHO_HENKO_DT IS '見積書変更日時'
/
COMMENT ON COLUMN ED4344T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORI_TEMPU_SHORUI_NM IS '見積添付書類名称'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORI_INSATSU_YMD IS '見積印刷年月日'
/
COMMENT ON COLUMN ED4344T_TBL.SONOTA_MTSMR_HY_AMT IS 'その他見積費用金額'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORISHO_RIREKI_HYOJI_FLG IS '見積書履歴表示フラグ'
/
COMMENT ON COLUMN ED4344T_TBL.SHOKI_HYOJI_FLG IS '初期表示フラグ'
/
COMMENT ON COLUMN ED4344T_TBL.MITSUMORISHO_FILE_NM IS '見積書ファイル名称'
/
COMMENT ON COLUMN ED4344T_TBL.KAIYAKU_AMT_HYOJUN_AMT IS '解約金額標準金額'
/
COMMENT ON COLUMN ED4344T_TBL.KEIYAKU_HYOJUN_AMT IS '契約標準金額'
/
COMMENT ON COLUMN ED4344T_TBL.KEIYAKU_SOGAKU_AMT IS '契約総額金額'
/
COMMENT ON COLUMN ED4344T_TBL.ANKEN_HANEI_ZUMI_FLG IS '案件反映済フラグ'
/
COMMENT ON COLUMN ED4344T_TBL.SEKISAN_NO IS '積算番号'
/
COMMENT ON COLUMN ED4344T_TBL.ANKEN_NO IS '案件番号'
/
COMMENT ON COLUMN ED4344T_TBL.SET_HAMBAI_TAISHO_FLG IS 'セット販売対象フラグ'
/
COMMENT ON COLUMN ED4344T_TBL.MTSMRSH_SHONINSHA_SHAIN_NO IS '見積書承認者社員番号'
/
COMMENT ON COLUMN ED4344T_TBL.MTSMRSH_HYOJI_JIGYOSHO_CD IS '見積書表示事業所コード'
/
COMMENT ON COLUMN ED4344T_TBL.MTSMRSH_SHTSRYK_SHHN_SRVC_CD IS '見積書出力商品サービスコード'
/
COMMENT ON COLUMN ED4344T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4344T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4344T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4344T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4344T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4344T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4344T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4344T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4344T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4344T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4344T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
