/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4397T_TBL.sql
-- 物理名：ED4397T_TBL
-- 論理名：積算添付ファイル管理テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4397T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4397T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,FILE_SHIKIBETSU_KEY  VARCHAR2(255) NOT NULL --「ファイル識別キー」
	,KEIYAKU_ID  CHAR(18) --「契約ＩＤ」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「受注契約変更番号」
	,KEIBI_SHINDAN_NO  CHAR(17) --「警備診断番号」
	,KOJI_SHIJISHO_NO  CHAR(18) --「工事指示書番号」
	,SHUTSUDO_JISSEKI_NO  CHAR(5) --「出動実績番号」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,TEMPU_FILE_KANRI_SN  CHAR(14) --「添付ファイル管理連番」
	,TEMPU_FILE_SHUBETSU_KBN  CHAR(1) NOT NULL --「添付ファイル種別区分」
	,TEMPU_SHIRYO_FILE_NM  VARCHAR2(255) --「添付資料ファイル名称」
	,TEMPU_FILE_HYOJI_GAMEN_ID  CHAR(15) --「添付ファイル表示画面ＩＤ」
	,TMP_FILE_HYJ_SECTION_KOMOKU_NO  NUMBER(9,0) DEFAULT '0' NOT NULL --「添付ファイル表示セクション項目番号」
	,TEMPU_FILE_UPLOAD_GAMEN_ID  CHAR(15) --「添付ファイルアップロード画面ＩＤ」
	,TEMPU_FILE_UPLOAD_DT  TIMESTAMP --「添付ファイルアップロード日時」
	,TEMPU_FILE_KOSHIN_DT  TIMESTAMP --「添付ファイル更新日時」
	,TEMPU_FILE_SAKUJO_DT  TIMESTAMP --「添付ファイル削除日時」
	,TEMPU_FILE_UPLOAD_JIGYOSHO_CD  CHAR(6) --「添付ファイルアップロード事業所コード」
	,TEMPU_FILE_UPLOAD_SHAIN_NO  VARCHAR2(8) --「添付ファイルアップロード社員番号」
	,TEMPU_FILE_KOSHIN_JIGYOSHO_CD  CHAR(6) --「添付ファイル更新事業所コード」
	,TEMPU_FILE_KOSHIN_SHAIN_NO  VARCHAR2(8) --「添付ファイル更新社員番号」
	,SEKISAN_SECTION_KBN  CHAR(2) NOT NULL --「積算セクション区分」
	,KYOCHO_IRAI_NO  CHAR(24) --「協調依頼番号」
	,RONRI_SAKUJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「論理削除フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4397T_PK PRIMARY KEY(
	 FILE_SHIKIBETSU_KEY
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4397T_TBL IS '積算添付ファイル管理テーブル'
/

COMMENT ON COLUMN ED4397T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4397T_TBL.FILE_SHIKIBETSU_KEY IS 'ファイル識別キー'
/
COMMENT ON COLUMN ED4397T_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED4397T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED4397T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED4397T_TBL.KEIBI_SHINDAN_NO IS '警備診断番号'
/
COMMENT ON COLUMN ED4397T_TBL.KOJI_SHIJISHO_NO IS '工事指示書番号'
/
COMMENT ON COLUMN ED4397T_TBL.SHUTSUDO_JISSEKI_NO IS '出動実績番号'
/
COMMENT ON COLUMN ED4397T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED4397T_TBL.TEMPU_FILE_KANRI_SN IS '添付ファイル管理連番'
/
COMMENT ON COLUMN ED4397T_TBL.TEMPU_FILE_SHUBETSU_KBN IS '添付ファイル種別区分'
/
COMMENT ON COLUMN ED4397T_TBL.TEMPU_SHIRYO_FILE_NM IS '添付資料ファイル名称'
/
COMMENT ON COLUMN ED4397T_TBL.TEMPU_FILE_HYOJI_GAMEN_ID IS '添付ファイル表示画面ＩＤ'
/
COMMENT ON COLUMN ED4397T_TBL.TMP_FILE_HYJ_SECTION_KOMOKU_NO IS '添付ファイル表示セクション項目番号'
/
COMMENT ON COLUMN ED4397T_TBL.TEMPU_FILE_UPLOAD_GAMEN_ID IS '添付ファイルアップロード画面ＩＤ'
/
COMMENT ON COLUMN ED4397T_TBL.TEMPU_FILE_UPLOAD_DT IS '添付ファイルアップロード日時'
/
COMMENT ON COLUMN ED4397T_TBL.TEMPU_FILE_KOSHIN_DT IS '添付ファイル更新日時'
/
COMMENT ON COLUMN ED4397T_TBL.TEMPU_FILE_SAKUJO_DT IS '添付ファイル削除日時'
/
COMMENT ON COLUMN ED4397T_TBL.TEMPU_FILE_UPLOAD_JIGYOSHO_CD IS '添付ファイルアップロード事業所コード'
/
COMMENT ON COLUMN ED4397T_TBL.TEMPU_FILE_UPLOAD_SHAIN_NO IS '添付ファイルアップロード社員番号'
/
COMMENT ON COLUMN ED4397T_TBL.TEMPU_FILE_KOSHIN_JIGYOSHO_CD IS '添付ファイル更新事業所コード'
/
COMMENT ON COLUMN ED4397T_TBL.TEMPU_FILE_KOSHIN_SHAIN_NO IS '添付ファイル更新社員番号'
/
COMMENT ON COLUMN ED4397T_TBL.SEKISAN_SECTION_KBN IS '積算セクション区分'
/
COMMENT ON COLUMN ED4397T_TBL.KYOCHO_IRAI_NO IS '協調依頼番号'
/
COMMENT ON COLUMN ED4397T_TBL.RONRI_SAKUJO_FLG IS '論理削除フラグ'
/
COMMENT ON COLUMN ED4397T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4397T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4397T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4397T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4397T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4397T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4397T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4397T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4397T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4397T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4397T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4397T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
