/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4375T_TBL.sql
-- 物理名：ED4375T_TBL
-- 論理名：詳細積算依頼先テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4375T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4375T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIYAKU_ID  CHAR(18) NOT NULL --「契約ＩＤ」
	,SHOSAI_SEKISAN_IRAI_SN  CHAR(14) NOT NULL --「詳細積算依頼連番」
	,SHOSAI_SEKISAN_IRAISAKI_KBN  CHAR(1) NOT NULL --「詳細積算依頼先区分」
	,SHOSAI_SEKISAN_IRAISAKI_SN  CHAR(14) NOT NULL --「詳細積算依頼先連番」
	,SKSN_KNR_KOMOKU_DIKMK_CD  CHAR(10) --「積算管理項目大項目コード」
	,SKSN_KNR_KOMOKU_CHKMK_CD  CHAR(10) --「積算管理項目中項目コード」
	,SKSN_KNR_KOMOKU_SHKMK_NAIYO  VARCHAR2(100) --「積算管理項目小項目内容」
	,IRAISAKI_JIGYOSHO_CD  CHAR(6) --「依頼先事業所コード」
	,IRAISAKI_TRHKSK_CD  CHAR(9) --「依頼先取引先コード」
	,IRISK_TRHKSK_CD  CHAR(4) --「依頼先取引先部署コード」
	,IRAISAKI_IRAI_CMNT  VARCHAR2(50) --「依頼先依頼コメント」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4375T_PK PRIMARY KEY(
	 KEIYAKU_ID
	,  SHOSAI_SEKISAN_IRAI_SN
	,  SHOSAI_SEKISAN_IRAISAKI_KBN
	,  SHOSAI_SEKISAN_IRAISAKI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4375T_TBL IS '詳細積算依頼先テーブル'
/

COMMENT ON COLUMN ED4375T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4375T_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED4375T_TBL.SHOSAI_SEKISAN_IRAI_SN IS '詳細積算依頼連番'
/
COMMENT ON COLUMN ED4375T_TBL.SHOSAI_SEKISAN_IRAISAKI_KBN IS '詳細積算依頼先区分'
/
COMMENT ON COLUMN ED4375T_TBL.SHOSAI_SEKISAN_IRAISAKI_SN IS '詳細積算依頼先連番'
/
COMMENT ON COLUMN ED4375T_TBL.SKSN_KNR_KOMOKU_DIKMK_CD IS '積算管理項目大項目コード'
/
COMMENT ON COLUMN ED4375T_TBL.SKSN_KNR_KOMOKU_CHKMK_CD IS '積算管理項目中項目コード'
/
COMMENT ON COLUMN ED4375T_TBL.SKSN_KNR_KOMOKU_SHKMK_NAIYO IS '積算管理項目小項目内容'
/
COMMENT ON COLUMN ED4375T_TBL.IRAISAKI_JIGYOSHO_CD IS '依頼先事業所コード'
/
COMMENT ON COLUMN ED4375T_TBL.IRAISAKI_TRHKSK_CD IS '依頼先取引先コード'
/
COMMENT ON COLUMN ED4375T_TBL.IRISK_TRHKSK_CD IS '依頼先取引先部署コード'
/
COMMENT ON COLUMN ED4375T_TBL.IRAISAKI_IRAI_CMNT IS '依頼先依頼コメント'
/
COMMENT ON COLUMN ED4375T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4375T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4375T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4375T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4375T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4375T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4375T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4375T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4375T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4375T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4375T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4375T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
