/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4304T_TBL.sql
-- 物理名：ED4304T_TBL
-- 論理名：詳細積算ケーブル接続工事テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4304T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4304T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SHOSAI_SEKISAN_NO  CHAR(17) NOT NULL --「詳細積算番号」
	,CHOKI_BAIKYAKU_KBN  CHAR(1) NOT NULL --「長期売却区分」
	,SHOSAI_SEKISAN_KOJIHI_KBN  CHAR(1) NOT NULL --「詳細積算工事費区分」
	,SHOSAI_SEKISAN_KOJIHI_SN  CHAR(14) NOT NULL --「詳細積算工事費連番」
	,KOJI_TAISHO_CHIKU_KBN  CHAR(1) NOT NULL --「工事対象地区区分」
	,CABLE_SETSUZOKU_SN  CHAR(14) NOT NULL --「ケーブル接続連番」
	,CABLE_STSZK_SHINSEN_SN  CHAR(14) DEFAULT '0' NOT NULL --「ケーブル接続心線連番」
	,CABLE_STSZK_SHINSEN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「ケーブル接続心線数量」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4304T_PK PRIMARY KEY(
	 SHOSAI_SEKISAN_NO
	,  CHOKI_BAIKYAKU_KBN
	,  SHOSAI_SEKISAN_KOJIHI_KBN
	,  SHOSAI_SEKISAN_KOJIHI_SN
	,  CABLE_SETSUZOKU_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4304T_TBL IS '詳細積算ケーブル接続工事テーブル'
/

COMMENT ON COLUMN ED4304T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4304T_TBL.SHOSAI_SEKISAN_NO IS '詳細積算番号'
/
COMMENT ON COLUMN ED4304T_TBL.CHOKI_BAIKYAKU_KBN IS '長期売却区分'
/
COMMENT ON COLUMN ED4304T_TBL.SHOSAI_SEKISAN_KOJIHI_KBN IS '詳細積算工事費区分'
/
COMMENT ON COLUMN ED4304T_TBL.SHOSAI_SEKISAN_KOJIHI_SN IS '詳細積算工事費連番'
/
COMMENT ON COLUMN ED4304T_TBL.KOJI_TAISHO_CHIKU_KBN IS '工事対象地区区分'
/
COMMENT ON COLUMN ED4304T_TBL.CABLE_SETSUZOKU_SN IS 'ケーブル接続連番'
/
COMMENT ON COLUMN ED4304T_TBL.CABLE_STSZK_SHINSEN_SN IS 'ケーブル接続心線連番'
/
COMMENT ON COLUMN ED4304T_TBL.CABLE_STSZK_SHINSEN_SURYO IS 'ケーブル接続心線数量'
/
COMMENT ON COLUMN ED4304T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4304T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4304T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4304T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4304T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4304T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4304T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4304T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4304T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4304T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4304T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4304T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
