/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4306T_TBL.sql
-- 物理名：ED4306T_TBL
-- 論理名：積算入出金機オプションテーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4306T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4306T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIYAKU_ID  CHAR(18) NOT NULL --「契約ＩＤ」
	,SEKISAN_NYUSHUKKINKI_OPTION_SN  CHAR(14) NOT NULL --「積算入出金機オプション連番」
	,NYUSHUKKINKI_OPTION_CD  CHAR(8) --「入出金機オプションコード」
	,NYUSHUKKINKI_OPTION_NM  VARCHAR2(60) --「入出金機オプション名称」
	,NYSHKKNK_OPTION_SHBTS_KBN  CHAR(1) NOT NULL --「入出金機オプション種別区分」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,NYUSHUKKINKI_OPTION_ARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「入出金機オプション有フラグ」
	,NYUSHUKKINKI_OPTION_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「入出金機オプション数量」
	,GETSUGAKU_OPTION_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「月額オプション原価金額」
	,DATA_TENSO_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「データ転送料金金額」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4306T_PK PRIMARY KEY(
	 KEIYAKU_ID
	,  SEKISAN_NYUSHUKKINKI_OPTION_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4306T_TBL IS '積算入出金機オプションテーブル'
/

COMMENT ON COLUMN ED4306T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4306T_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED4306T_TBL.SEKISAN_NYUSHUKKINKI_OPTION_SN IS '積算入出金機オプション連番'
/
COMMENT ON COLUMN ED4306T_TBL.NYUSHUKKINKI_OPTION_CD IS '入出金機オプションコード'
/
COMMENT ON COLUMN ED4306T_TBL.NYUSHUKKINKI_OPTION_NM IS '入出金機オプション名称'
/
COMMENT ON COLUMN ED4306T_TBL.NYSHKKNK_OPTION_SHBTS_KBN IS '入出金機オプション種別区分'
/
COMMENT ON COLUMN ED4306T_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED4306T_TBL.NYUSHUKKINKI_OPTION_ARI_FLG IS '入出金機オプション有フラグ'
/
COMMENT ON COLUMN ED4306T_TBL.NYUSHUKKINKI_OPTION_SURYO IS '入出金機オプション数量'
/
COMMENT ON COLUMN ED4306T_TBL.GETSUGAKU_OPTION_GENKA_AMT IS '月額オプション原価金額'
/
COMMENT ON COLUMN ED4306T_TBL.DATA_TENSO_RYOKIN_AMT IS 'データ転送料金金額'
/
COMMENT ON COLUMN ED4306T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4306T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4306T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4306T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4306T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4306T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4306T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4306T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4306T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4306T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4306T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4306T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
