/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4376T_TBL.sql
-- 物理名：ED4376T_TBL
-- 論理名：未登録品テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4376T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4376T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,MITOROKU_HIMMEI_CD  CHAR(8) NOT NULL --「未登録品品名コード」
	,MITOROKU_HIMMEI_NM  VARCHAR2(60) --「未登録品品名名称」
	,KATASHIKI_NM  VARCHAR2(15) --「型式名称」
	,BAIKYAKU_KBN  CHAR(1) NOT NULL --「売却区分」
	,KAKAKU_SETTEI_SHUBETSU_KBN  CHAR(1) NOT NULL --「価格設定種別区分」
	,HOJIN_HAMBAI_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「法人販売原価金額」
	,HOJIN_HAMBAI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「法人販売金額」
	,KOJIN_HAMBAI_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「個人販売原価金額」
	,KOJIN_HAMBAI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「個人販売金額」
	,SEKISAN_HIMMEI_BUNRUI_1_CD  CHAR(3) --「積算品名分類１コード」
	,SEKISAN_HIMMEI_BUNRUI_2_CD  CHAR(3) --「積算品名分類２コード」
	,SEKISAN_HIMMEI_BUNRUI_3_CD  CHAR(3) --「積算品名分類３コード」
	,SEKISAN_TANI_NM  VARCHAR2(5) --「積算単位名称」
	,DENATSU_SHURUI_KBN  CHAR(1) NOT NULL --「電圧種類区分」
	,SHOHI_DENRYU_12_V_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「消費電流１２Ｖ数量」
	,SHOHI_DENRYU_24_V_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「消費電流２４Ｖ数量」
	,SHOHI_DENRYU_SCI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「消費電流ＳＣＩ数量」
	,KYOKYU_DENRYU_12_V_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「供給電流１２Ｖ数量」
	,KYOKYU_DENRYU_24_V_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「供給電流２４Ｖ数量」
	,KYOKYU_DENRYU_SCI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「供給電流ＳＣＩ数量」
	,SHIIRESAKI_TORIHIKISAKI_CD  CHAR(9) --「仕入先取引先コード」
	,SHIRSK_TRHKSK_BSH_CD  CHAR(4) --「仕入先取引先部署コード」
	,MAKER_TORIHIKISAKI_CD  CHAR(9) --「メーカ取引先コード」
	,SETCHI_KIKI_JURYO_SN  CHAR(14) NOT NULL --「設置機器重量連番」
	,ANAAKE_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「穴あけ数量」
	,BIS_KOTEI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「ビス固定数量」
	,SETSUZOKU_BIS_TANSHI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「接続ビス端子数量」
	,STSZK_SCREW_LESS_TNSH_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「接続スクリューレス端子数量」
	,STSZK_CONNECTOR_TNSH_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「接続コネクター端子数量」
	,DENGEN_BIS_TANSHI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「電源ビス端子数量」
	,DENGEN_SCREW_LESS_TANSHI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「電源スクリューレス端子数量」
	,SONOTA_DENGEN_TANSHI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「その他電源端子数量」
	,SEKISAN_BUGAKARI_SURYO  NUMBER(12,3) DEFAULT '0' NOT NULL --「積算歩掛数量」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4376T_PK PRIMARY KEY(
	 MITOROKU_HIMMEI_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4376T_TBL IS '未登録品テーブル'
/

COMMENT ON COLUMN ED4376T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4376T_TBL.MITOROKU_HIMMEI_CD IS '未登録品品名コード'
/
COMMENT ON COLUMN ED4376T_TBL.MITOROKU_HIMMEI_NM IS '未登録品品名名称'
/
COMMENT ON COLUMN ED4376T_TBL.KATASHIKI_NM IS '型式名称'
/
COMMENT ON COLUMN ED4376T_TBL.BAIKYAKU_KBN IS '売却区分'
/
COMMENT ON COLUMN ED4376T_TBL.KAKAKU_SETTEI_SHUBETSU_KBN IS '価格設定種別区分'
/
COMMENT ON COLUMN ED4376T_TBL.HOJIN_HAMBAI_GENKA_AMT IS '法人販売原価金額'
/
COMMENT ON COLUMN ED4376T_TBL.HOJIN_HAMBAI_AMT IS '法人販売金額'
/
COMMENT ON COLUMN ED4376T_TBL.KOJIN_HAMBAI_GENKA_AMT IS '個人販売原価金額'
/
COMMENT ON COLUMN ED4376T_TBL.KOJIN_HAMBAI_AMT IS '個人販売金額'
/
COMMENT ON COLUMN ED4376T_TBL.SEKISAN_HIMMEI_BUNRUI_1_CD IS '積算品名分類１コード'
/
COMMENT ON COLUMN ED4376T_TBL.SEKISAN_HIMMEI_BUNRUI_2_CD IS '積算品名分類２コード'
/
COMMENT ON COLUMN ED4376T_TBL.SEKISAN_HIMMEI_BUNRUI_3_CD IS '積算品名分類３コード'
/
COMMENT ON COLUMN ED4376T_TBL.SEKISAN_TANI_NM IS '積算単位名称'
/
COMMENT ON COLUMN ED4376T_TBL.DENATSU_SHURUI_KBN IS '電圧種類区分'
/
COMMENT ON COLUMN ED4376T_TBL.SHOHI_DENRYU_12_V_SURYO IS '消費電流１２Ｖ数量'
/
COMMENT ON COLUMN ED4376T_TBL.SHOHI_DENRYU_24_V_SURYO IS '消費電流２４Ｖ数量'
/
COMMENT ON COLUMN ED4376T_TBL.SHOHI_DENRYU_SCI_SURYO IS '消費電流ＳＣＩ数量'
/
COMMENT ON COLUMN ED4376T_TBL.KYOKYU_DENRYU_12_V_SURYO IS '供給電流１２Ｖ数量'
/
COMMENT ON COLUMN ED4376T_TBL.KYOKYU_DENRYU_24_V_SURYO IS '供給電流２４Ｖ数量'
/
COMMENT ON COLUMN ED4376T_TBL.KYOKYU_DENRYU_SCI_SURYO IS '供給電流ＳＣＩ数量'
/
COMMENT ON COLUMN ED4376T_TBL.SHIIRESAKI_TORIHIKISAKI_CD IS '仕入先取引先コード'
/
COMMENT ON COLUMN ED4376T_TBL.SHIRSK_TRHKSK_BSH_CD IS '仕入先取引先部署コード'
/
COMMENT ON COLUMN ED4376T_TBL.MAKER_TORIHIKISAKI_CD IS 'メーカ取引先コード'
/
COMMENT ON COLUMN ED4376T_TBL.SETCHI_KIKI_JURYO_SN IS '設置機器重量連番'
/
COMMENT ON COLUMN ED4376T_TBL.ANAAKE_SURYO IS '穴あけ数量'
/
COMMENT ON COLUMN ED4376T_TBL.BIS_KOTEI_SURYO IS 'ビス固定数量'
/
COMMENT ON COLUMN ED4376T_TBL.SETSUZOKU_BIS_TANSHI_SURYO IS '接続ビス端子数量'
/
COMMENT ON COLUMN ED4376T_TBL.STSZK_SCREW_LESS_TNSH_SURYO IS '接続スクリューレス端子数量'
/
COMMENT ON COLUMN ED4376T_TBL.STSZK_CONNECTOR_TNSH_SURYO IS '接続コネクター端子数量'
/
COMMENT ON COLUMN ED4376T_TBL.DENGEN_BIS_TANSHI_SURYO IS '電源ビス端子数量'
/
COMMENT ON COLUMN ED4376T_TBL.DENGEN_SCREW_LESS_TANSHI_SURYO IS '電源スクリューレス端子数量'
/
COMMENT ON COLUMN ED4376T_TBL.SONOTA_DENGEN_TANSHI_SURYO IS 'その他電源端子数量'
/
COMMENT ON COLUMN ED4376T_TBL.SEKISAN_BUGAKARI_SURYO IS '積算歩掛数量'
/
COMMENT ON COLUMN ED4376T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4376T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4376T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4376T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4376T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4376T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4376T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4376T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4376T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4376T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4376T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4376T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
