/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4465T_TBL.sql
-- 物理名：ED4465T_TBL
-- 論理名：受注申請明細承認テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4465T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4465T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_SHINSEI_NO  CHAR(20) NOT NULL --「受注申請番号」
	,JUCHU_SHINSEI_MEISAI_NO  CHAR(7) NOT NULL --「受注申請明細番号」
	,SHINSEI_SHONIN_KAISO_KBN  CHAR(1) NOT NULL --「申請承認階層区分」
	,SHINSEI_SHONIN_CMNT  VARCHAR2(200) --「申請承認コメント」
	,SHINSEI_SHONINZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「申請承認済フラグ」
	,JCH_SHNSI_STATUS_KBN  CHAR(1) NOT NULL --「受注申請ステータス区分」
	,JCH_SHNSI_SISH_SHNN_KAISO_KBN  CHAR(1) NOT NULL --「受注申請最終承認階層区分」
	,YOSHIN_SAISHU_SHONIN_KAISO_KBN  CHAR(1) NOT NULL --「与信最終承認階層区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4465T_PK PRIMARY KEY(
	 JUCHU_SHINSEI_NO
	,  JUCHU_SHINSEI_MEISAI_NO
	,  SHINSEI_SHONIN_KAISO_KBN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4465T_TBL IS '受注申請明細承認テーブル'
/

COMMENT ON COLUMN ED4465T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4465T_TBL.JUCHU_SHINSEI_NO IS '受注申請番号'
/
COMMENT ON COLUMN ED4465T_TBL.JUCHU_SHINSEI_MEISAI_NO IS '受注申請明細番号'
/
COMMENT ON COLUMN ED4465T_TBL.SHINSEI_SHONIN_KAISO_KBN IS '申請承認階層区分'
/
COMMENT ON COLUMN ED4465T_TBL.SHINSEI_SHONIN_CMNT IS '申請承認コメント'
/
COMMENT ON COLUMN ED4465T_TBL.SHINSEI_SHONINZUMI_FLG IS '申請承認済フラグ'
/
COMMENT ON COLUMN ED4465T_TBL.JCH_SHNSI_STATUS_KBN IS '受注申請ステータス区分'
/
COMMENT ON COLUMN ED4465T_TBL.JCH_SHNSI_SISH_SHNN_KAISO_KBN IS '受注申請最終承認階層区分'
/
COMMENT ON COLUMN ED4465T_TBL.YOSHIN_SAISHU_SHONIN_KAISO_KBN IS '与信最終承認階層区分'
/
COMMENT ON COLUMN ED4465T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4465T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4465T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4465T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4465T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4465T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4465T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4465T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4465T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4465T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4465T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4465T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
