/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4462T_TBL.sql
-- 物理名：ED4462T_TBL
-- 論理名：詳細積算稼働表配置ポスト要員テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4462T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4462T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SHOSAI_SEKISAN_NO  CHAR(17) NOT NULL --「詳細積算番号」
	,SHSI_SKSN_KDHY_HICH_POST_SN  CHAR(14) NOT NULL --「詳細積算稼働表配置ポスト連番」
	,SSI_SKSN_KDH_HIC_POST_YIN_SN  CHAR(14) NOT NULL --「詳細積算稼働表配置ポスト要員連番」
	,YOIN_NM  VARCHAR2(60) --「要員氏名」
	,JITSUDOFUN_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「実働分時間」
	,KMM_KJNHY_GTSY_SHTSRYK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「勤務基準表月曜出力フラグ」
	,KMM_KJNHY_KY_SHTSRYK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「勤務基準表火曜出力フラグ」
	,KMM_KJNHY_SIY_SHTSRYK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「勤務基準表水曜出力フラグ」
	,KMM_KJNHY_MKY_SHTSRYK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「勤務基準表木曜出力フラグ」
	,KMM_KJNHY_KNY_SHTSRYK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「勤務基準表金曜出力フラグ」
	,KMM_KJNHY_DY_SHTSRYK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「勤務基準表土曜出力フラグ」
	,KMM_KJNHY_NCHY_SHTSRYK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「勤務基準表日曜出力フラグ」
	,KMM_KJNHY_SHKJTS_SHTSRYK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「勤務基準表祝日出力フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4462T_PK PRIMARY KEY(
	 SHOSAI_SEKISAN_NO
	,  SHSI_SKSN_KDHY_HICH_POST_SN
	,  SSI_SKSN_KDH_HIC_POST_YIN_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4462T_TBL IS '詳細積算稼働表配置ポスト要員テーブル'
/

COMMENT ON COLUMN ED4462T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4462T_TBL.SHOSAI_SEKISAN_NO IS '詳細積算番号'
/
COMMENT ON COLUMN ED4462T_TBL.SHSI_SKSN_KDHY_HICH_POST_SN IS '詳細積算稼働表配置ポスト連番'
/
COMMENT ON COLUMN ED4462T_TBL.SSI_SKSN_KDH_HIC_POST_YIN_SN IS '詳細積算稼働表配置ポスト要員連番'
/
COMMENT ON COLUMN ED4462T_TBL.YOIN_NM IS '要員氏名'
/
COMMENT ON COLUMN ED4462T_TBL.JITSUDOFUN_JIKAN IS '実働分時間'
/
COMMENT ON COLUMN ED4462T_TBL.KMM_KJNHY_GTSY_SHTSRYK_FLG IS '勤務基準表月曜出力フラグ'
/
COMMENT ON COLUMN ED4462T_TBL.KMM_KJNHY_KY_SHTSRYK_FLG IS '勤務基準表火曜出力フラグ'
/
COMMENT ON COLUMN ED4462T_TBL.KMM_KJNHY_SIY_SHTSRYK_FLG IS '勤務基準表水曜出力フラグ'
/
COMMENT ON COLUMN ED4462T_TBL.KMM_KJNHY_MKY_SHTSRYK_FLG IS '勤務基準表木曜出力フラグ'
/
COMMENT ON COLUMN ED4462T_TBL.KMM_KJNHY_KNY_SHTSRYK_FLG IS '勤務基準表金曜出力フラグ'
/
COMMENT ON COLUMN ED4462T_TBL.KMM_KJNHY_DY_SHTSRYK_FLG IS '勤務基準表土曜出力フラグ'
/
COMMENT ON COLUMN ED4462T_TBL.KMM_KJNHY_NCHY_SHTSRYK_FLG IS '勤務基準表日曜出力フラグ'
/
COMMENT ON COLUMN ED4462T_TBL.KMM_KJNHY_SHKJTS_SHTSRYK_FLG IS '勤務基準表祝日出力フラグ'
/
COMMENT ON COLUMN ED4462T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4462T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4462T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4462T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4462T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4462T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4462T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4462T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4462T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4462T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4462T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4462T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
