/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4481W_TBL.sql
-- 物理名：ED4481W_TBL
-- 論理名：売上報奨金算出基礎数値ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4481W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4481W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,KEIYAKU_ID  CHAR(18) NOT NULL --「契約ＩＤ」
	,TEIJI_KAKAKU_SN  CHAR(14) NOT NULL --「提示価格連番」
	,HOSHOKIN_KISO_SUCHI_NM  VARCHAR2(60) --「報奨金基礎数値名称」
	,SHINSEI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「申請金額」
	,HYOJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「標準金額」
	,GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「原価金額」
	,NEBIKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「値引金額」
	,NEBIKI_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「値引率」
	,RIEKI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「利益金額」
	,RIEKI_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「利益率」
	,NENGAKU_SHINSEI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「年額申請金額」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4481W_PK PRIMARY KEY(
	 KEIYAKU_ID
	,  TEIJI_KAKAKU_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4481W_TBL IS '売上報奨金算出基礎数値ワーク'
/

COMMENT ON COLUMN ED4481W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4481W_TBL.KEIYAKU_ID IS '契約ＩＤ'
/
COMMENT ON COLUMN ED4481W_TBL.TEIJI_KAKAKU_SN IS '提示価格連番'
/
COMMENT ON COLUMN ED4481W_TBL.HOSHOKIN_KISO_SUCHI_NM IS '報奨金基礎数値名称'
/
COMMENT ON COLUMN ED4481W_TBL.SHINSEI_AMT IS '申請金額'
/
COMMENT ON COLUMN ED4481W_TBL.HYOJUN_AMT IS '標準金額'
/
COMMENT ON COLUMN ED4481W_TBL.GENKA_AMT IS '原価金額'
/
COMMENT ON COLUMN ED4481W_TBL.NEBIKI_AMT IS '値引金額'
/
COMMENT ON COLUMN ED4481W_TBL.NEBIKI_RITSU IS '値引率'
/
COMMENT ON COLUMN ED4481W_TBL.RIEKI_AMT IS '利益金額'
/
COMMENT ON COLUMN ED4481W_TBL.RIEKI_RITSU IS '利益率'
/
COMMENT ON COLUMN ED4481W_TBL.NENGAKU_SHINSEI_AMT IS '年額申請金額'
/
COMMENT ON COLUMN ED4481W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4481W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4481W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4481W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4481W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4481W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4481W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4481W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4481W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4481W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4481W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4481W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
