/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4556W_TBL.sql
-- 物理名：ED4556W_TBL
-- 論理名：制御装置品名積算回線種別紐付マスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4556W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4556W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,SEIGYO_SOCHI_HIMMEI_CD  CHAR(8) NOT NULL --「制御装置品名コード」
	,WK_SEIGYO_SOCHI_HIMMEI_NM  VARCHAR2(60) --「ワーク用制御装置品名名称」
	,SHUKAISEN_SHUBETSU_CD  CHAR(3) NOT NULL --「主回線種別コード」
	,WK_SHKISN_SHUBETSU_CD_NM  VARCHAR2(60) --「ワーク用主回線種別名称」
	,SHUKAISEN_RYKN_KAISEN_SHY_KBN  CHAR(1) NOT NULL --「主回線利用可能回線所有区分」
	,WK_SHKISN_RYKN_KISN_SHY_KBN_NM  VARCHAR2(60) --「ワーク用主回線利用可能回線所有区分名称」
	,SHUKAISEN_OPTION_SERVICE_CD  CHAR(4) --「主回線オプションサービスコード」
	,WK_SHKISN_OPTION_SERVICE_NM  VARCHAR2(60) --「ワーク用主回線オプションサービス名称」
	,HYOJI_JUN_1  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順１」
	,FUKUKAISEN_SHUBETSU_CD  CHAR(3) NOT NULL --「副回線種別コード」
	,WK_FKKISN_SHUBETSU_NM  VARCHAR2(60) --「ワーク用副回線種別名称」
	,FUKUKAISEN_RYKN_KAISEN_SHY_KBN  CHAR(1) NOT NULL --「副回線利用可能回線所有区分」
	,WK_FKKISN_RYKN_KISN_SHY_KBN_NM  VARCHAR2(60) --「ワーク用副回線利用可能回線所有区分名称」
	,FUKUKAISEN_OPTION_SERVICE_CD  CHAR(4) --「副回線オプションサービスコード」
	,WK_FKKISN_OPTION_SERVICE_NM  VARCHAR2(60) --「ワーク用副回線オプションサービス名称」
	,HYOJI_JUN_2  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順２」
	,SHIYO_FUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「使用不可フラグ」
	,WK_SHIYO_FUKA_FLG_NM  VARCHAR2(60) --「ワーク用使用不可フラグ名称」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) NOT NULL --「アップロードテーブルＩＤ」
	,TH_SEIGYO_SOCHI_HIMMEI_CD  CHAR(8) --「退避用制御装置品名コード」
	,TH_SHUKAISEN_SHUBETSU_CD  CHAR(3) --「退避用主回線種別コード」
	,TH_FUKUKAISEN_SHUBETSU_CD  CHAR(3) --「退避用副回線種別コード」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4556W_PK PRIMARY KEY(
	 SEIGYO_SOCHI_HIMMEI_CD
	,  SHUKAISEN_SHUBETSU_CD
	,  FUKUKAISEN_SHUBETSU_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4556W_TBL IS '制御装置品名積算回線種別紐付マスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED4556W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED4556W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED4556W_TBL.SEIGYO_SOCHI_HIMMEI_CD IS '制御装置品名コード'
/
COMMENT ON COLUMN ED4556W_TBL.WK_SEIGYO_SOCHI_HIMMEI_NM IS 'ワーク用制御装置品名名称'
/
COMMENT ON COLUMN ED4556W_TBL.SHUKAISEN_SHUBETSU_CD IS '主回線種別コード'
/
COMMENT ON COLUMN ED4556W_TBL.WK_SHKISN_SHUBETSU_CD_NM IS 'ワーク用主回線種別名称'
/
COMMENT ON COLUMN ED4556W_TBL.SHUKAISEN_RYKN_KAISEN_SHY_KBN IS '主回線利用可能回線所有区分'
/
COMMENT ON COLUMN ED4556W_TBL.WK_SHKISN_RYKN_KISN_SHY_KBN_NM IS 'ワーク用主回線利用可能回線所有区分名称'
/
COMMENT ON COLUMN ED4556W_TBL.SHUKAISEN_OPTION_SERVICE_CD IS '主回線オプションサービスコード'
/
COMMENT ON COLUMN ED4556W_TBL.WK_SHKISN_OPTION_SERVICE_NM IS 'ワーク用主回線オプションサービス名称'
/
COMMENT ON COLUMN ED4556W_TBL.HYOJI_JUN_1 IS '表示順１'
/
COMMENT ON COLUMN ED4556W_TBL.FUKUKAISEN_SHUBETSU_CD IS '副回線種別コード'
/
COMMENT ON COLUMN ED4556W_TBL.WK_FKKISN_SHUBETSU_NM IS 'ワーク用副回線種別名称'
/
COMMENT ON COLUMN ED4556W_TBL.FUKUKAISEN_RYKN_KAISEN_SHY_KBN IS '副回線利用可能回線所有区分'
/
COMMENT ON COLUMN ED4556W_TBL.WK_FKKISN_RYKN_KISN_SHY_KBN_NM IS 'ワーク用副回線利用可能回線所有区分名称'
/
COMMENT ON COLUMN ED4556W_TBL.FUKUKAISEN_OPTION_SERVICE_CD IS '副回線オプションサービスコード'
/
COMMENT ON COLUMN ED4556W_TBL.WK_FKKISN_OPTION_SERVICE_NM IS 'ワーク用副回線オプションサービス名称'
/
COMMENT ON COLUMN ED4556W_TBL.HYOJI_JUN_2 IS '表示順２'
/
COMMENT ON COLUMN ED4556W_TBL.SHIYO_FUKA_FLG IS '使用不可フラグ'
/
COMMENT ON COLUMN ED4556W_TBL.WK_SHIYO_FUKA_FLG_NM IS 'ワーク用使用不可フラグ名称'
/
COMMENT ON COLUMN ED4556W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4556W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4556W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED4556W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED4556W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED4556W_TBL.TH_SEIGYO_SOCHI_HIMMEI_CD IS '退避用制御装置品名コード'
/
COMMENT ON COLUMN ED4556W_TBL.TH_SHUKAISEN_SHUBETSU_CD IS '退避用主回線種別コード'
/
COMMENT ON COLUMN ED4556W_TBL.TH_FUKUKAISEN_SHUBETSU_CD IS '退避用副回線種別コード'
/
COMMENT ON COLUMN ED4556W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED4556W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED4556W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED4556W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED4556W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED4556W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4556W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4556W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4556W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4556W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4556W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4556W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4556W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4556W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4556W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4556W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4556W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
