/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4567W_TBL.sql
-- 物理名：ED4567W_TBL
-- 論理名：入出金機両替機積算回線種別紐付マスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4567W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4567W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,NYUSHUKKINKI_RYOGAEKI_KISHU_CD  CHAR(8) NOT NULL --「入出金機両替機機種コード」
	,WK_NYUSHUKKINKI_RYGK_KWK_NM  VARCHAR2(30) --「ワーク用入出金機両替機機種名称」
	,NYSHKKNK_KISN_SHBTS_CD  CHAR(3) NOT NULL --「入出金機回線種別コード」
	,WK_NYSHKKNK_KISN_SHBTS_NM  VARCHAR2(60) --「ワーク用入出金機回線種別名称」
	,HYOJI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順」
	,KIKAI_KEIBI_KISN_SHUBETSU_CD  CHAR(3) NOT NULL --「機械警備回線種別コード」
	,WK_KIKAI_KEIBI_KISN_SHBTS_NM  VARCHAR2(60) --「ワーク用機械警備回線種別名称」
	,HIMMEI_CD  CHAR(8) NOT NULL --「品名コード」
	,WK_HIMMEI_NM  VARCHAR2(60) --「ワーク用品名名称」
	,RIYO_FUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「利用不可フラグ」
	,WK_RIYO_FUKA_FLG_NM  VARCHAR2(60) --「ワーク用利用不可フラグ名称」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) NOT NULL --「アップロードテーブルＩＤ」
	,TH_NYUSHUKKINKI_RYGK_KSH_CD  CHAR(8) --「退避用入出金機両替機機種コード」
	,TH_NYSHKKNK_KISN_SHBTS_CD  CHAR(3) --「退避用入出金機回線種別コード」
	,TH_KIKAI_KEIBI_KISN_SHBTS_CD  CHAR(3) --「退避用機械警備回線種別コード」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4567W_PK PRIMARY KEY(
	 NYUSHUKKINKI_RYOGAEKI_KISHU_CD
	,  NYSHKKNK_KISN_SHBTS_CD
	,  KIKAI_KEIBI_KISN_SHUBETSU_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4567W_TBL IS '入出金機両替機積算回線種別紐付マスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED4567W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED4567W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED4567W_TBL.NYUSHUKKINKI_RYOGAEKI_KISHU_CD IS '入出金機両替機機種コード'
/
COMMENT ON COLUMN ED4567W_TBL.WK_NYUSHUKKINKI_RYGK_KWK_NM IS 'ワーク用入出金機両替機機種名称'
/
COMMENT ON COLUMN ED4567W_TBL.NYSHKKNK_KISN_SHBTS_CD IS '入出金機回線種別コード'
/
COMMENT ON COLUMN ED4567W_TBL.WK_NYSHKKNK_KISN_SHBTS_NM IS 'ワーク用入出金機回線種別名称'
/
COMMENT ON COLUMN ED4567W_TBL.HYOJI_JUN IS '表示順'
/
COMMENT ON COLUMN ED4567W_TBL.KIKAI_KEIBI_KISN_SHUBETSU_CD IS '機械警備回線種別コード'
/
COMMENT ON COLUMN ED4567W_TBL.WK_KIKAI_KEIBI_KISN_SHBTS_NM IS 'ワーク用機械警備回線種別名称'
/
COMMENT ON COLUMN ED4567W_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED4567W_TBL.WK_HIMMEI_NM IS 'ワーク用品名名称'
/
COMMENT ON COLUMN ED4567W_TBL.RIYO_FUKA_FLG IS '利用不可フラグ'
/
COMMENT ON COLUMN ED4567W_TBL.WK_RIYO_FUKA_FLG_NM IS 'ワーク用利用不可フラグ名称'
/
COMMENT ON COLUMN ED4567W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4567W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4567W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED4567W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED4567W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED4567W_TBL.TH_NYUSHUKKINKI_RYGK_KSH_CD IS '退避用入出金機両替機機種コード'
/
COMMENT ON COLUMN ED4567W_TBL.TH_NYSHKKNK_KISN_SHBTS_CD IS '退避用入出金機回線種別コード'
/
COMMENT ON COLUMN ED4567W_TBL.TH_KIKAI_KEIBI_KISN_SHBTS_CD IS '退避用機械警備回線種別コード'
/
COMMENT ON COLUMN ED4567W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED4567W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED4567W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED4567W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED4567W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED4567W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4567W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4567W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4567W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4567W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4567W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4567W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4567W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4567W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4567W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4567W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4567W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
