/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4529W_TBL.sql
-- 物理名：ED4529W_TBL
-- 論理名：商品サービスオプションマスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4529W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4529W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,OPTION_SERVICE_CD  CHAR(4) NOT NULL --「オプションサービスコード」
	,OPTION_SERVICE_NM  VARCHAR2(60) --「オプションサービス名称」
	,OPTION_TANI_NM  VARCHAR2(5) --「オプション単位名称」
	,OPTION_HYOJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「オプション標準金額」
	,SHOKI_HYOJI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「初期表示フラグ」
	,WK_SHOKI_HYOJI_FLG_NM  VARCHAR2(60) --「ワーク用初期表示フラグ名称」
	,SHOKI_HYOJI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「初期表示数量」
	,GETSUGAKU_OPTION_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「月額オプション原価金額」
	,GYM_ITKSK_TRHKSK_CD  CHAR(9) --「業務委託先取引先コード」
	,WK_GYM_ITKSK_TRHKSK_NM  VARCHAR2(40) --「ワーク用業務委託先取引先名称」
	,GYM_ITKSK_TRHKSK_BSH_CD  CHAR(4) --「業務委託先取引先部署コード」
	,WK_GYM_ITKSK_TRHKSK_BWK_NM  VARCHAR2(40) --「ワーク用業務委託先取引先部署名称」
	,JIGYO_SEGMENT_CD  CHAR(3) --「事業セグメントコード」
	,WK_JIGYO_SEGMENT_NM  VARCHAR2(64) --「ワーク用事業セグメント名称」
	,JUCHU_SHORI_KBN  CHAR(2) NOT NULL --「受注処理区分」
	,WK_JUCHU_SHORI_KBN_NM  VARCHAR2(60) --「ワーク用受注処理区分名称」
	,RYOKIN_KBN  CHAR(5) NOT NULL --「料金区分」
	,WK_RYOKIN_KBN_NM  VARCHAR2(60) --「ワーク用料金区分名称」
	,SEIKYU_SHIHARAI_CD  CHAR(3) --「請求支払コード」
	,WK_SEIKYU_SHIHARAI_CD_NM  VARCHAR2(50) --「ワーク用請求支払コード名称」
	,URIAGE_KEIJO_SHUBETSU_KBN  CHAR(2) NOT NULL --「売上計上種別区分」
	,WK_URIAGE_KEIJO_SHBTS_KBN_NM  VARCHAR2(60) --「ワーク用売上計上種別区分名称」
	,OPTION_SS_GAMEN_ID  CHAR(15) --「オプション詳細画面ＩＤ」
	,OPTION_SURYO_HENKOKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「オプション数量変更可フラグ」
	,WK_OPTION_SRY_HENKOKA_FLG_NM  VARCHAR2(60) --「ワーク用オプション数量変更可フラグ名称」
	,OPTION_GNK_KNGKH_HENKOKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「オプション原価金額変更可フラグ」
	,WK_OPTION_GNK_KNG_HNKK_FLG_NM  VARCHAR2(60) --「ワーク用オプション原価金額変更可フラグ名称」
	,SHOSAI_BTN_KASSEI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「詳細ボタン活性フラグ」
	,WK_SHOSAI_BTN_KASSEI_FLG_NM  VARCHAR2(60) --「ワーク用詳細ボタン活性フラグ名称」
	,KK_KSI_FOLLOW_RENKEI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「機器構成フォロー連携フラグ」
	,WK_KK_KSI_FLLW_RENKEI_FLG_NM  VARCHAR2(60) --「ワーク用機器構成フォロー連携フラグ名称」
	,KANSHI_KOMOKU_CATEGORY_CD  CHAR(3) --「監視項目カテゴリコード」
	,WK_KANSHI_KOMOKU_CATEGORY_NM  VARCHAR2(300) --「ワーク用監視項目カテゴリ名称」
	,KKKB_OPTION_SERVICE_DBR_KBN  CHAR(2) NOT NULL --「機械警備オプションサービス大分類区分」
	,WK_KKKB_OPT_SERVICE_DBR_KBN_NM  VARCHAR2(60) --「ワーク用機械警備オプションサービス大分類区分名称」
	,GYM_ITKSK_HENKOKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「業務委託先変更可フラグ」
	,WK_GYM_ITKSK_HENKOKA_FLG_NM  VARCHAR2(60) --「ワーク用業務委託先変更可フラグ名称」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) NOT NULL --「アップロードテーブルＩＤ」
	,TH_OPTION_SERVICE_CD  CHAR(4) --「退避用オプションサービスコード」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4529W_PK PRIMARY KEY(
	 OPTION_SERVICE_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4529W_TBL IS '商品サービスオプションマスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED4529W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED4529W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED4529W_TBL.OPTION_SERVICE_CD IS 'オプションサービスコード'
/
COMMENT ON COLUMN ED4529W_TBL.OPTION_SERVICE_NM IS 'オプションサービス名称'
/
COMMENT ON COLUMN ED4529W_TBL.OPTION_TANI_NM IS 'オプション単位名称'
/
COMMENT ON COLUMN ED4529W_TBL.OPTION_HYOJUN_AMT IS 'オプション標準金額'
/
COMMENT ON COLUMN ED4529W_TBL.SHOKI_HYOJI_FLG IS '初期表示フラグ'
/
COMMENT ON COLUMN ED4529W_TBL.WK_SHOKI_HYOJI_FLG_NM IS 'ワーク用初期表示フラグ名称'
/
COMMENT ON COLUMN ED4529W_TBL.SHOKI_HYOJI_SURYO IS '初期表示数量'
/
COMMENT ON COLUMN ED4529W_TBL.GETSUGAKU_OPTION_GENKA_AMT IS '月額オプション原価金額'
/
COMMENT ON COLUMN ED4529W_TBL.GYM_ITKSK_TRHKSK_CD IS '業務委託先取引先コード'
/
COMMENT ON COLUMN ED4529W_TBL.WK_GYM_ITKSK_TRHKSK_NM IS 'ワーク用業務委託先取引先名称'
/
COMMENT ON COLUMN ED4529W_TBL.GYM_ITKSK_TRHKSK_BSH_CD IS '業務委託先取引先部署コード'
/
COMMENT ON COLUMN ED4529W_TBL.WK_GYM_ITKSK_TRHKSK_BWK_NM IS 'ワーク用業務委託先取引先部署名称'
/
COMMENT ON COLUMN ED4529W_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED4529W_TBL.WK_JIGYO_SEGMENT_NM IS 'ワーク用事業セグメント名称'
/
COMMENT ON COLUMN ED4529W_TBL.JUCHU_SHORI_KBN IS '受注処理区分'
/
COMMENT ON COLUMN ED4529W_TBL.WK_JUCHU_SHORI_KBN_NM IS 'ワーク用受注処理区分名称'
/
COMMENT ON COLUMN ED4529W_TBL.RYOKIN_KBN IS '料金区分'
/
COMMENT ON COLUMN ED4529W_TBL.WK_RYOKIN_KBN_NM IS 'ワーク用料金区分名称'
/
COMMENT ON COLUMN ED4529W_TBL.SEIKYU_SHIHARAI_CD IS '請求支払コード'
/
COMMENT ON COLUMN ED4529W_TBL.WK_SEIKYU_SHIHARAI_CD_NM IS 'ワーク用請求支払コード名称'
/
COMMENT ON COLUMN ED4529W_TBL.URIAGE_KEIJO_SHUBETSU_KBN IS '売上計上種別区分'
/
COMMENT ON COLUMN ED4529W_TBL.WK_URIAGE_KEIJO_SHBTS_KBN_NM IS 'ワーク用売上計上種別区分名称'
/
COMMENT ON COLUMN ED4529W_TBL.OPTION_SS_GAMEN_ID IS 'オプション詳細画面ＩＤ'
/
COMMENT ON COLUMN ED4529W_TBL.OPTION_SURYO_HENKOKA_FLG IS 'オプション数量変更可フラグ'
/
COMMENT ON COLUMN ED4529W_TBL.WK_OPTION_SRY_HENKOKA_FLG_NM IS 'ワーク用オプション数量変更可フラグ名称'
/
COMMENT ON COLUMN ED4529W_TBL.OPTION_GNK_KNGKH_HENKOKA_FLG IS 'オプション原価金額変更可フラグ'
/
COMMENT ON COLUMN ED4529W_TBL.WK_OPTION_GNK_KNG_HNKK_FLG_NM IS 'ワーク用オプション原価金額変更可フラグ名称'
/
COMMENT ON COLUMN ED4529W_TBL.SHOSAI_BTN_KASSEI_FLG IS '詳細ボタン活性フラグ'
/
COMMENT ON COLUMN ED4529W_TBL.WK_SHOSAI_BTN_KASSEI_FLG_NM IS 'ワーク用詳細ボタン活性フラグ名称'
/
COMMENT ON COLUMN ED4529W_TBL.KK_KSI_FOLLOW_RENKEI_FLG IS '機器構成フォロー連携フラグ'
/
COMMENT ON COLUMN ED4529W_TBL.WK_KK_KSI_FLLW_RENKEI_FLG_NM IS 'ワーク用機器構成フォロー連携フラグ名称'
/
COMMENT ON COLUMN ED4529W_TBL.KANSHI_KOMOKU_CATEGORY_CD IS '監視項目カテゴリコード'
/
COMMENT ON COLUMN ED4529W_TBL.WK_KANSHI_KOMOKU_CATEGORY_NM IS 'ワーク用監視項目カテゴリ名称'
/
COMMENT ON COLUMN ED4529W_TBL.KKKB_OPTION_SERVICE_DBR_KBN IS '機械警備オプションサービス大分類区分'
/
COMMENT ON COLUMN ED4529W_TBL.WK_KKKB_OPT_SERVICE_DBR_KBN_NM IS 'ワーク用機械警備オプションサービス大分類区分名称'
/
COMMENT ON COLUMN ED4529W_TBL.GYM_ITKSK_HENKOKA_FLG IS '業務委託先変更可フラグ'
/
COMMENT ON COLUMN ED4529W_TBL.WK_GYM_ITKSK_HENKOKA_FLG_NM IS 'ワーク用業務委託先変更可フラグ名称'
/
COMMENT ON COLUMN ED4529W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4529W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4529W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED4529W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED4529W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED4529W_TBL.TH_OPTION_SERVICE_CD IS '退避用オプションサービスコード'
/
COMMENT ON COLUMN ED4529W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED4529W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED4529W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED4529W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED4529W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED4529W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4529W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4529W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4529W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4529W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4529W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4529W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4529W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4529W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4529W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4529W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4529W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
