/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4580W_TBL.sql
-- 物理名：ED4580W_TBL
-- 論理名：商品サービス常駐詳細紐付マスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4580W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4580W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,WK_SHOHIN_SERVICE_NM  VARCHAR2(60) --「ワーク用商品サービス名称」
	,KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,WK_KAISHA_NM  VARCHAR2(40) --「ワーク用会社名称」
	,JOCHU_SHOSAI_KOMOKU_CD  CHAR(2) NOT NULL --「常駐詳細項目コード」
	,WK_JOCHU_SHOSAI_KOMOKU_NM  VARCHAR2(30) --「ワーク用常駐詳細項目名称」
	,HYOJI_JUN_1  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順１」
	,JOCHU_SHOSAI_NAIYO_CD  CHAR(2) NOT NULL --「常駐詳細内容コード」
	,WK_JOCHU_SHOSAI_NAIYO_NM  VARCHAR2(30) --「ワーク用常駐詳細内容名称」
	,HYOJI_JUN_2  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順２」
	,JOCHU_SHOSAI_NAIYO_HOSOKU_CD  CHAR(2) NOT NULL --「常駐詳細補足コード」
	,WK_JOCHU_SHOSAI_NAIYO_HSK_NM  VARCHAR2(300) --「ワーク用常駐詳細補足名称」
	,HYOJI_JUN_3  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順３」
	,KAITOU_SETSUMEI_HZK_NYRYK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「回答説明日付入力フラグ」
	,WK_KT_STSM_HZK_NYRYK_FLG_NM  VARCHAR2(60) --「ワーク用回答説明日付入力フラグ名称」
	,KAITOU_SETSUMEI_GYMKBN_NRK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「回答説明業務区分入力フラグ」
	,WK_KT_STSM_GYMKBN_NRK_FLG_NM  VARCHAR2(60) --「ワーク用回答説明業務区分入力フラグ名称」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) NOT NULL --「アップロードテーブルＩＤ」
	,TH_SHOHIN_SERVICE_CD  CHAR(3) --「退避用商品サービスコード」
	,TH_KAISHA_CD  CHAR(5) --「退避用会社コード」
	,TH_JOCHU_SHOSAI_KOMOKU_CD  CHAR(2) --「退避用常駐詳細項目コード」
	,TH_JOCHU_SHOSAI_NAIYO_CD  CHAR(2) --「退避用常駐詳細内容コード」
	,TH_JOCHU_SHOSAI_NAIYO_HSK_CD  CHAR(2) --「退避用常駐詳細補足コード」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4580W_PK PRIMARY KEY(
	 SHOHIN_SERVICE_CD
	,  KAISHA_CD
	,  JOCHU_SHOSAI_KOMOKU_CD
	,  JOCHU_SHOSAI_NAIYO_CD
	,  JOCHU_SHOSAI_NAIYO_HOSOKU_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4580W_TBL IS '商品サービス常駐詳細紐付マスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED4580W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED4580W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED4580W_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4580W_TBL.WK_SHOHIN_SERVICE_NM IS 'ワーク用商品サービス名称'
/
COMMENT ON COLUMN ED4580W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4580W_TBL.WK_KAISHA_NM IS 'ワーク用会社名称'
/
COMMENT ON COLUMN ED4580W_TBL.JOCHU_SHOSAI_KOMOKU_CD IS '常駐詳細項目コード'
/
COMMENT ON COLUMN ED4580W_TBL.WK_JOCHU_SHOSAI_KOMOKU_NM IS 'ワーク用常駐詳細項目名称'
/
COMMENT ON COLUMN ED4580W_TBL.HYOJI_JUN_1 IS '表示順１'
/
COMMENT ON COLUMN ED4580W_TBL.JOCHU_SHOSAI_NAIYO_CD IS '常駐詳細内容コード'
/
COMMENT ON COLUMN ED4580W_TBL.WK_JOCHU_SHOSAI_NAIYO_NM IS 'ワーク用常駐詳細内容名称'
/
COMMENT ON COLUMN ED4580W_TBL.HYOJI_JUN_2 IS '表示順２'
/
COMMENT ON COLUMN ED4580W_TBL.JOCHU_SHOSAI_NAIYO_HOSOKU_CD IS '常駐詳細補足コード'
/
COMMENT ON COLUMN ED4580W_TBL.WK_JOCHU_SHOSAI_NAIYO_HSK_NM IS 'ワーク用常駐詳細補足名称'
/
COMMENT ON COLUMN ED4580W_TBL.HYOJI_JUN_3 IS '表示順３'
/
COMMENT ON COLUMN ED4580W_TBL.KAITOU_SETSUMEI_HZK_NYRYK_FLG IS '回答説明日付入力フラグ'
/
COMMENT ON COLUMN ED4580W_TBL.WK_KT_STSM_HZK_NYRYK_FLG_NM IS 'ワーク用回答説明日付入力フラグ名称'
/
COMMENT ON COLUMN ED4580W_TBL.KAITOU_SETSUMEI_GYMKBN_NRK_FLG IS '回答説明業務区分入力フラグ'
/
COMMENT ON COLUMN ED4580W_TBL.WK_KT_STSM_GYMKBN_NRK_FLG_NM IS 'ワーク用回答説明業務区分入力フラグ名称'
/
COMMENT ON COLUMN ED4580W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4580W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4580W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED4580W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED4580W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED4580W_TBL.TH_SHOHIN_SERVICE_CD IS '退避用商品サービスコード'
/
COMMENT ON COLUMN ED4580W_TBL.TH_KAISHA_CD IS '退避用会社コード'
/
COMMENT ON COLUMN ED4580W_TBL.TH_JOCHU_SHOSAI_KOMOKU_CD IS '退避用常駐詳細項目コード'
/
COMMENT ON COLUMN ED4580W_TBL.TH_JOCHU_SHOSAI_NAIYO_CD IS '退避用常駐詳細内容コード'
/
COMMENT ON COLUMN ED4580W_TBL.TH_JOCHU_SHOSAI_NAIYO_HSK_CD IS '退避用常駐詳細補足コード'
/
COMMENT ON COLUMN ED4580W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED4580W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED4580W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED4580W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED4580W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED4580W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4580W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4580W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4580W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4580W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4580W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4580W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4580W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4580W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4580W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4580W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4580W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
