/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4510W_TBL.sql
-- 物理名：ED4510W_TBL
-- 論理名：入出金機オプションマスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4510W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4510W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,NYUSHUKKINKI_OPTION_CD  CHAR(8) NOT NULL --「入出金機オプションコード」
	,NYUSHUKKINKI_RYOGAEKI_KISHU_CD  CHAR(8) NOT NULL --「入出金機両替機機種コード」
	,WK_NYUSHUKKINKI_RYGK_KWK_NM  VARCHAR2(30) --「ワーク用入出金機両替機機種名称」
	,NYUSHUKKINKI_OPTION_NM  VARCHAR2(60) --「入出金機オプション名称」
	,NYSHKKNK_OPTION_SHBTS_KBN  CHAR(1) NOT NULL --「入出金機オプション種別区分」
	,WK_NYSHKKNK_OPT_SHBTS_KBN_NM  VARCHAR2(60) --「ワーク用入出金機オプション種別区分名称」
	,SURYO_SETTEIKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「数量設定可フラグ」
	,WK_SURYO_SETTEIKA_FLG_NM  VARCHAR2(60) --「ワーク用数量設定可フラグ名称」
	,AMT_SETTEIKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「金額設定可フラグ」
	,WK_AMT_SETTEIKA_FLG_NM  VARCHAR2(60) --「ワーク用金額設定可フラグ名称」
	,NYKNK_SHHN_STCH_HH_KBN  CHAR(1) --「入金機商品設置方法区分」
	,WK_NYKNK_SHHN_STCH_HH_KBN_NM  VARCHAR2(60) --「ワーク用入金機商品設置方法区分名称」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,WK_HIMMEI_NM  VARCHAR2(60) --「ワーク用品名名称」
	,GETSUGAKU_OPTION_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「月額オプション原価金額」
	,KIKI_LEASE_GETSUGAKU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「機器リース月額金額」
	,DATA_TENSO_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「データ転送料金金額」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) NOT NULL --「アップロードテーブルＩＤ」
	,TH_NYUSHUKKINKI_OPTION_CD  CHAR(8) --「退避用入出金機オプションコード」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4510W_PK PRIMARY KEY(
	 NYUSHUKKINKI_OPTION_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4510W_TBL IS '入出金機オプションマスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED4510W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED4510W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED4510W_TBL.NYUSHUKKINKI_OPTION_CD IS '入出金機オプションコード'
/
COMMENT ON COLUMN ED4510W_TBL.NYUSHUKKINKI_RYOGAEKI_KISHU_CD IS '入出金機両替機機種コード'
/
COMMENT ON COLUMN ED4510W_TBL.WK_NYUSHUKKINKI_RYGK_KWK_NM IS 'ワーク用入出金機両替機機種名称'
/
COMMENT ON COLUMN ED4510W_TBL.NYUSHUKKINKI_OPTION_NM IS '入出金機オプション名称'
/
COMMENT ON COLUMN ED4510W_TBL.NYSHKKNK_OPTION_SHBTS_KBN IS '入出金機オプション種別区分'
/
COMMENT ON COLUMN ED4510W_TBL.WK_NYSHKKNK_OPT_SHBTS_KBN_NM IS 'ワーク用入出金機オプション種別区分名称'
/
COMMENT ON COLUMN ED4510W_TBL.SURYO_SETTEIKA_FLG IS '数量設定可フラグ'
/
COMMENT ON COLUMN ED4510W_TBL.WK_SURYO_SETTEIKA_FLG_NM IS 'ワーク用数量設定可フラグ名称'
/
COMMENT ON COLUMN ED4510W_TBL.AMT_SETTEIKA_FLG IS '金額設定可フラグ'
/
COMMENT ON COLUMN ED4510W_TBL.WK_AMT_SETTEIKA_FLG_NM IS 'ワーク用金額設定可フラグ名称'
/
COMMENT ON COLUMN ED4510W_TBL.NYKNK_SHHN_STCH_HH_KBN IS '入金機商品設置方法区分'
/
COMMENT ON COLUMN ED4510W_TBL.WK_NYKNK_SHHN_STCH_HH_KBN_NM IS 'ワーク用入金機商品設置方法区分名称'
/
COMMENT ON COLUMN ED4510W_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED4510W_TBL.WK_HIMMEI_NM IS 'ワーク用品名名称'
/
COMMENT ON COLUMN ED4510W_TBL.GETSUGAKU_OPTION_GENKA_AMT IS '月額オプション原価金額'
/
COMMENT ON COLUMN ED4510W_TBL.KIKI_LEASE_GETSUGAKU_AMT IS '機器リース月額金額'
/
COMMENT ON COLUMN ED4510W_TBL.DATA_TENSO_RYOKIN_AMT IS 'データ転送料金金額'
/
COMMENT ON COLUMN ED4510W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4510W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4510W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED4510W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED4510W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED4510W_TBL.TH_NYUSHUKKINKI_OPTION_CD IS '退避用入出金機オプションコード'
/
COMMENT ON COLUMN ED4510W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED4510W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED4510W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED4510W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED4510W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED4510W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4510W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4510W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4510W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4510W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4510W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4510W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4510W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4510W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4510W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4510W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4510W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
