/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4574W_TBL.sql
-- 物理名：ED4574W_TBL
-- 論理名：入出金機売上回収係数マスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4574W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4574W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,NYUSHUKKINKI_RYOGAEKI_KBN  CHAR(1) NOT NULL --「入出金機両替機区分」
	,WK_NYUSHUKKINKI_RYGK_KBN_NM  VARCHAR2(60) --「ワーク用入出金機両替機区分名称」
	,NYSHKKNK_FURIKOMI_D_SHITEI_CD  CHAR(3) NOT NULL --「入出金機振込日指定コード」
	,WK_NYSHKKNK_FURIKOMI_D_SHT_NM  VARCHAR2(10) --「ワーク用入出金機振込日指定名称」
	,NYSHKKNK_URAGKN_KISH_KEISU_CD  CHAR(3) NOT NULL --「入出金機売上金回収係数コード」
	,URIAGE_KINRI_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「売上金利係数」
	,GEKKAN_KAISHU_KAISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「月間回収回数」
	,TSURISEN_TESURYO_RYGE_KEISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「釣銭手数料両替係数」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) NOT NULL --「アップロードテーブルＩＤ」
	,TH_NYSHKKNK_FURIKOMI_D_SHT_CD  CHAR(3) --「退避用入出金機振込日指定コード」
	,TH_NYSHKKNK_URGKN_KSH_KES_CD  CHAR(3) --「退避用入出金機売上金回収係数コード」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4574W_PK PRIMARY KEY(
	 NYUSHUKKINKI_RYOGAEKI_KBN
	,  NYSHKKNK_FURIKOMI_D_SHITEI_CD
	,  NYSHKKNK_URAGKN_KISH_KEISU_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4574W_TBL IS '入出金機売上回収係数マスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED4574W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED4574W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED4574W_TBL.NYUSHUKKINKI_RYOGAEKI_KBN IS '入出金機両替機区分'
/
COMMENT ON COLUMN ED4574W_TBL.WK_NYUSHUKKINKI_RYGK_KBN_NM IS 'ワーク用入出金機両替機区分名称'
/
COMMENT ON COLUMN ED4574W_TBL.NYSHKKNK_FURIKOMI_D_SHITEI_CD IS '入出金機振込日指定コード'
/
COMMENT ON COLUMN ED4574W_TBL.WK_NYSHKKNK_FURIKOMI_D_SHT_NM IS 'ワーク用入出金機振込日指定名称'
/
COMMENT ON COLUMN ED4574W_TBL.NYSHKKNK_URAGKN_KISH_KEISU_CD IS '入出金機売上金回収係数コード'
/
COMMENT ON COLUMN ED4574W_TBL.URIAGE_KINRI_KEISU IS '売上金利係数'
/
COMMENT ON COLUMN ED4574W_TBL.GEKKAN_KAISHU_KAISU IS '月間回収回数'
/
COMMENT ON COLUMN ED4574W_TBL.TSURISEN_TESURYO_RYGE_KEISU IS '釣銭手数料両替係数'
/
COMMENT ON COLUMN ED4574W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4574W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4574W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED4574W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED4574W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED4574W_TBL.TH_NYSHKKNK_FURIKOMI_D_SHT_CD IS '退避用入出金機振込日指定コード'
/
COMMENT ON COLUMN ED4574W_TBL.TH_NYSHKKNK_URGKN_KSH_KES_CD IS '退避用入出金機売上金回収係数コード'
/
COMMENT ON COLUMN ED4574W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED4574W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED4574W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED4574W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED4574W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED4574W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4574W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4574W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4574W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4574W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4574W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4574W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4574W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4574W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4574W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4574W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4574W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
