/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4571W_TBL.sql
-- 物理名：ED4571W_TBL
-- 論理名：救急トレーニング料金マスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4571W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4571W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,WK_SHOHIN_SERVICE_NM  VARCHAR2(60) --「ワーク用商品サービス名称」
	,KYUKYU_TRAINING_COURSE_KBN  CHAR(1) NOT NULL --「救急トレーニングコース区分」
	,WK_KYUKYU_TRNNG_CRS_KBN_NM  VARCHAR2(60) --「ワーク用救急トレーニングコース区分名称」
	,HYOJI_JUN_1  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順１」
	,KYKY_TRINNG_HIYO_SHBTS_KBN  CHAR(1) NOT NULL --「救急トレーニング費用種別区分」
	,WK_KYKY_TRNNG_HY_SHBTS_KBN_NM  VARCHAR2(60) --「ワーク用救急トレーニング費用種別区分名称」
	,KYUKYU_TRAINING_KOMOKU_CD  CHAR(4) NOT NULL --「救急トレーニング項目コード」
	,KYUKYU_TRAINING_KOMOKU_NM  VARCHAR2(100) --「救急トレーニング項目名称」
	,KYKY_TRAINING_KYZI_PLAN_KBN  CHAR(1) NOT NULL --「救急トレーニング教材プラン区分」
	,WK_KYKY_TRNNG_KYZI_PLN_KBN_NM  VARCHAR2(60) --「ワーク用救急トレーニング教材プラン区分名称」
	,HYOJI_JUN_2  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順２」
	,KYUKYU_TRAINING_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「救急トレーニング原価金額」
	,KYUKYU_TRAINING_HYOJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「救急トレーニング標準金額」
	,KYKY_TRINNG_TSIK_GNK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「救急トレーニング追加原価金額」
	,KYKY_TRINNG_TSIK_HYJN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「救急トレーニング追加標準金額」
	,KYKY_TRINNG_RYKN_SNSHTS_KEISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「救急トレーニング料金算出係数」
	,KYKY_TRINNG_KSHS_SNSHTS_KEISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「救急トレーニング講師数算出係数」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,WK_HIMMEI_NM  VARCHAR2(60) --「ワーク用品名名称」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) NOT NULL --「アップロードテーブルＩＤ」
	,TH_SHOHIN_SERVICE_CD  CHAR(3) --「退避用商品サービスコード」
	,TH_KYUKYU_TRNNG_CRS_KBN  CHAR(1) --「退避用救急トレーニングコース区分」
	,TH_KYKY_TRINNG_HIYO_SHBTS_KBN  CHAR(1) --「退避用救急トレーニング費用種別区分」
	,TH_KYUKYU_TRAINING_KOMOKU_CD  CHAR(4) --「退避用救急トレーニング項目コード」
	,TH_KYKY_TRNNG_KYZI_PLN_KBN  CHAR(1) --「退避用救急トレーニング教材プラン区分」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4571W_PK PRIMARY KEY(
	 SHOHIN_SERVICE_CD
	,  KYUKYU_TRAINING_COURSE_KBN
	,  KYKY_TRINNG_HIYO_SHBTS_KBN
	,  KYUKYU_TRAINING_KOMOKU_CD
	,  KYKY_TRAINING_KYZI_PLAN_KBN
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4571W_TBL IS '救急トレーニング料金マスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED4571W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED4571W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED4571W_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4571W_TBL.WK_SHOHIN_SERVICE_NM IS 'ワーク用商品サービス名称'
/
COMMENT ON COLUMN ED4571W_TBL.KYUKYU_TRAINING_COURSE_KBN IS '救急トレーニングコース区分'
/
COMMENT ON COLUMN ED4571W_TBL.WK_KYUKYU_TRNNG_CRS_KBN_NM IS 'ワーク用救急トレーニングコース区分名称'
/
COMMENT ON COLUMN ED4571W_TBL.HYOJI_JUN_1 IS '表示順１'
/
COMMENT ON COLUMN ED4571W_TBL.KYKY_TRINNG_HIYO_SHBTS_KBN IS '救急トレーニング費用種別区分'
/
COMMENT ON COLUMN ED4571W_TBL.WK_KYKY_TRNNG_HY_SHBTS_KBN_NM IS 'ワーク用救急トレーニング費用種別区分名称'
/
COMMENT ON COLUMN ED4571W_TBL.KYUKYU_TRAINING_KOMOKU_CD IS '救急トレーニング項目コード'
/
COMMENT ON COLUMN ED4571W_TBL.KYUKYU_TRAINING_KOMOKU_NM IS '救急トレーニング項目名称'
/
COMMENT ON COLUMN ED4571W_TBL.KYKY_TRAINING_KYZI_PLAN_KBN IS '救急トレーニング教材プラン区分'
/
COMMENT ON COLUMN ED4571W_TBL.WK_KYKY_TRNNG_KYZI_PLN_KBN_NM IS 'ワーク用救急トレーニング教材プラン区分名称'
/
COMMENT ON COLUMN ED4571W_TBL.HYOJI_JUN_2 IS '表示順２'
/
COMMENT ON COLUMN ED4571W_TBL.KYUKYU_TRAINING_GENKA_AMT IS '救急トレーニング原価金額'
/
COMMENT ON COLUMN ED4571W_TBL.KYUKYU_TRAINING_HYOJUN_AMT IS '救急トレーニング標準金額'
/
COMMENT ON COLUMN ED4571W_TBL.KYKY_TRINNG_TSIK_GNK_AMT IS '救急トレーニング追加原価金額'
/
COMMENT ON COLUMN ED4571W_TBL.KYKY_TRINNG_TSIK_HYJN_AMT IS '救急トレーニング追加標準金額'
/
COMMENT ON COLUMN ED4571W_TBL.KYKY_TRINNG_RYKN_SNSHTS_KEISU IS '救急トレーニング料金算出係数'
/
COMMENT ON COLUMN ED4571W_TBL.KYKY_TRINNG_KSHS_SNSHTS_KEISU IS '救急トレーニング講師数算出係数'
/
COMMENT ON COLUMN ED4571W_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED4571W_TBL.WK_HIMMEI_NM IS 'ワーク用品名名称'
/
COMMENT ON COLUMN ED4571W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4571W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4571W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED4571W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED4571W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED4571W_TBL.TH_SHOHIN_SERVICE_CD IS '退避用商品サービスコード'
/
COMMENT ON COLUMN ED4571W_TBL.TH_KYUKYU_TRNNG_CRS_KBN IS '退避用救急トレーニングコース区分'
/
COMMENT ON COLUMN ED4571W_TBL.TH_KYKY_TRINNG_HIYO_SHBTS_KBN IS '退避用救急トレーニング費用種別区分'
/
COMMENT ON COLUMN ED4571W_TBL.TH_KYUKYU_TRAINING_KOMOKU_CD IS '退避用救急トレーニング項目コード'
/
COMMENT ON COLUMN ED4571W_TBL.TH_KYKY_TRNNG_KYZI_PLN_KBN IS '退避用救急トレーニング教材プラン区分'
/
COMMENT ON COLUMN ED4571W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED4571W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED4571W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED4571W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED4571W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED4571W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4571W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4571W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4571W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4571W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4571W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4571W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4571W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4571W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4571W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4571W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4571W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
