/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4564W_TBL.sql
-- 物理名：ED4564W_TBL
-- 論理名：機器構成フォロー設定詳細マスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4564W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4564W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,KIKI_KOSEI_FOLLOW_SETTEI_CD  CHAR(3) NOT NULL --「機器構成フォロー設定コード」
	,WK_KIKI_KOSEI_FLLW_SETTEI_NM  VARCHAR2(60) --「ワーク用機器構成フォロー設定名称」
	,KK_KSI_FOLLOW_STTI_SHSI_NO  CHAR(8) NOT NULL --「機器構成フォロー設定詳細番号」
	,KK_KSI_FOLLOW_STTI_SHSI_NM  VARCHAR2(60) NOT NULL --「機器構成フォロー設定詳細名称」
	,HYOJI_JUN_1  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順１」
	,HYOJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「標準金額」
	,GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「原価金額」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) NOT NULL --「アップロードテーブルＩＤ」
	,TH_KIKI_KOSEI_FLLW_SETTEI_CD  CHAR(3) --「退避用機器構成フォロー設定コード」
	,TH_KK_KSI_FLLW_STTI_SHSI_NO  CHAR(8) --「退避用機器構成フォロー設定詳細番号」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4564W_PK PRIMARY KEY(
	 KIKI_KOSEI_FOLLOW_SETTEI_CD
	,  KK_KSI_FOLLOW_STTI_SHSI_NO
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4564W_TBL IS '機器構成フォロー設定詳細マスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED4564W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED4564W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED4564W_TBL.KIKI_KOSEI_FOLLOW_SETTEI_CD IS '機器構成フォロー設定コード'
/
COMMENT ON COLUMN ED4564W_TBL.WK_KIKI_KOSEI_FLLW_SETTEI_NM IS 'ワーク用機器構成フォロー設定名称'
/
COMMENT ON COLUMN ED4564W_TBL.KK_KSI_FOLLOW_STTI_SHSI_NO IS '機器構成フォロー設定詳細番号'
/
COMMENT ON COLUMN ED4564W_TBL.KK_KSI_FOLLOW_STTI_SHSI_NM IS '機器構成フォロー設定詳細名称'
/
COMMENT ON COLUMN ED4564W_TBL.HYOJI_JUN_1 IS '表示順１'
/
COMMENT ON COLUMN ED4564W_TBL.HYOJUN_AMT IS '標準金額'
/
COMMENT ON COLUMN ED4564W_TBL.GENKA_AMT IS '原価金額'
/
COMMENT ON COLUMN ED4564W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4564W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4564W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED4564W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED4564W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED4564W_TBL.TH_KIKI_KOSEI_FLLW_SETTEI_CD IS '退避用機器構成フォロー設定コード'
/
COMMENT ON COLUMN ED4564W_TBL.TH_KK_KSI_FLLW_STTI_SHSI_NO IS '退避用機器構成フォロー設定詳細番号'
/
COMMENT ON COLUMN ED4564W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED4564W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED4564W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED4564W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED4564W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED4564W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4564W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4564W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4564W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4564W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4564W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4564W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4564W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4564W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4564W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4564W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4564W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
