/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4525W_TBL.sql
-- 物理名：ED4525W_TBL
-- 論理名：受注申請稟議マスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4525W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4525W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,WK_KAISHA_NM  VARCHAR2(40) --「ワーク用会社名称」
	,RINGI_CD  CHAR(10) NOT NULL --「稟議コード」
	,JUCHU_SHINSEI_RINGI_SN  CHAR(14) NOT NULL --「受注申請稟議連番」
	,RINGI_NM  VARCHAR2(40) --「稟議名称」
	,RINGI_HANTEI_JOKEN_KBN  CHAR(1) NOT NULL --「稟議判定条件区分」
	,WK_RINGI_HANTEI_JOKEN_KBN_NM  VARCHAR2(60) --「ワーク用稟議判定条件区分名称」
	,RINGI_HANTEICHI  NUMBER(12,3) DEFAULT '0' NOT NULL --「稟議判定値」
	,RNG_HNTI_SQL_NAIYO  VARCHAR2(1000) --「稟議判定ＳＱＬ内容」
	,RNG_HNTI_SQL_PROGRAM_ID  VARCHAR2(255) --「稟議判定プログラムＩＤ」
	,SHOHIN_SERVICE_CD  CHAR(3) --「商品サービスコード」
	,WK_SHOHIN_SERVICE_NM  VARCHAR2(60) --「ワーク用商品サービス名称」
	,GAMEN_HYOJI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「画面表示フラグ」
	,WK_GAMEN_HYOJI_FLG_NM  VARCHAR2(60) --「ワーク用画面表示フラグ名称」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) NOT NULL --「アップロードテーブルＩＤ」
	,TH_RINGI_CD  CHAR(10) --「退避用稟議コード」
	,TH_JUCHU_SHINSEI_RINGI_SN  CHAR(14) --「退避用受注申請稟議連番」
	,TH_KAISHA_CD  CHAR(5) --「退避用会社コード」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4525W_PK PRIMARY KEY(
	 RINGI_CD
	,  JUCHU_SHINSEI_RINGI_SN
	,  KAISHA_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4525W_TBL IS '受注申請稟議マスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED4525W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED4525W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED4525W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4525W_TBL.WK_KAISHA_NM IS 'ワーク用会社名称'
/
COMMENT ON COLUMN ED4525W_TBL.RINGI_CD IS '稟議コード'
/
COMMENT ON COLUMN ED4525W_TBL.JUCHU_SHINSEI_RINGI_SN IS '受注申請稟議連番'
/
COMMENT ON COLUMN ED4525W_TBL.RINGI_NM IS '稟議名称'
/
COMMENT ON COLUMN ED4525W_TBL.RINGI_HANTEI_JOKEN_KBN IS '稟議判定条件区分'
/
COMMENT ON COLUMN ED4525W_TBL.WK_RINGI_HANTEI_JOKEN_KBN_NM IS 'ワーク用稟議判定条件区分名称'
/
COMMENT ON COLUMN ED4525W_TBL.RINGI_HANTEICHI IS '稟議判定値'
/
COMMENT ON COLUMN ED4525W_TBL.RNG_HNTI_SQL_NAIYO IS '稟議判定ＳＱＬ内容'
/
COMMENT ON COLUMN ED4525W_TBL.RNG_HNTI_SQL_PROGRAM_ID IS '稟議判定プログラムＩＤ'
/
COMMENT ON COLUMN ED4525W_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4525W_TBL.WK_SHOHIN_SERVICE_NM IS 'ワーク用商品サービス名称'
/
COMMENT ON COLUMN ED4525W_TBL.GAMEN_HYOJI_FLG IS '画面表示フラグ'
/
COMMENT ON COLUMN ED4525W_TBL.WK_GAMEN_HYOJI_FLG_NM IS 'ワーク用画面表示フラグ名称'
/
COMMENT ON COLUMN ED4525W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4525W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4525W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED4525W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED4525W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED4525W_TBL.TH_RINGI_CD IS '退避用稟議コード'
/
COMMENT ON COLUMN ED4525W_TBL.TH_JUCHU_SHINSEI_RINGI_SN IS '退避用受注申請稟議連番'
/
COMMENT ON COLUMN ED4525W_TBL.TH_KAISHA_CD IS '退避用会社コード'
/
COMMENT ON COLUMN ED4525W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED4525W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED4525W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED4525W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED4525W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED4525W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4525W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4525W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4525W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4525W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4525W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4525W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4525W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4525W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4525W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4525W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4525W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
