/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4524W_TBL.sql
-- 物理名：ED4524W_TBL
-- 論理名：監視項目種別マスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4524W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4524W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,WK_SHOHIN_SERVICE_NM  VARCHAR2(60) --「ワーク用商品サービス名称」
	,OMONA_KANSHI_KOMOKU_KBN  CHAR(1) NOT NULL --「主な監視項目区分」
	,WK_OMONA_KANSI_KOMOKU_KBN_NM  VARCHAR2(60) --「ワーク用主な監視項目区分名称」
	,KANSHI_KOMOKU_SHUBETSU_CD  CHAR(3) NOT NULL --「監視項目種別コード」
	,HYOJI_JUN_1  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順１」
	,KANSHI_HOHO_KBN  CHAR(1) NOT NULL --「監視方法区分」
	,WK_KANSHI_HOHO_KBN_NM  VARCHAR2(60) --「ワーク用監視方法区分名称」
	,HYOJI_JUN_2  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順２」
	,KANSHI_JIKAN_KBN  CHAR(2) NOT NULL --「監視時間区分」
	,WK_KANSHI_JIKAN_KBN_NM  VARCHAR2(60) --「ワーク用監視時間区分名称」
	,KOMOKU_SHUBETSU_NM  VARCHAR2(300) --「監視項目種別名称」
	,KANSHI_KASHOSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「監視箇所数」
	,KANSHI_KASHOSU_HENKOKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「監視箇所数変更可フラグ」
	,WK_KNS_KASHOSU_HENKOKA_FLG_NM  VARCHAR2(60) --「ワーク用監視箇所数変更可フラグ名称」
	,SHOKI_HYOJI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「初期表示フラグ」
	,WK_SHOKI_HYOJI_FLG_NM  VARCHAR2(60) --「ワーク用初期表示フラグ名称」
	,KANSHI_KOMOKU_KASAN_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「監視項目加算原価金額」
	,KANSHI_KOMOKU_KASAN_HYOJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「監視項目加算標準金額」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) NOT NULL --「アップロードテーブルＩＤ」
	,TH_SHOHIN_SERVICE_CD  CHAR(3) --「退避用商品サービスコード」
	,TH_OMONA_KANSHI_KOMOKU_KBN  CHAR(1) --「退避用主な監視項目区分」
	,TH_KANSHI_KOMOKU_SHUBETSU_CD  CHAR(3) --「退避用監視項目種別コード」
	,TH_KANSHI_HOHO_KBN  CHAR(1) --「退避用監視方法区分」
	,TH_KANSHI_JIKAN_KBN  CHAR(2) --「退避用監視時間区分」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4524W_PK PRIMARY KEY(
	 SHOHIN_SERVICE_CD
	,  OMONA_KANSHI_KOMOKU_KBN
	,  KANSHI_KOMOKU_SHUBETSU_CD
	,  KANSHI_HOHO_KBN
	,  KANSHI_JIKAN_KBN
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4524W_TBL IS '監視項目種別マスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED4524W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED4524W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED4524W_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4524W_TBL.WK_SHOHIN_SERVICE_NM IS 'ワーク用商品サービス名称'
/
COMMENT ON COLUMN ED4524W_TBL.OMONA_KANSHI_KOMOKU_KBN IS '主な監視項目区分'
/
COMMENT ON COLUMN ED4524W_TBL.WK_OMONA_KANSI_KOMOKU_KBN_NM IS 'ワーク用主な監視項目区分名称'
/
COMMENT ON COLUMN ED4524W_TBL.KANSHI_KOMOKU_SHUBETSU_CD IS '監視項目種別コード'
/
COMMENT ON COLUMN ED4524W_TBL.HYOJI_JUN_1 IS '表示順１'
/
COMMENT ON COLUMN ED4524W_TBL.KANSHI_HOHO_KBN IS '監視方法区分'
/
COMMENT ON COLUMN ED4524W_TBL.WK_KANSHI_HOHO_KBN_NM IS 'ワーク用監視方法区分名称'
/
COMMENT ON COLUMN ED4524W_TBL.HYOJI_JUN_2 IS '表示順２'
/
COMMENT ON COLUMN ED4524W_TBL.KANSHI_JIKAN_KBN IS '監視時間区分'
/
COMMENT ON COLUMN ED4524W_TBL.WK_KANSHI_JIKAN_KBN_NM IS 'ワーク用監視時間区分名称'
/
COMMENT ON COLUMN ED4524W_TBL.KOMOKU_SHUBETSU_NM IS '監視項目種別名称'
/
COMMENT ON COLUMN ED4524W_TBL.KANSHI_KASHOSU IS '監視箇所数'
/
COMMENT ON COLUMN ED4524W_TBL.KANSHI_KASHOSU_HENKOKA_FLG IS '監視箇所数変更可フラグ'
/
COMMENT ON COLUMN ED4524W_TBL.WK_KNS_KASHOSU_HENKOKA_FLG_NM IS 'ワーク用監視箇所数変更可フラグ名称'
/
COMMENT ON COLUMN ED4524W_TBL.SHOKI_HYOJI_FLG IS '初期表示フラグ'
/
COMMENT ON COLUMN ED4524W_TBL.WK_SHOKI_HYOJI_FLG_NM IS 'ワーク用初期表示フラグ名称'
/
COMMENT ON COLUMN ED4524W_TBL.KANSHI_KOMOKU_KASAN_GENKA_AMT IS '監視項目加算原価金額'
/
COMMENT ON COLUMN ED4524W_TBL.KANSHI_KOMOKU_KASAN_HYOJUN_AMT IS '監視項目加算標準金額'
/
COMMENT ON COLUMN ED4524W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4524W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4524W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED4524W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED4524W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED4524W_TBL.TH_SHOHIN_SERVICE_CD IS '退避用商品サービスコード'
/
COMMENT ON COLUMN ED4524W_TBL.TH_OMONA_KANSHI_KOMOKU_KBN IS '退避用主な監視項目区分'
/
COMMENT ON COLUMN ED4524W_TBL.TH_KANSHI_KOMOKU_SHUBETSU_CD IS '退避用監視項目種別コード'
/
COMMENT ON COLUMN ED4524W_TBL.TH_KANSHI_HOHO_KBN IS '退避用監視方法区分'
/
COMMENT ON COLUMN ED4524W_TBL.TH_KANSHI_JIKAN_KBN IS '退避用監視時間区分'
/
COMMENT ON COLUMN ED4524W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED4524W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED4524W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED4524W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED4524W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED4524W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4524W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4524W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4524W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4524W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4524W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4524W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4524W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4524W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4524W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4524W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4524W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
