/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4558W_TBL.sql
-- 物理名：ED4558W_TBL
-- 論理名：工事額定型見積マスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4558W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4558W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,KAISHA_CD  CHAR(5) --「会社コード」
	,WK_KAISHA_NM  VARCHAR2(40) --「ワーク用会社名称」
	,TEIKEI_MITSUMORI_NO  CHAR(15) NOT NULL --「定型見積番号」
	,TEIKEI_MITSUMORI_NM  VARCHAR2(30) --「定型見積名称」
	,TEIKEI_MITSUMORI_NAIYO  VARCHAR2(200) --「定型見積内容」
	,HYOJI_JUN_1  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順１」
	,SHOHIN_SERVICE_CD  CHAR(3) --「商品サービスコード」
	,WK_SHOHIN_SERVICE_NM  VARCHAR2(60) --「ワーク用商品サービス名称」
	,KEIYAKU_BUNRUI_KBN  CHAR(1) DEFAULT '0' NOT NULL --「契約分類区分」
	,WK_KEIYAKU_BUNRUI_KBN_NM  VARCHAR2(60) --「ワーク用契約分類区分名称」
	,TORIHIKISAKI_CD  CHAR(9) --「取引先コード」
	,WK_TORIHIKISAKI_NM  VARCHAR2(40) --「ワーク用取引先名称」
	,TODOFUKEN_CD  CHAR(2) --「都道府県コード」
	,WK_TODOFUKEN_NM  VARCHAR2(4) --「ワーク用都道府県名称」
	,TEIKEI_MITSUMORI_KJ_HYOJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「定型見積工事標準金額」
	,TEIKEI_MITSUMORI_KJ_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「定型見積工事原価金額」
	,SAGYO_JIKAN_WARIMASHI_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「作業時間割増対象フラグ」
	,WK_SGY_JKN_WRMSH_TISH_FLG_NM  VARCHAR2(60) --「ワーク用作業時間割増対象フラグ名称」
	,KSH_SGY_KJ_TIKI_MTSMR_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「高所作業工事定型見積対象フラグ」
	,WK_K_KJ_TIKI_MTSMR_TISH_FLG_NM  VARCHAR2(60) --「ワーク用高所作業工事定型見積対象フラグ名称」
	,HATSURI_KJ_TIKI_MTSMR_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「はつり工事定型見積対象フラグ」
	,WK_H_KJ_TIKI_MTSMR_TISH_FLG_NM  VARCHAR2(60) --「ワーク用はつり工事定型見積対象フラグ名称」
	,DNKJ_KK_KJ_TIKI_MTSMR_TISH_FLG  CHAR(1) DEFAULT '0' NOT NULL --「電気錠切り欠き工事定型見積対象フラグ」
	,WK_D_KJ_TIKI_MTSMR_TISH_FLG_NM  VARCHAR2(60) --「ワーク用電気錠切り欠き工事定型見積対象フラグ名称」
	,SHOKI_HYOJI_FLG  CHAR(1) DEFAULT '1' NOT NULL --「初期表示フラグ」
	,WK_SHOKI_HYOJI_FLG_NM  VARCHAR2(60) --「ワーク用初期表示フラグ名称」
	,HISSU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「必須フラグ」
	,WK_HISSU_FLG_NM  VARCHAR2(60) --「ワーク用必須フラグ名称」
	,SHOKI_HYOJI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「初期表示数量」
	,SURYO_HENKOKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「数量変更可フラグ」
	,WK_SURYO_HENKOKA_FLG_NM  VARCHAR2(60) --「ワーク用数量変更可フラグ名称」
	,JOGEN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「上限数量」
	,KAGEN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「下限数量」
	,GENKA_KINGAKU_HENKOKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「原価金額変更可フラグ」
	,WK_GENKA_KINGAKU_HNKK_FLG_NM  VARCHAR2(60) --「ワーク用原価金額変更可フラグ名称」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) NOT NULL --「アップロードテーブルＩＤ」
	,TH_TEIKEI_MITSUMORI_NO  CHAR(15) --「退避用定型見積番号」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4558W_PK PRIMARY KEY(
	 TEIKEI_MITSUMORI_NO
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4558W_TBL IS '工事額定型見積マスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED4558W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED4558W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED4558W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4558W_TBL.WK_KAISHA_NM IS 'ワーク用会社名称'
/
COMMENT ON COLUMN ED4558W_TBL.TEIKEI_MITSUMORI_NO IS '定型見積番号'
/
COMMENT ON COLUMN ED4558W_TBL.TEIKEI_MITSUMORI_NM IS '定型見積名称'
/
COMMENT ON COLUMN ED4558W_TBL.TEIKEI_MITSUMORI_NAIYO IS '定型見積内容'
/
COMMENT ON COLUMN ED4558W_TBL.HYOJI_JUN_1 IS '表示順１'
/
COMMENT ON COLUMN ED4558W_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4558W_TBL.WK_SHOHIN_SERVICE_NM IS 'ワーク用商品サービス名称'
/
COMMENT ON COLUMN ED4558W_TBL.KEIYAKU_BUNRUI_KBN IS '契約分類区分'
/
COMMENT ON COLUMN ED4558W_TBL.WK_KEIYAKU_BUNRUI_KBN_NM IS 'ワーク用契約分類区分名称'
/
COMMENT ON COLUMN ED4558W_TBL.TORIHIKISAKI_CD IS '取引先コード'
/
COMMENT ON COLUMN ED4558W_TBL.WK_TORIHIKISAKI_NM IS 'ワーク用取引先名称'
/
COMMENT ON COLUMN ED4558W_TBL.TODOFUKEN_CD IS '都道府県コード'
/
COMMENT ON COLUMN ED4558W_TBL.WK_TODOFUKEN_NM IS 'ワーク用都道府県名称'
/
COMMENT ON COLUMN ED4558W_TBL.TEIKEI_MITSUMORI_KJ_HYOJUN_AMT IS '定型見積工事標準金額'
/
COMMENT ON COLUMN ED4558W_TBL.TEIKEI_MITSUMORI_KJ_GENKA_AMT IS '定型見積工事原価金額'
/
COMMENT ON COLUMN ED4558W_TBL.SAGYO_JIKAN_WARIMASHI_TISH_FLG IS '作業時間割増対象フラグ'
/
COMMENT ON COLUMN ED4558W_TBL.WK_SGY_JKN_WRMSH_TISH_FLG_NM IS 'ワーク用作業時間割増対象フラグ名称'
/
COMMENT ON COLUMN ED4558W_TBL.KSH_SGY_KJ_TIKI_MTSMR_TISH_FLG IS '高所作業工事定型見積対象フラグ'
/
COMMENT ON COLUMN ED4558W_TBL.WK_K_KJ_TIKI_MTSMR_TISH_FLG_NM IS 'ワーク用高所作業工事定型見積対象フラグ名称'
/
COMMENT ON COLUMN ED4558W_TBL.HATSURI_KJ_TIKI_MTSMR_TISH_FLG IS 'はつり工事定型見積対象フラグ'
/
COMMENT ON COLUMN ED4558W_TBL.WK_H_KJ_TIKI_MTSMR_TISH_FLG_NM IS 'ワーク用はつり工事定型見積対象フラグ名称'
/
COMMENT ON COLUMN ED4558W_TBL.DNKJ_KK_KJ_TIKI_MTSMR_TISH_FLG IS '電気錠切り欠き工事定型見積対象フラグ'
/
COMMENT ON COLUMN ED4558W_TBL.WK_D_KJ_TIKI_MTSMR_TISH_FLG_NM IS 'ワーク用電気錠切り欠き工事定型見積対象フラグ名称'
/
COMMENT ON COLUMN ED4558W_TBL.SHOKI_HYOJI_FLG IS '初期表示フラグ'
/
COMMENT ON COLUMN ED4558W_TBL.WK_SHOKI_HYOJI_FLG_NM IS 'ワーク用初期表示フラグ名称'
/
COMMENT ON COLUMN ED4558W_TBL.HISSU_FLG IS '必須フラグ'
/
COMMENT ON COLUMN ED4558W_TBL.WK_HISSU_FLG_NM IS 'ワーク用必須フラグ名称'
/
COMMENT ON COLUMN ED4558W_TBL.SHOKI_HYOJI_SURYO IS '初期表示数量'
/
COMMENT ON COLUMN ED4558W_TBL.SURYO_HENKOKA_FLG IS '数量変更可フラグ'
/
COMMENT ON COLUMN ED4558W_TBL.WK_SURYO_HENKOKA_FLG_NM IS 'ワーク用数量変更可フラグ名称'
/
COMMENT ON COLUMN ED4558W_TBL.JOGEN_SURYO IS '上限数量'
/
COMMENT ON COLUMN ED4558W_TBL.KAGEN_SURYO IS '下限数量'
/
COMMENT ON COLUMN ED4558W_TBL.GENKA_KINGAKU_HENKOKA_FLG IS '原価金額変更可フラグ'
/
COMMENT ON COLUMN ED4558W_TBL.WK_GENKA_KINGAKU_HNKK_FLG_NM IS 'ワーク用原価金額変更可フラグ名称'
/
COMMENT ON COLUMN ED4558W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4558W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4558W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED4558W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED4558W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED4558W_TBL.TH_TEIKEI_MITSUMORI_NO IS '退避用定型見積番号'
/
COMMENT ON COLUMN ED4558W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED4558W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED4558W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED4558W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED4558W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED4558W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4558W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4558W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4558W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4558W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4558W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4558W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4558W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4558W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4558W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4558W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4558W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
