/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4548W_TBL.sql
-- 物理名：ED4548W_TBL
-- 論理名：情報通信本体機器マスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4548W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4548W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,WK_SHOHIN_SERVICE_NM  VARCHAR2(60) --「ワーク用商品サービス名称」
	,JH_TSSHN_HNTI_KIKI_CD  CHAR(8) NOT NULL --「情報通信本体機器コード」
	,HYOJI_JUN_1  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順１」
	,HIMMEI_CD  CHAR(8) NOT NULL --「品名コード」
	,WK_HIMMEI_NM  VARCHAR2(60) --「ワーク用品名名称」
	,KISHU_NM  VARCHAR2(30) --「機種名称」
	,JOGEN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「上限数量」
	,KAGEN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「下限数量」
	,GYM_ITKSK_TRHKSK_CD  CHAR(9) --「業務委託先取引先コード」
	,WK_GYM_ITKSK_TRHKSK_NM  VARCHAR2(40) --「ワーク用業務委託先取引先名称」
	,GYM_ITKSK_TRHKSK_BSH_CD  CHAR(4) --「業務委託先取引先部署コード」
	,WK_GYM_ITKSK_TRHKSK_BWK_NM  VARCHAR2(40) --「ワーク用業務委託先取引先部署名称」
	,SHOKI_HYOJI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「初期表示フラグ」
	,WK_SHOKI_HYOJI_FLG_NM  VARCHAR2(60) --「ワーク用初期表示フラグ名称」
	,SHOKI_HYOJI_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「初期表示数量」
	,HISSU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「必須フラグ」
	,WK_HISSU_FLG_NM  VARCHAR2(60) --「ワーク用必須フラグ名称」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) NOT NULL --「アップロードテーブルＩＤ」
	,TH_SHOHIN_SERVICE_CD  CHAR(3) --「退避用商品サービスコード」
	,TH_JH_TSSHN_HNTI_KIKI_CD  CHAR(8) --「退避用情報通信本体機器コード」
	,TH_HIMMEI_CD  CHAR(8) --「退避用品名コード」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4548W_PK PRIMARY KEY(
	 SHOHIN_SERVICE_CD
	,  JH_TSSHN_HNTI_KIKI_CD
	,  HIMMEI_CD
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4548W_TBL IS '情報通信本体機器マスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED4548W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED4548W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED4548W_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4548W_TBL.WK_SHOHIN_SERVICE_NM IS 'ワーク用商品サービス名称'
/
COMMENT ON COLUMN ED4548W_TBL.JH_TSSHN_HNTI_KIKI_CD IS '情報通信本体機器コード'
/
COMMENT ON COLUMN ED4548W_TBL.HYOJI_JUN_1 IS '表示順１'
/
COMMENT ON COLUMN ED4548W_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED4548W_TBL.WK_HIMMEI_NM IS 'ワーク用品名名称'
/
COMMENT ON COLUMN ED4548W_TBL.KISHU_NM IS '機種名称'
/
COMMENT ON COLUMN ED4548W_TBL.JOGEN_SURYO IS '上限数量'
/
COMMENT ON COLUMN ED4548W_TBL.KAGEN_SURYO IS '下限数量'
/
COMMENT ON COLUMN ED4548W_TBL.GYM_ITKSK_TRHKSK_CD IS '業務委託先取引先コード'
/
COMMENT ON COLUMN ED4548W_TBL.WK_GYM_ITKSK_TRHKSK_NM IS 'ワーク用業務委託先取引先名称'
/
COMMENT ON COLUMN ED4548W_TBL.GYM_ITKSK_TRHKSK_BSH_CD IS '業務委託先取引先部署コード'
/
COMMENT ON COLUMN ED4548W_TBL.WK_GYM_ITKSK_TRHKSK_BWK_NM IS 'ワーク用業務委託先取引先部署名称'
/
COMMENT ON COLUMN ED4548W_TBL.SHOKI_HYOJI_FLG IS '初期表示フラグ'
/
COMMENT ON COLUMN ED4548W_TBL.WK_SHOKI_HYOJI_FLG_NM IS 'ワーク用初期表示フラグ名称'
/
COMMENT ON COLUMN ED4548W_TBL.SHOKI_HYOJI_SURYO IS '初期表示数量'
/
COMMENT ON COLUMN ED4548W_TBL.HISSU_FLG IS '必須フラグ'
/
COMMENT ON COLUMN ED4548W_TBL.WK_HISSU_FLG_NM IS 'ワーク用必須フラグ名称'
/
COMMENT ON COLUMN ED4548W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4548W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4548W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED4548W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED4548W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED4548W_TBL.TH_SHOHIN_SERVICE_CD IS '退避用商品サービスコード'
/
COMMENT ON COLUMN ED4548W_TBL.TH_JH_TSSHN_HNTI_KIKI_CD IS '退避用情報通信本体機器コード'
/
COMMENT ON COLUMN ED4548W_TBL.TH_HIMMEI_CD IS '退避用品名コード'
/
COMMENT ON COLUMN ED4548W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED4548W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED4548W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED4548W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED4548W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED4548W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4548W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4548W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4548W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4548W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4548W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4548W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4548W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4548W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4548W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4548W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4548W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
