/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4570W_TBL.sql
-- 物理名：ED4570W_TBL
-- 論理名：見積書固定文言マスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4570W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4570W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,SHOHIN_SERVICE_CD  CHAR(3) NOT NULL --「商品サービスコード」
	,WK_SHOHIN_SERVICE_NM  VARCHAR2(60) --「ワーク用商品サービス名称」
	,CHOHYO_ID  VARCHAR2(20) NOT NULL --「帳票ＩＤ」
	,MITSUMORISHO_CHOHYOKOMOKU_ID  VARCHAR2(255) NOT NULL --「見積書帳票項目ＩＤ」
	,MTSMRSH_KOTEI_MONGON_SN  CHAR(14) NOT NULL --「見積書固定文言連番」
	,HYOJI_JUN_1  NUMBER(4,0) DEFAULT '0' NOT NULL --「表示順１」
	,MTSMRSH_KOTEI_MONGON_NAIYO  VARCHAR2(100) --「見積書固定文言内容」
	,SHOHIZEI_KBN  CHAR(1) DEFAULT '0' NOT NULL --「消費税区分」
	,WK_SHOHIZEI_KBN_NM  VARCHAR2(60) --「ワーク用消費税区分名称」
	,MTSMRSH_KTI_MNGN_NIY_S_HNT_KBN  CHAR(5) DEFAULT '00000' NOT NULL --「見積書固定文言内容出力判定区分」
	,WK_MTSMRSH_KMGN_NIY_HNT_KBN_NM  VARCHAR2(60) --「ワーク用見積書固定文言内容出力判定区分名称」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) NOT NULL --「アップロードテーブルＩＤ」
	,TH_SHOHIN_SERVICE_CD  CHAR(3) --「退避用商品サービスコード」
	,TH_CHOHYO_ID  VARCHAR2(20) --「退避用帳票ＩＤ」
	,TH_MITSUMORISHO_CHHYKOMOKU_ID  VARCHAR2(255) --「退避用見積書帳票項目ＩＤ」
	,TH_MTSMRSH_KOTEI_MONGON_SN  CHAR(14) --「退避用見積書固定文言連番」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4570W_PK PRIMARY KEY(
	 SHOHIN_SERVICE_CD
	,  CHOHYO_ID
	,  MITSUMORISHO_CHOHYOKOMOKU_ID
	,  MTSMRSH_KOTEI_MONGON_SN
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4570W_TBL IS '見積書固定文言マスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED4570W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED4570W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED4570W_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED4570W_TBL.WK_SHOHIN_SERVICE_NM IS 'ワーク用商品サービス名称'
/
COMMENT ON COLUMN ED4570W_TBL.CHOHYO_ID IS '帳票ＩＤ'
/
COMMENT ON COLUMN ED4570W_TBL.MITSUMORISHO_CHOHYOKOMOKU_ID IS '見積書帳票項目ＩＤ'
/
COMMENT ON COLUMN ED4570W_TBL.MTSMRSH_KOTEI_MONGON_SN IS '見積書固定文言連番'
/
COMMENT ON COLUMN ED4570W_TBL.HYOJI_JUN_1 IS '表示順１'
/
COMMENT ON COLUMN ED4570W_TBL.MTSMRSH_KOTEI_MONGON_NAIYO IS '見積書固定文言内容'
/
COMMENT ON COLUMN ED4570W_TBL.SHOHIZEI_KBN IS '消費税区分'
/
COMMENT ON COLUMN ED4570W_TBL.WK_SHOHIZEI_KBN_NM IS 'ワーク用消費税区分名称'
/
COMMENT ON COLUMN ED4570W_TBL.MTSMRSH_KTI_MNGN_NIY_S_HNT_KBN IS '見積書固定文言内容出力判定区分'
/
COMMENT ON COLUMN ED4570W_TBL.WK_MTSMRSH_KMGN_NIY_HNT_KBN_NM IS 'ワーク用見積書固定文言内容出力判定区分名称'
/
COMMENT ON COLUMN ED4570W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4570W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4570W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED4570W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED4570W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED4570W_TBL.TH_SHOHIN_SERVICE_CD IS '退避用商品サービスコード'
/
COMMENT ON COLUMN ED4570W_TBL.TH_CHOHYO_ID IS '退避用帳票ＩＤ'
/
COMMENT ON COLUMN ED4570W_TBL.TH_MITSUMORISHO_CHHYKOMOKU_ID IS '退避用見積書帳票項目ＩＤ'
/
COMMENT ON COLUMN ED4570W_TBL.TH_MTSMRSH_KOTEI_MONGON_SN IS '退避用見積書固定文言連番'
/
COMMENT ON COLUMN ED4570W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED4570W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED4570W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED4570W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED4570W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED4570W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4570W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4570W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4570W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4570W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4570W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4570W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4570W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4570W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4570W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4570W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4570W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
