/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED4505W_TBL.sql
-- 物理名：ED4505W_TBL
-- 論理名：受注申請与信マスタＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED4505W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED4505W_TBL (
	 SEKISAN_RECORD_SOSA_KBN  CHAR(1) --「積算レコード操作区分」
	,WK_SKSN_RECORD_SOSA_KBN_NM  VARCHAR2(60) --「ワーク用積算レコード操作区分名称」
	,KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,WK_KAISHA_NM  VARCHAR2(40) --「ワーク用会社名称」
	,YOSHIN_KOMOKU_CD  CHAR(10) NOT NULL --「与信項目コード」
	,YOSHIN_KOMOKU_MEISAI_NO  CHAR(3) NOT NULL --「与信項目明細番号」
	,KEIYAKU_BUNRUI_KBN  CHAR(1) NOT NULL --「契約分類区分」
	,WK_KEIYAKU_BUNRUI_KBN_NM  VARCHAR2(60) --「ワーク用契約分類区分名称」
	,YOSHIN_KOMOKU_NM  VARCHAR2(60) --「与信項目名称」
	,YOSHIN_HANTEI_SHORI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「与信判定処理順」
	,YOSHIN_KOMOKU_GAMEN_HYOJI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「与信項目画面表示順」
	,YOSHIN_HANTEI_SQL_NAIYO  VARCHAR2(1000) --「与信判定ＳＱＬ内容」
	,YOSHIN_HANTEI_PROGRAM_ID  VARCHAR2(255) --「与信判定プログラムＩＤ」
	,YOSHIN_HANTEI_JOKEN_KBN  CHAR(1) NOT NULL --「与信判定条件区分」
	,WK_YOSHIN_HANTEI_JOKEN_KBN_NM  VARCHAR2(60) --「ワーク用与信判定条件区分名称」
	,YOSHIN_HANTEICHI  NUMBER(12,3) DEFAULT '0' NOT NULL --「与信判定値」
	,YOSHIN_HANTEI_TISH_NM_1  VARCHAR2(40) --「与信判定対象名称１」
	,YOSHIN_HANTEI_TISH_NM_2  VARCHAR2(40) --「与信判定対象名称２」
	,YOSHIN_JISSHI_KBN  CHAR(1) NOT NULL --「与信実施区分」
	,WK_YOSIN_JISSHI_KBN_NM  VARCHAR2(60) --「ワーク用与信実施区分名称」
	,YOSHIN_HANTEI_END_FLG  CHAR(1) DEFAULT '0' NOT NULL --「与信判定終了フラグ」
	,WK_YSHN_HANTEI_SHURYO_FLG_NM  VARCHAR2(60) --「ワーク用与信判定終了フラグ名称」
	,YSHN_TRHK_NIY_TEXT_BOX_HYJ_FLG  CHAR(1) DEFAULT '0' NOT NULL --「与信取引内容テキストボックス表示フラグ」
	,WK_YSN_TRH_NY_TXT_BX_HY_FLG_NM  VARCHAR2(60) --「ワーク用与信取引内容テキストボックス表示フラグ名称」
	,YOSHIN_TRHK_KNGK_SHJN_KJN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「与信取引金額昇順降順フラグ」
	,WK_YSHN_TRHK_KNGK_SH_K_FLG_NM  VARCHAR2(60) --「ワーク用与信取引金額昇順降順フラグ名称」
	,EIGYOIN_SHNN_YSHN_TRHK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「営業員承認与信取引金額」
	,KACHO_SHNN_YSHN_TRHK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「課長承認与信取引金額」
	,BUCHO_SHNN_YSHN_TRHK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「部長承認与信取引金額」
	,SHOZOKUCHO_SHNN_YSHN_TRHK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「所属長承認与信取引金額」
	,CHIK_HNBCH_SHNN_YSHN_TRHK_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「地域本部長承認与信取引金額」
	,YOSHIN_JOHO_SHOSAI_NAIYO  VARCHAR2(40) --「与信情報詳細内容」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,ZENKAI_TEKIYO_KAISHI_YMD  DATE --「前回適用開始年月日」
	,ZENKAI_TEKIYO_SHURYO_YMD  DATE --「前回適用終了年月日」
	,UPLOAD_TABLE_ID  CHAR(11) NOT NULL --「アップロードテーブルＩＤ」
	,TH_YOSHIN_KOMOKU_CD  CHAR(10) --「退避用与信項目コード」
	,TH_KAISHA_CD  CHAR(5) --「退避用会社コード」
	,TH_YOSHIN_KOMOKU_MEISAI_NO  CHAR(3) --「退避用与信項目明細番号」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,CSV_WK_GYO_NO  CHAR(7) --「ＣＳＶワーク行番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED4505W_PK PRIMARY KEY(
	 YOSHIN_KOMOKU_CD
	,  KAISHA_CD
	,  YOSHIN_KOMOKU_MEISAI_NO
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED4505W_TBL IS '受注申請与信マスタＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED4505W_TBL.SEKISAN_RECORD_SOSA_KBN IS '積算レコード操作区分'
/
COMMENT ON COLUMN ED4505W_TBL.WK_SKSN_RECORD_SOSA_KBN_NM IS 'ワーク用積算レコード操作区分名称'
/
COMMENT ON COLUMN ED4505W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED4505W_TBL.WK_KAISHA_NM IS 'ワーク用会社名称'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_KOMOKU_CD IS '与信項目コード'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_KOMOKU_MEISAI_NO IS '与信項目明細番号'
/
COMMENT ON COLUMN ED4505W_TBL.KEIYAKU_BUNRUI_KBN IS '契約分類区分'
/
COMMENT ON COLUMN ED4505W_TBL.WK_KEIYAKU_BUNRUI_KBN_NM IS 'ワーク用契約分類区分名称'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_KOMOKU_NM IS '与信項目名称'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_HANTEI_SHORI_JUN IS '与信判定処理順'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_KOMOKU_GAMEN_HYOJI_JUN IS '与信項目画面表示順'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_HANTEI_SQL_NAIYO IS '与信判定ＳＱＬ内容'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_HANTEI_PROGRAM_ID IS '与信判定プログラムＩＤ'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_HANTEI_JOKEN_KBN IS '与信判定条件区分'
/
COMMENT ON COLUMN ED4505W_TBL.WK_YOSHIN_HANTEI_JOKEN_KBN_NM IS 'ワーク用与信判定条件区分名称'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_HANTEICHI IS '与信判定値'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_HANTEI_TISH_NM_1 IS '与信判定対象名称１'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_HANTEI_TISH_NM_2 IS '与信判定対象名称２'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_JISSHI_KBN IS '与信実施区分'
/
COMMENT ON COLUMN ED4505W_TBL.WK_YOSIN_JISSHI_KBN_NM IS 'ワーク用与信実施区分名称'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_HANTEI_END_FLG IS '与信判定終了フラグ'
/
COMMENT ON COLUMN ED4505W_TBL.WK_YSHN_HANTEI_SHURYO_FLG_NM IS 'ワーク用与信判定終了フラグ名称'
/
COMMENT ON COLUMN ED4505W_TBL.YSHN_TRHK_NIY_TEXT_BOX_HYJ_FLG IS '与信取引内容テキストボックス表示フラグ'
/
COMMENT ON COLUMN ED4505W_TBL.WK_YSN_TRH_NY_TXT_BX_HY_FLG_NM IS 'ワーク用与信取引内容テキストボックス表示フラグ名称'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_TRHK_KNGK_SHJN_KJN_FLG IS '与信取引金額昇順降順フラグ'
/
COMMENT ON COLUMN ED4505W_TBL.WK_YSHN_TRHK_KNGK_SH_K_FLG_NM IS 'ワーク用与信取引金額昇順降順フラグ名称'
/
COMMENT ON COLUMN ED4505W_TBL.EIGYOIN_SHNN_YSHN_TRHK_AMT IS '営業員承認与信取引金額'
/
COMMENT ON COLUMN ED4505W_TBL.KACHO_SHNN_YSHN_TRHK_AMT IS '課長承認与信取引金額'
/
COMMENT ON COLUMN ED4505W_TBL.BUCHO_SHNN_YSHN_TRHK_AMT IS '部長承認与信取引金額'
/
COMMENT ON COLUMN ED4505W_TBL.SHOZOKUCHO_SHNN_YSHN_TRHK_AMT IS '所属長承認与信取引金額'
/
COMMENT ON COLUMN ED4505W_TBL.CHIK_HNBCH_SHNN_YSHN_TRHK_AMT IS '地域本部長承認与信取引金額'
/
COMMENT ON COLUMN ED4505W_TBL.YOSHIN_JOHO_SHOSAI_NAIYO IS '与信情報詳細内容'
/
COMMENT ON COLUMN ED4505W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED4505W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED4505W_TBL.ZENKAI_TEKIYO_KAISHI_YMD IS '前回適用開始年月日'
/
COMMENT ON COLUMN ED4505W_TBL.ZENKAI_TEKIYO_SHURYO_YMD IS '前回適用終了年月日'
/
COMMENT ON COLUMN ED4505W_TBL.UPLOAD_TABLE_ID IS 'アップロードテーブルＩＤ'
/
COMMENT ON COLUMN ED4505W_TBL.TH_YOSHIN_KOMOKU_CD IS '退避用与信項目コード'
/
COMMENT ON COLUMN ED4505W_TBL.TH_KAISHA_CD IS '退避用会社コード'
/
COMMENT ON COLUMN ED4505W_TBL.TH_YOSHIN_KOMOKU_MEISAI_NO IS '退避用与信項目明細番号'
/
COMMENT ON COLUMN ED4505W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED4505W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED4505W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED4505W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED4505W_TBL.CSV_WK_GYO_NO IS 'ＣＳＶワーク行番号'
/
COMMENT ON COLUMN ED4505W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED4505W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED4505W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED4505W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED4505W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED4505W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED4505W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED4505W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED4505W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED4505W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED4505W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED4505W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
