/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED5102T_TBL.sql
-- 物理名：ED5102T_TBL
-- 論理名：ＮＢ警送従量分確定テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED5102T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED5102T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,NB_KEISO_JURYOBUN_TAISHO_YM  CHAR(6) NOT NULL --「ＮＢ警送従量分対象年月」
	,NB_KEISO_JURYOBUN_RIREKI_NO  NUMBER(2,0) DEFAULT '0' NOT NULL --「ＮＢ警送従量分履歴番号」
	,NB_KEISO_JURYOBUN_GYO_NO  NUMBER(9,0) DEFAULT '0' NOT NULL --「ＮＢ警送従量分行番号」
	,NB_KIS_JRYBN_TRKSH_ZM_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＮＢ警送従量分取消済フラグ」
	,SEJ_KBN  CHAR(1) NOT NULL --「ＳＥＪ区分」
	,NB_KEISO_JURYOBUN_SEIKYU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＮＢ警送従量分請求金額」
	,GYOMU_ITAKU_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「業務委託料金金額」
	,NB_CASSETTE_KOKAN_JISSEKI_KBN  CHAR(1) NOT NULL --「ＮＢカセット交換実績区分」
	,NB_ATM_SOCHI_NO  CHAR(7) --「ＮＢＡＴＭ装置番号」
	,NB_KEISO_JUCHU_KEIYAKU_NO  CHAR(15) --「ＮＢ警送受注契約番号」
	,NB_KEISO_JURYOBUN_SHORI_YMD  DATE --「ＮＢ警送従量分処理年月日」
	,NB_KEISO_JURYOBUN_UKETSUKE_YMD  DATE --「ＮＢ警送従量分受付年月日」
	,NB_KIS_JRYBN_NYKN_JKK_NAIYO  CHAR(8) --「ＮＢ警送従量分入館時刻内容」
	,NB_KIS_JRYBN_KKN_JKK_NAIYO  CHAR(8) --「ＮＢ警送従量分交換時刻内容」
	,NB_KIS_JRYBN_TIKN_JKK_NAIYO  CHAR(8) --「ＮＢ警送従量分退館時刻内容」
	,NB_CASSETTE_KOKAN_TEMPO_NM  VARCHAR2(60) --「ＮＢカセット交換店舗名称」
	,NB_CASSETTE_KOKAN_RIYU_CD  CHAR(2) --「ＮＢカセット交換理由コード」
	,NB_KAKUTEISHORI_YMD  DATE --「ＮＢ確定処理年月日」
	,NB_KKTISHR_EIGYKNR_NENDO  CHAR(4) --「ＮＢ確定処理営業管理年度」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED5102T_PK PRIMARY KEY(
	 NB_KEISO_JURYOBUN_TAISHO_YM
	,  NB_KEISO_JURYOBUN_RIREKI_NO
	,  NB_KEISO_JURYOBUN_GYO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED5102T_TBL IS 'ＮＢ警送従量分確定テーブル'
/

COMMENT ON COLUMN ED5102T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED5102T_TBL.NB_KEISO_JURYOBUN_TAISHO_YM IS 'ＮＢ警送従量分対象年月'
/
COMMENT ON COLUMN ED5102T_TBL.NB_KEISO_JURYOBUN_RIREKI_NO IS 'ＮＢ警送従量分履歴番号'
/
COMMENT ON COLUMN ED5102T_TBL.NB_KEISO_JURYOBUN_GYO_NO IS 'ＮＢ警送従量分行番号'
/
COMMENT ON COLUMN ED5102T_TBL.NB_KIS_JRYBN_TRKSH_ZM_FLG IS 'ＮＢ警送従量分取消済フラグ'
/
COMMENT ON COLUMN ED5102T_TBL.SEJ_KBN IS 'ＳＥＪ区分'
/
COMMENT ON COLUMN ED5102T_TBL.NB_KEISO_JURYOBUN_SEIKYU_AMT IS 'ＮＢ警送従量分請求金額'
/
COMMENT ON COLUMN ED5102T_TBL.GYOMU_ITAKU_RYOKIN_AMT IS '業務委託料金金額'
/
COMMENT ON COLUMN ED5102T_TBL.NB_CASSETTE_KOKAN_JISSEKI_KBN IS 'ＮＢカセット交換実績区分'
/
COMMENT ON COLUMN ED5102T_TBL.NB_ATM_SOCHI_NO IS 'ＮＢＡＴＭ装置番号'
/
COMMENT ON COLUMN ED5102T_TBL.NB_KEISO_JUCHU_KEIYAKU_NO IS 'ＮＢ警送受注契約番号'
/
COMMENT ON COLUMN ED5102T_TBL.NB_KEISO_JURYOBUN_SHORI_YMD IS 'ＮＢ警送従量分処理年月日'
/
COMMENT ON COLUMN ED5102T_TBL.NB_KEISO_JURYOBUN_UKETSUKE_YMD IS 'ＮＢ警送従量分受付年月日'
/
COMMENT ON COLUMN ED5102T_TBL.NB_KIS_JRYBN_NYKN_JKK_NAIYO IS 'ＮＢ警送従量分入館時刻内容'
/
COMMENT ON COLUMN ED5102T_TBL.NB_KIS_JRYBN_KKN_JKK_NAIYO IS 'ＮＢ警送従量分交換時刻内容'
/
COMMENT ON COLUMN ED5102T_TBL.NB_KIS_JRYBN_TIKN_JKK_NAIYO IS 'ＮＢ警送従量分退館時刻内容'
/
COMMENT ON COLUMN ED5102T_TBL.NB_CASSETTE_KOKAN_TEMPO_NM IS 'ＮＢカセット交換店舗名称'
/
COMMENT ON COLUMN ED5102T_TBL.NB_CASSETTE_KOKAN_RIYU_CD IS 'ＮＢカセット交換理由コード'
/
COMMENT ON COLUMN ED5102T_TBL.NB_KAKUTEISHORI_YMD IS 'ＮＢ確定処理年月日'
/
COMMENT ON COLUMN ED5102T_TBL.NB_KKTISHR_EIGYKNR_NENDO IS 'ＮＢ確定処理営業管理年度'
/
COMMENT ON COLUMN ED5102T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED5102T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED5102T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED5102T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED5102T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED5102T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED5102T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED5102T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED5102T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED5102T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED5102T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED5102T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
