/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED5104M_TBL.sql
-- 物理名：ED5104M_TBL
-- 論理名：ＮＢ警送従量分金額マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED5104M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED5104M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SEJ_KBN  CHAR(1) NOT NULL --「ＳＥＪ区分」
	,NB_KIS_JRYBN_TSJ_SKO_KBN  CHAR(1) NOT NULL --「ＮＢ警送従量分通常即応区分」
	,NB_KEISO_JURYOBUN_SEIKYU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＮＢ警送従量分請求金額」
	,GYOMU_ITAKU_RYOKIN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「業務委託料金金額」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED5104M_PK PRIMARY KEY(
	 SEJ_KBN
	,  NB_KIS_JRYBN_TSJ_SKO_KBN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED5104M_TBL IS 'ＮＢ警送従量分金額マスタ'
/

COMMENT ON COLUMN ED5104M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED5104M_TBL.SEJ_KBN IS 'ＳＥＪ区分'
/
COMMENT ON COLUMN ED5104M_TBL.NB_KIS_JRYBN_TSJ_SKO_KBN IS 'ＮＢ警送従量分通常即応区分'
/
COMMENT ON COLUMN ED5104M_TBL.NB_KEISO_JURYOBUN_SEIKYU_AMT IS 'ＮＢ警送従量分請求金額'
/
COMMENT ON COLUMN ED5104M_TBL.GYOMU_ITAKU_RYOKIN_AMT IS '業務委託料金金額'
/
COMMENT ON COLUMN ED5104M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED5104M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED5104M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED5104M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED5104M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED5104M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED5104M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED5104M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED5104M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED5104M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED5104M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED5104M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
