/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED5106T_TBL.sql
-- 物理名：ED5106T_TBL
-- 論理名：ＮＢカセット交換実績テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED5106T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED5106T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,NB_CSSTT_KKN_JSSK_TISH_YM  CHAR(6) NOT NULL --「ＮＢカセット交換実績対象年月」
	,NB_CSSTT_KKN_JSSK_RRK_NO  NUMBER(3,0) DEFAULT '0' NOT NULL --「ＮＢカセット交換実績履歴番号」
	,NB_CSSTT_KKN_JSSK_GY_NO  NUMBER(7,0) DEFAULT '0' NOT NULL --「ＮＢカセット交換実績行番号」
	,NB_CSSTT_KKN_JSSK_SKJ_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＮＢカセット交換実績削除フラグ」
	,NB_CSSTT_KKN_HKK_JGYSH_CD  CHAR(6) --「ＮＢカセット交換報告事業所コード」
	,NB_CST_KKN_HKK_GYMITK_TRHK_CD  CHAR(9) --「ＮＢカセット交換報告業務委託先取引先コード」
	,NB_CST_KN_HK_GYIT_TRHK_BSH_CD  CHAR(4) --「ＮＢカセット交換報告業務委託先取引先部署コード」
	,NB_CSSTT_KKN_RY_TRK_JKY_KBN  CHAR(1) NOT NULL --「ＮＢカセット交換理由登録状況区分」
	,NB_ATM_SOCHI_NO  CHAR(7) --「ＮＢＡＴＭ装置番号」
	,NB_CSSTT_KKN_JSSK_SYR_YMD  DATE --「ＮＢカセット交換実績処理年月日」
	,NB_CASSETTE_KOKAN_JIKOKU_NAIYO  CHAR(8) --「ＮＢカセット交換時刻内容」
	,NB_CASSETTE_KOKAN_KBN  CHAR(1) NOT NULL --「ＮＢカセット交換区分」
	,NB_GENKIN_KANRI_CENTER_CD  CHAR(6) --「ＮＢ現金管理センターコード」
	,NB_GENKIN_KANRI_CENTER_NM  VARCHAR2(40) --「ＮＢ現金管理センター名称」
	,NB_KEISO_CENTER_CD  CHAR(6) --「ＮＢ警送センターコード」
	,NB_KEISO_CENTER_NM  VARCHAR2(40) --「ＮＢ警送センター名称」
	,NB_CASSETTE_KOKAN_TEMPO_NM  VARCHAR2(60) --「ＮＢカセット交換店舗名称」
	,NB_ATM_KISHU_CD  CHAR(2) --「ＮＢＡＴＭ機種コード」
	,NB_ATM_KISHU_NM  VARCHAR2(10) --「ＮＢＡＴＭ機種名称」
	,NB_CASSETTE_KOKAN_RIYU_CD  CHAR(2) --「ＮＢカセット交換理由コード」
	,NB_CSSTT_KKN_RY_SNT_NAIYO  VARCHAR2(200) --「ＮＢカセット交換理由その他内容」
	,NB_CSSTT_KKN_JSSK_SHSH_BIKO  VARCHAR2(200) --「ＮＢカセット交換実績支社備考」
	,NB_CST_KKN_JSSK_KKNN_JK_NAIYO  VARCHAR2(200) --「ＮＢカセット交換実績確認事項内容」
	,NB_CST_KK_JSK_KKN_JK_KIT_NAIYO  VARCHAR2(200) --「ＮＢカセット交換実績確認事項回答内容」
	,NB_CSSTT_KKN_SIKY_KH_KBN  CHAR(1) NOT NULL --「ＮＢカセット交換請求可否区分」
	,NB_CST_KK_JSK_ATM_GYMST_BIKO  VARCHAR2(200) --「ＮＢカセット交換実績ＡＴＭ業務室備考」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED5106T_PK PRIMARY KEY(
	 NB_CSSTT_KKN_JSSK_TISH_YM
	,  NB_CSSTT_KKN_JSSK_RRK_NO
	,  NB_CSSTT_KKN_JSSK_GY_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED5106T_TBL IS 'ＮＢカセット交換実績テーブル'
/

COMMENT ON COLUMN ED5106T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CSSTT_KKN_JSSK_TISH_YM IS 'ＮＢカセット交換実績対象年月'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CSSTT_KKN_JSSK_RRK_NO IS 'ＮＢカセット交換実績履歴番号'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CSSTT_KKN_JSSK_GY_NO IS 'ＮＢカセット交換実績行番号'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CSSTT_KKN_JSSK_SKJ_FLG IS 'ＮＢカセット交換実績削除フラグ'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CSSTT_KKN_HKK_JGYSH_CD IS 'ＮＢカセット交換報告事業所コード'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CST_KKN_HKK_GYMITK_TRHK_CD IS 'ＮＢカセット交換報告業務委託先取引先コード'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CST_KN_HK_GYIT_TRHK_BSH_CD IS 'ＮＢカセット交換報告業務委託先取引先部署コード'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CSSTT_KKN_RY_TRK_JKY_KBN IS 'ＮＢカセット交換理由登録状況区分'
/
COMMENT ON COLUMN ED5106T_TBL.NB_ATM_SOCHI_NO IS 'ＮＢＡＴＭ装置番号'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CSSTT_KKN_JSSK_SYR_YMD IS 'ＮＢカセット交換実績処理年月日'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CASSETTE_KOKAN_JIKOKU_NAIYO IS 'ＮＢカセット交換時刻内容'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CASSETTE_KOKAN_KBN IS 'ＮＢカセット交換区分'
/
COMMENT ON COLUMN ED5106T_TBL.NB_GENKIN_KANRI_CENTER_CD IS 'ＮＢ現金管理センターコード'
/
COMMENT ON COLUMN ED5106T_TBL.NB_GENKIN_KANRI_CENTER_NM IS 'ＮＢ現金管理センター名称'
/
COMMENT ON COLUMN ED5106T_TBL.NB_KEISO_CENTER_CD IS 'ＮＢ警送センターコード'
/
COMMENT ON COLUMN ED5106T_TBL.NB_KEISO_CENTER_NM IS 'ＮＢ警送センター名称'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CASSETTE_KOKAN_TEMPO_NM IS 'ＮＢカセット交換店舗名称'
/
COMMENT ON COLUMN ED5106T_TBL.NB_ATM_KISHU_CD IS 'ＮＢＡＴＭ機種コード'
/
COMMENT ON COLUMN ED5106T_TBL.NB_ATM_KISHU_NM IS 'ＮＢＡＴＭ機種名称'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CASSETTE_KOKAN_RIYU_CD IS 'ＮＢカセット交換理由コード'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CSSTT_KKN_RY_SNT_NAIYO IS 'ＮＢカセット交換理由その他内容'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CSSTT_KKN_JSSK_SHSH_BIKO IS 'ＮＢカセット交換実績支社備考'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CST_KKN_JSSK_KKNN_JK_NAIYO IS 'ＮＢカセット交換実績確認事項内容'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CST_KK_JSK_KKN_JK_KIT_NAIYO IS 'ＮＢカセット交換実績確認事項回答内容'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CSSTT_KKN_SIKY_KH_KBN IS 'ＮＢカセット交換請求可否区分'
/
COMMENT ON COLUMN ED5106T_TBL.NB_CST_KK_JSK_ATM_GYMST_BIKO IS 'ＮＢカセット交換実績ＡＴＭ業務室備考'
/
COMMENT ON COLUMN ED5106T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED5106T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED5106T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED5106T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED5106T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED5106T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED5106T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED5106T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED5106T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED5106T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED5106T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED5106T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
