/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED8632T_TBL.sql
-- 物理名：ED8632T_TBL
-- 論理名：資産元資産情報変更テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED8632T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED8632T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SHISAN_NO  CHAR(12) NOT NULL --「資産番号」
	,SHISAN_BN  CHAR(4) NOT NULL --「資産枝番」
	,KOTEI_SHISAN_SHORI_CD  CHAR(4) NOT NULL --「固定資産処理コード」
	,HASSEIMOTO_GYOMU_KBN  CHAR(3) NOT NULL --「発生元業務区分」
	,HASSEIMOTO_KINO_ID  CHAR(15) NOT NULL --「発生元機能ＩＤ」
	,KEIJO_YMD  DATE NOT NULL --「計上年月日」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,KTI_SHSN_KNR_BMN_SSHK_CD  CHAR(6) NOT NULL --「固定資産管理部門組織コード」
	,SHINKI_SHUTOKU_KAGAKU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「新規取得価額金額」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,KOTEI_SHISAN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「固定資産数量」
	,KOTEI_SHISAN_SHUTOKU_YMD  DATE --「固定資産取得年月日」
	,KOTEI_SHISAN_KADO_YMD  DATE --「固定資産稼動年月日」
	,KOTEI_SHISAN_IDO_YMD  DATE --「固定資産異動年月日」
	,KOTEI_SHISAN_SHOBUN_YMD  DATE --「固定資産処分年月日」
	,KTI_SHSN_SHKYK_TISH_YMD  DATE --「固定資産償却停止年月日」
	,KTI_SHSN_SHKYK_SIKI_YMD  DATE --「固定資産償却再開年月日」
	,GLOVIA_KOTEI_SHISAN_TEKIYO  VARCHAR2(64) --「ＧＬＯＶＩＡ固定資産摘要」
	,SHOHIN_SERVICE_BUNRUI_CD  CHAR(6) NOT NULL --「商品サービス分類コード」
	,JIGYO_SEGMENT_CD  CHAR(3) NOT NULL --「事業セグメントコード」
	,UNYO_COURSE_CD  CHAR(9) --「運用コースコード」
	,AITESAKI_TORIHIKISAKI_CD  CHAR(9) --「相手先取引先コード」
	,TAISHOSAKI_CD  CHAR(9) NOT NULL --「対象先コード」
	,TODOFUKEN_CD  CHAR(2) NOT NULL --「都道府県コード」
	,SHIKUCHOSON_CD  CHAR(3) NOT NULL --「市区町村コード」
	,KOJIHI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「工事費金額」
	,ROMUHI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「労務費金額」
	,SHISAMMOTO_DEMPYO_NO  CHAR(20) NOT NULL --「資産元伝票番号」
	,SHISAMMOTO_DEMPYO_NO_BN  CHAR(20) --「資産元伝票番号枝番」
	,SHSMMT_DMPY_MISIGY_NO  CHAR(20) --「資産元伝票明細行番号」
	,SHSMMT_DMPY_MISIGY_NO_BN  CHAR(20) --「資産元伝票明細行番号枝番」
	,SHISAN_TORIKESHI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「資産取消フラグ」
	,RONRI_SAKUJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「論理削除フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED8632T_PK PRIMARY KEY(
	 SHISAN_NO
	,  KEIJO_YMD
	,  KAISHA_CD
	,  KOTEI_SHISAN_SHORI_CD
	,  SHISAN_BN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED8632T_TBL IS '資産元資産情報変更テーブル'
/

COMMENT ON COLUMN ED8632T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED8632T_TBL.SHISAN_NO IS '資産番号'
/
COMMENT ON COLUMN ED8632T_TBL.SHISAN_BN IS '資産枝番'
/
COMMENT ON COLUMN ED8632T_TBL.KOTEI_SHISAN_SHORI_CD IS '固定資産処理コード'
/
COMMENT ON COLUMN ED8632T_TBL.HASSEIMOTO_GYOMU_KBN IS '発生元業務区分'
/
COMMENT ON COLUMN ED8632T_TBL.HASSEIMOTO_KINO_ID IS '発生元機能ＩＤ'
/
COMMENT ON COLUMN ED8632T_TBL.KEIJO_YMD IS '計上年月日'
/
COMMENT ON COLUMN ED8632T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED8632T_TBL.KTI_SHSN_KNR_BMN_SSHK_CD IS '固定資産管理部門組織コード'
/
COMMENT ON COLUMN ED8632T_TBL.SHINKI_SHUTOKU_KAGAKU_AMT IS '新規取得価額金額'
/
COMMENT ON COLUMN ED8632T_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED8632T_TBL.KOTEI_SHISAN_SURYO IS '固定資産数量'
/
COMMENT ON COLUMN ED8632T_TBL.KOTEI_SHISAN_SHUTOKU_YMD IS '固定資産取得年月日'
/
COMMENT ON COLUMN ED8632T_TBL.KOTEI_SHISAN_KADO_YMD IS '固定資産稼動年月日'
/
COMMENT ON COLUMN ED8632T_TBL.KOTEI_SHISAN_IDO_YMD IS '固定資産異動年月日'
/
COMMENT ON COLUMN ED8632T_TBL.KOTEI_SHISAN_SHOBUN_YMD IS '固定資産処分年月日'
/
COMMENT ON COLUMN ED8632T_TBL.KTI_SHSN_SHKYK_TISH_YMD IS '固定資産償却停止年月日'
/
COMMENT ON COLUMN ED8632T_TBL.KTI_SHSN_SHKYK_SIKI_YMD IS '固定資産償却再開年月日'
/
COMMENT ON COLUMN ED8632T_TBL.GLOVIA_KOTEI_SHISAN_TEKIYO IS 'ＧＬＯＶＩＡ固定資産摘要'
/
COMMENT ON COLUMN ED8632T_TBL.SHOHIN_SERVICE_BUNRUI_CD IS '商品サービス分類コード'
/
COMMENT ON COLUMN ED8632T_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED8632T_TBL.UNYO_COURSE_CD IS '運用コースコード'
/
COMMENT ON COLUMN ED8632T_TBL.AITESAKI_TORIHIKISAKI_CD IS '相手先取引先コード'
/
COMMENT ON COLUMN ED8632T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED8632T_TBL.TODOFUKEN_CD IS '都道府県コード'
/
COMMENT ON COLUMN ED8632T_TBL.SHIKUCHOSON_CD IS '市区町村コード'
/
COMMENT ON COLUMN ED8632T_TBL.KOJIHI_AMT IS '工事費金額'
/
COMMENT ON COLUMN ED8632T_TBL.ROMUHI_AMT IS '労務費金額'
/
COMMENT ON COLUMN ED8632T_TBL.SHISAMMOTO_DEMPYO_NO IS '資産元伝票番号'
/
COMMENT ON COLUMN ED8632T_TBL.SHISAMMOTO_DEMPYO_NO_BN IS '資産元伝票番号枝番'
/
COMMENT ON COLUMN ED8632T_TBL.SHSMMT_DMPY_MISIGY_NO IS '資産元伝票明細行番号'
/
COMMENT ON COLUMN ED8632T_TBL.SHSMMT_DMPY_MISIGY_NO_BN IS '資産元伝票明細行番号枝番'
/
COMMENT ON COLUMN ED8632T_TBL.SHISAN_TORIKESHI_FLG IS '資産取消フラグ'
/
COMMENT ON COLUMN ED8632T_TBL.RONRI_SAKUJO_FLG IS '論理削除フラグ'
/
COMMENT ON COLUMN ED8632T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED8632T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED8632T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED8632T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED8632T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED8632T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED8632T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED8632T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED8632T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED8632T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED8632T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED8632T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
