/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED8707T_TBL.sql
-- 物理名：ED8707T_TBL
-- 論理名：買掛金未払金計上テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED8707T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED8707T_TBL (
	 KIKKKN_MHRIKN_KIJ_SN  CHAR(14) NOT NULL --「買掛金未払金計上連番」
	,KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,EIGYO_KANRI_YM  CHAR(6) NOT NULL --「営業管理年月」
	,SHIWAKE_DEMPYO_NO  CHAR(12) --「仕訳伝票番号」
	,SHIWAKE_DEMPYO_MEISAI_NO  CHAR(8) --「仕訳伝票明細番号」
	,JIGYOSHO_CD  CHAR(6) NOT NULL --「事業所コード」
	,TORIHIKISAKI_CD  CHAR(9) --「取引先コード」
	,TORIHIKISAKI_SHIHARAI_JOHO_CD  CHAR(4) --「取引先支払情報コード」
	,KANJO_KAMOKU_CD  VARCHAR2(12) NOT NULL --「勘定科目コード」
	,KEIRI_GYOMU_KBN  CHAR(3) NOT NULL --「経理業務区分」
	,KEIJO_YMD  DATE NOT NULL --「計上年月日」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,KEIRI_GYOMU_KBN_NM  VARCHAR2(60) --「経理業務区分名称」
	,JIGYOSHO_NM  VARCHAR2(200) --「事業所名称」
	,JIGYOSHO_KETSUGO_NM  VARCHAR2(400) --「事業所結合名称」
	,KANJO_KAMOKU_NM  VARCHAR2(64) --「勘定科目名称」
	,TAISHOSAKI_CD  CHAR(9) --「対象先コード」
	,TAISHOSAKI_NM  VARCHAR2(40) --「対象先名称」
	,TORIHIKISAKI_NM  VARCHAR2(40) --「取引先名称」
	,TORIHIKISAKI_SEISHIKI_NM  VARCHAR2(50) --「取引先正式名称」
	,TORIHIKISAKI_SHIHARAI_JOHO_NM  VARCHAR2(40) --「取引先支払情報名称」
	,KEIJO_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「計上金額」
	,HASSEIMOTO_GYOMU_KBN  CHAR(3) NOT NULL --「発生元業務区分」
	,HASSEIMOTO_KINO_ID  CHAR(15) --「発生元機能ＩＤ」
	,SHIWAKE_SHIKIBETSU_CD  CHAR(8) --「仕訳識別コード」
	,SHIWAKEMOTO_DEMPYO_NO  CHAR(20) --「仕訳元伝票番号」
	,SHIWAKEMOTO_DEMPYO_NO_BN  CHAR(20) --「仕訳元伝票番号枝番」
	,SHWKMT_DMPY_MISIGY_NO  CHAR(20) --「仕訳元伝票明細行番号」
	,SHWKMT_DMPY_MISIGY_NO_BN  CHAR(20) --「仕訳元伝票明細行番号枝番」
	,AKAKURO_KBN  CHAR(1) --「赤黒区分」
	,KAIKEI_SHORI_YMD  DATE --「会計処理年月日」
	,SHIHARAI_SHINSEI_NO  CHAR(12) --「支払申請番号」
	,SHIHARAI_SHINSEI_MEISAI_SN  CHAR(14) --「支払申請明細連番」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,SHIHARAI_YOTEI_YMD  DATE --「支払予定年月日」
	,SHIHARAI_SHINSEI_YMD  DATE --「支払申請年月日」
	,SHIHARAI_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「支払金額」
	,KKK_MBK_ZANDAKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「買掛金未払金残高金額」
	,KKK_MBK_ZNDK_KNGKGY_SHRI_KBN  CHAR(1) --「買掛金未払金残高金額行種類区分」
	,SHIHARAI_STATUS_KBN  CHAR(2) --「支払ステータス区分」
	,JUCHU_KANRI_NO_KBN  CHAR(1) --「受注管理番号区分」
	,JUCHU_KANRI_NO_KBN_NM  VARCHAR2(60) --「受注管理番号区分名称」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED8707T_PK PRIMARY KEY(
	 KIKKKN_MHRIKN_KIJ_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED8707T_TBL IS '買掛金未払金計上テーブル'
/

COMMENT ON COLUMN ED8707T_TBL.KIKKKN_MHRIKN_KIJ_SN IS '買掛金未払金計上連番'
/
COMMENT ON COLUMN ED8707T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED8707T_TBL.EIGYO_KANRI_YM IS '営業管理年月'
/
COMMENT ON COLUMN ED8707T_TBL.SHIWAKE_DEMPYO_NO IS '仕訳伝票番号'
/
COMMENT ON COLUMN ED8707T_TBL.SHIWAKE_DEMPYO_MEISAI_NO IS '仕訳伝票明細番号'
/
COMMENT ON COLUMN ED8707T_TBL.JIGYOSHO_CD IS '事業所コード'
/
COMMENT ON COLUMN ED8707T_TBL.TORIHIKISAKI_CD IS '取引先コード'
/
COMMENT ON COLUMN ED8707T_TBL.TORIHIKISAKI_SHIHARAI_JOHO_CD IS '取引先支払情報コード'
/
COMMENT ON COLUMN ED8707T_TBL.KANJO_KAMOKU_CD IS '勘定科目コード'
/
COMMENT ON COLUMN ED8707T_TBL.KEIRI_GYOMU_KBN IS '経理業務区分'
/
COMMENT ON COLUMN ED8707T_TBL.KEIJO_YMD IS '計上年月日'
/
COMMENT ON COLUMN ED8707T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED8707T_TBL.KEIRI_GYOMU_KBN_NM IS '経理業務区分名称'
/
COMMENT ON COLUMN ED8707T_TBL.JIGYOSHO_NM IS '事業所名称'
/
COMMENT ON COLUMN ED8707T_TBL.JIGYOSHO_KETSUGO_NM IS '事業所結合名称'
/
COMMENT ON COLUMN ED8707T_TBL.KANJO_KAMOKU_NM IS '勘定科目名称'
/
COMMENT ON COLUMN ED8707T_TBL.TAISHOSAKI_CD IS '対象先コード'
/
COMMENT ON COLUMN ED8707T_TBL.TAISHOSAKI_NM IS '対象先名称'
/
COMMENT ON COLUMN ED8707T_TBL.TORIHIKISAKI_NM IS '取引先名称'
/
COMMENT ON COLUMN ED8707T_TBL.TORIHIKISAKI_SEISHIKI_NM IS '取引先正式名称'
/
COMMENT ON COLUMN ED8707T_TBL.TORIHIKISAKI_SHIHARAI_JOHO_NM IS '取引先支払情報名称'
/
COMMENT ON COLUMN ED8707T_TBL.KEIJO_AMT IS '計上金額'
/
COMMENT ON COLUMN ED8707T_TBL.HASSEIMOTO_GYOMU_KBN IS '発生元業務区分'
/
COMMENT ON COLUMN ED8707T_TBL.HASSEIMOTO_KINO_ID IS '発生元機能ＩＤ'
/
COMMENT ON COLUMN ED8707T_TBL.SHIWAKE_SHIKIBETSU_CD IS '仕訳識別コード'
/
COMMENT ON COLUMN ED8707T_TBL.SHIWAKEMOTO_DEMPYO_NO IS '仕訳元伝票番号'
/
COMMENT ON COLUMN ED8707T_TBL.SHIWAKEMOTO_DEMPYO_NO_BN IS '仕訳元伝票番号枝番'
/
COMMENT ON COLUMN ED8707T_TBL.SHWKMT_DMPY_MISIGY_NO IS '仕訳元伝票明細行番号'
/
COMMENT ON COLUMN ED8707T_TBL.SHWKMT_DMPY_MISIGY_NO_BN IS '仕訳元伝票明細行番号枝番'
/
COMMENT ON COLUMN ED8707T_TBL.AKAKURO_KBN IS '赤黒区分'
/
COMMENT ON COLUMN ED8707T_TBL.KAIKEI_SHORI_YMD IS '会計処理年月日'
/
COMMENT ON COLUMN ED8707T_TBL.SHIHARAI_SHINSEI_NO IS '支払申請番号'
/
COMMENT ON COLUMN ED8707T_TBL.SHIHARAI_SHINSEI_MEISAI_SN IS '支払申請明細連番'
/
COMMENT ON COLUMN ED8707T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED8707T_TBL.SHIHARAI_YOTEI_YMD IS '支払予定年月日'
/
COMMENT ON COLUMN ED8707T_TBL.SHIHARAI_SHINSEI_YMD IS '支払申請年月日'
/
COMMENT ON COLUMN ED8707T_TBL.SHIHARAI_AMT IS '支払金額'
/
COMMENT ON COLUMN ED8707T_TBL.KKK_MBK_ZANDAKA_AMT IS '買掛金未払金残高金額'
/
COMMENT ON COLUMN ED8707T_TBL.KKK_MBK_ZNDK_KNGKGY_SHRI_KBN IS '買掛金未払金残高金額行種類区分'
/
COMMENT ON COLUMN ED8707T_TBL.SHIHARAI_STATUS_KBN IS '支払ステータス区分'
/
COMMENT ON COLUMN ED8707T_TBL.JUCHU_KANRI_NO_KBN IS '受注管理番号区分'
/
COMMENT ON COLUMN ED8707T_TBL.JUCHU_KANRI_NO_KBN_NM IS '受注管理番号区分名称'
/
COMMENT ON COLUMN ED8707T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED8707T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED8707T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED8707T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED8707T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED8707T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED8707T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED8707T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED8707T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED8707T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED8707T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED8707T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
