/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED8805W_TBL.sql
-- 物理名：ED8805W_TBL
-- 論理名：建仮明細作成エラーワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED8805W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED8805W_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,ERROR_HASSEI_SN  CHAR(14) NOT NULL --「エラー発生連番」
	,ERROR_CD  CHAR(10) NOT NULL --「エラーコード」
	,ERROR_NAIYO  VARCHAR2(300) NOT NULL --「エラー内容」
	,KENKARI_MEISAI_NO  CHAR(12) NOT NULL --「建仮明細番号」
	,KENKARI_MEISAI_BN  CHAR(4) NOT NULL --「建仮明細枝番」
	,KENKARI_BUKKEN_RIREKI_NO  CHAR(4) NOT NULL --「建仮物件履歴番号」
	,KOTEI_SHISAN_SHORI_CD  CHAR(4) NOT NULL --「固定資産処理コード」
	,HASSEIMOTO_GYOMU_KBN  CHAR(3) NOT NULL --「発生元業務区分」
	,HASSEIMOTO_KINO_ID  CHAR(15) NOT NULL --「発生元機能ＩＤ」
	,KENKARI_ID  CHAR(12) NOT NULL --「建仮ＩＤ」
	,KENKARI_KEIJO_YMD  DATE NOT NULL --「建仮計上年月日」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,KTI_SHSN_KNR_BMN_SSHK_CD  CHAR(6) NOT NULL --「固定資産管理部門組織コード」
	,SHUTOKU_KAGAKU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「取得価額金額」
	,HIMMEI_CD  CHAR(8) --「品名コード」
	,KEIHO_SOCHI_KANRI_NO  CHAR(15) --「警報装置管理番号」
	,KEIHO_SOCHI_KANRI_MEISAI_NO  CHAR(4) --「警報装置管理明細番号」
	,KOTEI_SHISAN_SURYO  NUMBER(9,0) DEFAULT '0' NOT NULL --「固定資産数量」
	,SHIWAKE_PATTERN_HOJO_CD  CHAR(6) NOT NULL --「仕訳パターン補助コード」
	,SHOZAI_JIGYOSHO_CD  CHAR(6) --「所在事業所コード」
	,AITESAKI_TORIHIKISAKI_CD  CHAR(9) --「相手先取引先コード」
	,GLOVIA_KOTEI_SHISAN_TEKIYO  VARCHAR2(64) --「ＧＬＯＶＩＡ固定資産摘要」
	,SHOHIN_SERVICE_BUNRUI_CD  CHAR(6) --「商品サービス分類コード」
	,JIGYO_SEGMENT_CD  CHAR(3) NOT NULL --「事業セグメントコード」
	,UNYO_COURSE_CD  CHAR(9) --「運用コースコード」
	,KENKARIMOTO_DEMPYO_NO  CHAR(20) NOT NULL --「建仮元伝票番号」
	,KENKARIMOTO_DEMPYO_NO_BN  CHAR(20) --「建仮元伝票番号枝番」
	,KNKRMT_DMPY_MISIGY_NO  CHAR(20) --「建仮元伝票明細行番号」
	,KNKRMT_DMPY_MISIGY_NO_BN  CHAR(20) --「建仮元伝票明細行番号枝番」
	,KENKARI_TORIKESHI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「建仮取消フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED8805W_PK PRIMARY KEY(
	 ERROR_HASSEI_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED8805W_TBL IS '建仮明細作成エラーワーク'
/

COMMENT ON COLUMN ED8805W_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED8805W_TBL.ERROR_HASSEI_SN IS 'エラー発生連番'
/
COMMENT ON COLUMN ED8805W_TBL.ERROR_CD IS 'エラーコード'
/
COMMENT ON COLUMN ED8805W_TBL.ERROR_NAIYO IS 'エラー内容'
/
COMMENT ON COLUMN ED8805W_TBL.KENKARI_MEISAI_NO IS '建仮明細番号'
/
COMMENT ON COLUMN ED8805W_TBL.KENKARI_MEISAI_BN IS '建仮明細枝番'
/
COMMENT ON COLUMN ED8805W_TBL.KENKARI_BUKKEN_RIREKI_NO IS '建仮物件履歴番号'
/
COMMENT ON COLUMN ED8805W_TBL.KOTEI_SHISAN_SHORI_CD IS '固定資産処理コード'
/
COMMENT ON COLUMN ED8805W_TBL.HASSEIMOTO_GYOMU_KBN IS '発生元業務区分'
/
COMMENT ON COLUMN ED8805W_TBL.HASSEIMOTO_KINO_ID IS '発生元機能ＩＤ'
/
COMMENT ON COLUMN ED8805W_TBL.KENKARI_ID IS '建仮ＩＤ'
/
COMMENT ON COLUMN ED8805W_TBL.KENKARI_KEIJO_YMD IS '建仮計上年月日'
/
COMMENT ON COLUMN ED8805W_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED8805W_TBL.KTI_SHSN_KNR_BMN_SSHK_CD IS '固定資産管理部門組織コード'
/
COMMENT ON COLUMN ED8805W_TBL.SHUTOKU_KAGAKU_AMT IS '取得価額金額'
/
COMMENT ON COLUMN ED8805W_TBL.HIMMEI_CD IS '品名コード'
/
COMMENT ON COLUMN ED8805W_TBL.KEIHO_SOCHI_KANRI_NO IS '警報装置管理番号'
/
COMMENT ON COLUMN ED8805W_TBL.KEIHO_SOCHI_KANRI_MEISAI_NO IS '警報装置管理明細番号'
/
COMMENT ON COLUMN ED8805W_TBL.KOTEI_SHISAN_SURYO IS '固定資産数量'
/
COMMENT ON COLUMN ED8805W_TBL.SHIWAKE_PATTERN_HOJO_CD IS '仕訳パターン補助コード'
/
COMMENT ON COLUMN ED8805W_TBL.SHOZAI_JIGYOSHO_CD IS '所在事業所コード'
/
COMMENT ON COLUMN ED8805W_TBL.AITESAKI_TORIHIKISAKI_CD IS '相手先取引先コード'
/
COMMENT ON COLUMN ED8805W_TBL.GLOVIA_KOTEI_SHISAN_TEKIYO IS 'ＧＬＯＶＩＡ固定資産摘要'
/
COMMENT ON COLUMN ED8805W_TBL.SHOHIN_SERVICE_BUNRUI_CD IS '商品サービス分類コード'
/
COMMENT ON COLUMN ED8805W_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED8805W_TBL.UNYO_COURSE_CD IS '運用コースコード'
/
COMMENT ON COLUMN ED8805W_TBL.KENKARIMOTO_DEMPYO_NO IS '建仮元伝票番号'
/
COMMENT ON COLUMN ED8805W_TBL.KENKARIMOTO_DEMPYO_NO_BN IS '建仮元伝票番号枝番'
/
COMMENT ON COLUMN ED8805W_TBL.KNKRMT_DMPY_MISIGY_NO IS '建仮元伝票明細行番号'
/
COMMENT ON COLUMN ED8805W_TBL.KNKRMT_DMPY_MISIGY_NO_BN IS '建仮元伝票明細行番号枝番'
/
COMMENT ON COLUMN ED8805W_TBL.KENKARI_TORIKESHI_FLG IS '建仮取消フラグ'
/
COMMENT ON COLUMN ED8805W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED8805W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED8805W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED8805W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED8805W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED8805W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED8805W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED8805W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED8805W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED8805W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED8805W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED8805W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
