/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9035M_TBL.sql
-- 物理名：ED9035M_TBL
-- 論理名：採番マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9035M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9035M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SAIBAN_CD  VARCHAR2(50) NOT NULL --「採番コード」
	,SAIBAN_HOJO_CD_1  VARCHAR2(10) NOT NULL --「採番補助コード１」
	,SAIBAN_HOJO_CD_2  VARCHAR2(10) NOT NULL --「採番補助コード２」
	,SAIBAN_NM  VARCHAR2(60) --「採番名称」
	,SAIBAN_GENZAI_NO  NUMBER(20,0) DEFAULT '0' NOT NULL --「採番現在番号」
	,SAIBAN_KAISHI_NO  NUMBER(20,0) DEFAULT '0' NOT NULL --「採番開始番号」
	,SAIBAN_SHURYO_NO  NUMBER(20,0) DEFAULT '0' NOT NULL --「採番終了番号」
	,SAIBAN_ZOBUN_SEIGYOCHI  NUMBER(9,0) DEFAULT '0' NOT NULL --「採番増分制御値」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9035M_PK PRIMARY KEY(
	 SAIBAN_CD
	,  SAIBAN_HOJO_CD_1
	,  SAIBAN_HOJO_CD_2
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9035M_TBL IS '採番マスタ'
/

COMMENT ON COLUMN ED9035M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED9035M_TBL.SAIBAN_CD IS '採番コード'
/
COMMENT ON COLUMN ED9035M_TBL.SAIBAN_HOJO_CD_1 IS '採番補助コード１'
/
COMMENT ON COLUMN ED9035M_TBL.SAIBAN_HOJO_CD_2 IS '採番補助コード２'
/
COMMENT ON COLUMN ED9035M_TBL.SAIBAN_NM IS '採番名称'
/
COMMENT ON COLUMN ED9035M_TBL.SAIBAN_GENZAI_NO IS '採番現在番号'
/
COMMENT ON COLUMN ED9035M_TBL.SAIBAN_KAISHI_NO IS '採番開始番号'
/
COMMENT ON COLUMN ED9035M_TBL.SAIBAN_SHURYO_NO IS '採番終了番号'
/
COMMENT ON COLUMN ED9035M_TBL.SAIBAN_ZOBUN_SEIGYOCHI IS '採番増分制御値'
/
COMMENT ON COLUMN ED9035M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9035M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9035M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9035M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9035M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9035M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9035M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9035M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9035M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9035M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9035M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9035M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
