/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9063T_TBL.sql
-- 物理名：ED9063T_TBL
-- 論理名：タスク通知テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9063T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9063T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TASK_TSUCHI_NO  CHAR(10) NOT NULL --「タスク通知番号」
	,TASK_TSUCHI_BUNRUI_CD  CHAR(6) NOT NULL --「タスク通知分類コード」
	,TASK_HASSHINSHA_KAISHA_CD  CHAR(5) --「タスク発信者会社コード」
	,TASK_HASSHINSHA_JIGYOSHO_CD  CHAR(6) --「タスク発信者事業所コード」
	,TASK_HASSHINSHA_SHAIN_NO  VARCHAR2(8) --「タスク発信者社員番号」
	,SENISAKI_GAMEN_ID  CHAR(15) --「遷移先画面ＩＤ」
	,KIDO_PARAMETER  CLOB --「起動パラメータ」
	,TASK_HASSHIN_DT  TIMESTAMP --「タスク発信日時」
	,TASK_TSUCHI_STATUS_KBN  CHAR(2) NOT NULL --「タスク通知ステータス区分」
	,TASK_KANRYO_DT  TIMESTAMP --「タスク完了日時」
	,TASK_KANRYOSHA_JIGYOSHO_CD  CHAR(6) --「タスク完了者事業所コード」
	,TASK_KANRYOSHA_SHAIN_NO  VARCHAR2(8) --「タスク完了者社員番号」
	,TASK_TSUCHI_HOSOKU_JOHO_NAIYO  VARCHAR2(200) --「タスク通知補足情報内容」
	,TASK_KANRYO_YMD  DATE --「タスク完了年月日」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9063T_PK PRIMARY KEY(
	 TASK_TSUCHI_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9063T_TBL IS 'タスク通知テーブル'
/

COMMENT ON COLUMN ED9063T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED9063T_TBL.TASK_TSUCHI_NO IS 'タスク通知番号'
/
COMMENT ON COLUMN ED9063T_TBL.TASK_TSUCHI_BUNRUI_CD IS 'タスク通知分類コード'
/
COMMENT ON COLUMN ED9063T_TBL.TASK_HASSHINSHA_KAISHA_CD IS 'タスク発信者会社コード'
/
COMMENT ON COLUMN ED9063T_TBL.TASK_HASSHINSHA_JIGYOSHO_CD IS 'タスク発信者事業所コード'
/
COMMENT ON COLUMN ED9063T_TBL.TASK_HASSHINSHA_SHAIN_NO IS 'タスク発信者社員番号'
/
COMMENT ON COLUMN ED9063T_TBL.SENISAKI_GAMEN_ID IS '遷移先画面ＩＤ'
/
COMMENT ON COLUMN ED9063T_TBL.KIDO_PARAMETER IS '起動パラメータ'
/
COMMENT ON COLUMN ED9063T_TBL.TASK_HASSHIN_DT IS 'タスク発信日時'
/
COMMENT ON COLUMN ED9063T_TBL.TASK_TSUCHI_STATUS_KBN IS 'タスク通知ステータス区分'
/
COMMENT ON COLUMN ED9063T_TBL.TASK_KANRYO_DT IS 'タスク完了日時'
/
COMMENT ON COLUMN ED9063T_TBL.TASK_KANRYOSHA_JIGYOSHO_CD IS 'タスク完了者事業所コード'
/
COMMENT ON COLUMN ED9063T_TBL.TASK_KANRYOSHA_SHAIN_NO IS 'タスク完了者社員番号'
/
COMMENT ON COLUMN ED9063T_TBL.TASK_TSUCHI_HOSOKU_JOHO_NAIYO IS 'タスク通知補足情報内容'
/
COMMENT ON COLUMN ED9063T_TBL.TASK_KANRYO_YMD IS 'タスク完了年月日'
/
COMMENT ON COLUMN ED9063T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9063T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9063T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9063T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9063T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9063T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9063T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9063T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9063T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9063T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9063T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9063T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
