/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9069W_TBL.sql
-- 物理名：ED9069W_TBL
-- 論理名：Ｃｔｒｅｅ親企業ファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9069W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9069W_TBL (
	 TDB_KIGYO_CD  CHAR(9) NOT NULL --「ＴＤＢ企業コード」
	,KESSAN_Y  CHAR(4) NOT NULL --「決算年」
	,KESSAN_M  CHAR(2) NOT NULL --「決算月」
	,SHOKEN_CD  CHAR(4) --「証券コード」
	,TDB_KIGYO_NM  VARCHAR2(127) --「ＴＤＢ企業名称」
	,TDB_KIGYO_HKN_NM  VARCHAR2(255) --「ＴＤＢ企業半角カナ名称」
	,DAIHYOSHA_NM  VARCHAR2(60) --「代表者氏名」
	,TDB_SHOZAICHI_JUSHO  VARCHAR2(255) --「ＴＤＢ所在地住所」
	,DENWA_NO  VARCHAR2(20) --「電話番号」
	,EDINET_JIGYO_NAIYO  VARCHAR2(300) --「ＥＤＩＮＥＴ事業内容」
	,JUGYOIN_NINZU  NUMBER(9,0) DEFAULT '0' NOT NULL --「従業員人数」
	,ZENSHA_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「全社件数」
	,KOGAISHA_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「子会社件数」
	,KANREN_KAISHA_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「関連会社件数」
	,TDBOK_EIGYO_SHUEKI  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＴＤＢ親企業＿営業収益」
	,TDBOK_KEIJO_RIEKI  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＴＤＢ親企業＿経常利益」
	,TDBOK_TOKI_JUNRIEKI  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＴＤＢ親企業＿当期純利益」
	,TDBOK_JUNSHISANGAKU  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＴＤＢ親企業＿純資産額」
	,TDBOK_SOSHISANGAKU  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＴＤＢ親企業＿総資産額」
	,TDBOK_HTKB_ATR_JNSHSNGK  NUMBER(15,2) DEFAULT '0' NOT NULL --「ＴＤＢ親企業＿一株当り純資産額」
	,TDBOK_HTKB_ATR_TK_JNREK  NUMBER(15,2) DEFAULT '0' NOT NULL --「ＴＤＢ親企業＿一株当り当期純利益」
	,TDBOK_RENKETSU_URIAGEDAKA  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＴＤＢ親企業＿連結売上高」
	,TDBOK_RENKETSU_KEIJO_RIEKI  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＴＤＢ親企業＿連結経常利益」
	,TDBOK_RENKETSU_TOKI_JUNRIEKI  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＴＤＢ親企業＿連結当期純利益」
	,TDBOK_RENKETSU_JUNSHISANGAKU  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＴＤＢ親企業＿連結純資産額」
	,TDBOK_RENKETSU_SOSHISANGAKU  NUMBER(13,0) DEFAULT '0' NOT NULL --「ＴＤＢ親企業＿連結総資産額」
	,TDBOK_RNKT_B_HTKB_ATR_JNSHSNGK  NUMBER(15,2) DEFAULT '0' NOT NULL --「ＴＤＢ親企業＿連結ベースの一株当り純資産額」
	,TDBOK_RNKT_B_HTKB_ATR_TK_JNREK  NUMBER(15,2) DEFAULT '0' NOT NULL --「ＴＤＢ親企業＿連結ベースの一株当り当期純利益」
	,TDBOK_KAIKEI_KIJUN_KBN  CHAR(1) --「ＴＤＢ親企業＿会計基準区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9069W_PK PRIMARY KEY(
	 TDB_KIGYO_CD
	,  KESSAN_Y
	,  KESSAN_M
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9069W_TBL IS 'Ｃｔｒｅｅ親企業ファイルワーク'
/

COMMENT ON COLUMN ED9069W_TBL.TDB_KIGYO_CD IS 'ＴＤＢ企業コード'
/
COMMENT ON COLUMN ED9069W_TBL.KESSAN_Y IS '決算年'
/
COMMENT ON COLUMN ED9069W_TBL.KESSAN_M IS '決算月'
/
COMMENT ON COLUMN ED9069W_TBL.SHOKEN_CD IS '証券コード'
/
COMMENT ON COLUMN ED9069W_TBL.TDB_KIGYO_NM IS 'ＴＤＢ企業名称'
/
COMMENT ON COLUMN ED9069W_TBL.TDB_KIGYO_HKN_NM IS 'ＴＤＢ企業半角カナ名称'
/
COMMENT ON COLUMN ED9069W_TBL.DAIHYOSHA_NM IS '代表者氏名'
/
COMMENT ON COLUMN ED9069W_TBL.TDB_SHOZAICHI_JUSHO IS 'ＴＤＢ所在地住所'
/
COMMENT ON COLUMN ED9069W_TBL.DENWA_NO IS '電話番号'
/
COMMENT ON COLUMN ED9069W_TBL.EDINET_JIGYO_NAIYO IS 'ＥＤＩＮＥＴ事業内容'
/
COMMENT ON COLUMN ED9069W_TBL.JUGYOIN_NINZU IS '従業員人数'
/
COMMENT ON COLUMN ED9069W_TBL.ZENSHA_KENSU IS '全社件数'
/
COMMENT ON COLUMN ED9069W_TBL.KOGAISHA_KENSU IS '子会社件数'
/
COMMENT ON COLUMN ED9069W_TBL.KANREN_KAISHA_KENSU IS '関連会社件数'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_EIGYO_SHUEKI IS 'ＴＤＢ親企業＿営業収益'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_KEIJO_RIEKI IS 'ＴＤＢ親企業＿経常利益'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_TOKI_JUNRIEKI IS 'ＴＤＢ親企業＿当期純利益'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_JUNSHISANGAKU IS 'ＴＤＢ親企業＿純資産額'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_SOSHISANGAKU IS 'ＴＤＢ親企業＿総資産額'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_HTKB_ATR_JNSHSNGK IS 'ＴＤＢ親企業＿一株当り純資産額'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_HTKB_ATR_TK_JNREK IS 'ＴＤＢ親企業＿一株当り当期純利益'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_RENKETSU_URIAGEDAKA IS 'ＴＤＢ親企業＿連結売上高'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_RENKETSU_KEIJO_RIEKI IS 'ＴＤＢ親企業＿連結経常利益'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_RENKETSU_TOKI_JUNRIEKI IS 'ＴＤＢ親企業＿連結当期純利益'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_RENKETSU_JUNSHISANGAKU IS 'ＴＤＢ親企業＿連結純資産額'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_RENKETSU_SOSHISANGAKU IS 'ＴＤＢ親企業＿連結総資産額'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_RNKT_B_HTKB_ATR_JNSHSNGK IS 'ＴＤＢ親企業＿連結ベースの一株当り純資産額'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_RNKT_B_HTKB_ATR_TK_JNREK IS 'ＴＤＢ親企業＿連結ベースの一株当り当期純利益'
/
COMMENT ON COLUMN ED9069W_TBL.TDBOK_KAIKEI_KIJUN_KBN IS 'ＴＤＢ親企業＿会計基準区分'
/
COMMENT ON COLUMN ED9069W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9069W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9069W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9069W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9069W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9069W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9069W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9069W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9069W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9069W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9069W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9069W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
