/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9075W_TBL.sql
-- 物理名：ED9075W_TBL
-- 論理名：Ｃｔｒｅｅ子企業ファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9075W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9075W_TBL (
	 TDB_KIGYO_CD  CHAR(9) NOT NULL --「ＴＤＢ企業コード」
	,TDB_KIGYO_NM  VARCHAR2(127) --「ＴＤＢ企業名称」
	,TDB_KIGYO_HKN_NM  VARCHAR2(255) --「ＴＤＢ企業半角カナ名称」
	,TDB_KOGAISHA_KIGYO_CD  CHAR(9) NOT NULL --「ＴＤＢ子会社企業コード」
	,TDB_KOKIGYO_NM  VARCHAR2(127) --「ＴＤＢ子企業名称」
	,TDB_KOKIGYO_HKN_NM  VARCHAR2(255) --「ＴＤＢ子企業半角カナ名称」
	,SHOKEN_CD  CHAR(4) --「証券コード」
	,TDB_OYAKIGYO_KANKEI_KBN  CHAR(1) --「ＴＤＢ親企業関係区分」
	,TDB_SHOZAICHI_JUSHO  VARCHAR2(255) --「ＴＤＢ所在地住所」
	,TDBKK_SHIHONKIN  VARCHAR2(150) --「ＴＤＢ子企業＿資本金」
	,YK_SHKN_HKKSH_KSI_JGY_NAIYO  VARCHAR2(300) --「有価証券報告書記載事業内容」
	,KGISH_GKTSKN_CHKSTS_SHY_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「子会社議決権直接所有率」
	,KGISH_GKTSKN_KNSTS_SHY_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「子会社議決権間接所有率」
	,KGISH_GKTSKN_GKI_SHY_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「子会社議決権合計所有率」
	,YKIN_KNNN_TSH_YKIN_NINZU  NUMBER(9,0) DEFAULT '0' NOT NULL --「役員兼任当社役員人数」
	,YKIN_KNNN_TSH_SHKIN_NINZU  NUMBER(9,0) DEFAULT '0' NOT NULL --「役員兼任当社職員人数」
	,YK_SHKN_HKKSH_TRHK_NAIYO  VARCHAR2(300) --「有価証券報告書取引内容」
	,YK_SHKN_HKKSH_SNT_NAIYO  VARCHAR2(300) --「有価証券報告書その他内容」
	,GAIKOKU_KIGYO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「外国企業フラグ」
	,KABUSHIKI_JOJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「株式上場フラグ」
	,KESSAN_Y  CHAR(4) --「決算年」
	,KESSAN_M  CHAR(2) --「決算月」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9075W_PK PRIMARY KEY(
	 TDB_KIGYO_CD
	,  TDB_KOGAISHA_KIGYO_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9075W_TBL IS 'Ｃｔｒｅｅ子企業ファイルワーク'
/

COMMENT ON COLUMN ED9075W_TBL.TDB_KIGYO_CD IS 'ＴＤＢ企業コード'
/
COMMENT ON COLUMN ED9075W_TBL.TDB_KIGYO_NM IS 'ＴＤＢ企業名称'
/
COMMENT ON COLUMN ED9075W_TBL.TDB_KIGYO_HKN_NM IS 'ＴＤＢ企業半角カナ名称'
/
COMMENT ON COLUMN ED9075W_TBL.TDB_KOGAISHA_KIGYO_CD IS 'ＴＤＢ子会社企業コード'
/
COMMENT ON COLUMN ED9075W_TBL.TDB_KOKIGYO_NM IS 'ＴＤＢ子企業名称'
/
COMMENT ON COLUMN ED9075W_TBL.TDB_KOKIGYO_HKN_NM IS 'ＴＤＢ子企業半角カナ名称'
/
COMMENT ON COLUMN ED9075W_TBL.SHOKEN_CD IS '証券コード'
/
COMMENT ON COLUMN ED9075W_TBL.TDB_OYAKIGYO_KANKEI_KBN IS 'ＴＤＢ親企業関係区分'
/
COMMENT ON COLUMN ED9075W_TBL.TDB_SHOZAICHI_JUSHO IS 'ＴＤＢ所在地住所'
/
COMMENT ON COLUMN ED9075W_TBL.TDBKK_SHIHONKIN IS 'ＴＤＢ子企業＿資本金'
/
COMMENT ON COLUMN ED9075W_TBL.YK_SHKN_HKKSH_KSI_JGY_NAIYO IS '有価証券報告書記載事業内容'
/
COMMENT ON COLUMN ED9075W_TBL.KGISH_GKTSKN_CHKSTS_SHY_RITSU IS '子会社議決権直接所有率'
/
COMMENT ON COLUMN ED9075W_TBL.KGISH_GKTSKN_KNSTS_SHY_RITSU IS '子会社議決権間接所有率'
/
COMMENT ON COLUMN ED9075W_TBL.KGISH_GKTSKN_GKI_SHY_RITSU IS '子会社議決権合計所有率'
/
COMMENT ON COLUMN ED9075W_TBL.YKIN_KNNN_TSH_YKIN_NINZU IS '役員兼任当社役員人数'
/
COMMENT ON COLUMN ED9075W_TBL.YKIN_KNNN_TSH_SHKIN_NINZU IS '役員兼任当社職員人数'
/
COMMENT ON COLUMN ED9075W_TBL.YK_SHKN_HKKSH_TRHK_NAIYO IS '有価証券報告書取引内容'
/
COMMENT ON COLUMN ED9075W_TBL.YK_SHKN_HKKSH_SNT_NAIYO IS '有価証券報告書その他内容'
/
COMMENT ON COLUMN ED9075W_TBL.GAIKOKU_KIGYO_FLG IS '外国企業フラグ'
/
COMMENT ON COLUMN ED9075W_TBL.KABUSHIKI_JOJO_FLG IS '株式上場フラグ'
/
COMMENT ON COLUMN ED9075W_TBL.KESSAN_Y IS '決算年'
/
COMMENT ON COLUMN ED9075W_TBL.KESSAN_M IS '決算月'
/
COMMENT ON COLUMN ED9075W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9075W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9075W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9075W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9075W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9075W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9075W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9075W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9075W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9075W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9075W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9075W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
