/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9062T_TBL.sql
-- 物理名：ED9062T_TBL
-- 論理名：申請承認処理状況テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9062T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9062T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SHINSEI_SHONIN_NO  CHAR(14) NOT NULL --「申請承認番号」
	,SHINSEI_SHONIN_SHORI_JOKYO_SN  NUMBER(3,0) DEFAULT '1' NOT NULL --「申請承認処理状況連番」
	,SHINSEI_SHONIN_ID  CHAR(6) NOT NULL --「申請承認ＩＤ」
	,JOI_JIGYOSHO_CD  CHAR(6) NOT NULL --「上位事業所コード」
	,SHINSEI_SHONIN_ROUTE_SN  NUMBER(3,0) DEFAULT '1' NOT NULL --「申請承認ルート連番」
	,SHINSEI_SHONIN_KAISO_NO  CHAR(2) DEFAULT '1' NOT NULL --「申請承認階層番号」
	,SHINSEI_SHONIN_KAISO_SN  NUMBER(3,0) DEFAULT '1' NOT NULL --「申請承認階層連番」
	,SHINSEI_SHONIN_SHORI_KBN  CHAR(2) NOT NULL --「申請承認処理区分」
	,JISSHISHA_JIGYOSHO_CD  CHAR(6) --「実施者事業所コード」
	,JISSHISHA_SHAIN_NO  VARCHAR2(8) --「実施者社員番号」
	,JISSHI_DT  TIMESTAMP --「実施日時」
	,KAISOSAKI_SHITEI_KBN  CHAR(1) --「回送先指定区分」
	,KAISOSAKI_JIGYOSHO_CD  CHAR(6) --「回送先事業所コード」
	,KAISOSAKI_YAKUSHOKU_CD  VARCHAR2(4) --「回送先役職コード」
	,KAISOSAKI_SHOKUMU_CD  VARCHAR2(4) --「回送先職務コード」
	,KAISOSAKI_SHAIN_NO  VARCHAR2(8) --「回送先社員番号」
	,KAISOSAKI_SENTAKU_SOSA_KBN  CHAR(2) --「回送先選択操作区分」
	,SHINSEI_SHONIN_CMNT  VARCHAR2(200) --「申請承認コメント」
	,SHINSEI_SHONIN_SETTEI_KBN  CHAR(2) NOT NULL --「申請承認設定区分」
	,GENZAI_ICHI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「現在位置フラグ」
	,SAISHU_SHONIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「最終承認フラグ」
	,SHONIN_KENGEN_KBN  CHAR(2) NOT NULL --「承認権限区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9062T_PK PRIMARY KEY(
	 SHINSEI_SHONIN_NO
	,  KAISHA_CD
	,  SHINSEI_SHONIN_SHORI_JOKYO_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9062T_TBL IS '申請承認処理状況テーブル'
/

COMMENT ON COLUMN ED9062T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED9062T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED9062T_TBL.SHINSEI_SHONIN_SHORI_JOKYO_SN IS '申請承認処理状況連番'
/
COMMENT ON COLUMN ED9062T_TBL.SHINSEI_SHONIN_ID IS '申請承認ＩＤ'
/
COMMENT ON COLUMN ED9062T_TBL.JOI_JIGYOSHO_CD IS '上位事業所コード'
/
COMMENT ON COLUMN ED9062T_TBL.SHINSEI_SHONIN_ROUTE_SN IS '申請承認ルート連番'
/
COMMENT ON COLUMN ED9062T_TBL.SHINSEI_SHONIN_KAISO_NO IS '申請承認階層番号'
/
COMMENT ON COLUMN ED9062T_TBL.SHINSEI_SHONIN_KAISO_SN IS '申請承認階層連番'
/
COMMENT ON COLUMN ED9062T_TBL.SHINSEI_SHONIN_SHORI_KBN IS '申請承認処理区分'
/
COMMENT ON COLUMN ED9062T_TBL.JISSHISHA_JIGYOSHO_CD IS '実施者事業所コード'
/
COMMENT ON COLUMN ED9062T_TBL.JISSHISHA_SHAIN_NO IS '実施者社員番号'
/
COMMENT ON COLUMN ED9062T_TBL.JISSHI_DT IS '実施日時'
/
COMMENT ON COLUMN ED9062T_TBL.KAISOSAKI_SHITEI_KBN IS '回送先指定区分'
/
COMMENT ON COLUMN ED9062T_TBL.KAISOSAKI_JIGYOSHO_CD IS '回送先事業所コード'
/
COMMENT ON COLUMN ED9062T_TBL.KAISOSAKI_YAKUSHOKU_CD IS '回送先役職コード'
/
COMMENT ON COLUMN ED9062T_TBL.KAISOSAKI_SHOKUMU_CD IS '回送先職務コード'
/
COMMENT ON COLUMN ED9062T_TBL.KAISOSAKI_SHAIN_NO IS '回送先社員番号'
/
COMMENT ON COLUMN ED9062T_TBL.KAISOSAKI_SENTAKU_SOSA_KBN IS '回送先選択操作区分'
/
COMMENT ON COLUMN ED9062T_TBL.SHINSEI_SHONIN_CMNT IS '申請承認コメント'
/
COMMENT ON COLUMN ED9062T_TBL.SHINSEI_SHONIN_SETTEI_KBN IS '申請承認設定区分'
/
COMMENT ON COLUMN ED9062T_TBL.GENZAI_ICHI_FLG IS '現在位置フラグ'
/
COMMENT ON COLUMN ED9062T_TBL.SAISHU_SHONIN_FLG IS '最終承認フラグ'
/
COMMENT ON COLUMN ED9062T_TBL.SHONIN_KENGEN_KBN IS '承認権限区分'
/
COMMENT ON COLUMN ED9062T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9062T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9062T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9062T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9062T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9062T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9062T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9062T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9062T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9062T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9062T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9062T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
