/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9023M_TBL.sql
-- 物理名：ED9023M_TBL
-- 論理名：業種分類マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9023M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9023M_TBL (
	 GYOSHU_DAIBUNRUI_CD  CHAR(2) NOT NULL --「業種大分類コード」
	,GYOSHU_CHUBUNRUI_CD  CHAR(2) NOT NULL --「業種中分類コード」
	,EIGY_KNR_GYSH_BNRI_HYJ_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「営業管理業種分類表示順」
	,GYOSHU_BUNRUI_NM  VARCHAR2(60) --「業種分類名称」
	,SHIYO_FUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「使用不可フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9023M_PK PRIMARY KEY(
	 GYOSHU_DAIBUNRUI_CD
	,  GYOSHU_CHUBUNRUI_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9023M_TBL IS '業種分類マスタ'
/

COMMENT ON COLUMN ED9023M_TBL.GYOSHU_DAIBUNRUI_CD IS '業種大分類コード'
/
COMMENT ON COLUMN ED9023M_TBL.GYOSHU_CHUBUNRUI_CD IS '業種中分類コード'
/
COMMENT ON COLUMN ED9023M_TBL.EIGY_KNR_GYSH_BNRI_HYJ_JUN IS '営業管理業種分類表示順'
/
COMMENT ON COLUMN ED9023M_TBL.GYOSHU_BUNRUI_NM IS '業種分類名称'
/
COMMENT ON COLUMN ED9023M_TBL.SHIYO_FUKA_FLG IS '使用不可フラグ'
/
COMMENT ON COLUMN ED9023M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9023M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9023M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9023M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9023M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9023M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9023M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9023M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9023M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9023M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9023M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9023M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
