/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9047M_TBL.sql
-- 物理名：ED9047M_TBL
-- 論理名：ロールマスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9047M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9047M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,ROLE_ID  CHAR(6) NOT NULL --「ロールＩＤ」
	,ROLE_NM  VARCHAR2(60) NOT NULL --「ロール名称」
	,GYOMU_KBN_CD  CHAR(3) NOT NULL --「業務区分コード」
	,GYOMU_KINO_CD  CHAR(4) NOT NULL --「業務機能コード」
	,ROLE_SEIGYO_KBN  CHAR(1) NOT NULL --「ロール制御区分」
	,ROLE_BUNRUI_KBN  CHAR(1) NOT NULL --「ロール分類区分」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9047M_PK PRIMARY KEY(
	 ROLE_ID
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9047M_TBL IS 'ロールマスタ'
/

COMMENT ON COLUMN ED9047M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED9047M_TBL.ROLE_ID IS 'ロールＩＤ'
/
COMMENT ON COLUMN ED9047M_TBL.ROLE_NM IS 'ロール名称'
/
COMMENT ON COLUMN ED9047M_TBL.GYOMU_KBN_CD IS '業務区分コード'
/
COMMENT ON COLUMN ED9047M_TBL.GYOMU_KINO_CD IS '業務機能コード'
/
COMMENT ON COLUMN ED9047M_TBL.ROLE_SEIGYO_KBN IS 'ロール制御区分'
/
COMMENT ON COLUMN ED9047M_TBL.ROLE_BUNRUI_KBN IS 'ロール分類区分'
/
COMMENT ON COLUMN ED9047M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9047M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9047M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9047M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9047M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9047M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9047M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9047M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9047M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9047M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9047M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9047M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
