/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9076T_TBL.sql
-- 物理名：ED9076T_TBL
-- 論理名：取引先差分保管テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9076T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9076T_TBL (
	 TORIHIKISAKI_CD  CHAR(9) NOT NULL --「取引先コード」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,TRHKSK_MASTER_KTTS_KBN  CHAR(2) NOT NULL --「取引先マスタ更新対象区分」
	,TRHKSK_MASTER_KTTS_KOMOKU_NM  VARCHAR2(30) --「取引先マスタ更新対象項目名称」
	,TRHKSK_MASTER_KSHMMECH_KOMOKU  VARCHAR2(200) --「取引先マスタ更新前値項目」
	,TRHKSK_MASTER_KSHNGCH_KOMOKU  VARCHAR2(200) --「取引先マスタ更新後値項目」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9076T_PK PRIMARY KEY(
	 TORIHIKISAKI_CD
	,  TRHKSK_MASTER_KTTS_KBN
	,  TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9076T_TBL IS '取引先差分保管テーブル'
/

COMMENT ON COLUMN ED9076T_TBL.TORIHIKISAKI_CD IS '取引先コード'
/
COMMENT ON COLUMN ED9076T_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED9076T_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED9076T_TBL.TRHKSK_MASTER_KTTS_KBN IS '取引先マスタ更新対象区分'
/
COMMENT ON COLUMN ED9076T_TBL.TRHKSK_MASTER_KTTS_KOMOKU_NM IS '取引先マスタ更新対象項目名称'
/
COMMENT ON COLUMN ED9076T_TBL.TRHKSK_MASTER_KSHMMECH_KOMOKU IS '取引先マスタ更新前値項目'
/
COMMENT ON COLUMN ED9076T_TBL.TRHKSK_MASTER_KSHNGCH_KOMOKU IS '取引先マスタ更新後値項目'
/
COMMENT ON COLUMN ED9076T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9076T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9076T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9076T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9076T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9076T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9076T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9076T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9076T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9076T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9076T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9076T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
