/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9136T_TBL.sql
-- 物理名：ED9136T_TBL
-- 論理名：申請用取引先支払情報添付ファイル管理テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9136T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9136T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TORIHIKISAKI_CD  CHAR(9) NOT NULL --「取引先コード」
	,TORIHIKISAKI_SHIHARAI_JOHO_CD  CHAR(4) NOT NULL --「取引先支払情報コード」
	,TEMPU_SHIRYO_FILE_SN  CHAR(14) NOT NULL --「添付資料ファイル連番」
	,TEMPU_SHIRYO_FILE_NM  VARCHAR2(255) NOT NULL --「添付資料ファイル名称」
	,FILE_SHIKIBETSU_KEY  VARCHAR2(255) NOT NULL --「ファイル識別キー」
	,SHIHARAI_SHINSEISHA_SHAIN_NO  VARCHAR2(8) NOT NULL --「支払申請者社員番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9136T_PK PRIMARY KEY(
	 TORIHIKISAKI_CD
	,  TORIHIKISAKI_SHIHARAI_JOHO_CD
	,  TEMPU_SHIRYO_FILE_SN
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9136T_TBL IS '申請用取引先支払情報添付ファイル管理テーブル'
/

COMMENT ON COLUMN ED9136T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED9136T_TBL.TORIHIKISAKI_CD IS '取引先コード'
/
COMMENT ON COLUMN ED9136T_TBL.TORIHIKISAKI_SHIHARAI_JOHO_CD IS '取引先支払情報コード'
/
COMMENT ON COLUMN ED9136T_TBL.TEMPU_SHIRYO_FILE_SN IS '添付資料ファイル連番'
/
COMMENT ON COLUMN ED9136T_TBL.TEMPU_SHIRYO_FILE_NM IS '添付資料ファイル名称'
/
COMMENT ON COLUMN ED9136T_TBL.FILE_SHIKIBETSU_KEY IS 'ファイル識別キー'
/
COMMENT ON COLUMN ED9136T_TBL.SHIHARAI_SHINSEISHA_SHAIN_NO IS '支払申請者社員番号'
/
COMMENT ON COLUMN ED9136T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9136T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9136T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9136T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9136T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9136T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9136T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9136T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9136T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9136T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9136T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9136T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
