/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9159W_TBL.sql
-- 物理名：ED9159W_TBL
-- 論理名：警備系＿営業送信＿組織ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9159W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9159W_TBL (
	 KBK_KAISHA_CD  CHAR(5) NOT NULL --「ＫＢＫ＿会社コード」
	,KBK_SOSHIKI_CD  VARCHAR2(6) NOT NULL --「ＫＢＫ＿組織コード」
	,KBK_TEKIYO_KAISHI_YMD  CHAR(8) NOT NULL --「ＫＢＫ＿適用開始年月日」
	,KBK_TEKIYO_SHURYO_YMD  CHAR(8) NOT NULL --「ＫＢＫ＿適用終了年月日」
	,KBK_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿組織名称」
	,KBK_SOSHIKI_RNM  VARCHAR2(200) --「ＫＢＫ＿組織略称」
	,KBK_JOI_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿上位組織コード」
	,KBK_SHISHABU_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿支社部組織コード」
	,KBK_HIFMT_TIS_HNS_BMN_SSK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＫＢＫ＿共通費配賦元対象本社部門組織フラグ」
	,KBK_HIFSK_TIS_ZNS_SEGMENT_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＫＢＫ＿共通費配賦先対象全社セグメントフラグ」
	,KBK_KNKY_KIHTS_BMN_SSHK_KBN  CHAR(1) NOT NULL --「ＫＢＫ＿研究開発部門組織区分」
	,KBK_HY_FTN_BMN_SSHK_CD  VARCHAR2(6) --「ＫＢＫ＿費用負担部門組織コード」
	,KBK_ICHJ_SHNN_BMN_SSHK_CD  VARCHAR2(6) --「ＫＢＫ＿経費一次承認部門組織コード」
	,KBK_SHISHA_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿支社組織コード」
	,KBK_CHIIKI_HOMBU_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿地域本部組織コード」
	,KBK_JIGYO_HOMBU_SANSHOKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＫＢＫ＿事業本部参照可フラグ」
	,KBK_ZENSHA_SANSHOKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ＫＢＫ＿全社参照可フラグ」
	,KBK_KIR_KNR_SHSHB_SSHK_CD  VARCHAR2(6) --「ＫＢＫ＿経理管理支社部組織コード」
	,KBK_SOSHIKI_RANK_NO  NUMBER(2,0) DEFAULT '0' NOT NULL --「ＫＢＫ＿組織ランク番号」
	,KBK_RANK_01_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク０１組織コード」
	,KBK_RANK_02_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク０２組織コード」
	,KBK_RANK_03_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク０３組織コード」
	,KBK_RANK_04_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク０４組織コード」
	,KBK_RANK_05_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク０５組織コード」
	,KBK_RANK_06_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク０６組織コード」
	,KBK_RANK_07_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク０７組織コード」
	,KBK_RANK_08_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク０８組織コード」
	,KBK_RANK_09_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク０９組織コード」
	,KBK_RANK_10_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク１０組織コード」
	,KBK_RANK_11_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク１１組織コード」
	,KBK_RANK_12_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク１２組織コード」
	,KBK_RANK_13_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク１３組織コード」
	,KBK_RANK_14_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク１４組織コード」
	,KBK_RANK_15_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク１５組織コード」
	,KBK_RANK_16_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク１６組織コード」
	,KBK_RANK_17_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク１７組織コード」
	,KBK_RANK_18_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク１８組織コード」
	,KBK_RANK_19_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク１９組織コード」
	,KBK_RANK_20_SOSHIKI_CD  VARCHAR2(6) --「ＫＢＫ＿ランク２０組織コード」
	,KBK_RANK_01_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク０１組織名称」
	,KBK_RANK_02_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク０２組織名称」
	,KBK_RANK_03_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク０３組織名称」
	,KBK_RANK_04_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク０４組織名称」
	,KBK_RANK_05_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク０５組織名称」
	,KBK_RANK_06_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク０６組織名称」
	,KBK_RANK_07_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク０７組織名称」
	,KBK_RANK_08_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク０８組織名称」
	,KBK_RANK_09_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク０９組織名称」
	,KBK_RANK_10_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク１０組織名称」
	,KBK_RANK_11_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク１１組織名称」
	,KBK_RANK_12_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク１２組織名称」
	,KBK_RANK_13_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク１３組織名称」
	,KBK_RANK_14_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク１４組織名称」
	,KBK_RANK_15_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク１５組織名称」
	,KBK_RANK_16_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク１６組織名称」
	,KBK_RANK_17_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク１７組織名称」
	,KBK_RANK_18_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク１８組織名称」
	,KBK_RANK_19_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク１９組織名称」
	,KBK_RANK_20_SOSHIKI_NM  VARCHAR2(200) --「ＫＢＫ＿ランク２０組織名称」
	,KBK_YOBI_KOMOKU_01  VARCHAR2(255) --「ＫＢＫ＿予備項目０１」
	,KBK_YOBI_KOMOKU_02  VARCHAR2(255) --「ＫＢＫ＿予備項目０２」
	,KBK_YOBI_KOMOKU_03  VARCHAR2(255) --「ＫＢＫ＿予備項目０３」
	,KBK_YOBI_KOMOKU_04  VARCHAR2(255) --「ＫＢＫ＿予備項目０４」
	,KBK_YOBI_KOMOKU_05  VARCHAR2(255) --「ＫＢＫ＿予備項目０５」
	,KBK_YOBI_KOMOKU_06  VARCHAR2(255) --「ＫＢＫ＿予備項目０６」
	,KBK_YOBI_KOMOKU_07  VARCHAR2(255) --「ＫＢＫ＿予備項目０７」
	,KBK_YOBI_KOMOKU_08  VARCHAR2(255) --「ＫＢＫ＿予備項目０８」
	,KBK_YOBI_KOMOKU_09  VARCHAR2(255) --「ＫＢＫ＿予備項目０９」
	,KBK_YOBI_KOMOKU_10  VARCHAR2(255) --「ＫＢＫ＿予備項目１０」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9159W_PK PRIMARY KEY(
	 KBK_SOSHIKI_CD
	,  KBK_KAISHA_CD
	,  KBK_TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9159W_TBL IS '警備系＿営業送信＿組織ワーク'
/

COMMENT ON COLUMN ED9159W_TBL.KBK_KAISHA_CD IS 'ＫＢＫ＿会社コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_SOSHIKI_CD IS 'ＫＢＫ＿組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_TEKIYO_KAISHI_YMD IS 'ＫＢＫ＿適用開始年月日'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_TEKIYO_SHURYO_YMD IS 'ＫＢＫ＿適用終了年月日'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_SOSHIKI_NM IS 'ＫＢＫ＿組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_SOSHIKI_RNM IS 'ＫＢＫ＿組織略称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_JOI_SOSHIKI_CD IS 'ＫＢＫ＿上位組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_SHISHABU_SOSHIKI_CD IS 'ＫＢＫ＿支社部組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_HIFMT_TIS_HNS_BMN_SSK_FLG IS 'ＫＢＫ＿共通費配賦元対象本社部門組織フラグ'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_HIFSK_TIS_ZNS_SEGMENT_FLG IS 'ＫＢＫ＿共通費配賦先対象全社セグメントフラグ'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_KNKY_KIHTS_BMN_SSHK_KBN IS 'ＫＢＫ＿研究開発部門組織区分'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_HY_FTN_BMN_SSHK_CD IS 'ＫＢＫ＿費用負担部門組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_ICHJ_SHNN_BMN_SSHK_CD IS 'ＫＢＫ＿経費一次承認部門組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_SHISHA_SOSHIKI_CD IS 'ＫＢＫ＿支社組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_CHIIKI_HOMBU_SOSHIKI_CD IS 'ＫＢＫ＿地域本部組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_JIGYO_HOMBU_SANSHOKA_FLG IS 'ＫＢＫ＿事業本部参照可フラグ'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_ZENSHA_SANSHOKA_FLG IS 'ＫＢＫ＿全社参照可フラグ'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_KIR_KNR_SHSHB_SSHK_CD IS 'ＫＢＫ＿経理管理支社部組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_SOSHIKI_RANK_NO IS 'ＫＢＫ＿組織ランク番号'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_01_SOSHIKI_CD IS 'ＫＢＫ＿ランク０１組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_02_SOSHIKI_CD IS 'ＫＢＫ＿ランク０２組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_03_SOSHIKI_CD IS 'ＫＢＫ＿ランク０３組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_04_SOSHIKI_CD IS 'ＫＢＫ＿ランク０４組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_05_SOSHIKI_CD IS 'ＫＢＫ＿ランク０５組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_06_SOSHIKI_CD IS 'ＫＢＫ＿ランク０６組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_07_SOSHIKI_CD IS 'ＫＢＫ＿ランク０７組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_08_SOSHIKI_CD IS 'ＫＢＫ＿ランク０８組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_09_SOSHIKI_CD IS 'ＫＢＫ＿ランク０９組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_10_SOSHIKI_CD IS 'ＫＢＫ＿ランク１０組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_11_SOSHIKI_CD IS 'ＫＢＫ＿ランク１１組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_12_SOSHIKI_CD IS 'ＫＢＫ＿ランク１２組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_13_SOSHIKI_CD IS 'ＫＢＫ＿ランク１３組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_14_SOSHIKI_CD IS 'ＫＢＫ＿ランク１４組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_15_SOSHIKI_CD IS 'ＫＢＫ＿ランク１５組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_16_SOSHIKI_CD IS 'ＫＢＫ＿ランク１６組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_17_SOSHIKI_CD IS 'ＫＢＫ＿ランク１７組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_18_SOSHIKI_CD IS 'ＫＢＫ＿ランク１８組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_19_SOSHIKI_CD IS 'ＫＢＫ＿ランク１９組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_20_SOSHIKI_CD IS 'ＫＢＫ＿ランク２０組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_01_SOSHIKI_NM IS 'ＫＢＫ＿ランク０１組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_02_SOSHIKI_NM IS 'ＫＢＫ＿ランク０２組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_03_SOSHIKI_NM IS 'ＫＢＫ＿ランク０３組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_04_SOSHIKI_NM IS 'ＫＢＫ＿ランク０４組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_05_SOSHIKI_NM IS 'ＫＢＫ＿ランク０５組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_06_SOSHIKI_NM IS 'ＫＢＫ＿ランク０６組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_07_SOSHIKI_NM IS 'ＫＢＫ＿ランク０７組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_08_SOSHIKI_NM IS 'ＫＢＫ＿ランク０８組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_09_SOSHIKI_NM IS 'ＫＢＫ＿ランク０９組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_10_SOSHIKI_NM IS 'ＫＢＫ＿ランク１０組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_11_SOSHIKI_NM IS 'ＫＢＫ＿ランク１１組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_12_SOSHIKI_NM IS 'ＫＢＫ＿ランク１２組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_13_SOSHIKI_NM IS 'ＫＢＫ＿ランク１３組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_14_SOSHIKI_NM IS 'ＫＢＫ＿ランク１４組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_15_SOSHIKI_NM IS 'ＫＢＫ＿ランク１５組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_16_SOSHIKI_NM IS 'ＫＢＫ＿ランク１６組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_17_SOSHIKI_NM IS 'ＫＢＫ＿ランク１７組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_18_SOSHIKI_NM IS 'ＫＢＫ＿ランク１８組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_19_SOSHIKI_NM IS 'ＫＢＫ＿ランク１９組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_RANK_20_SOSHIKI_NM IS 'ＫＢＫ＿ランク２０組織名称'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_YOBI_KOMOKU_01 IS 'ＫＢＫ＿予備項目０１'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_YOBI_KOMOKU_02 IS 'ＫＢＫ＿予備項目０２'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_YOBI_KOMOKU_03 IS 'ＫＢＫ＿予備項目０３'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_YOBI_KOMOKU_04 IS 'ＫＢＫ＿予備項目０４'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_YOBI_KOMOKU_05 IS 'ＫＢＫ＿予備項目０５'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_YOBI_KOMOKU_06 IS 'ＫＢＫ＿予備項目０６'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_YOBI_KOMOKU_07 IS 'ＫＢＫ＿予備項目０７'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_YOBI_KOMOKU_08 IS 'ＫＢＫ＿予備項目０８'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_YOBI_KOMOKU_09 IS 'ＫＢＫ＿予備項目０９'
/
COMMENT ON COLUMN ED9159W_TBL.KBK_YOBI_KOMOKU_10 IS 'ＫＢＫ＿予備項目１０'
/
COMMENT ON COLUMN ED9159W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9159W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9159W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9159W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9159W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9159W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9159W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9159W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9159W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9159W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9159W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
