/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9134W_TBL.sql
-- 物理名：ED9134W_TBL
-- 論理名：取引先部署マスタ検索結果ＣＳＶファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9134W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9134W_TBL (
	 TRHKSK_BSH_M_KSKK_IKTS_TKY_SN  NUMBER(14,0) DEFAULT '0' NOT NULL --「取引先部署マスタ検索結果一括取込用連番」
	,RECORD_SOSA_KBN  CHAR(1) NOT NULL --「レコード操作区分」
	,TORIHIKISAKI_CD  CHAR(9) NOT NULL --「取引先コード」
	,TORIHIKISAKI_BUSHO_CD  CHAR(4) --「取引先部署コード」
	,TEKIYO_KAISHI_YMD  DATE NOT NULL --「適用開始年月日」
	,TEKIYO_SHURYO_YMD  DATE NOT NULL --「適用終了年月日」
	,TORIHIKISAKI_BUSHO_NM  VARCHAR2(40) --「取引先部署名称」
	,TORIHIKISAKI_BUSHO_KN_NM  VARCHAR2(40) --「取引先部署カナ名称」
	,JUSHO_CD  CHAR(11) --「住所コード」
	,YUBIN_NO  CHAR(7) --「郵便番号」
	,HOSOKU_JUSHO  VARCHAR2(60) --「補足住所」
	,JUSHO_BANCHI  VARCHAR2(50) --「住所番地」
	,TATEMONO_NM  VARCHAR2(50) --「建物名称」
	,TATEMONO_KN_NM  VARCHAR2(50) --「建物カナ名称」
	,TO_NM  VARCHAR2(50) --「棟名称」
	,KAI_NM  VARCHAR2(50) --「階名称」
	,KUKAKU_NM  VARCHAR2(50) --「区画名称」
	,HEYA_NM  VARCHAR2(50) --「部屋名称」
	,DENWA_NO  VARCHAR2(20) --「電話番号」
	,FAX_NO  VARCHAR2(20) --「ＦＡＸ番号」
	,MAIL_ADDRESS_1  VARCHAR2(200) --「メールアドレス１」
	,MAIL_ADDRESS_2  VARCHAR2(200) --「メールアドレス２」
	,MAIL_ADDRESS_3  VARCHAR2(200) --「メールアドレス３」
	,TANTO_KAISHA_CD  CHAR(5) --「担当会社コード」
	,TANTO_JIGYOSHO_CD  CHAR(6) --「担当事業所コード」
	,TANTO_SHAIN_NO  VARCHAR2(8) --「担当社員番号」
	,JIGYOSHO_CD  CHAR(6) --「事業所コード」
	,IKKATSU_TORIKOMIYO_TS  TIMESTAMP --「一括取込用タイムスタンプ」
	,IKKATSU_TORIKOMIYO_KAISHA_CD  CHAR(5) --「一括取込用会社コード」
	,IKKATSU_TORIKOMIYO_SOSHIKI_CD  VARCHAR2(6) --「一括取込用組織コード」
	,IKKATSU_TORIKOMIYO_SHAIN_NO  VARCHAR2(8) --「一括取込用社員番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9134W_PK PRIMARY KEY(
	 TRHKSK_BSH_M_KSKK_IKTS_TKY_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9134W_TBL IS '取引先部署マスタ検索結果ＣＳＶファイルワーク'
/

COMMENT ON COLUMN ED9134W_TBL.TRHKSK_BSH_M_KSKK_IKTS_TKY_SN IS '取引先部署マスタ検索結果一括取込用連番'
/
COMMENT ON COLUMN ED9134W_TBL.RECORD_SOSA_KBN IS 'レコード操作区分'
/
COMMENT ON COLUMN ED9134W_TBL.TORIHIKISAKI_CD IS '取引先コード'
/
COMMENT ON COLUMN ED9134W_TBL.TORIHIKISAKI_BUSHO_CD IS '取引先部署コード'
/
COMMENT ON COLUMN ED9134W_TBL.TEKIYO_KAISHI_YMD IS '適用開始年月日'
/
COMMENT ON COLUMN ED9134W_TBL.TEKIYO_SHURYO_YMD IS '適用終了年月日'
/
COMMENT ON COLUMN ED9134W_TBL.TORIHIKISAKI_BUSHO_NM IS '取引先部署名称'
/
COMMENT ON COLUMN ED9134W_TBL.TORIHIKISAKI_BUSHO_KN_NM IS '取引先部署カナ名称'
/
COMMENT ON COLUMN ED9134W_TBL.JUSHO_CD IS '住所コード'
/
COMMENT ON COLUMN ED9134W_TBL.YUBIN_NO IS '郵便番号'
/
COMMENT ON COLUMN ED9134W_TBL.HOSOKU_JUSHO IS '補足住所'
/
COMMENT ON COLUMN ED9134W_TBL.JUSHO_BANCHI IS '住所番地'
/
COMMENT ON COLUMN ED9134W_TBL.TATEMONO_NM IS '建物名称'
/
COMMENT ON COLUMN ED9134W_TBL.TATEMONO_KN_NM IS '建物カナ名称'
/
COMMENT ON COLUMN ED9134W_TBL.TO_NM IS '棟名称'
/
COMMENT ON COLUMN ED9134W_TBL.KAI_NM IS '階名称'
/
COMMENT ON COLUMN ED9134W_TBL.KUKAKU_NM IS '区画名称'
/
COMMENT ON COLUMN ED9134W_TBL.HEYA_NM IS '部屋名称'
/
COMMENT ON COLUMN ED9134W_TBL.DENWA_NO IS '電話番号'
/
COMMENT ON COLUMN ED9134W_TBL.FAX_NO IS 'ＦＡＸ番号'
/
COMMENT ON COLUMN ED9134W_TBL.MAIL_ADDRESS_1 IS 'メールアドレス１'
/
COMMENT ON COLUMN ED9134W_TBL.MAIL_ADDRESS_2 IS 'メールアドレス２'
/
COMMENT ON COLUMN ED9134W_TBL.MAIL_ADDRESS_3 IS 'メールアドレス３'
/
COMMENT ON COLUMN ED9134W_TBL.TANTO_KAISHA_CD IS '担当会社コード'
/
COMMENT ON COLUMN ED9134W_TBL.TANTO_JIGYOSHO_CD IS '担当事業所コード'
/
COMMENT ON COLUMN ED9134W_TBL.TANTO_SHAIN_NO IS '担当社員番号'
/
COMMENT ON COLUMN ED9134W_TBL.JIGYOSHO_CD IS '事業所コード'
/
COMMENT ON COLUMN ED9134W_TBL.IKKATSU_TORIKOMIYO_TS IS '一括取込用タイムスタンプ'
/
COMMENT ON COLUMN ED9134W_TBL.IKKATSU_TORIKOMIYO_KAISHA_CD IS '一括取込用会社コード'
/
COMMENT ON COLUMN ED9134W_TBL.IKKATSU_TORIKOMIYO_SOSHIKI_CD IS '一括取込用組織コード'
/
COMMENT ON COLUMN ED9134W_TBL.IKKATSU_TORIKOMIYO_SHAIN_NO IS '一括取込用社員番号'
/
COMMENT ON COLUMN ED9134W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9134W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9134W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9134W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9134W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9134W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9134W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9134W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9134W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9134W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9134W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9134W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
