/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9153M_TBL.sql
-- 物理名：ED9153M_TBL
-- 論理名：業務依頼先グループ詳細マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9153M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9153M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,GYMIRI_GROUP_CD  CHAR(3) NOT NULL --「業務依頼先グループコード」
	,GYOMU_IRAISAKI_GROUP_SN  NUMBER(5,0) DEFAULT '1' NOT NULL --「業務依頼先グループ連番」
	,IRAISAKI_JIGYOSHO_CD  CHAR(6) --「依頼先事業所コード」
	,IRISK_YKSHK_CD  VARCHAR2(4) --「依頼先役職コード」
	,IRISK_SHKM_CD  VARCHAR2(4) --「依頼先職務コード」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9153M_PK PRIMARY KEY(
	 GYOMU_IRAISAKI_GROUP_SN
	,  GYMIRI_GROUP_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9153M_TBL IS '業務依頼先グループ詳細マスタ'
/

COMMENT ON COLUMN ED9153M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED9153M_TBL.GYMIRI_GROUP_CD IS '業務依頼先グループコード'
/
COMMENT ON COLUMN ED9153M_TBL.GYOMU_IRAISAKI_GROUP_SN IS '業務依頼先グループ連番'
/
COMMENT ON COLUMN ED9153M_TBL.IRAISAKI_JIGYOSHO_CD IS '依頼先事業所コード'
/
COMMENT ON COLUMN ED9153M_TBL.IRISK_YKSHK_CD IS '依頼先役職コード'
/
COMMENT ON COLUMN ED9153M_TBL.IRISK_SHKM_CD IS '依頼先職務コード'
/
COMMENT ON COLUMN ED9153M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9153M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9153M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9153M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9153M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9153M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9153M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9153M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9153M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9153M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9153M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9153M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
