/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9103M_TBL.sql
-- 物理名：ED9103M_TBL
-- 論理名：ユーザ確認対象バッチ処理マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9103M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9103M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,USER_KAKUNIN_TAISHO_JOB_ID  CHAR(15) NOT NULL --「ユーザ確認対象ジョブＩＤ」
	,USER_KAKUNIN_TAISHO_JOB_NM  VARCHAR2(20) --「ユーザ確認対象ジョブ名称」
	,UPLOAD_TAISHO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「アップロード対象フラグ」
	,YAKAN_BATCH_JIGYOSHO_CD  CHAR(6) --「夜間バッチ事業所コード」
	,FILE_MOJI_CD_KBN  CHAR(2) --「ファイル文字コード区分」
	,UPLOAD_GYOMU_CHECK_PROGRAM_ID  VARCHAR2(255) --「アップロード業務チェックプログラムＩＤ」
	,JOB_JUFUKU_KIDO_FUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「ジョブ重複起動不可フラグ」
	,UPLOAD_GROUP_CD  VARCHAR2(20) --「アップロードグループコード」
	,SHR_KEKKA_DOWNLOAD_FILE_NM  VARCHAR2(255) --「処理結果ダウンロードファイル名称」
	,GYOMU_KINO_REQUEST_KIDO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「業務機能リクエスト起動フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9103M_PK PRIMARY KEY(
	 USER_KAKUNIN_TAISHO_JOB_ID
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9103M_TBL IS 'ユーザ確認対象バッチ処理マスタ'
/

COMMENT ON COLUMN ED9103M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED9103M_TBL.USER_KAKUNIN_TAISHO_JOB_ID IS 'ユーザ確認対象ジョブＩＤ'
/
COMMENT ON COLUMN ED9103M_TBL.USER_KAKUNIN_TAISHO_JOB_NM IS 'ユーザ確認対象ジョブ名称'
/
COMMENT ON COLUMN ED9103M_TBL.UPLOAD_TAISHO_FLG IS 'アップロード対象フラグ'
/
COMMENT ON COLUMN ED9103M_TBL.YAKAN_BATCH_JIGYOSHO_CD IS '夜間バッチ事業所コード'
/
COMMENT ON COLUMN ED9103M_TBL.FILE_MOJI_CD_KBN IS 'ファイル文字コード区分'
/
COMMENT ON COLUMN ED9103M_TBL.UPLOAD_GYOMU_CHECK_PROGRAM_ID IS 'アップロード業務チェックプログラムＩＤ'
/
COMMENT ON COLUMN ED9103M_TBL.JOB_JUFUKU_KIDO_FUKA_FLG IS 'ジョブ重複起動不可フラグ'
/
COMMENT ON COLUMN ED9103M_TBL.UPLOAD_GROUP_CD IS 'アップロードグループコード'
/
COMMENT ON COLUMN ED9103M_TBL.SHR_KEKKA_DOWNLOAD_FILE_NM IS '処理結果ダウンロードファイル名称'
/
COMMENT ON COLUMN ED9103M_TBL.GYOMU_KINO_REQUEST_KIDO_FLG IS '業務機能リクエスト起動フラグ'
/
COMMENT ON COLUMN ED9103M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9103M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9103M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9103M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9103M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9103M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9103M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9103M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9103M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9103M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9103M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9103M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
