/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9160W_TBL.sql
-- 物理名：ED9160W_TBL
-- 論理名：警備系＿営業送信＿社員ワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9160W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9160W_TBL (
	 KBK_KAISHA_CD  CHAR(5) NOT NULL --「ＫＢＫ＿会社コード」
	,KBK_SHAIN_NO  VARCHAR2(8) NOT NULL --「ＫＢＫ＿社員番号」
	,KBK_TEKIYO_KAISHI_YMD  CHAR(8) NOT NULL --「ＫＢＫ＿適用開始年月日」
	,KBK_TEKIYO_SHURYO_YMD  CHAR(8) NOT NULL --「ＫＢＫ＿適用終了年月日」
	,KBK_NYUSHA_YMD  CHAR(8) --「ＫＢＫ＿入社年月日」
	,KBK_TAISHOKU_YMD  CHAR(8) --「ＫＢＫ＿退職年月日」
	,KBK_SHAIN_NM  VARCHAR2(60) --「ＫＢＫ＿社員氏名」
	,KBK_SHAINSEI_NM  VARCHAR2(30) --「ＫＢＫ＿社員姓氏名」
	,KBK_SHAIMMEI_NM  VARCHAR2(30) --「ＫＢＫ＿社員名氏名」
	,KBK_SHAIN_HKN_NM  VARCHAR2(90) --「ＫＢＫ＿社員半角カナ氏名」
	,KBK_SHAIN_KN_NM  VARCHAR2(90) --「ＫＢＫ＿社員カナ氏名」
	,KBK_MIBUN_CD  VARCHAR2(3) --「ＫＢＫ＿身分コード」
	,KBK_MIBUN_NM  VARCHAR2(200) --「ＫＢＫ＿身分名称」
	,KBK_SEIBETSU_KBN  CHAR(1) NOT NULL --「ＫＢＫ＿性別区分」
	,KBK_SEIBETSU_NM  VARCHAR2(10) --「ＫＢＫ＿性別名称」
	,KBK_SHAIN_SAIYO_KBN  CHAR(3) --「ＫＢＫ＿社員採用区分」
	,KBK_SHAIN_SAIYO_NM  VARCHAR2(10) --「ＫＢＫ＿社員採用名称」
	,KBK_YAKUSHOKU_CD  VARCHAR2(4) --「ＫＢＫ＿役職コード」
	,KBK_YAKUSHOKU_NM  VARCHAR2(200) --「ＫＢＫ＿役職名称」
	,KBK_YAKUSHOKU_RNM  VARCHAR2(200) --「ＫＢＫ＿役職略称」
	,KBK_SHOKUMU_CD  VARCHAR2(4) --「ＫＢＫ＿職務コード」
	,KBK_SHOKUMU_NM  VARCHAR2(200) --「ＫＢＫ＿職務名称」
	,KBK_SHOKUMU_RNM  VARCHAR2(200) --「ＫＢＫ＿職務略称」
	,KBK_JIGYO_SEGMENT_CD  CHAR(3) --「ＫＢＫ＿事業セグメントコード」
	,KBK_JIGYO_SEGMENT_NM  VARCHAR2(64) --「ＫＢＫ＿事業セグメント名称」
	,KBK_SHOKUSHU_CD  VARCHAR2(4) --「ＫＢＫ＿職種コード」
	,KBK_SHOKUSHU_NM  VARCHAR2(200) --「ＫＢＫ＿職種名称」
	,KBK_YOBI_KOMOKU_01  VARCHAR2(255) --「ＫＢＫ＿予備項目０１」
	,KBK_YOBI_KOMOKU_02  VARCHAR2(255) --「ＫＢＫ＿予備項目０２」
	,KBK_YOBI_KOMOKU_03  VARCHAR2(255) --「ＫＢＫ＿予備項目０３」
	,KBK_YOBI_KOMOKU_04  VARCHAR2(255) --「ＫＢＫ＿予備項目０４」
	,KBK_YOBI_KOMOKU_05  VARCHAR2(255) --「ＫＢＫ＿予備項目０５」
	,KBK_YOBI_KOMOKU_06  VARCHAR2(255) --「ＫＢＫ＿予備項目０６」
	,KBK_YOBI_KOMOKU_07  VARCHAR2(255) --「ＫＢＫ＿予備項目０７」
	,KBK_YOBI_KOMOKU_08  VARCHAR2(255) --「ＫＢＫ＿予備項目０８」
	,KBK_YOBI_KOMOKU_09  VARCHAR2(255) --「ＫＢＫ＿予備項目０９」
	,KBK_YOBI_KOMOKU_10  VARCHAR2(255) --「ＫＢＫ＿予備項目１０」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9160W_PK PRIMARY KEY(
	 KBK_SHAIN_NO
	,  KBK_KAISHA_CD
	,  KBK_TEKIYO_KAISHI_YMD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9160W_TBL IS '警備系＿営業送信＿社員ワーク'
/

COMMENT ON COLUMN ED9160W_TBL.KBK_KAISHA_CD IS 'ＫＢＫ＿会社コード'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SHAIN_NO IS 'ＫＢＫ＿社員番号'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_TEKIYO_KAISHI_YMD IS 'ＫＢＫ＿適用開始年月日'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_TEKIYO_SHURYO_YMD IS 'ＫＢＫ＿適用終了年月日'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_NYUSHA_YMD IS 'ＫＢＫ＿入社年月日'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_TAISHOKU_YMD IS 'ＫＢＫ＿退職年月日'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SHAIN_NM IS 'ＫＢＫ＿社員氏名'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SHAINSEI_NM IS 'ＫＢＫ＿社員姓氏名'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SHAIMMEI_NM IS 'ＫＢＫ＿社員名氏名'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SHAIN_HKN_NM IS 'ＫＢＫ＿社員半角カナ氏名'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SHAIN_KN_NM IS 'ＫＢＫ＿社員カナ氏名'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_MIBUN_CD IS 'ＫＢＫ＿身分コード'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_MIBUN_NM IS 'ＫＢＫ＿身分名称'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SEIBETSU_KBN IS 'ＫＢＫ＿性別区分'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SEIBETSU_NM IS 'ＫＢＫ＿性別名称'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SHAIN_SAIYO_KBN IS 'ＫＢＫ＿社員採用区分'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SHAIN_SAIYO_NM IS 'ＫＢＫ＿社員採用名称'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_YAKUSHOKU_CD IS 'ＫＢＫ＿役職コード'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_YAKUSHOKU_NM IS 'ＫＢＫ＿役職名称'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_YAKUSHOKU_RNM IS 'ＫＢＫ＿役職略称'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SHOKUMU_CD IS 'ＫＢＫ＿職務コード'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SHOKUMU_NM IS 'ＫＢＫ＿職務名称'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SHOKUMU_RNM IS 'ＫＢＫ＿職務略称'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_JIGYO_SEGMENT_CD IS 'ＫＢＫ＿事業セグメントコード'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_JIGYO_SEGMENT_NM IS 'ＫＢＫ＿事業セグメント名称'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SHOKUSHU_CD IS 'ＫＢＫ＿職種コード'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_SHOKUSHU_NM IS 'ＫＢＫ＿職種名称'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_YOBI_KOMOKU_01 IS 'ＫＢＫ＿予備項目０１'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_YOBI_KOMOKU_02 IS 'ＫＢＫ＿予備項目０２'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_YOBI_KOMOKU_03 IS 'ＫＢＫ＿予備項目０３'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_YOBI_KOMOKU_04 IS 'ＫＢＫ＿予備項目０４'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_YOBI_KOMOKU_05 IS 'ＫＢＫ＿予備項目０５'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_YOBI_KOMOKU_06 IS 'ＫＢＫ＿予備項目０６'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_YOBI_KOMOKU_07 IS 'ＫＢＫ＿予備項目０７'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_YOBI_KOMOKU_08 IS 'ＫＢＫ＿予備項目０８'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_YOBI_KOMOKU_09 IS 'ＫＢＫ＿予備項目０９'
/
COMMENT ON COLUMN ED9160W_TBL.KBK_YOBI_KOMOKU_10 IS 'ＫＢＫ＿予備項目１０'
/
COMMENT ON COLUMN ED9160W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9160W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9160W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9160W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9160W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9160W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9160W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9160W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9160W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9160W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9160W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9160W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
