/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9116T_TBL.sql
-- 物理名：ED9116T_TBL
-- 論理名：業務依頼テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9116T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9116T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SHINSEI_SHONIN_NO  CHAR(14) NOT NULL --「申請承認番号」
	,GYOMU_IRAI_STATUS_KBN  CHAR(2) NOT NULL --「業務依頼ステータス区分」
	,GYM_IRI_SHBTS_BNRI_KBN  CHAR(1) NOT NULL --「業務依頼種別分類区分」
	,GYM_IRI_SHBTS_DIBNRI_CD  CHAR(2) NOT NULL --「業務依頼種別大分類コード」
	,GYM_IRI_SHBTS_CHBNRI_CD  CHAR(2) NOT NULL --「業務依頼種別中分類コード」
	,GYM_IRI_SHBTS_SHBNRI_CD  CHAR(2) NOT NULL --「業務依頼種別小分類コード」
	,IRAI_DT  TIMESTAMP NOT NULL --「依頼日時」
	,IRAISAKI_JIGYOSHO_CD  CHAR(6) NOT NULL --「依頼先事業所コード」
	,IRISK_YKSHK_CD  VARCHAR2(4) --「依頼先役職コード」
	,IRISK_SHKM_CD  VARCHAR2(4) --「依頼先職務コード」
	,IRAISAKI_SHAIN_NO  VARCHAR2(8) --「依頼先社員番号」
	,IRIMT_JIGYOSHO_CD  CHAR(6) --「依頼元事業所コード」
	,IRIMT_SHAIN_NO  VARCHAR2(8) --「依頼元社員番号」
	,IRAISHA_MAIL_ADDRESS  VARCHAR2(200) --「依頼者メールアドレス」
	,IRAISHA_NAISEN_NO  VARCHAR2(20) --「依頼者内線番号」
	,IRAISHA_KEITAI_DENWA_NO  VARCHAR2(20) --「依頼者携帯電話番号」
	,IRAISHA_GAISEN_NO  VARCHAR2(20) --「依頼者外線番号」
	,NOHIN_JISSHI_DT  TIMESTAMP --「納品実施日時」
	,NOHIN_KIBO_YMD  DATE --「納品希望年月日」
	,ANKEN_NO  CHAR(13) --「案件番号」
	,JUCHU_KEIYAKU_NO  CHAR(15) --「受注契約番号」
	,DENKEI_NO  CHAR(9) --「電計番号」
	,NYUSHUKKINKI_NO  VARCHAR2(6) --「入出金機番号」
	,SEKISAN_NO  CHAR(17) --「積算番号」
	,ANKEN_TORIHIKISAKI_CD  CHAR(9) --「案件取引先コード」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,KIYKSK_TRHKSK_BSH_CD  CHAR(4) --「契約先取引先部署コード」
	,GYOMU_IRAI_NAIYO  VARCHAR2(1000) --「業務依頼内容」
	,GYM_IRI_RNRKHY_ATSK_NM  VARCHAR2(40) --「業務依頼連絡票宛先名称」
	,KEISHO_KBN  CHAR(1) --「敬称区分」
	,GYOMU_IRAI_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「業務依頼件数」
	,SAGYO_NAIYO_HYOKA_KBN  CHAR(1) --「作業内容評価区分」
	,SAGYO_NAIYO_HYOKA_CMNT  VARCHAR2(200) --「作業内容評価コメント」
	,NOKI_HYOKA_KBN  CHAR(1) --「納期評価区分」
	,NOKI_HYOKA_CMNT  VARCHAR2(200) --「納期評価コメント」
	,NOHIN_YOTEI_YMD  DATE --「納品予定年月日」
	,CHECK_TANTOSHA_SONZAI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「チェック担当者存在フラグ」
	,CHECK_TANTOSHA_JIGYOSHO_CD  CHAR(6) --「チェック担当者事業所コード」
	,CHECK_TANTOSHA_SHAIN_NO  VARCHAR2(8) --「チェック担当者社員番号」
	,IRAISAKI_NYURYOKU_JOHO_NAIYO  VARCHAR2(500) --「依頼先入力情報内容」
	,SHORI_KENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「処理件数」
	,SAGYO_JIKAN  NUMBER(12,3) DEFAULT '0' NOT NULL --「作業時間」
	,SAGYO_TANTOSHA_SHAIN_NO  VARCHAR2(8) --「作業担当者社員番号」
	,SGY_TNTSH_JIGYOSHO_CD  CHAR(6) --「作業担当者事業所コード」
	,IRAI_NAIYO_HYOKA_KBN  CHAR(1) --「依頼内容評価区分」
	,IRAI_NAIYO_HYOKA_CMNT  VARCHAR2(200) --「依頼内容評価コメント」
	,IRAIJI_RENRAKU_KBN  CHAR(1) --「依頼時連絡区分」
	,IRAIJI_RENRAKU_CMNT  VARCHAR2(200) --「依頼時連絡コメント」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9116T_PK PRIMARY KEY(
	 SHINSEI_SHONIN_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9116T_TBL IS '業務依頼テーブル'
/

COMMENT ON COLUMN ED9116T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED9116T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED9116T_TBL.GYOMU_IRAI_STATUS_KBN IS '業務依頼ステータス区分'
/
COMMENT ON COLUMN ED9116T_TBL.GYM_IRI_SHBTS_BNRI_KBN IS '業務依頼種別分類区分'
/
COMMENT ON COLUMN ED9116T_TBL.GYM_IRI_SHBTS_DIBNRI_CD IS '業務依頼種別大分類コード'
/
COMMENT ON COLUMN ED9116T_TBL.GYM_IRI_SHBTS_CHBNRI_CD IS '業務依頼種別中分類コード'
/
COMMENT ON COLUMN ED9116T_TBL.GYM_IRI_SHBTS_SHBNRI_CD IS '業務依頼種別小分類コード'
/
COMMENT ON COLUMN ED9116T_TBL.IRAI_DT IS '依頼日時'
/
COMMENT ON COLUMN ED9116T_TBL.IRAISAKI_JIGYOSHO_CD IS '依頼先事業所コード'
/
COMMENT ON COLUMN ED9116T_TBL.IRISK_YKSHK_CD IS '依頼先役職コード'
/
COMMENT ON COLUMN ED9116T_TBL.IRISK_SHKM_CD IS '依頼先職務コード'
/
COMMENT ON COLUMN ED9116T_TBL.IRAISAKI_SHAIN_NO IS '依頼先社員番号'
/
COMMENT ON COLUMN ED9116T_TBL.IRIMT_JIGYOSHO_CD IS '依頼元事業所コード'
/
COMMENT ON COLUMN ED9116T_TBL.IRIMT_SHAIN_NO IS '依頼元社員番号'
/
COMMENT ON COLUMN ED9116T_TBL.IRAISHA_MAIL_ADDRESS IS '依頼者メールアドレス'
/
COMMENT ON COLUMN ED9116T_TBL.IRAISHA_NAISEN_NO IS '依頼者内線番号'
/
COMMENT ON COLUMN ED9116T_TBL.IRAISHA_KEITAI_DENWA_NO IS '依頼者携帯電話番号'
/
COMMENT ON COLUMN ED9116T_TBL.IRAISHA_GAISEN_NO IS '依頼者外線番号'
/
COMMENT ON COLUMN ED9116T_TBL.NOHIN_JISSHI_DT IS '納品実施日時'
/
COMMENT ON COLUMN ED9116T_TBL.NOHIN_KIBO_YMD IS '納品希望年月日'
/
COMMENT ON COLUMN ED9116T_TBL.ANKEN_NO IS '案件番号'
/
COMMENT ON COLUMN ED9116T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED9116T_TBL.DENKEI_NO IS '電計番号'
/
COMMENT ON COLUMN ED9116T_TBL.NYUSHUKKINKI_NO IS '入出金機番号'
/
COMMENT ON COLUMN ED9116T_TBL.SEKISAN_NO IS '積算番号'
/
COMMENT ON COLUMN ED9116T_TBL.ANKEN_TORIHIKISAKI_CD IS '案件取引先コード'
/
COMMENT ON COLUMN ED9116T_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED9116T_TBL.KIYKSK_TRHKSK_BSH_CD IS '契約先取引先部署コード'
/
COMMENT ON COLUMN ED9116T_TBL.GYOMU_IRAI_NAIYO IS '業務依頼内容'
/
COMMENT ON COLUMN ED9116T_TBL.GYM_IRI_RNRKHY_ATSK_NM IS '業務依頼連絡票宛先名称'
/
COMMENT ON COLUMN ED9116T_TBL.KEISHO_KBN IS '敬称区分'
/
COMMENT ON COLUMN ED9116T_TBL.GYOMU_IRAI_KENSU IS '業務依頼件数'
/
COMMENT ON COLUMN ED9116T_TBL.SAGYO_NAIYO_HYOKA_KBN IS '作業内容評価区分'
/
COMMENT ON COLUMN ED9116T_TBL.SAGYO_NAIYO_HYOKA_CMNT IS '作業内容評価コメント'
/
COMMENT ON COLUMN ED9116T_TBL.NOKI_HYOKA_KBN IS '納期評価区分'
/
COMMENT ON COLUMN ED9116T_TBL.NOKI_HYOKA_CMNT IS '納期評価コメント'
/
COMMENT ON COLUMN ED9116T_TBL.NOHIN_YOTEI_YMD IS '納品予定年月日'
/
COMMENT ON COLUMN ED9116T_TBL.CHECK_TANTOSHA_SONZAI_FLG IS 'チェック担当者存在フラグ'
/
COMMENT ON COLUMN ED9116T_TBL.CHECK_TANTOSHA_JIGYOSHO_CD IS 'チェック担当者事業所コード'
/
COMMENT ON COLUMN ED9116T_TBL.CHECK_TANTOSHA_SHAIN_NO IS 'チェック担当者社員番号'
/
COMMENT ON COLUMN ED9116T_TBL.IRAISAKI_NYURYOKU_JOHO_NAIYO IS '依頼先入力情報内容'
/
COMMENT ON COLUMN ED9116T_TBL.SHORI_KENSU IS '処理件数'
/
COMMENT ON COLUMN ED9116T_TBL.SAGYO_JIKAN IS '作業時間'
/
COMMENT ON COLUMN ED9116T_TBL.SAGYO_TANTOSHA_SHAIN_NO IS '作業担当者社員番号'
/
COMMENT ON COLUMN ED9116T_TBL.SGY_TNTSH_JIGYOSHO_CD IS '作業担当者事業所コード'
/
COMMENT ON COLUMN ED9116T_TBL.IRAI_NAIYO_HYOKA_KBN IS '依頼内容評価区分'
/
COMMENT ON COLUMN ED9116T_TBL.IRAI_NAIYO_HYOKA_CMNT IS '依頼内容評価コメント'
/
COMMENT ON COLUMN ED9116T_TBL.IRAIJI_RENRAKU_KBN IS '依頼時連絡区分'
/
COMMENT ON COLUMN ED9116T_TBL.IRAIJI_RENRAKU_CMNT IS '依頼時連絡コメント'
/
COMMENT ON COLUMN ED9116T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9116T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9116T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9116T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9116T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9116T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9116T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9116T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9116T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9116T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9116T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9116T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
