/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9100M_TBL.sql
-- 物理名：ED9100M_TBL
-- 論理名：申請承認処理マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9100M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9100M_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,SHINSEI_SHONIN_ID  CHAR(6) NOT NULL --「申請承認ＩＤ」
	,SHINSEI_SHONIN_SHORI_KBN  CHAR(2) NOT NULL --「申請承認処理区分」
	,SENISAKI_GAMEN_ID  CHAR(15) --「遷移先画面ＩＤ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9100M_PK PRIMARY KEY(
	 SHINSEI_SHONIN_SHORI_KBN
	,  SHINSEI_SHONIN_ID
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9100M_TBL IS '申請承認処理マスタ'
/

COMMENT ON COLUMN ED9100M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED9100M_TBL.SHINSEI_SHONIN_ID IS '申請承認ＩＤ'
/
COMMENT ON COLUMN ED9100M_TBL.SHINSEI_SHONIN_SHORI_KBN IS '申請承認処理区分'
/
COMMENT ON COLUMN ED9100M_TBL.SENISAKI_GAMEN_ID IS '遷移先画面ＩＤ'
/
COMMENT ON COLUMN ED9100M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9100M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9100M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9100M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9100M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9100M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9100M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9100M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9100M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9100M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9100M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9100M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
