/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9130W_TBL.sql
-- 物理名：ED9130W_TBL
-- 論理名：業種マスタファイルワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9130W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9130W_TBL (
	 RECORD_SOSA_KBN  CHAR(1) NOT NULL --「レコード操作区分」
	,GYOSHU_CD  CHAR(4) NOT NULL --「業種コード」
	,GYOSHU_NM  VARCHAR2(60) --「業種名称」
	,GYOSHU_DAIBUNRUI_CD  CHAR(2) --「業種大分類コード」
	,GYOSHU_CHUBUNRUI_CD  CHAR(2) --「業種中分類コード」
	,EIGY_KNR_GYSH_DIBNRI_CD  CHAR(2) --「営業管理業種大分類コード」
	,EIGY_KNR_GYSH_CHBNRI_CD  CHAR(2) --「営業管理業種中分類コード」
	,EIGY_KNR_GYSH_SHBNRI_CD  CHAR(3) --「営業管理業種小分類コード」
	,EIGY_KNR_GYSH_SIBNRI_CD  CHAR(4) --「営業管理業種細分類コード」
	,TORIHIKISAKI_GYOSHU_KBN  CHAR(1) NOT NULL --「取引先業種区分」
	,SHIYO_FUKA_FLG  CHAR(1) DEFAULT '0' NOT NULL --「使用不可フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9130W_PK PRIMARY KEY(
	 RECORD_SOSA_KBN
	,  GYOSHU_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9130W_TBL IS '業種マスタファイルワーク'
/

COMMENT ON COLUMN ED9130W_TBL.RECORD_SOSA_KBN IS 'レコード操作区分'
/
COMMENT ON COLUMN ED9130W_TBL.GYOSHU_CD IS '業種コード'
/
COMMENT ON COLUMN ED9130W_TBL.GYOSHU_NM IS '業種名称'
/
COMMENT ON COLUMN ED9130W_TBL.GYOSHU_DAIBUNRUI_CD IS '業種大分類コード'
/
COMMENT ON COLUMN ED9130W_TBL.GYOSHU_CHUBUNRUI_CD IS '業種中分類コード'
/
COMMENT ON COLUMN ED9130W_TBL.EIGY_KNR_GYSH_DIBNRI_CD IS '営業管理業種大分類コード'
/
COMMENT ON COLUMN ED9130W_TBL.EIGY_KNR_GYSH_CHBNRI_CD IS '営業管理業種中分類コード'
/
COMMENT ON COLUMN ED9130W_TBL.EIGY_KNR_GYSH_SHBNRI_CD IS '営業管理業種小分類コード'
/
COMMENT ON COLUMN ED9130W_TBL.EIGY_KNR_GYSH_SIBNRI_CD IS '営業管理業種細分類コード'
/
COMMENT ON COLUMN ED9130W_TBL.TORIHIKISAKI_GYOSHU_KBN IS '取引先業種区分'
/
COMMENT ON COLUMN ED9130W_TBL.SHIYO_FUKA_FLG IS '使用不可フラグ'
/
COMMENT ON COLUMN ED9130W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9130W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9130W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9130W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9130W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9130W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9130W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9130W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9130W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9130W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9130W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9130W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
