/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9174W_TBL.sql
-- 物理名：ED9174W_TBL
-- 論理名：統合監査ログワーク
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9174W_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9174W_TBL (
	 KANSA_LOG_SN  CHAR(14) NOT NULL --「監査ログ連番」
	,KANSA_LOG_EVENT_DT  TIMESTAMP NOT NULL --「監査ログイベント日時」
	,KANSA_LOG_RETURN_CD  NUMBER(38,0) DEFAULT '0' NOT NULL --「監査ログリターンコード」
	,KANSA_LOG_ACTION_NM  VARCHAR2(100) --「監査ログアクション名称」
	,KANSA_LOG_TABLE_ID  CHAR(11) --「監査ログテーブルＩＤ」
	,KANSA_LOG_SQL_NAIYO  CLOB --「監査ログＳＱＬ内容」
	,KANSA_LOG_SQL_BINDS_NAIYO  CLOB --「監査ログＳＱＬバインド内容」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9174W_PK PRIMARY KEY(
	 KANSA_LOG_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9174W_TBL IS '統合監査ログワーク'
/

COMMENT ON COLUMN ED9174W_TBL.KANSA_LOG_SN IS '監査ログ連番'
/
COMMENT ON COLUMN ED9174W_TBL.KANSA_LOG_EVENT_DT IS '監査ログイベント日時'
/
COMMENT ON COLUMN ED9174W_TBL.KANSA_LOG_RETURN_CD IS '監査ログリターンコード'
/
COMMENT ON COLUMN ED9174W_TBL.KANSA_LOG_ACTION_NM IS '監査ログアクション名称'
/
COMMENT ON COLUMN ED9174W_TBL.KANSA_LOG_TABLE_ID IS '監査ログテーブルＩＤ'
/
COMMENT ON COLUMN ED9174W_TBL.KANSA_LOG_SQL_NAIYO IS '監査ログＳＱＬ内容'
/
COMMENT ON COLUMN ED9174W_TBL.KANSA_LOG_SQL_BINDS_NAIYO IS '監査ログＳＱＬバインド内容'
/
COMMENT ON COLUMN ED9174W_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9174W_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9174W_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9174W_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9174W_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9174W_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9174W_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9174W_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9174W_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9174W_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9174W_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9174W_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
