/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED9601M_TBL.sql
-- 物理名：ED9601M_TBL
-- 論理名：マニュアル管理マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED9601M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED9601M_TBL (
	 SYSTEM_ID  CHAR(1) NOT NULL --「システムＩＤ」
	,KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,MANUAL_ID  VARCHAR2(36) NOT NULL --「マニュアルＩＤ」
	,MANUAL_NM  VARCHAR2(255) NOT NULL --「マニュアル名称」
	,FILE_PATH  VARCHAR2(1024) NOT NULL --「ファイルパス」
	,MANUAL_MOKUJI_ID  CHAR(9) NOT NULL --「マニュアル目次ＩＤ」
	,MANUAL_MOKUJI_KOMOKU_NO  VARCHAR2(8) --「マニュアル目次項目番号」
	,MANUAL_HYOJI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「マニュアル表示順」
	,RONRI_SAKUJO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「論理削除フラグ」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED9601M_PK PRIMARY KEY(
	 MANUAL_ID
	,  KAISHA_CD
	,  SYSTEM_ID
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED9601M_TBL IS 'マニュアル管理マスタ'
/

COMMENT ON COLUMN ED9601M_TBL.SYSTEM_ID IS 'システムＩＤ'
/
COMMENT ON COLUMN ED9601M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED9601M_TBL.MANUAL_ID IS 'マニュアルＩＤ'
/
COMMENT ON COLUMN ED9601M_TBL.MANUAL_NM IS 'マニュアル名称'
/
COMMENT ON COLUMN ED9601M_TBL.FILE_PATH IS 'ファイルパス'
/
COMMENT ON COLUMN ED9601M_TBL.MANUAL_MOKUJI_ID IS 'マニュアル目次ＩＤ'
/
COMMENT ON COLUMN ED9601M_TBL.MANUAL_MOKUJI_KOMOKU_NO IS 'マニュアル目次項目番号'
/
COMMENT ON COLUMN ED9601M_TBL.MANUAL_HYOJI_JUN IS 'マニュアル表示順'
/
COMMENT ON COLUMN ED9601M_TBL.RONRI_SAKUJO_FLG IS '論理削除フラグ'
/
COMMENT ON COLUMN ED9601M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED9601M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED9601M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED9601M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED9601M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED9601M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED9601M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED9601M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED9601M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED9601M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED9601M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED9601M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
