/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ZD0005M_TBL.sql
-- 物理名：ZD0005M_TBL
-- 論理名：電子帳票格納先マスタ
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ZD0005M_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ZD0005M_TBL (
	 SYSTEM_ID  CHAR(1) NOT NULL --「システムＩＤ」
	,KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,CHOHYO_KAKUNO_SAKI_ID  VARCHAR2(36) NOT NULL --「帳票格納先ＩＤ」
	,CHOHYO_KAKUNO_SAKI_NM  VARCHAR2(100) NOT NULL --「帳票格納先名称」
	,OYA_CHOHYO_KAKUNO_SAKI_ID  VARCHAR2(36) --「親帳票格納先ＩＤ」
	,CHOHYO_KAKUNO_SAKI_KAISO  NUMBER(9,0) DEFAULT '0' NOT NULL --「帳票格納先階層」
	,KO_KAISO_TOROKU_KANO_FLG  CHAR(1) DEFAULT '1' NOT NULL --「子階層登録可能フラグ」
	,FILE_TOROKU_KANO_FLG  CHAR(1) DEFAULT '1' NOT NULL --「ファイル登録可能フラグ」
	,SHOKAI_GAMEN_HYOJI_FLG  CHAR(1) DEFAULT '1' NOT NULL --「照会画面表示フラグ」
	,KENGEN_CHECK_ARI_FLG  CHAR(1) DEFAULT '1' NOT NULL --「権限チェック有フラグ」
	,CHOHYO_KAKUNOSAKI_HYOJI_JUN  NUMBER(4,0) DEFAULT '0' NOT NULL --「帳票格納先表示順」
	,CHOHYO_KAKUNOSAKI_PATH  VARCHAR2(300) --「帳票格納先パス」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ZD0005M_PK PRIMARY KEY(
	 CHOHYO_KAKUNO_SAKI_ID
	,  KAISHA_CD
	,  SYSTEM_ID
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ZD0005M_TBL IS '電子帳票格納先マスタ'
/

COMMENT ON COLUMN ZD0005M_TBL.SYSTEM_ID IS 'システムＩＤ'
/
COMMENT ON COLUMN ZD0005M_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ZD0005M_TBL.CHOHYO_KAKUNO_SAKI_ID IS '帳票格納先ＩＤ'
/
COMMENT ON COLUMN ZD0005M_TBL.CHOHYO_KAKUNO_SAKI_NM IS '帳票格納先名称'
/
COMMENT ON COLUMN ZD0005M_TBL.OYA_CHOHYO_KAKUNO_SAKI_ID IS '親帳票格納先ＩＤ'
/
COMMENT ON COLUMN ZD0005M_TBL.CHOHYO_KAKUNO_SAKI_KAISO IS '帳票格納先階層'
/
COMMENT ON COLUMN ZD0005M_TBL.KO_KAISO_TOROKU_KANO_FLG IS '子階層登録可能フラグ'
/
COMMENT ON COLUMN ZD0005M_TBL.FILE_TOROKU_KANO_FLG IS 'ファイル登録可能フラグ'
/
COMMENT ON COLUMN ZD0005M_TBL.SHOKAI_GAMEN_HYOJI_FLG IS '照会画面表示フラグ'
/
COMMENT ON COLUMN ZD0005M_TBL.KENGEN_CHECK_ARI_FLG IS '権限チェック有フラグ'
/
COMMENT ON COLUMN ZD0005M_TBL.CHOHYO_KAKUNOSAKI_HYOJI_JUN IS '帳票格納先表示順'
/
COMMENT ON COLUMN ZD0005M_TBL.CHOHYO_KAKUNOSAKI_PATH IS '帳票格納先パス'
/
COMMENT ON COLUMN ZD0005M_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ZD0005M_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ZD0005M_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ZD0005M_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ZD0005M_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ZD0005M_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ZD0005M_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ZD0005M_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ZD0005M_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ZD0005M_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ZD0005M_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ZD0005M_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
