/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ZD0022T_TBL.sql
-- 物理名：ZD0022T_TBL
-- 論理名：取引先利用端末テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ZD0022T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ZD0022T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,TORIHIKISAKI_CD  CHAR(9) NOT NULL --「取引先コード」
	,COMPUTER_NM  VARCHAR2(60) --「コンピュータ名称」
	,MAC_ADDRESS  VARCHAR2(64) NOT NULL --「ＭＡＣアドレス」
	,TANMATSU_TOROKU_DT  TIMESTAMP --「端末登録日時」
	,TNMTS_TRK_SHGI_RYSH_NO  CHAR(8) --「端末登録社外利用者番号」
	,TNMTS_TRK_SHGI_RYSH_NM  VARCHAR2(60) --「端末登録社外利用者氏名」
	,SAISHU_LOGIN_DT  TIMESTAMP --「最終ログイン日時」
	,SAISHU_LOGIN_SHAGAI_RIYOSHA_NO  CHAR(8) --「最終ログイン社外利用者番号」
	,SAISHU_LOGIN_SHAGAI_RIYOSHA_NM  VARCHAR2(60) --「最終ログイン社外利用者氏名」
	,TNMTS_TRK_SHONIN_DT  TIMESTAMP --「端末登録承認日時」
	,TNMTS_TRK_SHONIN_SHAIN_NO  VARCHAR2(8) --「端末登録承認社員番号」
	,TNMTS_TRK_SHONIN_SHAIN_NM  VARCHAR2(60) --「端末登録承認社員氏名」
	,TSUCHI_SAKI_SOSHIKI_CD  VARCHAR2(6) --「通知先組織コード」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ZD0022T_PK PRIMARY KEY(
	 MAC_ADDRESS
	,  TORIHIKISAKI_CD
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ZD0022T_TBL IS '取引先利用端末テーブル'
/

COMMENT ON COLUMN ZD0022T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ZD0022T_TBL.TORIHIKISAKI_CD IS '取引先コード'
/
COMMENT ON COLUMN ZD0022T_TBL.COMPUTER_NM IS 'コンピュータ名称'
/
COMMENT ON COLUMN ZD0022T_TBL.MAC_ADDRESS IS 'ＭＡＣアドレス'
/
COMMENT ON COLUMN ZD0022T_TBL.TANMATSU_TOROKU_DT IS '端末登録日時'
/
COMMENT ON COLUMN ZD0022T_TBL.TNMTS_TRK_SHGI_RYSH_NO IS '端末登録社外利用者番号'
/
COMMENT ON COLUMN ZD0022T_TBL.TNMTS_TRK_SHGI_RYSH_NM IS '端末登録社外利用者氏名'
/
COMMENT ON COLUMN ZD0022T_TBL.SAISHU_LOGIN_DT IS '最終ログイン日時'
/
COMMENT ON COLUMN ZD0022T_TBL.SAISHU_LOGIN_SHAGAI_RIYOSHA_NO IS '最終ログイン社外利用者番号'
/
COMMENT ON COLUMN ZD0022T_TBL.SAISHU_LOGIN_SHAGAI_RIYOSHA_NM IS '最終ログイン社外利用者氏名'
/
COMMENT ON COLUMN ZD0022T_TBL.TNMTS_TRK_SHONIN_DT IS '端末登録承認日時'
/
COMMENT ON COLUMN ZD0022T_TBL.TNMTS_TRK_SHONIN_SHAIN_NO IS '端末登録承認社員番号'
/
COMMENT ON COLUMN ZD0022T_TBL.TNMTS_TRK_SHONIN_SHAIN_NM IS '端末登録承認社員氏名'
/
COMMENT ON COLUMN ZD0022T_TBL.TSUCHI_SAKI_SOSHIKI_CD IS '通知先組織コード'
/
COMMENT ON COLUMN ZD0022T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ZD0022T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ZD0022T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ZD0022T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ZD0022T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ZD0022T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ZD0022T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ZD0022T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ZD0022T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ZD0022T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ZD0022T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ZD0022T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
