/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ZD0025T_TBL.sql
-- 物理名：ZD0025T_TBL
-- 論理名：ジョブネット実行結果履歴テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ZD0025T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ZD0025T_TBL (
	 JIKKO_YMD_NAIYO  CHAR(8) NOT NULL --「実行日内容」
	,JIKKO_JIKAN_NAIYO  CHAR(6) NOT NULL --「実行時間内容」
	,JIKKO_SN  CHAR(14) NOT NULL --「実行連番」
	,HOST_NM  VARCHAR2(50) --「ホスト名称」
	,SUB_SYSTEM_NO  VARCHAR2(5) --「サブシステム番号」
	,PROJECT_ID  VARCHAR2(50) --「プロジェクトＩＤ」
	,JOBNET_ID  VARCHAR2(50) --「ジョブネットＩＤ」
	,JOBNET_NM  VARCHAR2(50) --「ジョブネット名称」
	,JOBNET_JOTAI_NAIYO  VARCHAR2(20) --「ジョブネット状態内容」
	,KIDO_YTI_TS  TIMESTAMP --「起動予定タイムスタンプ」
	,JOBNET_KAISHI_TS  TIMESTAMP --「ジョブネット開始タイムスタンプ」
	,JOBNET_SHURYO_TS  TIMESTAMP --「ジョブネット終了タイムスタンプ」
	,JOBNET_SHURYO_NO  VARCHAR2(5) --「ジョブネット終了番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ZD0025T_PK PRIMARY KEY(
	 JIKKO_YMD_NAIYO
	,  JIKKO_JIKAN_NAIYO
	,  JIKKO_SN
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ZD0025T_TBL IS 'ジョブネット実行結果履歴テーブル'
/

COMMENT ON COLUMN ZD0025T_TBL.JIKKO_YMD_NAIYO IS '実行日内容'
/
COMMENT ON COLUMN ZD0025T_TBL.JIKKO_JIKAN_NAIYO IS '実行時間内容'
/
COMMENT ON COLUMN ZD0025T_TBL.JIKKO_SN IS '実行連番'
/
COMMENT ON COLUMN ZD0025T_TBL.HOST_NM IS 'ホスト名称'
/
COMMENT ON COLUMN ZD0025T_TBL.SUB_SYSTEM_NO IS 'サブシステム番号'
/
COMMENT ON COLUMN ZD0025T_TBL.PROJECT_ID IS 'プロジェクトＩＤ'
/
COMMENT ON COLUMN ZD0025T_TBL.JOBNET_ID IS 'ジョブネットＩＤ'
/
COMMENT ON COLUMN ZD0025T_TBL.JOBNET_NM IS 'ジョブネット名称'
/
COMMENT ON COLUMN ZD0025T_TBL.JOBNET_JOTAI_NAIYO IS 'ジョブネット状態内容'
/
COMMENT ON COLUMN ZD0025T_TBL.KIDO_YTI_TS IS '起動予定タイムスタンプ'
/
COMMENT ON COLUMN ZD0025T_TBL.JOBNET_KAISHI_TS IS 'ジョブネット開始タイムスタンプ'
/
COMMENT ON COLUMN ZD0025T_TBL.JOBNET_SHURYO_TS IS 'ジョブネット終了タイムスタンプ'
/
COMMENT ON COLUMN ZD0025T_TBL.JOBNET_SHURYO_NO IS 'ジョブネット終了番号'
/
COMMENT ON COLUMN ZD0025T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ZD0025T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ZD0025T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ZD0025T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ZD0025T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ZD0025T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ZD0025T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ZD0025T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ZD0025T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ZD0025T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ZD0025T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ZD0025T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
