/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ZD0019T_TBL.sql
-- 物理名：ZD0019T_TBL
-- 論理名：中継サーバ対象ＤＢデータ削除テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ZD0019T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ZD0019T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,INTERFACE_ID  CHAR(7) NOT NULL --「インターフェースＩＤ」
	,SAKUJO_IRAI_NAIYO  VARCHAR2(300) NOT NULL --「削除依頼内容」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ZD0019T_PK PRIMARY KEY(
	 INTERFACE_ID
	,  KAISHA_CD
	,  SAKUJO_IRAI_NAIYO
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ZD0019T_TBL IS '中継サーバ対象ＤＢデータ削除テーブル'
/

COMMENT ON COLUMN ZD0019T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ZD0019T_TBL.INTERFACE_ID IS 'インターフェースＩＤ'
/
COMMENT ON COLUMN ZD0019T_TBL.SAKUJO_IRAI_NAIYO IS '削除依頼内容'
/
COMMENT ON COLUMN ZD0019T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ZD0019T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ZD0019T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ZD0019T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ZD0019T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ZD0019T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ZD0019T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ZD0019T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ZD0019T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ZD0019T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ZD0019T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ZD0019T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
