/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ZD0001T_TBL.sql
-- 物理名：ZD0001T_TBL
-- 論理名：帳票管理情報テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ZD0001T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ZD0001T_TBL (
	 SYSTEM_ID  CHAR(1) NOT NULL --「システムＩＤ」
	,KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,CHOHYO_KANRI_ID  VARCHAR2(50) NOT NULL --「帳票管理ＩＤ」
	,CHOHYO_FILE_NM  VARCHAR2(255) NOT NULL --「帳票ファイル名称」
	,CHOHYO_ID  VARCHAR2(20) --「帳票ＩＤ」
	,FILE_PATH  VARCHAR2(1024) NOT NULL --「ファイルパス」
	,CHOHYO_KAKUNO_SAKI_ID  VARCHAR2(36) NOT NULL --「帳票格納先ＩＤ」
	,DENSHI_CHOHYO_HYOJI_FLG  CHAR(1) DEFAULT '1' NOT NULL --「電子帳票表示フラグ」
	,CHOHYO_FILE_SIZE  NUMBER(10,0) DEFAULT '0' NOT NULL --「帳票ファイルサイズ」
	,CHOHYO_REGSTR_EMP_NO  VARCHAR2(100) --「帳票登録者社員番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ZD0001T_PK PRIMARY KEY(
	 CHOHYO_KANRI_ID
	,  KAISHA_CD
	,  SYSTEM_ID
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ZD0001T_TBL IS '帳票管理情報テーブル'
/

COMMENT ON COLUMN ZD0001T_TBL.SYSTEM_ID IS 'システムＩＤ'
/
COMMENT ON COLUMN ZD0001T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ZD0001T_TBL.CHOHYO_KANRI_ID IS '帳票管理ＩＤ'
/
COMMENT ON COLUMN ZD0001T_TBL.CHOHYO_FILE_NM IS '帳票ファイル名称'
/
COMMENT ON COLUMN ZD0001T_TBL.CHOHYO_ID IS '帳票ＩＤ'
/
COMMENT ON COLUMN ZD0001T_TBL.FILE_PATH IS 'ファイルパス'
/
COMMENT ON COLUMN ZD0001T_TBL.CHOHYO_KAKUNO_SAKI_ID IS '帳票格納先ＩＤ'
/
COMMENT ON COLUMN ZD0001T_TBL.DENSHI_CHOHYO_HYOJI_FLG IS '電子帳票表示フラグ'
/
COMMENT ON COLUMN ZD0001T_TBL.CHOHYO_FILE_SIZE IS '帳票ファイルサイズ'
/
COMMENT ON COLUMN ZD0001T_TBL.CHOHYO_REGSTR_EMP_NO IS '帳票登録者社員番号'
/
COMMENT ON COLUMN ZD0001T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ZD0001T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ZD0001T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ZD0001T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ZD0001T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ZD0001T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ZD0001T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ZD0001T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ZD0001T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ZD0001T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ZD0001T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ZD0001T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
