/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ZD0015T_TBL.sql
-- 物理名：ZD0015T_TBL
-- 論理名：社外パスワード世代テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ZD0015T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ZD0015T_TBL (
	 SHAGAI_RIYOSHA_NO  CHAR(8) NOT NULL --「社外利用者番号」
	,HENKOMAE_PASSWORD  VARCHAR2(128) NOT NULL --「変更前パスワード」
	,PASSWORD_HENKO_DT  TIMESTAMP --「パスワード変更日時」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ZD0015T_PK PRIMARY KEY(
	 SHAGAI_RIYOSHA_NO
	,  HENKOMAE_PASSWORD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ZD0015T_TBL IS '社外パスワード世代テーブル'
/

COMMENT ON COLUMN ZD0015T_TBL.SHAGAI_RIYOSHA_NO IS '社外利用者番号'
/
COMMENT ON COLUMN ZD0015T_TBL.HENKOMAE_PASSWORD IS '変更前パスワード'
/
COMMENT ON COLUMN ZD0015T_TBL.PASSWORD_HENKO_DT IS 'パスワード変更日時'
/
COMMENT ON COLUMN ZD0015T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ZD0015T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ZD0015T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ZD0015T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ZD0015T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ZD0015T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ZD0015T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ZD0015T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ZD0015T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ZD0015T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ZD0015T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ZD0015T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
