/* ---------------------------------------------------------------------- */
-- テーブル作成DDL(ORACLE用)
-- ファイル名：ED0517T_TBL.sql
-- 物理名：ED0517T_TBL
-- 論理名：受注テーブル
/* ---------------------------------------------------------------------- */

--/
--DROP TABLE ED0517T_TBL CASCADE CONSTRAINTS;
--/
ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';
CREATE TABLE ED0517T_TBL (
	 KAISHA_CD  CHAR(5) NOT NULL --「会社コード」
	,JUCHU_KEIYAKU_NO  CHAR(15) NOT NULL --「受注契約番号」
	,JUCHU_KEIYAKU_HENKO_NO  CHAR(6) NOT NULL --「受注契約変更番号」
	,ANKEN_NO  CHAR(13) --「案件番号」
	,ANKEN_SHOHIN_SN  CHAR(3) --「案件商品連番」
	,ANKEN_TAISHOSAKI_SN  CHAR(7) --「案件対象先連番」
	,KEIBI_SHINDAN_NO  CHAR(17) --「警備診断番号」
	,KOJI_SHIJISHO_NO  CHAR(18) --「工事指示書番号」
	,SEKISAN_NO  CHAR(17) --「積算番号」
	,SHOSAI_SEKISAN_NO  CHAR(17) --「詳細積算番号」
	,MITSUMORI_NO  CHAR(15) --「見積番号」
	,KEIYAKUSHO_NO  CHAR(17) --「契約書番号」
	,MITSUMORISHO_NO  CHAR(20) --「見積書番号」
	,SHOHIN_SERVICE_CD  CHAR(3) --「商品サービスコード」
	,SEKISAN_STATUS_KBN  CHAR(1) NOT NULL --「積算ステータス区分」
	,SHOSAI_SEKISAN_IRAI_STATUS_KBN  CHAR(1) NOT NULL --「詳細積算依頼ステータス区分」
	,KEIYAKU_STATUS_KBN  CHAR(1) NOT NULL --「契約ステータス区分」
	,JIGYO_SEGMENT_CD  CHAR(3) --「事業セグメントコード」
	,KEIYAKU_CHOKI_RINJI_KBN  CHAR(1) NOT NULL --「契約長期臨時区分」
	,DENKEI_NO  CHAR(9) --「電計番号」
	,KANREN_JUCHU_KEIYAKU_NO  CHAR(15) --「関連受注契約番号」
	,KEIYAKU_YOTEI_YMD  DATE --「契約予定年月日」
	,GYOMU_KAISHI_YOTEI_YMD  DATE --「業務開始予定年月日」
	,GYOMU_MANRYO_YOTEI_YMD  DATE --「業務満了予定年月日」
	,GYOMU_KAISHI_YMD  DATE --「業務開始年月日」
	,GYOMU_SHURYO_YMD  DATE --「業務終了年月日」
	,KEIYAKU_KOSHIN_TSUKISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「契約更新月数」
	,KEIYAKU_KOSHIN_NENSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「契約更新年数」
	,KIHON_KYOTSU_KEIYAKU_NO  CHAR(9) --「基本共通契約番号」
	,KEIYAKUSAKI_TORIHIKISAKI_CD  CHAR(9) --「契約先取引先コード」
	,KIYKSK_TRHKSK_BSH_CD  CHAR(4) --「契約先取引先部署コード」
	,TORIHIKISAKI_CD  CHAR(9) --「取引先コード」
	,TORIHIKISAKI_BUSHO_CD  CHAR(4) --「取引先部署コード」
	,KEIYAKU_TSUKISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「契約月数」
	,KEIYAKU_SHURYOBI_SETTEIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「契約終了日設定有フラグ」
	,KEIYAKU_KOSHIN_TSUCHI_KBN  CHAR(1) NOT NULL --「契約更新通知区分」
	,KAIYAKUKIN_SETTEI_KBN  CHAR(1) --「解約金設定区分」
	,KAIYAKUKINARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「解約金有フラグ」
	,KAIYAKUKIN_KEISANSHIKI_CD  CHAR(3) --「解約金計算式コード」
	,KAIYAKUKIN_KEISU  NUMBER(12,3) DEFAULT '0' NOT NULL --「解約金係数」
	,KAIYAKUKIN_HENKO_RIYU  VARCHAR2(100) --「解約金変更理由」
	,KAIYAKUKIN_TOKKI_NAIYO  VARCHAR2(100) --「解約金特記内容」
	,SEIKYU_KEITAI_KBN  CHAR(2) NOT NULL --「請求形態区分」
	,SHIHARAI_JOKEN_KBN  CHAR(1) NOT NULL --「支払条件区分」
	,SHIHARAI_D  CHAR(2) --「支払日」
	,KOKYAKU_SHIHARAI_HOHO_KBN  CHAR(2) NOT NULL --「顧客支払方法区分」
	,SEIKYUSHO_HYOJI_KIKAN_KAISHI_D  NUMBER(9,0) DEFAULT '0' NOT NULL --「請求書表示期間開始日」
	,SEIKYUSHO_HYOJI_KIKAN_SHURYO_D  NUMBER(9,0) DEFAULT '0' NOT NULL --「請求書表示期間終了日」
	,KESSAN_M  CHAR(2) --「決算月」
	,SEIKYU_KEITAI_KITEN_M  CHAR(2) --「請求形態起点月」
	,KEIYAKU_SHINKI_KBN  CHAR(1) NOT NULL --「契約新規区分」
	,SHOKAISAKI_TORIHIKISAKI_CD  CHAR(9) --「紹介先取引先コード」
	,SHIEN_JIGYOSHO_CD  CHAR(6) --「支援事業所コード」
	,SHEN_JGYSH_TNTSH_SHIN_NO  VARCHAR2(8) --「支援事業所担当者社員番号」
	,SHIEN_RANK_KBN  CHAR(1) NOT NULL --「支援ランク区分」
	,SIKY_DIK_IRIMT_TRHKSK_CD  CHAR(9) --「請求代行依頼元取引先コード」
	,KIYK_SIKY_DIK_IRISH_NO  CHAR(10) --「契約請求代行依頼書番号」
	,OYAKEIYAKU_FLG  CHAR(1) DEFAULT '0' NOT NULL --「親契約フラグ」
	,SHIHARAI_TANI_KBN  CHAR(1) NOT NULL --「支払単位区分」
	,JUCHU_SHUBETSU_KBN  CHAR(2) NOT NULL --「受注種別区分」
	,KEIYAKU_NENDO  CHAR(2) --「契約年度」
	,KEIYAKU_KBN  CHAR(1) NOT NULL --「契約区分」
	,RINJI_KEIYAKU_KBN  CHAR(1) NOT NULL --「臨時契約区分」
	,TAIKISHO_CD  CHAR(4) --「待機所コード」
	,TAIKISHO_SHOYO_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「待機所所要時間」
	,TAIKISHO_KYORI_M  NUMBER(12,3) DEFAULT '0' NOT NULL --「待機所距離メートル」
	,YAKAN_TAIKISHO_CD  CHAR(4) --「夜間待機所コード」
	,YAKAN_TAIKISHO_SHOYO_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「夜間待機所所要時間」
	,YAKAN_TAIKISHO_KYORI_M  NUMBER(12,3) DEFAULT '0' NOT NULL --「夜間待機所距離メートル」
	,KOJI_NAIYO  VARCHAR2(100) --「工事内容」
	,KOJI_YOBI_KBN  CHAR(1) --「工事曜日区分」
	,KOJI_JIKANTAI_KBN  CHAR(1) --「工事時間帯区分」
	,ANKEN_NM  VARCHAR2(100) --「案件名称」
	,SEIKYU_DAIKO_KANRI_NO  CHAR(13) --「請求代行管理番号」
	,JUCHU_JIGYOSHO_CD  CHAR(6) --「受注事業所コード」
	,KEIYAKU_JUCHU_TANTO_SHAIN_NO  VARCHAR2(8) --「契約受注担当社員番号」
	,JUCHU_TANTOSHA_DENWA_NO  VARCHAR2(20) --「受注担当者電話番号」
	,SONOTA_KEIYAKU_SHORI_KBN  CHAR(1) --「その他契約処理区分」
	,SONOTA_KEIYAKU_SHORI_BIKO  VARCHAR2(50) --「その他契約処理備考」
	,SNT_KIYK_JH_TRK_RIYU  VARCHAR2(100) --「その他契約情報登録理由」
	,KEIYAKUSHO_SAKUSEI_MAISU_KBN  CHAR(1) NOT NULL --「契約書作成枚数区分」
	,KEIYAKU_TEIKETSU_YMD  DATE --「契約締結年月日」
	,JUCHU_TANTOSHA_MEMO_NAIYO  VARCHAR2(100) --「受注担当者メモ内容」
	,NEBIKI_CD  CHAR(6) --「値引コード」
	,SHINSEI_SHONIN_NO  CHAR(14) --「申請承認番号」
	,SHMHN_JSSH_JGYSH_THIK_FLG  CHAR(1) DEFAULT '0' NOT NULL --「消耗品実施事業所手配可フラグ」
	,KEIYAKU_KOJIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「契約工事有フラグ」
	,KIYKBTS_BKKN_BNSK_KOMOKU_1  VARCHAR2(20) --「契約別物件分析項目１」
	,KIYKBTS_BKKN_BNSK_KOMOKU_2  VARCHAR2(20) --「契約別物件分析項目２」
	,MELTEC_KOJIKI_NO  CHAR(2) --「メルテック工事期番号」
	,MELTEC_KOJI_BUMON_NO  CHAR(5) --「メルテック工事部門番号」
	,MELTEC_KOJI_KEIYAKUSHU_NO  CHAR(5) --「メルテック工事契約種番号」
	,MELTEC_KOJI_TATEMONO_NO  CHAR(7) --「メルテック工事建物番号」
	,MELTEC_KOJI_HONSU_SN  CHAR(3) --「メルテック工事本数連番」
	,SONOTA_KAIYAKU_RIYU  VARCHAR2(20) --「その他解約理由」
	,CROSS_SELL_YO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「クロスセル要フラグ」
	,LEASE_KAISHA_SHIYOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「リース会社使用有フラグ」
	,KEIBI_TAISHOSAKI_TEMPOSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「警備対象先店舗数」
	,KEISO_SHOYO_JIKAN  NUMBER(9,0) DEFAULT '0' NOT NULL --「警送所要時間」
	,NYUSHUKKINARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「入出金有フラグ」
	,SAIKEIYAKU_JUCHU_KEIYAKU_NO  CHAR(15) --「再契約受注契約番号」
	,SAIKEIYAKUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「再契約有フラグ」
	,SAIKEIYAKU_GYOMU_KAISHI_YMD  DATE --「再契約業務開始年月日」
	,ROMU_TANKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「労務単価金額」
	,JUCHU_SHINSEI_MEMO_NAIYO  VARCHAR2(200) --「受注申請メモ内容」
	,JUCHU_SHINSEI_RIYU  VARCHAR2(400) --「受注申請理由」
	,SHOHIN_SERVICE_SHUBETSU_CD  CHAR(3) --「商品サービス種別コード」
	,BAIKYAKU_LEASE_KBN  CHAR(1) --「売却リース区分」
	,KEIYAKU_KAITEI_YOTEI_YMD  DATE --「契約改定予定年月日」
	,KEIYAKU_KOKAIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「契約更改有フラグ」
	,KEIYAKU_MANRYO_YOTEI_YMD  DATE --「契約満了予定年月日」
	,KEIYAKU_MANRYO_YOTEIBIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「契約満了予定日有フラグ」
	,TAIO_JIKO_NAIYO  VARCHAR2(500) --「対応事項内容」
	,TEKKYO_KOJI_KBN  CHAR(1) NOT NULL --「撤去工事区分」
	,KAITEI_YOTEI_YMD  DATE --「改定予定年月日」
	,KISHU_PACK_KBN  CHAR(1) NOT NULL --「機種パック区分」
	,MMK_KISHU_KBN  CHAR(1) NOT NULL --「ＭＭＫ機種区分」
	,ZANSON_KEIYAKU_TSUKISU  NUMBER(12,3) --「残存契約月数」
	,TOKUSHU_HOSHU_KOJIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「特殊補修工事有フラグ」
	,ISETSUARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「移設有フラグ」
	,SEKISAN_MEMO_NAIYO  VARCHAR2(300) --「積算メモ内容」
	,NOHIN_YOTEI_YMD  DATE --「納品予定年月日」
	,YOBO_JIKO_NAIYO  VARCHAR2(500) --「要望事項内容」
	,KAIYAKU_YOTEI_YMD  DATE --「解約予定年月日」
	,KAIYAKU_RIYU_CD  CHAR(2) --「解約理由コード」
	,KAIYAKUKIN_MENJO_RIYU  VARCHAR2(200) --「解約金免除理由」
	,KAIYAKUKIN_ZANSON_TSUKISU  NUMBER(9,0) DEFAULT '0' NOT NULL --「解約金残存月数」
	,KAIYAKUKIN_TOKKI_JIKO  VARCHAR2(100) --「解約金特記事項」
	,KAIYAKUKIN_BAI_RITSU  NUMBER(7,3) DEFAULT '0' NOT NULL --「解約金倍率」
	,KIYKKN_KISNSHK_HNK_RIYU  VARCHAR2(100) --「解約金計算式変更理由」
	,KAIYAKUKIN_SETTEI_NAIYO  VARCHAR2(100) --「解約金設定内容」
	,SEIKYUSHO_SHURYO_D  CHAR(2) --「請求書終了日」
	,SEIKYUSHO_KAISHI_D  CHAR(2) --「請求書開始日」
	,SEIKYU_KAISHI_M  CHAR(2) --「請求開始月」
	,TEKKYO_KOJIARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「撤去工事有フラグ」
	,KOSHO_SAGYOARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「高所作業有フラグ」
	,KEIYAKU_YM_KBN  CHAR(1) --「契約年月区分」
	,SHOHIZEI_KBN  CHAR(1) NOT NULL --「消費税区分」
	,HIKAZEI_RIYU  VARCHAR2(60) --「非課税理由」
	,TORIHIKISAKI_SHIHARAI_JOHO_CD  CHAR(4) --「取引先支払情報コード」
	,KEIYAKU_TOROKUSHA_KAISHA_CD  CHAR(5) --「契約登録者会社コード」
	,KEIYAKU_TOROKUSHA_SHAIN_NO  VARCHAR2(8) --「契約登録者社員番号」
	,KEIYAKU_TOROKU_DT  TIMESTAMP --「契約登録日時」
	,KEIYAKU_KOSHINSHA_KAISHA_CD  CHAR(5) --「契約更新者会社コード」
	,KEIYAKU_KOSHINSHA_SHAIN_NO  VARCHAR2(8) --「契約更新者社員番号」
	,KEIYAKU_KOSHIN_DT  TIMESTAMP --「契約更新日時」
	,KEIYAKUSAKI_TANTOSHA_NM  VARCHAR2(60) --「契約先担当者氏名」
	,KEIYAKUSAKI_DENWA_NO  VARCHAR2(20) --「契約先電話番号」
	,JUCHU_SHORI_KBN  CHAR(2) NOT NULL --「受注処理区分」
	,KEIYAKUSHO_KAISHU_YOTEI_YMD  DATE --「契約書回収予定年月日」
	,KEIYAKUSHO_KAISHU_YMD  DATE --「契約書回収年月日」
	,KEIYAKU_TOROKU_GAMEN_ID  CHAR(15) --「契約登録画面ＩＤ」
	,SOLUTION_CD_2  CHAR(3) --「ソリューションコード２」
	,SOLUTION_CD_3  CHAR(3) --「ソリューションコード３」
	,SOLUTION_CD_4  CHAR(3) --「ソリューションコード４」
	,SOLUTION_CD_5  CHAR(3) --「ソリューションコード５」
	,SOLUTION_CD  CHAR(3) --「ソリューションコード」
	,HKTG_MOTO_JUCHU_KEIYAKU_NO  CHAR(15) --「引継元受注契約番号」
	,KEIYAKU_SAISHIN_FLG  CHAR(1) DEFAULT '0' NOT NULL --「契約最新フラグ」
	,KAITEIMAE_JUCHU_KEIYAKU_NO  CHAR(15) --「改定前受注契約番号」
	,KEIYAKU_KENSAKU_TAISHO_FLG  CHAR(1) DEFAULT '0' NOT NULL --「契約検索表示対象フラグ」
	,KITIME_JUCHU_KEIYAKU_HENKO_NO  CHAR(6) --「改定前受注契約変更番号」
	,GYOMU_ITAKU_SERVICE_CD  CHAR(3) --「業務委託サービスコード」
	,KEIYAKU_BUNRUI_KBN  CHAR(1) NOT NULL --「契約分類区分」
	,JUCHU_SHINSEI_NO  CHAR(20) --「受注申請番号」
	,JUCHU_SHINSEI_MEISAI_NO  CHAR(7) --「受注申請明細番号」
	,JCH_KIYK_HNK_RRK_MSKSI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「受注契約変更履歴未作成フラグ」
	,HENSHU_KOMOKU_SHUBETSU_KBN  CHAR(1) NOT NULL --「編集項目種別区分」
	,TEKKYO_KOJI_YOTEI_D  DATE --「撤去工事予定日」
	,ANKEN_HANEI_ZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「案件反映済フラグ」
	,SHOHI_ZEIRITSU_CD  CHAR(2) --「消費税率コード」
	,NENGAKU_SETTEI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「年額設定フラグ」
	,FUKUSU_KEIYAKUSAKI_SETTEI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「複数契約先設定フラグ」
	,SHHRI_JKN_NBKAR_FLG  CHAR(1) DEFAULT '0' NOT NULL --「支払条件値引有フラグ」
	,MITSUMORISHO_TEIAN_NAIYO  VARCHAR2(100) --「見積書提案内容」
	,MTSMRSH_YUKO_KIGEN_NISSU  NUMBER(9,0) DEFAULT '0' NOT NULL --「見積書有効期限日数」
	,MITSUMORISHO_HSK_STSMI_NAIYO  VARCHAR2(500) --「見積書補足説明内容」
	,URIAGE_KOGAKU_JUCHU_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上高額受注金額」
	,URIAGE_YOSHIN_JOGEN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「売上与信上限金額」
	,GCJIGYOSHO_CD  CHAR(6) --「ＧＣ事業所コード」
	,JUCHU_SHONIN_DT  TIMESTAMP --「受注承認日時」
	,JUCHU_SHINSEI_DT  TIMESTAMP --「受注申請日時」
	,JUCHU_TANTO_JIGYOSHO_CD  CHAR(6) --「受注担当者事業所コード」
	,SEKISAN_KANRYO_DT  TIMESTAMP --「積算完了日時」
	,BISH_GNDGK_HYJN_AMT_NAIYO_1  VARCHAR2(30) --「賠償限度額標準金額内容１」
	,KNSH_KMK_KOJI_GOKEI_GENKA_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「監視項目加算合計原価金額」
	,KNSH_KMK_KOJI_GOKEI_HYOJUN_AMT  NUMBER(13,0) DEFAULT '0' NOT NULL --「監視項目加算合計標準金額」
	,JIDO_KOSHINARI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「自動更新有フラグ」
	,NB_KIGYO_CD  CHAR(2) --「ＮＢ企業コード」
	,NB_TEMPO_NO  CHAR(6) --「ＮＢ店舗番号」
	,SHIHARAI_JOKEN_NEBIKI_CD  CHAR(6) --「支払条件値引コード」
	,KEIYAKU_JOHO_SENI_ZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「契約情報遷移済フラグ」
	,MITSUMORISHO_SAKUSEIZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「見積書作成済フラグ」
	,SKSN_TIJ_KKK_TOROKU_ZUMI_FLG  CHAR(1) DEFAULT '0' NOT NULL --「積算提示価格登録済フラグ」
	,HIMOZUKE_JUCHU_GROUP_NO  CHAR(15) --「紐付受注契約番号」
	,PLAN_TEIAN_FLG  CHAR(1) DEFAULT '1' NOT NULL --「プラン提案フラグ」
	,ANKN_HNEI_SHHN_SRVC_PLAN_KBN  CHAR(1) DEFAULT '0' NOT NULL --「案件反映商品サービスプラン区分」
	,TEKKYO_TAISHO_KBN  CHAR(1) DEFAULT '0' NOT NULL --「撤去対象区分」
	,TAIKISHO_NM  VARCHAR2(40) --「待機所名称」
	,TIKSH_TNYRYK_KTSG_JUSHO  VARCHAR2(200) --「待機所手入力結合住所」
	,YAKAN_TAIKISHO_NM  VARCHAR2(40) --「夜間待機所名称」
	,YKN_TIKSH_TNYRYK_KTSG_JUSHO  VARCHAR2(200) --「夜間待機所手入力結合住所」
	,GC_JIGYOSHO_NM  VARCHAR2(200) --「ＧＣ事業所名称」
	,GC_JGYSH_KTSG_JUSHO  VARCHAR2(200) --「ＧＣ事業所結合住所」
	,SHURI_CARD_NO  CHAR(8) --「修理カード番号」
	,REGST_TMSTMP  TIMESTAMP --「登録タイムスタンプ」
	,REGSTR_CO_CD  CHAR(5) --「登録者会社コード」
	,REGSTR_SOSHIKI_CD  VARCHAR2(6) --「登録者組織コード」
	,REGSTR_EMP_NO  VARCHAR2(8) --「登録者社員番号」
	,REGST_GAMEN_ID  CHAR(15) --「登録画面ＩＤ」
	,REGST_PGM_ID  VARCHAR2(255) --「登録プログラムＩＤ」
	,UPD_TMSTMP  TIMESTAMP --「更新タイムスタンプ」
	,UPDTR_CO_CD  CHAR(5) --「更新者会社コード」
	,UPDTR_SOSHIKI_CD  VARCHAR2(6) --「更新者組織コード」
	,UPDTR_EMP_NO  VARCHAR2(8) --「更新者社員番号」
	,UPD_GAMEN_ID  CHAR(15) --「更新画面ＩＤ」
	,UPD_PGM_ID  VARCHAR2(255) --「更新プログラムＩＤ」
	,CONSTRAINT ED0517T_PK PRIMARY KEY(
	 JUCHU_KEIYAKU_NO
	,  JUCHU_KEIYAKU_HENKO_NO
	,  KAISHA_CD
	)
)
/

-- テーブルのコメント作成
COMMENT ON TABLE ED0517T_TBL IS '受注テーブル'
/

COMMENT ON COLUMN ED0517T_TBL.KAISHA_CD IS '会社コード'
/
COMMENT ON COLUMN ED0517T_TBL.JUCHU_KEIYAKU_NO IS '受注契約番号'
/
COMMENT ON COLUMN ED0517T_TBL.JUCHU_KEIYAKU_HENKO_NO IS '受注契約変更番号'
/
COMMENT ON COLUMN ED0517T_TBL.ANKEN_NO IS '案件番号'
/
COMMENT ON COLUMN ED0517T_TBL.ANKEN_SHOHIN_SN IS '案件商品連番'
/
COMMENT ON COLUMN ED0517T_TBL.ANKEN_TAISHOSAKI_SN IS '案件対象先連番'
/
COMMENT ON COLUMN ED0517T_TBL.KEIBI_SHINDAN_NO IS '警備診断番号'
/
COMMENT ON COLUMN ED0517T_TBL.KOJI_SHIJISHO_NO IS '工事指示書番号'
/
COMMENT ON COLUMN ED0517T_TBL.SEKISAN_NO IS '積算番号'
/
COMMENT ON COLUMN ED0517T_TBL.SHOSAI_SEKISAN_NO IS '詳細積算番号'
/
COMMENT ON COLUMN ED0517T_TBL.MITSUMORI_NO IS '見積番号'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKUSHO_NO IS '契約書番号'
/
COMMENT ON COLUMN ED0517T_TBL.MITSUMORISHO_NO IS '見積書番号'
/
COMMENT ON COLUMN ED0517T_TBL.SHOHIN_SERVICE_CD IS '商品サービスコード'
/
COMMENT ON COLUMN ED0517T_TBL.SEKISAN_STATUS_KBN IS '積算ステータス区分'
/
COMMENT ON COLUMN ED0517T_TBL.SHOSAI_SEKISAN_IRAI_STATUS_KBN IS '詳細積算依頼ステータス区分'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_STATUS_KBN IS '契約ステータス区分'
/
COMMENT ON COLUMN ED0517T_TBL.JIGYO_SEGMENT_CD IS '事業セグメントコード'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_CHOKI_RINJI_KBN IS '契約長期臨時区分'
/
COMMENT ON COLUMN ED0517T_TBL.DENKEI_NO IS '電計番号'
/
COMMENT ON COLUMN ED0517T_TBL.KANREN_JUCHU_KEIYAKU_NO IS '関連受注契約番号'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_YOTEI_YMD IS '契約予定年月日'
/
COMMENT ON COLUMN ED0517T_TBL.GYOMU_KAISHI_YOTEI_YMD IS '業務開始予定年月日'
/
COMMENT ON COLUMN ED0517T_TBL.GYOMU_MANRYO_YOTEI_YMD IS '業務満了予定年月日'
/
COMMENT ON COLUMN ED0517T_TBL.GYOMU_KAISHI_YMD IS '業務開始年月日'
/
COMMENT ON COLUMN ED0517T_TBL.GYOMU_SHURYO_YMD IS '業務終了年月日'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_KOSHIN_TSUKISU IS '契約更新月数'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_KOSHIN_NENSU IS '契約更新年数'
/
COMMENT ON COLUMN ED0517T_TBL.KIHON_KYOTSU_KEIYAKU_NO IS '基本共通契約番号'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKUSAKI_TORIHIKISAKI_CD IS '契約先取引先コード'
/
COMMENT ON COLUMN ED0517T_TBL.KIYKSK_TRHKSK_BSH_CD IS '契約先取引先部署コード'
/
COMMENT ON COLUMN ED0517T_TBL.TORIHIKISAKI_CD IS '取引先コード'
/
COMMENT ON COLUMN ED0517T_TBL.TORIHIKISAKI_BUSHO_CD IS '取引先部署コード'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_TSUKISU IS '契約月数'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_SHURYOBI_SETTEIARI_FLG IS '契約終了日設定有フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_KOSHIN_TSUCHI_KBN IS '契約更新通知区分'
/
COMMENT ON COLUMN ED0517T_TBL.KAIYAKUKIN_SETTEI_KBN IS '解約金設定区分'
/
COMMENT ON COLUMN ED0517T_TBL.KAIYAKUKINARI_FLG IS '解約金有フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.KAIYAKUKIN_KEISANSHIKI_CD IS '解約金計算式コード'
/
COMMENT ON COLUMN ED0517T_TBL.KAIYAKUKIN_KEISU IS '解約金係数'
/
COMMENT ON COLUMN ED0517T_TBL.KAIYAKUKIN_HENKO_RIYU IS '解約金変更理由'
/
COMMENT ON COLUMN ED0517T_TBL.KAIYAKUKIN_TOKKI_NAIYO IS '解約金特記内容'
/
COMMENT ON COLUMN ED0517T_TBL.SEIKYU_KEITAI_KBN IS '請求形態区分'
/
COMMENT ON COLUMN ED0517T_TBL.SHIHARAI_JOKEN_KBN IS '支払条件区分'
/
COMMENT ON COLUMN ED0517T_TBL.SHIHARAI_D IS '支払日'
/
COMMENT ON COLUMN ED0517T_TBL.KOKYAKU_SHIHARAI_HOHO_KBN IS '顧客支払方法区分'
/
COMMENT ON COLUMN ED0517T_TBL.SEIKYUSHO_HYOJI_KIKAN_KAISHI_D IS '請求書表示期間開始日'
/
COMMENT ON COLUMN ED0517T_TBL.SEIKYUSHO_HYOJI_KIKAN_SHURYO_D IS '請求書表示期間終了日'
/
COMMENT ON COLUMN ED0517T_TBL.KESSAN_M IS '決算月'
/
COMMENT ON COLUMN ED0517T_TBL.SEIKYU_KEITAI_KITEN_M IS '請求形態起点月'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_SHINKI_KBN IS '契約新規区分'
/
COMMENT ON COLUMN ED0517T_TBL.SHOKAISAKI_TORIHIKISAKI_CD IS '紹介先取引先コード'
/
COMMENT ON COLUMN ED0517T_TBL.SHIEN_JIGYOSHO_CD IS '支援事業所コード'
/
COMMENT ON COLUMN ED0517T_TBL.SHEN_JGYSH_TNTSH_SHIN_NO IS '支援事業所担当者社員番号'
/
COMMENT ON COLUMN ED0517T_TBL.SHIEN_RANK_KBN IS '支援ランク区分'
/
COMMENT ON COLUMN ED0517T_TBL.SIKY_DIK_IRIMT_TRHKSK_CD IS '請求代行依頼元取引先コード'
/
COMMENT ON COLUMN ED0517T_TBL.KIYK_SIKY_DIK_IRISH_NO IS '契約請求代行依頼書番号'
/
COMMENT ON COLUMN ED0517T_TBL.OYAKEIYAKU_FLG IS '親契約フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.SHIHARAI_TANI_KBN IS '支払単位区分'
/
COMMENT ON COLUMN ED0517T_TBL.JUCHU_SHUBETSU_KBN IS '受注種別区分'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_NENDO IS '契約年度'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_KBN IS '契約区分'
/
COMMENT ON COLUMN ED0517T_TBL.RINJI_KEIYAKU_KBN IS '臨時契約区分'
/
COMMENT ON COLUMN ED0517T_TBL.TAIKISHO_CD IS '待機所コード'
/
COMMENT ON COLUMN ED0517T_TBL.TAIKISHO_SHOYO_JIKAN IS '待機所所要時間'
/
COMMENT ON COLUMN ED0517T_TBL.TAIKISHO_KYORI_M IS '待機所距離メートル'
/
COMMENT ON COLUMN ED0517T_TBL.YAKAN_TAIKISHO_CD IS '夜間待機所コード'
/
COMMENT ON COLUMN ED0517T_TBL.YAKAN_TAIKISHO_SHOYO_JIKAN IS '夜間待機所所要時間'
/
COMMENT ON COLUMN ED0517T_TBL.YAKAN_TAIKISHO_KYORI_M IS '夜間待機所距離メートル'
/
COMMENT ON COLUMN ED0517T_TBL.KOJI_NAIYO IS '工事内容'
/
COMMENT ON COLUMN ED0517T_TBL.KOJI_YOBI_KBN IS '工事曜日区分'
/
COMMENT ON COLUMN ED0517T_TBL.KOJI_JIKANTAI_KBN IS '工事時間帯区分'
/
COMMENT ON COLUMN ED0517T_TBL.ANKEN_NM IS '案件名称'
/
COMMENT ON COLUMN ED0517T_TBL.SEIKYU_DAIKO_KANRI_NO IS '請求代行管理番号'
/
COMMENT ON COLUMN ED0517T_TBL.JUCHU_JIGYOSHO_CD IS '受注事業所コード'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_JUCHU_TANTO_SHAIN_NO IS '契約受注担当社員番号'
/
COMMENT ON COLUMN ED0517T_TBL.JUCHU_TANTOSHA_DENWA_NO IS '受注担当者電話番号'
/
COMMENT ON COLUMN ED0517T_TBL.SONOTA_KEIYAKU_SHORI_KBN IS 'その他契約処理区分'
/
COMMENT ON COLUMN ED0517T_TBL.SONOTA_KEIYAKU_SHORI_BIKO IS 'その他契約処理備考'
/
COMMENT ON COLUMN ED0517T_TBL.SNT_KIYK_JH_TRK_RIYU IS 'その他契約情報登録理由'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKUSHO_SAKUSEI_MAISU_KBN IS '契約書作成枚数区分'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_TEIKETSU_YMD IS '契約締結年月日'
/
COMMENT ON COLUMN ED0517T_TBL.JUCHU_TANTOSHA_MEMO_NAIYO IS '受注担当者メモ内容'
/
COMMENT ON COLUMN ED0517T_TBL.NEBIKI_CD IS '値引コード'
/
COMMENT ON COLUMN ED0517T_TBL.SHINSEI_SHONIN_NO IS '申請承認番号'
/
COMMENT ON COLUMN ED0517T_TBL.SHMHN_JSSH_JGYSH_THIK_FLG IS '消耗品実施事業所手配可フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_KOJIARI_FLG IS '契約工事有フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.KIYKBTS_BKKN_BNSK_KOMOKU_1 IS '契約別物件分析項目１'
/
COMMENT ON COLUMN ED0517T_TBL.KIYKBTS_BKKN_BNSK_KOMOKU_2 IS '契約別物件分析項目２'
/
COMMENT ON COLUMN ED0517T_TBL.MELTEC_KOJIKI_NO IS 'メルテック工事期番号'
/
COMMENT ON COLUMN ED0517T_TBL.MELTEC_KOJI_BUMON_NO IS 'メルテック工事部門番号'
/
COMMENT ON COLUMN ED0517T_TBL.MELTEC_KOJI_KEIYAKUSHU_NO IS 'メルテック工事契約種番号'
/
COMMENT ON COLUMN ED0517T_TBL.MELTEC_KOJI_TATEMONO_NO IS 'メルテック工事建物番号'
/
COMMENT ON COLUMN ED0517T_TBL.MELTEC_KOJI_HONSU_SN IS 'メルテック工事本数連番'
/
COMMENT ON COLUMN ED0517T_TBL.SONOTA_KAIYAKU_RIYU IS 'その他解約理由'
/
COMMENT ON COLUMN ED0517T_TBL.CROSS_SELL_YO_FLG IS 'クロスセル要フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.LEASE_KAISHA_SHIYOARI_FLG IS 'リース会社使用有フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.KEIBI_TAISHOSAKI_TEMPOSU IS '警備対象先店舗数'
/
COMMENT ON COLUMN ED0517T_TBL.KEISO_SHOYO_JIKAN IS '警送所要時間'
/
COMMENT ON COLUMN ED0517T_TBL.NYUSHUKKINARI_FLG IS '入出金有フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.SAIKEIYAKU_JUCHU_KEIYAKU_NO IS '再契約受注契約番号'
/
COMMENT ON COLUMN ED0517T_TBL.SAIKEIYAKUARI_FLG IS '再契約有フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.SAIKEIYAKU_GYOMU_KAISHI_YMD IS '再契約業務開始年月日'
/
COMMENT ON COLUMN ED0517T_TBL.ROMU_TANKA_AMT IS '労務単価金額'
/
COMMENT ON COLUMN ED0517T_TBL.JUCHU_SHINSEI_MEMO_NAIYO IS '受注申請メモ内容'
/
COMMENT ON COLUMN ED0517T_TBL.JUCHU_SHINSEI_RIYU IS '受注申請理由'
/
COMMENT ON COLUMN ED0517T_TBL.SHOHIN_SERVICE_SHUBETSU_CD IS '商品サービス種別コード'
/
COMMENT ON COLUMN ED0517T_TBL.BAIKYAKU_LEASE_KBN IS '売却リース区分'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_KAITEI_YOTEI_YMD IS '契約改定予定年月日'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_KOKAIARI_FLG IS '契約更改有フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_MANRYO_YOTEI_YMD IS '契約満了予定年月日'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_MANRYO_YOTEIBIARI_FLG IS '契約満了予定日有フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.TAIO_JIKO_NAIYO IS '対応事項内容'
/
COMMENT ON COLUMN ED0517T_TBL.TEKKYO_KOJI_KBN IS '撤去工事区分'
/
COMMENT ON COLUMN ED0517T_TBL.KAITEI_YOTEI_YMD IS '改定予定年月日'
/
COMMENT ON COLUMN ED0517T_TBL.KISHU_PACK_KBN IS '機種パック区分'
/
COMMENT ON COLUMN ED0517T_TBL.MMK_KISHU_KBN IS 'ＭＭＫ機種区分'
/
COMMENT ON COLUMN ED0517T_TBL.ZANSON_KEIYAKU_TSUKISU IS '残存契約月数'
/
COMMENT ON COLUMN ED0517T_TBL.TOKUSHU_HOSHU_KOJIARI_FLG IS '特殊補修工事有フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.ISETSUARI_FLG IS '移設有フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.SEKISAN_MEMO_NAIYO IS '積算メモ内容'
/
COMMENT ON COLUMN ED0517T_TBL.NOHIN_YOTEI_YMD IS '納品予定年月日'
/
COMMENT ON COLUMN ED0517T_TBL.YOBO_JIKO_NAIYO IS '要望事項内容'
/
COMMENT ON COLUMN ED0517T_TBL.KAIYAKU_YOTEI_YMD IS '解約予定年月日'
/
COMMENT ON COLUMN ED0517T_TBL.KAIYAKU_RIYU_CD IS '解約理由コード'
/
COMMENT ON COLUMN ED0517T_TBL.KAIYAKUKIN_MENJO_RIYU IS '解約金免除理由'
/
COMMENT ON COLUMN ED0517T_TBL.KAIYAKUKIN_ZANSON_TSUKISU IS '解約金残存月数'
/
COMMENT ON COLUMN ED0517T_TBL.KAIYAKUKIN_TOKKI_JIKO IS '解約金特記事項'
/
COMMENT ON COLUMN ED0517T_TBL.KAIYAKUKIN_BAI_RITSU IS '解約金倍率'
/
COMMENT ON COLUMN ED0517T_TBL.KIYKKN_KISNSHK_HNK_RIYU IS '解約金計算式変更理由'
/
COMMENT ON COLUMN ED0517T_TBL.KAIYAKUKIN_SETTEI_NAIYO IS '解約金設定内容'
/
COMMENT ON COLUMN ED0517T_TBL.SEIKYUSHO_SHURYO_D IS '請求書終了日'
/
COMMENT ON COLUMN ED0517T_TBL.SEIKYUSHO_KAISHI_D IS '請求書開始日'
/
COMMENT ON COLUMN ED0517T_TBL.SEIKYU_KAISHI_M IS '請求開始月'
/
COMMENT ON COLUMN ED0517T_TBL.TEKKYO_KOJIARI_FLG IS '撤去工事有フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.KOSHO_SAGYOARI_FLG IS '高所作業有フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_YM_KBN IS '契約年月区分'
/
COMMENT ON COLUMN ED0517T_TBL.SHOHIZEI_KBN IS '消費税区分'
/
COMMENT ON COLUMN ED0517T_TBL.HIKAZEI_RIYU IS '非課税理由'
/
COMMENT ON COLUMN ED0517T_TBL.TORIHIKISAKI_SHIHARAI_JOHO_CD IS '取引先支払情報コード'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_TOROKUSHA_KAISHA_CD IS '契約登録者会社コード'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_TOROKUSHA_SHAIN_NO IS '契約登録者社員番号'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_TOROKU_DT IS '契約登録日時'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_KOSHINSHA_KAISHA_CD IS '契約更新者会社コード'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_KOSHINSHA_SHAIN_NO IS '契約更新者社員番号'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_KOSHIN_DT IS '契約更新日時'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKUSAKI_TANTOSHA_NM IS '契約先担当者氏名'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKUSAKI_DENWA_NO IS '契約先電話番号'
/
COMMENT ON COLUMN ED0517T_TBL.JUCHU_SHORI_KBN IS '受注処理区分'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKUSHO_KAISHU_YOTEI_YMD IS '契約書回収予定年月日'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKUSHO_KAISHU_YMD IS '契約書回収年月日'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_TOROKU_GAMEN_ID IS '契約登録画面ＩＤ'
/
COMMENT ON COLUMN ED0517T_TBL.SOLUTION_CD_2 IS 'ソリューションコード２'
/
COMMENT ON COLUMN ED0517T_TBL.SOLUTION_CD_3 IS 'ソリューションコード３'
/
COMMENT ON COLUMN ED0517T_TBL.SOLUTION_CD_4 IS 'ソリューションコード４'
/
COMMENT ON COLUMN ED0517T_TBL.SOLUTION_CD_5 IS 'ソリューションコード５'
/
COMMENT ON COLUMN ED0517T_TBL.SOLUTION_CD IS 'ソリューションコード'
/
COMMENT ON COLUMN ED0517T_TBL.HKTG_MOTO_JUCHU_KEIYAKU_NO IS '引継元受注契約番号'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_SAISHIN_FLG IS '契約最新フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.KAITEIMAE_JUCHU_KEIYAKU_NO IS '改定前受注契約番号'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_KENSAKU_TAISHO_FLG IS '契約検索表示対象フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.KITIME_JUCHU_KEIYAKU_HENKO_NO IS '改定前受注契約変更番号'
/
COMMENT ON COLUMN ED0517T_TBL.GYOMU_ITAKU_SERVICE_CD IS '業務委託サービスコード'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_BUNRUI_KBN IS '契約分類区分'
/
COMMENT ON COLUMN ED0517T_TBL.JUCHU_SHINSEI_NO IS '受注申請番号'
/
COMMENT ON COLUMN ED0517T_TBL.JUCHU_SHINSEI_MEISAI_NO IS '受注申請明細番号'
/
COMMENT ON COLUMN ED0517T_TBL.JCH_KIYK_HNK_RRK_MSKSI_FLG IS '受注契約変更履歴未作成フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.HENSHU_KOMOKU_SHUBETSU_KBN IS '編集項目種別区分'
/
COMMENT ON COLUMN ED0517T_TBL.TEKKYO_KOJI_YOTEI_D IS '撤去工事予定日'
/
COMMENT ON COLUMN ED0517T_TBL.ANKEN_HANEI_ZUMI_FLG IS '案件反映済フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.SHOHI_ZEIRITSU_CD IS '消費税率コード'
/
COMMENT ON COLUMN ED0517T_TBL.NENGAKU_SETTEI_FLG IS '年額設定フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.FUKUSU_KEIYAKUSAKI_SETTEI_FLG IS '複数契約先設定フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.SHHRI_JKN_NBKAR_FLG IS '支払条件値引有フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.MITSUMORISHO_TEIAN_NAIYO IS '見積書提案内容'
/
COMMENT ON COLUMN ED0517T_TBL.MTSMRSH_YUKO_KIGEN_NISSU IS '見積書有効期限日数'
/
COMMENT ON COLUMN ED0517T_TBL.MITSUMORISHO_HSK_STSMI_NAIYO IS '見積書補足説明内容'
/
COMMENT ON COLUMN ED0517T_TBL.URIAGE_KOGAKU_JUCHU_AMT IS '売上高額受注金額'
/
COMMENT ON COLUMN ED0517T_TBL.URIAGE_YOSHIN_JOGEN_AMT IS '売上与信上限金額'
/
COMMENT ON COLUMN ED0517T_TBL.GCJIGYOSHO_CD IS 'ＧＣ事業所コード'
/
COMMENT ON COLUMN ED0517T_TBL.JUCHU_SHONIN_DT IS '受注承認日時'
/
COMMENT ON COLUMN ED0517T_TBL.JUCHU_SHINSEI_DT IS '受注申請日時'
/
COMMENT ON COLUMN ED0517T_TBL.JUCHU_TANTO_JIGYOSHO_CD IS '受注担当者事業所コード'
/
COMMENT ON COLUMN ED0517T_TBL.SEKISAN_KANRYO_DT IS '積算完了日時'
/
COMMENT ON COLUMN ED0517T_TBL.BISH_GNDGK_HYJN_AMT_NAIYO_1 IS '賠償限度額標準金額内容１'
/
COMMENT ON COLUMN ED0517T_TBL.KNSH_KMK_KOJI_GOKEI_GENKA_AMT IS '監視項目加算合計原価金額'
/
COMMENT ON COLUMN ED0517T_TBL.KNSH_KMK_KOJI_GOKEI_HYOJUN_AMT IS '監視項目加算合計標準金額'
/
COMMENT ON COLUMN ED0517T_TBL.JIDO_KOSHINARI_FLG IS '自動更新有フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.NB_KIGYO_CD IS 'ＮＢ企業コード'
/
COMMENT ON COLUMN ED0517T_TBL.NB_TEMPO_NO IS 'ＮＢ店舗番号'
/
COMMENT ON COLUMN ED0517T_TBL.SHIHARAI_JOKEN_NEBIKI_CD IS '支払条件値引コード'
/
COMMENT ON COLUMN ED0517T_TBL.KEIYAKU_JOHO_SENI_ZUMI_FLG IS '契約情報遷移済フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.MITSUMORISHO_SAKUSEIZUMI_FLG IS '見積書作成済フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.SKSN_TIJ_KKK_TOROKU_ZUMI_FLG IS '積算提示価格登録済フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.HIMOZUKE_JUCHU_GROUP_NO IS '紐付受注契約番号'
/
COMMENT ON COLUMN ED0517T_TBL.PLAN_TEIAN_FLG IS 'プラン提案フラグ'
/
COMMENT ON COLUMN ED0517T_TBL.ANKN_HNEI_SHHN_SRVC_PLAN_KBN IS '案件反映商品サービスプラン区分'
/
COMMENT ON COLUMN ED0517T_TBL.TEKKYO_TAISHO_KBN IS '撤去対象区分'
/
COMMENT ON COLUMN ED0517T_TBL.TAIKISHO_NM IS '待機所名称'
/
COMMENT ON COLUMN ED0517T_TBL.TIKSH_TNYRYK_KTSG_JUSHO IS '待機所手入力結合住所'
/
COMMENT ON COLUMN ED0517T_TBL.YAKAN_TAIKISHO_NM IS '夜間待機所名称'
/
COMMENT ON COLUMN ED0517T_TBL.YKN_TIKSH_TNYRYK_KTSG_JUSHO IS '夜間待機所手入力結合住所'
/
COMMENT ON COLUMN ED0517T_TBL.GC_JIGYOSHO_NM IS 'ＧＣ事業所名称'
/
COMMENT ON COLUMN ED0517T_TBL.GC_JGYSH_KTSG_JUSHO IS 'ＧＣ事業所結合住所'
/
COMMENT ON COLUMN ED0517T_TBL.SHURI_CARD_NO IS '修理カード番号'
/
COMMENT ON COLUMN ED0517T_TBL.REGST_TMSTMP IS '登録タイムスタンプ'
/
COMMENT ON COLUMN ED0517T_TBL.REGSTR_CO_CD IS '登録者会社コード'
/
COMMENT ON COLUMN ED0517T_TBL.REGSTR_SOSHIKI_CD IS '登録者組織コード'
/
COMMENT ON COLUMN ED0517T_TBL.REGSTR_EMP_NO IS '登録者社員番号'
/
COMMENT ON COLUMN ED0517T_TBL.REGST_GAMEN_ID IS '登録画面ＩＤ'
/
COMMENT ON COLUMN ED0517T_TBL.REGST_PGM_ID IS '登録プログラムＩＤ'
/
COMMENT ON COLUMN ED0517T_TBL.UPD_TMSTMP IS '更新タイムスタンプ'
/
COMMENT ON COLUMN ED0517T_TBL.UPDTR_CO_CD IS '更新者会社コード'
/
COMMENT ON COLUMN ED0517T_TBL.UPDTR_SOSHIKI_CD IS '更新者組織コード'
/
COMMENT ON COLUMN ED0517T_TBL.UPDTR_EMP_NO IS '更新者社員番号'
/
COMMENT ON COLUMN ED0517T_TBL.UPD_GAMEN_ID IS '更新画面ＩＤ'
/
COMMENT ON COLUMN ED0517T_TBL.UPD_PGM_ID IS '更新プログラムＩＤ'
/
